### ISSUE TITLE
Volume snapshot created by lxc not shown in volume show

### ISSUE THREAD

**Issue by markrattray** [lxc/lxd#10000]
Hi... low priority...

Ubuntu Server 20.04 AMD64 LXD Snap 4.23

TEST: Added a second disk named `container65disk2` to an Ubuntu 20.04 container named `container65` on LXD managed ZFS pools in a 3 node cluster. As far as I've tested all is good except I cannot list snapshots using `lxc storage volume show/info` even though they were taken using the command `lxc storage volume snapshot lxd_local_disk1 container65disk2 1215z`

```
remmy@lxdhost3:~$ lxc storage volume show lxd_local_disk1 container65disk2
config:
  volatile.idmap.last: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
description: ""
name: container65disk2
type: custom
used_by:
- /1.0/instances/container65
location: lxdhost3.remmy.net
content_type: filesystem
```

So the only way I've found the snapshot is to use the `zfs` tool, which shows the `1215z` snapshot:

```
remmy@lxdhost3:~$ sudo zfs list -t snapshot
NAME                                                                                                               USED  AVAIL     REFER  MOUNTPOINT
lxd_local_disk0/deleted/images/2d786b1dcf52de3d262429187b8d28a0b82dbeb2f1f4ba164543d8b542075b7b@readonly           1K      -     24.5K  -
lxd_local_disk0/deleted/images/2d786b1dcf52de3d262429187b8d28a0b82dbeb2f1f4ba164543d8b542075b7b.block@readonly     1K      -     11.8G  -
lxd_local_disk0/images/017d8572a250a681aec28aa59da770d95db2b79ba156dd590d5f250d0df974ea@readonly                   0B      -      571M  -
lxd_local_disk0/images/19f7efb7274e929538bea1785f9f3e34100c148e819f24feacc99b4909e7b9db@readonly                   0B      -      228M  -
lxd_local_disk0/images/44650bc10c092105a5695a240307f518b9f5a6f3a6c8094f340d663331191e48@readonly                   1K      -      571M  -
lxd_local_disk1/custom/default_container65disk2@snapshot-1215z                                                            14K      -       25K  -
```

It would be nice if `lxc storage volume show` produced the same nice snapshot output as `lxc info`:
```
remmy@lxdhost3:~$ lxc info container65
        .....
        inet6: ::1/128 (local)

Snapshots:
+-------+----------------------+------------+----------+
| NAME  |       TAKEN AT       | EXPIRES AT | STATEFUL |
+-------+----------------------+------------+----------+
| 1334z | 2022/03/04 13:34 UTC |            | NO       |
+-------+----------------------+------------+----------+
```
Another thing it would be _nice_ if there was just one `info` or `show` command or some correlation across commands, e.g.:

- instance does not have `show`, but has `info`
- volume has `show` and `info`, but `show` for volume is more like `info` for instance

Thanks
