### ISSUE TITLE
When using pylxd to create and modify instances its possible to create a broken LXD instance

### ISSUE THREAD

**Issue by Dweller** [lxc/lxd#10081]
# Required information

 *Red Hat Enterprise Linux release 8.5 (Ootpa)
 
 *LXD 4.24
 * python 3.6.8
 * pylxd 2.3.1

# Issue description

I've discovered in instance where if I create a new LXD instance via pylxd and then modify it the new instance is left in a unusable state.  e.g. connecting to it via lxd exec gives a 'Error: value too large for defined data type' error message.  The instance isn't running and when I force delete it the veth device that was assigned is left orphaned on the box.

Also be warned that the orphaned veth device on my box then adopted the device and created a new default route to lxdbr0 which broke the WAN networking.   You can still get into the box via another IP on the same subnet otherwise you'll need to do a remote reboot to reset the table.   The default route can be deleted manually if you can get entry.

# Steps to reproduce

 1. Run the attached mkdud script
 2. lxc exec dud-instance bash
 3. lxc delete --force dud-instance
 
[mkdud.txt](https://github.com/lxc/lxd/files/8303318/mkdud.txt)

**Comment by tomponline** [comment]
Thanks!

Also useful context from https://discuss.linuxcontainers.org/t/error-value-too-large-for-defined-data-type-problem-when-execing-newly-created-instances/13571/41?u=tomp

> The issue appears to be the proxies config or the saves() that is producing unusable instances.
If I comment out the con.save(wait=True) on the new devices the problem doesn’t occur…
> I’ll try changing the code so the proxies are created with the container and not as a modification after the instance is running.
> That’s cracked it… so instead of adding in the proxies after the creation I created them in the initial configuration for the instance create and that’s solved the problem…

**Comment by tomponline** [comment]
@simondeziel as you're looking at pylxd issues ATM I wondered if you could validate this issue (only if you have time). Thanks

**Comment by simondeziel** [comment]
I can confirm the issue. The problem seems to manifests when the container is started and then the config is altered and saved while the container is still going through idmap shifting.

@Dweller here's a workaround:

```
# diff -Naur mkdud.txt.orig mkdud.txt
--- mkdud.txt.orig	2022-03-31 19:54:47.045279890 +0000
+++ mkdud.txt	2022-03-31 20:38:41.720937590 +0000
@@ -43,7 +43,6 @@
 task['name'] = name
 con=lxd.containers.create(task, wait=True)        
 print(time.time(), con.name, "Devices", con.devices)
-con.start(wait=True);
 
 print("Sleeping for 5 secs to give the instance boot")
 time.sleep(5) # Give the instance a chance to start
@@ -52,5 +51,6 @@
 con.devices['dud80']= {'connect': 'tcp:127.0.0.1:4000', 'listen': 'tcp:0.0.0.0:6661', 'type': 'proxy'}
 print(time.time(), con.name, "Devices", con.devices)
 con.save(wait=True)
+con.start(wait=True);
 
 print(time.time(), "That's all folks")
```

**Comment by tomponline** [comment]
OK so we need to make sure not using idmapped mounts for this issue? Sounds  like we need to prevent configuration modifications during start-up.

**Comment by simondeziel** [comment]
@tomponline looking at the container config right after the `sleep 5`:

```
root@pylxd:~# lxc config show dud-instance
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Centos 8-Stream amd64 (20220330_07:53)
  image.os: Centos
  image.release: 8-Stream
  image.serial: "20220330_07:53"
  image.type: squashfs
  image.variant: default
  volatile.base_image: 01b83ebd0cd36e247764ac3d522e5646f526e0ef35e5efa013885fd97e7bfd0b
  volatile.eth0.host_name: veth1e4ab740
  volatile.eth0.hwaddr: 00:16:3e:3f:4b:af
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: d4b65501-7cf1-40f6-bed9-ff7904d0bd12
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

And the once the script is done running:

```
root@pylxd:~# lxc config show dud-instance
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Centos 8-Stream amd64 (20220330_07:53)
  image.os: Centos
  image.release: 8-Stream
  image.serial: "20220330_07:53"
  image.type: squashfs
  image.variant: default
  volatile.apply_template: create
  volatile.base_image: 01b83ebd0cd36e247764ac3d522e5646f526e0ef35e5efa013885fd97e7bfd0b
  volatile.eth0.hwaddr: 00:16:3e:3f:4b:af
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.uuid: d4b65501-7cf1-40f6-bed9-ff7904d0bd12
devices:
  dud80:
    connect: tcp:127.0.0.1:4000
    listen: tcp:0.0.0.0:6661
    type: proxy
  dud8080:
    connect: tcp:127.0.0.1:80
    listen: tcp:0.0.0.0:6660
    type: proxy
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

At which point we hit the issue:

```
root@pylxd:~# lxc exec dud-instance bash
Error: value too large for defined data type
```
Then if you restart it to trigger another re-idmapping (I pressed enter a bunch of time to make the `Remapping container filesystem` message visible:

```
root@pylxd:~# lxc restart dud-instance



Remapping container filesystem

root@pylxd:~#                  
root@pylxd:~# 
root@pylxd:~# 
root@pylxd:~# 
root@pylxd:~# 
root@pylxd:~# 
root@pylxd:~# lxc exec dud-instance bash
[root@dud-instance ~]# exit
```
