### ISSUE TITLE
Instance volume migration does not transfer volume DB config

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#10102]
When doing a cross-pool copy of an instance, the storage volume DB record config is not transferred (unlike when doing a custom storage volume cross-pool copy).

E.g.

```
lxc storage create lvm1 lvm
lxc storage set lvm1 volume.block.filesystem=xfs
lxc storage create lvm2 lvm
lxc init images:ubuntu/focal c1 -s lvm1

lxc storage volume show lvm1 container/c1
config:
  block.filesystem: xfs
  block.mount_options: discard
description: ""
name: c1
type: container
used_by:
- /1.0/instances/c1
location: none
content_type: filesystem

lxc copy c1 c2 -s lvm2
lxc storage volume show lvm2 container/c2
config:
  block.filesystem: ext4
  block.mount_options: discard
description: ""
name: c2
type: container
used_by:
- /1.0/instances/c2
location: none
content_type: filesystem
```

The `block.filesystem` setting has not been preserved. 

Also snapshot storage records are not transferred for either instance or custom volume types.

- [x] Fix instance storage volume (and snapshots) config copying. (https://github.com/lxc/lxd/pull/10526).
- [x] Fix custom storage volume (and snapshots) config copying (https://github.com/lxc/lxd/pull/10423).
