### ISSUE TITLE
Custom storage volume snapshot expiry not maintained when volume is copied

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#10103]
Unlike instance snapshots, custom volume snapshot expiry settings are not maintained when they are copied, even within the same storage pool:

```
lxc storage create lvm1 lvm
lxc storage create lvm2 lvm
lxc storage volume create lvm1 vol1
lxc storage volume set lvm1 vol1 snapshots.expiry=1H
lxc storage volume show lvm1 vol1
config:
  block.filesystem: ext4
  block.mount_options: discard
  snapshots.expiry: 1H
description: ""
name: vol1
type: custom
used_by: []
location: none
content_type: filesystem

lxc storage volume snapshot lvm1 vol1 snap0
lxc storage volume show lvm1 vol1/snap0
description: ""
expires_at: 2022-03-22T18:45:21.164119859Z
name: snap0
config:
  block.filesystem: ext4
  block.mount_options: discard
  snapshots.expiry: 1H
content_type: filesystem

lxc storage volume copy lvm1/vol1 lvm1/vol2

lxc storage volume show lvm1 vol2/snap0
description: ""
expires_at: 0001-01-01T00:00:00Z
name: snap0
config:
  block.filesystem: ext4
  block.mount_options: discard
  snapshots.expiry: 1H
content_type: filesystem
```

The `expires_at` setting has been lost.
