### ISSUE TITLE
`lxc restore` does not restore instance snapshot volume config onto main volume config

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#10118]
E.g.

```
lxc init images:ubuntu/focal c1 -s default
lxc storage volume set default container/c1 user.foo=bar
lxc storage volume show default container/c1
config:
  user.foo: bar
description: ""
name: c1
type: container
used_by:
- /1.0/instances/c1
location: none
content_type: filesystem

lxc snapshot c1
lxc storage volume show default container/c1/snap0
description: ""
expires_at: 0001-01-01T00:00:00Z
name: snap0
config:
  user.foo: bar
content_type: filesystem

lxc storage volume set default container/c1 user.foo=notbar
lxc storage volume show default container/c1
config:
  user.foo: notbar
description: ""
name: c1
type: container
used_by:
- /1.0/instances/c1
location: none
content_type: filesystem

lxc restore c1 snap0
lxc storage volume show default container/c1
config:
  user.foo: notbar
description: ""
name: c1
type: container
used_by:
- /1.0/instances/c1
location: none
content_type: filesystem
```

The `user.foo` value is still the old `notbar` rather than being restored from the snapshot as `bar`.
