### ISSUE TITLE
lxd: copying same instance multiple times concurrently not working

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#10111]
This is with LXD 4.24:

```
  driver: lxc | qemu
  driver_version: 4.0.12 | 6.1.1
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    idmapped_mounts: "false"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-100-generic
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: false
  server_event_mode: full-mesh
  server_name: pengar
  server_pid: 3118261
  server_version: "4.24"
  storage: dir
  storage_version: "1"
  storage_supported_drivers:
  - name: btrfs
    version: 5.4.1
    remote: false
  - name: cephfs
    version: 15.2.14
    remote: true
  - name: dir
    version: "1"
    remote: false
  - name: lvm
    version: 2.03.07(2) (2019-11-30) / 1.02.167 (2019-11-30) / 4.41.0
    remote: false
  - name: zfs
    version: 0.8.3-1ubuntu12.13
    remote: false
  - name: ceph
    version: 15.2.14
    remote: true
```
I have two disks. The `default` storage pool is a directory on `/dev/sda2` and the `lxd-ssd-pool` is a storage pool on `/dev/sdb` which is an ssd:

```
ubuntu@pengar:~/ssd/linux$ lxc storage info default
info:
  description: ""
  driver: dir
  name: default
  space used: 80.87GiB
  total space: 456.96GiB
used by:
  instances:
  - imp2-vm
  profiles:
  - default
  - vm
ubuntu@pengar:~/ssd/linux$ lxc storage info lxd-ssd-pool
info:
  description: ""
  driver: dir
  name: lxd-ssd-pool
  space used: 147.46GiB
  total space: 228.23GiB
used by:
  instances:
  - imp1-vm
  - imp3-vm
```

When I try to copy the same instace multiple times concurrently it seems that only one copy runs all the other ones are blocked.

In addition, when I transfer between pools then I see a progress report but when I transfer within the same `lxd-ssd-pool` then I don't.
