### ISSUE TITLE
Privileged containers memory limit issue when swap disabled

### ISSUE THREAD

**Issue by YuiIchi** [lxc/lxd#10154]
# Required information

 * Distribution: Ubuntu
 * Distribution version:  Ubuntu 21.10
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux dev-physical-0-19 5.13.0-30-generic x86_64 GNU/Linux
   * LXC version: 4.24
   * LXD version: 4.24
   * Storage backend in use: dir

# Issue description

The problem is that when the profile has the above 2 seetings at the same time, the 「limits.memory」 will not work.
```
security.privileged: “true”
limits.memory.swap: “false”
```

# Steps to reproduce

#### 1. Create the test profile:
```
root@dev-physical-0-17:~# cat test.profile 
name: k8s 
config:
  security.privileged: "true"
  limits.memory.swap: "false"
description: ""
root@dev-physical-0-17:~# lxc profile create test
root@dev-physical-0-17:~# cat test.profile | lxc profile edit test
root@dev-physical-0-17:~# lxc profile show test
config:
  limits.memory.swap: "false"
  security.privileged: "true"
description: ""
devices: {}
name: test
used_by: []
```

#### 2. Launch the instance and verify the memory seeting:
```
root@dev-physical-0-17:~# lxc -p default -p test launch dev-physical-0-19:centos-8-base c1 -c limits.cpu=1 -c limits.memory=256MiB
Creating c1
Starting c1 
root@dev-physical-0-17:~# lxc exec c1 -- sh -c "free -h"
              total        used        free      shared  buff/cache   available
Mem:          376Gi        34Mi       376Gi       8.0Mi       8.0Mi       376Gi
Swap:            0B          0B          0B
```

you can see the memory size is not correct.

# Information to attach
