### ISSUE TITLE
Failed to load device... Device name too long max 27 characters

### ISSUE THREAD

**Issue by jemail99** [lxc/lxd#10238]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   Armbian Focal Linux 5.10.81-meson64 21.08.6 SMP PREEMPT aarch64 aarch64 aarch64 GNU/Linux
   * LXC version:
   5.0.0
   * LXD version:
   5.0.0
   * Storage backend in use:
   Btrfs

# Issue description

Rebooted my server today and two containers failed to start with:
Failed to load device... Device name too long max 27 characters

Could a dev please provide instructions on how to resolve this error so I can start these containers?

**Comment by tomponline** [comment]
Can you show `lxc config show <instance>` and `lxc profile show <profile>`

**Comment by jemail99** [comment]
```
lxc config show calendar-server 
architecture: aarch64
config:
  boot.autostart: "true"
  image.architecture: arm64
  image.description: Alpine 3.14 arm64 (20211120_13:00)
  image.os: Alpine
  image.release: "3.14"
  image.serial: "20211120_13:00"
  image.type: squashfs
  image.variant: default
  raw.idmap: |-
    uid 1000-1002 1000-1002
    gid 1005 1005
  volatile.apply_template: rename
  volatile.base_image: 351b6564e8c5e892c979e118c760477518d8e8f554bd36b51e3817675ad21f63
  volatile.cloud-init.instance-id: f5b3146f-70d5-4a19-b49c-441321f5dacd
  volatile.eth0.host_name: mac1f00f97d
  volatile.eth0.hwaddr: 00:16:3e:7f:54:21
  volatile.eth0.last_state.created: "false"
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":3},{"Isuid":true,"Isgid":false,"Hostid":1001003,"Nsid":1003,"Maprange":999998997},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1005},{"Isuid":false,"Isgid":true,"Hostid":1005,"Nsid":1005,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1001006,"Nsid":1006,"Maprange":999998994}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":3},{"Isuid":true,"Isgid":false,"Hostid":1001003,"Nsid":1003,"Maprange":999998997},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1005},{"Isuid":false,"Isgid":true,"Hostid":1005,"Nsid":1005,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1001006,"Nsid":1006,"Maprange":999998994}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":3},{"Isuid":true,"Isgid":false,"Hostid":1001003,"Nsid":1003,"Maprange":999998997},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1005},{"Isuid":false,"Isgid":true,"Hostid":1005,"Nsid":1005,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1001006,"Nsid":1006,"Maprange":999998994}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 07c492e3-f43c-4d6b-b6f1-5d8a6719cae6
devices:
  alpine-calendar-share-ssl-acme.sh:
    path: /etc/ssl/acme.sh/
    source: /etc/ssl/acme.sh/
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
```
lxc profile show default 
config: {}
description: Default container configuration for titanium containers allowing LAN
  access.
devices:
  eth0:
    name: eth0
    nictype: macvlan
    parent: eth0
    type: nic
  root:
    path: /
    pool: titanium-btrfs
    type: disk
name: default
used_by:
- /1.0/instances/media-server
- /1.0/instances/download-server
- /1.0/instances/file-server
- /1.0/instances/calendar-server
- /1.0/instances/sync-server
```
