### ISSUE TITLE
Joining a cluster using OVN when you have pre-existing projects using `restricted.networks.subnets` fails

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#10258]
When joining a cluster using OVN when you have pre-existing projects using `restricted.networks.subnets`, it fails with something like:

```
Error: Failed to join cluster: Failed to initialize member: Failed to create local node project "dlebrun": Invalid project configuration key "restricted.networks.subnets" value: Invalid uplink network "UPLINK": Network not found
```

**Comment by tomponline** [comment]
This feels like an ordering issue, the dependent UPLINK network hasn't been created before the projects that depend on it.

**Comment by tomponline** [comment]
I would've thought this setup would have recreated the error but it does not:

```
lxc network show lxdbr0 --target=v1
config:
  ipv4.address: 10.124.59.1/24
  ipv4.nat: "true"
  ipv4.routes: 10.0.0.0/24
  ipv6.address: fd42:59df:71dc:15c2::1/64
  ipv6.nat: "true"
description: ""
name: lxdbr0
type: bridge
used_by: []
managed: true
status: Created
locations:
- v1
```

```
 lxc project show foo
config:
  features.images: "true"
  features.networks: "true"
  features.profiles: "true"
  features.storage.volumes: "true"
  restricted: "true"
  restricted.networks.subnets: lxdbr0:10.0.0.0/24
description: ""
name: foo
used_by:
- /1.0/profiles/default?project=foo
```
