### ISSUE TITLE
LXC Init with Debian Bullseye image hangs - locked?

### ISSUE THREAD

**Issue by webdock-io** [lxc/lxd#10279]
LXC v4.16 on Ubuntu Focal

Encountered this on a system today, never seen this before:

```
# lxc init images:debian/bullseye foo
Creating foo
```

Hangs forever, while LXC monitor says:

```
location: none
metadata:
  context: {}
  level: dbug
  message: Acquiring lock for image download of "93a8f44df60764e57e0d87d54b06ed2a444304610bf045bf3e9072089911d590"
timestamp: "2022-04-19T15:51:40.698513185+02:00"
type: logging
```

And does not proceed. So, something has that image locked? I tried deleting the image with lxc image delete - this did not improve the situation on subesequent tries.

I made sure the server can reach images.linuxcontainers.org - I also checked to see if any processes were running referencing this image:

`# ps aux | grep debian`

But no hits.

I also tried other images from that remote, and they work, e.g.:

```
# lxc init images:almalinux/8 foo
Creating foo
root@tora:/home/master# lxc delete foo
root@tora:/home/master# lxc image delete f2725d46b3cd
root@tora:/home/master# lxc init images:almalinux/8 foo
Creating foo
root@tora:/home/master#
```

So it's just this one image LXD is having issues with. Not sure what this is or how to recover.

**Comment by tomponline** [comment]
Can you try reloading LXD as I just tried that here using `lxc init images:debian/bullseye foo` and it completed fine.

It suggests perhaps there is an ongoing download of the image that has got stuck, perhaps due to network issues.

**Comment by webdock-io** [comment]
@tomponline Yes this works on other installs, so it's just hanging on this system for some reason.

How should I reload LXD? Will this bring down my containers? If so, I'll need to do this in a maintenance window. Please advise...

**Comment by tomponline** [comment]
Normal LXD reload, no it won't bring down your containers.

```
sudo systemctl reload snap.lxd.daemon
```

**Comment by webdock-io** [comment]
Ouch well that wasn't completely safe to do, as I have a lot of containers on there so the procedure has taken some time and is now - seemingly - hanging. During which LXD is inoperational so our systems can no longer interact with containers via. LXD - which is bad.

It looks to be hanging here:

```
location: none
metadata:
  context:
    socket: /var/snap/lxd/common/lxd/unix.socket
  level: info
  message: ' - closing socket'
timestamp: "2022-04-19T16:10:52.155257014+02:00"
type: logging
```

So yeah... Anyway should I just wait and try to mitigate whatever issues turn up while this runs to completion, eventually, hopefully, or should I press the big red reboot button on this system? :)

I'll be sure to post as soon as something, hopefully, changes.
