### ISSUE TITLE
LXD guessing the FQN so a node can't join with its short name

### ISSUE THREAD

**Issue by mdione-cloudian** [lxc/lxd#10287]
Cluster 'leader':

```
cloudian@uk-lxd1:~/mdione/automation-frameworks/terrible$ lxc config trust list
+--------+---------+---------------------------+--------------+------------------------------+------------------------------+
|  TYPE  |  NAME   |        COMMON NAME        | FINGERPRINT  |          ISSUE DATE          |         EXPIRY DATE          |
+--------+---------+---------------------------+--------------+------------------------------+------------------------------+
| server | uk-lxd1 | root@uk-lxd1.cloudian.com | 89c30fd931b0 | Apr 20, 2022 at 1:22pm (UTC) | Apr 17, 2032 at 1:22pm (UTC) |
+--------+---------+---------------------------+--------------+------------------------------+------------------------------+
```

Cluster 2nd node:

```
$ sudo /snap/bin/lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: yes
What IP address or DNS name should be used to reach this node? [default=10.130.40.82]: 10.130.40.82:5555
Are you joining an existing cluster? (yes/no) [default=no]: yes
Do you have a join token? (yes/no/[token]) [default=no]: no
What name should be used to identify this node in the cluster? [default=uk-lxd2.cloudian.com]: uk-lxd2
IP address or FQDN of an existing cluster member (may include port): 10.130.40.81:5555
Cluster fingerprint: 542aed9f6f78671f34cd19d44bbb7b0bcd2b2ca81e24485034971d0246132199
You can validate this fingerprint by running "lxc info" locally on an existing node.
Is this the correct fingerprint? (yes/no/[fingerprint]) [default=no]: yes
Cluster trust password: 
All existing data is lost when joining a cluster, continue? (yes/no) [default=no] yes
Choose "source" property for storage pool "local": 
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: yes
```

```yaml
config: {}
networks: []
storage_pools: []
profiles: []
projects: []
cluster:
  server_name: uk-lxd2
  enabled: true
  member_config:
  - entity: storage-pool
    name: local
    key: source
    value: ""
    description: '"source" property for storage pool "local"'
  cluster_address: 10.130.40.81:5555
  cluster_certificate: |
    -----BEGIN CERTIFICATE-----
    MIICLjCCAbOgAwIBAgIQTUZ3X/Q2sEn8hyF2u4kzsjAKBggqhkjOPQQDAzBCMRww
    GgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMSIwIAYDVQQDDBlyb290QHVrLWx4
    ZDEuY2xvdWRpYW4uY29tMB4XDTIyMDQyMDEzMzcyNVoXDTMyMDQxNzEzMzcyNVow
    QjEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEiMCAGA1UEAwwZcm9vdEB1
    ay1seGQxLmNsb3VkaWFuLmNvbTB2MBAGByqGSM49AgEGBSuBBAAiA2IABDQKunlo
    RgGNkuELAvWwCwdh1f28u8oHIYjolinuFNy+dXn94Y7/3FnGrmJRSiFa0sBSeoy6
    84Td99bkANPDOrRFOYreTvOMprtgmAGI27qdLtZg4lYOCOyu0uVyQ8T9+6NuMGww
    DgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQC
    MAAwNwYDVR0RBDAwLoIUdWstbHhkMS5jbG91ZGlhbi5jb22HBH8AAAGHEAAAAAAA
    AAAAAAAAAAAAAAEwCgYIKoZIzj0EAwMDaQAwZgIxALk6tiOkqPu6q/QuR/9ThQue
    2h9lCnQMENCpXHHv2H0uEEYPL5lWrCO+1X7ZNIFv1AIxAMg2zURyMzE34pj3j0Rv
    q7U0bFhT7H8lkrnPsEdLsffoH+6nN5kNBoGRqWKaoy3BRw==
    -----END CERTIFICATE-----
  server_address: 10.130.40.82:5555
  cluster_password: ""
  cluster_certificate_path: ""
  cluster_token: ""
```

but:

```
Error: Failed to join cluster: Failed to update cluster trust: Existing server certificate with different name "uk-lxd2.cloudian.com" already in trust store
```

because

```
$ lxc config trust list
+--------+----------------------+---------------------------+--------------+------------------------------+------------------------------+
|  TYPE  |         NAME         |        COMMON NAME        | FINGERPRINT  |          ISSUE DATE          |         EXPIRY DATE          |
+--------+----------------------+---------------------------+--------------+------------------------------+------------------------------+
| server | uk-lxd1              | root@uk-lxd1.cloudian.com | 89c30fd931b0 | Apr 20, 2022 at 1:22pm (UTC) | Apr 17, 2032 at 1:22pm (UTC) |
+--------+----------------------+---------------------------+--------------+------------------------------+------------------------------+
| server | uk-lxd2.cloudian.com | root@uk-lxd2.cloudian.com | 36e672dbaead | Apr 20, 2022 at 2:37pm (UTC) | Apr 17, 2032 at 2:37pm (UTC) |
+--------+----------------------+---------------------------+--------------+------------------------------+------------------------------+
```

Notice I used `uk-lxd2` instead of `uk-lxd2.cloudian.com`. If I try to add the node with the FQDN, it works.
