### ISSUE TITLE
Wrong interfaces assignement when creating containers with terraform and multiple interfaces

### ISSUE THREAD

**Issue by invizus** [lxc/lxd#10282]
# Required information

 * Distribution: Debian 10
 * Distribution version: 10.11
 * The output of "lxc info" or if that fails: (it was 413 lines long, so here is the summary below)
   * Kernel version: 
   * LXC version: 
   * LXD version:
   * Storage backend in use: dir
```
  driver: lxc | qemu
  driver_version: 4.0.12 | 6.1.1
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    idmapped_mounts: "false"
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 4.19.0-19-amd64
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Debian GNU/Linux
  os_version: "10"
  project: default
  server: lxd
  server_clustered: false
  server_event_mode: full-mesh
  server_pid: 17878
  server_version: 5.0.0
  storage: dir
  storage_version: "1"
```
# Issue description

My LXD host is setup with two bridge interfaces (`bridge-utils`), and I configure profile to use them for containers. So my containers have two interfaces too. I do not use DHCP, my network config is static. I use cloud-init I think, not sure but it works.

See my terraform code below for reference.

Half of the time the container network is created wrong (does not often happen if you create one container, but almost always happens when I create like 8 containers). The internal interface is assigned to the wrong host interface. If I ping something from within container and monitor traffic with tcpdump, I can see that traffic is being sent out via the wrong interface.

One of the maintainers asked whether containers are created concurrently? I believe so. When I monitor `lxc ls`, I see all new containers that are being created appear at the same time together.

# Steps to reproduce
For example see the part of the config from the `lxc config edit <container>`:
```
config:
  ...
  volatile.eth0.host_name: vetheyxxxyyy
  volatile.eth0.hwaddr: 00:1x:xx:xx:xx:yy
  volatile.eth0.name: eth1
  volatile.eth1.host_name: veth6xxx6xxx
  volatile.eth1.hwaddr: 00:1x:xx:xx:xx:xx
  volatile.eth1.name: eth0
```
I have to fix these two lines, restart container and then network works as expected.
```
volatile.eth0.name: eth0
volatile.eth1.name: eth1
```
Looks like a race condition to me. Should I let people on terraform-lxd github know about this or is this something for you guys to look at?

My profile:
```
$ lxc profile show myprofile
config: {}
description: Created by Terraform
devices:
  eth0:
    nictype: bridged
    parent: br0
    type: nic
  eth1:
    nictype: bridged
    parent: br1
    type: nic
```

This is some of my terraform code:
```
# this is modules/container/main.tf, scroll down for network.yml template
resource "lxd_container" "container" {
  name = var.name
  image = var.image
  ephemeral = var.ephemeral
  profiles = var.profiles

  config = {
    "user.network-config" : data.template_file.network_config.rendered
  }
}

data "template_file" "network_config" {
  template = file("${path.module}/network.yml")
  vars = {
    eth0_ip = var.eth0_ip
    eth0_netmask = var.eth0_netmask
    eth0_gateway = var.eth0_gateway
    eth1_ip = var.eth1_ip
    eth1_netmask = var.eth1_netmask
    nameserver = var.nameserver
  }
}

# this is modules/container/network.yml
network:
  version: 1
  config:
    - type: physical
      name: eth0
      subnets:
        - type: static
          ipv4: true
          address: ${eth0_ip}
          netmask: ${eth0_netmask}
          gateway: ${eth0_gateway}
          control: auto
    - type: physical
      name: eth1
      subnets:
        - type: static
          ipv4: true
          address: ${eth1_ip}
          netmask: ${eth1_netmask}
          control: auto
```
```
# this is project
module "mycontainer1" {
  source = "./modules/container"
  name = "mycontainer1"
  image = "images:debian/buster/cloud/amd64"
  profiles = ["myprofile"]

  eth0_ip = "xxxxx"
  eth0_netmask = "255.255.255.0"
  eth0_gateway = "xxxxxxx"
  eth1_ip = "xxxxxxx"
  eth1_netmask = "255.255.255.0"
  nameserver = "xxxxxxx"
}
```
Feel free to ask any questions. Code above was sanitized a bit so may be few mistakes made during copy/paste.

There is another lxd terraform glitch, when you use modules - terraform will fail to download lxd provider binaries. I had to add providers into the module itself, and pass variables to the module. If someone will be testing terraform and experience this issue, please let me know and I will help.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
