### ISSUE TITLE
Invalid certificate?

### ISSUE THREAD

**Issue by mdione-cloudian** [lxc/lxd#10286]
I'm trying to automate the setup of an LXD cluster. It's just a couple of bash scripts, so I can easily paste the commands here.

```
sudo apt install -y snapd
sudo systemctl enable --now snapd.socket
sudo snap wait system seed.loaded

sudo snap install lxd --channel=5.0/stable

sudo --preserve-env=PATH /snap/bin/lxd init --preseed  # we actually feed the info from stdin, nothing too weird, maybe except for 
# core.https_address: ${ip}:5555  # the original port is 8443, but we might use that for proxying the CMC
```

Here's the config in whole:

```
config:
  core.https_address: ${ip}:5555  # the original port is 8443, but we might use that for proxying the CMC
  core.trust_password: true
  core.trust_password: "${password}"

storage_pools:
- name: local
  driver: dir
  config: {}

networks:
- name: lxd-provision
  type: bridge
  config:
    dns.mode: none
    ipv4.nat: "true"
    raw.dnsmasq: |-
      dhcp-ignore-names
      local-ttl=4938790

profiles:
- config: {}
  description: ""
  devices:
    root:
      path: /
      pool: local
      type: disk
  name: default

cluster:
  server_name: $(hostname --short)
  enabled: true
  member_config: []
  cluster_address: ""
  cluster_certificate: ""
  server_address: ""
  cluster_password: ""
  cluster_certificate_path: ""
  cluster_token: ""
```

If we run the generated cert through `openssl` we get:

```
cat cert.pem | openssl x509 -text
[...]
            X509v3 Subject Alternative Name:
                DNS:uk-lxd1.cloudian.com, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1
``` 

which does not match the IP. According to @tomponline:

> <tomp> StyXman: lxd doesnt validate common names on certs, is the time correct on the server?
> <tomp> StyXman: the IPs/names arent validated

We corroborated that time's are fine. 

But when trying to add a second node a first time I got:

```
$ cat uk-lxd2_lxd-config.yaml | lxd init --preseed
Error: Failed to join cluster: Failed to update cluster trust: Failed to connect to target cluster node "10.130.40.81:5555": Get "https://10.130.40.81:5555/1.0": x509: certificate is valid for 127.0.0.1, ::1, not 10.130.40.81
```
This is the config for the second node:

```
cloudian@uk-lxd2:~/mdione$ cat uk-lxd2_lxd-config.yaml
config: {}
networks: []
storage_pools: []
profiles: []
projects: []
cluster:
  server_name: uk-lxd2
  enabled: true
  member_config:
  - entity: storage-pool
    name: local
    key: source
    value: ""
    description: '"source" property for storage pool "local"'
  cluster_address: 10.130.40.81:5555
  cluster_certificate: |
    -----BEGIN CERTIFICATE-----
    MIICLjCCAbSgAwIBAgIRAKgC2z3bTa/l17q7s30EJqAwCgYIKoZIzj0EAwMwQjEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEiMCAGA1UEAwwZcm9vdEB1ay1s
    eGQxLmNsb3VkaWFuLmNvbTAeFw0yMjA0MTIxNDAyNDlaFw0zMjA0MDkxNDAyNDla
    MEIxHDAaBgNVBAoTE2xpbnV4Y29udGFpbmVycy5vcmcxIjAgBgNVBAMMGXJvb3RA
    dWstbHhkMS5jbG91ZGlhbi5jb20wdjAQBgcqhkjOPQIBBgUrgQQAIgNiAATcRp6g
    2TQJn7STRg7kOQszrWpFOkcDw0v1WMpGXI7DvejNjRftYhYI98UhrlTnv94BeVdl
    UW3q8xEtBTNKVPjR0iA5sErbP1mvNrLTWaLaHN8LhWUBqGvgWx9Gt5vzV/KjbjBs
    MA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8E
    AjAAMDcGA1UdEQQwMC6CFHVrLWx4ZDEuY2xvdWRpYW4uY29thwR/AAABhxAAAAAA
    AAAAAAAAAAAAAAABMAoGCCqGSM49BAMDA2gAMGUCMQDmCqd56zjlL2xukH5kwY2z
    Ys75VWio6PZm3S3h++3mvxYcc/NeEyKI/zT/4/MVeVECMCXnKRPncTFUroNZTU2I
    QT700I09cmM+RKdBo45iIVnT2IarPUzAlt/l6SmGkUjVVA==
    -----END CERTIFICATE-----
  server_address: 10.130.40.82:5555
  cluster_password: ""
  cluster_certificate_path: ""
  cluster_token: ""
```
