### ISSUE TITLE
Can't start VMs: guest-cid property must be a 32-bit number

### ISSUE THREAD

**Issue by bjornt** [lxc/lxd#10300]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 21.10
 * The output of "lxc info" or if that fails:
   * https://paste.ubuntu.com/p/fJmQ7JSS52/
   
# Issue description

Whenever I try to start a new VM, it fails, complaining that guest-cid property must be a 32-bit number.

I've launched many VMs so far, but then I removed all and and when I create new ones, I always get the error.

# Steps to reproduce
```
salvia:~> lxc launch --vm ubuntu:20.04 test
Creating test
Starting test                               
Error: Failed to run: forklimits limit=memlock:unlimited:unlimited fd=3 -- /snap/lxd/22923/bin/qemu-system-x86_64 -S -name test -uuid a50d7235-63cd-49ab-99c6-2cb2ce89bba1 -daemonize -cpu host,hv_passthrough -nographic -serial chardev:console -nodefaults -no-user-config -sandbox on,obsolete=deny,elevateprivileges=allow,spawn=allow,resourcecontrol=deny -readconfig /var/snap/lxd/common/lxd/logs/maas_test/qemu.conf -spice unix=on,disable-ticketing=on,addr=/var/snap/lxd/common/lxd/logs/maas_test/qemu.spice -pidfile /var/snap/lxd/common/lxd/logs/maas_test/qemu.pid -D /var/snap/lxd/common/lxd/logs/maas_test/qemu.log -smbios type=2,manufacturer=Canonical Ltd.,product=LXD -runas lxd: : Process exited with non-zero value 1
Try `lxc info --show-log salvia:test` for more info
salvia:~> lxc info --show-log salvia:test
Name: test
Status: STOPPED
Type: virtual-machine
Architecture: x86_64
Created: 2022/04/21 14:24 CEST

Log:

qemu-system-x86_64:/var/snap/lxd/common/lxd/logs/maas_test/qemu.conf:131: guest-cid property must be a 32-bit number

salvia:~> sudo grep guest-cid /var/snap/lxd/common/lxd/logs/maas_test/qemu.conf
[sudo] password for bjorn: 
guest-cid = "4294967386"
```

**Comment by tomponline** [comment]
@bjornt can you show `lxd sql global "select * from instances where name = 'test'"

**Comment by tomponline** [comment]
I suspect its caused by this https://github.com/lxc/lxd/pull/10216

**Comment by bjornt** [comment]
This is the output of `lxd sql global "select * from instances where name = 'test'":
```
+----+---------+------+--------------+------+-----------+--------------------------------+----------+----------------------+-------------+------------+----------------------+
| id | node_id | name | architecture | type | ephemeral |         creation_date          | stateful |    last_use_date     | description | project_id |     expiry_date      |
+----+---------+------+--------------+------+-----------+--------------------------------+----------+----------------------+-------------+------------+----------------------+
| 90 | 1       | test | 2            | 1    | 0         | 2022-04-21T12:24:46.413687995Z | 0        | 1970-01-01T00:00:00Z |             | 2          | 0001-01-01T00:00:00Z |
+----+---------+------+--------------+------+-----------+--------------------------------+----------+----------------------+-------------+------------+----------------------+

```

I don't use nested VMs, this is on bare metal.

**Comment by tomponline** [comment]
Can you provide `lxc config show test --expanded` please?

**Comment by bjornt** [comment]
```
salvia:~> lxc config show test --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20220419)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20220419"
  image.type: disk-kvm.img
  image.version: "20.04"
  limits.cpu: "2"
  limits.memory: 4GB
  security.secureboot: "false"
  volatile.base_image: 97251b450155a2daa46b88cab190322430d4c1f0729df5c791a89a989ee5faa3
  volatile.cloud-init.instance-id: ad02bd2d-0e79-4fcd-abe8-3613ffc455f3
  volatile.eth0.hwaddr: 00:16:3e:c0:b3:ea
  volatile.eth1.hwaddr: 00:16:3e:4e:f1:d8
  volatile.uuid: a50d7235-63cd-49ab-99c6-2cb2ce89bba1
  volatile.vsock_id: "4294967386"
devices:
  eth0:
    boot.priority: "100"
    nictype: bridged
    parent: maaslocal
    type: nic
  eth1:
    nictype: bridged
    parent: maaslocal2
    type: nic
  root:
    boot.priority: "1"
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

```
