### ISSUE TITLE
lxd recover: Instance "..." has a different instance type in its backup file ("")

### ISSUE THREAD

**Issue by tmarkettos** [lxc/lxd#10314]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04 copying to 20.04

Original server:
```
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-171-generic
  server: lxd
  server_pid: 2805
  server_version: 3.0.3
  storage: zfs
  storage_version: 0.7.5-1ubuntu16.12
  server_clustered: false
  server_name: source_server
  project: ""
```

New server:
```
  driver: lxc | qemu
  driver_version: 4.0.12 | 6.1.1
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-109-generic
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: new_server
  server_pid: 881
  server_version: 4.0.9
  storage: dir
  storage_version: "1"
  storage_supported_drivers:
  - name: zfs
    version: 0.8.3-1ubuntu12.13
    remote: false
  - name: ceph
    version: 15.2.14
    remote: true
  - name: btrfs
    version: 5.4.1
    remote: false
  - name: cephfs
    version: 15.2.14
    remote: true
  - name: dir
    version: "1"
    remote: false
  - name: lvm
    version: 2.03.07(2) (2019-11-30) / 1.02.167 (2019-11-30) / 4.41.0
    remote: false
```

# Issue description

I copied a running LXD container on Ubuntu 18.04 (zfs storage) by tarring up the files in /var/lib/lxd/storage-pools/default/containers/mycontainer and copying to /var/snap/lxd/common/lxd/storage-pools/default/containers/mycontainer on a new server.

I also edited the backup.yaml file to change from a ZFS storage pool to a directory pool (I set up a new LXD container in the 'dir' pool and copied the `pool:` fragment from backup.yaml across).  I then ran `lxd recover`:

```
# lxd recover
This LXD server currently has the following storage pools:
 - default (backend="dir", source="/var/snap/lxd/common/lxd/storage-pools/default")
Would you like to recover another storage pool? (yes/no) [default=no]: 
The recovery process will be scanning the following storage pools:
 - EXISTING: "default" (backend="dir", source="/var/snap/lxd/common/lxd/storage-pools/default")
Would you like to continue with scanning for lost volumes? (yes/no) [default=yes]: 
Scanning for unknown volumes...
Error: Failed validation request: Failed checking volumes on pool "default": Instance "mycontainer" in project "default" has a different instance type in its backup file ("")
```

I eventually worked out how to fix this by adding:
```
  type: container
```
to the `container:` section in backup.yaml, and then the container imported.

This should probably be a default value so that older containers will import.
