### ISSUE TITLE
Events missing?

### ISSUE THREAD

**Issue by turtle0x1** [lxc/lxd#10498]
When reading the events [docs](https://linuxcontainers.org/lxd/docs/master/events) I saw the heading `Supported lifecycle events` which makes me think that certain events are supposed to be emitted when listening on `/1.0/events?type=operation,lifecycle`.

When I create a profile a listen with `lxc monitor --debug` I can see the lifecycle event but when I try the same with projects its missing (or deleting a project)

```
location: none
metadata:
  action: profile-created
  requestor:
    address: '@'
    protocol: unix
    username: www-data
  source: /1.0/profiles/latest-randy
project: default
timestamp: "2022-06-01T23:01:20.949323898+01:00"
type: lifecycle
```
