### ISSUE TITLE
the restapi about create instance and config limits.cpu

### ISSUE THREAD

**Issue by GoJoonHee** [lxc/lxd#10543]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:5.2
   * LXD version:5.2
   * Storage: zfs
   * Storage_version: 0.8.3-1ubuntu12.13

# Issue description
my lxc version is 5.2, my lxd version is 5.2.
I need to specify cpu resource limits when creating instances by rest api.
so i post to https://172.31.18.253:8443/1.0/instances,
and my request body is :
{
	"name": "chenchen",
	"source": {
		"fingerprint": "c0be9736b44271f1aeb8bffbe13c89eb607cd0cce7d6d5b6a6b01e959cbbda56",
		"type": "image"
	},
	**_"config": {
		"limits.cpu": "2"
	},_**
	"type": "container"
}
and then  nothing responded in response body , the http response code is 202.
i found that the instance has been succeesfully created. 
i can see the container through 'lxc list'.
the only problem is that the rest api doesn't seem to return normally.
Did I paas the wrong parameter？
Looking forward to your answers，Thank you all very, very much.

**Comment by stgraber** [comment]
```
stgraber@dakara:~$ curl --unix-socket /var/snap/lxd/common/lxd/unix.socket lxd/1.0/instances -X POST -d '{"name": "chenchen", "source": {"fingerprint": "ee087d230706deec7328dfb084782a3e77ab831f8ba2f2a866f1bc34d3747367", "type": "image"}, "config": {"limits.cpu": "2"}, "type": "container"}'

{"type":"async","status":"Operation created","status_code":100,"operation":"/1.0/operations/ddea58ab-52f3-4a22-a6b3-8eb572dd863f","error_code":0,"error":"","metadata":{"id":"ddea58ab-52f3-4a22-a6b3-8eb572dd863f","class":"task","description":"Creating instance","created_at":"2022-06-13T20:18:58.582493885-04:00","updated_at":"2022-06-13T20:18:58.582493885-04:00","status":"Running","status_code":103,"resources":{"containers":["/1.0/containers/chenchen"],"instances":["/1.0/instances/chenchen"]},"metadata":null,"may_cancel":false,"err":"","location":"none"}}


stgraber@dakara:~$ lxc config show chenchen
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Alpine edge amd64 (20220429_13:01)
  image.os: Alpine
  image.release: edge
  image.requirements.secureboot: "false"
  image.serial: "20220429_13:01"
  image.type: squashfs
  image.variant: default
  limits.cpu: "2"
  volatile.apply_template: create
  volatile.base_image: ee087d230706deec7328dfb084782a3e77ab831f8ba2f2a866f1bc34d3747367
  volatile.cloud-init.instance-id: 737fd0d6-712f-474e-85e7-f6326af81179
  volatile.eth0.hwaddr: 00:16:3e:7c:8a:c8
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.uuid: b77990b8-8efd-4472-9f82-59655db9f9fc
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
stgraber@dakara:~$ 
```
