### ISSUE TITLE
Lost network name when `lxc copy`, `lxc move` or `lxd recover`

### ISSUE THREAD

**Issue by olivier-lz** [lxc/lxd#10576]
# Required information

 * Distribution: **Debian**
 * Distribution version: **11.3** 
 * The output of "lxc info" or if that fails:
   * Kernel version: **Debian 5.10.120-1**
   * LXC version: **5.2**
   * LXD version: **5.2**
   * Storage backend in use: **btrfs**

_I search existing active issue with this keyword : `copy` `volatile`_

# Issue description

When a copy or move (Between two host, or on the same host), the config `volatile.*.name` is automatically renamed `eth#`.

I have the same result with `lxd recover` _(I am actually testing the recovery procedure)_

# Steps to reproduce

 1. lxc copy **u1** **u2**
 2. lxc config show **u1** | grep "volatile\\..*\\.name"
     ```
       volatile.lxdbr0.name: lxdbr0
       volatile.lxdbr1.name: lxdbr1
     ```
 3. lxc config show **u2** | grep "volatile\\..*\\.name"
     ```
       volatile.lxdbr0.name: eth0
       volatile.lxdbr1.name: eth1
     ```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [x] Container configuration (`lxc config show NAME --expanded`)
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Debian buster amd64 (20201113_05:24)
  image.os: Debian
  image.release: buster
  image.serial: "20201113_05:24"
  image.type: squashfs
  image.variant: default
  snapshots.expiry: 1d
  volatile.base_image: 4c386063295aba98f9392fb117f0c84e28f761a24c69c71d86db0f70fe925499
  volatile.cloud-init.instance-id: 6c25ece1-0e0f-4b31-88b9-b4be521ab84e
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.lxdbr0.host_name: vethe0298d9c
  volatile.lxdbr0.hwaddr: 00:16:3e:7a:23:09
  volatile.lxdbr0.name: lxdbr0
  volatile.lxdbr1.host_name: vethda091d50
  volatile.lxdbr1.hwaddr: 00:16:3e:bd:c1:8e
  volatile.lxdbr1.name: lxdbr1
  volatile.uuid: b7267dbf-7bae-4a26-9cae-3075847bd30a
devices:
  lxdbr0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  lxdbr1:
    nictype: bridged
    parent: lxdbr1
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
- net-lxdbr0
- net-lxdbr1
stateful: false
description: 
```
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

Thanks in advance.

**Comment by stgraber** [comment]
Why are you directly altering volatile keys?
Those are not meant for user use, they are internal state which indeed does not persist migrations.

Instead you should just use the name property on the network device itself.

**Comment by olivier-lz** [comment]
Hi @stgraber, thanks for your quick answer.

You make me doubt !

When I show the network configuration, I am expecting `lxdbr0` as interface name : 

```bash
# lxc network show lxdbr0
config:
  ipv4.address: 10.2.179.1/24
  ipv4.dhcp.expiry: 30d
  ipv4.nat: "true"
  ipv6.address: fd42:d392:2bf9:820d::1/64
  ipv6.nat: "true"
description: ""
name: lxdbr0
type: bridge
used_by:
- /1.0/instances/u1
- /1.0/instances/u2
- /1.0/profiles/net-lxdbr0
managed: true
status: Created
locations:
- none
```
```bash
# lxc profile show net-lxdbr0
config: {}
description: ""
devices:
  lxdbr0:
    nictype: bridged
    parent: lxdbr0
    type: nic
name: net-lxdbr0
used_by:
- /1.0/instances/u1
- /1.0/instances/u2
```

But I just try to create a new instance :

```bash
# lxc init images:debian/11 u3
Creating u3
                                            
The instance you are starting doesn't have any network attached to it.
  To create a new network, use: lxc network create
  To attach a network to an instance, use: lxc network attach

# lxc profile add u3 net-lxdbr0 
Profile net-lxdbr0 added to u3

# lxc config show u3 | grep "volatile\..*\.name" 
  volatile.lxdbr0.name: eth0
```

Why the name inside the CT is `eth0` ?
What is the proper way to set it to `lxdbr0` ?

**Comment by stgraber** [comment]
> ```shell
> # lxc profile show net-lxdbr0
> config: {}
> description: ""
> devices:
>   lxdbr0:
>     nictype: bridged
>     parent: lxdbr0
>     type: nic
> name: net-lxdbr0
> used_by:
> - /1.0/instances/u1
> - /1.0/instances/u2
> ```

This should have:

`name: lxdbr0` inside of the `lxdbr0` devices section, so:

```
config: {}
description: ""
devices:
  lxdbr0:
    nictype: bridged
    parent: lxdbr0
    type: nic
    name: lxdbr0
name: net-lxdbr0
used_by:
- /1.0/instances/u1
- /1.0/instances/u2
```

Without it, LXD will pick whatever next ethX is available and put that in the volatile config key.
