### ISSUE TITLE
CephFS: ability to mount with FS-Cache enabled

### ISSUE THREAD

**Issue by lblasc** [lxc/lxd#10575]
For CephFS to use [FS-Cache](https://www.kernel.org/doc/Documentation/filesystems/caching/fscache.txt) backend mount option `fsc` needs to be set.

I've tried to set it on volume (`foo`) in CephFS storage pool by using `raw.mount.options` in the profile, unfortunately it didn't work. 
```
config:
  security.nesting: "true"
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr1
    type: nic
  foo:
    path: /bla
    pool: remote-fs
    raw.mount.options: fsc
    source: bla
    type: disk
  root:
    path: /
    pool: local
    type: disk
name: default
used_by:
- /1.0/instances/u1
- /1.0/instances/u2
- /1.0/instances/u3
```

After the change /etc/mtab on container doesn't show `fsc` flag: 
```
root@u3:~# cat /etc/mtab | grep bla
[fd18:70de::499]:3300,[fd18:70de::499]:6789,[fd18:70de::500]:6789,[fd18:70de::501]:6789:/remote-fs /bla ceph rw,relatime,name=admin,secret=<hidden>,acl,mds_namespace=fs1 0 0
```

Most likely this should to be set while creating CephFS storage pool, because there is one CephFS mount for all volumes on that pool, am I correct ?
Looking at the source I don't see any way how to pass this option flag.
https://github.com/lxc/lxd/blob/master/lxd/storage/drivers/driver_cephfs.go#L281

FS-Cache is super useful for lowering our network traffic, I can submit PR for this myself but I'm not sure
whats the right place to add this option and how the option should be called - should it be generic like
`raw.mount.options` ?

Thanks! Let me know if you need any more information on this.

# Required information

 * Distribution: Ubuntu 
 * Distribution version: 22.04 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-25-generic
   * LXC version: 5.0.0
   * LXD version: 5.0.0
   * Storage backend in use: cephfs
