### ISSUE TITLE
Post http://unix.socket/1.0/images: EOF

### ISSUE THREAD

**Issue by aarnaud** [lxc/lxd#1067]
Hi,

I can't publish an privileged container. 

I tried to compare with unprivileged container and the difference is this value : volatile.last_state.idmap: '[]' on volatile.last_state.idmap: '[]'

Result of `lxc config show test_privileged` command
````
name: test_privileged
profiles:
- privileged
config:
  volatile.base_image: 05fd1bdab1865f56ae043ec90137508b96167eff9d500cc1d852ae395a9f1a72
  volatile.eth0.hwaddr: 00:16:3e:f2:a0:b1
  volatile.last_state.idmap: '[]'
devices: {}
ephemeral: false
````

When i tried to publish with `lxc publish test_privileged --alias=test_privileged`
````
error: Post http://unix.socket/1.0/images: EOF
````

thanks
