### ISSUE TITLE
Failed to mount ERROR issues with lxd version 5.4. Can't start my lxd machines that I used for UI apps.

### ISSUE THREAD

**Issue by thepenguinthatwants** [lxc/lxd#10696]
So this problem started after upgrading from lxd version 4 to version 5, I thought 5.4 would've fix the issue from 5.3 but it seems to be still around. 

# Required information

 * Distribution: Manjaro
 * Distribution version: Testing
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 5.4
   * LXD version:5.4
   * Storage backend in use:

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

I have an lxd machine that I've used for launching softwares with UI. I could just easily start firefox and it will open up to my machine through lxd.

Now when I try `lxc start guimachine`, it fails and 

`lxc info --show-log guimachine`
I get

```
lxc guimachine 20220720113952.496 ERROR    conf - ../src/lxc/conf.c:mount_entry:2459 - Operation not permitted - Failed to mount "/var/lib/lxd/devices/guimachine/disk.X0.tmp-.X11--unix-X0" on "/usr/lib/lxc/rootfs/tmp/.X11-unix/X0"
lxc guimachine 20220720113952.496 ERROR    conf - ../src/lxc/conf.c:lxc_setup:4375 - Failed to setup mount entries
lxc guimachine 20220720113952.496 ERROR    start - ../src/lxc/start.c:do_start:1275 - Failed to setup container "guimachine"
lxc guimachine 20220720113952.496 ERROR    sync - ../src/lxc/sync.c:sync_wait:34 - An error occurred in another process (expected sequence number 3)
lxc guimachine 20220720113952.504 WARN     network - ../src/lxc/network.c:lxc_delete_network_priv:3631 - Failed to rename interface with index 0 from "eth0" to its initial name "vethc0f4e9f6"
lxc guimachine 20220720113952.504 ERROR    lxccontainer - ../src/lxc/lxccontainer.c:wait_on_daemonized_start:877 - Received container state "ABORTING" instead of "RUNNING"
lxc guimachine 20220720113952.504 ERROR    start - ../src/lxc/start.c:__lxc_start:2074 - Failed to spawn container "guimachine"
lxc guimachine 20220720113952.504 WARN     start - ../src/lxc/start.c:lxc_abort:1039 - No such process - Failed to send SIGKILL via pidfd 17 for process 311924
lxc 20220720113957.692 ERROR    af_unix - ../src/lxc/af_unix.c:lxc_abstract_unix_recv_fds_iov:218 - Connection reset by peer - Failed to receive response
lxc 20220720113957.692 ERROR    commands - ../src/lxc/commands.c:lxc_cmd_rsp_recv_fds:127 - Failed to receive file descriptors for command "get_state"
```

` lxc config show guimachine --expanded`
Output

```
architecture: x86_64
config:
  boot.autostart: "false"
  environment.DISPLAY: :0
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20201209)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20201209"
  image.type: squashfs
  image.version: "18.04"
  raw.idmap: both 1000 1000
  user.user-data: |
    #cloud-config
    runcmd:
      - 'sed -i "s/; enable-shm = yes/enable-shm = no/g" /etc/pulse/client.conf'
      - 'echo export PULSE_SERVER=unix:/tmp/.pulse-native | tee --append /home/ubuntu/.profile'
    packages:
      - x11-apps
      - mesa-utils
      - pulseaudio
  volatile.base_image: 0cb978a481d837eae60e40250faee5cbbff7d5325cac859fbd6222ebee0f1896
  volatile.cloud-init.instance-id: 4569108c-b5f3-4a0f-bcff-835ab538c58f
  volatile.eth0.hwaddr: 00:16:3e:d9:bd:b7
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":101001,"Nsid":1001,"Maprange":64535},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":101001,"Nsid":1001,"Maprange":64535}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":101001,"Nsid":1001,"Maprange":64535},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":101001,"Nsid":1001,"Maprange":64535}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
  volatile.uuid: 5b491b7c-629e-40fd-8387-83c89aa5c868
devices:
  PASocket:
    path: /tmp/.pulse-native
    source: /run/user/1000/pulse/native
    type: disk
  X0:
    path: /tmp/.X11-unix/X0
    source: /tmp/.X11-unix/X0
    type: disk
  eth0:
    ipv4.address: 10.41.134.199
    nictype: bridged
    parent: lxdbr0
    type: nic
  mygpu:
    type: gpu
  myhomedir:
    path: /home/ubuntu/mount
    source: /home/janic/Documents/Jira_caset/guimachine/home
    type: disk
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
- gui
stateful: false
description: ""
```
