### ISSUE TITLE
Understanding disk space allowance and utilization in Virtual Machines

### ISSUE THREAD

**Issue by webdock-io** [lxc/lxd#10813]
In the spirit of the stated goal of feature parity with containers, I have made some observations today regarding disk allowance and utilization when it comes to virtual machines which may merit some attention, or at least some clarification.

Create a virtual machine:

`lxc launch images:ubuntu/focal/cloud testvm --profile testvm --vm`

With a simple profile:

```
config:
  agent.nic_config: "true"
  boot.autostart: "false"
  limits.cpu: "10"
  limits.memory: 10GB
description: ""
devices:
  eth0:
    limits.egress: 1000Mbit
    limits.ingress: 1000Mbit
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    limits.read: 4000iops
    limits.write: 1000iops
    path: /
    pool: lxd
    size: 100GB
    type: disk
name: testvm
```

What's the real disk utilization according to the VM?

```
# lxc exec testvm -- df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            4.6G     0  4.6G   0% /dev
tmpfs           927M  808K  926M   1% /run
/dev/sda2        91G  838M   90G   1% /
tmpfs           4.6G     0  4.6G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           4.6G     0  4.6G   0% /sys/fs/cgroup
tmpfs            50M   13M   38M  25% /run/lxd_agent
/dev/sda1        99M  3.2M   96M   4% /boot/efi
```
100GB to GiB is ~93.13 so you might expect that to be the free space available on / as it would be in a container instance, but I attribute the difference from the reported 91GiB available to be normal as there are other partitions in the block volume taking up some space. Ok no problems here so far I suppose, however you could argue that since I am asking LXD in the profile to give me 100GB for the root (/) partition, that's what I should get.

So anyway, 838M consumed on / while LXD reports:

```
# lxc info testvm --resources
(.. standard stuff)

Resources:
  Processes: 17
  Disk usage:
    root: 6.74GiB
(...standard stuff)
```

Wait, 6.74GiB? Where is that number coming from? zfs list shows:

```
NAME                                                                                  USED  AVAIL     REFER  MOUNTPOINT
lxd/virtual-machines/testvm.block                                                    2.86G   174G     6.74G  -
```

Ok so this is refer usage as reported by ZFS. Hmm. Is this because the Ubuntu image downloaded, unpacked, is this size?

I understand LXD wants to be agnostic as to what's running in the VM so it's out of the question to query with `df -h` inside the VM - but is there really no way of getting a more precise number for real disk utilization than the ZFS refer value? Which I'm not quite sure what refers to, exactly (no pun intended).

I need this number for reporting and today we use `lxc list --format json` which reports this erroneous figure for VMs - I am thinking of solutions here and all I've come up with so far is to query the VM directly with `df -h` myself and override that value on my side.

I can almost guess that this is just a side-effect of how the disk is presented to the VM as a block device and that it may be impossible to get a reading on disk utilization on the host level without entering the VM - but arguably the reported disk utilization is wrong.

PS: Apologies if this is a rehash of something old which has been discussed elsewhere but I could not find any mentions of this specific issue when searching.
