### ISSUE TITLE
LXD fails to rename network device when container is stopped

### ISSUE THREAD

**Issue by parkervcp** [lxc/lxd#10851]
# Required information

 * Distribution: Rocky Linux
 * Distribution version: 9.0 (Blue Onyx)
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.14.0-70.22.1.el9_0.x86_64
   * LXC version: 5.4
   * LXD version: 5.4
   * Storage backend in use: zfs

# Issue description
container fails to start after being stopped due to missing device
`Error: Failed to start device "phys1": Parent device 'enp8s0f0' doesn't exist`

appears to be that lxd isn't able to release the device properly
`network - ../src/src/lxc/network.c:lxc_delete_network_priv:3631 - Failed to rename interface with index 3 from "eth1" to its initial name "enp8s0f0"`

# Steps to reproduce

 1. create profile `lxc profile create phys1`
 2. add physical device to profile`lxc profile device add phys1 phys1 nic nictype=physical parent=enp8s0f0`
 3. create container `lxc launch images:rockylinux/9 rockylinux-test-9`
 4. add profile to container ` lxc profile assign rockylinux-test-9 default,phys1`
 5. start container `lxc start rockylinux-test-9`
 6. stop container `lxc stop rockylinux-test-9`
 7. start container `lxc start rockylinux-test-9`

# Information to attach

 - [x] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

dmesg
```
[   71.407793] physA8E52m: renamed from mac195b3242
[   71.621006] igb 0000:08:00.0 physh80fsi: renamed from enp8s0f0
[   71.632082] eth0: renamed from physA8E52m
[   71.643053] igb 0000:08:00.0 eth1: renamed from physh80fsi
[   74.675524] igb 0000:08:00.0 eth1: igb: eth1 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[   74.676305] IPv6: ADDRCONF(NETDEV_CHANGE): eth1: link becomes ready
[  154.853946] physA8E52m: renamed from eth0
[  155.077038] igb 0000:08:00.0 physh80fsi: renamed from eth1
[  155.087897] mac195b3242: renamed from physA8E52m
[  158.068504] igb 0000:08:00.0 physh80fsi: igb: physh80fsi NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[  158.178180] IPv6: ADDRCONF(NETDEV_CHANGE): physh80fsi: link becomes ready
```
container log
```
[parker@arwen ~]$ lxc info rockylinux-test-9 --show-log
Name: rockylinux-test-9
Status: STOPPED
Type: container
Architecture: x86_64
Created: 2022/08/24 23:32 EDT
Last Used: 2022/08/25 10:26 EDT

Log:

lxc rockylinux-test-9 20220825142615.587 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc rockylinux-test-9 20220825142615.587 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3598 - newgidmap binary is missing
lxc rockylinux-test-9 20220825142615.587 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc rockylinux-test-9 20220825142615.587 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3598 - newgidmap binary is missing
lxc rockylinux-test-9 20220825142633.353 WARN     attach - ../src/src/lxc/attach.c:get_attach_context:477 - No security context received
lxc rockylinux-test-9 20220825142633.353 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc rockylinux-test-9 20220825142633.353 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3598 - newgidmap binary is missing
lxc rockylinux-test-9 20220825142739.536 WARN     network - ../src/src/lxc/network.c:lxc_delete_network_priv:3631 - Failed to rename interface with index 3 from "eth1" to its initial name "enp8s0f0"
lxc rockylinux-test-9 20220825142739.597 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc rockylinux-test-9 20220825142739.598 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3598 - newgidmap binary is missing
```

**Comment by stgraber** [comment]
Looks like that's because the container has renamed it:
```
[  155.077038] igb 0000:08:00.0 physh80fsi: renamed from eth1
```

For liblxc to be able to rename the interface, it needs to be named the way it's expecting at the time the container is stopped.
In this case it looks like there was no `eth1` to be found, so the rename failed.

**Comment by parkervcp** [comment]
It starts as `enp8s0f0` on the host os, which is the device name, I even have that specified in the `/etc/sysconfig/network-scripts/ifcfg-enp8s0f0` file where `DEVICE=enp8s0f0` and `NAME=enp8s0f0`

I can try telling it to use eth1 instead on the host level.

**Comment by stgraber** [comment]
I'm not talking about the host OS.

**Comment by stgraber** [comment]
What the log looks like is that the container was started once with the device correctly named enp8s0f0 on the host, the container then renamed that device and then the container stopped. This then cause the interface to be moved back to the host without its name getting restored as liblxc was unable to locate the interface named `eth1` at that time.

**Comment by parkervcp** [comment]
What can I get for you to help identify a fix here?

**Comment by stgraber** [comment]
```
root@v1:~# lxc profile create phys1
Profile phys1 created
root@v1:~# lxc profile device add phys1 phys1 nic nictype=physical parent=enp6s0
Device phys1 added to phys1
root@v1:~# lxc init images:rockylinux/9 rockylinux-test-9
Creating rockylinux-test-9
root@v1:~# lxc profile assign rockylinux-test-9 default,phys1
Profiles default,phys1 applied to rockylinux-test-9
root@v1:~# lxc start rockylinux-test-9
root@v1:~# lxc stop rockylinux-test-9
root@v1:~# lxc start rockylinux-test-9
root@v1:~# 
```

**Comment by stgraber** [comment]
If you need a one time fix for your host device, you can likely run `ip link set dev eth1 name enp8s0f0`

**Comment by parkervcp** [comment]
I resolved by adding `net.ifnames=0 biosdevname=0` to my `GRUB_CMDLINE_LINUX`. I then set up names in the ifcfg files as well in `/etc/sysconfig/network-scripts/ifcfg-eth*`

This is a fix, but not a particularly good one, I would rather not have done that.

I can set up a vm to test the default setup moving forward to test this more in rocky 9

**Comment by stgraber** [comment]
Still not sure what's causing issue in your case as I've followed your steps pretty closely and can't seem to reproduce the issue here.

**Comment by parkervcp** [comment]
I am unsure as to why it doesn't rename back to the enp name either.

**Comment by tomponline** [comment]
If you can recreate the problem, then I would like to see the following:

* `ip a` on the LXD host (before the container is started).
* `ip a` inside the container after it has been started.
* `ip a` on the LXD host after the container has been stopped.

Its possible that something inside the container is renaming the interface.
  
> I am unsure as to why it doesn't rename back to the enp name either.
If the interface has been renamed inside the container after LXD has set it up, then it won't know which interface to rename back to the original name on the host and so it does nothing. Then when the container stops the kernel will move the interface back to the host using the name it was inside the container (unless something on the host then renames it as it appears on the host).

**Comment by parkervcp** [comment]
I have done that before and inside the container it renamed to `eth1`. When it stopped it renamed to `physA8E52m`.

I am spinning up a vm for testing here soon.

**Comment by tomponline** [comment]
I suppose it could also be caused by another interface on the host taking the original interface's name while it was moved into the container, which would prevent the original one being renamed back to it.

**Comment by parkervcp** [comment]
none of the other interfaces changed when I was looking.

**Comment by tomponline** [comment]
Hrm, either that or something is changing the index of the interface (if thats possible).

I'd suggest try disabling network manager in the container and seeing if that fixes it, at least that will give a pointer as to what is happening.

**Comment by parkervcp** [comment]
I have a vm with 2 nics. The primary is a macvlan. The secondary is in the phys1 profile.

profiles are here.
```
[root@localhost ~]# lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: macvlan
    parent: enp1s0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/instances/rockylinux-test-9
[root@localhost ~]# lxc profile show phys1
config: {}
description: ""
devices:
  phys1:
    nictype: physical
    parent: enp7s0
    type: nic
name: phys1
used_by:
- /1.0/instances/rockylinux-test-9
```

before starting the container on the host
```
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:ad:25:1b brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.36/24 brd 192.168.122.255 scope global dynamic noprefixroute enp1s0
       valid_lft 3584sec preferred_lft 3584sec
    inet6 fe80::5054:ff:fead:251b/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: enp7s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:c3:9c:7d brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.34/24 brd 192.168.122.255 scope global dynamic noprefixroute enp7s0
       valid_lft 3589sec preferred_lft 3589sec
    inet6 fe80::7508:5a2f:247b:8dd1/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

after starting the container in the container
```
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:c3:9c:7d brd ff:ff:ff:ff:ff:ff
    altname enp7s0
    inet 192.168.122.34/24 brd 192.168.122.255 scope global dynamic noprefixroute eth1
       valid_lft 3407sec preferred_lft 3407sec
    inet6 fe80::b52b:6db5:f65d:58d/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

before stopping the container on the host
```
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:ad:25:1b brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.36/24 brd 192.168.122.255 scope global dynamic noprefixroute enp1s0
       valid_lft 3043sec preferred_lft 3043sec
    inet6 fe80::5054:ff:fead:251b/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: physoJPTRF: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 52:54:00:c3:9c:7d brd ff:ff:ff:ff:ff:ff
    altname enp7s0
```

dmesg
```
[  201.201620] physaPm4LV: renamed from macc4ae5016
[  201.205221] eth0: renamed from physaPm4LV
[  269.499641] physaPm4LV: renamed from eth0
[  269.505659] macc4ae5016: renamed from physaPm4LV
[  314.418558] phys5WlDo7: renamed from mac7a31a959
[  314.479774] e1000e 0000:07:00.0 enp7s0: NIC Link is Down
[  314.485565] e1000e 0000:07:00.0 physoJPTRF: renamed from enp7s0
[  314.489848] eth0: renamed from phys5WlDo7
[  314.494673] e1000e 0000:07:00.0 eth1: renamed from physoJPTRF
[  317.287614] e1000e 0000:07:00.0 eth1: NIC Link is Up 1000 Mbps Full Duplex, Flow Control: Rx/Tx
[  317.288081] IPv6: ADDRCONF(NETDEV_CHANGE): eth1: link becomes ready
[  559.082300] phys5WlDo7: renamed from eth0
[  559.142031] e1000e 0000:07:00.0 eth1: NIC Link is Down
[  559.147876] e1000e 0000:07:00.0 physoJPTRF: renamed from eth1
[  559.167282] mac7a31a959: renamed from phys5WlDo7
[  561.314788] e1000e 0000:07:00.0 physoJPTRF: NIC Link is Up 1000 Mbps Full Duplex, Flow Control: Rx/Tx
[  561.315217] IPv6: ADDRCONF(NETDEV_CHANGE): physoJPTRF: link becomes ready
```

**Comment by tomponline** [comment]
Right so that is pretty odd.
Can I see `lxc config show <instance> --expanded` so I can see how those profiles have been applied please?

Can you also show `ip a` on the host after starting the container please?

**Comment by tomponline** [comment]
i would say that "[  559.167282] mac7a31a959: renamed from phys5WlDo7" is suspicious,

**Comment by parkervcp** [comment]
Trying to rename the interface with `ip` with the suggestion above.
```
[root@localhost ~]# ip link set dev physoJPTRF name enp8s0f0
RTNETLINK answers: Device or resource busy
```

Config output
```
[root@localhost ~]# lxc config show rockylinux-test-9 --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Rockylinux 9 amd64 (20220826_02:48)
  image.os: Rockylinux
  image.release: "9"
  image.serial: "20220826_02:48"
  image.type: squashfs
  image.variant: default
  volatile.base_image: e09c6990f0007ff3f0a7b53ace28b5d3e5e043a29c34bc87e6d90490745c0a34
  volatile.cloud-init.instance-id: e205f3c9-c392-470d-bb2a-d7b2495374b4
  volatile.eth0.host_name: macd738dc95
  volatile.eth0.hwaddr: 00:16:3e:bb:26:b1
  volatile.eth0.last_state.created: "false"
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.phys1.host_name: enp7s0
  volatile.phys1.last_state.created: "false"
  volatile.phys1.last_state.hwaddr: 52:54:00:c3:9c:7d
  volatile.phys1.last_state.mtu: "1500"
  volatile.phys1.name: eth1
  volatile.uuid: b70c1848-842d-42b7-a627-7416ed89b3b3
devices:
  eth0:
    name: eth0
    nictype: macvlan
    parent: enp1s0
    type: nic
  phys1:
    nictype: physical
    parent: enp7s0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
- phys1
stateful: false
description: ""
```

**Comment by parkervcp** [comment]
`ip -a` on the host while the vm is running
```
[root@localhost ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:ad:25:1b brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.36/24 brd 192.168.122.255 scope global dynamic noprefixroute enp1s0
       valid_lft 3430sec preferred_lft 3430sec
    inet6 fe80::5054:ff:fead:251b/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
[root@localhost ~]# 
```

**Comment by tomponline** [comment]
Also, for completeness can you add a `name: eth1` setting to your `phys1` NIC so its explicit and see if that helps.

**Comment by parkervcp** [comment]
So far as i know there are no left over processes. There is only a single container. This is my first time working with LXD.

```
[root@localhost ~]# lxc profile show phys1
config: {}
description: ""
devices:
  eth1:
    name: eth1
    nictype: physical
    parent: enp7s0
    type: nic
name: phys1
used_by:
- /1.0/instances/rockylinux-test-9
```
