### ISSUE TITLE
Breaks on 4 level `$HOME` dir path, Permission error, No network error in container.

### ISSUE THREAD

**Issue by chris001** [lxc/lxd#10874]
# Required information

 * Distribution: Ubuntu
 * Distribution version:  22.04
 * The output of "lxc info" or if that fails: 
   * Kernel version: `5.15.0-47-generic`
   * LXC version: `5.5`
   * LXD version: `5.5`
   * Storage backend in use:  `zfs`

# Issue description

1. `lxd` appears to break when my `home` dir is `/home/domain/homes/$USER` instead of `/home/$USER` ?? As a result, `lxd` and `lxc` commands fail unless run with `sudo`, even though `groups` shows my user is member of the `lxd` group! 

2. Containers fail to obtain a private `10.x.x.x` IP address from `lxd` bridge `lxdbr0` !

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

1 ``lxd` and `lxc` commands require `sudo` even though my user is a member of the `lxd` group, verified `lxd` shows up when you run `groups`!
When your run `lxd` or `lxc` without `sudo`, the error is: `cannot create user data directory: /home/mydomain/homes/chris/snap/lxd/23537: Permission denied`

2. `lxc` containers fail to obtain private IP address from `lxdbr0` bridge, presumably via `DHCP` !

# Steps to reproduce

 1. `sudo apt install snapd && sudo snap install lxd && sudo usermod -aG lxd $USER && newgrp lxd && newgrp && sudo lxd init`
 2. `lxc launch ubuntu: friday`
 4. Even 30 seconds later `lxc list`  shows container never gets an IP address!
 5. `lxc shell friday`
 6. `ping 8.8.8.8` fails.  `ping github.com` fails.
 7. `logout`

# Information to attach

 - [x] Any relevant kernel output (`dmesg`)  Not sure.
 - [x] Container log (`lxc info NAME --show-log`)
```
lxc friday 20220902224221.655 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc friday 20220902224221.657 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3598 - newgidmap binary is missing
lxc friday 20220902224221.665 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc friday 20220902224221.666 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3598 - newgidmap binary is missing
```
 - [x] Container configuration (`lxc config show NAME --expanded`)
```
sudo lxc config show friday --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20220824)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20220824"
  image.type: squashfs
  image.version: "20.04"
  volatile.base_image: e299296138c256b79dda4e61ac7454cf4ac134b43f5521f1ac894f49a9421d00
  volatile.cloud-init.instance-id: cc7e1095-6183-4b1c-8c0c-2b76ea9478c2
  volatile.eth0.host_name: veth1708b777
  volatile.eth0.hwaddr: 00:16:3e:10:af:7a
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.last_state.ready: "false"
  volatile.uuid: c33dd908-60cc-466c-a1c7-7c743d0618e0
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

 - [x] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
```
/var/snap/lxd/common/lxd/logs/lxd.log :
time="2022-09-02T18:37:22-04:00" level=warning msg=" - Couldn't find the CGroup network priority controller, network priority will be ignored"
time="2022-09-02T18:37:22-04:00" level=warning msg="Instance type not operational" driver=qemu err="KVM support is missing (no /dev/kvm)" type=virtual-machine
```

 - [x] Output of the client with --debug   Not sure.
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)   `lxc monitor`  has no obviously unusual output.
