### ISSUE TITLE
LXC Container Creation not working without Screen using NodeJS

### ISSUE THREAD

**Issue by dziebart** [lxc/lxd#10879]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04.1 LTS
 * The output of "lxc info":
 ```
 # lxc info
config:
  core.https_address: '[::]:8443'
  images.auto_update_interval: "0"
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
<OMITTED>
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    <OMITTED>
    -----END CERTIFICATE-----
  certificate_fingerprint: e23c03b810cbbc434218c00bf0555f8ca21c1548b0dceeec6945a0e71e7cf275
  driver: lxc
  driver_version: 5.0.1
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    idmapped_mounts: "true"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "true"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.15.0-46-generic
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "22.04"
  project: default
  server: lxd
  server_clustered: false
  server_event_mode: full-mesh
  server_name: system-1-dc
  server_pid: 1297
  server_version: 5.0.1
  storage: dir
  storage_version: "1"
  storage_supported_drivers:
  - name: btrfs
    version: 5.4.1
    remote: false
  - name: cephfs
    version: 15.2.16
    remote: true
  - name: dir
    version: "1"
    remote: false
  - name: lvm
    version: 2.03.07(2) (2019-11-30) / 1.02.167 (2019-11-30) / 4.45.0
    remote: false
  - name: zfs
    version: 2.1.4-0ubuntu0.1
    remote: false
  - name: ceph
    version: 15.2.16
    remote: true
```

# Issue description

I have discovered a strange behavior when using NodeJs to install and manage lxd-containers. 
Normally I would use a bash-script, which just invokes commands like these:
```
snap/bin/lxc init integrator:ubuntu-20-04-managed-srv s-c-7-srv-a -n br0 -s default --no-profiles -q
```
Which works fine when I run the script.

Now when I use NodeJS and the function `exec` from `child_process` to run the script like this:
```
  exec(/opt/myscript.sh, (error, stdout) => {
      if ( error ) {
          return reject(error);
      }

      resolve(stdout);
  });
```

The script suddenly halts at the `init` command. I can see in my process-tree, that the init is, in fact, running but not really doing anything:
```
root     1160985  0.0  0.1 1088648 14084 ?       Sl   15:20   0:00 lxc init integrator:ubuntu-20-04-managed-srv s-c-7-srv-a -n br0 -s default --no-profiles -q
``` 
And it will continue to do so until I manually kill it.
It seems like the command is waiting for something, but pipeing `echo y` does not work.

On the other hand, when I edit the script, so that the command runs in a separate screen, the init works flawlessly:
```
screen -S "Container_Create" -d -m /snap/bin/lxc init integrator:ubuntu-20-04-managed-srv s-c-7-srv-a -n br0 -s default --no-profiles -q
```
Note, that the script itself has a shebang, so it can't be a scenario, where sh instead of bash is used.
Also Note, that `lxc launch` will also not work without creating a screen first.

Is this expected behaviour? Does `lxc` need a TTY to work? What is the "minimum" `lxc` will work with?
