### ISSUE TITLE
macvlan interface on VMs do not have multi-queue enabled

### ISSUE THREAD

**Issue by dnegreira** [lxc/lxd#10873]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
  [lxc info](https://pastebin.ubuntu.com/p/4xDwK4ft6D/)
  Tested with 4.0/stable and 5.0/stable channels
 
# Issue description

Multi-queue does not seem to be enabled for virtual machines with macvlan interfaces

```
root@mvlant01:~# grep processor /proc/cpuinfo | wc -l
8
root@mvlant01:~# ethtool -L enp5s0
no channel parameters changed.
current values: rx 0 tx 0 other 0 combined 1
```

Profile
```
ubuntu@intent-jennet:~$ lxc profile show macvlan-test
config: {}
description: Default LXD profile
devices:
  eth0:
    nictype: macvlan
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: macvlan-test
used_by:
- /1.0/instances/mvlant01
- /1.0/instances/mvlant02

```

# Steps to reproduce

Launch the VM with the above profile and more than one cpu:
1) lxc launch ubuntu: testvm --vm -p macvlan-test -c limits.cpu=4
2) lxc exec testvm bash
3) ethtool -l <interface> and it shows only `Combined: 1` instead of `Combined: 4`

```
root@testvm:~# ethtool -l enp5s0
Channel parameters for enp5s0:
Pre-set maximums:
RX:             0
TX:             0
Other:          0
Combined:       1
Current hardware settings:
RX:             0
TX:             0
Other:          0
Combined:       1
```
