### ISSUE TITLE
Cannot download some files from Internet

### ISSUE THREAD

**Issue by microcoder** [lxc/lxd#10921]
# Required information

 * Distribution: 
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.19.7 MANJARO
   * LXC version: 5.5
   * LXD version: 5.5
   * Storage backend in use: BTRFS

# Issue description

 I cannot download some files from Internet to container. Don't works wget, apk update and etc...

```
lxc exec jupyter -- wget https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
Connecting to dl-cdn.alpinelinux.org (151.101.86.133:443)
```

And In log file on the host system writing next message:

```
sudo tail -n3 -f /var/log/lxd/jupyter/lxc.log
/src/lxc/attach.c:get_attach_context:477 - No security context received
```

And request is hang... But when I try to downloads another file, for example, then download very well:

```
lxc exec jupyter -- wget https://hsto.org/r/w1560/webt/l8/3u/km/l83ukmshtxtanhyi4src9hmnqkm.png
Connecting to hsto.org (188.114.99.192:443)
saving to 'l83ukmshtxtanhyi4src9hmnqkm.png'
l83ukmshtxtanhyi4src 100% |*****************************************************************************************************************| 19734  0:00:00 ETA
'l83ukmshtxtanhyi4src9hmnqkm.png' saved
```

Ping from the container to file host doesn’t have trouble:

```
lxc exec jupyter -- ping 151.101.86.133
PING 151.101.86.133 (151.101.86.133): 56 data bytes
64 bytes from 151.101.86.133: seq=0 ttl=59 time=24.214 ms
64 bytes from 151.101.86.133: seq=1 ttl=59 time=24.323 ms
64 bytes from 151.101.86.133: seq=2 ttl=59 time=24.349 ms
^C
--- 151.101.86.133 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 24.214/24.295/24.349 ms
```

And even more... I can download APKINDEX.tar.gz from my host system without any trouble:

```
wget https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
--2022-09-13 10:01:24--  https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving dl-cdn.alpinelinux.org (dl-cdn.alpinelinux.org)... 151.101.86.133, 2a04:4e42:14::645
Connecting to dl-cdn.alpinelinux.org (dl-cdn.alpinelinux.org)|151.101.86.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 655179 (640K) [application/octet-stream]
Saving to: ‘APKINDEX.tar.gz’

APKINDEX.tar.gz                          100%[===============================================================================>] 639,82K  --.-KB/s    in 0,1s    

2022-09-13 10:01:29 (4,81 MB/s) - ‘APKINDEX.tar.gz’ saved [655179/655179]
```

# Information to attach

 - [ ] Container configuration (`lxc config show NAME --expanded`)
```
lxc config show jupyter --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Alpine 3.16 amd64 (20220912_13:01)
  image.os: Alpine
  image.release: "3.16"
  image.requirements.secureboot: "false"
  image.serial: "20220912_13:01"
  image.type: squashfs
  image.variant: default
  volatile.base_image: d5a4e7b523f1e2ba509124bcfbef0eba7fbbc6d46da0f082c355447d162cb9c5
  volatile.cloud-init.instance-id: e1cb408e-3bdd-4f1c-ad89-b9109fbb3a79
  volatile.eth0.host_name: vethb5bc917d
  volatile.eth0.hwaddr: 00:16:3e:2d:ef:89
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":65536}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 52a038df-cc73-45ab-b3fe-2ca886f9271f
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: ssdpool
    type: disk
ephemeral: false
profiles:
- default
- ssdroot
stateful: false
description: ""
```

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
Nothing...

 - [ ] Output of the client with --debug
[lxc-debug-log.txt](https://github.com/lxc/lxd/files/9581866/lxc-debug-log.txt)

 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
[lxc-monitor.txt](https://github.com/lxc/lxd/files/9581912/lxc-monitor.txt)
