### ISSUE TITLE
Lxd doesn't have KVM images for focal arm64

### ISSUE THREAD

**Issue by Basdbruijne** [lxc/lxd#10939]
In SQA testrun https://solutions.qa.canonical.com/testruns/testRun/66cfff7a-8dd3-43bf-9c2f-fd26071d4467, which is focal on arm64 with lxd latest/stable (5.5-37534be) fails because juju can't find arm64 images for focal kvm:

```
Machine  State    Address         Inst id              Series  AZ     Message
0        started  10.246.200.106  sqa-lab2-node-1-arm  focal   zone1  Deployed
0/lxd/0  started  10.246.200.210  juju-91e9d3-0-lxd-0  focal   zone1  Container started
1        started  10.246.200.107  sqa-lab2-node-2-arm  focal   zone2  Deployed
1/lxd/0  started  10.246.200.209  juju-91e9d3-1-lxd-0  focal   zone2  Container started
1/lxd/1  started  10.246.200.208  juju-91e9d3-1-lxd-1  focal   zone2  Container started
2        started  10.246.200.105  sqa-lab2-node-3-arm  focal   zone3  Deployed
2/lxd/0  started  10.246.200.212  juju-91e9d3-2-lxd-0  focal   zone3  Container started
2/lxd/1  started  10.246.200.213  juju-91e9d3-2-lxd-1  focal   zone3  Container started
3        started  10.246.200.108  sqa-lab2-node-4-arm  focal   zone1  Deployed
3/lxd/0  started  10.246.200.207  juju-91e9d3-3-lxd-0  focal   zone1  Container started
4        started  10.246.200.109  sqa-lab2-node-6-arm  focal   zone3  Deployed
4/lxd/0  started  10.246.200.214  juju-91e9d3-4-lxd-0  focal   zone3  Container started
5        started  10.246.200.200  sqa-lab2-node-7-arm  focal   zone1  Deployed
5/kvm/0  down                     pending              focal          no results for "arm64", "focal", "released", "uefi1.img"
5/lxd/0  started  10.246.200.211  juju-91e9d3-5-lxd-0  focal   zone1  Container started
5/lxd/1  started  10.246.200.217  juju-91e9d3-5-lxd-1  focal   zone1  Container started
6        started  10.246.200.110  sqa-lab2-node-8-arm  focal   zone2  Deployed
6/lxd/0  started  10.246.200.205  juju-91e9d3-6-lxd-0  focal   zone2  Container started
6/lxd/1  started  10.246.200.206  juju-91e9d3-6-lxd-1  focal   zone2  Container started
7        started  10.246.200.203  sqa-lab2-node-9-arm  focal   zone3  Deployed
7/kvm/0  down                     pending              focal          no results for "arm64", "focal", "released", "uefi1.img"
7/lxd/0  started  10.246.200.215  juju-91e9d3-7-lxd-0  focal   zone3  Container started
7/lxd/1  started  10.246.200.216  juju-91e9d3-7-lxd-1  focal   zone3  Container started
8        started  10.246.200.201  vault-1              focal   zone1  Deployed
9        started  10.246.200.204  vault-2              focal   zone2  Deployed
10       started  10.246.200.202  vault-3              focal   zone3  Deployed
```

I've been told that the kvm machines are handled through lxd, hence I'm are opening the bug here.
Logs and configs collected for this testrun can be found here:
https://oil-jenkins.canonical.com/artifacts/66cfff7a-8dd3-43bf-9c2f-fd26071d4467/index.html

**Comment by stgraber** [comment]
Juju does not currently use LXD for virtual machines.

LXD does have access to focal arm64 images (we in fact use those ourselves daily):
```
stgraber@dakara:~$ lxc image info ubuntu:focal/arm64 --vm
Fingerprint: d1361bdb666ba432f6a5a1b79c6e89b05d2c4615ffaad48b989b63be3c5cda22
Size: 543.56MB
Architecture: aarch64
Type: virtual-machine
Public: yes
Timestamps:
    Created: 2022/09/20 00:00 UTC
    Uploaded: 2022/09/20 00:00 UTC
    Expires: 2025/04/23 00:00 UTC
    Last used: never
Properties:
    label: release
    serial: 20220920
    description: ubuntu 20.04 LTS arm64 (release) (20220920)
    type: disk1.img
    os: ubuntu
    release: focal
    version: 20.04
    architecture: arm64
Aliases:
    - 20.04/arm64
    - f/arm64
    - focal/arm64
Cached: no
Auto update: disabled
Profiles: []
```
