### ISSUE TITLE
[MAAS/LXD] Setting dns.mode=none does not prevent dnsmasq from binding to the associated network

### ISSUE THREAD

**Issue by VariableDeclared** [lxc/lxd#10938]
# Required information

 * Distribution: 22.04
 * Distribution version: 22.04.1
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-48-generic
   * LXC version: 5.6
   * LXD version: 5.6
   * Storage backend in use: default
# Issue description

When configuring LXD as a backend for maas configring dns.mode: "none" does not disable dnsmasq from trying to bind to the IP of a bridge network.

I have multiple L2 LXD Bridge networks created using LXC, and I want to disable dnsmasq from binding onto the .1 address of each network, and allow MAAS to manage DNS.

```
Sep 23 11:30:53 pjds-ubuntu dnsmasq[102633]: failed to create listening socket for 10.66.240.1: Address already in use
Sep 23 11:30:53 pjds-ubuntu dnsmasq[102633]: FAILED to start up
```

# Steps to reproduce

 1. Install MAAS to latest stable
 2. Install LXD to latest canddiate
 3. Setup a bridge network and MAAS using the setup procedure from the MAAS site
 4. Setup the LXD network in MAAS and enable managed allocation
 5. Stop lxd
 6. Stop MAAS 
 7. Start MAAS
 8. Start LXD

Observe journalctl for the above log where network configuration fails to complete, due to DNS masq being unable to bind to .1

# Information to attach

 - [x] Any relevant kernel output (`dmesg`) - Not Applicable
 - [x] Container log (`lxc info NAME --show-log`) - Not Applicable
 - [x] Container configuration (`lxc config show NAME --expanded`) - Not Applicable
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)

https://paste.ubuntu.com/p/JNd7CD5hYC/

 - [x] Output of the client with --debug - Not Applicable
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue) - Not Applicable

# Workaround
Change the dnsmasq port with config: 
```
config:
  dns.mode: none
  ipv4.address: 10.66.240.1/24
  ipv4.dhcp: "false"
  ipv4.nat: "true"
  ipv6.address: fd42:9a92:4793:8c96::1/64
  ipv6.nat: "true"
  raw.dnsmasq: port=54
```

**Comment by VariableDeclared** [comment]
LXD Network configuration: 

```
config:
  dns.mode: none
  ipv4.address: 10.66.240.1/24
  ipv4.dhcp: "false"
  ipv4.nat: "true"
  ipv6.address: fd42:9a92:4793:8c96::1/64
  ipv6.nat: "true"
description: ""
name: lxc-kvm
type: bridge
used_by:
- /1.0/instances/apt-mirror?project=infra
- /1.0/instances/bd-vm-test?project=infra
- /1.0/instances/calico-enterprise-test
- /1.0/instances/k8s-worker-0?project=ws-sandbox
- /1.0/instances/k8s-worker-2?project=ws-sandbox
- /1.0/instances/server-iso-builder
- /1.0/instances/test-6?project=ws-sandbox
- /1.0/instances/test-vm-0?project=ws-sandbox
- /1.0/instances/test?project=ws-sandbox
managed: true
status: Created
locations:
- none
```
