### ISSUE TITLE
Unauthorized access to global remote

### ISSUE THREAD

**Issue by MrDaGree** [lxc/lxd#10986]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 5.0.1
   * LXD version: 5.0.1
   * Storage backend in use:

# Issue description

After adding a global remote based off documentation for LXD versions, some remotes work but others do not seem to work despite having servercert in correct directory

```
$ lxc remote list
+-----------------+------------------------------------------+---------------+-------------+--------+--------+--------+
|      NAME       |                   URL                    |   PROTOCOL    |  AUTH TYPE  | PUBLIC | STATIC | GLOBAL |
+-----------------+------------------------------------------+---------------+-------------+--------+--------+--------+
| myremote        | https://myremote:8443                    | lxd           | tls         | NO     | NO     | YES    |
+-----------------+------------------------------------------+---------------+-------------+--------+--------+--------+
```

However I am unable to actually use the remote, instead getting this error:
```
$ lxc list myremote:
Error: not authorized
```

If I run `lxc info myremote:`, I see that the environment section is empty (I don’t see the certificate or any of the other data), whereas a normal/working remote has the certificate and other data populated in this section:
```
environment:
  addresses: []
  architectures: []
  certificate: ""
  certificate_fingerprint: ""
  driver: ""
  driver_version: ""
  firewall: ""
  kernel: ""
  kernel_architecture: ""
  kernel_features: {}
  kernel_version: ""
  lxc_features: {}
  os_name: ""
  os_version: ""
  project: ""
  server: ""
  server_clustered: false
  server_event_mode: ""
  server_name: ""
  server_pid: 0
  server_version: ""
  storage: ""
  storage_version: ""
  storage_supported_drivers: []
  ```
The certificate file is present in /var/snap/lxd/common/global-conf/servercerts/, has the same permissions/owner as other certificates in that directory, etc, yet it won’t work. I have tried restarting the snap.lxd.daemon service with no change in behavior.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
