### ISSUE TITLE
LXC file pull fails when pulling a symlinked file

### ISSUE THREAD

**Issue by webdock-io** [lxc/lxd#11016]
Host: Ubuntu Jammy
VM/container: Ubuntu Jammy (cloud)
LXD v. 5.6

Try pulling a symlinked file, e.g. /etc/localtime with `lxc file pull myserver/etc/localtime -` and it will hang indefinitely. LXD seems to be able to follow symlinks as long as it's not directly to a file (say, if /etc was a symlinked directory, files within are pullable)

This happens in both containers and VMs. At first we thought it was a bug in lxd-agent but after seeing this happen for containers as well, we check `lxc monitor` and we  see this spinning infinitely:

```
location: none
metadata:
  action: instance-file-retrieved
  context:
    path: /usr/share/zoneinfo/UTC
  source: /1.0/instances/lxdlemp81
project: default
timestamp: "2022-10-12T09:24:01.363099634+02:00"
type: lifecycle


location: none
metadata:
  context:
    ip: '@'
    method: GET
    protocol: unix
    url: /1.0/instances/lxdlemp81/files?path=%2Fusr%2Fshare%2Fzoneinfo%2FUTC
    username: root
  level: debug
  message: Handling API request
timestamp: "2022-10-12T09:24:01.363859228+02:00"
type: logging
```
