### ISSUE TITLE
Image exceeds specified volume size by 4096 bytes

### ISSUE THREAD

**Issue by amartin3225** [lxc/lxd#11081]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0
   * LXC version: 5.0.0
   * LXD version: 5.0.0
   * Storage backend in use: ZFS

# Issue description

I'm running LXD 5.0 with ZFS for the storage pool; I have the following in my default profile:
```
  devices:
    root:
      path: /
      pool: mypool
      type: disk
      size: 200GB
```

I then launch a VM using the `images:ubuntu/20.04/desktop` image and successfully create a server. I then publish an image of this server to my LXD image server. However, when I try to launch a new container from the image, it fails because the image is 4096 bytes larger than the size limit:
```
$ lxc launch myimageserver:myimage test
Creating test
Error: Failed instance creation: Failed creating instance from image: Source image size (200000004096) exceeds specified volume size (200000000000)
```

How can I fix this so I can set a limit on the size of disks (to prevent a VM or container from consuming more than its fair share of space) but also be able to launch new servers from images I publish? Thanks!

# Steps to reproduce

 1. Set a size limit on the `/` device on the `default` profile
 2. Launch a VM using the `images:ubuntu/20.04/desktop` image:
 ```
lxc launch images:ubuntu/20.04/desktop myvm --vm
```
 4. Publish an image of this VM
 ```
lxc publish myimageserver:myimage myvm --alias myimage --compression pigz --force
```
 6. Attempt to launch a new VM from the image you published:
 ```
 lxc launch myimageserver:myimage test
 ```

# Information to attach

```
 # lxc image info myimageserver:myimage
Fingerprint: 7e4cae30ed3dd270c86333a3a37b5c4f9ef1d8225685d58b281902876bd2be78
Size: 6279.10MB
Architecture: x86_64
Type: virtual-machine
Public: no
Timestamps:
    Created: 2022/11/01 22:19 UTC
    Uploaded: 2022/11/01 22:20 UTC
    Expires: 2022/11/30 08:01 UTC
    Last used: never
Properties:
    name: myimage
    os: ubuntu
    release: focal
    serial: 20221031_07:43
    variant: desktop
    architecture: amd64
    description: Ubuntu focal amd64 (desktop) (20221031_07:43)
Aliases:
    - myimage
Cached: no
Auto update: disabled
Profiles:
    - default
```
