### ISSUE TITLE
LXD does not cross-check if network forwards conflict with proxy port forwarding

### ISSUE THREAD

**Issue by cricalix** [lxc/lxd#11332]
For context, see https://discuss.linuxcontainers.org/t/how-to-investigate-why-ipv4-proxy-stops-for-one-container/16014/.

# Required information

```
  driver: lxc
  driver_version: 5.0.2
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    idmapped_mounts: "true"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.15.0-58-generic
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "22.04"
  project: default
  server: lxd
  server_clustered: false
  server_event_mode: full-mesh
  server_name: mackerel
  server_pid: 1110326
  server_version: "5.10"
  storage: zfs
  storage_version: 2.1.4-0ubuntu0.1
```

# Issue description

If both `lxc network forward port add lxdbr0` and profile proxy configurations are used to set up port forwarding, a `snap refresh` or `systemctl reload` of lxd will potentially break the firewall rules used to enact the forwarding.

My specific environment is nftables, with `type: proxy`, `nat: "true"` devices set up in profiles.

# Steps to reproduce

1. Boot a new container, using DHCP addressing. (Do not, at this point, enable static/long term memory of addresses in lxd)
2. Add a network forward for a TCP port from the public IP of the host to the internal IP of the container (tcp 25 as an example).
3. Verify the forwarding works (set up something to listen on the port)
4. Add a new profile from default, and add a devices section that sets up a NAT proxy for a port.

For instance, 
```
  proxy_25:
    connect: tcp:10.68.0.103:25   # container ip
    listen: tcp:1.2.3.4:25   # public ip
    nat: "true"
    type: proxy
```

5. Stop and delete the container
6. Create the container again, from the profile that has the proxy device; it should get a different IP. If it doesn't, make it.
7. Verify that the port forwarding works. If it doesn't, reboot the host and see if it does. If it doesn't, I'm not sure what's different from my scenario.
8. `systemctl reload snap.lxd.daemon`
9. Verify that the port forwarding works. It **should not**.

Review `nft list ruleset` for the port. It should appear in several chains with both the current container IP, and the one used in the `network forward port` command.

The network forward should have put the forward in something like `chain fwdprert.lxdbr0`. It'll be a `dnat` rule, with the receiving IP being the old container IP.

The proxy forward should have put the forward in `chain prert.[container].[proxy_name]`. It'll be the same `dnat` rule, but the receiving IP will be the current container IP.

This feels like something that lxd should be able to detect, as it has full context on both network forwards and proxy devices being set up with the same public IP and port.
