### ISSUE TITLE
Unable to set cluster zpool source in preseed

### ISSUE THREAD

**Issue by MrDaGree** [lxc/lxd#11374]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-60-generic
   * LXC version: 5.0.2
   * LXD version: 5.0.2
   * Storage backend in use: zfs

# Issue description

I am working on transitioning to using clustering between my 3 lxd hosts but am struggling to understand how to setup storage pools, specifically with zfs. I already have a zpool created, as a mirror between 2 drives, that I want to use. Normally I would just do like below, but Im not sure how to set the source or additional settings?
```
storage_pools:
- name: default
  driver: zfs
  config:
    source: lxd-storage
    volume.zfs.remove_snapshots: true
    zfs.clone_copy: false
```

I have tried doing the following but it doesnt seem to pick my already created zpool and creates a brand new one: 
```
cluster:
  server_name: <value>
  server_address: <value>
  cluster_address: <value>
  cluster_password: <value>
  cluster_certificate_path: <value>
  member_config:
    - entity: storage-pool
      key: lxd-storage
      name: default
      value: zfs

  enabled: true
```

Just looking for clarification on how exactly I can do this. I was originally looking at [this](https://github.com/lxc/lxd/blob/79d8142dad6c66d393f2ad5e45cbac599de2c350/shared/api/cluster.go#L51) since I couldnt find clearer documentation for it so once I have a better understanding my goal is to update the docs for it as well

**Comment by stgraber** [comment]
Can you show `lxc query /1.0/cluster` from an existing clustered system?

It should show you the expected `member_config` (formatted as JSON).

I think in your case, you want:

```
member_config:
 - entity: storage-pool
   name: default
   key: source
   value: lxd-storage
```

This effectively instructs the joining server that it has a server-specific config key to set for the `source` property on storage-pool `default` and that for this system, the value is `lxd-storage`.

Note that clusters usually use `local` rather than `default`, so you'll want to make sure the pool name matches what's been used for your cluster.
