### ISSUE TITLE
VM config volume should not be a zvol when ZFS pool has volume.zfs.block_mode enabled

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#11403]
This question occurred during the development of this feature:

> tomponline: Should VM config volumes be influenced by the zfs block mode setting, i.e if enabled, should VM config volumes be block volumes with a filesystem, or should that setting only apply to the user-facing volume and the VM config volume remain as a ZFS dataset even if zfs block mode is enabled on the pool?

> stgraber: Those should remain ZFS datasets

However this is not the case:

```
lxc storage show zfs
config:
  size: 30GiB
  source: /var/lib/lxd/disks/zfs.img
  volume.block.filesystem: xfs
  volume.zfs.block_mode: "true"
  zfs.pool_name: zfs
```

```
lxc init images:ubuntu/jammy v1 --vm -s zfs
```

```
sudo zfs list -o name,type zfs/virtual-machines/v1
NAME                     TYPE
zfs/virtual-machines/v1  volume
```

Expected:

```
lxc delete -f v1
lxc storage unset zfs volume.zfs.block_mode
lxc init images:ubuntu/jammy v1 --vm -s zfs

sudo zfs list -o name,type zfs/virtual-machines/v1
NAME                     TYPE
zfs/virtual-machines/v1  filesystem
```

This is a problem because activating and mounting a block backed filesystem is slower than a ZFS dataset and this means making config changes to stopped VMs is slower because they need to mount the config volume to update the backup.yaml file.
