### ISSUE TITLE
Fail to copy a container inside a zvol storage

### ISSUE THREAD

**Issue by alepaes1975** [lxc/lxd#11417]
Hi,

I sucessful created a zfs storage with zvol and xfs. After, I created testezvol container.

```
# lxc storage show zfspool_zvol
config:
  size: 10GB
  source: /var/snap/lxd/common/lxd/disks/zfspool_zvol.img
  volume.block.filesystem: xfs
  volume.zfs.block_mode: "true"
  zfs.pool_name: zfspool_zvol
driver: zfs
used_by:
- /1.0/instances/testezvol
```

When I try to copy this container (to the same storage or another), an error occurs:

```
# lxc copy testezvol testezvolcopy1 -s zfspool_zvol --instance-only 
Error: Create instance from copy: Failed to mount "/dev/zvol/zfspool_zvol/containers/testezvolcopy1" on "/var/snap/lxd/common/lxd/storage-pools/zfspool_zvol/containers/testezvolcopy1" using "xfs": invalid argument
```
