### ISSUE TITLE
`lxc init|launch` does not pick up `description:` from provided YAML configuration

### ISSUE THREAD

**Issue by m-ueberall** [lxc/lxd#11436]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Focal/20.04
 * LXC/LXD version: 5.11-ad0b61e
 * Storage backend in use: ZFS

# Issue description

When specifying the `description` of a container using a YAML configuration file with `lxc init|launch`, it gets ignored.

# Steps to reproduce

Use a YAML configuration as documented in the `lxc init|launch --help` examples (it does not matter whether it's a temporary [Heredoc](https://linuxize.com/post/bash-heredoc/) or an existing file; moving the `description` above `profiles` also has no effect whatsoever, so it's not a case of the last line being ignored):

```
# lxc init --target nodeNN ubuntu:22.04 c01 << EOF
config:
  boot.autostart: "true"
  boot.autostart.priority: "5"
  raw.idmap: |-
    uid 500 500
    gid 4 4
devices:
  pbuilder:
    optional: "true"
    path: /REDACTED
    source: /REDACTED
    type: disk
profiles:
- default-ovn
description: "Weblate server (Ubuntu 22.04 LTS, amd64/x86_64)"
EOF
```

Output:
```
Creating c01
#
```

Everything _but_ the above description has been picked up:
```
# lxc config show c01 | grep -E 'boot.autostart|raw.idmap| uid | gid |pbuilder|^description'
  boot.autostart: "true"
  boot.autostart.priority: "5"
  raw.idmap: |-
    uid 500 500
    gid 4 4
  pbuilder:
description: ""
#
```
