### ISSUE TITLE
GPU id donot work in my container

### ISSUE THREAD

**Issue by fengjk12138** [lxc/lxd#11442]
# Required information

 * Distribution: ubuntu
 * Distribution version: 22.04 TLS
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux 5.15.0-67-generic 74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: 5.0.2
   * LXD version: 5.0.2
   * Storage backend in use: zfs

# Issue description

I set gpu id=0 for my container， but there are two gpu in container. ID property not work. 
And I try `PCI` property, that work well to change number of gpus.

# Steps to reproduce

 1. 
 ```
> lxc config device add testc gpu gpu id=0
Device gpu added to testc
```
2. `lxc start testc`
3. `lxc exec testc -- nvidia-smi`
```log
Sat Mar  4 18:23:51 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.108.03   Driver Version: 510.108.03   CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| 29%   28C    P8    N/A / 100W |      2MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:02:00.0 Off |                  N/A |
| 20%   24C    P8    N/A /  75W |      2MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

# Information to attach

lxc info --resources
```yaml
CPU (x86_64):
  Vendor: GenuineIntel
  Name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Caches:
    - Level 1 (type: Data): 32KiB
    - Level 1 (type: Instruction): 32KiB
    - Level 2 (type: Unified): 256KiB
    - Level 3 (type: Unified): 8MiB
  Cores:
    - Core 0
      Frequency: 800Mhz
      Threads:
        - 0 (id: 0, online: true, NUMA node: 0)
        - 1 (id: 4, online: true, NUMA node: 0)
    - Core 1
      Frequency: 800Mhz
      Threads:
        - 0 (id: 1, online: true, NUMA node: 0)
        - 1 (id: 5, online: true, NUMA node: 0)
    - Core 2
      Frequency: 800Mhz
      Threads:
        - 0 (id: 2, online: true, NUMA node: 0)
        - 1 (id: 6, online: true, NUMA node: 0)
    - Core 3
      Frequency: 800Mhz
      Threads:
        - 0 (id: 3, online: true, NUMA node: 0)
        - 1 (id: 7, online: true, NUMA node: 0)
  Frequency: 800Mhz (min: 800Mhz, max: 4200Mhz)

Memory:
  Free: 6.18GiB
  Used: 9.82GiB
  Total: 16.00GiB

GPUs:
  Card 0:
    NUMA node: 0
    Vendor: NVIDIA Corporation (10de)
    Product: GP107 [GeForce GTX 1050 Ti] (1c82)
    PCI address: 0000:01:00.0
    Driver: nvidia (510.108.03)
    DRM:
      ID: 0
      Card: card0 (226:0)
      Control: controlD64 (226:0)
      Render: renderD128 (226:128)
    NVIDIA information:
      Architecture: 6.1
      Brand: GeForce
      Model: NVIDIA GeForce GTX 1050 Ti
      CUDA Version: 11.6
      NVRM Version: 510.108.03
      UUID: GPU-a4485aae-f20a-494e-ab4b-1d743dcc72ab
  Card 1:
    NUMA node: 0
    Vendor: NVIDIA Corporation (10de)
    Product: GP107 [GeForce GTX 1050 Ti] (1c82)
    PCI address: 0000:02:00.0
    Driver: nvidia (510.108.03)
    DRM:
      ID: 1
      Card: card1 (226:1)
      Control: controlD65 (226:1)
      Render: renderD129 (226:129)
    NVIDIA information:
      Architecture: 6.1
      Brand: GeForce
      Model: NVIDIA GeForce GTX 1050 Ti
      CUDA Version: 11.6
      NVRM Version: 510.108.03
      UUID: GPU-176688b4-3dcc-1c90-a18f-a44b76f539b5

NIC:
  NUMA node: 0
  Vendor: Intel Corporation (8086)
  Product: Ethernet Connection (2) I219-V (15b8)
  PCI address: 0000:00:1f.6
  Driver: e1000e (5.15.0-67-generic)
  Ports:
    - Port 0 (ethernet)
      ID: enp0s31f6
      Address: 18:31:bf:b7:f2:06
      Supported modes: 10baseT/Half, 10baseT/Full, 100baseT/Half, 100baseT/Full, 1000baseT/Full
      Supported ports: twisted pair
      Port type: twisted pair
      Transceiver type: internal
      Auto negotiation: true
      Link detected: true
      Link speed: 1000Mbit/s (full duplex)

Disks:
  Disk 0:
    NUMA node: 0
    ID: sda
    Device: 8:0
    Model: ST500DM002-1BD14
    Type: scsi
    Size: 465.76GiB
    Read-Only: false
    Removable: false
    Partitions:
      - Partition 1
        ID: sda1
        Device: 8:1
        Read-Only: false
        Size: 1.00MiB
      - Partition 2
        ID: sda2
        Device: 8:2
        Read-Only: false
        Size: 200.00GiB
  Disk 1:
    NUMA node: 0
    ID: sdb
    Device: 8:16
    Model: WDC WD10EZEX-60Z
    Type: scsi
    Size: 931.51GiB
    Read-Only: false
    Removable: false
    Partitions:
      - Partition 1
        ID: sdb1
        Device: 8:17
        Read-Only: false
        Size: 931.50GiB
      - Partition 9
        ID: sdb9
        Device: 8:25
        Read-Only: false
        Size: 8.00MiB
```

lxc profile show default
```yaml
config:
  nvidia.runtime: "true"
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
```
lxc config show mycontainer
```yaml
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Ubuntu jammy amd64 (20230303_07:42)
  image.os: Ubuntu
  image.release: jammy
  image.serial: "20230303_07:42"
  image.type: squashfs
  image.variant: default
  volatile.base_image: e52061c15e5fb283d0aff9444580640af21a94f53182924d267a4cba79ef5a20
  volatile.cloud-init.instance-id: 8ef3f73c-6efc-43f6-b10f-11fdf169e2d5
  volatile.eth0.host_name: vetheeee8295
  volatile.eth0.hwaddr: 00:16:3e:30:29:59
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: bf4ea0ff-eeff-4917-afe2-b3a12690d091
devices:
  gpu:
    id: "0"
    type: gpu
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

**Comment by stgraber** [comment]
Can you show `find /dev` inside the container when the problem occurs?

**Comment by fengjk12138** [comment]
lxc exec testc -- find /dev
```log
/dev
/dev/log
/dev/initctl
/dev/core
/dev/shm
/dev/.lxc-boot-id
/dev/stderr
/dev/stdout
/dev/stdin
/dev/fd
/dev/console
/dev/ptmx
/dev/zero
/dev/urandom
/dev/tty
/dev/random
/dev/null
/dev/full
/dev/nvidia-uvm-tools
/dev/nvidia-uvm
/dev/nvidiactl
/dev/.lxd-mounts
find: ‘/dev/.lxd-mounts’: Permission denied
/dev/nvidia1
/dev/nvidia0
/dev/dri
/dev/dri/renderD128
/dev/dri/card0
/dev/lxd
/dev/lxd/sock
/dev/mqueue
/dev/net
/dev/net/tun
/dev/fuse
/dev/pts
/dev/pts/1
/dev/pts/0
/dev/pts/ptmx
```

>

**Comment by fengjk12138** [comment]
> Can you show `find /dev` inside the container when the problem occurs?


And I can use `PCI` to control the GPU. I confuse with that.  I perfer `id`, because it's more clean and  brief.

I edit config with `PCI`.
```yaml
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 22.04 LTS amd64 (release) (20230210)
  image.label: release
  image.os: ubuntu
  image.release: jammy
  image.serial: "20230210"
  image.type: squashfs
  image.version: "22.04"
  volatile.base_image: 6de3bbd44fa9fdaeef6e5a96b03bb0c09b59b6be7d594bcd3beb92c1956250b6
  volatile.cloud-init.instance-id: 0896f78f-7573-4432-9cca-5a61cb139cb0
  volatile.eth0.host_name: vethc778ffcf
  volatile.eth0.hwaddr: 00:16:3e:7c:18:63
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 4a1f31e1-5b02-4674-93fc-25b2bc313d26
devices:
  gpu:
    pci: "0000:02:00.0"
    type: gpu
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

Then I run `lxc exec testc -- nvidia-smi`, result is following
```
Sun Mar  5 02:45:29 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.108.03   Driver Version: 510.108.03   CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:02:00.0 Off |                  N/A |
| 20%   24C    P8    N/A /  75W |      2MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
