### ISSUE TITLE
Windows 11 VM bricks to recovery mode after a couple of restarts

### ISSUE THREAD

**Issue by cube-1u** [lxc/lxd#11454]
After updates are loaded, the system fails to boot with the drive seemingly "missing".  Restoring from snapshot before the updates are allowed to run allows you to reproduce this issue 100% of the time. 

# Required information

 * Distribution: Ubuntu
 * Distribution version: kudu
 * The output of "lxc info" or if that fails:
```  
  driver_version: 5.0.2 | 7.1.0
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    idmapped_mounts: "true"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.19.0-35-generic
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "22.10"
  project: default
  server: lxd
  server_clustered: false
  server_event_mode: full-mesh
  server_name: cube
  server_pid: 96048
  server_version: "5.11"
  storage: zfs
  storage_version: 2.1.5-1ubuntu6
  storage_supported_drivers:
  - name: btrfs
    version: 5.4.1
    remote: false
  - name: ceph
    version: 15.2.17
    remote: true
  - name: cephfs
    version: 15.2.17
    remote: true
  - name: cephobject
    version: 15.2.17
    remote: true
  - name: dir
    version: "1"
    remote: false
  - name: lvm
    version: 2.03.07(2) (2019-11-30) / 1.02.167 (2019-11-30) / 4.47.0
    remote: false
  - name: zfs
    version: 2.1.5-1ubuntu6
    remote: false
```
```
root@cube:/home/user# uname -a
Linux cube 5.19.0-35-generic #36-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 3 18:36:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
root@cube:/home/user# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.10
DISTRIB_CODENAME=kinetic
DISTRIB_DESCRIPTION="Ubuntu 22.10"
root@cube:/home/user# lxd --version
5.11
root@cube:/home/user# lxc --version
5.11
root@cube:/home/user# 
```

# Issue description

I am attempting to run a Win11 VM. All goes well until the 1st round of updates, then brick.

The boot sequence seems to be unable to detect the drives, causing a reboot and then a subsequent UEFI recovery mode that lands the boot process in some kind of degraded windows 11 recovery application that does not work because all the HDDs are missing. 

If you however boot from the CDROM (win11 install media) the HDDs are visible again, you can even tell it to "repair" your windows by pointing at it (HDDs all seems well files are there). Alas, the repair does not work same result. A boot loop into some windows recovery screen. You could if you wanted to perform a re-install which works again until the updates are installed again.

# Steps to reproduce

 1. Install win11 Vm as per popular instructions
 2. Allow the machine to upgrade itself with the latest patches
 3. Observe a freshly minted brick

# Information to attach

```
root@cube:/home/user# lxc config show win11
architecture: x86_64
config:
  limits.cpu: "8"
  limits.memory: 8GiB
  volatile.cloud-init.instance-id: 0e3ba979-c007-4341-927c-33905620aa5a
  volatile.eth0.host_name: tap04607dd1
  volatile.eth0.hwaddr: 00:16:3e:1e:31:8c
  volatile.last_state.power: RUNNING
  volatile.last_state.ready: "false"
  volatile.lxdbr0.hwaddr: 00:16:3e:4d:5b:f4
  volatile.uuid: af53469f-490a-491c-b106-0df55a138a1c
  volatile.vsock_id: "4"
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    size: 250GiB
    type: disk
  vtpm:
    path: /dev/tpm0
    type: tpm
  win11.installer:
    boot.priority: "10"
    source: /home/user/Downloads/win11.lxd.iso
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
