### ISSUE TITLE
Unsupported CGroup setup detected, but lxd used to work in this machine.

### ISSUE THREAD

**Issue by thepenguinthatwants** [lxc/lxd#11481]
Hi guys, for some reasons my machine can't start or work with any lxc/lxd images.

# Required information

 * Distribution: Arch linux
 * Distribution version: Linux archlinux 6.2.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 13 Mar 2023 17:02:08 +0000 x86_64 GNU/Linux
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
Client version: 5.11
Server version: 5.11

   * LXD version:  5.11

   * Storage backend in use: BTRFS

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Step one
```
lxc launch ubuntu:18.04 ubu1804
Output:
Creating ubu1804
Starting ubu1804
Error: Failed to run: /usr/bin/lxd forkstart ubu1804 /var/lib/lxd/containers /var/log/lxd/ubu1804/lxc.conf: exit status 1
Try `lxc info --show-log local:ubu1804` for more info

```

 3. Step two
`lxc info --show-log local:ubu1804`

```
Name: ubu1804
Status: STOPPED
Type: container
Architecture: x86_64
Created: 2023/03/17 17:56 EET
Last Used: 2023/03/17 17:56 EET

Log:

lxc ubu1804 20230317155657.538 ERROR    cgfsng - ../src/lxc/cgroups/cgfsng.c:cgfsng_mount:2139 - No such file or directory - Failed to create cgroup at_mnt 24()
lxc ubu1804 20230317155657.538 ERROR    conf - ../src/lxc/conf.c:lxc_mount_auto_mounts:852 - No such file or directory - Failed to mount "/sys/fs/cgroup"
lxc ubu1804 20230317155657.538 ERROR    conf - ../src/lxc/conf.c:lxc_setup:4433 - Failed to setup remaining automatic mounts
lxc ubu1804 20230317155657.538 ERROR    start - ../src/lxc/start.c:do_start:1272 - Failed to setup container "ubu1804"
lxc ubu1804 20230317155657.538 ERROR    sync - ../src/lxc/sync.c:sync_wait:34 - An error occurred in another process (expected sequence number 4)
lxc ubu1804 20230317155657.542 WARN     network - ../src/lxc/network.c:lxc_delete_network_priv:3631 - Failed to rename interface with index 0 from "eth0" to its initial name "vethef8d9433"
lxc ubu1804 20230317155657.542 ERROR    lxccontainer - ../src/lxc/lxccontainer.c:wait_on_daemonized_start:878 - Received container state "ABORTING" instead of "RUNNING"
lxc ubu1804 20230317155657.542 ERROR    start - ../src/lxc/start.c:__lxc_start:2107 - Failed to spawn container "ubu1804"
lxc ubu1804 20230317155657.542 WARN     start - ../src/lxc/start.c:lxc_abort:1036 - No such process - Failed to send SIGKILL via pidfd 19 for process 8942
```

 4. Step three

 - [ ] Container configuration (`lxc config show NAME --expanded`)

lxc config show ubu1804 --expanded

```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20230303)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20230303"
  image.type: squashfs
  image.version: "18.04"
  volatile.base_image: eac8ed7b2d652de0edf14b6d163ace1948d24123fd7517258545ab420597a7c9
  volatile.cloud-init.instance-id: 7034cc40-517d-47d4-a051-065a6f6c2344
  volatile.eth0.hwaddr: 00:16:3e:a2:51:ed
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
  volatile.last_state.ready: "false"
  volatile.uuid: 497a1d71-01b3-4403-8179-867894b4d094
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
```
time="2023-03-17T17:53:11+02:00" level=warning msg="AppArmor support has been disabled because of lack of kernel support"
time="2023-03-17T17:53:11+02:00" level=warning msg="Unsupported CGroup setup detected, V1 controllers on top of V2 root"
time="2023-03-17T17:53:11+02:00" level=warning msg=" - AppArmor support has been disabled, Disabled because of lack of kernel support"
time="2023-03-17T17:53:11+02:00" level=warning msg=" - Couldn't find the CGroup network priority controller, network priority will be ignored"
time="2023-03-17T17:53:57+02:00" level=error msg="Failed starting instance" action=start created="2023-03-17 15:46:24.043849788 +0000 UTC" ephemeral=false instance=ubu1804 instanceType=container project=default stateful=false used="2023-03-17 15:46:26.928361936 +0000 UTC"
time="2023-03-17T17:56:35+02:00" level=error msg="Failed starting instance" action=start created="2023-03-17 15:56:34.710244103 +0000 UTC" ephemeral=false instance=ubu1804 instanceType=container project=default stateful=false used="1970-01-01 00:00:00 +0000 UTC"
time="2023-03-17T17:56:57+02:00" level=error msg="Failed starting instance" action=start created="2023-03-17 15:56:57.029069332 +0000 UTC" ephemeral=false instance=ubu1804 instanceType=container project=default stateful=false used="1970-01-01 00:00:00 +0000 UTC"
