### ISSUE TITLE
Docker not working inside container

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#11549]
OS Hypervisor is Ubuntu 22.04 LTS

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

LXD is v5.0.2

```
root@rlabdc4-hybr4001 (node):~# lxc --version
5.0.2
```

Profile ot the container:

```
~# lxc config show rlabdc4-cephD001
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Ubuntu jammy amd64 (20230403_07:42)
  image.os: Ubuntu
  image.release: jammy
  image.serial: "20230403_07:42"
  image.type: squashfs
  image.variant: default
  security.nesting: "true" <============= added
  security.syscalls.intercept.bpf: "true"  <============= added
  security.syscalls.intercept.bpf.devices: "true"  <============= added 
  security.syscalls.intercept.mknod: "true"  <============= added
  security.syscalls.intercept.setxattr: "true"  <============= added
  volatile.base_image: 8a543deebfd6911097684506399e75d700edc5be8cc1e08c0ab4fa698b52393b
  volatile.cloud-init.instance-id: 77823234-e474-4bbf-a279-828333835d9c
  volatile.eth0.host_name: veth24c4bebe
  volatile.eth0.hwaddr: 00:16:3e:43:5a:28
  volatile.idmap.base: "0"
  volatile.idmap.current: '[]'
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 5bf68a98-25d9-4e18-b046-ed9fc5eeb359
devices: {}
ephemeral: false
profiles:
- default
- cephD
stateful: false
description: ""
```

In the container it is also ubuntu 22.04

```
root@rlabdc4-cephD001:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

Trying to run the simple docker "hello-world" but it is exiting immediately after start:

```
root@rlabdc4-cephD001:~# docker start 0bf9399f61fe
0bf9399f61fe
root@rlabdc4-cephD001:~# docker ps --all
CONTAINER ID   IMAGE         COMMAND       CREATED          STATUS                      PORTS     NAMES
0bf9399f61fe   hello-world   "/hello"      33 minutes ago   Exited (0) 1 second ago               upbeat_hypatia
a0ed66de8352   ubuntu        "/bin/bash"   43 hours ago     Exited (0) 28 minutes ago             elastic_wright
```

Any clue is welcome.

thanks
