### ISSUE TITLE
Routed network proxy_ndp error

### ISSUE THREAD

**Issue by kamzar1** [lxc/lxd#11631]
Host: Ubuntu 22.04
lxd 5.13
lxd     git-57a5cc6  24804  latest/edge

When trying to add a routed Ipv6:
```
  eth1:
    ipv6.address: 2a0b:bbc0:xxxx::xxxx:xxxx
    nictype: routed
    parent: eno4
    type: nic
```
get:
`Config parsing error: Failed to start device "eth1": Routed mode requires sysctl net.ipv6.conf.eno4.proxy_ndp=1`
```
sysctl config:
/etc/sysctl.conf
net.ipv6.conf.default.autoconf=1
net.ipv6.conf.all.autoconf=1
net.ipv6.conf.eno4.autoconf=1
net.ipv6.conf.eno4.forwarding=1
net.ipv6.conf.all.proxy_ndp=1
net.ipv6.conf.eno4.proxy_ndp=1
```
Though config is activated in sysctl, it gets dectivated by itself and I need to run sysctl -p manually.
I am not sure whether it is nftables or netplan who is deactivating only this  particular config. My guess, netplan.
Is it an upstream bug?  
Yet it affects LXD.
