### ISSUE TITLE
Unknown configuration key: volatile.idmap.next

### ISSUE THREAD

**Issue by WereCatf** [lxc/lxd#11787]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04.2
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-73-generic
   * LXC version: 5.14-7072c7b (snap)
   * LXD version: 5.14-7072c7b (snap)
   * Storage backend in use: btrfs

# Issue description

Attempting to copy a VM errors out with `Error: Invalid config: Unknown configuration key: volatile.idmap.next` even though it seems like the VM was successfully copied. The instance does not have such key, so I have no idea where that error comes from.

# Steps to reproduce

 1. `lxc copy --refresh shinobi shinobi --target-project backup -s backup`
 2. Receive error `Error: Invalid config: Unknown configuration key: volatile.idmap.next`
 3. Go to Github and open an issue?

**Comment by tomponline** [comment]
Can you do show "lxc config show shinobi" on both source and destination.

**Comment by WereCatf** [comment]
> Can you do show "lxc config show shinobi" on both source and destination.

The original:
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20230111)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20230111"
  image.type: disk-kvm.img
  image.version: "20.04"
  limits.cpu: "2"
  limits.memory: 4GiB
  security.secureboot: "false"
  snapshots.expiry: 2d
  snapshots.schedule: '@daily'
  snapshots.schedule.stopped: "true"
  volatile.base_image: 82f82b34a18900c12d0bd7d390ef573f31f2842b31494b55372b4778ec996568
  volatile.cloud-init.instance-id: 40781ae8-d924-4fb0-94c4-c1e271b0df5e
  volatile.eth0.host_name: macf107b699
  volatile.eth0.hwaddr: 00:16:3e:a3:f4:12
  volatile.eth0.last_state.created: "false"
  volatile.last_state.power: RUNNING
  volatile.nvaudio.last_state.pci.driver: vfio-pci
  volatile.nvaudio.last_state.pci.slot.name: "0000:01:00.1"
  volatile.nvgpu.last_state.pci.driver: vfio-pci
  volatile.nvgpu.last_state.pci.slot.name: "0000:01:00.0"
  volatile.uuid: cab259e3-a63f-43c1-aab6-882ee3e0ae4c
  volatile.uuid.generation: cab259e3-a63f-43c1-aab6-882ee3e0ae4c
  volatile.vsock_id: "29"
devices:
  nvaudio:
    address: "01:00.1"
    type: pci
  nvgpu:
    address: "01:00.0"
    type: pci
  root:
    path: /
    pool: default
    size: 20GiB
    type: disk
  videos:
    path: home/Shinobi/videos
    required: "false"
    source: /mnt/shinobi
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

```

The copy:
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20230111)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20230111"
  image.type: disk-kvm.img
  image.version: "20.04"
  limits.cpu: "2"
  limits.memory: 4GiB
  security.secureboot: "false"
  snapshots.expiry: 2d
  snapshots.schedule: '@daily'
  snapshots.schedule.stopped: "true"
  volatile.apply_template: copy
  volatile.base_image: 82f82b34a18900c12d0bd7d390ef573f31f2842b31494b55372b4778ec996568
  volatile.cloud-init.instance-id: 40781ae8-d924-4fb0-94c4-c1e271b0df5e
  volatile.eth0.hwaddr: 00:16:3e:a3:f4:12
  volatile.uuid: cab259e3-a63f-43c1-aab6-882ee3e0ae4c
  volatile.uuid.generation: cab259e3-a63f-43c1-aab6-882ee3e0ae4c
  volatile.vsock_id: "29"
devices:
  nvaudio:
    address: "01:00.1"
    type: pci
  nvgpu:
    address: "01:00.0"
    type: pci
  root:
    path: /
    pool: backup
    size: 20GiB
    type: disk
  videos:
    path: home/Shinobi/videos
    required: "false"
    source: /mnt/shinobi
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
