### ISSUE TITLE
Stateful snaphost fails with read-only file system error.

### ISSUE THREAD

**Issue by IshwarKanse** [lxc/lxd#1485]
OS: Ubuntu 15.10 
LXD version: 0.26
Storage backend: btrfs
CRIU: 1.7.2-2~ubuntu15.10.1~ppa1 

```
ishwar@anonymous:~$ lxc info
apicompat: 1
auth: trusted
environment:
  addresses: []
  architectures:
  - 2
  - 1
  driver: lxc
  driverversion: 1.1.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-23-generic
  server: lxd
  serverpid: 2871
  serverversion: "0.26"
  storage: btrfs
  storageversion: "4.0"
config: {}
public: false
```
```
ishwar@anonymous:~$ lxc snapshot zabbix fresh --stateful --debug
DBUG[01-08|14:47:55] Posting {"name":"fresh","stateful":true}
 to http://unix.socket/1.0/containers/zabbix/snapshots 
DBUG[01-08|14:47:55] Raw response: {"type":"async","status":"OK","status_code":100,"metadata":{"id":"b20d8953-e8e9-4bb5-8a82-fc3f84a22ac9","class":"task","created_at":"2016-01-08T14:47:55.222007693+05:30","updated_at":"2016-01-08T14:47:55.222007693+05:30","status":"Running","status_code":103,"resources":{"containers":["/1.0/containers/zabbix"]},"metadata":null,"may_cancel":false,"err":""},"operation":"/1.0/operations/b20d8953-e8e9-4bb5-8a82-fc3f84a22ac9"}
 
DBUG[01-08|14:47:55] 1.0/operations/b20d8953-e8e9-4bb5-8a82-fc3f84a22ac9/wait 
DBUG[01-08|14:47:56] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"id":"b20d8953-e8e9-4bb5-8a82-fc3f84a22ac9","class":"task","created_at":"2016-01-08T14:47:55.222007693+05:30","updated_at":"2016-01-08T14:47:55.222007693+05:30","status":"Failure","status_code":400,"resources":{"containers":["/1.0/containers/zabbix"]},"metadata":null,"may_cancel":false,"err":"mkdir /var/lib/lxd/snapshots/zabbix/fresh/state: read-only file system"},"operation":""}
 
error: mkdir /var/lib/lxd/snapshots/zabbix/fresh/state: read-only file system
```
