### ISSUE TITLE
container net device (nictype: bridged) left behind at host reboot

### ISSUE THREAD

**Issue by nick4u** [lxc/lxd#1596]
I'm trying to use Open vSwitch with lxd. I've added fake bridge with tag:100 in order to put CT's in coresponding vlans:
\# ovs-vsctl show
567e4c02-ff9a-4f47-82f6-0c182dfa3ec4
    Bridge "br0"
        Port "vlan100"
            tag: 100
            Interface "**vlan100**"
                type: internal
        Port "br0"
            Interface "br0"
                type: internal
    ovs_version: "2.4.0"

I've configured CT ct04:
\# lxc config show ct04
[...]
devices:
  eth0:
    host_name: vlan100ct04
    nictype: bridged
    parent: **vlan100**
    type: nic
[...]

Everything simes to work just fine if you do "_lxc start ct04_" and "_lxc stop ct04_" - device is added to bridge and then removed.
But when host is restarted device vlan100ct04 is left behind. 
so.. after reboot :
\# ovs-vsctl show
567e4c02-ff9a-4f47-82f6-0c182dfa3ec4
    Bridge "br0"
        Port "vlan100"
            tag: 100
            Interface "vlan100"
                type: internal
        Port "vlan100ct04"
            tag: 100
 **           Interface "vlan100ct04"
                error: "could not open network device vlan100ct04 (No such device)"
 **       Port "br0"
            Interface "br0"
                type: internal
    ovs_version: "2.4.0"

\# lxc start ct04
error: Error calling 'lxd forkstart ct04 /var/lib/lxd/containers /var/log/lxd/ct04/lxc.conf': err='exit status 1'
Try `lxc info --show-log ct04` for more info

I must manually remove port from bridge 
\# ovs-vsctl del-port "vlan100ct05"

and then CT starts

**Comment by stgraber** [comment]
Can you paste the output of:

    lxc info

That should let me confirm what version of LXC and other bits you're using.
Up until recently, LXC indeed wasn't particularly aware of openvswitch and its need to remove the ports from OVS on shutdown, but @hallyn fixed that in upstream LXC very recently and I'd expect the current LXC upstream not to suffer from this issue.

**Comment by nick4u** [comment]
I should have put this info at initial post - my fault - this is data before updating lxd today:

```
# lxc info
apicompat: 1
auth: trusted
environment:
  addresses: []
  architectures:
  - 2
  - 1
  driver: lxc
  driverversion: 2.0.0.beta2
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-27-generic
  server: lxd
  serverpid: 4824
  serverversion: 2.0.0.beta2
  storage: zfs
  storageversion: "5"
config:
  storage.zfs_pool_name: lxd
public: false

# dpkg -l|grep lx[cd]
ii  liblxc1                            2.0.0~beta2-0ubuntu2~ubuntu15.10.1~ppa1 amd64        Linux Containers userspace tools (library)
ii  lxc                                2.0.0~beta2-0ubuntu2~ubuntu15.10.1~ppa1 amd64        Linux Containers userspace tools
ii  lxc-templates                      2.0.0~beta2-0ubuntu2~ubuntu15.10.1~ppa1 amd64        Linux Containers userspace tools (templates)
ii  lxcfs                              2.0.0~beta1-0ubuntu1~ubuntu15.10.1~ppa1 amd64        FUSE based filesystem for LXC
ii  lxd                                2.0.0~beta2-0ubuntu1~ubuntu15.10.1~ppa1 amd64        Container hypervisor based on LXC - daemon
ii  lxd-client                         2.0.0~beta2-0ubuntu1~ubuntu15.10.1~ppa1 amd64        Container hypervisor based on LXC - client
ii  python3-lxc                        2.0.0~beta2-0ubuntu2~ubuntu15.10.1~ppa1 amd64        Linux Containers userspace tools (Python 3.x bindings)
```

Just after checking my versions I found pending updates and did them - this is from /var/log/apt/history.log:
```
Start-Date: 2016-02-12  11:04:57
Upgrade: lxd:amd64 (2.0.0~beta1-0ubuntu4~ubuntu15.10.1~ppa1, 2.0.0~beta2-0ubuntu1~ubuntu15.10.1~ppa1), lxd-client:amd64 (2.0.0~beta1-0ubuntu4~ubuntu15.10.1~ppa1, 2.0.0~beta2-0ubuntu1~ubuntu15.10.1~ppa1), libpam-cgfs:amd64 (0.17-0ubuntu3~ubuntu15.10.1~ppa1, 2.0.0~beta1-0ubuntu1~ubuntu15.10.1~ppa1), libseccomp2:amd64 (2.2.3-2ubuntu3~ubuntu15.10.1~ppa1, 2.2.3-3ubuntu1~ubuntu15.10.1~ppa1), lxcfs:amd64 (0.17-0ubuntu3~ubuntu15.10.1~ppa1, 2.0.0~beta1-0ubuntu1~ubuntu15.10.1~ppa1)
End-Date: 2016-02-12  11:05:11

Start-Date: 2016-02-15  08:39:46
Upgrade: lxd:amd64 (2.0.0~beta2-0ubuntu1~ubuntu15.10.1~ppa1, 2.0.0~beta2-0ubuntu2~ubuntu15.10.1~ppa1), lxd-client:amd64 (2.0.0~beta2-0ubuntu1~ubuntu15.10.1~ppa1, 2.0.0~beta2-0ubuntu2~ubuntu15.10.1~ppa1)
End-Date: 2016-02-15  08:39:55
```

This upgrade (thou I see no version number change?) does not fix isue. "lxc info" returns sime strings.
