### ISSUE TITLE
Profile not working

### ISSUE THREAD

**Issue by rdab** [lxc/lxd#1597]
Hello,
I'm trying to create a profile to spin up containers with some default users.

Here is my profile:
```
$ lxc profile show profile1
name: profile1
config:
  limits.memory: 512MB
  user.user-data: |
    #cloud-config
    users:
      - name: barfoo
        gecos: Bar B. Foo
        sudo: ALL=(ALL) NOPASSWD:ALL
        groups: users, admin
        ssh-authorized-keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3QfyI4p4VaLTWBDP3illhPtvUeyToBxEAGoXS4I5kkfNFKEaj/rgaDB1IZ13XHsyT1OYHIdYi0tECDn+EZjs0dDZ6Zq15h/shcm4XzXVcKMGm8DgkymIleWWPIGvlMf2dngurZ7RlZnMhRVbT$
devices: {}
```

The user-data config is from the cloud-config [docs](http://bazaar.launchpad.net/~cloud-init-dev/cloud-init/trunk/view/head:/doc/examples/cloud-config-user-groups.txt)

But when I launch a container `lxc launch ubuntu test -p profile1` it doesn't create the user.

Is it the correct format for the profile?

**Comment by stgraber** [comment]
How did you import that Ubuntu image and what version of LXD is that?

**Comment by rdab** [comment]
LXD info:
```
$ lxc info
apicompat: 1
auth: trusted
environment:
  addresses: []
  architectures:
  - 2
  - 1
  driver: lxc
  driverversion: 2.0.0.beta2
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.19.0-32-generic
  server: lxd
  serverpid: 1424
  serverversion: 2.0.0.beta2
  storage: btrfs
  storageversion: "3.12"
config: {}
public: false
```

I imported the ubuntu image following the steps from the docs:
`lxd-images import ubuntu --alias ubuntu`

Here is the information about the image
```
 lxc image info ubuntu
Fingerprint: 1032903165a677e18ed93bde5057ae6287841ae756d1a6296eef8f2e5a825e4a
Size: 118.21MB
Architecture: x86_64
Public: no
Timestamps:
    Created: 2016/01/14 17:37 UTC
    Uploaded: 2016/01/26 23:54 UTC
    Expires: never
Properties:
    architecture: x86_64
    description: Ubuntu 14.04 LTS server (20160114.5)
    os: ubuntu
    release: trusty
Aliases:
    - ubuntu
```
Thanks for your help @stgraber, you are doing a great work.

**Comment by stgraber** [comment]
Oh, one catch I only just noticed, by passing "-p profile1", your container will not be based on the default profile, so won't have an eth0 device, which I suspect will make cloud-init fail.

Instead you properly want:

    lxc launch ubuntu test -p default -p profile1

Which will make the container be based first on the default profile and then have your profile1 profile be applied on top.

**Comment by stgraber** [comment]
Running with the above command here still failed, looking at /var/log/cloud-init-output.log, I'm seeing:

```
2016-02-15 00:47:03,107 - util.py[WARNING]: Failed to create user barfoo
2016-02-15 00:47:03,108 - util.py[WARNING]: Running users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_users_groups.pyc'>) failed
```

**Comment by stgraber** [comment]
The problem appears to be that the "users" group doesn't exist in the default Ubuntu image, so the user fails to get created. Removing "users" and just having "admin" listed in the groups list, I get:

    stgraber@dakara:~/data/code/lxc/lxd (stgraber/master)$ lxc exec issue1597 id barfoo
    uid=1000(barfoo) gid=1000(barfoo) groups=1000(barfoo),110(admin)

Let me know if I missed anything, but if that's it, it doesn't look like there is a LXD bug here so I guess we can close this issue :)

**Comment by rdab** [comment]
Sorry for taken too long to answer. 
Thanks. That was it. I specified the `default` profile and changed the group for user `barfoo` to admin only and everything worked.

**Comment by rdab** [comment]
I'd like to highlight that currently there is a [bug](https://bugs.launchpad.net/cloud-init/+bug/1356208) reported in the cloud-init project affecting the `groups` keyword when defining the user's groups. The profile example posted in the first question would not work because the groups must be specified without spaces:
```
....
user.user-data: |
    #cloud-config
    users:
      - name: barfoo
        groups: users,admin,other,foo,bar  <-- without spaces
....
```

I hope posting this here helps because the `users` group does exist in the default ubuntu image, so I was very frustated when trying to add a user to several groups using the syntax specified in [cloud-init docs](http://cloudinit.readthedocs.org/en/latest/topics/examples.html#including-users-and-groups) without success.
