### ISSUE TITLE
stateful snapshot is broken (at least on btrfs)

### ISSUE THREAD

**Issue by TechCredi** [lxc/lxd#1599]
--stateful snapshot executes without error, but it's not possible to restore it (even in non-stateful way).

```
# lxc snapshot --stateful newtest statefulsnap

# lxc restore --stateful newtest statefulsnap
error: restore failed

# lxc restore newtest statefulsnap
error: restore failed

# lxc restore newtest statefulsnap
error: restore failed

```

```
# dpkg -l|grep lxd
ii  lxd                                      2.0.0~beta2-0ubuntu1~ubuntu14.04.1~ppa1 amd64        Container hypervisor based on LXC - daemon
ii  lxd-client                               2.0.0~beta2-0ubuntu1~ubuntu14.04.1~ppa1 amd64        Container hypervisor based on LXC - client
```

May be related to https://github.com/lxc/lxd/issues/1485

**Comment by stgraber** [comment]
stateful snapshots are pretty picky on a bunch of things.

I see you're running current LXD (2.0.0.beta2), what version of CRIU are you using and what kernel are you using this with?

**Comment by tchwpkgorg** [comment]
Behaves like in the initial report for me with:

kernel 4.4.0
criu 1.7.2-2~ubuntu14.04.1~ppa1


Also, don't see any "criu image" (or whatever I should be seeing) in /var/lib/lxd/snapshots/containername/snap0 (just have "metadata.yaml,  rootfs,  templates" there).

**Comment by stgraber** [comment]
@tych0

**Comment by colebrumley** [comment]
Also seeing this on a fresh Wily install on a btrfs disk.

```
cole@wily:~$ sudo add-apt-repository ppa:ubuntu-lxc/lxd-git-master && sudo apt-get update && sudo apt-get install criu
... install stuff ...
cole@wily:~$ sudo criu check --ms
Warn  (cr-check.c:592): Skipping PTRACE_O_SUSPEND_SECCOMP check
Warn  (tun.c:58): Skipping tun support check
Warn  (timerfd.c:48): timerfd: Skipping timerfd support check
Warn  (cr-check.c:296): Skipping mnt_id support check
Looks good.
cole@wily:~$ sudo criu --version
Version: 1.7
cole@wily:~$ sudo apt-get install lxd
... install stuff...
cole@wily:~$ newgrp lxd
cole@wily:~$ lxc --version
2.0.0.beta2
cole@wily:~$ lxd --version
2.0.0.beta2
```

When I run CRIU again:
```
cole@wily:~$ sudo criu check --ms; echo $?
139
```
[Here's](http://pastebin.com/bxtWEJdH) an strace of criu when lxd is installed in case it helps.

**Comment by Ases** [comment]
Also broken on my *Xenial* on *btrfs*

Distribution:	Ubuntu Xenial Xerus (development branch)
Release:	16.04
LXD: 2.0.0.beta2
CRIU: Version: 1.8

```
lxc info:
apicompat: 1
auth: trusted
environment:
  addresses:
  - xx.xx.xx.xx:8443
  architectures:
  - 2
  - 1
  driver: lxc
  driverversion: 2.0.0.beta2
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-4-generic
  server: lxd
  serverpid: 3185
  serverversion: 2.0.0.beta2
  storage: btrfs
  storageversion: "4.4"
config:
  core.https_address: xx.xx.xx.xx:8443
  core.trust_password: true
public: false
```
