### ISSUE TITLE
lxc config device add - mount lost after container restart

### ISSUE THREAD

**Issue by tchwpkgorg** [lxc/lxd#1605]
I'm adding a mount in the container with the following command:
```
lxc config device add $CONTAINER_NAME uploads disk source=/srv/deployment/uploads path=/var/www/uploads
```

This is then shown with "lxc config show $CONTAINER_NAME":

```
devices:
  uploads:
    path: /var/www/uploads
    source: /srv/deployment/uploads
    type: disk
```

The mount is visible in the container when it's booted.

However, when we reboot the container (using "reboot" command within the container), the mount is no longer present.
