### ISSUE TITLE
block device backing zpool on lvm isn't detected properly

### ISSUE THREAD

**Issue by nick4u** [lxc/lxd#1662]
Setting limits.read, limits.write for a container :

```
# lxc config show ct04
name: ct04
profiles:
- small
config:
  boot.autostart: "false"
  user.ens.p: "1"
  user.ens.x: "12.2"
  volatile.base_image: 4525094c3dd2c58b0a60feac5e72963942062ea74f2ee08bcba13a7b448712e4
  volatile.eth0.hwaddr: 00:16:3e:3c:e8:b0
  volatile.eth0.name: eth0
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
  volatile.lo.hwaddr: 00:16:3e:02:26:b5
  volatile.lo.name: eth1
devices:
  eth0:
    host_name: vlan100ct04
    nictype: bridged
    parent: vlan100
    type: nic
  root:
    limits.read: 100kB
    limits.write: 100kB
    path: /
    type: disk
```

does (from log):
```
lxc 20160226114116.069 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1960 - cgroup 'blkio.throttle.read_bps_device' set to '252:0 102400'
lxc 20160226114116.069 DEBUG    lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1960 - cgroup 'blkio.throttle.write_bps_device' set to '252:0 102400'
lxc 20160226114116.069 INFO     lxc_cgfs - cgfs.c:do_setup_cgroup_limits:1964 - cgroup has been setup
```

but dev 252:0 is just a :

```
# ls -l /dev |grep 252
brw-rw---- 1 root   disk    252,   0 Feb 26 08:02 dm-0
brw-rw---- 1 root   disk    252,   1 Feb 26 08:02 dm-1
brw-rw---- 1 root   disk    252,   2 Feb 26 08:02 dm-2
root@ubuntu:/dev# dmsetup ls
ubuntu--vg-lxd  (252:2)
ubuntu--vg-swap_1       (252:1)
ubuntu--vg-root (252:0)
root@ubuntu:/dev# lvs
  LV     VG        Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lxd    ubuntu-vg -wi-ao---- 50.00g (not used - not mounted)
  root   ubuntu-vg -wi-ao---- 33.25g
  swap_1 ubuntu-vg -wi-ao----  4.00g
root@ubuntu:/dev# zpool list
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
lxd   49.8G  4.36G  45.4G         -    10%     8%  1.33x  ONLINE  -
root@ubuntu:/dev# mount |grep lxd
lxd on /lxd type zfs (rw,relatime,xattr,noacl)
lxd/containers on /lxd/containers type zfs (rw,relatime,xattr,noacl)
lxd/images on /lxd/images type zfs (rw,relatime,xattr,noacl)
lxd/containers/ct02-bugzilla on /var/lib/lxd/containers/ct02-bugzilla.zfs type zfs (rw,relatime,xattr,noacl)
lxd/containers/ct04 on /var/lib/lxd/containers/ct04.zfs type zfs (rw,relatime,xattr,noacl)
lxd/containers/ct05 on /var/lib/lxd/containers/ct05.zfs type zfs (rw,relatime,xattr,noacl)
lxd/containers/ctMySQL on /var/lib/lxd/containers/ctMySQL.zfs type zfs (rw,relatime,xattr,noacl)
lxd/containers/spid24-pl on /var/lib/lxd/containers/spid24-pl.zfs type zfs (rw,relatime,xattr,noacl)
lxd/images/4525094c3dd2c58b0a60feac5e72963942062ea74f2ee08bcba13a7b448712e4 on /var/lib/lxd/images/4525094c3dd2c58b0a60feac5e72963942062ea74f2ee08bcba13a7b448712e4.zfs type zfs (ro,relatime,xattr,noacl)
/dev/mapper/ubuntu--vg-root on /var/lib/lxd/shmounts type ext4 (rw,relatime,errors=remount-ro,data=ordered)

```
Limits are set on wrong device ... limiting is not working
I am not even sure if enforcing those limits is possible for separate CT's at ZFS without dedicated zvol for each?

Doc storage-backends.md is silent about lack of limits for zfs
Doc configuration.md also states that dev "Type: disk" has required "source" key - there is no such a key in automatically created CT's config
Did I miss come important README section?

# Required information
 * Distribution: Ubuntu
 * Distribution version:15.10
```
#lxc info
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: <cert>
  driver: lxc
  driverversion: 2.0.0.rc3
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-30-generic
  server: lxd
  serverpid: 17135
  serverversion: 2.0.0.beta4
  storage: zfs
  storageversion: "5"
config:
  storage.zfs_pool_name: lxd
public: false
```
