### ISSUE TITLE
live migration : Error (sk-packet.c:420): Can't bind packet socket: Invalid argument

### ISSUE THREAD

**Issue by arsiesys** [lxc/lxd#1668]
Hello, there is my issue :) : 

# Required information
 * Distribution: Ubuntu
 * Distribution version: 14.04
 * The output of "lxc info" 
```
apicompat: 0
auth: trusted
environment:
  addresses:
  - xxx.xxx.xxx.xxx:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
xxxxxx
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0.rc2
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.13.0-79-generic
  server: lxd
  serverpid: 1035
  serverversion: 2.0.0.beta4
  storage: btrfs
  storageversion: "3.12"
config:
  core.https_address: xx.xx.xx.xx:8443
  core.trust_password: true
public: false
```
Same configuration on remote server (but do not use btrfs for test).

# Issue description
lxc live migration failed with error : 
error: Error transferring container data: restore failed:
(00.197685)   1269: Error (sk-packet.c:420): Can't bind packet socket: Invalid argument
(00.208241) Error (cr-restore.c:1304): 15147 killed by signal 9
(00.208498) Error (cr-restore.c:2130): Restoring FAILED.
Please note that I used the last criu sources available on both hosts.

# Steps to reproduce
- init  a new clean container with debian wheezy amd64
- apply migratable and default profile
- start container
- lxc copy test lxd2:

# Information to attach
last container log on source host :
```
lxc 20160226190741.901 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - peer has disconnected
            lxc 20160226190741.970 DEBUG    lxc_start - start.c:signal_handler:337 - container init process exited
            lxc 20160226190741.970 DEBUG    lxc_start - start.c:__lxc_start:1312 - unknown exit status for init: 9
            lxc 20160226190741.970 DEBUG    lxc_start - start.c:__lxc_start:1317 - Pushing physical nics back to host namespace
            lxc 20160226190741.970 DEBUG    lxc_start - start.c:__lxc_start:1320 - Tearing down virtual network devices used by container
            lxc 20160226190741.970 WARN     lxc_conf - conf.c:lxc_delete_network:2904 - failed to remove interface 52 'eth0'
            lxc 20160226190741.970 INFO     lxc_error - error.c:lxc_error_set_and_log:55 - child <17587> ended on signal (9)
            lxc 20160226190741.970 WARN     lxc_conf - conf.c:lxc_delete_network:2904 - failed to remove interface 52 'eth0'
            lxc 20160226190741.970 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'test', config section 'lxc'
            lxc 20160226190742.474 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 369 stop' for container 'test', config section 'lxc'
            lxc 20160226190742.641 WARN     lxc_cgmanager - cgmanager.c:cgm_get:989 - do_cgm_get exited with error
            lxc 20160226191156.452 WARN     lxc_cgmanager - cgmanager.c:cgm_get:989 - do_cgm_get exited with error
```

end of migration log on destination host : 
```
pie: 1d6134
pie: vdso: image [vdso] 0x7ffeed1d6000-0x7ffeed1d8000 [vvar] 0xfffffff>
pie: fffffffff-0xffffffffffffffff
pie: vdso: Runtime vdso mismatches dumpee, generate proxy
pie: vdso: jmp: 0x7ffeed1d6000/0x700 -> 0x24000/0x700 (index 0)
pie: vdso: jmp: 0x7ffeed1d6000/0xf80 -> 0x24000/0xfc0 (index 1)
pie: vdso: jmp: 0x7ffeed1d6000/0xca0 -> 0x24000/0xcb0 (index 2)
pie: vdso: jmp: 0x7ffeed1d6000/0xf60 -> 0x24000/0xfa0 (index 3)
pie: Restoring EXE link
pie: Restoring scheduler params 0.0.0
pie: 1362: Restored
(00.197494)   1269: Restoring resources
(00.197503)   1269: Opening fdinfo-s
(00.197507)   1269: 	Restoring fd 0 (state -> prepare)
(00.197512)   1269: 	Restoring fd 1 (state -> prepare)
(00.197514)   1269: 	Restoring fd 2 (state -> prepare)
(00.197516)   1269: 	Restoring fd 3 (state -> prepare)
(00.197519)   1269: 	Restoring fd 4 (state -> prepare)
(00.197521)   1269: 	Restoring fd 5 (state -> prepare)
(00.197523)   1269: 	Restoring fd 20 (state -> prepare)
(00.197525)   1269: 	Restoring fd 21 (state -> prepare)
(00.197527)   1269: 	Restoring fd 0 (state -> create)
(00.197548)   1269: 		Create fd for 0
(00.197555)   1269: 	Restoring fd 1 (state -> create)
(00.197568)   1269: 		Create fd for 1
(00.197572)   1269: 	Restoring fd 2 (state -> create)
(00.197578)   1269: 		Create fd for 2
(00.197582)   1269: 	Restoring fd 3 (state -> create)
(00.197591)   1269: 		Create fd for 3
(00.197595)   1269: 	Restoring fd 4 (state -> create)
(00.197599)   1269: Opening packet socket id 0xd
(00.197685)   1269: Error (sk-packet.c:420): Can't bind packet socket: Invalid argument
pie: Task 1269  exited, status= 1
(00.208241) Error (cr-restore.c:1304): 15147 killed by signal 9
(00.208498) Error (cr-restore.c:2130): Restoring FAILED.
```
