### ISSUE TITLE
detect backgrounded tasks using stdout/stderr on exit of interactive shell

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1677]
- Distribution: ubuntu 15.10

```
apicompat: 0
auth: trusted
environment:
  addresses:
  - 10.10.1.2:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
...
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0.rc4
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-30-generic
  server: lxd
  serverpid: 1821
  serverversion: 2.0.0.beta4
  storage: btrfs
  storageversion: "4.0"
config:
  core.https_address: '[::]:8443'
public: false
```
# Issue description

When a background job is running, exit from container hangs.
# Steps to reproduce
1. host# lxc exec ct bash
2. ct# tail -f /var/log/syslog &
3. ct# exit 

terminal now hangs waiting for the background job to finish
