### ISSUE TITLE
curl on /dev/lxd/sock returns 500 error

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1751]
(Inside a container)
```
jeroen@develop ~ % curl -v --unix-socket /dev/lxd/sock http://x/1.0/config
*   Trying /dev/lxd/sock...
* Connected to x (/var/lib/lxd/devlxd/sock) port 80 (#0)
> GET /1.0/config HTTP/1.1
> Host: x
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Sat, 12 Mar 2016 21:51:56 GMT
< Content-Length: 27
<
sql: no rows in result set
* Connection #0 to host x left intact
jeroen@develop ~ %
```
Especially the SQL error makes me think something is off
```
# lxc info                                             apicompat: 0
auth: trusted
environment:
  addresses:
  - 10.10.1.2:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE--
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0.rc5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-30-generic
  server: lxd
  serverpid: 26577
  serverversion: 2.0.0.rc1
  storage: btrfs
  storageversion: "4.0"
config:
  core.https_address: '[::]:8443'
public: false
```
