### ISSUE TITLE
lxc snapshot --stateful should create stateless snapshot if criu fails

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#1768]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information
```
 * Distribution: Ubuntu
 * Distribution version: Trusty
 * The output of "lxc info" or if that fails: 
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
[...]
  driver: lxc
  driverversion: 2.0.0.rc10
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-22-generic
  server: lxd
  serverpid: 1637
  serverversion: 2.0.0.rc3
  storage: zfs
  storageversion: "5"
config:
  storage.zfs_pool_name: tank/lxd
public: false
```
# Issue description
However criu is failing during 'lxc snapshot --stateless' (eg. old criu version), 'lxc info' shows stateful snapshots.

# Steps to reproduce
```
$ criu --version
Version: 1.7.2

$ lxc snapshot --stateful x1 foobar
error: checkpoint failed

$ lxc info x1 |grep foobar
  x1/foobar (taken at 2016/03/17 08:22 UTC) (stateful)
```
