### ISSUE TITLE
How does one exactly run Docker in LXD?

### ISSUE THREAD

**Issue by slava-vishnyakov** [lxc/lxd#1770]
# Required information

 * Distribution: Ubuntu 15.10
 * Distribution version: 15.10
 * The output of "lxc info" or if that fails:
```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE---
    ....
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0.rc10
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-27-generic
  server: lxd
  serverpid: 18226
  serverversion: 2.0.0.rc3
  storage: dir
  storageversion: ""
config: {}
public: false
```

# Issue description

I'm trying to run Docker inside LXD but that fails at every step :) 

Maybe we could have a bit more detailed guide than what's available at https://github.com/lxc/lxd#how-can-i-run-docker-inside-a-lxd-container ?

# Steps to reproduce

Install clean Ubuntu 15.10

Install Docker so that we can build Docker from source (`checkout v1.10.0.serge.2`).

We can't build custom binary inside container, since that requires working Docker, so let's build on host.

```
(on host)
apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-wily main" > /etc/apt/sources.list.d/docker.list; \
apt-get update
apt-get install -y docker-engine
```

Build custom Docker from `v1.10.0.serge.2`

```
(on host)
apt-get update && apt-get install -y build-essential
git clone https://github.com/hallyn/docker.git
cd docker
git checkout v1.10.0.serge.2
make build
make binary
```

Run Docker host container

```
(on host)
lxc launch ubuntu:15.10 my-docker-host -p default -p docker
lxc exec my-docker-host bash
```

(now we are inside container, I guess only binary would be not enough and we need all service definition files, so let's install unmodified default Docker first)

```
(in container)
apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install -y docker-engine
```

Now the Docker fails, complaining 

```
Error starting daemon: AppArmor enabled on system but the docker-default profile could not be loaded
```

Ok, let's remove apparmor

```
(in container)
apt-get purge apparmor
```

Now docker daemon starts, bring the custom docker binary from host system to inside container

```
(in container) 
rm /usr/bin/docker

(on host) 
lxc file push bundles/1.10.0/binary/docker-1.10.0 my-docker-host/usr/bin/docker
```

Ok, let's restart docker daemon and make sure we run the patched version

```
(in container)
# sudo service docker restart
# docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   ab8e54b
 Built:        Thu Mar 17 15:08:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   ab8e54b
 Built:        Thu Mar 17 15:08:23 2016
 OS/Arch:      linux/amd64
```

Good, ab8e54b is the commit from https://github.com/hallyn/docker/commits/v1.10.0.serge.2

Let's try to run it..

```
(in container)
# docker run hello-world
docker: Error response from daemon: error creating aufs mount to /var/lib/docker/aufs/mnt/bf39fe22b47ce5670e8ad399bdb4025972d24bf2587cdd470d67fea0ba84821f-init: operation not permitted.
```

Well, I'm stuck :) 

Am I doing it The Stupid Way™? Am I missing something? 
Is this not working because of 15.10? 
I can't seem to get 16.04 running in container - apt-get update fails badly https://pastebin.ubuntu.com/15407782/ 

Little help? 

Can we update https://github.com/lxc/lxd#how-can-i-run-docker-inside-a-lxd-container with more instructions?

Thanks!
