### ISSUE TITLE
Support per-container and per-image storage backend

### ISSUE THREAD

**Issue by onionjake** [lxc/lxd#1784]
# Required information
- Distribution: Ubuntu
- Distribution version: 16.04
- The output of "lxc info":

```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
     <...snip...>
  driver: lxc
  driverversion: 2.0.0.rc11
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-14-generic
  server: lxd
  serverpid: 1823
  serverversion: 2.0.0.rc4
  storage: dir
  storageversion: ""
config:
  storage.zfs_pool_name: lxd_pool
public: false
```
# Issue description

lxd reverts back to dir storage if zfs pool isn't available.  It isn't available because it is on a encrypted luks device.  lxd should fail instead of silently reverting back to `dir`
# Steps to reproduce
1. Setup luks device.  `sudo cryptsetup luksOpen <luks_device> lxd_volume`
2. Run `sudo lxd init`.  Pick `zfs`, create new pool, and `/dev/mapper/lxd_volume`.
3. `lxc info` shows `storage: zfs`.
4. Reboot
5. `lxc info` shows `storage: dir`. `lxc list` and `lxc create` work, but with dir storage.  Expected it to error saying: `lxd storage unavailable` or similar.
