### ISSUE TITLE
Update README with step by step Docker instructions

### ISSUE THREAD

**Issue by mbruzek** [lxc/lxd#1791]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04 
 * The output of "lxc info" or if that fails:
```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: REDACTED
  driver: lxc
  driverversion: 2.0.0.rc11
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-13-generic
  server: lxd
  serverpid: 13632
  serverversion: 2.0.0.rc4
  storage: dir
  storageversion: ""
config: {}
public: false
```
# Issue description

The docker profile does not include a network adapter so when I start a container it has no network apter to reach any network services.

# Steps to reproduce

 1. Step one - lxc launch images:ubuntu/xenial/amd64 xenial --profile docker
 2. Step two - lxc exec xenial /bin/bash
 3. Step three - apt-get update

# Information to attach

I was able to edit the docker profile and add the network device to work around this issue:
```yaml
  eth0:
    name: eth0
    nictype: bridged
    parent: lxcbr0
    type: nic
```
Can we please include some network information in the docker profile so users do not have this same problem?
