### ISSUE TITLE
docker: Error response from daemon: error creating aufs mount

### ISSUE THREAD

**Issue by mbruzek** [lxc/lxd#1792]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info":
```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: REDACTED
  driver: lxc
  driverversion: 2.0.0.rc11
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-13-generic
  server: lxd
  serverpid: 13632
  serverversion: 2.0.0.rc4
  storage: dir
  storageversion: ""
config: {}
public: false
```

# Issue description

While using the docker profile in lxc xenial image I am unable to run any docker containers. I edited/worked around issue #1791 by adding an ethernet device to the docker profile. Then I was able to `apt-get update` and `apt-get install docker.io`. The `docker ps` command ran successfully and I had docker Version: 1.10.2 running successfully. However when I tried to run a docker container I got an error trying to mount aufs.

# Steps to reproduce

1. Step one: Edit docker profile

```
lxc profile edit docker
```
2. Step two:  Add eth0 device

```yaml
  eth0:
    name: eth0
    nictype: bridged
    parent: lxcbr0
    type: nic
```

3. Step three: Launch image with docker profile
 ```
lxc launch images:ubuntu/xenial/amd64 xenial --profile docker
```

 4. Step four: Get inside the container, update, install docker.io

```
lxc exe xenial /bin/bash
# apt-get update && apt-get install -y docker.io
```

 5. Step five:

```
# docker info 
# docker run hello-world
```

# Information to attach

It looks like mounting aufs was not permitted. Is there anything else we need in the docker profile that would allow aufs to mount?
