### ISSUE TITLE
Creating a container by property match fails

### ISSUE THREAD

**Issue by jsuwo** [lxc/lxd#1817]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04.4
 * The output of "lxc info" or if that fails:
   * Kernel version: 3.19.0-43-generic
   * LXC version: 1.1.5
   * LXD version: 2.0.0.rc2
   * Storage backend in use: btrfs

# Issue description

The REST API docs indicate that a container can be created based on a match of one of more image properties:

```
Input (container based on most recent match based on image properties):

{
    "name": "my-new-container",                                         # 64 chars max, ASCII, no slash, no colon and no comma
    "architecture": "x86_64",
    "profiles": ["default"],                                            # List of profiles
    "ephemeral": true,                                                  # Whether to destroy the container on shutdown
    "config": {"limits.cpu": "2"},                                      # Config override.
    "source": {"type": "image",                                         # Can be: "image", "migration", "copy" or "none"
               "properties": {                                          # Properties
                    "os": "ubuntu",
                    "release": "14.04",
                    "architecture": "x86_64"
                }},
}
```

However, LXD appears to return the following error every time:

```
{"error":"must specify one of alias or fingerprint for init from image","error_code":400,"type":"error"}
```

# Steps to reproduce

 1. Create an image and assign it some properties:

```
# lxc image info busybox
Fingerprint: 097e75d6f7419d3a5e204d8125582f2d7bdd4ee4c35bd324513321c645f0c415
Size: 0.77MB
Architecture: x86_64
Public: no
Timestamps:
    Created: 2016/01/11 17:17 UTC
    Uploaded: 2016/03/28 20:19 UTC
    Expires: never
Properties:
    description: Busybox x86_64
    name: busybox-x86_64
    os: Busybox
    architecture: x86_64
Aliases:
    - busybox
Auto update: disabled
```

 2. Attempt to create a container via image property matching:

```
curl -H 'Content-type: application/json'\
     --key ~/.config/lxc/client.key \
     --cert ~/.config/lxc/client.crt \
     -X POST \
     -d '{"name":"test","source":{"type":"image","properties":{"os":"Busybox","architecture":"x86_64"}}}' \
     -k https://127.0.0.1:8443/1.0/containers

{"error":"must specify one of alias or fingerprint for init from image","error_code":400,"type":"error"}
```

To be sure it wasn't something wrong with the properties I had attached to my image, I also tried creating a container in `"mode": pull`, by pulling an image down from images.linuxcontainers.org via property match.  Same result.

```
curl -H 'Content-type: application/json'\
     --key ~/.config/lxc/client.key \
     --cert ~/.config/lxc/client.crt \
     -X POST \
     -d '{"name":"test","source":{"type":"image","mode":"pull","server":"https://images.linuxcontainers.org:8443","properties":{"description": "Ubuntu xenial (s390x) (20160325_03:49)"}}}' \
     -k https://127.0.0.1:8443/1.0/containers

{"error":"must specify one of alias or fingerprint for init from image","error_code":400,"type":"error"}
```

(I tried pulling by image description since the images on images.linuxcontainers.org don't appear to have any other properties associated with them).
