### ISSUE TITLE
container network statistics not correct

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1825]
When using `lxc info ctname` the network statistics are incorrect.

Packets sent and received are identical, which is incorrect:
If you ping a host that drops icmp echo requests, packets sent should increase, and received should not. However, both counters increase.

Also, my gut says that bytes received/sent are also incorrect, but I cannot verify this at the moment:

```
    eth0:
      Bytes received: 13.35GB
      Bytes sent: 187.06MB
      Packets received: 231350387
      Packets sent: 231350387
```

```
% lxc info
apicompat: 0
auth: trusted
environment:
  addresses:
  - 62.148.169.250:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0.rc13
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.13.0-79-generic
  server: lxd
  serverpid: 4044
  serverversion: 2.0.0.rc7
  storage: dir
  storageversion: ""
config:
  core.https_address: 62.148.169.250:8443
public: false
```
