### ISSUE TITLE
Allow for signal forwarding during exec

### ISSUE THREAD

**Issue by bzeller** [lxc/lxd#1830]
# Required information
 * Distribution: Ubuntu 
 * Distribution version: Xenial
 * The output of "lxc info"
```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    .....
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0.rc12
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-15-generic
  server: lxd
  serverpid: 2146
  serverversion: 2.0.0.rc5
  storage: zfs
  storageversion: "5"
config:
  storage.zfs_pool_name: lxd
public: false
```

# Issue description
When running GUI applications inside a LXD container, sending SIGTERM 
to the "lxc exec" PID will result in the lxc process going away but the process
inside the container will continue to run.

# Steps to reproduce

 1. Enable X11 apps for a container
 2. Run any X11 app "lxc exec container -- su -l -s /bin/bash user -c "DISPLAY=:0 xeyes""
 3. send SIGTERM to the lxc exec process
 4. the lxc exec process goes away, but the GUI app will continue to run
