### ISSUE TITLE
script lxc-to-lxd fail to create rootfs

### ISSUE THREAD

**Issue by vince06fr** [lxc/lxd#1901]
Litle bug in the script lxc-to-lxd, when i try to run it, i get : 

```
Copying container rootfs
Traceback (most recent call last):
  File "lxc-to-lxd", line 419, in <module>
    convert_container(container_name, args)
  File "lxc-to-lxd", line 360, in convert_container
    os.mkdir(lxd_rootfs)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/lxd/containers/container1/rootfs'
```

with this traceback, resolve this bug is very easy : 

Just replace ```os.mkdir(lxd_rootfs)``` by ```os.makedirs(lxd_rootfs)```

os.makedirs is like the -p option of mkdir

**Comment by stgraber** [comment]
that would just paper over the real issue which is that LXD didn't create the /var/lib/lxd/containers/container1 path as it should have.

**Comment by vince06fr** [comment]
Maybe the problem is that the script delete this directory and then fail to recreate it because the path don't exist anymore after the deletion

```
if args.copy_rootfs:
        print("Copying container rootfs")
        if not os.path.exists(lxd_rootfs):
            os.mkdir(lxd_rootfs)

        if subprocess.call(["rsync", "-Aa", "--sparse",
                            "--acls", "--numeric-ids", "--hard-links",
                            "%s/" % rootfs, "%s/" % lxd_rootfs]) != 0:
            print("Failed to transfer the container rootfs, skipping...")
            return False
    else:
        if os.path.exists(lxd_rootfs):
            os.rmdir(lxd_rootfs)
```

**Comment by stgraber** [comment]
The script only removes "/var/lib/lxd/containers/NAME/rootfs" if it exists before it moves your existing rootfs into /var/lib/lxd/containers/NAME/rootfs" which is absolutely correct.

The script absolutely never removes "/var/lib/lxd/containers/NAME", it only ever deals with "/var/lib/lxd/containers/NAME/rootfs", so no, your suggested change is still wrong.

**Comment by stgraber** [comment]
It would be far more constructive if you could describe what you're doing rather than how you think the code is wrong :)

What command are your running, what's your source container like, what's the LXD server log, ... then we actually stand a chance to figure this out and fix what needs fixing.

**Comment by vince06fr** [comment]
Ok it is true.

Host ubuntu wily x86_64 kernel 4.2.0-35-generic with lxd stable ppa
scripts installed from github and pylxd installed inside a python3 virtualenv

lxc info : 
```
apicompat: 0
auth: trusted
environment:
  addresses:
  - x.x.x.x:8443
  - 10.0.3.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    XXXXXXXXXXXXXXXXXXXXXXX
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-35-generic
  server: lxd
  serverpid: 26281
  serverversion: 2.0.0
  storage: btrfs
  storageversion: "4.4"
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
public: false
```

lxc-info of source container : 
```
lxc-info -n c1
Name:           c1
State:          RUNNING
PID:            13392
IP:             10.0.3.110
CPU use:        926.30 seconds
BlkIO use:      2.13 GiB
Memory use:     388.71 MiB
KMem use:       0 bytes
Link:           vethXXXXX
 TX bytes:      123.60 MiB
 RX bytes:      161.03 MiB
 Total bytes:   284.63 MiB
```
go to lxd/script directory and activate virtualenv 
(I prefere copy rootfs than mv it for keep the source container integrity safe)

```
(env)root@host:/home/vince06fr/lxd/scripts# lxc-stop -n c1
(env)root@host:/home/vince06fr/lxd/scripts# python lxc-to-lxd --copy-rootfs c1
==> Processing container: c1
Parsing LXC configuration
Checking for existing containers
Validating container name
Validating container mode
Validating container rootfs
Processing network configuration
Processing environment configuration
Processing container boot configuration
Processing container apparmor configuration
Processing container seccomp configuration
Processing container SELinux configuration
Processing container capabilities configuration
Converting container architecture configuration
Unknown architecture, assuming native.
Creating the container
Copying container rootfs
Traceback (most recent call last):
  File "lxc-to-lxd", line 420, in <module>
    convert_container(container_name, args)
  File "lxc-to-lxd", line 361, in convert_container
    os.mkdir(lxd_rootfs)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/lxd/containers/c1/rootfs'
```
search lxc container log : 
```
(env)root@host:/home/vince06fr/lxd/scripts# cat /var/log/lxc/devosi.log
(env)root@host:/home/vince06fr/lxd/scripts#
```
nothing here....
searching the log of the new lxd container, nothing there too : 

```
(venv3) root@host:/home/vince/lxd/scripts# lxc info --show-log c1
Name: c1
Architecture: x86_64
Created: 2016/04/22 12:48 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

```

running the new container don't work because there is no rootfs...

Maybe my workaround is a paper on another probleme and I don't know why the rootfs is not created but without it I cannot migrate my containers .
