### ISSUE TITLE
Publish container as image using REST API: detectCompression failed, err='Unsupported compression.

### ISSUE THREAD

**Issue by patademahesh** [lxc/lxd#1915]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 14.04.4 LTS
 * The output of "lxc info" or if that fails:
```
   apicompat: 0
auth: trusted
environment:
  addresses:
  - 172.18.10.99:8443
  - 10.0.3.1:8443
  architectures:
  - x86_64
  - i686
  driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.19.0-58-generic
  server: lxd
  serverpid: 28734
  serverversion: 2.0.0.rc9
  storage: btrfs
  storageversion: "4.4"
config:
  core.https_address: '[::]'
  core.trust_password: true
public: false
```

# Issue description

I am trying to publish image using source as container but getting below error.

URL: https://172.x.x.x:8443/1.0/images

**JSON POST Data:**
{"properties":"{}","public":false,"source":{"name":"copy5","type":"container"}}

**API Output:**

Array
(
    [type] => sync
    [status] => Success
    [status_code] => 200
    [metadata] => Array
        (
            [id] => ece6c9ba-e47b-4a92-8598-044f23e3e708
            [class] => task
            [created_at] => 2016-04-21T15:36:44.422089024+05:30
            [updated_at] => 2016-04-21T15:36:44.422089024+05:30
            [status] => Failure
            [status_code] => 400
            [resources] => 
            [metadata] => 
            [may_cancel] => 
            [err] => **detectCompression failed, err='Unsupported compression.', tarfile='/var/lib/lxd/images/lxd_build_350295507/lxd_tar_934400381**'
        )

Thank You
Mahesh
