### ISSUE TITLE
Confusion around properties values & filtering

### ISSUE THREAD

**Issue by aguytech** [lxc/lxd#1917]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04
 * "lxc info"
```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
driver: lxc
  driverversion: 1.1.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-35-generic
  server: lxd
  serverpid: 25658
  serverversion: 2.0.0
  storage: lvm
  storageversion: 2.02.98(2) (2012-10-15) / 1.02.77 (2012-10-15) / 4.33.0
config:
  images.auto_update_cached: "true"
  images.auto_update_interval: "24"
  images.remote_cache_expiry: "10"
  storage.lvm_thinpool_name: LXDPool
  storage.lvm_vg_name: ssd
  storage.lvm_volume_size: 2G
public: false
```
# Issue description
Unitl I define properties values of configuration with 'lxc config set' or in profile, the default values of a container can't get touch.
for example : 
`lxc list security.privileged=true`
give me a list of container trusted privileges is present in his configuration
`lxc list security.privileged=false`
list nothing even for the unprivileged container (default value)

### filters for listing runs on which properties ?
I can't filter listing with properties presents in 'lxc list --format json' ? or just with properties are in config file or profile file ?

### boolean value 1 or true are different for filtering
lxc list security.privileged=1
lxc list security.privileged=true
the results depends on which value gave in settings true or 1

# Steps to reproduce
```
lxc image copy images:centos/6/amd64 local: --alias centos6 --auto-update
lxc init centos6 c1
lxc init centos6 c2
lxc init centos6 c3

lxc config set c1 security.privileged true
lxc config set c2 security.privileged 1

lxc list security.privileged=true
lxc list security.privileged=1
lxc list security.privileged=false
lxc list security.privileged=
```

**Comment by stgraber** [comment]
Yeah, looks like we could improve things a bit there.

**Comment by aguytech** [comment]
just a little add ;o)

we can find this text '* A single keyword like "web" which will list any container with "web" in its name.'
in 
`lxc list --help`

Currently the searching is made only with the beginning of container name
lxc list
```
root@fx8320e:~$lxc list
+-----------------+---------+-------------------+------+------------+-----------+
|      NAME       |  STATE  |       IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
+-----------------+---------+-------------------+------+------------+-----------+
| debian8         | RUNNING | 10.0.1.200 (eth0) |      | PERSISTENT | 2         |
+-----------------+---------+-------------------+------+------------+-----------+
| debian8-php-dev | RUNNING | 10.0.1.210 (eth0) |      | PERSISTENT | 2         |
+-----------------+---------+-------------------+------+------------+-----------+
| debian8-php-pro | RUNNING | 10.0.1.211 (eth0) |      | PERSISTENT | 1         |
+-----------------+---------+-------------------+------+------------+-----------+
```
lxc list debian
```
root@fx8320e:~$lxc list debian-php
+-----------------+---------+-------------------+------+------------+-----------+
|      NAME       |  STATE  |       IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
+-----------------+---------+-------------------+------+------------+-----------+
| debian8-php-dev | RUNNING | 10.0.1.210 (eth0) |      | PERSISTENT | 2         |
+-----------------+---------+-------------------+------+------------+-----------+
| debian8-php-pro | RUNNING | 10.0.1.211 (eth0) |      | PERSISTENT | 1         |
+-----------------+---------+-------------------+------+------------+-----------+

```
lxc list php
```
root@fx8320e:~$lxc list php
+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+
root@fx8320e:~$
```

**Comment by stgraber** [comment]
Sounds like we should:
 - Update the help to say that we only match against the beginning of the container name
 - Add regexp support for the container name too (as we have for key=value)

**Comment by stgraber** [comment]
Ok, so the commit above should have improved things a bit by more clearly documenting the behavior and by supporting regexps for container names.

It's still not doing quite what you want for key=value config filtering but improving things further will be pretty difficult. Basically the client only sees config keys set against the container, it doesn't know about the default values and doesn't know what the key means.

Fixing this would require the client knowing about every single configuration key and its default value which would be pretty difficult when we want to support older and newer clients for any daemon, despite the daemon potentially growing more config options.

**Comment by stgraber** [comment]
So as far as documenting current behavior and improving the bits that could be improved, I'm considering this issue fixed.

I'll keep it open for a bit in case you can think of some easy ways to improve things for you.

**Comment by aguytech** [comment]
Effectively, the helping documentation becomes more clear !

Thanks for that, but I do not understand why you cannot retrieve container information that are accessible via the 'lxc info' command?
I do not know the internal structure of your development, but that the command "lxc info" can recover, why "lxc list" can do not?

I understand that create and maintain a parallel list of data is a wrong way but what I'm thinking is a possibility to filter on the container data "owned by itself" and accessible by 'lxc info'.

**Comment by stgraber** [comment]
Filtering on what's shown in "lxc config show <name> --expanded" should work. Let me run through what you put in your report to see if there's something I missed.

**Comment by stgraber** [comment]
Ok, so looks like what we don't have it matching for unset keys, so "lxc list security.privileged=" currently doesn't return anything when it in fact probably should.

**Comment by aguytech** [comment]
here is 
root@fx8320e:~$lxc config show --expanded debian8
```
name: debian8
profiles:
- default
config:
  raw.apparmor: mount options=(rw, nosuid, nodev, noexec), mount options=(ro, nosuid,
    nodev, noexec, remount, strictatime),
  security.privileged: "true"
  volatile.base_image: 09cbd1efc9c2c5a4fc0e833419a01b9c242b93e40a1b057470ad5711a535c3aa
  volatile.eth0.hwaddr: 00:16:3e:9e:55:bb
  volatile.last_state.idmap: '[]'
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    type: disk
  share:
    path: /var/share
    source: /var/lib/lxd/share
    type: disk
ephemeral: false
```
root@fx8320e:~$lxc list security.privileged="true"
```
+-----------------+---------+-------------------+------+------------+-----------+
|      NAME       |  STATE  |       IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
+-----------------+---------+-------------------+------+------------+-----------+
| debian8         | RUNNING | 10.0.1.200 (eth0) |      | PERSISTENT | 2         |
+-----------------+---------+-------------------+------+------------+-----------+
| debian8-php-dev | RUNNING | 10.0.1.210 (eth0) |      | PERSISTENT | 2         |
+-----------------+---------+-------------------+------+------------+-----------+
| debian8-php-pro | RUNNING | 10.0.1.211 (eth0) |      | PERSISTENT | 1         |
+-----------------+---------+-------------------+------+------------+-----------+
```
root@fx8320e:~$lxc list volatile.eth0.hwaddr="00:16:3e:9e:55:bb"
```
error: unknown remote name: "volatile.eth0.hwaddr=00"
```
root@fx8320e:~$lxc list name="debian8"
```
+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+
root@fx8320e:~$
```
