### ISSUE TITLE
append/remove a profile to a container

### ISSUE THREAD

**Issue by aguytech** [lxc/lxd#1920]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04
 * "lxc info"
```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
  driver: lxc
  driverversion: 1.1.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-35-generic
  server: lxd
  serverpid: 1454
  serverversion: 2.0.0
  storage: lvm
  storageversion: 2.02.98(2) (2012-10-15) / 1.02.77 (2012-10-15) / 4.33.0
config:
  images.auto_update_cached: "true"
  images.auto_update_interval: "24"
  images.remote_cache_expiry: "10"
  storage.lvm_thinpool_name: LXDPool
  storage.lvm_vg_name: ssd
  storage.lvm_volume_size: 2G
public: false
```
# Issue description
is it possible to add functions add and remove from profile to the container in the next milestone? instead of apply globally a list of container.

Currently it is necessary to recover the whole of profiles via something like:
`lxc list --format=json | jq -r '.[] | select(.name == "mycontainner") | .profiles [] + ","'`
to add a new one or to remove an old one to finally apply then to container :o(

PS: the part of jq 'select(.name == "mycontainner")' is necessary to select the good container because the selection by part of name is not secure to select a container.
