### ISSUE TITLE
Add a --format option to "lxc image list"

### ISSUE THREAD

**Issue by aguytech** [lxc/lxd#1951]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04
 * "lxc info"
```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
  driver: lxc
  driverversion: 1.1.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-35-generic
  server: lxd
  serverpid: 1499
  serverversion: 2.0.0
  storage: lvm
  storageversion: 2.02.98(2) (2012-10-15) / 1.02.77 (2012-10-15) / 4.33.0
config:
  images.auto_update_cached: "true"
  images.auto_update_interval: "24"
  images.remote_cache_expiry: "10"
  storage.lvm_thinpool_name: LXDPool
  storage.lvm_vg_name: ssd
  storage.lvm_volume_size: 2G
public: false
```

# Issue description
Currently filtering the list of image container works with this properties:
distribution, release, architecture, build, description.
a trick to not give the container name:
lxc image list '' distribution=debian

But to scripting automation of initializing container, I need to get fingerprint (with some filters )

Is it possible to get json information like for lixc list ?
