### ISSUE TITLE
Containers initialized before openvswitch service starts

### ISSUE THREAD

**Issue by nick4u** [lxc/lxd#1953]
System: Ubuntu 16.04 LTS
```
#lxc info
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
<data>
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-21-generic
  server: lxd
  serverpid: 2481
  serverversion: 2.0.0
  storage: zfs
  storageversion: "5"
config:
  storage.zfs_pool_name: lxd
public: false

```

I am using openvswitch 
```
#ovs-vsctl -V
ovs-vsctl (Open vSwitch) 2.5.0
Compiled Mar 10 2016 14:16:49
DB Schema 7.12.1
```

My containers have config like :
```
# lxc config show ct04
name: ct04
profiles:
- small
config:
  boot.autostart: "true"
  user.ens.p: 8i
  user.ens.x: "12.2"
  volatile.base_image: 4525094c3dd2c58b0a60feac5e72963942062ea74f2ee08bcba13a7b448712e4
  volatile.eth0.hwaddr: 00:16:3e:3c:e8:b0
  volatile.eth0.name: eth0
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
devices:
  eth0:
    host_name: vlan100ct04
    limits.max: 1000kbit
    nictype: bridged
    parent: vlan100
    type: nic
  root:
    limits.read: 10MB
    limits.write: 10MB
    path: /
    type: disk
ephemeral: false
```

not all CT's are started after reboot and I think the reason for it is:
```
Apr 27 08:46:07 ubuntu ovs-vsctl[2684]: ovs|00001|vsctl|INFO|Called as ovs-vsctl add-port vlan100 vlan100ct04
Apr 27 08:46:07 ubuntu ovs-vsctl[2684]: ovs|00002|db_ctl_base|ERR|unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
Apr 27 08:46:07 ubuntu ovs-ctl[2025]:  * Starting ovsdb-server
Apr 27 08:46:07 ubuntu ovs-vsctl[3210]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --no-wait -- init -- set Open_vSwitch . db-version=7.12.1
Apr 27 08:46:07 ubuntu ovs-vsctl[3296]: ovs|00001|vsctl|INFO|Called as ovs-vsctl --no-wait set Open_vSwitch . ovs-version=2.5.0 "external-ids:system-id=\"21299820-5e7b-448c-bdf1-d990d011969d\"" "system-type=\"Ubuntu\"" "s
Apr 27 08:46:07 ubuntu ovs-ctl[2025]:  * Configuring Open vSwitch system IDs

```

It seams lxd service has no dependency with openvswitch and tries to start container before vswitch is ready

```
            lxc 20160427084607.211 INFO     lxc_start - start.c:lxc_init:488 - 'ct04' is initialized
            lxc 20160427084607.211 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 165536 range 65536
            lxc 20160427084607.211 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 165536 range 65536
            lxc 20160427084607.219 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 165536 range 65536
            lxc 20160427084607.219 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type g nsid 0 hostid 165536 range 65536
            lxc 20160427084607.225 DEBUG    lxc_start - start.c:__lxc_start:1302 - Not dropping cap_sys_boot or watching utmp
            lxc 20160427084607.225 INFO     lxc_start - start.c:resolve_clone_flags:999 - Cloning a new user namespace
            lxc 20160427084607.344 ERROR    lxc_conf - conf.c:instantiate_veth:2594 - failed to attach 'vlan100ct04' to the bridge 'vlan100': Operation not permitted
            lxc 20160427084607.359 ERROR    lxc_conf - conf.c:lxc_create_network:2871 - failed to create netdev
            lxc 20160427084607.359 ERROR    lxc_start - start.c:lxc_spawn:1066 - failed to create the network
            lxc 20160427084607.359 ERROR    lxc_start - start.c:__lxc_start:1329 - failed to spawn 'ct04'
            lxc 20160427084607.359 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'ct04', config section 'lxc'
            lxc 20160427084607.871 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 9 stop' for container 'ct04', config section 'lxc'
            lxc 20160427084608.019 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160427084608.019 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160427084608.019 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160427084608.025 INFO     lxc_confile - confile.c:config_idmap:1498 - read uid map: type u nsid 0 hostid 165536 range 65536
```
Of course when I later manualy do "lxc start ct04" everything is just fine and CT start

At my dev/test env 1 of 3 CTs fail to start due to this I guess
At prod env with is much faster 4 CTs are spawned to fast.

I would like to add and test systemd dependency (Requires=openvswitch-switch and After=openvswitch-switch) but I am not sure to which one?

```
  lxd-bridge.service                                                                                                        loaded active exited    LXD - network bridge
  lxd-containers.service                                                                                                    loaded active exited    LXD - container startup/shutdown
  lxd.service                                                                                                               loaded active running   LXD - main daemon
  lxd.socket                                                                                                                loaded active running   LXD - unix socket
```
