### ISSUE TITLE
publish, verify the existence of an image before the treatment & the failure

### ISSUE THREAD

**Issue by aguytech** [lxc/lxd#1969]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04
 * "lxc info"
```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
   driver: lxc
  driverversion: 1.1.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-35-generic
  server: lxd
  serverpid: 1499
  serverversion: 2.0.0
  storage: lvm
  storageversion: 2.02.98(2) (2012-10-15) / 1.02.77 (2012-10-15) / 4.33.0
config:
  images.auto_update_cached: "true"
  images.auto_update_interval: "24"
  images.remote_cache_expiry: "10"
  storage.lvm_thinpool_name: LXDPool
  storage.lvm_vg_name: ssd
  storage.lvm_volume_size: 2G
public: false
```
# Issue description

I used lvm.
When I trie d to publish a container to an existing image, the time to writing is consumed but at final an normal error message:
`error: The image already exists: 68fb09223890c59e9af2d1bac9be936a69f888f3c3fc058e32437a4f3748f939`

May be it 's possible to test existence before the treatment ?
Possibly due to lvm use ?

# Steps to reproduce
```
root@fx8320e:~$date '+%s'; lxc publish debian-test2 --alias=debian8-$(date '+%Y%m%d'); date '+%s'
1461880351
Container published with fingerprint: 68fb09223890c59e9af2d1bac9be936a69f888f3c3fc058e32437a4f3748f939
1461880381
root@fx8320e:~$date '+%s'; lxc publish debian-test2 --alias=debian8-$(date '+%Y%m%d'); date '+%s'
1461880428
error: The image already exists: 68fb09223890c59e9af2d1bac9be936a69f888f3c3fc058e32437a4f3748f939
1461880453
root@fx8320e:~$
```
