### ISSUE TITLE
Trouble when exporting a copying image (with lvm)

### ISSUE THREAD

**Issue by aguytech** [lxc/lxd#1972]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04
 * "lxc info"
```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
  driver: lxc
  driverversion: 1.1.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-35-generic
  server: lxd
  serverpid: 1499
  serverversion: 2.0.0
  storage: lvm
  storageversion: 2.02.98(2) (2012-10-15) / 1.02.77 (2012-10-15) / 4.33.0
config:
  images.auto_update_cached: "true"
  images.auto_update_interval: "24"
  images.remote_cache_expiry: "10"
  storage.lvm_thinpool_name: LXDPool
  storage.lvm_vg_name: ssd
  storage.lvm_volume_size: 2G
public: false
```
# Issue description
When I copy an image from images: and I export it I get just a file of meta data, no rootfs file.
Instead if I create a container and publish it, When I export the image I get a correct unified file with meta & rootfs file

**The export of image are made from lvm lv or file in /var/lib/lxd/images ?**

# Steps to reproduce

copying image
```
root@fx8320e:~$lxc image copy images:debian/jessie/amd64 local: --alias debian8 --auto-update
Image copied successfully!
root@fx8320e:~$lxc image export debian8 /tmp
Output is in /tmp
```
publish a container
```
root@fx8320e:~$lxc init debian8 debian-test
Creating debian-test
root@fx8320e:~$lxc publish debian-test --alias=debian-test
Container published with fingerprint: 0e0d9c34bbae4164841c895efb131bc199c81d9f077d8ce5645c0e02cf070e61
root@fx8320e:~$lxc image export debian-test /tmp
Output is in /tmp/0e0d9c34bbae4164841c895efb131bc199c81d9f077d8ce5645c0e02cf070e61.tar.gz
```
lxc image list 
```
+-------------+--------------+--------+----------------------------------------+--------+----------+-------------------------------+
|    ALIAS    | FINGERPRINT  | PUBLIC |              DESCRIPTION               |  ARCH  |   SIZE   |          UPLOAD DATE          |
+-------------+--------------+--------+----------------------------------------+--------+----------+-------------------------------+
| debian-test | 0e0d9c34bbae | no     |                                        | x86_64 | 140.84MB | Apr 29, 2016 at 10:02am (UTC) |
+-------------+--------------+--------+----------------------------------------+--------+----------+-------------------------------+
| debian8     | a31bff875bbb | no     | Debian jessie (amd64) (20160428_22:42) | x86_64 | 104.07MB | Apr 29, 2016 at 9:58am (UTC)  |
+-------------+--------------+--------+----------------------------------------+--------+----------+-------------------------------+
```
ll /tmp
```
-rw-r--r--  1 root   root   147677065 avril 29 12:02 0e0d9c34bbae4164841c895efb131bc199c81d9f077d8ce5645c0e02cf070e61.tar.gz
-rw-------  1 root   root         736 avril 29 12:00 meta-a31bff875bbb3ca36bf00564eaa018d6e03d5e83a15d939395b6e74758614b8c.tar.xz
```

# Information to attach

There are correct links to lvm lv; but a strange difference of size compare to lvm lv occupied size?
ll /var/lib/lxd/images/
```
total 250804
drwx------  2 root root      4096 avril 29 12:02 .
drwxr-xr-x 12 root root      4096 avril 29 12:02 ..
-rw-r--r--  1 root root 147677065 avril 29 12:01 0e0d9c34bbae4164841c895efb131bc199c81d9f077d8ce5645c0e02cf070e61
lrwxrwxrwx  1 root root        73 avril 29 12:01 0e0d9c34bbae4164841c895efb131bc199c81d9f077d8ce5645c0e02cf070e61.lv -> /dev/ssd/0e0d9c34bbae4164841c895efb131bc199c81d9f077d8ce5645c0e02cf070e61
-rw-r--r--  1 root root       736 avril 29 11:55 a31bff875bbb3ca36bf00564eaa018d6e03d5e83a15d939395b6e74758614b8c
lrwxrwxrwx  1 root root        73 avril 29 11:58 a31bff875bbb3ca36bf00564eaa018d6e03d5e83a15d939395b6e74758614b8c.lv -> /dev/ssd/a31bff875bbb3ca36bf00564eaa018d6e03d5e83a15d939395b6e74758614b8c
-rw-r--r--  1 root root 109121916 avril 29 11:58 a31bff875bbb3ca36bf00564eaa018d6e03d5e83a15d939395b6e74758614b8c.rootfs
```
lvdisplay /dev/ssd/0e0d9c34bbae4164841c895efb131bc199c81d9f077d8ce5645c0e02cf070e61
 ```
 --- Logical volume ---
  LV Path                /dev/ssd/0e0d9c34bbae4164841c895efb131bc199c81d9f077d8ce5645c0e02cf070e61
  LV Name                0e0d9c34bbae4164841c895efb131bc199c81d9f077d8ce5645c0e02cf070e61
  VG Name                ssd
  LV UUID                tcLSEe-UC2B-LRRr-kzxT-obFV-x2EM-mdTMPs
  LV Write Access        read/write
  LV Creation host, time fx8320e, 2016-04-29 12:01:57 +0200
  LV Pool name           LXDPool
  LV Status              available
  # open                 0
  LV Size                2,00 GiB
  Mapped size            20,66%
  Current LE             512
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           252:12
```
   
```
lvdisplay /dev/ssd/a31bff875bbb3ca36bf00564eaa018d6e03d5e83a15d939395b6e74758614b8c
  --- Logical volume ---
  LV Path                /dev/ssd/a31bff875bbb3ca36bf00564eaa018d6e03d5e83a15d939395b6e74758614b8c
  LV Name                a31bff875bbb3ca36bf00564eaa018d6e03d5e83a15d939395b6e74758614b8c
  VG Name                ssd
  LV UUID                RYLeL7-XTY4-c3gw-rq9y-bJbW-QdJx-lzzIHU
  LV Write Access        read/write
  LV Creation host, time fx8320e, 2016-04-29 11:58:37 +0200
  LV Pool name           LXDPool
  LV Status              available
  # open                 0
  LV Size                2,00 GiB
  Mapped size            20,66%
  Current LE             512
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           252:10
```
