### ISSUE TITLE
Is there a way to change export format

### ISSUE THREAD

**Issue by aguytech** [lxc/lxd#1973]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04
 * "lxc info"
```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
  driver: lxc
  driverversion: 1.1.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-35-generic
  server: lxd
  serverpid: 1499
  serverversion: 2.0.0
  storage: lvm
  storageversion: 2.02.98(2) (2012-10-15) / 1.02.77 (2012-10-15) / 4.33.0
config:
  images.auto_update_cached: "true"
  images.auto_update_interval: "24"
  images.remote_cache_expiry: "10"
  storage.lvm_thinpool_name: LXDPool
  storage.lvm_vg_name: ssd
  storage.lvm_volume_size: 2G
public: false
```
# Issue description

I can't find a way to change the export format 'split & unified' describe at:
https://github.com/lxc/lxd/blob/master/doc/image-handling.md
https://insights.ubuntu.com/2016/04/01/lxd-2-0-image-management-512/

No information about it in 
```
root@fx8320e:~$lxc image info debian8-init
Fingerprint: a31bff875bbb3ca36bf00564eaa018d6e03d5e83a15d939395b6e74758614b8c
Size: 104.07MB
Architecture: x86_64
Public: no
Timestamps:
    Created: 2016/04/28 23:18 UTC
    Uploaded: 2016/04/29 09:58 UTC
    Expires: never
Properties:
    build: 20160428_22:42
    description: Debian jessie (amd64) (20160428_22:42)
    distribution: debian
    release: jessie
    architecture: amd64
Aliases:
    - debian8-init
Auto update: enabled
root@fx8320e:~$lxc image show debian8-init
autoupdate: true
properties:
  architecture: amd64
  build: "20160428_22:42"
  description: Debian jessie (amd64) (20160428_22:42)
  distribution: debian
  release: jessie
public: false
```

No option information in
`lxc image export --help`

Failed using options
```
root@fx8320e:~$lxc image export debian8-init /tmp --format=split
error: flag provided but not defined: --format
root@fx8320e:~$lxc image export debian8-init /tmp --format split
error: flag provided but not defined: --format
root@fx8320e:~$lxc image export debian8-init /tmp --split
rerror: flag provided but not defined: --split
```
