### ISSUE TITLE
publish a container with an existing image alias

### ISSUE THREAD

**Issue by aguytech** [lxc/lxd#1974]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04
 * "lxc info"
```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
  driver: lxc
  driverversion: 1.1.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-35-generic
  server: lxd
  serverpid: 1499
  serverversion: 2.0.0
  storage: lvm
  storageversion: 2.02.98(2) (2012-10-15) / 1.02.77 (2012-10-15) / 4.33.0
config:
  images.auto_update_cached: "true"
  images.auto_update_interval: "24"
  images.remote_cache_expiry: "10"
  storage.lvm_thinpool_name: LXDPool
  storage.lvm_vg_name: ssd
  storage.lvm_volume_size: 2G
public: false
```
# Issue description

Publish a container with an existing image alias just create a new image without warning or error and produce an orphan image without alias

# Steps to reproduce
```

lxc publish debian8 --alias=debian8
lxc publish debian8 --alias=debian8
lxc image list
+--------------+--------------+--------+----------------------------------------+--------+----------+-------------------------------+
|    ALIAS     | FINGERPRINT  | PUBLIC |              DESCRIPTION               |  ARCH  |   SIZE   |          UPLOAD DATE          |
+--------------+--------------+--------+----------------------------------------+--------+----------+-------------------------------+
| debian8      | 09b1ccac49eb | no     |                                        | x86_64 | 165.53MB | Apr 29, 2016 at 11:49am (UTC) |
+--------------+--------------+--------+----------------------------------------+--------+----------+-------------------------------+
| debian8-init | a31bff875bbb | no     | Debian jessie (amd64) (20160428_22:42) | x86_64 | 104.07MB | Apr 29, 2016 at 9:58am (UTC)  |
+--------------+--------------+--------+----------------------------------------+--------+----------+-------------------------------+
|              | b773ee2632fe | no     |                                        | x86_64 | 165.53MB | Apr 29, 2016 at 11:46am (UTC) |
+--------------+--------------+--------+----------------------------------------+--------+----------+-------------------------------+
```
