### ISSUE TITLE
containers in the process of being created have "ERROR" status in 'lxc list' 

### ISSUE THREAD

**Issue by mikemccracken** [lxc/lxd#1988]
# Required information

 * Distribution: ubuntu
 * Distribution version: xenial

lxc info:
```

apicompat: 0
auth: trusted
environment:
  addresses:
  - 172.16.0.156:8443
  - 10.17.158.1:8443
  architectures:
  - x86_64
  - i686
  driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-21-generic
  server: lxd
  serverpid: 17362
  serverversion: 2.0.0
  storage: zfs
  storageversion: "5"
config:
  core.https_address: '[::]'
  storage.zfs_pool_name: lxd
public: false
```

# Issue description

while creating many containers at once (using juju 2.0 lxd provider), 'watch -n 1 lxc list' shows that a container starts out in ERROR state until switching to STOPPED, then RUNNING.
