### ISSUE TITLE
Changes to /etc/network/interfaces doesn't remain persistent in a copied Xenial container.

### ISSUE THREAD

**Issue by IshwarKanse** [lxc/lxd#1996]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 15.10
 * The output of "lxc info":
```
apicompat: 0
auth: trusted
environment:
  addresses:
  - 172.31.31.35:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-35-generic
  server: lxd
  serverpid: 1241
  serverversion: 2.0.0
  storage: btrfs
  storageversion: "4.4"
config:
  core.https_address: 172.31.31.35
public: false
```

# Issue description
When a Xenial container with changes made to /etc/network/interfaces, like adding a static ip is copied. The copy of the container doesn't have the changes when run. This happens when a copy of Xenial container is created in same host or moving/copying the container to different host. This issue is specific to Xenial container.

# Steps to reproduce

1. lxc launch images:ubuntu/xenial/amd64 test
2. lxc exec test -- bash
3. Static IP added to  /etc/network of the container.
```
# The primary network interface
auto eth0
iface eth0 inet static
address 172.31.31.23
netmask 255.255.255.0
gateway 172.31.31.2
dns-nameservers 8.8.8.8 8.8.4.4
```
4. lxc stop test &&  lxc profile apply test bridged
7. lxc start test
~~~
ishwar@lxdhost:~$ lxc list | grep -i running
| dcjmumbai     | RUNNING | 172.31.31.3 (eth0)  |      | PERSISTENT | 0         |
| test          | RUNNING | 172.31.31.23 (eth0) |      | PERSISTENT | 0         |
| zabbix        | RUNNING | 172.31.31.50 (eth0) |      | PERSISTENT | 0         |
~~~
8. lxc stop test && lxc copy test test2
9. lxc start test2
~~~
ishwar@lxdhost:~$ lxc list | grep -i running
| dcjmumbai     | RUNNING | 172.31.31.3 (eth0)  |      | PERSISTENT | 0         |
| test2         | RUNNING |                     |      | PERSISTENT | 0         |
| zabbix        | RUNNING | 172.31.31.50 (eth0) |      | PERSISTENT | 0         |
~~~
~~~
ishwar@lxdhost:~$ lxc exec test2 -- cat /etc/network/interfaces
# The primary network interface
auto eth0
iface eth0 inet dhcp
~~~
