### ISSUE TITLE
make visible LXD daemon without 'lxd init'

### ISSUE THREAD

**Issue by aguytech** [lxc/lxd#2011]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04
 * "lxc info"
```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
  driver: lxc
  driverversion: 1.1.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-36-generic
  server: lxd
  serverpid: 1597
  serverversion: 2.0.0
  storage: lvm
  storageversion: 2.02.98(2) (2012-10-15) / 1.02.77 (2012-10-15) / 4.33.0
config:
  core.https_address: 192.168.1.200:8443
  core.trust_password: true
  images.auto_update_cached: "true"
  images.auto_update_interval: "24"
  images.remote_cache_expiry: "10"
  storage.lvm_thinpool_name: LXDPool
  storage.lvm_vg_name: ssd
  storage.lvm_volume_size: 2G
public: false
```

# Issue description
after reading https://insights.ubuntu.com/2016/04/01/lxd-2-0-image-management-512/
> Just running a public LXD server
> The easiest way to share LXD images is to run a publicly visible LXD daemon.
> You typically do that by running:
> lxc config set core.https_address "[::]:8443"
> Remote users can then add your server as a public image server with:
> lxc remote add <some name> <IP or DNS> --public

I tried to make visible my daemon (initially don't visible from 'lxd init') with this command:
```
lxc config set core.https_address "192.168.1.200:8443"
lxc config set core.trust_password "mypassword"
service lxd restart
```
and nothing...
'netstat -pln' show me nothing listening in port 8443

After removing all images & all containers & launch "lxd init" and accept to lxd become available over the network
My lxd daemon become effectively available over my network with the same result of configuration for 'lxc info'

What I have missing ?
