### ISSUE TITLE
'error: Invalid value: 1G' after upgrade to LXD 2.0

### ISSUE THREAD

**Issue by karlhaas** [lxc/lxd#2024]
After upgrading LXD some containers are in state ERROR. All operations on those containers show the following error message:

```
# lxc info nexus
error: Invalid value: 1G
```

Maybe I set the config to: lxc config set nexus limits.memory 1G

```
# lxc config set nexus limits.memory 1GB
error: Invalid value: 1G
```

How can I replace the configuration?

**Comment by niko-daniel** [comment]
you can try this one

> lxc config set nexus limits.memory 1GB

**Comment by karlhaas** [comment]
I already did ...
```
lxc config set nexus limits.memory 1GB
error: Invalid value: 1G
```

I can't even delete the container:
```
# lxc delete -if nexus
Remove nexus (yes/no): yes
error: Invalid value: 1G
```

**Comment by stgraber** [comment]
Did you maybe set the memory limit in a profile?

**Comment by stgraber** [comment]
If so, fixing the entry in the profile should fix any container using it.
We do have migration code for that stuff which should have moved everything to the new syntax on upgrade, I'm a bit unsure why it didn't seem to run for you...

**Comment by karlhaas** [comment]
No profile. I set the memory limit for all containers manually.

```
# lxc profile list
default
docker

# lxc profile show default
name: default
config: {}
description: ""
devices:
  eth0:
    nictype: bridged
    parent: lxcbr0
    type: nic

# lxc profile show docker
name: docker
config:
  linux.kernel_modules: overlay, nf_nat
  security.nesting: "true"
description: Profile supporting docker in containers
devices:
  aadisable:
    path: /sys/module/apparmor/parameters/enabled
    source: /dev/null
    type: disk
  fuse:
    path: /dev/fuse
    type: unix-char
```

Is there a way to fix the broken configuration without using lxc?
