### ISSUE TITLE
fstrim error in unprivileged container

### ISSUE THREAD

**Issue by tomposmiko** [lxc/lxd#2030]
I'm not sure whether this should be solved here or in util-linux.

```
Ubuntu Xenial (host + guest)
apicompat: 0
auth: trusted
environment:
  addresses:
  - 10.0.0.4:20004
  - 192.168.122.1:20004
  - 172.17.0.1:20004
  architectures:
  - x86_64
  - i686
  certificate: |
[...]
  driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-21-generic
  server: lxd
  serverpid: 43820
  serverversion: 2.0.0
  storage: zfs
  storageversion: "5"
config:
  core.https_address: 0.0.0.0:20004
  core.trust_password: true
  storage.zfs_pool_name: tank/lxd
public: false
```

```
# /etc/cron.weekly/fstrim:
fstrim: cannot open /dev/.lxd-mounts: Permission denied
fstrim: /dev/fuse: not a directory
fstrim: /dev/lxd: FITRIM ioctl failed: Operation not permitted
```

As you can see, there is a cron
```
#!/bin/sh
# trim all mounted file systems which support it
/sbin/fstrim --all || true
```
```
/dev/md0 on /dev/.lxd-mounts type ext4 (rw,noatime,discard,errors=remount-ro,data=ordered)
```

It appears as a normal ext4 filesystem, that's why it wants it.
