### ISSUE TITLE
unable to use NetworkManager to manage eth0 in container

### ISSUE THREAD

**Issue by pgassmann** [lxc/lxd#2048]
# Issue description

After installing NetworkManager inside lxd container, NetworkManager shows eth0 as unmanaged and cannot bring up the interface. Which is required to manage connections on top of the interface. E.g. openvpn

I tried with centos/7/amd4 and ubuntu/xenial/amd64
I tried various "solutions" I could find on the internet. None of it helped.

Is there a way to let NetworkManager inside a container manage the main interface eth0?

# Steps to reproduce

 1. Install NetworkManager inside a container. `yum install NetworkManager-tui` on centos,` apt install network-manager` on ubuntu
 2. reboot
 3. nmcli device show 
```
root@test2:~# nmcli device
DEVICE  TYPE      STATE      CONNECTION 
eth0    ethernet  unmanaged  --         
lo      loopback  unmanaged  --         
root@test2:~# nmcli device show
GENERAL.DEVICE:                         eth0
GENERAL.TYPE:                           ethernet
GENERAL.HWADDR:                         00:16:3E:E0:8B:07
GENERAL.MTU:                            1500
GENERAL.STATE:                          10 (unmanaged)
GENERAL.CONNECTION:                     --
GENERAL.CON-PATH:                       --
WIRED-PROPERTIES.CARRIER:               on
IP4.GATEWAY:                            
IP6.ADDRESS[1]:                         fe80::216:3eff:fee0:8b07/64
IP6.GATEWAY:                            

GENERAL.DEVICE:                         lo
GENERAL.TYPE:                           loopback
GENERAL.HWADDR:                         00:00:00:00:00:00
GENERAL.MTU:                            65536
GENERAL.STATE:                          10 (unmanaged)
GENERAL.CONNECTION:                     --
GENERAL.CON-PATH:                       --
IP4.ADDRESS[1]:                         127.0.0.1/8
IP4.GATEWAY:                            
IP6.ADDRESS[1]:                         ::1/128
IP6.GATEWAY:     
```
```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
18: eth0@if19: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:e0:8b:07 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::216:3eff:fee0:8b07/64 scope link 
       valid_lft forever preferred_lft forever

```

# Required information

 * Distribution: Ubuntu 16.04 Xenial
 * lxc info:
```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
  driver: lxc
  driverversion: 2.0.1
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-23-generic
  server: lxd
  serverpid: 1126
  serverversion: 2.0.1
  storage: btrfs
  storageversion: "4.4"
config: {}
public: false
```
