### ISSUE TITLE
REST API will not start container

### ISSUE THREAD

**Issue by Celdir** [lxc/lxd#2049]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04
 * The output of "lxc info":
```
    apicompat: 0
    auth: trusted
    environment:
      addresses:
      - 10.30.2.8:8443
      - 10.40.252.8:8443
      architectures:
      - x86_64
      - i686
      certificate: |
      driver: lxc
      driverversion: 2.0.1
      kernel: Linux
      kernelarchitecture: x86_64
      kernelversion: 3.13.0-86-generic
      server: lxd
      serverpid: 1752
      serverversion: 2.0.1
      storage: dir
      storageversion: ""
    config:
      core.https_address: '[::]'
    public: false
```

# Issue description

I am using the REST API in a python script that creates and starts containers for me. The script is able to successfully create and delete profiles and containers using the requests package to interface with the REST API, however, starting containers always fails. I get status code 202, which means the operation has started, and no failure messages, but the containers never start. The script waits for a container's status to be "Running" before proceeding, so it gets stuck in a loop. In another terminal, I tried `lxc start <container>`, which actually started the container. However, running something like `sudo curl -k -L --cert ~/.config/lxc/client.crt --key ~/.config/lxc/client.key -H "Content-Type: application/json" -X PUT -d '{"action": "start", "timeout": 30, "force": false, "stateful": false}' ` does not start the container. Am I doing something wrong, or is this a bug in the REST API?
