### ISSUE TITLE
Improve documentation of ZFS backend shortcomings

### ISSUE THREAD

**Issue by madkinder** [lxc/lxd#2055]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04.4 LTS
 * The output of "lxc info":

     ```
    apicompat: 0
    auth: trusted
    environment:
      addresses: []
      architectures:
      - x86_64
      - i686
      certificate: |
        -----BEGIN CERTIFICATE-----
        -----SKIPPED-----
        -----END CERTIFICATE-----
      driver: lxc
      driverversion: 1.1.5
      kernel: Linux
      kernelarchitecture: x86_64
      kernelversion: 3.13.0-86-generic
      server: lxd
      serverpid: 3678
      serverversion: 2.0.0
      storage: zfs
      storageversion: "5"
    config:
      storage.zfs_pool_name: lxd
    public: false
     ```

# Issue description

A brief description of what failed or what could be improved.

# Steps to reproduce

 1. Configure lxd to use ZFS storage backend
 2. `lxc launch ubuntu tmp`
 3. `lxc snapshot tmp snap0`
 4. `lxc restore tmp snap0`

Here's the actual output from my console:

```
madkinder@madkinder-laptop:~$ lxc info jenkins-master 
Name: jenkins-master
Architecture: x86_64
Created: 2016/04/19 13:00 UTC
Status: Stopped
Type: persistent
Profiles: default
Snapshots:
  snap0 (taken at 2016/04/25 11:40 UTC) (stateless)
madkinder@madkinder-laptop:~$ lxc restore jenkins-master snap0
error: ZFS can only restore from the latest snapshot. Delete newer snapshots or copy the snapshot into a new container instead.
```

Unfortunately the steps above aren't actually the steps to reproduce, restoring to the very same snapshot used to work with this very container. But after a while it doesn't restore anymore even though this is the only snapshot this container has.

I'm attaching the logs since the time I created this container. Hope it can shed some light on the problem.

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [x] container log (lxc info NAME --show-log) (see [logs.zip][logs]/lxc-info.log)
 - [x] main daemon log (/var/log/lxd.log) (see [logs.zip][logs]/lxd.log)
 - [x] output of the client with --debug (see [logs.zip][logs]/lxc-restore.client.log)
 - [ ] output of the daemon with --debug

 [logs]: https://github.com/lxc/lxd/files/286351/logs.zip
