### ISSUE TITLE
Migration integration test fails when using rsync

### ISSUE THREAD

**Issue by sean-jc** [lxc/lxd#2072]
# Required information

Ubuntu 16.04, LXD nightly from commit f0d29e2c0729e6a51cdc24a5260d75939aa1e551 or later.
```
apicompat: 0
auth: trusted
environment:
  addresses:
  - 127.0.0.1:16801
  architectures:
  - x86_64
  - i686
  certificate: ...
  driver: lxc
  driverversion: 2.0.1
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-22-generic
  server: lxd
  serverpid: 28955
  serverversion: 2.0.2
  storage: zfs
  storageversion: "5"
config:
  core.https_address: 127.0.0.1:16801
  core.trust_password: true
  storage.zfs_pool_name: lxd
public: false
```

# Issue description

The changes to make ReaderToChannel buffered created a scenario where it will send a zero byte message on the channel, e.g. after receiving EOF error.  This causes a rsync protocol error during a migration test.  The debug output below, with an extra message to show the offset and error when sending to the channel, shows a zero length send due to an EOF. 

This is fixed by checking `offset > 0`, I'll get a PR submitted.

```
DBUG[06-02|07:41:46] Send offset: 4, err: %!s(<nil>) 
DBUG[06-02|07:41:46] Send offset: 4, err: %!s(<nil>) 
DBUG[06-02|07:41:47] Send offset: 0, err: EOF           <--- problematic send
DBUG[06-02|07:41:47] sending write barrier 
DBUG[06-02|07:41:47] rsync recv error for path /home/sean/go/src/github.com/lxc/lxd/test/tmp.QvH/DES/snapshots/nonlive/snap0/: exit status 12: rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.1]
 
DBUG[06-02|07:41:47] Got message barrier, resetting stream 
DBUG[06-02|07:41:47] Send offset: 0, err: read unix /tmp/lxd_rsync_619118954->@: use of closed network connection
```

# Steps to reproduce

LXD_DEBUG=1 LXD_INSPECT=1 sudo -E ./main.sh migration

The basic failure:
```
Creating nonlive
EROR[06-02|07:51:20] Error during migration sink              err="exit status 12"
error: Error transferring container data: exit status 12
```

With LXD_DEBUG=1:
```
DBUG[06-02|07:39:28] rsync recv error for path /home/sean/go/src/github.com/lxc/lxd/test/tmp.ULt/PpI/snapshots/nonlive/snap0/: exit status 12: rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.1]
 
DBUG[06-02|07:39:28] sending write barrier 
DBUG[06-02|07:39:28] Got message barrier, resetting stream 
DBUG[06-02|07:39:28] ContainerStop                            driver=storage/dir container=nonlive
EROR[06-02|07:39:28] Error during migration sink              err="exit status 12"
```
