### ISSUE TITLE
Daemon failed to setup shared mounts base with nesting

### ISSUE THREAD

**Issue by antitoine** [lxc/lxd#2136]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04 LTS
 * The output of "lxc info" or if that fails:
```
apicompat: 0
auth: trusted
environment:
  addresses:
  - 192.168.0.49:8443
  - 10.0.4.1:8443
  - '[fd15:e533:53cf:e274::1]:8443'
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    [...]
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.1
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-24-generic
  server: lxd
  serverpid: 1664
  serverversion: 2.0.2
  storage: dir
  storageversion: ""
config:
  core.https_address: '::'
  core.trust_password: true
public: false
```

# Issue description

I can't run LXD container inside another with nesting set to true.
I have this error after `lxc launch ubuntu-daily:16.04 test -c security.nesting=true` : 
```
Creating test
Starting test
error: Daemon failed to setup shared mounts base: permission denied.
Does security.nesting need to be turned on?
Try `lxc info --show-log test` for more info
```

The output of `lxc info --show-log test` : 
```
Name: test
Architecture: x86_64
Created: 2016/06/18 10:00 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:
```

The output of `lxc launch ubuntu-daily:16.04 test -c security.nesting=true --debug` : [lxc-launch-nesting-debug.txt](https://github.com/lxc/lxd/files/321685/lxc-launch-nesting-debug.txt)

The output of `lxc info` in the container who try to launch test : [lxc-info-container.txt](https://github.com/lxc/lxd/files/321686/lxc-info-container.txt)

# Steps to reproduce

I follow the great post here: https://www.stgraber.org/2016/04/14/lxd-2-0-lxd-in-lxd-812/

All command (start from host, no container) : 

 1. `lxc launch ubuntu-daily:16.04 test-host`
 2. `lxc exec test-host -- /bin/bash`
 3. `su ubuntu`
 4. `sudo lxd init` with `Would you like to have your containers share their parent's allocation (yes/no)? yes`, full version here : [lxd-init.txt](https://github.com/lxc/lxd/files/321687/lxd-init.txt)
 5. `lxc launch ubuntu-daily:16.04 test`
