### ISSUE TITLE
unused config keys are silently ignored

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#2179]
If I try to save something like:

```
name: unpriv
profiles:
- default
config:
  volatile.base_image: f452cda3bccb2903e56d53e402b9d35334b4276783d098a879be5d74b04e62e2
  volatile.eth0.hwaddr: 00:16:3e:1e:8a:97
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  root:
    path: /
    type: disk
ephemeral: false
not-a-valid-config-key: foo
```

it just eats `not-a-valid-config-key`. It would be nice to give an error here.
