### ISSUE TITLE
No lxdbr0 after install and error: Error calling 'lxd forkstart my-ubuntu /var/lib/lxd/containers /var/log/lxd/my-ubuntu/lxc.conf': err='exit status 1'

### ISSUE THREAD

**Issue by hverlin** [lxc/lxd#2193]
Hi! I have an issue with a fresh install of lxd on a ubuntu 16.04 server.

# Required information

 * Distribution: ubuntu
 * Distribution version:16.04
 * The output of "lxc info":
```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFYjCCA0qgAwIBAgIRAO......
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.1
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-28-generic
  server: lxd
  serverpid: 2205
  serverversion: 2.0.2
  storage: dir
  storageversion: ""
config: {}
public: false
```
   * Storage backend in use: dir

# Issue description

I am unable to use lxd. The following error is printed each time I try to launch a machine.

```
$ lxc launch ubuntu-daily:16.04 my-ubuntu
Creating my-ubuntu
Starting my-ubuntu
error: Error calling 'lxd forkstart my-ubuntu /var/lib/lxd/containers /var/log/lxd/my-ubuntu/lxc.conf': err='exit status 1'
Try `lxc info --show-log my-ubuntu` for more info
```

Moreover, I have noticed than the lxdbr0 bridge is not present in the ouput of ``ifconfig``

```
$ ifconfig
enp0s20f0 Link encap:Ethernet  HWaddr 00:07:cb:03:c2:a7  
          inet addr:163.172.37.195  Bcast:163.172.37.255  Mask:255.255.255.0
          inet6 addr: fe80::207:cbff:fe03:c2a7/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:107948 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7270 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:155096412 (155.0 MB)  TX bytes:634766 (634.7 KB)
          Memory:80000000-8001ffff 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:7 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:349 (349.0 B)  TX bytes:349 (349.0 B)

```

I use lxd with dir, no network and I have leave all default values for the bridge configuration.

# Information to attach

 - any relevant kernel output (dmesg)
[dmesg.txt](https://github.com/lxc/lxd/files/355153/dmesg.txt)

 - container log (lxc info NAME --show-log)
[lxdinfo.txt](https://github.com/lxc/lxd/files/355155/lxdinfo.txt)
 - main daemon log (/var/log/lxd.log)
[lxclog.txt](https://github.com/lxc/lxd/files/355163/lxclog.txt)
