### ISSUE TITLE
Perpetual Issue: error: Error calling 'lxd forkstart cont1 /var/lib/lxd/containers /var/log/lxd/cont1/lxc.conf': err='exit status 1'

### ISSUE THREAD

**Issue by Kentoseth** [lxc/lxd#2195]
So I have been trying to debug this issue repeatedly, using all the multiple solutions/issues/mailing-list-issues/etc. to find a working solution to what seems to be a recurring LXD issue across OS versions (and multiple OSes).

This is very worrying that something like LXD made it past 1.0 with this recurring problem still present.

The actual error message is in the title, but here it is once again:

`error: Error calling 'lxd forkstart cont1 /var/lib/lxd/containers /var/log/lxd/cont1/lxc.conf': err='exit status 1'`

# Required information

Host: Ubuntu 14.04

```
 lxc info
apicompat: 0
auth: trusted
environment:
  addresses:
  - [masked]:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
...
    -----END CERTIFICATE-----
  certificatefingerprint: ...
  driver: lxc
  driverversion: 2.0.3
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.16.0-76-generic
  server: lxd
  serverpid: 4075
  serverversion: 2.0.3
  storage: dir
  storageversion: ""
config:
  core.https_address: [masked]:8443
public: false
```

Here is a partial of the ifconfig:

```
lxdbr0    Link encap:Ethernet  HWaddr 00:00:00:00:00:00  
          inet addr:10.20.117.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::c084:54ff:fe93:aad9/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:1 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:76 (76.0 B)  TX bytes:570 (570.0 B)
```

# Issue description

See initial text above about the issue.

# Steps to reproduce

 1. Fresh Ubuntu 14.04 install
 2. Perform `apt-get update` and `apt-get dist-upgrade`
 3. Follow regular LXD install instructions (including the `sudo lxd init` part)
 4. Everything works up to the point of this command: `lxc launch ubuntu cont1` (where ubuntu is the local alias for the image)

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log) 

`https://gist.github.com/Kentoseth/7d2358007b5ee905733584bf6841d878`
 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug
