### ISSUE TITLE
Copying containers results in old hostname reported by hostname -A in new container

### ISSUE THREAD

**Issue by austinjp** [lxc/lxd#2198]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 14.04 LTS
 * The output of "lxc info" or if that fails:

```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: ...
  certificatefingerprint: ...
  driver: lxc
  driverversion: 2.0.3
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.13.0-91-generic
  server: lxd
  serverpid: 8005
  serverversion: 2.0.3
  storage: zfs
  storageversion: "5"
config:
  storage.zfs_pool_name: lxd
public: false
```

# Issue description

Copying a container seems to leave the old container's hostname lingering in various places, including being reported by `hostname -A`.

# Steps to reproduce

```
# lxc list
+--------------------+---------+-------------------+------+------------+-----------+
|        NAME        |  STATE  |       IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
+--------------------+---------+-------------------+------+------------+-----------+
| CONTAINER-SKELETON | STOPPED |                   |      | PERSISTENT | 0         |
+--------------------+---------+-------------------+------+------------+-----------+
# lxc copy CONTAINER-SKELETON test2
# lxc start test2
# lxc exec test2 bash
root@test2:~# hostname
test2
root@test2:~# hostname -A
CONTAINER.lxd
root@test2:~# cd /
root@test2:~# grep -rl CONTAINER-SKELETON * 2>/dev/null
etc/aliases.db
etc/postfix/main.cf.bak
etc/postfix/main.cf
etc/emacs23/site-start.d/00debian-vars.elc
proc/2690/task/2690/cmdline
proc/2690/cmdline
usr/share/emacs23/site-lisp/debian-startup.elc
var/log/upstart/pollinate.log
var/log/dmesg
var/log/mail.log
var/log/mysql/error.log
var/log/auth.log
var/log/cloud-init.log
var/log/syslog
var/log/cloud-init-output.log
var/log/kern.log
var/log/apt/term.log
var/log/dmesg.0
var/cache/debconf/config.dat
var/cache/debconf/config.dat-old
var/lib/mlocate/mlocate.db
var/lib/cloud/data/previous-instance-id
var/lib/cloud/instances/CONTAINER-SKELETON/obj.pkl
var/lib/dhcp/dhclient.leases
var/lib/dhcp/dhclient.eth0.leases
var/lib/mysql/ibdata1
var/lib/mysql/wordpress/wp_options.ibd
var/lib/mysql/wordpress/wp_posts.ibd
var/lib/mysql/ib_logfile0
```

The CONTAINER-SKELETON machine has various things installed including postfix, MySQL, and Wordpress.

This is causing me problems, because the Wordpress running in the test2 container is getting very confused. I've fixed mentions of CONTAINER-SKELETON in the Wordpress MySQL database, but various other PHP calls are fetching the hostname in various ways, some of which return "CONTAINER-SKELETON" instead of "test2".

I can probably fix most of this, but the output of `hostname -A` concerns me.

I'm unsure if this is a bug exactly, or can be fixed by passing some config options on creation of the new container?

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [x] container log (lxc info NAME --show-log)

See https://gist.github.com/austinjp/731442a445e22de27760206b27d5d17a#file-lxc-info-test2-show-log-log

 - [x] main daemon log (/var/log/lxd.log)

See https://gist.github.com/austinjp/731442a445e22de27760206b27d5d17a#file-var-log-lxd-lxd-log

 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug
