### ISSUE TITLE
Setting vm.max_map_count inside LXD container fails

### ISSUE THREAD

**Issue by naisanza** [lxc/lxd#2206]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-28-generic
   * LXC version: 2.0.3
   * LXD version: 2.0.3
   * Storage backend in use: ZFS

# Issue description

Setting the vm.max_map_count value inside the container fails. This report is solely on the failure of setting the `vm.max_map_count` value.

The origin for trying to set the `vm.max_map_count` value is, because Elasticsearch 5.0.0alpha4 recommends setting `vm.max_map_count` to at least 262144, however this is not an issue with Elasticsearch 2.3.4

5.0.0alpha4 startup log:
```
max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]
```
 I've opened a bug report with Elasticsearch as well https://github.com/elastic/elasticsearch/issues/19458

# Steps to reproduce

 1. Launch LXD container
 2. Install [Java ](http://javadl.oracle.com/webapps/download/AutoDL?BundleId=207765)+ [Elasticsearch 5.0.0alpha4](https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/5.0.0-alpha4/elasticsearch-5.0.0-alpha4.tar.gz) 
 3. Run Elasticsearch

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [x] container log (lxc info NAME --show-log)
[base-elasticsearch-5-0-0-alpha4.log.txt](https://github.com/lxc/lxd/files/366840/base-elasticsearch-5-0-0-alpha4.log.txt)
 - [x] main daemon log (/var/log/lxd.log)
[lxd.log.txt](https://github.com/lxc/lxd/files/366839/lxd.log.txt)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

Following the [instructions from the Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html) docs to set the vm.max_map_count value, writing the new value fails in the container.
```
root@base-elasticsearch-5-0-0-alpha4:~# sysctl -w vm.max_map_count=262144
sysctl: permission denied on key 'vm.max_map_count'

root@base-elasticsearch-5-0-0-alpha4:~# sysctl -a | grep vm.max_map_count
sysctl: permission denied on key 'fs.protected_hardlinks'
sysctl: permission denied on key 'fs.protected_symlinks'
sysctl: permission denied on key 'kernel.cad_pid'
sysctl: permission denied on key 'kernel.unprivileged_userns_apparmor_policy'
sysctl: permission denied on key 'kernel.usermodehelper.bset'
sysctl: permission denied on key 'kernel.usermodehelper.inheritable'
sysctl: reading key "net.ipv6.conf.all.stable_secret"
sysctl: reading key "net.ipv6.conf.default.stable_secret"
sysctl: reading key "net.ipv6.conf.eth0.stable_secret"
sysctl: reading key "net.ipv6.conf.lo.stable_secret"
vm.max_map_count = 65530
```

**Comment by stgraber** [comment]
Can you do "lxc config set base-elasticsearch raw.lxc lxc.aa_profile=unconfined", then restart the container with "lxc restart base-elasticsearch" and see if it's still a problem?

If it is, it's because that particular key isn't namespaced and/or allowed for unprivileged user use by the kernel.

**Comment by naisanza** [comment]
@stgraber it still is

```
eric@bigma:~$ lxc config show base-elasticsearch-5-0-0-alpha4
name: base-elasticsearch-5-0-0-alpha4
profiles:
- default
config:
  boot.autostart: "true"
  raw.lxc: lxc.aa_profile=unconfined
  volatile.base_image: f452cda3bccb2903e56d53e402b9d35334b4276783d098a879be5d74b04e62e2
  volatile.eth0.hwaddr: 00:16:3e:b1:d9:31
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  root:
    path: /
    type: disk
ephemeral: false

eric@bigma:~$ lxc exec base-elasticsearch-5-0-0-alpha4  bash

root@base-elasticsearch-5-0-0-alpha4:~# sysctl -w vm.max_map_count=262144
sysctl: permission denied on key 'vm.max_map_count'
```
