### ISSUE TITLE
systemd can't start elasticsearch

### ISSUE THREAD

**Issue by yml** [lxc/lxd#2218]
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04 
 * The output of "lxc info" or if that fails:

```
Name: xenial-elastic2
Architecture: x86_64
Created: 2016/07/20 12:42 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 17095
Ips:
  eth0:	inet	10.245.115.251	vethMW7D3A
  eth0:	inet6	fd4f:e995:459f:f46b:216:3eff:fee1:8d2e	vethMW7D3A
  eth0:	inet6	fe80::216:3eff:fee1:8d2e	vethMW7D3A
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 75
  Memory usage:
    Memory (current): 282.11MB
    Memory (peak): 316.48MB
  Network usage:
    eth0:
      Bytes received: 43.60kB
      Bytes sent: 152.11kB
      Packets received: 494
      Packets sent: 378
    lo:
      Bytes received: 4.34kB
      Bytes sent: 4.34kB
      Packets received: 51
      Packets sent: 51

```

# Issue description

Systemd can't start Elasticsearch

# Steps to reproduce

 1. Create a container
 2. sudo apt install elasticsearch
 3. reboot

I can manually start elasticsearch with no issue: 

```
sudo /usr/share/elasticsearch/bin/elasticsearch
```

**Comment by tych0** [comment]
Are there any systemd logs?

**Comment by yml** [comment]
Not really when I restart the service like this : 

```
sudo systemctl restart elasticsearch.service
```

I get this output:

```
juil. 20 16:36:29 xenial-elastic2 systemd[1]: Stopping LSB: Starts elasticsearch...
juil. 20 16:36:29 xenial-elastic2 systemd[1]: Stopped LSB: Starts elasticsearch.
juil. 20 16:36:29 xenial-elastic2 systemd[1]: Starting LSB: Starts elasticsearch...
juil. 20 16:36:29 xenial-elastic2 systemd[1]: Started LSB: Starts elasticsearch.
```

But elastic search is not listening on port 92000  :-/

**Comment by pcdummy** [comment]
I had the same Problem with varnish,

have a look at **/lib/systemd/system/elasticsearch.service** its pretty sure there are limits or some other stuff set, which aren't allowed for unprivileged users.

You have two choices then, either overwrite this in /etc/systemd/system/ or run the container privileged.

**Comment by yml** [comment]
Not sure if it is a good sign or a bad one but this file does not exist:

```
yml@xenial-elastic2$ cat /lib/systemd/system/elasticsearch.service
cat: /lib/systemd/system/elasticsearch.service: No such file or directory
```

**Comment by yml** [comment]
I also try to set the `security.privileged` to `true` then restarted the container and rebooted the OS and I have the same issue.

```
yml@carbon$ lxc config show xenial-elastic2
name: xenial-elastic2
profiles:
- default
config:
  security.privileged: "true"
  volatile.base_image: 961b6594233e619daa6e44296315d19d93db862773e30d9a278dd5b5574a7e2b
  volatile.eth0.hwaddr: 00:16:3e:e1:8d:2e
  volatile.last_state.idmap: '[]'
devices:
  root:
    path: /
    type: disk
ephemeral: false
```
