### ISSUE TITLE
Sort disk entries by target path (mount parent first)

### ISSUE THREAD

**Issue by naisanza** [lxc/lxd#2249]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-31-generic
   * LXC version: 2.0.3
   * LXD version: 2.0.3
   * Storage backend in use: ZFS

# Issue description

The container will not start with added `disk` `devices`. 

Sample error:
`lxc 20160729063411.372 ERROR    lxc_utils - utils.c:mkdir_p:253 - Permission denied - failed to create directory '/usr/lib/x86_64-linux-gnu/lxc/turtle/_data/downloads'`

I'm adding ZFS datasets as the `source` for `lxc device add`. However, the container will not start.

But, if I start the container without any added devices, and add the devices **_after_** the container is running, everything works.

# Steps to reproduce that works

 1. `$ lxc launch f452cda3bccb outer-smb -p outer_rim` (container will be running)
 2. `$ lxc config device add outer-smb data disk source=/turtle/_data path=/turtle/_data` etc. etc.

# Steps to reproduce that doesn't work (method one)

 1.  `$ lxc launch f452cda3bccb outer-smb -p outer_rim` (container will be running)
 2.  `$ lxc stop outer-smb`
 3.  `$ lxc config device add outer-smb data disk source=/turtle/_data path=/turtle/_data` etc. etc.
 4.  `$ lxc start outer-smb`
 5.  container fails to start (see attached outer-smb.log)

# Steps to reproduce that doesn't work (method two)

 1. `$ lxc launch f452cda3bccb outer-smb -p outer_rim` (container will be running)
 2. `$ lxc config device add outer-smb data disk source=/turtle/_data path=/turtle/_data` etc. etc.
 3. `$ lxc restart outer-smb`
 4. container fails to start (see attached outer-smb.log)

ZFS datasets have the following extended attribute settings: `xattr=sa`, `acltype=posixacl`
I've also used `setfacl` to set all the datasets with identical permissions

# Information to attach

 - [x] any relevant kernel output (dmesg) none relevant
 - [x] container log (lxc info NAME --show-log) [lxc-info.log.txt](https://github.com/lxc/lxd/files/390371/lxc-info.log.txt)
 - [x] main daemon log (/var/log/lxd.log) [lxd.log.txt](https://github.com/lxc/lxd/files/390370/lxd.log.txt)
 - [x] output of the client with --debug [outer-smb.log.txt](https://github.com/lxc/lxd/files/390367/outer-smb.log.txt)
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment]
Can you include "lxc config show outer-smb --expanded" from after you added the device?

**Comment by naisanza** [comment]
@stgraber posting mobily, apologies for not just an uploaded file. Here's the output 


```
name: outer-smb
profiles:
- outer_rim
config:
  volatile.base_image: f452cda3bccb2903e56d53e402b9d35334b4276783d098a879be5d74b04e62e2
  volatile.eth0.hwaddr: 00:16:3e:66:54:93
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  data:
    path: /turtle/_data
    source: /turtle/_data
    type: disk
  downloads:
    path: /turtle/_data/downloads
    source: /turtle/_data/downloads
    type: disk
  downloads-books:
    path: /turtle/_data/downloads/books
    source: /turtle/_data/downloads/books
    type: disk
  downloads-space:
    path: /turtle/_data/downloads/space
    source: /turtle/_data/downloads/space
    type: disk
  downloads-unsorted:
    path: /turtle/_data/downloads/unsorted
    source: /turtle/_data/downloads/unsorted
    type: disk
  eth0:
    name: eth0
    nictype: bridged
    parent: outer_rim
    type: nic
  home:
    path: /turtle/_data/home
    source: /turtle/_data/home
    type: disk
  home-eric:
    path: /turtle/_data/home/eric
    source: /turtle/_data/home/eric
    type: disk
  recovery:
    path: /turtle/_data/recovery
    source: /turtle/_data/recovery
    type: disk
  root:
    path: /
    type: disk
  util:
    path: /turtle/_data/util
    source: /turtle/_data/util
    type: disk
ephemeral: false
```
