### ISSUE TITLE
How to update existing container from image with new version of container?

### ISSUE THREAD

**Issue by vistoyn** [lxc/lxd#2303]
I download image and create container. 
Then i create new image with new version of the container, and i want to update all my containers to the new version.
I update the image to the new version of the container from tarball:

```
lxc image import /backup/new.version.tar.bz2  --alias my-image
```

How to update existing container from new image?

The command

```
lxc launch my-container my-image
```

give `error: The container already exists`

**Comment by vistoyn** [comment]
I can do this by the script https://github.com/vistoyn/lxd_backup with command:
```
lxc-stop {container_name}
lxc-restore {container_name} /backup/new.version.tar.bz2
```

But I think this is strange way.

I can't use LXD private server and snapshots system because I haven't second server. I use Amazon S3 as backup storage of the my containers, and sometimes download container's backups by FTP.

**Comment by stgraber** [comment]
Right so there isn't a way to just replace the rootfs of a container from an image. You're expected to create a new container from it, so deleting the old one.

If you care about the container configuration, which is the only thing that would be lost if you were to just delete the container before launching it again, then something like this would do the trick:

    lxc config show my-container > old-config
    lxc delete my-container
    lxc init my-image my-container
    lxc config edit my-container < old-config
    lxc start my-container

Alternatively, you could just have any relevant container config in a profile and just use the -p argument of launch to apply that to the new container, saving the show/edit steps.

We don't see this as a far common use case since folks usually care about the data in the container and so don't really feel the need to wipe it all clean to replace with a new image, without also wanting to modify the config.

**Comment by vistoyn** [comment]
I think that all the users data should be mounted in a container so that they do not accidentally remove the removal of the container.
For example:
```
$ lxc config device add disk_name test disk path=/folder source=/data/test/folder
```
And update command should replace old container on new container by `rsync`.

**Comment by vistoyn** [comment]
```
lxc config show my-container > old-config
lxc delete my-container
lxc init my-image my-container
lxc config edit my-container < old-config
lxc start my-container
```
It's too long. Maybe should make a single command?

**Comment by stgraber** [comment]
I don't believe this is a common enough case that it warrants its own command.
If it is something you have to very commonly do, writing a short shell script for your environment should be easy enough.

If other people need this, please comment in this issue and we may re-consider.

**Comment by jkroepke** [comment]
@stgraber The command described in https://github.com/lxc/lxd/issues/2303#issuecomment-241753846 does not works anymore. 

Old Container has this entries in dnsmasq:
I'm using the latest 2.12 ppa packages.

Here is the test
```
# lxc init images:ubuntu/xenial test
# lxc start test
# grep test /var/lib/lxd/networks/br1/dnsmasq.leases
0 00:16:3e:7c:9b:4b 10.0.10.179 test *
1490578933 1052821298 2a01: test 00:01:00:01:20:6b:0d:29:00:16:3e:c0:c7:32
# lxc config show test
architecture: x86_64
config:
  boot.autostart: "false"
  image.architecture: amd64
  image.description: Ubuntu xenial amd64 (20170326_03:49)
  image.os: Ubuntu
  image.release: xenial
  image.serial: "20170326_03:49"
  limits.cpu: "2"
  limits.memory: 512MB
  volatile.base_image: 9d9604bcf7cb52ced1d2133398014c22c5acc7c22986d426bc6cfb055c865090
  volatile.eth0.hwaddr: 00:16:3e:7c:9b:4b
  volatile.eth0.name: eth0
  volatile.idmap.base: "2328224"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":2328224,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":23$
8224,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":2328224,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Host$
d":2328224,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices: {}
ephemeral: false
profiles:
- default
# lxc config show test > /tmp/test
# lxc delete --force test

# lxc init images:ubuntu/xenial test
# lxc config edit test < /tmp/test

# egrep 'test|179 ' /var/lib/lxd/networks/br1/dnsmasq.leases
0 00:16:3e:7c:9b:4b 10.0.10.179 test *
1490578933 1052821298 2a01: test 00:01:00:01:20:6b:0d:29:00:16:3e:c0:c7:32

# lxc start test

# egrep 'test|179 ' /var/lib/lxd/networks/br1/dnsmasq.leases
0 00:16:3e:7c:9b:4b 10.0.10.179 LXC_NAME *
1490578933 1052821298 2a01: test 00:01:00:01:20:6b:0d:29:00:16:3e:c0:c7:32
# lxc exec test hostname
LXC_NAME
```

Looks like a missing variables expression, not?

My Network config:



```

# lxc network show br1
config:
  ipv4.address: 10.0.10.2/24
  ipv4.dhcp: "true"
  ipv4.dhcp.expiry: infinite
  ipv4.dhcp.ranges: 10.0.10.10-10.0.10.200
  ipv4.firewall: "false"
  ipv4.nat: "false"
  ipv4.routing: "true"
  ipv6.address: 2a01:../64
  ipv6.dhcp: "true"
  ipv6.dhcp.expiry: infinite
  ipv6.dhcp.stateful: "true"
  ipv6.firewall: "false"
  ipv6.nat: "false"
  ipv6.routing: "true"

```
