### ISSUE TITLE
USB device entry leads to major/minor stored in device, causes start failure

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#2312]
@tych0 

So after playing with USB devices, I ended up having the following thing happen to me at startup time:

```
stgraber@castiana:~$ lxc start android
error: Invalid device configuration key for usb: major
Try `lxc info --show-log android` for more info
```

The container config is clearly wrong as it's storing what should be internal details:
```
stgraber@castiana:~$ lxc config show android
name: android
profiles:
- default
config:
  limits.cpu: "3"
  volatile.base_image: 34f838f28fd16387391e40de3a3efb16186b873384945eb908683d85cc042fec
  volatile.eth0.hwaddr: 00:16:3e:47:47:ab
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  root:
    path: /
    type: disk
  z5c:
    major: "189"
    minor: "4"
    path: /dev/bus/usb/001/005
    productid: 51da
    type: usb
    vendorid: 0fce
ephemeral: false
```
