### ISSUE TITLE
How to set global hostid?

### ISSUE THREAD

**Issue by vistoyn** [lxc/lxd#2316]
I'm install LXD on two servers. I'm use rsync to sync data beetwen servers. But one server have hostid 100000, second server have hostid 165536. Root is different. Rsync doesn't work!
I need hostid id on both servers = 100000. 
How i can do it?

I do:
1) lxc config show test > ./config
2) change text 165536 to 100000 in file ./config
3) lxc config edit test < ./config
4) lxc start test
5) lxc config show test 
Show me again hostid 165536 
```
name: test
profiles:
- default
config:
  volatile.base_image: 6db4f6ec6c3a34e91a133cbdd6bc1d69f0c6cc5e8259ff599e105431c453e5f5
  volatile.eth0.hwaddr: 00:16:3e:b6:b8:b0
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
devices:
  root:
    path: /
    type: disk
ephemeral: false
```

How to set hostid of the container?
How to set global hostid?
