### ISSUE TITLE
Docker -  could not open moddep file

### ISSUE THREAD

**Issue by givre** [lxc/lxd#2321]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

 * The output of "lxc info" or if that fails:
   * Kernel version:
4.4.0-28-generic
   * LXC version:
lxc --version
2.0.3

   * LXD version:
lxd --version
2.0.2

   * Storage backend in use:
ZFS

* Docker Version : 1.11 and 1.12  from ubuntu 

**# Issue description**

Cannot load specific kernel modules for Docker ( br_netfilter , nf_nat)lxc

**# Steps to reproduce**

 **1. Step one**
Install docker : apt-get install docker.io

 **2. Step two**
Start docker daemon 

# Information to attach

....WARN[0001] Running modprobe bridge br_netfilter failed with message: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-28-generic/modules.dep.bin'
modprobe: WARNING: Module bridge not found in directory /lib/modules/4.4.0-28-generic
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-28-generic/modules.dep.bin'
modprobe: WARNING: Module br_netfilter not found in directory /lib/modules/4.4.0-28-generic
, error: exit status 1

**Comment by stgraber** [comment]
Hmm, the docker profile loads nf_nat for you, are you using it?

**Comment by givre** [comment]
Yes I do, but I looks like It's now loaded inside de container


**lxc profile show docker** 
```
name: docker
config:
  linux.kernel_modules: overlay, nf_nat, br_netfilter
  raw.lxc: lxc.aa_allow_incomplete = 1
  security.nesting: "true"
description: Profile supporting docker in containers
devices:
  aadisable:
    path: /sys/module/apparmor/parameters/enabled
    source: /dev/null
    type: disk
  fuse:
    path: /dev/fuse
    type: unix-char
```

**lxc config show dock-m1**
```
name: dock-m1
profiles:
- default
- docker
config:
  security.privileged: "true"
  volatile.base_image: 3fb03bf23058dacff32a8054fd71c7218648073017ad3c1a457fa46e008592e9
  volatile.eth0.name: eth0
  volatile.eth1.name: eth1
  volatile.last_state.idmap: '[]'
```
