### ISSUE TITLE
Copying between ZFS and Btrfs hosts fails if there are snapshots

### ISSUE THREAD

**Issue by MarkGavalda** [lxc/lxd#2359]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.1
 * ZFS machine lxc info:
```
apiextensions: []
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
  - 10.240.0.14:8443
  architectures:
  - x86_64
  - i686
  driver: lxc
  driverversion: 2.0.4
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-34-generic
  server: lxd
  serverpid: 2628753
  serverversion: 2.0.4
  storage: zfs
  storageversion: "5"
config:
  core.https_address: 10.240.0.14:8443
  core.trust_password: true
  storage.zfs_pool_name: lxd
public: false
```
 * Btrfs machine lxc info:
```
apiextensions: []
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
  - 10.240.0.16:8443
  architectures:
  - x86_64
  - i686
  driver: lxc
  driverversion: 2.0.4
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-36-generic
  server: lxd
  serverpid: 3392
  serverversion: 2.0.4
  storage: btrfs
  storageversion: "4.4"
config:
  core.https_address: 10.240.0.16:8443
  core.trust_password: true
public: false
```

# Issue description

When there are snapshots in the ZFS based container lxc copy and move both fail with:
error: Error transferring container data: exit status 23

# Steps to reproduce
```
root@lxd-9:~# lxc copy lxd-4:ccX-atest8888 ccX-atest8888
error: Error transferring container data: exit status 23

root@lxd-4:~# lxc copy ccX-atest8888/atest8888-1473435272-autobackup atest8888-1473435272-autobackup

root@lxd-9:~# lxc copy lxd-4:atest8888-1473435272-autobackup ccX-atest8888
```
And the last one succeeds.
