### ISSUE TITLE
Suspected live-lock issue in lxd.db under contention

### ISSUE THREAD

**Issue by leehambley** [lxc/lxd#2398]
# Required information

 * Distribution: 

```
root@virthost ~ # uname -a
Linux virthost 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@virthost ~ # cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```

 * The output of "lxc info":

```
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    ....snip....
    -----END CERTIFICATE-----
  certificatefingerprint: ....snip....
  driver: lxc
  driverversion: 2.0.3
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-34-generic
  server: lxd
  serverpid: 3207
  serverversion: 2.0.3
  storage: btrfs
  storageversion: "4.4"
config: {}
public: false
```

# Issue description

We run an environment where the `lxc` command line tool is used to run short-lived workloads in containers. The `lxc` commands are dispatched into the background with a `fork/exec/detach` process (very typical) from our worker processes.

The behaviour we observe is a progressive slowing-down of the system in spite of negligible host load. With three parallel processes we have a throughput of ~3.8 containers per minute, with more that drops significantly.

Initial research suggests that this is related to a live-lock contention of `lxd.db` as processes have a fixed 100x100ms retry behaviour which causes all the processes to line up and bang on the lock simultaneously.

First indications are that introducing a little entropy into the loop sleep times increases throughput dramatically, such as adding `rand(100,i)`ms sleep to each loop interation

# Steps to reproduce

 1. Run a tight loop, say 100 entries `for i in \`seq 1 100\`; do lxc exec ubuntu-32 sleep 500 &; done`
 2. Observe that with more concurrency the loop gets slower and slower, spending more and more time with `lxc` processes hanging. Output of `lsof /var/lib/lxd/lxd.db` shows `~3+n` (where `n` is roughly the number of times we've dispatched an `lxc exec` command)
 3. Lament the naïve locking in https://github.com/lxc/lxd/blob/master/lxd/db.go around each DB operation.

I'm not quite sure how best to time the issue, I thought about the following:

* Emit UDP packets (statsd format?) on each transition change, e.g in https://github.com/lxc/lxd/blob/master/lxd/db.go#L287 (and all similar places)
* Plot that somehow, rrdtool springs to mind, but doesn't have precision better than `1s`, so is unsuitable.
* Probably observe all processes *lining up* to fail to acquire the lock, whilst sitting potentially for as long as 10s per call, failing to get a database lock.

Before attempting a PR I'd like to know what, if any discussion has been had around the internal database, it's design choices, the implementation (~3+n × the same file open) and the naïve choice of sleep/wait with the locking of the database. Before potentially pushing an unwelcome change to the internals.
