### ISSUE TITLE
Cannot run a simple docker container inside of LXC

### ISSUE THREAD

**Issue by linsun** [lxc/lxd#2426]
I have gotten this working before... it could be on a different level of kernel but it no longer works today.

```
root@linsun-server2:~# uname -r
4.4.0-38-generic
root@linsun-server2:~# lxd --version
2.0.2
root@linsun-server2:~# lxc info docker1
Name: docker1
Architecture: x86_64
Created: 2016/09/26 20:29 UTC
Status: Running
Type: persistent
Profiles: default, docker
Pid: 2132
Ips:
  eth0:	inet	10.168.95.43	vethKO0U70
  eth0:	inet6	fe80::216:3eff:fec3:90c7	vethKO0U70
  lo:	inet	127.0.0.1
  lo:	inet6	::1
  docker0:	inet	172.17.0.1
  docker0:	inet6	fe80::42:6eff:fe35:57c9
  docker_gwbridge:	inet	172.18.0.1
Resources:
  Processes: 57
  Memory usage:
    Memory (current): 716.02MB
    Memory (peak): 776.28MB
  Network usage:
    lo:
      Bytes received: 57.54kB
      Bytes sent: 57.54kB
      Packets received: 544
      Packets sent: 544
    docker0:
      Bytes received: 76 bytes
      Bytes sent: 258 bytes
      Packets received: 1
      Packets sent: 3
    docker_gwbridge:
      Bytes received: 0 bytes
      Bytes sent: 0 bytes
      Packets received: 0
      Packets sent: 0
    eth0:
      Bytes received: 114.83MB
      Bytes sent: 2.71MB
      Packets received: 80222
      Packets sent: 42132

root@linsun-server2:~# lxc config show docker1
name: docker1
profiles:
- default
- docker
config:
  security.privileged: "true"
  volatile.base_image: 5d03c5b456b31def5bc1e3781a12f976064a39dde06fd43c981904496720b54d
  volatile.eth0.hwaddr: 00:16:3e:c3:90:c7
  volatile.last_state.idmap: '[]'
devices:
  root:
    path: /
    type: disk
ephemeral: false
root@linsun-server2:~# lxc config show docker2
name: docker2
profiles:
- default
- docker
config:
  security.privileged: "true"
  volatile.base_image: 5d03c5b456b31def5bc1e3781a12f976064a39dde06fd43c981904496720b54d
  volatile.eth0.hwaddr: 00:16:3e:20:a1:f4
  volatile.last_state.idmap: '[]'
devices:
  root:
    path: /
    type: disk
ephemeral: false

root@docker1:~# **docker run hello-world**
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
c04b14da8d14: Pull complete 
Digest: sha256:0256e8a36e2070f7bf2d0b0763dbabdd67798512411de4cdcf9431a1feb60fd9
Status: Downloaded newer image for hello-world:latest
**docker: Error response from daemon: oci runtime error: process_linux.go:291: setting cgroup config for ready process caused "failed to write c 10:200 rwm to devices.allow: write /sys/fs/cgroup/devices/docker/5cb8a853bcfd9a6f9835ac20e0f77f124ab9539baf429d280ffe384276934032/devices.allow: operation not permitted".**
```

**Comment by linsun** [comment]
Note: I've tried both dir or zfs storage, same prob.

**Comment by stgraber** [comment]
I see that those containers are privileged, could that be why they're not working anymore?

**Comment by stgraber** [comment]
Hmm, actually, no, the error is for 10:200 which is /dev/net/tun.

I suspect the problem is simply that you're running an old LXD release which doesn't include /dev/net/tun by default, you need LXD 2.0.4 and above you're running 2.0.2.

Update your system to get 2.0.4 through updates and then restart the affected containers.

**Comment by linsun** [comment]
Thank you @stgraber, I will try update to 2.0.4 and let you know!

**Comment by niko-daniel** [comment]
Latest docker version (1.12.1) only can run when we set "security.privileged true" to container, 
I think new docker needs more kernel caps to running. But overlay networking between container and host  not work on me when try to running swarm service across lxd containers.

**Host informations** 
```
user@env:~$ lxc info 
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  certificatefingerprint: c8718dccad55424c5975ba5bcea6c27edc63205d8dd77633c1b9a8259333ea2b
  driver: lxc
  driverversion: 2.0.4
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-38-generic
  server: lxd
  serverpid: 1439
  serverversion: "2.2"
  storage: dir
  storageversion: ""
config: {}
public: false
```

**Container profile**
```
user@env:~$ lxc config show swarm 
name: swarm
profiles:
- default
- docker
config:
  limits.memory: 512MB
  security.privileged: "true"
  volatile.base_image: 981926b5b513af70539a0fa521387306987266bc3b6e0019f1be55996caec6fb
  volatile.eth0.hwaddr: 00:16:3e:e1:d8:32
  volatile.last_state.idmap: '[]'
devices:
  root:
    path: /
    type: disk
ephemeral: false
```

**Docker version**
docker inside LXD container
```
user@env:~$ lxc exec swarm -- docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```
**List LXD container**
```
user@env:~$ lxc list
+-----------+---------+--------------------------------+------+------------+-----------+
|   NAME    |  STATE  |              IPV4              | IPV6 |    TYPE    | SNAPSHOTS |
+-----------+---------+--------------------------------+------+------------+-----------+
| swarm     | RUNNING | 172.17.0.1 (docker0)           |      | PERSISTENT | 0         |
|           |         | 172.18.0.1 (docker_gwbridge)   |      |            |           |
|           |         | 10.109.250.164 (eth0)          |      |            |           |
+-----------+---------+--------------------------------+------+------------+-----------+
| worker-01 | RUNNING | 172.17.0.1 (docker0)           |      | PERSISTENT | 0         |
|           |         | 172.18.0.1 (docker_gwbridge)   |      |            |           |
|           |         | 10.109.250.149 (eth0)          |      |            |           |
+-----------+---------+--------------------------------+------+------------+-----------+
| worker-02 | RUNNING | 172.17.0.1 (docker0)           |      | PERSISTENT | 0         |
|           |         | 172.18.0.1 (docker_gwbridge)   |      |            |           |
|           |         | 10.109.250.71 (eth0)           |      |            |           |
+-----------+---------+--------------------------------+------+------------+-----------+

```
**Test run simple apps**

```
root@swarm:~# docker run --name test --publish 80:80 -d tutum/hello-world
d14d2661c803612c4228172ec490944d79bfbd52b586df73a35ad148aea26c40

```
**test from local** 
```
root@swarm:~# curl localhost
<html>
<head>
	<title>Hello world!</title>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
	<style>
	body {
		background-color: white;
		text-align: center;
		padding: 50px;
		font-family: "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
	}

	#logo {
		margin-bottom: 40px;
	}
	</style>
</head>
<body>
	<img id="logo" src="logo.png" />
	<h1>Hello world!</h1>
	<h3>My hostname is d14d2661c803</h3>	</body>
</html>

```
**test from LXD Host**
```
user@env:~$ curl 10.109.250.164
<html>
<head>
	<title>Hello world!</title>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
	<style>
	body {
		background-color: white;
		text-align: center;
		padding: 50px;
		font-family: "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
	}

	#logo {
		margin-bottom: 40px;
	}
	</style>
</head>
<body>
	<img id="logo" src="logo.png" />
	<h1>Hello world!</h1>
	<h3>My hostname is d14d2661c803</h3>	</body>
</html>
```
