### ISSUE TITLE
Don't create a new container if host disk doesn't have sufficient space

### ISSUE THREAD

**Issue by dooferlad** [lxc/lxd#2458]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu 16.04
```
apiextensions: []
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driverversion: 2.0.4
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-38-generic
  server: lxd
  serverpid: 10184
  serverversion: 2.0.4
  storage: zfs
  storageversion: "5"
config:
  core.proxy_ignore_hosts: 10.224.1.55,127.0.0.1,37.153.111.101,::1
  storage.zfs_pool_name: lxd
public: false
```

# Issue description
This has come out of tracking some bugs down with Juju on Joyent where the root disk is small. LXD will try to create a new container and, in doing so, seems to over-allocate in the ZFS pool, triggering:

From dmesg:

`[ 1090.253680] WARNING: Pool 'lxd' has encountered an uncorrectable I/O failure and has been suspended.`

http://paste.ubuntu.com/23274269/ is the full dmesg output from this point.

```
root@c0b55d45-188c-45dc-8efd-17c6766a5425:~# zpool status -x
  pool: lxd
 state: ONLINE
status: One or more devices are faulted in response to IO failures.
action: Make sure the affected devices are connected, then run 'zpool clear'.
   see: http://zfsonlinux.org/msg/ZFS-8000-HC
  scan: none requested
config:

 NAME STATE READ WRITE CKSUM
 lxd ONLINE 0 640 0
   /var/lib/lxd/zfs.img ONLINE 0 1.30K 0

errors: 640 data errors, use '-v' for a list

This particular issue is documented here:
http://zfsonlinux.org/msg/ZFS-8000-HC/

Data errors took the pool offline.
```

It would be better to check free disk space and not attempt to create a container if the host disk would be filled up.

# Steps to reproduce

 1. Keep starting LXCs until you run out of disk space
