### ISSUE TITLE
lxc publish and lxc image export creates lxd_lxd_metadata_id in archive root instead metadata.yaml

### ISSUE THREAD

**Issue by cryptofuture** [lxc/lxd#2467]
lxc publish and lxc image export creates lxd_lxd_metadata_id in archive root instead metadata.yaml. Renaming lxd_lxd_metadata_id to metadata.yaml in archive root helps. 
Without renaming import shows this error:
`error: Could not extract image metadata.yaml from tar: exit status 2 (tar: metadata.yaml: Not found in archive)`

```
  driver: lxc
  driverversion: 2.0.4
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-41-generic
  server: lxd
  serverpid: 820
  serverversion: 2.0.4
  storage: dir
  storageversion: ""
config:
  core.trust_password: true
public: false

```
