### ISSUE TITLE
not authorized error

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#2491]
After creating a nested container and starting it successfully, I tried to add the container as a remote to the host lxd. That worked:
```
root:~# lxc remote list
+-----------------+------------------------------------------+---------------+--------+--------+
|      NAME       |                   URL                    |   PROTOCOL    | PUBLIC | STATIC |
+-----------------+------------------------------------------+---------------+--------+--------+
| images          | https://images.linuxcontainers.org       | simplestreams | YES    | NO     |
+-----------------+------------------------------------------+---------------+--------+--------+
| local (default) | unix://                                  | lxd           | NO     | YES    |
+-----------------+------------------------------------------+---------------+--------+--------+
| test            | https://10.85.172.111:8443               | lxd           | NO     | NO     |
+-----------------+------------------------------------------+---------------+--------+--------+
| ubuntu          | https://cloud-images.ubuntu.com/releases | simplestreams | YES    | YES    |
+-----------------+------------------------------------------+---------------+--------+--------+
| ubuntu-daily    | https://cloud-images.ubuntu.com/daily    | simplestreams | YES    | YES    |
+-----------------+------------------------------------------+---------------+--------+--------+
```

However, I can't do anything on the remote (especially not live migration ;) ).

```
root:~# lxc launch ubuntu:16.04 test:inner-test2
error: not authorized
root:~# lxc list test:
error: not authorized
root:~# lxc move test:inner-test outer-test
error: Error transferring container data: migration dump failed
(00.035327) Error (ptrace.c:64): suspending seccomp failed: Operation not permitted
```

I think the solution is simple but I couldn't find an appropriate config for this again. :/

**Comment by tych0** [comment]
How did you add the container as a remote? By editing the config or with `lxc remote add`?

**Comment by srkunze** [comment]
By `lxc remote add test 10.85.172.111`

I got the container IP address by lxc list.

**Comment by tych0** [comment]
Hmm, it seems like somehow your client key didn't get added to the target lxd's keystore. Is lxc regenerating a new key each time because it can't write to the config dir or something crazy like that?

**Comment by srkunze** [comment]
I have no idea. How can I check that?

**Comment by tych0** [comment]
What are the perms on `~/.config/lxc`?

**Comment by srkunze** [comment]
```
root@test:~# ll ~/.config/lxc
total 16
drwxr-x--- 2 root root 4096 Oct 13 20:27 ./
drwxr-x--- 3 root root 4096 Oct 13 20:27 ../
-rw-r--r-- 1 root root 2053 Oct 13 20:27 client.crt
-rw------- 1 root root 3247 Oct 13 20:27 client.key
root@test:~# ll ~/.config/lxc -d
drwxr-x--- 2 root root 4096 Oct 13 20:27 /root/.config/lxc/
```

**Comment by tych0** [comment]
I'm confused. Those are the permissions on the host `test`, which is the nested container, no?

**Comment by srkunze** [comment]
Hm. Sorry.

That's the chain: metal host -> container test -> container inner-test

The permissions you just saw are from "test"

**Comment by stgraber** [comment]
Right, but what we're interested in is the ~/.config/lxc for where the lxc client failed, which was on the meta host.

**Comment by srkunze** [comment]
Alright. Here, you are: 
```
root@metal:~# ll ~/.config/lxc
total 24
drwxr-x--- 3 root root 4096 Okt 13 23:25 ./
drwxr-xr-x 5 root root 4096 Okt 13 22:09 ../
-rw-r--r-- 1 root root 2252 Okt 13 23:25 client.crt
-rw------- 1 root root 3243 Okt 13 23:25 client.key
-rw-r--r-- 1 root root  206 Okt 13 23:25 config.yml
drwxr-x--- 2 root root 4096 Okt 13 23:25 servercerts/
root@metal:~# ll ~/.config/lxc -d
drwxr-x--- 3 root root 4096 Okt 13 23:25 /root/.config/lxc/
```

**Comment by stgraber** [comment]
Ok, anyway, the fact that you're running things as root makes it pretty unlikely to be a permission problem.

Can you run "lxc config trust list" inside the container and "lxc info test:" outside of it?

**Comment by srkunze** [comment]
```
root@metal:~# lxc info test:
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
apistatus: stable
apiversion: "1.0"
auth: untrusted
environment:
  addresses: []
  architectures: []
  certificate: ""
  certificatefingerprint: ""
  driver: ""
  driverversion: ""
  kernel: ""
  kernelarchitecture: ""
  kernelversion: ""
  server: ""
  serverpid: 0
  serverversion: ""
  storage: ""
  storageversion: ""
config: {}
public: false
root@metal:~# lxc exec test -- /bin/bash
root@test:~# lxc config trust list
+--------------+----------------+------------------------------+------------------------------+
| FINGERPRINT  |  COMMON NAME   |          ISSUE DATE          |         EXPIRY DATE          |
+--------------+----------------+------------------------------+------------------------------+
| 2edb0ba2c271 | root@metal | Oct 13, 2016 at 9:25pm (UTC) | Oct 11, 2026 at 9:25pm (UTC) |
+--------------+----------------+------------------------------+------------------------------+
```

**Comment by stgraber** [comment]
openssl x509 -noout -fingerprint -sha256 -in ~/.config/lxc/client.crt

**Comment by srkunze** [comment]
metal + test?

**Comment by stgraber** [comment]
metal

**Comment by srkunze** [comment]
SHA256 Fingerprint=2E:DB:0B:A2:C2:71:FF:3B:91:78:7A:C1:9C:E9:1D:60:43:5B:20:79:55:38:87:5C:A4:39:EF:07:8F:45:54:1B

**Comment by stgraber** [comment]
what's the output of "date" on metal?

**Comment by srkunze** [comment]
Fr 14. Okt 00:14:58 CEST 2016

**Comment by stgraber** [comment]
curl -k -s --cert ~/.config/lxc/client.crt --key ~/.config/lxc/client.key https://10.85.172.111:8443/1.0

on metal

**Comment by srkunze** [comment]
root@metal:~# curl -k -s --cert ~/.config/lxc/client.crt --key ~/.config/lxc/client.key https://10.85.172.111:8443/1.0
{"type":"sync","status":"Success","status_code":200,"metadata":{"api_extensions":["storage_zfs_remove_snapshots","container_host_shutdown_timeout","container_syscall_filtering","auth_pki","container_last_used_at","etag","patch","usb_devices","https_allowed_credentials","image_compression_algorithm","directory_manipulation","container_cpu_time","storage_zfs_use_refquota","storage_lvm_mount_options","network","profile_usedby","container_push"],"api_status":"stable","api_version":"1.0","auth":"trusted","config":{"core.https_address":"0.0.0.0:8443","core.trust_password":true},"environment":{"addresses":["10.0.3.1:8443","10.91.243.1:8443","10.85.172.111:8443"],"architectures":["x86_64","i686"],"certificate":"-----BEGIN CERTIFICATE-----\nMIIF6DCCA9CgAwIBAgIQf/uf8fw+gn7CwJOBc/ugGjANBgkqhkiG9w0BAQsFADAy\nMRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRIwEAYDVQQDDAlyb290QHRl\nc3QwHhcNMTYxMDEzMjAyNzMzWhcNMjYxMDExMjAyNzMzWjAyMRwwGgYDVQQKExNs\naW51eGNvbnRhaW5lcnMub3JnMRIwEAYDVQQDDAlyb290QHRlc3QwggIiMA0GCSqG\nSIb3DQEBAQUAA4ICDwAwggIKAoICAQDm5NfdY6pe7MV19q67QclbjMqZXQGKByVW\nyY1tmUadh18BEp3xI+Nlg4sXfNOovPMfsGYcaPfzhYX7un4xufxAsV/5b9OUZiA5\n8FoeEGxeDKoAIVpN3kHD5pVKrGxRJ3RGZivdbkfEkG+LoprKwE2OJdIBunS/5tlr\njXYKtBFTJBADWRDjHsTFql340dv8gYjG44qc+OxGmDeWf+KBQKb/B5r7xOzQaDLA\nUQM6gJ9q+nIXHKzVbZ8/piCW77uDNDyNuOFGGtRqLVzpkDNtmGFvNXxZsLGp7Lk4\ntarXAtRARla+5hOJ+5TQV+fttALHq9wVL8nx/BqibWl+UON4rF6MsA28XMu/uvGf\nJJCdP4cFpfNa/yZ90byj3b5Ez3YKU7F4otTK0lZuq1ELr7yfyL+ZIg1vdRGgDHDm\nG1VQT9t2WVyPFZeGkUC6NAH6h0dPh64g5D0kgH8ITML8QjPUajWFo9wzJMc78BNO\nEYmiQQxFhCiqgBBmGoa8tpw9enyXkKJ9Y+5b0eHS/ObdNJD/2FqhpEvG0XkDVsO0\npAxnmAxdQOvm+Aj0gMIzVuaJjh0HFbL5PyB9T+00MDwPI+/9ocEW+Pv8XGoPNWJx\nPaJUDOi6VBgKOUVNWowKBlJ3ieQmtr0S2AZxlUfb2WxNiHrXVB1e4JeYJnYeeZ/C\nwFafQRGfVQIDAQABo4H5MIH2MA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggr\nBgEFBQcDATAMBgNVHRMBAf8EAjAAMIHABgNVHREEgbgwgbWCBHRlc3SCCzEwLjAu\nMy4xLzI0ghxmZTgwOjo2Yzg4OmY0ZmY6ZmU3NTo4NGFlLzY0ghxmZTgwOjphMDNj\nOmQwZmY6ZmVhMzpkZWEyLzY0ggpmZTgwOjoxLzY0ghAxMC44NS4xNzIuMTExLzI0\ngilmZDQyOmQ1ZTM6NGU3NTplYzkyOjIxNjozZWZmOmZlZGE6MWVkOS82NIIbZmU4\nMDo6MjE2OjNlZmY6ZmVkYToxZWQ5LzY0MA0GCSqGSIb3DQEBCwUAA4ICAQDG6bxg\nQMbH6tCQVd5oBGhTtgXlulDOItugV6tOmnpdHTzRQz/wGGN0xV4X/I8gmEkWOHPf\nw67nbsa4goPKUm7P62IKgWyxlkphF5dbdXNDdDmloxbd8wzea1NtAQyp4G4DdSDj\nH5CmMQCi0zVtC+LRokGFsNSr4Kz3bGXpea1QJ2qDSBVIuYd2jWJ0gU5XStqm9s1L\ndLNWE12aWDcERzyDdoHpZu2woDYypTkuOfWWZZw5/jATr5nVDtFjeV3XTvTgRaR6\nzWMM+ClnXetq4kdJnXcJM9fSE7X9RI6XkXrNmHCVEKhFh82RRfQPPzlsYBahg7W+\nnHtQaa3luQE+Lfki7JFZE0Afd3Arndl7VAP10i53Wf4+fzAEFb+4g2XOK8sZSApo\nyitmA9dFmYez7Ld0gmjH1cN6kpkwVW7kdcpPnml7nrsldaGXKMGQd7MqoF+jyiDo\nr/r5HKE7SJuui4BWb+adK4sieVfMorUj/r2lY414xHtE67sinldqcZwjZ5TtCos/\nCcVK+ZcXxf/TT7JhIIZ7cHNz00CTvmKrJKon9Y2Q+GurR0K1/1jO5qU0qB7XvOPy\n4WvCI5D+KBGQZyK0G6p97MA99xTiI9O04kF7ClGyiFcKBkv5S0KmaT9y8gbWaNXb\nDoLgiw4E0SbvGO/quyUepcMm4NYEK5SvMueFzQ==\n-----END CERTIFICATE-----\n","driver":"lxc","driver_version":"2.0.5","kernel":"Linux","kernel_architecture":"x86_64","kernel_version":"4.4.0-42-generic","server":"lxd","server_pid":319,"server_version":"2.4.1","storage":"dir","storage_version":""},"public":false}}

**Comment by stgraber** [comment]
Ok, so the problem isn't with the LXD in the container since that query now shows you as trusted...

Did the output of "lxc info test:" change now by any chance?

**Comment by srkunze** [comment]
```
root@metal:~# lxc info test:
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
apistatus: stable
apiversion: "1.0"
auth: untrusted
environment:
  addresses: []
  architectures: []
  certificate: ""
  certificatefingerprint: ""
  driver: ""
  driverversion: ""
  kernel: ""
  kernelarchitecture: ""
  kernelversion: ""
  server: ""
  serverpid: 0
  serverversion: ""
  storage: ""
  storageversion: ""
config: {}
public: false
```

I don't think so.
