### ISSUE TITLE
Pinging via lxc exec fails when running from a bash script

### ISSUE THREAD

**Issue by frankscholten** [lxc/lxd#2542]
# Issue description

I want to script the creation of images. However when I run commands that access the network like `apt-get` I get and `Unknown host` error.

# Steps to reproduce

Create the following script `build.sh`

```
#!/bin/bash

lxc launch ubuntu:16.04 build

lxc exec build -- ping ubuntu.com
```

Output

```
$ ./build.sh
Creating build
Starting build
ping: unknown host ubuntu.com
```

However when I run these commands separately and not via a shell script pinging does work.

```
frank@franktop:~/src/sandbox-lxd$ lxc launch ubuntu:16.04 build 
Creating build
Starting build
frank@franktop:~/src/sandbox-lxd$ lxc exec build -- ping ubuntu.com
PING ubuntu.com (91.189.94.40) 56(84) bytes of data.
64 bytes from ovinnik.canonical.com (91.189.94.40): icmp_seq=1 ttl=51 time=16.2 ms
64 bytes from ovinnik.canonical.com (91.189.94.40): icmp_seq=2 ttl=51 time=15.2 ms
^C
--- ubuntu.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 15.212/15.737/16.263/0.540 ms
```

# System Information

 * Distribution: Ubuntu
 * Distribution version: 16.04

```
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: <SNIP>
  certificatefingerprint: <SNIP>
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-45-generic
  server: lxd
  serverpid: 11875
  serverversion: 2.4.1
  storage: dir
  storageversion: ""
config: {}
public: false
```
