### ISSUE TITLE
lxd network attach-profile lxdbr0 default doesn't create a device named eth0

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#2552]
```
dev:~ lxc network attach-profile lxdbr0 default
dev:~ lxc profile show default
name: default
config: {}
description: Default LXD profile
devices:
  lxdbr0:
    nictype: bridged
    parent: lxdbr0
    type: nic
usedby: []
```

We should call this device eth0. More generally, we should compute `eth%d` for the next integer value.
