### ISSUE TITLE
USB pass-thought fails

### ISSUE THREAD

**Issue by haarts** [lxc/lxd#2556]
I'd like to use an LXD container to develop for Android. Keep it all nice and separated. 
I've started a privileged container (to share my code on the host machine with the client) and added an USB device. The device seems to show up on the container but is unusable.
# Steps to reproduce
1. Start a container (I've used Arch) `lxc launch images:archlinux my-container`
2. Make it a privileged container (not sure this is relevant). `lxc config set my-container security.privileged true`
3. Plugin a phone and figure out the vendorid and deviceid with `lsusb`. (BTW deviceid is required as opposed to what the docs say)
4. Observe that `/dev/bus/usb/xxx/yyy` now exists on the host and not the container
5. Add the device with: `lxc config device add my-container my-phone usb vendorid=18d1 productid=4e42`
6. Observe that `/dev/bus/usb/xxx/yyy` now exists on the container.
7. `cat /dev/bus/usb/xxx/yyy` on container yields `cat: /dev/bus/usb/xxx/yyy: No such device or address`

On the host: `ls -l /dev/bus/usb/xxx/yyy`:

```
crw-rw-r-- 1 root adbusers 189, 63 25 okt 11:41 /dev/bus/usb/001/062
```

On the container: `ls -l /dev/bus/usb/xxx/yyy`:

```
crw-rw---- 1 root root 61, 189 Oct 25 09:35 /dev/bus/usb/001/062
```

`lxc info`:

```
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: <snip>
  certificatefingerprint: 3a8c8b7e55185ec647323fbf95305f2ebb0e89077ccef844df68799551f57955
  driver: lxc
  driverversion: 2.0.4
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.19-1-lts-userns
  server: lxd
  serverpid: 22039
  serverversion: "2.1"
  storage: dir
  storageversion: ""
config: {}
public: false
```

`lxc info my-container`:

```
Name: my-container
Architecture: x86_64
Created: 2016/10/24 12:03 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 813
Ips:
  eth0: inet    10.202.80.247   veth4QLNRF
  eth0: inet6   fe80::216:3eff:fe2d:ec1a    veth4QLNRF
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 38
  Memory usage:
    Memory (current): 501.48MB
    Memory (peak): 746.71MB
  Network usage:
    eth0:
      <snip>
    lo:
      <snip>
```

`lxc config show my-container`:

```
name: my-container
profiles:
- default
config:
  security.privileged: "true"
  volatile.base_image: 260bc1f340935aa338b3b680e3b43b6c3a3d1f8d9cd46067598d28f5fadd1c1a
  volatile.eth0.hwaddr: 00:16:3e:2d:ec:1a
  volatile.last_state.idmap: '[]'
devices:
  my-phone:
    productid: "4e42"
    type: usb
    vendorid: 18d1
  root:
    path: /
    type: disk
  software:
    path: /root/source
    source: /home/harm/prj/my-source/
    type: disk
ephemeral: false
```

I'm at a loss here.
