### ISSUE TITLE
lxc doesn't export metadata properties in metadata.yaml

### ISSUE THREAD

**Issue by dridk** [lxc/lxd#2560]
# Required information

 * Distribution: Ubuntu
 * Distribution version: Xenial 
 * The output of "lxc info" 
  architectures:
  - x86_64
  - i686
  - driver: lxc
  - driverversion: 2.0.5
  - kernel: Linux
  - kernelarchitecture: x86_64
  - kernelversion: 4.4.0-45-generic
  - server: lxd
  - serverpid: 2433
  - serverversion: 2.0.5
  - storage: dir
  - storageversion: ""

# Issue description

lxc doesn't export properties in metadata.yaml . 

# Steps to reproduce

 1. Publish an image with properties 

`lxc publish test --alias=myImage description=test age=32`

 2. Check if age and description properties are define . ( It works)
```
lxc image info myImage
Size: 125.08MB
Architecture: x86_64
Public: no
Timestamps:
    Created: 0001/01/01 00:00 UTC
    Uploaded: 2016/10/25 21:32 UTC
    Expires: 0001/01/01 00:00 UTC
Properties:
    age: 32
    description: test
Aliases:
    - myImage
Auto update: disabled
```

 3. Export image and check the content of metadata 

```
 lxc image export myImage image
tar -zxvf image.tar.gz 
cat metadata.yaml 
{
    "architecture": "x86_64",
    "creation_date": 1477367340,
    "properties": {
        "architecture": "x86_64",
        "description": "ubuntu xenial x86_64 (default) (20161025_03:49)",
        "name": "ubuntu-xenial-x86_64-default-20161025_03:49",
        "os": "ubuntu",
        "release": "xenial",
        "variant": "default"
    },
```

Properties are gone ! 
It seems it use the metadata from the original image I used to make my own image.
