### ISSUE TITLE
--debug doesn't show requests

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#2561]
* Distribution: Vista 32
 * The output of "lxc info":
```
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.8.0-26-generic
  server: lxd
  serverpid: 2703
  serverversion: 2.4.1
  storage: dir
  storageversion: ""
```
   * LXC version: 2.5

### Issue description

I am trying to debug issue with pushing files and I don't see the request that is being set to server. 
```
>lxc file push --debug --verbose t01list.py far2l/root
DBUG[10-26|12:20:26] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{}}
```

Looks like https://github.com/lxc/lxd/tree/master/doc is missing hacking/development guide. There are some bits in README.md, but they are not enough for this case.

**Comment by techtonik** [comment]
In #2565 it looks that client sends paths with backward slashes, but how to see this?

**Comment by tych0** [comment]
You can look at the server, which prints out every request in --debug mode.

**Comment by techtonik** [comment]
Well, the server is located on remote box behind a firewall. Is there a way to do this from a client?

**Comment by tych0** [comment]
Not right now.

**Comment by techtonik** [comment]
Let me recap. Stop server as a service:
```
systemctl stop lxd.service lxd.socket
```
Then start it in foreground:
```
sudo lxd --debug
```

**Comment by techtonik** [comment]
Yes, POST gives url ending with `..files?path=%5Croot", and %5C is a backslash \

**Comment by stgraber** [comment]
There sure is a way, just run "lxc monitor", that will send you a copy of all the log entries of the server.

**Comment by stgraber** [comment]
with lxc monitor, a file push shows me:

```
metadata:
  context:
    ip: '@'
    method: POST
    url: /1.0/containers/base/files?path=%2Ftmp%2Fa
  level: dbug
  message: handling
timestamp: 2016-10-26T14:51:16.354752318-04:00
type: logging


metadata:
  context:
    container: base
    driver: storage/zfs
  level: dbug
  message: ContainerStart
timestamp: 2016-10-26T14:51:16.364511254-04:00
type: logging


metadata:
  context:
    container: base
    driver: storage/zfs
  level: dbug
  message: ContainerStop
timestamp: 2016-10-26T14:51:16.37808558-04:00
type: logging


metadata:
  context: {}
  level: dbug
  message: "\n\t{\n\t\t\"type\": \"sync\",\n\t\t\"status\": \"Success\",\n\t\t\"status_code\":
    200,\n\t\t\"metadata\": {}\n\t}"
timestamp: 2016-10-26T14:51:16.378442449-04:00
type: logging
```

That's probably good enough for now. I agree that proper logging of requests would be nice too, I'll add a note to #1926
