### ISSUE TITLE
cron.daily error regarding mdma

### ISSUE THREAD

**Issue by l00mi** [lxc/lxd#2571]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
```
environment:
  architectures:
  - x86_64
  - i686
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-38-generic
  server: lxd
  serverpid: 15681
  serverversion: 2.0.5
  storage: zfs
  storageversion: "5"
```
# Issue description

Not sure if the right place for this Issue. We get on our `lxc launch ubuntu:` installations a `run-parts: /etc/cron.daily/mdadm exited because of uncaught signal 11`.

The output of the script `mdadm --monitor --scan --oneshot`:
`Segmentation fault (core dumped)`

# Steps to reproduce

Create new container, wait for email (-,
