### ISSUE TITLE
Image updating umounts some mounted zfs filesystems (possibly)

### ISSUE THREAD

**Issue by danielllek** [lxc/lxd#2617]
I'm using lxd from few weeks and I have found that some zfs filesystems get umounted "magically".
Today I've finally found possible source of problem:
* On 6:43 on graphs I've noticed drop of disk usage (graph shows sum of disk usage from all mounted zfs filesystems)
* I've one cron job that writes file every hour from host system to this mounted filesystem, and it started failing (first time at 7:00)
* After looking without success at various cron jobs (first suspect was cron.daily) and lxd per container logs, I've found that exactly before that lxd logged in master log:
```t=2016-11-16T06:41:56+0100 lvl=info msg="Updating images"
t=2016-11-16T06:41:57+0100 lvl=info msg="Downloading image" alias=x server=https://cloud-images.ubuntu.com/releases
t=2016-11-16T06:42:45+0100 lvl=info msg="Image downloaded" alias=x server=https://cloud-images.ubuntu.com/releases
t=2016-11-16T06:42:58+0100 lvl=info msg="Done updating images"
```

Is that a known bug/fixed later than 2.0.5 (ubuntu 16.04 has rather old version of lxd)?

```
 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info":
# lxc info
apiextensions: []
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-45-generic
  server: lxd
  serverpid: 4770
  serverversion: 2.0.5
  storage: zfs
  storageversion: "5"
config:
  storage.zfs_pool_name: data
public: false
```
