### ISSUE TITLE
"Could not initialize storage type ZFS" after upgrade to 2.0.5

### ISSUE THREAD

**Issue by lckarssen** [lxc/lxd#2639]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04 LTS
 * The output of "lxc info":
   
```
apiextensions: []
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    REMOVED STUFF HERE
    -----END CERTIFICATE-----
  certificatefingerprint: 610bd0838806583df3751343981e0a9235e7bee425be3ec42d01af4c217541d9
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-24-generic
  server: lxd
  serverpid: 21891
  serverversion: 2.0.5
  storage: dir
  storageversion: ""
config:
  storage.zfs_pool_name: SSDpool
public: false
```

# Issue description

After upgrading to the latest Ubuntu package version (2.0.5-0ubuntu1~ubuntu16.04.1) lxd fails to start (and hence all my containers remain down). Restarting the lxd service gives the following entry in `/var/log/syslog` and `/var/log/lxd/lxd.log`:
```
lvl=eror msg="Could not initialize storage type ZFS: Failed to run: zfs set mountpoint
=none SSDpool: umount: /SSDpool: target is busy\n        (In some cases useful info about processes that\n         use the device is found by lsof(8) 
or fuser(1).)\ncannot unmount '/SSDpool': umount failed - falling back to dir"
```
So lxd tries to unmount my ZFS pool. Why? The fact that is tails is correct, I have other filesystems in the pool (e.g. `/usr/local`, `/opt/` and `/var/lib/lxd`). 

The commit message of [commit 2a24b81](https://github.com/lxc/lxd/commit/2a24b813d39d713a69cb00f24828d25d6c239e43) says: 

> LXD assumes that it completely owns whatever storage.zfs_pool_name points to

Is that indeed true? So far this never was a problem...
