### ISSUE TITLE
Include statement in profile

### ISSUE THREAD

**Issue by overquota** [lxc/lxd#2648]
Hello!
Could you add possibility to include 1 profile into another profile?

E.g. I have `base` profile:
```
name: base
config:
  user.network_mode: link-local
  user.vendor-data: |
    #cloud-config
    system_info:
      apt_get_command:
        - 'apt-get'
        - '-y'
        - '--force-yes'
        - '--quiet'
...
```

`vlan` profile:
```
name: vlan556
config: {}
description: Container device for 556 vlan
devices:
  eth0:
    nictype: bridged
    parent: br0.556
    type: nic
usedby: []
```

And I need to create some project machine, which would have base profile and 1 of the vlan's profile (there may be many vlan profiles)
Now I need to write `lxc launch ubuntu: container -p base -p vlan556`
I want to shorter this to `lxc launch ubuntu: container -p <containers_project>`
where <containers_project> profile contains something like this:
```
name: <containers_project>
include:
  - base
  - vlan556
```
