### ISSUE TITLE
containter in ERROR state

### ISSUE THREAD

**Issue by nnovikov** [lxc/lxd#2654]
Hi!

After upgrade LXD from 2.5-0ubuntu1~ubuntu16.04.1~ppa1 to
2.6.2-0ubuntu1~ubuntu16.04.1~ppa1 all containters have ERROR state.

In log I see problems with lxc_parse: 

`lxc 20161126134719.275 ERROR    lxc_parse - parse.c:lxc_file_for_each_line:57 - Failed to parse config: lxc.start.auto =`

Some info:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

```
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
  - X.X.X.X:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  certificatefingerprint: ...
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-47-generic
  server: lxd
  serverpid: 2479
  serverversion: 2.6.2
  storage: lvm
  storageversion: 2.02.133(2) (2015-10-30) / 1.02.110 (2015-10-30) / 4.34.0
config:
  core.https_address: '[::]'
  core.trust_password: true
  storage.lvm_fstype: xfs
  storage.lvm_thinpool_name: lxdpool
  storage.lvm_vg_name: vg0
public: false
```
