### ISSUE TITLE
error: Bad key: raw.idmap

### ISSUE THREAD

**Issue by shawnnpatti** [lxc/lxd#2677]
* Distribution: Ubuntu
 * Distribution version: 16.04
 * lxc info
```
apiextensions: []
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-51-generic
  server: lxd
  serverpid: 6511
  serverversion: 2.0.5
  storage: zfs
  storageversion: "5"
```
# Issue description
```
lxc config set devc raw.idmap "both 1000 1000"
error: Bad key: raw.idmap
```
A brief description of what failed or what could be improved.
I'm attempting to follow the userns-id.md doc for custom namespace to do bind mounts and am running into this error. 

# Steps to reproduce

 1. execute lxc config set devc raw.idmap "both 1000 1000"
 2. error: Bad key: raw.idmap
