### ISSUE TITLE
Unable get IP address via DHCP

### ISSUE THREAD

**Issue by gedOHub** [lxc/lxd#2688]
# Required information

```
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
...
driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-51-generic
  server: lxd
  serverpid: 25295
  serverversion: 2.6.2
  storage: zfs
  storageversion: "5"
config:
  storage.zfs_pool_name: lxd
public: false
```

# Issue description

Unable to get IP address from DHCP and static address from LXD configuration. Able add IP only via manual commands like ip addr or ip route. No response to /etc/networking/interfaces changes

# Information to attach

 - [ ] any relevant kernel output (dmesg)
``[ 6577.942011] device vethJU1KE8 entered promiscuous mode
[ 6577.942098] IPv6: ADDRCONF(NETDEV_UP): vethJU1KE8: link is not ready
[ 6577.943696] device vethN990WD entered promiscuous mode
[ 6577.943790] IPv6: ADDRCONF(NETDEV_UP): vethN990WD: link is not ready
[ 6577.943815] lxdbr0: port 1(vethN990WD) entered forwarding state
[ 6577.943823] lxdbr0: port 1(vethN990WD) entered forwarding state
[ 6578.020971] eth0: renamed from vethMCG3S8
[ 6578.036607] eth1: renamed from vethQ217F2
[ 6578.049834] IPv6: ADDRCONF(NETDEV_CHANGE): vethN990WD: link becomes ready
[ 6578.049932] IPv6: ADDRCONF(NETDEV_CHANGE): vethJU1KE8: link becomes ready
[ 6578.049981] baltnetabr: port 2(vethJU1KE8) entered forwarding state
[ 6578.049990] baltnetabr: port 2(vethJU1KE8) entered forwarding state
[ 6578.613876] audit: type=1400 audit(1480941988.568:937): apparmor="STATUS" operation="profile_load" label="lxd-proxy_</var/lib/lxd>//&:lxd-proxy_<var-lib-lxd>://unconfined" name="/usr/bin/lxc-start" pid=30549 comm="apparmor_parser"
...
[ 6578.990411] audit: type=1400 audit(1480941988.944:945): apparmor="STATUS" operation="profile_load" label="lxd-proxy_</var/lib/lxd>//&:lxd-proxy_<var-lib-lxd>://unconfined" name="/usr/lib/connman/scripts/dhclient-script" pid=30547 comm="apparmor_parser"
[ 6589.713885] audit_printk_skb: 78 callbacks suppressed
[ 6589.713891] audit: type=1400 audit(1480941999.668:972): apparmor="DENIED" operation="file_perm" namespace="root//lxd-proxy_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=30652 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[ 6589.713906] audit: type=1400 audit(1480941999.668:973): apparmor="DENIED" operation="file_perm" namespace="root//lxd-proxy_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=30652 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[ 6592.988008] lxdbr0: port 1(vethN990WD) entered forwarding state
[ 6593.052007] baltnetabr: port 2(vethJU1KE8) entered forwarding state
[ 6599.771198] audit: type=1400 audit(1480942009.724:974): apparmor="DENIED" operation="file_perm" namespace="root//lxd-proxy_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=30652 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
...
[ 6873.050243] audit: type=1400 audit(1480942283.003:1017): apparmor="DENIED" operation="file_perm" namespace="root//lxd-proxy_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=30652 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0``
 - [ ] container log (lxc info NAME --show-log)
`lxc info proxy --show-log
Name: proxy
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2016/12/05 12:45 UTC
Status: Running
Type: persistent
Profiles: unlimited_baltneta
Pid: 29882
Ips:
  eth0:	inet6	fe80::216:3eff:fee9:91e3	vethJU1KE8
  eth1:	inet6	fe80::216:3eff:fe9a:8a72	vethN990WD
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 25
  Disk usage:
    root: 6.42MB
  CPU usage:
    CPU usage (in seconds): 8
  Memory usage:
    Memory (current): 87.47MB
    Memory (peak): 209.11MB
  Network usage:
    eth0:
      Bytes received: 9.79kB
      Bytes sent: 8.98kB
      Packets received: 124
      Packets sent: 33
    eth1:
      Bytes received: 948 bytes
      Bytes sent: 648 bytes
      Packets received: 10
      Packets sent: 8
    lo:
      Bytes received: 1.52kB
      Bytes sent: 1.52kB
      Packets received: 20
      Packets sent: 20

Log:

            lxc 20161205144627.682 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:265 - Seccomp: failed to resolve syscall: .
            lxc 20161205144627.682 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:266 - This syscall will NOT be blacklisted.
            lxc 20161205144627.682 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:265 - Seccomp: failed to resolve syscall: .
            lxc 20161205144627.682 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:266 - This syscall will NOT be blacklisted.
            lxc 20161205144628.059 WARN     lxc_start - start.c:signal_handler:338 - invalid pid for SIGCHLD
            lxc 20161205144637.306 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:265 - Seccomp: failed to resolve syscall: .
            lxc 20161205144637.306 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:266 - This syscall will NOT be blacklisted.
            lxc 20161205144637.306 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:265 - Seccomp: failed to resolve syscall: .
            lxc 20161205144637.306 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:266 - This syscall will NOT be blacklisted.
`
 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment]
How did you create that container?

**Comment by gedOHub** [comment]
Container init command:

`lxc init ubuntu-daily: proxy -p unlimited`

Profile info:

```
lxc profile show unlimited
name: unlimited
config: {}
description: ""
devices:
  eth0:
    nictype: bridged
    parent: br
    type: nic
  eth1:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    type: disk
usedby:
- /1.0/containers/proxy
```

br interface info:
```
auto br
iface br inet manual
	bridge_ports enp3s0.103
```
ip addr info:

```
9: br: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:1a:64:ca:1b:00 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::21a:64ff:feca:1b00/64 scope link 
       valid_lft forever preferred_lft foreve
47: lxdbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether fe:01:86:32:ac:c9 brd ff:ff:ff:ff:ff:ff
    inet 172.17.4.1/24 scope global lxdbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::a804:efff:fec1:31b7/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by stgraber** [comment]
So I just tried here on 2.6.2:

```
stgraber@castiana:~$ lxc launch ubuntu-daily: blah
Creating blah
Starting blah
stgraber@castiana:~$ lxc exec blah -- ifconfig -a
eth0      Link encap:Ethernet  HWaddr 00:16:3e:1a:26:bc
          inet addr:10.166.57.10  Bcast:10.166.57.255  Mask:255.255.255.0
          inet6 addr: fd42:c5cf:7d6a:2987:216:3eff:fe1a:26bc/64 Scope:Global
          inet6 addr: fe80::216:3eff:fe1a:26bc/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:84 errors:0 dropped:0 overruns:0 frame:0
          TX packets:17 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:10631 (10.6 KB)  TX bytes:1820 (1.8 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
````

Maybe the problem is caused by having two network devices attached to the container?
I'm not sure exactly what cloud-init does in that case in Ubuntu 16.04, maybe it's trying to DHCP on the wrong one?

**Comment by gedOHub** [comment]
Okey, deleted that container and created new.

```
lxc init ubuntu-daily: proxy -p unlimited
Creating proxy

The container you are starting doesn't have any network attached to it.
  To create a new network, use: lxc network create
  To attach a network to a container, use: lxc network attach
```
Profile info:
```
lxc profile show unlimited
name: unlimited
config: {}
description: ""
devices:
  root:
    path: /
    type: disk
usedby:
- /1.0/containers/proxy
```
Config info:
```
lxc config show proxy 
name: proxy
profiles:
- unlimited
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (daily) (20161203)
  image.label: daily
  image.os: ubuntu
  image.release: xenial
  image.serial: "20161203"
  image.version: "16.04"
  volatile.base_image: 3ed1d991fa3d009e031f7c4982d1226f5440541447dda9d111108fb827a81bab
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: STOPPED
devices: {}
ephemeral: false
```

Attaching first interface
`lxc network attach lxdbr0 proxy`

Running it. DHCP address was set:
```
lxc list
+-------+---------+---------------------+------+------------+-----------+
| NAME  |  STATE  |        IPV4         | IPV6 |    TYPE    | SNAPSHOTS |
+-------+---------+---------------------+------+------------+-----------+
| proxy | RUNNING | 172.17.4.244 (eth0) |      | PERSISTENT | 0         |
+-------+---------+---------------------+------+------------+-----------+
```
Setting static IP:
```
lxc config device set proxy eth0 ipv4.address 172.17.4.2
lxc start proxy
lxc list
+-------+---------+-------------------+------+------------+-----------+
| NAME  |  STATE  |       IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
+-------+---------+-------------------+------+------------+-----------+
| proxy | RUNNING | 172.17.4.2 (eth0) |      | PERSISTENT | 0         |
+-------+---------+-------------------+------+------------+-----------+
```
Adding another interface:
`lxc network attach br proxy`
Config:
```
lxc config show proxy 
name: proxy
profiles:
- unlimited
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (daily) (20161203)
  image.label: daily
  image.os: ubuntu
  image.release: xenial
  image.serial: "20161203"
  image.version: "16.04"
  volatile.baltnetabr.hwaddr: 00:16:3e:4f:25:99
  volatile.baltnetabr.name: eth1
  volatile.base_image: 3ed1d991fa3d009e031f7c4982d1226f5440541447dda9d111108fb827a81bab
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
  volatile.lxdbr0.hwaddr: 00:16:3e:c2:0d:aa
  volatile.lxdbr0.name: eth0
devices:
  baltnetabr:
    nictype: bridged
    parent: baltnetabr
    type: nic
  lxdbr0:
    ipv4.address: 172.17.4.2
    nictype: bridged
    parent: lxdbr0
    type: nic
ephemeral: false
```
Adding IP info to /etc/network/interfaces
```
auto eth1
iface eth1 inet manual
	address xx.xx.xx.xx
	netmask mm.mm.mm.mm
	gateway xx.xx.xx.yy
	dns-servers zz.zz.zz.zz zz.zz.zz.zz
```
Restarting networking:
`service networking restart`
ip addr info:
```
ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
66: eth1@if67: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:4f:25:99 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::216:3eff:fe4f:2599/64 scope link 
       valid_lft forever preferred_lft forever
68: eth0@if69: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:c2:0d:aa brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.4.2/24 brd 172.17.4.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fec2:daa/64 scope link 
       valid_lft forever preferred_lft forever
```
No change. Dmesg output:
```
[38194.982827] audit: type=1400 audit(1480973604.934:1241): apparmor="DENIED" operation="file_inherit" namespace="root//lxd-proxy_<var-lib-lxd>" profile="/sbin/dhclient" name="/run/systemd/journal/stdout" pid=7032 comm="dhclient" requested_mask="wr" denied_mask="wr" fsuid=100000 ouid=100000
[38194.982846] audit: type=1400 audit(1480973604.934:1242): apparmor="DENIED" operation="file_inherit" namespace="root//lxd-proxy_<var-lib-lxd>" profile="/sbin/dhclient" name="/run/systemd/journal/stdout" pid=7032 comm="dhclient" requested_mask="wr" denied_mask="wr" fsuid=100000 ouid=100000
[38194.985008] audit: type=1400 audit(1480973604.938:1243): apparmor="DENIED" operation="file_perm" namespace="root//lxd-proxy_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=7032 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[38194.985022] audit: type=1400 audit(1480973604.938:1244): apparmor="DENIED" operation="file_perm" namespace="root//lxd-proxy_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=7032 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[38195.985144] audit: type=1400 audit(1480973605.942:1245): apparmor="DENIED" operation="file_perm" namespace="root//lxd-proxy_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=7032 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[38195.985159] audit: type=1400 audit(1480973605.942:1246): apparmor="DENIED" operation="file_perm" namespace="root//lxd-proxy_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=7032 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[38195.985186] audit: type=1400 audit(1480973605.942:1247): apparmor="DENIED" operation="file_perm" namespace="root//lxd-proxy_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=7032 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[38195.985198] audit: type=1400 audit(1480973605.942:1248): apparmor="DENIED" operation="file_perm" namespace="root//lxd-proxy_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=7032 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[38195.985224] audit: type=1400 audit(1480973605.942:1249): apparmor="DENIED" operation="file_perm" namespace="root//lxd-proxy_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=7032 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[38195.985237] audit: type=1400 audit(1480973605.942:1250): apparmor="DENIED" operation="file_perm" namespace="root//lxd-proxy_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=7032 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[38196.048841] lxdbr0: port 1(veth6RYF6V) entered disabled state
[38196.259965] lxdbr0: port 1(veth6RYF6V) entered forwarding state
[38196.259979] lxdbr0: port 1(veth6RYF6V) entered forwarding state
```
Syslog:
```
Dec  5 21:52:23 proxy systemd[1]: Started Raise network interfaces.
Dec  5 21:54:01 proxy systemd[1]: Stopping User Manager for UID 0...
Dec  5 21:54:01 proxy systemd[474]: Stopped target Default.
Dec  5 21:54:01 proxy systemd[474]: Reached target Shutdown.
Dec  5 21:54:01 proxy systemd[474]: Stopped target Basic System.
Dec  5 21:54:01 proxy systemd[474]: Stopped target Sockets.
Dec  5 21:54:01 proxy systemd[474]: Stopped target Timers.
Dec  5 21:54:01 proxy systemd[474]: Stopped target Paths.
Dec  5 21:54:01 proxy systemd[474]: Starting Exit the Session...
Dec  5 21:54:01 proxy systemd[474]: Received SIGRTMIN+24 from PID 1221 (kill).
Dec  5 21:54:01 proxy systemd[1]: Stopped User Manager for UID 0.
Dec  5 21:54:01 proxy systemd[1]: Removed slice User Slice of root.
Dec  5 21:54:52 proxy systemd[1]: Created slice User Slice of root.
Dec  5 21:54:52 proxy systemd[1]: Failed to reset devices.list on /user.slice/user-0.slice: Operation not permitted
Dec  5 21:54:52 proxy systemd[1]: Failed to reset devices.list on /user.slice/user-0.slice/user@0.service: Operation not permitted
Dec  5 21:54:52 proxy systemd[1]: Starting User Manager for UID 0...
Dec  5 21:54:52 proxy systemd[1]: Failed to reset devices.list on /user.slice/user-0.slice/session-43.scope: Operation not permitted
Dec  5 21:54:52 proxy systemd[1]: Started Session 43 of user root.
Dec  5 21:54:52 proxy systemd[1251]: Reached target Paths.
Dec  5 21:54:52 proxy systemd[1251]: Reached target Timers.
Dec  5 21:54:52 proxy systemd[1251]: Reached target Sockets.
Dec  5 21:54:52 proxy systemd[1251]: Reached target Basic System.
Dec  5 21:54:52 proxy systemd[1251]: Reached target Default.
Dec  5 21:54:52 proxy systemd[1251]: Startup finished in 7ms.
Dec  5 21:54:52 proxy systemd[1]: Started User Manager for UID 0.
```

Run out of ideas...

**Comment by gedOHub** [comment]
Another test.
Created new container:
```
lxc init ubuntu-daily: proxy -p unlimited
Creating proxy

The container you are starting doesn't have any network attached to it.
  To create a new network, use: lxc network create
  To attach a network to a container, use: lxc network attach
```
Profile info:
```
lxc profile show unlimited
name: unlimited
config: {}
description: Neribojami resursai
devices:
  root:
    path: /
    type: disk
usedby:
- /1.0/containers/proxy
```
First attached br bridge
`lxc network attach br proxy`
Then lxd bridge
```
lxc network attach lxdbr0 proxy 
lxc config device show proxy 
baltnetabr:
  nictype: bridged
  parent: baltnetabr
  type: nic
lxdbr0:
  nictype: bridged
  parent: lxdbr0
  type: nic

```
Set static IP for LXD interface
```
lxc config device set proxy lxdbr0 ipv4.address 172.17.4.2
lxc config device show proxy 
baltnetabr:
  nictype: bridged
  parent: baltnetabr
  type: nic
lxdbr0:
  ipv4.address: 172.17.4.2
  nictype: bridged
  parent: lxdbr0
  type: nic
lxc start proxy

```
And no result:
```
lxc list
+-------+---------+------+------+------------+-----------+
| NAME  |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+-------+---------+------+------+------------+-----------+
| proxy | RUNNING |      |      | PERSISTENT | 0         |
+-------+---------+------+------+------------+-----------+
```
Also no syslog in container...
```
lxc shell proxy 
run-parts: /etc/update-motd.d/98-fsck-at-reboot exited with return code 1

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

mesg: ttyname failed: Success
root@proxy:~# less /var/log/syslog
/var/log/syslog: No such file or directory

```
Removing IP address
`lxc config device unset proxy lxdbr0 ipv4.address`
No DHCP lease
```
lxc restart proxy
lxc info proxylxc info proxy
Name: proxy
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2016/12/06 07:51 UTC
Status: Running
Type: persistent
Profiles: unlimited
Pid: 4495
Ips:
  eth0:	inet6	fe80::216:3eff:fe6e:50e3	veth8OOE7E
  eth1:	inet6	fe80::216:3eff:fe58:5679	vethWWBIOO
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 6
  Disk usage:
    root: 6.43MB
  CPU usage:
    CPU usage (in seconds): 1
  Memory usage:
    Memory (current): 11.38MB
    Memory (peak): 31.36MB
  Network usage:
    eth0:
      Bytes received: 2.23kB
      Bytes sent: 3.97kB
      Packets received: 26
      Packets sent: 18
    eth1:
      Bytes received: 948 bytes
      Bytes sent: 648 bytes
      Packets received: 10
      Packets sent: 8
    lo:
      Bytes received: 0 bytes
      Bytes sent: 0 bytes
      Packets received: 0
      Packets sent: 0
```
Have I done some mistake in config? Or find a bug?
