### ISSUE TITLE
Docker in LXD limits not kept

### ISSUE THREAD

**Issue by giany** [lxc/lxd#2729]
* Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:

```
root@bench:~# lxc info
apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
  - 10.135.87.110:8443
  - 169.50.34.36:8443
  - 10.218.213.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
..................
    -----END CERTIFICATE-----
  certificatefingerprint: 123c9de4ba5ebe2aada4248df9d934376cd0c1e1798d1e1f9f162a0608607365
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-53-generic
  server: lxd
  serverpid: 1529
  serverversion: 2.0.8
  storage: dir
  storageversion: ""
config:
  core.https_address: '[::]:8443'
public: false

```

# Issue description

Containers started in docker on a lxc container show the whole resources even though I've set limits on the lxc container.

```
root@bench:~# free -m
              total        used        free      shared  buff/cache   available
Mem:           8015         186        5681          30        2146        7665
Swap:          2047          10        2036
root@bench:~# lxc exec srv2 -- /bin/bash
root@srv2:~# free -m
              total        used        free      shared  buff/cache   available
Mem:            300         271          28          30           0          28
Swap:          2047          10        2036
root@srv2:~# docker exec -ti 361c64ba551e bash
root@361c64ba551e:/# free -m
             total       used       free     shared    buffers     cached
Mem:          8015       2342       5672         30        160       1736
-/+ buffers/cache:        445       7569
Swap:         2047         10       2036

```
Notice that the docker container has the same amount of memory as the host (bench). It should show the same as srv2.

# Steps to reproduce

 1. Start a lxc container
 2. Set a limit (memory/cpu) on that container
 3. In LXC container install docker and start a container
