### ISSUE TITLE
CGROUP does not get deleted on failure.

### ISSUE THREAD

**Issue by pcdummy** [lxc/lxd#2764]
This is not a common bug but a IMHO a bug:

When LXD fails to create a container `Failed to set up id mapping.` the cgroup gets never deleted:

    error: Error calling 'lxd forkstart psql1 /var/lib/lxd/containers /var/log/lxd/psql1/lxc.conf': err='exit status 1'
    lxc 20161224084734.754 ERROR lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1310 - Path "/sys/fs/cgroup/systemd//lxc/psql1" already existed.
    lxc 20161224084734.754 ERROR lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1367 - No such file or directory - Failed to create /sys/fs/cgroup/systemd//lxc/psql1: No such file or directory

# Required information

 * Distribution: Ubuntu
 * Distribution version: Xenial
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-57-generic
   * LXC version: 2.6.2
   * LXD version: 2.6.2
   * Storage backend in use: BTRFS

# Steps to reproduce

 1. Mess up id mapping (mess up /etc/sub?id
 2. Run a existing container with now bad uid mapping
 3. Fix uid mapping
 4. Run it again.

**Comment by pcdummy** [comment]
I'm only able to reproduce this with debian jessie containers.

**Comment by stgraber** [comment]
Can you post an actual "lxc info" output?

**Comment by pcdummy** [comment]
Ofc, sorry. In the meanwhile i updated LXD/LXC to 2.7:

```
root@srv01:~# lxc info
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
  - 10.167.160.14:8443
  - '[fd57:c87d:f1ee:ee00:f::14]:8443'
  - '[hidden]:8443'
  - 10.0.3.1:8443
  - 192.168.122.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  certificatefingerprint: 1ec2bcdfa5288bbc7d2a857a42278bc8392e2e16b2d481b3f104131ceb33d5c7
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-57-generic
  server: lxd
  serverpid: 1410
  serverversion: "2.7"
  storage: btrfs
  storageversion: "4.4"
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
public: false
```
