### ISSUE TITLE
Multiple tun interfaces in the same container

### ISSUE THREAD

**Issue by cryptofuture** [lxc/lxd#2766]
Currently I'm not able to create multiple tun interfaces inside in the same container.  Only single random tun interface/openvpn connection starts (mostly its tun0, but sometimes tun1)
```
audit: type=1400 audit(1483118350.924:513): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxd-metrics_</var/lib/lxd>" name="/bin/" pid=9119 comm="(openvpn)" flags="ro, remount, bind"
```
I tried to add extra exception, in `/etc/apparmor.d/local/usr.bin.lxc-start` and in `/etc/apparmor.d/abstractions/lxc/container-base`:
```
mount options=(rw,bind, remount) /dev/net/tun, 
```
Not sure thats only apparmor issue. 
config show:
```
name: metrics
profiles:
- default
config:
  boot.autostart: "1"
  boot.autostart.priority: "11"
  volatile.base_image: id
  volatile.eth0.hwaddr: mac
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  root:
    path: /
    type: disk
  tun:
    path: /dev/net/tun
    type: unix-char
ephemeral: false
```
lxc info:
```
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIGGTCCBAOgAwIBAgIRAJbkrahym2RGMQ6T1LxohrQwCwYJKoZIhvcNAQELMB4x
    HDAaBgNVBAoTE2xpbnV4Y29udGFpbmVycy5vcmcwHhcNMTUwNjAxMDYwMTEwWhcN
    MjUwNTI5MDYwMTEwWjAeMRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMIIC
    IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArKpcYXqK8BrgfKLMgi/+2fjD
    FYAc9gnPrLvEJxS+UIDb+DTBT4U6+/BlIvhxmzIrVm2CupoaWKACYyzU8lAmkMqN
    6/uUES7Vh72zaMieJkmq6RSl2WpEB4U/ej7NvjT06rH/+jJzfGsjs/RScBrsjWIZ
    NlixrBH0rx+mLWS7Ycw0dax5gcBOi8kDJYt6sog2CVPsqHSTvk+AMvnfxBl/qVCV
    KPhdEqVC87hfA0tJeXVtN9x61YW3blaGxZD0tHW1L4C0FTaZKQHfKvo/bZJ+vAQ8
    utRMym1Pv02IIodhKMVlgwfpprfujZIq+LRAYrnXFw6LWz/gFttTV/eJuVjkZYLM
    QjJF6RnL+LdCdknX1ANHQc0J9knSwuqmpdjsH4+g93JT23ZvYZ80zjTbF+Hg9pQp
    TCV0QmqOvGWzli40YG1ZC6XOYLWK4/YjaSPo+g7m1H1vsDFW/Zppupgg0ajiwfjO
    EqO4TpPmyZqf8VzVRryqEVOjGnTQZmyL7+jffMpR2kloO53QnHvukQGF0z61QTKW
    qGrdp0t/m0yN7tcAJRxN4f6mD8XGBarN3hFwqhdPm2o8D6Xy9YVeCdSMmtU4fLTu
    MihQmuVGeix8sNZHbaLfokJJhpp3i+xFLNhxUe4yYnTQ66aj+a4NLuiZQanVOBon
    dBHCjEfG2XPAL2nn7g8CAwEAAaOCAVQwggFQMA4GA1UdDwEB/wQEAwIAoDATBgNV
    HSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMIIBGQYDVR0RBIIBEDCCAQyC
    BWRsaW5rghAxOTIuMTY4LjEuMjI4LzI0ghdmZDI5Ojk5MjY6YzBiNjo6MjEyLzEy
    OIIlZmQyOTo5OTI2OmMwYjY6MDo3NTBiOjU4NGQ6OWYwOjhjZS82NIInZmQyOTo5
    OTI2OmMwYjY6MDozMjBlOmQ1ZmY6ZmUxMjozOTEwLzY0giQyMDAxOjQ3MDoyODo5
    NGE6NzUwYjo1ODRkOjlmMDo4Y2UvNjSCJjIwMDE6NDcwOjI4Ojk0YTozMjBlOmQ1
    ZmY6ZmUxMjozOTEwLzY0ghxmZTgwOjozMjBlOmQ1ZmY6ZmUxMjozOTEwLzY0gg8x
    OTIuMTY4LjU2LjEvMjSCCzEwLjguMC42LzMyMAsGCSqGSIb3DQEBCwOCAgEAc9j6
    MB1U98ruJqeFDW7qSZVRLpHN4RHlAWHioo6r5tWJHHcKnYWLe/NPBvd5frS0aQgr
    EFLXFEUVhBr/ZcMVsFtV/aQww5SrkoAzxyCT4+BU9I7VDW0O1xwHIfAoX/EFh9j6
    VUAqoeLfd4jafWEcWBFJqlQzfYT2F+2D9a9OAOxs5mU4Umk4a8DmLX7jG5KZBmCY
    PJNeN6oEhvpdzv5JTVv2xRyDURllXT4WwbBOKRkS0gOsUiZd6DSdTEOqrU+QBSTH
    gnxzrlGOJVNGhO7V3pFy36aLt381k6afebqS5usnMNSjeEgB2zFfVsLiXY/zwjju
    iaY0+O5CPksKcrh2Kl5O4VBDFJn0FzJu7dk/LM2UE2A8H6How/rPxzskddYL6FSv
    srkpVDhZ+dCag6fCvpEitCt1Q/IZ8LK4Tp/m7KTC1xlNIqpkCxxaaV6fDHmXpMU4
    vgz802bFNJx9LcFIhk5qKh55FVvrkihjoqyM7u5N2f32+7zFgkTl6i3VMi7UKKPV
    aScTwZD+T5ZONcPSecQ0mDa77eq4m1cWkZsGcmoK3MJwdWm43sWA87A15SyJb8/I
    Ych+ieV3AUGH/WMQQzXVVfhSkIZReVDa+cAdWoQ52XoyZ7Ut7iKaJA6PkNjY0x7M
    s2w7jPgv3q2jJReBDbMajbSwP7SxEvBBctCGHCU=
    -----END CERTIFICATE-----
  certificatefingerprint: d1f6f03fa58795d62a7141005e95d3b76af87e2e0c4ef07f45e018b24a0105e7
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-58-generic
  server: lxd
  serverpid: 3362
  serverversion: "2.7"
  storage: zfs
  storageversion: "5"
config:
  core.trust_password: true
  storage.zfs_pool_name: lxd
public: false
```
Nothing handy in lxd.log and container logs.
