### ISSUE TITLE
dnsmasq does not return the ip address, if the container is stopped.

### ISSUE THREAD

**Issue by jkroepke** [lxc/lxd#2775]
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-57-generic
   * LXC version: 2.0.6-0ubuntu5~ubuntu16.04.1~ppa1
   * LXD version: 2.7-0ubuntu2~ubuntu16.04.1~ppa1
   * Storage backend in use: btrfs

# Issue description

dig container is empty for stopped containers

# Steps to reproduce

 1. Create a container
 2. Start and stop container

# Expected:

 dnsmasq should return the ip address for stopped containers.

# Infos

 ```
# lxc network show br1
name: br1
config:
  dns.domain: example.com
  ipv4.address: 10.0.10.2/24
  ipv4.dhcp: "true"
  ipv4.dhcp.ranges: 10.0.10.30-10.0.10.99
  ipv4.firewall: "false"
  ipv4.nat: "false"
  ipv4.routing: "true"
  ipv6.address: .../64
  ipv6.dhcp: "true"
  ipv6.dhcp.stateful: "true"
  ipv6.firewall: "false"
  ipv6.nat: "false"
  ipv6.routing: "true"
  raw.dnsmasq: |
    expand-hosts
    bogus-priv
    stop-dns-rebind
    rebind-localhost-ok
    domain-needed
    local-service
managed: true
type: bridge
```
