### ISSUE TITLE
Make sure that dnsmasq leases are cleaned on delete

### ISSUE THREAD

**Issue by karolpiatek** [lxc/lxd#2781]
**Issue description**

Assigning the same IP from custom defined network does not work.
The container gets random IP next time it is created,
despite the setup:

```
lxc network attach ${network_name} ${vm_name} eth0
lxc config device set ${vm_name} eth0 ipv4.address 10.212.213.2
```

**Steps to reproduce the fault.**

Execute create_network.sh
Execute create_vm.sh

Check if the IP 10.212.213.2 is assigned to container

Execute delete_vm.sh
Execute create_vm.sh

Check if the IP 10.212.213.2 is assigned to container
( in my case the IP is assigned now randomly, e.g. 10.212.213.175 )

Scripts attached in one file
[lxd_static_ip_scripts.txt](https://github.com/lxc/lxd/files/698463/lxd_static_ip_scripts.txt)

**Expected:**
IP 10.212.213.2 is assigned to container

lxc info output

```
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificatefingerprint: b80568b780059d6be06cb0c454488ccba295d5c0c8c3db14514ae123e120e2e5
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.8.0-34-generic
  server: lxd
  serverpid: 1550
  serverversion: 2.4.1
  storage: dir
  storageversion: ""
config: {}
public: false
```

LXD version: 2.4.1
