### ISSUE TITLE
lxd forkstart ... failed to get real path for ...

### ISSUE THREAD

**Issue by cpaelzer** [lxc/lxd#2814]
# Required information
 * Distribution: Ubuntu
 * Distribution version: Xenial
 * The output of "lxc info" or if that fails:
 * lxc info
```
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - ppc64le
  certificate: |
  [...]
  certificatefingerprint: 7a49e772f33c732a951b3df6f42921183006aca680df02fb995dd8f68390c4a0
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: ppc64le
  kernelversion: 4.4.0-57-generic
  server: lxd
  serverpid: 95372
  serverversion: "2.7"
  storage: zfs
  storageversion: "5"
config:
  storage.zfs_pool_name: lxd
public: false
```

# Issue description
Hi,
I ran into a situation being unable to start any more lxd containers. It only seems to happen on the systems that I have using zfs as backing for the containers. I don't think it is related, but so far only occurring on my ppc64el boxes (just happen to be the zfs ones atm).
It seems to work once (starting a bunch of containers and working with them), but after I removed them and re-create them from scratch I ran into:

Here a lxc info after the failed launch:
```
$ lxc info --show-log local:testkvm-xenial-from
Name: testkvm-xenial-from
Remote: unix:/var/lib/lxd/unix.socket
Architecture: ppc64le
Created: 2017/01/24 07:43 UTC
Status: Stopped
Type: persistent
Profiles: kvm
```

Log:
```
            lxc 20170124074307.470 ERROR    lxc_conf - conf.c:mount_rootfs:807 - No such file or directory - failed to get real path for '/var/lib/lxd/containers/testkvm-xenial-from/rootfs'
            lxc 20170124074307.471 ERROR    lxc_conf - conf.c:setup_rootfs:1221 - failed to mount rootfs
            lxc 20170124074307.471 ERROR    lxc_conf - conf.c:do_rootfs_setup:3671 - failed to setup rootfs for 'testkvm-xenial-from'
            lxc 20170124074307.471 ERROR    lxc_conf - conf.c:lxc_setup:3753 - Error setting up rootfs mount after spawn
            lxc 20170124074307.471 ERROR    lxc_start - start.c:do_start:826 - Failed to setup container "testkvm-xenial-from".
            lxc 20170124074307.471 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
            lxc 20170124074307.526 ERROR    lxc_start - start.c:__lxc_start:1338 - Failed to spawn container "testkvm-xenial-from".
            lxc 20170124074308.080 ERROR    lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
            lxc 20170124074308.080 ERROR    lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "testkvm-xenial-from".
            lxc 20170124074308.080 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20170124074308.080 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
```

Ok, I thought it could be my KVM profile, so I tried without
```
$ lxc launch ubuntu-daily:xenial/ppc64el testkvm-xenial-test2
Creating testkvm-xenial-test2
error: No such file or directory: "/var/lib/lxd/containers/testkvm-xenial-test2.zfs/rootfs"
```

Well that is a different error, but still not working.

Yet FYI here the current KVM profile:
```
$ lxc profile show kvm
name: kvm
config:
  boot.autostart: "true"
  linux.kernel_modules: openvswitch,nbd,ip_tables,ip6_tables,kvm
  security.nesting: "true"
  security.privileged: "true"
description: ""
devices:
  eth0:
    mtu: "9000"
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  kvm:
    path: /dev/kvm
    type: unix-char
  mem:
    path: /dev/mem
    type: unix-char
  root:
    path: /
    type: disk
  sharedimg:
    path: /var/lib/uvtool/libvirt
    source: /tmp/testimages
    type: disk
  tun:
    path: /dev/net/tun
    type: unix-char
usedby:
- /1.0/containers/testkvm-xenial-from
- /1.0/containers/testkvm-xenial-test1
```

# Steps to reproduce
I'm guessing here :-/
 1. set up lxd with zfs
 2. launch and delete containers in a loop until launch fails (maybe on ppc64el maybe with the kvm profile I have)

# Information to attach
 - main daemon log: http://pastebin.com/CsWDYH8N
 - output of the client with --debug (default profile):  http://pastebin.com/FNEmappK
 - output of the client with --debug (kvm profile): http://pastebin.com/U0fLP0TJ

Related bugs / discussions I've found:
- https://github.com/lxc/lxd/issues/2121
- http://askubuntu.com/questions/774097/lxd-managed-containers-on-zfs-vanish-after-deleting-a-different-one
