### ISSUE TITLE
storage_lvm: created LV fadesout during "lvc init"

### ISSUE THREAD

**Issue by Laguna-x** [lxc/lxd#2829]
//start service
//copying image remote:debian/jessie to local --alias=debian_j-amd64
 lxc init debian_j-amd64 debNetMgmt

> Creating debNetMgmt
> error: Error mounting snapshot LV: no such file or directory

# lvm version
  LVM version:     2.02.111(2) (2014-09-01)
  Library version: 1.02.90 (2014-09-01)
  Driver version:  4.27.0
# uname -a
Linux mSys 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

# /var/log/lxd/lxd.log
```
lvl=info msg="LXD 2.8 is starting in normal mode" path=/var/lib/lxd t=2017-01-28T06:32:21+0300
...
lvl=info msg="Done updating images" t=2017-01-30T00:07:04+0300
ephemeral=false lvl=info msg="Creating container" name=debNetMgmt t=2017-01-30T00:07:18+0300
ephemeral=false lvl=info msg="Created container" name=debNetMgmt t=2017-01-30T00:07:18+0300
created=2017-01-29T21:07:18+0000 ephemeral=false lvl=info msg="Deleting container" name=debNetMgmt t=2017-01-30T00:07:18+0300 used=1970-01-01T00:00:00+0000
created=2017-01-29T21:07:18+0000 ephemeral=false lvl=info msg="Deleted container" name=debNetMgmt t=2017-01-30T00:07:19+0300 used=1970-01-01T00:00:00+0000
```
# lxc config show
```
config:
  core.https_address: '[::]:8443'
  core.https_allowed_headers: Content-Type
  core.https_allowed_methods: GET, POST, PUT, DELETE, OPTIONS
  core.https_allowed_origin: '*'
  core.trust_password: true
  images.auto_update_cached: "false"
  images.auto_update_interval: "24"
  images.remote_cache_expiry: "5"
  storage.lvm_vg_name: Data
```

Next i'm trying to edit ...go/src/github.com/lxc/lxd/lxd/storage_lvm.go to catch the problem. So:
find function 
> func (s *storageLvm) ContainerCreateFromImage(

next wright something like <<return fmt.Errorf("!EBUGGING:")>> after "destPath := container.Path()"
then
```
# lxc init debian_j-amd64 debNetMgmt
Creating debNetMgmt
error: !EBUGGING:
# lvs |grep deb
  debNetMgmt                                                       Data   Vwi---tz-k  10,00g LXDPool 40e7...
```

!BUT! if <<return fmt.Errorf("!EBUGGING:")>> move after
 ```
       if err := os.MkdirAll(destPath, 0755); err != nil {
                return fmt.Errorf("Error creating container directory: %v", err)
        }
```
then << lvs |grep deb>> return nothing, so there is new LV disapperes after "os.MkdirAll(destPath, 0755)" (or what?)

PS. trying to create dir by hands - thats ok
```
# lvs |grep deb
  debNetMgmt                                                       Data   Vwi---tz-k  10,00g LXDPool 40e7...   
# lxc list
+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+
# mkdir /var/lib/lxd/containers/debNetMgmt
# lvs |grep deb
  debNetMgmt                                                       Data   Vwi---tz-k  10,00g LXDPool 40e...   

```
