### ISSUE TITLE
Allow all lxd init questions to be pre-seeded

### ISSUE THREAD

**Issue by ajd394** [lxc/lxd#2834]
while the interactive version of lxd init allows you to create a lxd bridge, the non-interactive, using --auto, does not accept the arguments to perform the creation of the lxd bridge.

**Comment by davidfavor** [comment]
Was looking for the ticket where Stephan answered this for me. Can't find the ticket.

My notes show...
```
lxd init --auto --storage-backend dir 
lxc network create lxdbr0
lxc network attach-profile lxdbr0 default eth0
```

**Comment by stgraber** [comment]
Right, you can indeed do it through "lxc network".

In general, I'd like to rework "lxd init" to allow for a .yaml preseed file to be passed as constantly adding new command line options makes parsing it and testing it much harder than it should.

I expect we'll keep the current ones as they are for backward compatibility but will add a way to pass a .yaml with everything else in the near future.

**Comment by ajd394** [comment]
@stgraber Sounds great!

**Comment by stgraber** [comment]
So just dumping some notes in here since we've been pointing to this quite a bit lately.
The expectation as far as pre-seeding so far is:
 - Have "lxd init" read a yaml document from stdin when --auto is passed.
 - Keep the other command line arguments around but print a deprecation warning to stderr, pointing to the yaml pre-seeding format as preferred.
 - Document LXD daemon configuration preseeding in doc/
 - Allow pre-seeding of:
   - Daemon configuration
   - Storage pools
   - Networks
   - Profiles
   - Initial image set
 - Re-work the interactive mode to match those new options, possibly moving some of the more advanced options behind a --advanced flag.

**Comment by brauner** [comment]
@stgraber, I've assigned @freeekanayaka to this for now so that he can take a stab at it. What we need to discuss is the format of the `yaml` file. My idea was basically to support the various post api struct in `shared/api/*` that are supported by `lxd init` already. So for `storage` and networks the section of the yaml file could look like:
```
pool:
- config:
    size: 57GB
    source: /var/lib/lxd/disks/default.img
    zfs.pool_name: default
  name: default
  driver: zfs
  used_by: []
- config:
    lvm.thinpool_name: LXDThinpool
    lvm.vg_name: lvmpool
    size: 57GB
    source: /var/lib/lxd/disks/lvmpool.img
  name: lvmpool
  driver: lvm
- config:
    size: 57GB
    source: /var/lib/lxd/disks/pool1.img
  name: pool1
  driver: btrfs
network:
- config:
    ipv4.address: 10.48.159.1/24
    ipv4.nat: "true"
    ipv6.address: fd42:f3fc:def8:af88::1/64
    ipv6.nat: "true"
  name: lxdbr0
  type: bridge
- config:
    ipv4.address: 10.44.93.1/24
    ipv4.nat: "true"
    ipv6.address: fd42:347f:b637:1ddc::1/64
    ipv6.nat: "true"
  name: lxdbr1
```

**Comment by brauner** [comment]
And I wouldn't necessarily deprecate the old `lxd init --auto` options since some users might just want a quick and dirty way of setting up `lxd`. We certainly don't need to add more options to it and leave any advanced configuration via the yaml file. It will likely be most useful in automatic deployment environments anyway.

**Comment by stgraber** [comment]
Right, we can't deprecate the existing arguments just yet, we'll add the yaml preseeding as a new option. Won't be adding new stuff to the command line arguments and we can drop them when we release LXD 3.0.

As for the layout you proposed, that seems fine to me, though I'd argue for plural form for the top levels ("networks" instead of "network").

I suspect we'll also want to add some helpers later, for example letting you easily specific a default network and storage pool without having to list a "default" profile in there, which would then conflict with your existing default profile.

We also probably should check whether any of the listed stuff already exists and bail before applying any of those changes. We can then provide some way to explicitly request an update of the existing config (when possible).

**Comment by freeekanayaka** [comment]
@stgraber just to be clear, do you mean that if ANY of the value passed via the stdin yaml text is already present in the database (or whatever persistence storage is used to a particular setting), then "lxd init" should return 1?

I was thinking to start with all daemon-level config values already supported by the --auto cmd line and proceed gradually to more advanced things like pools and networks. So the initial yaml snippet I would implement support for could look like:

```
daemon:
- config:
    core.https_address: 127.0.0.1:9999
    core.trust_password: sekret

# pools:
# - config:
#     <THIS WILL COME LATER>
```

This would be equivalent to:

```bash
lxd init --auto --network-address 127.0.0.1 --network-port 9999 --trust-password sekret
```

Does it sound reasonable?
