### ISSUE TITLE
Cannot add network of show a network. lxc network show returns "error: cannot open 'lxd': dataset does not exist"

### ISSUE THREAD

**Issue by arthurlogilab** [lxc/lxd#2852]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.10
 * The output of "lxc info" or if that fails:

```
# lxc info
config:
  storage.zfs_pool_name: lxd
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
apistatus: stable
apiversion: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
[snip]
    -----END CERTIFICATE-----
  certificatefingerprint: [snip]
  driver: lxc
  driverversion: 2.0.7
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.8.0-34-generic
  server: lxd
  serverpid: 8828
  serverversion: "2.8"
  storage: dir
  storageversion: ""
```

# Issue description

Cannot add network of show a network. 

# Steps to reproduce

```
root@ursa:/var/lib/lxd# lxc network list
+------+------+---------+---------+
| NAME | TYPE | MANAGED | USED BY |
+------+------+---------+---------+
root@ursa:/var/lib/lxd# lxc network create internal0
Network internal0 created
root@ursa:/var/lib/lxd# lxc network list
+------+------+---------+---------+
| NAME | TYPE | MANAGED | USED BY |
+------+------+---------+---------+
root@ursa:/var/lib/lxd# lxc network show internal0
error: cannot open 'lxd': dataset does not exist
root@ursa:/var/lib/lxd# lxc network create testbr0
lxc Network testbr0 created
root@ursa:/var/lib/lxd# lxc network list
+------+------+---------+---------+
| NAME | TYPE | MANAGED | USED BY |
+------+------+---------+---------+
root@ursa:/var/lib/lxd# dpkg -l lxd
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                           Version              Architecture         Description
+++-==============================-====================-====================-=================================================================
ii  lxd                            2.8-0ubuntu1~ubuntu1 amd64                Container hypervisor based on LXC - daemon
root@ursa:/var/lib/lxd# lxc network show testbr0
error: cannot open 'lxd': dataset does not exist


```
