### ISSUE TITLE
run command at startup container

### ISSUE THREAD

**Issue by Laguna-x** [lxc/lxd#2880]
Using LXD with OpenvSwitch.
In my setup i have internal ports on OpenvSwitch. 
Testdesc has one bridge with one manualy added internal port for LXD container.
whyle creating containers i'm doing something like:
`lxc network attach my-container default ovsbr01`
but ovs with lxd have some bug with this:
ovs internal port (made by add-br and then config set interface type=internal) mast be turned up by
"ip link set dev ovsbr01 up". If i do it before container starts - then it have no effect on container interface (networking do not working (no effects on dhcp, ping, etc..., but interfaces shows normal states)).  So this command (ip link ... up) mast be run after container startup. 
Is there any way to run commands outside container with container startup (need startup on boot)?
Another one bug with this:
when i run "ip  ... ovsbr01 up" (in both cases: before and after container starts), then "ip link" says:

> ovsbr01: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1

I think that lxc do not links with ovs port fully somehow (state is UNCKNOWN), and this may be cause to not start automaticaly link with lxc-interface and ovs-port (as i wrote above)

sorry for bad english

**Comment by stgraber** [comment]
What does "lxc config show --expanded name-of-the-container" shows?

**Comment by Laguna-x** [comment]
```
# lxc config show --expanded cert
architecture: x86_64
config:
  boot.autostart: "1"
  image.architecture: amd64
  image.description: Debian jessie amd64 (20170209_22:42)
  image.os: Debian
  image.release: jessie
  image.serial: "20170209_22:42"
  volatile.base_image: a3ad03a84e055c4c8c259c32b1e19374c3ee5b76733b322dffcda1f5761a4d10
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: STOPPED
  volatile.root.hwaddr: 00:16:3e:0b:08:e7
  volatile.root.name: eth1
  volatile.tmp0.hwaddr: 00:16:3e:6f:56:ed
  volatile.tmp0.name: eth0
devices:
  root:
    path: /
    type: disk
  tmp0:
    nictype: macvlan
    parent: tmp0
    type: nic
ephemeral: false
profiles:
- default

```

**Comment by Laguna-x** [comment]
stored nicktype: physical:
```
# service networking restart
# ip link | grep tmp0
197: tmp0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
# lxc start cert
# lxc list
+------+---------+------+------+------------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+------+------+------------+-----------+
| cert | RUNNING |      |      | PERSISTENT | 0         |
+------+---------+------+------+------------+-----------+
# ip link | grep tmp0
215: tmp0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1
# ip link set dev tmp0 up
# ip link | grep tmp0
215: tmp0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
# lxc list
+------+---------+------+------+------------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+------+------+------------+-----------+
| cert | RUNNING |      |      | PERSISTENT | 0         |
+------+---------+------+------+------------+-----------+

```

**Comment by Laguna-x** [comment]
another bug catched, whn in thi situation i store nicktypa: bridge - then lxc shows error and it do not unmount it's volume.
```
# lxc start cert
error: Error calling 'lxd forkstart cert /var/lib/lxd/containers /var/log/lxd/cert/lxc.conf': err='exit status 1'
  lxc 20160214225341.959 ERROR lxc_conf - conf.c:instantiate_veth:2669 - failed to attach 'vethFFPT8M' to the bridge 'tmp0': Operation not permitted
  lxc 20160214225341.985 ERROR lxc_conf - conf.c:lxc_create_network:2962 - failed to create netdev
  lxc 20160214225341.985 ERROR lxc_start - start.c:lxc_spawn:1088 - Failed to create the network.
  lxc 20160214225341.985 ERROR lxc_start - start.c:__lxc_start:1346 - Failed to spawn container "cert".
  lxc 20160214225342.511 ERROR lxc_conf - conf.c:run_buffer:405 - Script exited with status 1.
  lxc 20160214225342.511 ERROR lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "cert".

Try `lxc info --show-log cert` for more info
# lxc config edit cert (return nicktype to macvlan)
lxc start cert
error: Error mounting snapshot LV path='/var/lib/lxd/containers/cert': device or resource busy
Try `lxc info --show-log cert` for more info
# lxc stop cert
error: The container is already stopped
Try `lxc info --show-log cert` for more info
# lxc start cert
error: Error mounting snapshot LV path='/var/lib/lxd/containers/cert': device or resource busy
Try `lxc info --show-log cert` for more info
# umount /var/lib/lxd/containers/cert
# lxc start cert
# lxc list
+------+---------+------+------+------------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+------+------+------------+-----------+
| cert | RUNNING |      |      | PERSISTENT | 0         |
+------+---------+------+------+------------+-----------+

```

**Comment by Laguna-x** [comment]
```
# lxc info
config:
  core.https_address: XX.XX.XX.XX
  core.trust_password: true
  storage.lvm_vg_name: Data
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
apistatus: stable
apiversion: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - XX.XX.XX.XX:YYYY
  architectures:
  - x86_64
  - i686
  certificate: |
....
  certificatefingerprint: ...
  driver: lxc
  driverversion: 2.0.7
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-62-generic
  server: lxd
  serverpid: 6298
  serverversion: "2.8"
  storage: lvm
  storageversion: 2.02.133(2) (2015-10-30) / 1.02.110 (2015-10-30) / 4.34.0

```
