### ISSUE TITLE
When scanning for uid/gid maps, discard if not mapped in the user namespace

### ISSUE THREAD

**Issue by jameinel** [lxc/lxd#2885]
# Required information

 * Distribution: xenial
 * The output of "lxc info" or if that fails:
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-62-generic
  server: lxd
  serverpid: 3426
  serverversion: "2.8"
  storage: zfs
  storageversion: "5"

(lxc info has gotten awfully long, but I can include it if you want)

# Issue description

A brief description of what failed or what could be improved.

# Steps to reproduce

I'm currently running Xenial with the backported 2.8 LXD. If I try to do nested containers with Juju (juju bootstrap lxd; juju add-machine --to lxd:0) it is failing with:
```  
        machine-status:
          current: provisioning error
          message: 'Failed to change ownership of: /var/lib/lxd/containers/juju-ab3dc6-0-lxd-0/rootfs'
          since: 15 Feb 2017 10:13:21+04:00
```

If I set "security.privileged: true" in the profile, then I'm able to create a nested container. I thought "security.nested" was intended to be all you really needed to do.

When I track through the lxd code the line appears to be from:
  shared/util_linux.go ShiftOwner()
which only seems to be called from:
  shared/idmapset_linux.go doUidshiftIntoContainer

A simpler way to trigger this seems to be:
```
$ lxc launch ubuntu:x --config security.nesting=true nest-test
$ lxc exec nest-test bash
$$ lxc launch ubuntu:x inside-test
Generating a client certificate. This may take a minute...
If this is your first time using LXD, you should also run: sudo lxd init
To start your first container, try: lxc launch ubuntu:16.04

Creating inside-test
Retrieving image: 100%error: Failed to change ownership of: /var/lib/lxd/containers/inside-test/rootfs
```

Note that if I set "security.privileged=true" along with "security.nested=true" then it *does* work to launch a nested container.
