### ISSUE TITLE
Make sure LVM VG/LV are active

### ISSUE THREAD

**Issue by Laguna-x** [lxc/lxd#2889]
Ubuntu 16.04
```
# uname -ra
Linux mSys 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
 * The output of "lxc info" or if that fails:
```
# lxc info
config:
  core.https_address: XX.XX.XX.XX
  core.trust_password: true
  storage.lvm_vg_name: Data
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
apistatus: stable
apiversion: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - xx.xx.xx.xx:yyyy
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  certificatefingerprint: ...
  driver: lxc
  driverversion: 2.0.7
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-62-generic
  server: lxd
  serverpid: 6185
  serverversion: "2.8"
  storage: lvm
  storageversion: 2.02.133(2) (2015-10-30) / 1.02.110 (2015-10-30) / 4.34.0
```
 # Issue description
When power loss (physicaly from server) then container makes unavailable.

# Steps to reproduce
```
# lxc launch debian/jessie powerloss
# lxc list
+-----------+---------+------+------+------------+-----------+
|   NAME    |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+-----------+---------+------+------+------------+-----------+
| cert      | STOPPED |      |      | PERSISTENT | 0         |
+-----------+---------+------+------+------------+-----------+
| powerloss | RUNNING |      |      | PERSISTENT | 0         |
+-----------+---------+------+------+------------+-----------+
# power off manualy from electrical cord
login as: 
$ sudo -i
# lxc list
+-----------+---------+------+------+------------+-----------+
|   NAME    |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+-----------+---------+------+------+------------+-----------+
| cert      | STOPPED |      |      | PERSISTENT | 0         |
+-----------+---------+------+------+------------+-----------+
| powerloss | STOPPED |      |      | PERSISTENT | 0         |
+-----------+---------+------+------+------------+-----------+
# lxc start powerloss
error: Error mounting snapshot LV path='/var/lib/lxd/containers/powerloss': no such file or directory
# mount | grep powerloss
#
# lxc config show powerloss
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Debian jessie amd64 (20170209_22:42)
  image.os: Debian
  image.release: jessie
  image.serial: "20170209_22:42"
  volatile.base_image: a3ad03a84e055c4c8c259c32b1e19374c3ee5b76733b322dffcda1f5761a4d10
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  root:
    path: /
    type: disk
ephemeral: false
profiles:
- default
# lvs | grep a3ad03a84e055c4c8c259c32b1e19374c3ee5b76733b322dffcda1f5761a4d10
  a3ad03a84e055c4c8c259c32b1e19374c3ee5b76733b322dffcda1f5761a4d10 Data   Vwi---tz--  10.00g LXDPool                                                                    
  cert                                                             Data   Vwi---tz--  10.00g LXDPool a3ad03a84e055c4c8c259c32b1e19374c3ee5b76733b322dffcda1f5761a4d10   
  powerloss                                                        Data   Vwi---tz--  10.00g LXDPool a3ad03a84e055c4c8c259c32b1e19374c3ee5b76733b322dffcda1f5761a4d10   

```
"cert" was first container with this issue. as we see: lvm creates same origin in pool for powerloss as it was with cert (a3ad03a84e055c4c8c259c32b1e19374c3ee5b76733b322dffcda1f5761a4d10).
is it issue with LVM pool, or LXD?
