### ISSUE TITLE
Containers started as boot sometimes don't have shared mounts available

### ISSUE THREAD

**Issue by iainlane** [lxc/lxd#2895]
Ubuntu zesty, lxd 2.8(-0ubuntu1)

I have this .mount unit

```
# /etc/systemd/system/srv-mirrors.mount
[Unit]
Description=mirrors
ConditionPathExists=/dev/disk/by-uuid/9266db28-4a38-4ddb-9ee4-f4daed170e8f
Before=local-fs.target

[Mount]
What=/dev/disk/by-uuid/9266db28-4a38-4ddb-9ee4-f4daed170e8f
Where=/srv/mirrors/
Type=ext4

[Install]
WantedBy=local-fs.target
```

Which seems to work fine on the host - in particular, I /think/ that the WantedBy and Before are right.

My container has, in its config-

```
devices:
  /srv/mirrors:
    path: /srv/mirrors
    source: /srv/mirrors
    type: disk
```

The problem I see is that sometimes `/srv/mirrors` is an empty directory in the container even though by the time I look it's mounted on the host.

Is lxd racing with systemd getting the thing mounted? In that case, `After=local-fs.target` (and maybe `remote-fs.target`?) might help?

Let me know if you want any more information, like stuff from the journal, or if I should try that ^- suggestion.

**Comment by stgraber** [comment]
I thought that all normal systemd units were supposed to get an implicit after local-fs.target?

**Comment by iainlane** [comment]
I didn't know that. `systemd.special(7)` sort of implies that `basic.target` gives you this for local mounts. I don't see that when doing `systemctl cat basic.target`, but maybe it's transitive or something.

If that's right, then my suggestion doesn't help. I can dig around in the journal to find out what order things happened in.

**Comment by stgraber** [comment]
I may perfectly be wrong, would certainly be worth checking exactly what systemd adds for us.

**Comment by iainlane** [comment]
I got it today, so let's have a look in the journal (unrelated mounts removed)...

```
Feb 21 11:14:21 raleigh.local systemd[1]: Mounting mirrors...
Feb 21 11:14:21 raleigh.local kernel: EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
Feb 21 11:14:21 raleigh.local systemd[1]: Mounted mirrors.
Feb 21 11:14:21 raleigh.local systemd[1]: Reached target Local File Systems.
Feb 21 11:14:25 raleigh.local systemd[1]: Starting LXD - unix socket.
Feb 21 11:14:25 raleigh.local systemd[1]: Listening on LXD - unix socket.
Feb 21 11:14:25 raleigh.local systemd[1]: Starting LXD - container startup/shutdown...
Feb 21 11:14:31 raleigh.local systemd[1]: Starting LXD - main daemon...
Feb 21 11:14:35 raleigh.local systemd[1]: Started LXD - container startup/shutdown.
Feb 21 11:14:36 raleigh.local systemd[1]: Started LXD - main daemon.
```

Hmm, so it's mounting before LXD starts, so that's good. The other ordering looks right too, per the unit files (I'm assuming that `lxd.service` is socket activated by `lxd activateifneeded` from `lxd-containers.service`).

**Comment by stgraber** [comment]
yeah, that looks right and suggests the path was mounted by systemd a whole 4 seconds before LXD was spawned, so I have no idea why the path wouldn't actually be visible on the host at that point...

**Comment by iainlane** [comment]
I just had this again, and this time rebooting the container (from within it - `sudo reboot') did *not* fix the issue the first couple of times. On the third reboot it did. Maybe that indicates a race within lxd that's more likely to happen on boot but still can happen at any time? Or maybe using `lxc restart' would have been better.

I don't see much in the journal; can I start lxd in verbose/debugging mode so that if this happens again we can see what went on?

**Comment by stgraber** [comment]
@iainlane yeah, you can edit the LXD unit (with an override ideally) to pass "--debug" to LXD. That will have it log a lot more stuff in lxd.log

**Comment by deadlybore** [comment]
I got the same problem on a gentoo server (with openrc) with lxd 2.11 and Linux 4.9.24
I have 4 shared directories and it's always the same directory that may not appear
I added --debug and --verbose but I see no difference between a reboot where all the shared directories are properly mounted and a reboot that did not

Furthermore, even when the shared directory doesn't show in the container I can see that the mount is properly done in `/var/lib/lxd/devices/$CONTAINER_NAME`

And if I try to remove the shared directory I got this error : 
```
error: The following containers failed to update (profile change still saved):
 - web: Error unmounting the device: Failed to run: /usr/sbin/lxd forkumount 6792 /usr/portage/distfiles: Error unmounting /usr/portage/distfiles: Invalid argument
```

Any suggestions to debug ?

**Comment by stgraber** [comment]
As discussed in person, this doesn't seem to be reproducible right now by @iainlane on current LXD (2.16). The best guess right now is that on the original system, systemd was being a bit trigger happy and unmounting filesystems as has been observed in the past.

**Comment by deadlybore** [comment]
@stgraber did you see my previous message ? I'm running a system without systemd.

**Comment by stgraber** [comment]
@deadlybore I did but you're running outdated LXD so was focusing on the report that was running an up to date version of the daemon.

Can you reproduce your issue with LXD 2.16?

**Comment by deadlybore** [comment]
Indeed, I still have the problem with LXD 2.14 but the 2.16 has not been released yet so I haven't tested with that one

**Comment by stgraber** [comment]
@deadlybore can you post:
 - lxc info
 - lxc config show --expanded CONTAINER-NAME
 - HOST: cat /proc/self/mountinfo
 - CONTAINER: cat /proc/self/mountinfo
 - /var/log/lxd/CONTAINER-NAME/lxc.log
 - /var/log/lxd/CONTAINER-NAME/lxc.conf

You may also want to do:

    lxc config set CONTAINER-NAME raw.lxc=lxc.loglevel=trace

And when the issue next happens, capture and post those files before doing anything to the container:
 - CONTAINER: cat /proc/self/mountinfo
 - /var/log/lxd/CONTAINER-NAME/lxc.log
 - /var/log/lxd/CONTAINER-NAME/lxc.conf

**Comment by deadlybore** [comment]
Hum I think I find something, the order in which the mounting are done is not always the same. And as a result sometimes it overlap

The mountinfo when there is no problem:
```
314 80 8:3 / /usr/portage ro,nodev,noatime,nodiratime - ext4 /dev/sda3 rw,block_validity,delalloc,barrier,user_xattr,acl
315 314 0:37 / /usr/portage/distfiles rw,noatime - zfs tank/distfiles rw,xattr,noacl
316 314 0:49 / /usr/portage/packages rw,noatime - zfs tank/packages rw,xattr,noacl
```

When the problem appears:
```
314 80 0:37 / /usr/portage/distfiles rw,noatime - zfs tank/distfiles rw,xattr,noacl
315 80 8:3 / /usr/portage ro,nodev,noatime,nodiratime - ext4 /dev/sda3 rw,block_validity,delalloc,barrier,user_xattr,acl
316 315 0:49 / /usr/portage/packages rw,noatime - zfs tank/packages rw,xattr,noacl
```

Is there anyway to specify a priority ?

**Comment by stgraber** [comment]
Oh yeah, that would be a problem :)

I thought we had logic to do mount ordering to avoid that problem...

Can you please post the lxc.conf for both cases?

**Comment by deadlybore** [comment]
Yeah sure :)

Without the problem:
```
lxc.cap.drop = sys_time sys_module sys_rawio mac_admin mac_override
lxc.mount.auto = proc:rw sys:rw
lxc.autodev = 1
lxc.pts = 1024
lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file,optional
lxc.mount.entry = /dev/net/tun dev/net/tun none bind,create=file,optional
lxc.mount.entry = /proc/sys/fs/binfmt_misc proc/sys/fs/binfmt_misc none rbind,create=dir,optional
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none rbind,create=dir,optional
lxc.mount.entry = /dev/mqueue dev/mqueue none rbind,create=dir,optional
lxc.include = /usr/share/lxc/config/common.conf.d/
lxc.logfile = /var/log/lxd/modoboa/lxc.log
lxc.loglevel = trace
lxc.arch = linux64
lxc.hook.pre-start = /usr/sbin/lxd callhook /var/lib/lxd 10 start
lxc.hook.post-stop = /usr/sbin/lxd callhook /var/lib/lxd 10 stop
lxc.tty = 0
lxc.utsname = modoboa
lxc.mount.entry = /var/lib/lxd/devlxd dev/lxd none bind,create=dir 0 0
lxc.seccomp = /var/lib/lxd/security/seccomp/modoboa
lxc.id_map = u 0 1000000 65536
lxc.id_map = g 0 1000000 65536
lxc.rootfs.backend = dir
lxc.rootfs = /var/lib/lxd/containers/modoboa/rootfs
lxc.mount.entry = /var/lib/lxd/devices/modoboa/disk.usr-portage usr/portage none bind,ro,create=dir
lxc.mount.entry = /var/lib/lxd/devices/modoboa/disk.usr-portage-distfiles usr/portage/distfiles none bind,create=dir
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = xenbr0
lxc.network.hwaddr = ***
lxc.network.name = eth0
lxc.mount.entry = /var/lib/lxd/devices/modoboa/disk.usr-portage-packages usr/portage/packages none bind,create=dir
lxc.mount.entry = /var/lib/lxd/devices/modoboa/disk.var-tmp-portage var/tmp/portage none bind,create=dir
lxc.mount.entry = /var/lib/lxd/shmounts/modoboa dev/.lxd-mounts none bind,create=dir 0 0
lxc.loglevel=trace
```

With the problem:
```
lxc.cap.drop = sys_time sys_module sys_rawio mac_admin mac_override
lxc.mount.auto = proc:rw sys:rw
lxc.autodev = 1
lxc.pts = 1024
lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file,optional
lxc.mount.entry = /dev/net/tun dev/net/tun none bind,create=file,optional
lxc.mount.entry = /proc/sys/fs/binfmt_misc proc/sys/fs/binfmt_misc none rbind,create=dir,optional
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none rbind,create=dir,optional
lxc.mount.entry = /dev/mqueue dev/mqueue none rbind,create=dir,optional
lxc.include = /usr/share/lxc/config/common.conf.d/
lxc.logfile = /var/log/lxd/modoboa/lxc.log
lxc.loglevel = trace
lxc.arch = linux64
lxc.hook.pre-start = /usr/sbin/lxd callhook /var/lib/lxd 10 start
lxc.hook.post-stop = /usr/sbin/lxd callhook /var/lib/lxd 10 stop
lxc.tty = 0
lxc.utsname = modoboa
lxc.mount.entry = /var/lib/lxd/devlxd dev/lxd none bind,create=dir 0 0
lxc.seccomp = /var/lib/lxd/security/seccomp/modoboa
lxc.id_map = u 0 1000000 65536
lxc.id_map = g 0 1000000 65536
lxc.rootfs.backend = dir
lxc.rootfs = /var/lib/lxd/containers/modoboa/rootfs
lxc.mount.entry = /var/lib/lxd/devices/modoboa/disk.usr-portage-distfiles usr/portage/distfiles none bind,create=dir
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = xenbr0
lxc.network.hwaddr = ***
lxc.network.name = eth0
lxc.mount.entry = /var/lib/lxd/devices/modoboa/disk.usr-portage usr/portage none bind,ro,create=dir
lxc.mount.entry = /var/lib/lxd/devices/modoboa/disk.usr-portage-packages usr/portage/packages none bind,create=dir
lxc.mount.entry = /var/lib/lxd/devices/modoboa/disk.var-tmp-portage var/tmp/portage none bind,create=dir
lxc.mount.entry = /var/lib/lxd/shmounts/modoboa dev/.lxd-mounts none bind,create=dir 0 0
lxc.loglevel=trace
```

**Comment by stgraber** [comment]
Ok, cool, so looks like this is indeed LXD's fault. Either that or liblxc's save_config isn't writing stuff in order, but that seems doubtful.

**Comment by stgraber** [comment]
@deadlybore Can you please post "lxc config show --expanded modoboa"?

I've setup what should be a worst case scenario reproducer for this bug and I'm unable to get the out of order thing to happen here...

**Comment by deadlybore** [comment]
Sorry for the late reply here you go:

```
lxc config show --expanded modoboa
description: ""
architecture: x86_64
config:
  raw.lxc: lxc.loglevel=trace
  volatile.base_image: 1a490d192c0532a7c78c9d8daedf79e6f89919c24a29d565068751e61f21ae6c
  volatile.eth0.hwaddr: ***
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  distfiles:
    path: /usr/portage/distfiles
    source: /tank/distfiles
    type: disk
  eth0:
    nictype: bridged
    parent: xenbr0
    type: nic
  packages:
    path: /usr/portage/packages
    source: /tank/packages
    type: disk
  portage:
    path: /usr/portage
    readonly: "true"
    source: /usr/portage
    type: disk
  portage_tmpfs:
    path: /var/tmp/portage
    source: /var/tmp/lxd
    type: disk
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
```
