### ISSUE TITLE
2.9: Invalid storage volume configuration key: lvm.thinpool_name

### ISSUE THREAD

**Issue by neil-bowers** [lxc/lxd#2909]
# Required information

 * Distribution: `Ubuntu Server`
 * Distribution version: `16.10`
 * The output of "lxc info" or if that fails:
   * Kernel version:`4.8.0-37-generic`
   * LXC version: `2.9.1`
   * LXD version: `2.9.1`
   * Storage backend in use: `LVM`

# Issue description

Editing a storage volume container and then exiting - even if no changes are made - results in the error `...Invalid storage volume configuration key: lvm.thinpool_name`.

# Steps to reproduce

 1. `lxc launch ubuntu_r1610 -p default-msm minecraft`
 2. `lxc storage volume edit lxc-vg container/minecraft` [Note, my default editor is `nano`]
 3. `Ctrl-X` to exit `nano` upon which the message:

    `Config parsing error: Invalid storage volume configuration key: lvm.thinpool_name
    Press enter to open the editor again`

# Devices portion of `default-msm`

```
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: lxc-vg
    type: disk
name: default-msm
```

# Storage volume configuration for `container/minecraft`

```
name: minecraft
config:
  block.filesystem: ext4
  block.mount_options: discard
  lvm.thinpool_name: LXDThinpool
  size: "10737418240"
type: container
used_by: []
```
