### ISSUE TITLE
Can't access loop device: "mount failed: Unknown error -1" or "failed to setup loop device: Operation not permitted"

### ISSUE THREAD

**Issue by juju4** [lxc/lxd#2980]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04 or 16.04
```
apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: xxx
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.13.0-110-generic
  server: lxd
  serverpid: 29354
  serverversion: 2.0.8
  storage: dir
  storageversion: ""
config: {}
public: false
$ lxc config show default-ubuntu-1604-1488070504
name: default-ubuntu-1604-1488070504
profiles:
- default
config:
  security.privileged: "true"
  volatile.base_image: 8f9eca42551b96e4eebf82b608079e8e4b47187ea4644e5b00f86034d512b6e6
  volatile.eth0.hwaddr: 00:16:3e:47:c5:9d
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  root:
    path: /
    type: disk
ephemeral: false
```

# Issue description

can't loop mount an image
I did check this previous case https://github.com/lxc/lxd/issues/1693

# Steps to reproduce

image from https://www.honeynet.org/challenges/2011_7_compromised_server
```
# mknod -m660 /dev/loop0 b 7 0
# ls -la /dev/loop*
brw-rw---- 1 root root 7, 0 Feb 27 22:21 /dev/loop0
# mount -o loop,ro,noexec,noload /cases/sources/victoria-v8.sda1.img /mnt
mount: /mnt: mount failed: Unknown error -1
```

host
```
$ sudo ls -la /var/lib/lxd/containers/default-ubuntu-1604-1488070504/rootfs/dev/ |grep loop
brw-rw----  1 root disk   7,   0 aoû 15  2016 loop0
brw-rw----  1 root disk   7,   1 aoû 15  2016 loop1
brw-rw----  1 root disk   7,   2 aoû 15  2016 loop2
brw-rw----  1 root disk   7,   3 aoû 15  2016 loop3
brw-rw----  1 root disk   7,   4 aoû 15  2016 loop4
brw-rw----  1 root disk   7,   5 aoû 15  2016 loop5
brw-rw----  1 root disk   7,   6 aoû 15  2016 loop6
brw-rw----  1 root disk   7,   7 aoû 15  2016 loop7
```
In a xenial host, message is a bit better
```
root@default-ubuntu-1604-1488301801:~# mknod -m660 /dev/loop8 b 7 8
root@default-ubuntu-1604-1488301801:~# mount -o loop,ro,noexec,noload /cases/sources/victoria-v8.sda1.img /mnt
mount: /cases/sources/victoria-v8.sda1.img: failed to setup loop device: Operation not permitted
```
No message in host syslog/kern.log/auth.log

# Information to attach

Trusty host
```
$ lxc info default-ubuntu-1604-1488070504 --show-log
Name: default-ubuntu-1604-1488070504
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/02/27 19:58 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 12760
Ips:
  eth0: inet    10.21.181.40    vethNITF33
  eth0: inet6   fe80::216:3eff:fe47:c59d        vethNITF33
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 44
  Memory usage:
    Memory (current): 19.82GB
    Memory (peak): 19.98GB
  Network usage:
    eth0:
      Bytes received: 3.91GB
      Bytes sent: 197.38MB
      Packets received: 2870476
      Packets sent: 1533344
    lo:
      Bytes received: 34.02MB
      Bytes sent: 34.02MB
      Packets received: 79469
      Packets sent: 79469

Log:

            lxc 20170227145901.185 WARN     lxc_start - start.c:signal_handler:322 - Invalid pid for SIGCHLD. Received pid 12750, expected pid 12760.
$ cat /var/log/lxd/lxd.log
[...]
t=2017-02-27T15:59:32-0500 lvl=info msg="Executed command" environment="[HOME=/root TERM=screen USER=root PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]" args="[/usr/bin/lxd forkexec default-ubuntu-1404-1486764297 /var/lib/lxd/containers /var/log/lxd/default-ubuntu-1404-1486764297/lxc.conf -- env HOME=/root TERM=screen USER=root PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -- cmd ls /root/.ssh]"
t=2017-02-27T15:59:33-0500 lvl=info msg="Executing command" environment="[USER=root HOME=/root TERM=screen PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]" args="[/usr/bin/lxd forkexec default-ubuntu-1404-1486764297 /var/lib/lxd/containers /var/log/lxd/default-ubuntu-1404-1486764297/lxc.conf -- env USER=root HOME=/root TERM=screen PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -- cmd chown root:root /root/.ssh/authorized_keys]"
t=2017-02-27T15:59:33-0500 lvl=info msg="Executed command" environment="[USER=root HOME=/root TERM=screen PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]" args="[/usr/bin/lxd forkexec default-ubuntu-1404-1486764297 /var/lib/lxd/containers /var/log/lxd/default-ubuntu-1404-1486764297/lxc.conf -- env USER=root HOME=/root TERM=screen PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -- cmd chown root:root /root/.ssh/authorized_keys]"
t=2017-02-27T16:05:30-0500 lvl=info msg="Stopping container" name=default-ubuntu-1404-1486764297 action=stop creation date=2017-02-27T20:59:13+0000 ephemeral=false stateful=false
t=2017-02-27T16:05:30-0500 lvl=info msg="Freezing container" name=default-ubuntu-1404-1486764297 creation date=2017-02-27T20:59:13+0000 ephemeral=false
t=2017-02-27T16:05:30-0500 lvl=info msg="Froze container" ephemeral=false name=default-ubuntu-1404-1486764297 creation date=2017-02-27T20:59:13+0000
t=2017-02-27T16:05:31-0500 lvl=info msg="Stopped container" name=default-ubuntu-1404-1486764297 action=stop creation date=2017-02-27T20:59:13+0000 ephemeral=false stateful=false
t=2017-02-27T16:05:31-0500 lvl=info msg="Deleting container" name=default-ubuntu-1404-1486764297 creation date=2017-02-27T20:59:13+0000 ephemeral=false
t=2017-02-27T16:05:32-0500 lvl=info msg="Deleted container" name=default-ubuntu-1404-1486764297 creation date=2017-02-27T20:59:13+0000 ephemeral=false
t=2017-02-27T16:27:07-0500 lvl=info msg="Updating images"
t=2017-02-27T16:27:07-0500 lvl=info msg="Done updating images"
```

Xenial host
```
# lxc config show default-ubuntu-1604-1488301801
architecture: x86_64
config:
  security.privileged: "true"
  volatile.base_image: 699518185f6db84f04cca429b9101c71d4fe445dae254759f816183e4be022e2
  volatile.eth0.hwaddr: 00:16:3e:b2:e6:4e
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  root:
    path: /
    type: disk
ephemeral: false
profiles:
- default
# uname -a
Linux xxx 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
# lxc info default-ubuntu-1604-1488301801 --show-log
Name: default-ubuntu-1604-1488301801
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/02/28 22:09 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 14144
Ips:
  eth0: inet    10.252.11.106   vethVSU7FR
  eth0: inet6   fe80::216:3eff:feb2:e64e        vethVSU7FR
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 108
  Memory usage:
    Memory (current): 739.50MB
    Memory (peak): 1.27GB
  Network usage:
    eth0:
      Bytes received: 2.02GB
      Bytes sent: 19.36MB
      Packets received: 317899
      Packets sent: 198767
    lo:
      Bytes received: 39.19MB
      Bytes sent: 39.19MB
      Packets received: 114199
      Packets sent: 114199

Log:

            lxc 20160228220917.298 WARN     lxc_start - start.c:signal_handler:322 - Invalid pid for SIGCHLD. Received pid 14136, expected pid 14144.
```

**Comment by stgraber** [comment]
Instead of using mknod from inside the container which will create the device node but not let you use it (as you noticed), you should instead tell LXD to create those devices for you.

Remove that /dev/loop0 from inside the container and do:
```
lxc config device add default-ubuntu-1604-1488301801 loop0 unix-block path=/dev/loop0
lxc config device add default-ubuntu-1604-1488301801 loop1 unix-block path=/dev/loop1
lxc config device add default-ubuntu-1604-1488301801 loop2 unix-block path=/dev/loop2
lxc config device add default-ubuntu-1604-1488301801 loop3 unix-block path=/dev/loop3
lxc config device add default-ubuntu-1604-1488301801 loop4 unix-block path=/dev/loop4
lxc config device add default-ubuntu-1604-1488301801 loop5 unix-block path=/dev/loop5
lxc config device add default-ubuntu-1604-1488301801 loop6 unix-block path=/dev/loop6
lxc config device add default-ubuntu-1604-1488301801 loop7 unix-block path=/dev/loop7
lxc config device add default-ubuntu-1604-1488301801 loop-control unix-char path=/dev/loop-control
```

That will properly create and allow all 8 loop devices and also pass loop-control which most tools now use to allocate loop devices.

**Comment by juju4** [comment]
doesn't seem so

Xenial host
```
# lxc config show --expanded default-ubuntu-1604-1488301801
architecture: x86_64
config:
  security.privileged: "true"
  volatile.base_image: 699518185f6db84f04cca429b9101c71d4fe445dae254759f816183e4be022e2
  volatile.eth0.hwaddr: 00:16:3e:b2:e6:4e
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  loop-control:
    path: /dev/loop-control
    type: unix-char
  loop0:
    path: /dev/loop0
    type: unix-block
  loop1:
    path: /dev/loop1
    type: unix-block
  loop2:
    path: /dev/loop2
    type: unix-block
  loop3:
    path: /dev/loop3
    type: unix-block
  loop4:
    path: /dev/loop4
    type: unix-block
  loop5:
    path: /dev/loop5
    type: unix-block
  loop6:
    path: /dev/loop6
    type: unix-block
  loop7:
    path: /dev/loop7
    type: unix-block
  root:
    path: /
    type: disk
ephemeral: false
profiles:
- default
root@default-ubuntu-1604-1488301801:~# mount -o loop,ro,noexec,noload /cases/sources/victoria-v8.sda1.img /mnt
mount: /cases/sources/victoria-v8.sda1.img: failed to setup loop device: Operation not permitted
root@default-ubuntu-1604-1488301801:~# ls -l /dev/loop*
brw-rw---- 1 root root  7,   0 Mar  1 01:11 /dev/loop0
brw-rw---- 1 root root  7,   1 Mar  1 01:11 /dev/loop1
brw-rw---- 1 root root  7,   2 Mar  1 01:11 /dev/loop2
brw-rw---- 1 root root  7,   3 Mar  1 01:11 /dev/loop3
brw-rw---- 1 root root  7,   4 Mar  1 01:11 /dev/loop4
brw-rw---- 1 root root  7,   5 Mar  1 01:11 /dev/loop5
brw-rw---- 1 root root  7,   6 Mar  1 01:11 /dev/loop6
brw-rw---- 1 root root  7,   7 Mar  1 01:11 /dev/loop7
crw-rw---- 1 root root 10, 237 Mar  1 01:11 /dev/loop-control
```

same on Trusty host
