### ISSUE TITLE
[2.0.9] apparmor change: host and guest?

### ISSUE THREAD

**Issue by juju4** [lxc/lxd#2981]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-62-generic
   * LXC version: 2.0.7-0ubuntu1~16.04.1
   * LXD version: 2.0.8 -> 2.0.9

# Issue description

I have a bind setup in a container and I observed recently it fails to start for some permission denied on custom log path.
This error is commonly linked to apparmor but its profile customization inside guest container is part of my deployment play.

Just in case, I tried to do the change in apparmor profiles of host and after, bind started again.
It seems lxc/lxd was updated from 2.0.6/2.0.8 to 2.0.7/2.0.9 the day before it stopped working.

is it new normal behavior? documented? not found any with a quick search.
I checked https://linuxcontainers.org/lxd/news/ but didn't see any matching entry

Thanks

# Steps to reproduce

 1. Have bind in container with custom apparmor profile (ex: custom log to /var/log/bind)
 2. start daemon

before: OK
after 2.0.7/2.0.9: need to modify host profile too

**Comment by stgraber** [comment]
Can you show "lxc config show --expanded NAME-OF-CONTAINER"?

**Comment by juju4** [comment]
```
# lxc config show --expanded dlbind                        
architecture: x86_64
config:
  volatile.base_image: 8542ececdfd6d9a01f3f52ec79c5c82947f525cd73a4e1f3ea16cadd5c34dd05
  volatile.eth0.hwaddr: 00:16:3e:82:7d:c3
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    type: disk
ephemeral: false
profiles:
- default
```
