### ISSUE TITLE
Problem moving containers after storage-pools migration

### ISSUE THREAD

**Issue by sbworth** [lxc/lxd#3036]
# Required information

 * Distribution: Ubuntu
 * Distribution version:  16.04LTS and 14.04LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0
   * LXC version: 2.10.1 and 2.10.1
   * LXD version: 2.10.1 and 2.10.1
   * Storage backend in use: LVM and dir

# Issue description

When attempting to move a container from sys2 (LVM) to sys1 (dir), I get:
```
root@sys2:~# lxc move test1 sys1:
error: sql: no rows in result set
```
On the receiving system,  sys1, I see in `var/log/lxd/lxd.log`:
```
INFO[03-07|15:40:29] Creating container       ephemeral=false name=test1
INFO[03-07|15:40:29] Deleting container       created=2017-03-07T20:40:29+0000 ephemeral=false name=test1 used=1970-01-01T00:00:00+0000
INFO[03-07|15:40:29] Deleted container        created=2017-03-07T20:40:29+0000 ephemeral=false name=test1 used=1970-01-01T00:00:00+0000
```
I tried creating a new container test3, and then moved it from sys2 to sys1, started it up, turned it off, and then transferred it back; so new containers seem to be fine.

I confirmed with a couple of other containers as well.
```
  Prexisting container  => failure
  New container  => success
```
It appears that lxd.db has not been updated properly. :-(
(Currently looking for differences in lxd.db between new and pre-storage-api containers.)

**Comment by brauner** [comment]
Can you please also show:
- `lxc storage volume show container/<container_name>`
- `lxc storage show <pool_name>`

**Comment by sbworth** [comment]
Truncated list, but all containers show the same references:
```
root@sol2:/var/lib/lxd# lxc storage show lxd
config:
  lvm.thinpool_name: LXDPool
  lvm.vg_name: lxd
  source: lxd
  volume.size: 21GB
name: lxd
driver: lvm
used_by:
- /1.0/containers/pcstest
- /1.0/containers/sample-alpine34
- /1.0/containers/sample-jessie
- /1.0/containers/test1
- /1.0/containers/test2
- /1.0/containers/test3
- /1.0/containers/webwork
- /1.0/images/11fc1b1d39b9f9cd7e9491871f1421ac4278e1d599ecf5d180f2a6e2483bd172
- /1.0/images/18e7ed74d0d653894f65343afbc35b92c6781933c273943d882c36a5c5535533
- /1.0/images/457a80ea4720900b69e5542cea5351f58021331bc96e773e4855a3e2ce1e6595
- /1.0/images/543e662b70958f5b87f68b20eb0a205d8c4b14c41f80699e9a98b3b851883d15
- /1.0/images/a570ce23e1dae791e7b8b2f2bcb98c1404273e97c7a1fb972bf0f5835ac3e869
- /1.0/images/d7c16c4fedd3308b5bffdb91f491b8458610c6115d37ace8ba4bcf5c29b23cc6
- /1.0/images/e12c3c1aed259ce62b4a5e8dc5fe8b92d14d36e611b3beae3f55c94df069eeed
- /1.0/profiles/default
```
```
root@sys2# lxc storage volume show lxd container/pcstest
name: pcstest
config:
  block.filesystem: ext4
  size: 300GB
type: container
used_by: []
```
This is strange, because pcstest is actually 10.0GB.

LVM info from `lvs`:
```
  containers_pcstest                                                      lxd  Vwi-aotz--  10.00g LXDPool images_543e662b70958f5b87f68b20eb0a205d8c4b14c41f80699e9a98b3b851883d15 8.59 ```
  images_543e662b70958f5b87f68b20eb0a205d8c4b14c41f80699e9a98b3b851883d15 lxd  Vwi-a-tz--  10.00g LXDPool                                                                         8.59                               
```
It may be important to know that I attempted to change volume.size to 20GB, but the change was rejected as deprecated. I then edited it back to 300GB and it seemed to accept the value and exit without an obvious error, but now volume.size says 21GB. Something seems messed up.

The target LXD server has 2.3TB in its storage pool; so there is no space constraint at work.
