### ISSUE TITLE
adding another volume changes quota on btrfs root volume to 0.00B

### ISSUE THREAD

**Issue by visit1985** [lxc/lxd#3043]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.2
 * Host filesystems:
   * `/` (ext4)
   * `/var/lib/lxd` (btrfs)
 * The output of "lxc info":
```
config:
  core.proxy_http: ...
  core.proxy_https: ...
apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  certificatefingerprint: ...
  driver: lxc
  driverversion: 2.0.7
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-64-generic
  server: lxd
  serverpid: 36551
  serverversion: 2.0.9
  storage: btrfs
  storageversion: "4.4"
```

# Issue description

I'm using a quota enabled btrfs as storage backend. When I add an additional bind mount (non-btrfs) from the host, the quota for the btrfs root volume is changed to 0.00B.

# Steps to reproduce

 1. Create a centos container:
    `lxc launch images:centos/7/amd64 centos`
 2. Set a quota for it:
    `lxc config device set centos root size 5GB`
 3. Ensure the quota is set:
    `btrfs qgroup show -re /var/lib/lxd`
```
qgroupid         rfer         excl     max_rfer     max_excl
--------         ----         ----     --------     --------
0/259       398.75MiB    398.75MiB         none      5.00GiB
```
 4. Add another (non-btrfs) device:
    `lxc config device add centos data disk source=/srv/centos path=/srv`
 5. Check the quota on the host again:
    `btrfs qgroup show -re /var/lib/lxd`
```
qgroupid         rfer         excl     max_rfer     max_excl
--------         ----         ----     --------     --------
0/259       398.75MiB    398.75MiB         none        0.00B
```
 6. Check the container config:
    `lxc config device get centos root size`
    It remains `5GB`.
