### ISSUE TITLE
Clarifying root device configuration in storage-api era

### ISSUE THREAD

**Issue by sbworth** [lxc/lxd#3045]
* Distribution: Ubuntu
 * Distribution version: 14.04LTS and 16.04LTS
   * LXC version: 2.10.1
   * LXD version: 2.10.1
   * Storage backend in use: dir and LVM

# Root Device Configuration

My older containers (created under lxd<2.9) all have configuration data that contains a devices section that looks like:
```
devices:
  root:
    path: /
    pool: default
    type: disk
```
The newly created containers, with lxd==2.10.1, all look like:
```
devices: {}
```

The new containers all work as long as they inherit from the default profile, which currently looks like:
```
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxcbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
```
In this scenario, all device data is inherited/defined from the profile.

Unfortunately, the majority of my containers do not associate with the default profile. These profiles look like:
```
config:
  user.network_mode: link-local
description: ""
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br165
    type: nic
name: vlan165
```
They DO NOT define a root device section. I am 90% confident that at the time I modelled them after the default profile, there was no such section in the default profile either.

To keep everything working, I need to inherit a root device from somewhere. 

- Is there a problem with having the root disk defined in the individual container now?
- Is there a problem with having the root disk defined in both the container AND a profile? Will the container setting override the profile setting?
- I am considering creating a rootdisk profile that defines only the root and then assigning it to all of the affected containers along with my network-oriented profiles. Do you see a problem with that?
