### ISSUE TITLE
Cannot pass config value with space in `lxc launch`

### ISSUE THREAD

**Issue by nisargjhaveri** [lxc/lxd#3095]
# Issue description

When I try to run `lxc launch ... -c key="value"`, if the `"value"` has a space in it, the command fails with `error: wrong number of subcommand arguments`. If the value does not have any spaces, everything works as expected. I also tried to escape the spaces without any luck.

How do I set multiword config option while launching a container?

# Steps to reproduce

 1. Run `lxc launch ... -c key="word1 word2"`

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info":
```
api_status: stable
api_version: "1.0"
environment:
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-66-generic
  server: lxd
  server_pid: 2578
  server_version: "2.11"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu15
```
