### ISSUE TITLE
sql no rows in result set on lxc copy

### ISSUE THREAD

**Issue by cryptofuture** [lxc/lxd#3137]
`lxc copy target:con6 con6` fails with
```
error: sql: no rows in result set
```
   >Note: I already recreated (btw, looks like we still have no copy in lxc network)  lxdbr2 interface and copied limit profile from target

Ubuntu Xenial 16.04.x
[monitor-log.txt](https://github.com/lxc/lxd/files/886466/monitor-log.txt)
[copy-debug.txt](https://github.com/lxc/lxd/files/886461/copy-debug.txt)

```
:lxc info
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-71-generic
  server: lxd
  server_pid: 944
  server_version: "2.12"
  storage: btrfs
  storage_version: "4.4"
```
```
:target lxc info
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-13-generic
  server: lxd
  server_pid: 4590
  server_version: "2.12"
  storage: zfs
  storage_version: 0.6.5.9-2
```

```
:lxc profile show limit
config: {}
description: ""
devices:
  eth0:
    limits.egress: 600Kbit
    limits.ingress: 600Kbit
    nictype: bridged
    parent: lxdbr2
    type: nic
  root:
    path: /
    pool: lxd
    type: disk
name: limit
used_by:
- /1.0/containers/con6
```
```
:lxc config show con6
architecture: x86_64
config:
  volatile.base_image: id
  volatile.eth0.hwaddr: mac
  volatile.eth0.name: eth0
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: STOPPED
  volatile.root.hwaddr: mac
  volatile.root.name: eth1
devices:
  root:
    path: /
    pool: lxd
    type: disk
ephemeral: false
profiles:
- limit
```

**Comment by stgraber** [comment]
Do you have a storage pool called "lxd" on the target server?

**Comment by cryptofuture** [comment]
Oh, I understand what you suggesting, and most likely it is. lxd storage still remains the same in copied profile, but i have no `lxd` storage on another machine, its could `default` on it.
Will try to edit profile.

**Comment by stgraber** [comment]
Note that the error message totally needs to be fixed as it's very confusing :)

But since your source container has a direct device entry for a root using the "lxd" pool, LXD will fail to re-create the container on the target unless there is a similarly named pool available.

The best option may be to remove that container device entry, letting it inherit from the default profile instead, then migrate it again, which would have LXD use the profile of the remote server to select what storage pool to use.

**Comment by stgraber** [comment]
@brauner can you reproduce this issue and fix the error to make a bit more sense to users? :)

**Comment by cryptofuture** [comment]
Btw, I still can test myself. Copying 60Gb container right now, more ~80% done. So I can try again only after it will finish.

**Comment by cryptofuture** [comment]
Thats what I have after profile editing now, still same error.
```
config: {}
description: ""
devices:
  eth0:
    limits.egress: 600Kbit
    limits.ingress: 600Kbit
    nictype: bridged
    parent: lxdbr2
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: limit
used_by: []
```
```
+---------+--------+----------------------------+---------+
|  NAME   | DRIVER |           SOURCE           | USED BY |
+---------+--------+----------------------------+---------+
| default | btrfs  | /var/lib/lxd/disks/default | 31      |
+---------+--------+----------------------------+---------+
```
