### ISSUE TITLE
container not starting with idmap

### ISSUE THREAD

**Issue by nhadsall** [lxc/lxd#3149]
I have folder mounted in my container with:
```
devices:
  oc-data:
    path: /data/oc/
    source: /data/oc/
    type: disk
```
In the host, this folder is owned by www-data.

I wanted to map this to a different user in the container
```
raw.idmap: |
    uid 33 112
```

I have tried multiple variations to get this to work (even using `raw.lxc = lxc.id_map`, but it won't ever start. 

Thoughts?

Here is the full lxc config edit if it helps

```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20170330)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20170330"
  image.version: "16.04"
  raw.idmap: |
    uid 33 112
  volatile.base_image: 3e50ba589426c21f26370e2f949f30210f2d0419fbb9d4d4a0f860a035373353
  volatile.eth0.hwaddr: 00:16:3e:4b:2c:80
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":112},{"Isuid":true,"Isgid":false,"Hostid":33,"Nsid":112,"Maprange":1},{"Isuid":true,"Isgid":false,"$
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":112},{"Isuid":true,"Isgid":false,"Hostid":33,"Nsid":112,"Maprange":1},{"Isuid":true,"Isgid":f$
  volatile.last_state.power: RUNNING
devices:
  oc-data:
    path: /data/oc/
    source: /data/oc/
    type: disk
ephemeral: false
profiles:
- default
```
