### ISSUE TITLE
[LXD 2.12] Unable to Resize Container backed by LVM

### ISSUE THREAD

**Issue by neil-bowers** [lxc/lxd#3150]
# Required information

 * Distribution: Ubuntu Server
 * Distribution version: 16.10
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 2.12
   * LXD version: 2.12
   * Storage backend in use: LVM

# Issue description

Attempting to resize an existing container utilizing the new `storage` commands fails, even when the container is stopped.

# Steps to reproduce

 1.
```
└─▪ lxc storage list
+--------+--------+--------+---------+
|  NAME  | DRIVER | SOURCE | USED BY |
+--------+--------+--------+---------+
| lxc-vg | lvm    | lxc-vg | 11      |
+--------+--------+--------+---------+
```
 2. 
```
└─▪ lxc storage volume list lxc-vg
+-----------+------------------------------------------------------------------+---------+
|   TYPE    |                               NAME                               | USED BY |
+-----------+------------------------------------------------------------------+---------+
| container | intense-osprey                                                   | 0       |
+-----------+------------------------------------------------------------------+---------+
| container | minecraft                                                        | 0       |
+-----------+------------------------------------------------------------------+---------+
| container | minecraft-dev                                                    | 0       |
+-----------+------------------------------------------------------------------+---------+
| image     | 2cab90c0c342346ea154bc2e8cacdae752a70747a755ce1f2970c9a9ebb5fe8c | 0       |
+-----------+------------------------------------------------------------------+---------+
| image     | 5997477b0ef64780540d274fe25b812640ba7e91094dc5b27befbbde1f0a0fc2 | 0       |
+-----------+------------------------------------------------------------------+---------+
| image     | a5f582060c4f453d8385d19e3f4e88be0a4169217ec413a5d9ef71bbcc969436 | 0       |
+-----------+------------------------------------------------------------------+---------+
```

 3.
```
└─▪ lxc storage volume show lxc-vg container/minecraft
config:
  block.filesystem: ext4
  size: 10GB
name: minecraft
type: container
used_by: []
```

4.
```
└─▪ lxc storage volume set lxc-vg container/minecraft size 20GB
error: The properties "[size]" cannot be changed.
```

# Comments

- I get this error regardless if the container is stopped or started.
- There is plenty of room on the disk in question - in fact, the storage pool consumes the entire disk
- As an aside, the `volume.size` key in the `pool` properties isn't clear on whether that relates to the pool itself, or to the subsequent container volumes created, especially since there is no equivalent `pool.size` property:
```
└─▪ lxc storage show lxc-vg
config:
  lvm.thinpool_name: LXDThinpool
  lvm.vg_name: lxc-vg
  source: lxc-vg
  volume.block.filesystem: ext4
  volume.size: 20GB
name: lxc-vg
driver: lvm
used_by:
- /1.0/containers/intense-osprey
- /1.0/containers/minecraft
- /1.0/containers/minecraft-dev
- /1.0/images/2cab90c0c342346ea154bc2e8cacdae752a70747a755ce1f2970c9a9ebb5fe8c
- /1.0/images/5997477b0ef64780540d274fe25b812640ba7e91094dc5b27befbbde1f0a0fc2
- /1.0/images/a5f582060c4f453d8385d19e3f4e88be0a4169217ec413a5d9ef71bbcc969436
- /1.0/profiles/default-lxc
- /1.0/profiles/default-msm
- /1.0/profiles/default-msm-dev
- /1.0/profiles/default-old
- /1.0/profiles/default-smb
```
