### ISSUE TITLE
lxd stop / lxd restart hangs and never returns (Command get_cgroup failed to receive response: Connection reset by peer)

### ISSUE THREAD

**Issue by tchwpkgorg** [lxc/lxd#3159]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04

I saw the issue with various 2.0.x versions; the last one where it happens is 2.0.9-0ubuntu1~16.04.2. Also tried different many kernels (stock Ubuntu, newer ppa).

- "lxc stop container" will stop the container but will never exit
- "lxc restart container" will stop the container, will not start it again and will never exit

This gets logged to container log:

            lxc 20170301115514.738 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - Command get_cgroup failed to receive response: Connection reset by peer.

When it starts to happen, it affects all containers. LXD server runs 100+ containers, which starts/stops/deletes dozens of containers daily and is used for automation, sometimes many at the same time. Approximately once every 1-2 months, "lxc stop" / "lxc restart" command will fail, which is a bit of stability concern for us.

The only thing which fixes that is server restart (lxd restart doesn't fix it).

There is also no clear way to reproduce it reliably (other than running the server for long, and starting/stopping a large number of containers over that time...).

```
# lxc info
config:
  core.https_address: '[::]'
  core.trust_password: true
apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
public: false
environment:
  addresses:
(...)
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
(...)
  driver: lxc
  driverversion: 2.0.7
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.10.8-041008-generic
  server: lxd
  serverpid: 2269
  serverversion: 2.0.9
  storage: btrfs
  storageversion: "4.4"

```
