### ISSUE TITLE
Install nfs server on CentOS 6 container

### ISSUE THREAD

**Issue by k-hristov** [lxc/lxd#3209]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * "lxc info"
  ```
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
  storage.zfs_pool_name: lxd
apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - xxx.xxx.xxx.xxx:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFZzCCA0+gAwIBAgIQT8m1n1aOX8uV7dhAsRAK2DANBgkqhkiG9w0BAQsFADAz
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRMwEQYDVQQDDApyb290QHNy
    djAyMB4XDTE3MDIyNzIzMTMzNFoXDTI3MDIyNTIzMTMzNFowMzEcMBoGA1UEChMT
    bGludXhjb250YWluZXJzLm9yZzETMBEGA1UEAwwKcm9vdEBzcnYwMjCCAiIwDQYJ
    KoZIhvcNAQEBBQADggIPADCCAgoCggIBAN0GCJtED/f8i5sc07/GnfnmnsPmc3qa
    I0f5h/HZjqea/7ShIP6b6wfxq0hq0E3wQ9qZJ9e9gF4f8HJ5pKVmu8QWYQHzbphM
    TZnQo+XZcby0EsvEm3Mxcm06gYxZ/AdAZlLHBsVAa027EXGps4zxghXdQGcos5YL
    H+VbC1nLd9U2H/HdfxIhx2/oaxS+ytwoy5SmbuAh/aIHJK20c0ZSmmwcw0RBCk2j
    VaV6odNHC/IXPGlYFB/QN8HJk0jciK6zXzFmjEaaKO1Vmxs0gCHYQnRkwtrgwjDJ
    wi7bVraeJZh7SlJ/RSGRqER0xufpPZrloG7mIUx2xZHlw5a5GSTVOYIkpI8VQeWL
    ZMVZzA2w/2snFFj/BZZhYZE1kvEQxTha8O2TdfcubHcttx40m0EN8eMJM3BaKLW9
    4DhPztq3ci0xMn8+6Ci1qfXJiomz8DfSs5Yn2mc4QNLMTekJ5Z0z1lhdjGvPa8ps
    VorbPK13pQOAfFfIsmUF7FjrlGrKzl0xP3wi6s8/WeHQxxZb1gOoN6It6sKBh7G6
    Lds0fC6a4gnqtpoBI0PAfWicp4CMy107b6oJloJyZEico48Bbhx6zJIrnV0dkkYX
    7qayeSnG40Ishri+YSiL62K0TBcKz99WawO7wR+0Yw6skILdJ3TFUde8J54Hse0O
    shmWc7LL5Nw7AgMBAAGjdzB1MA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggr
    BgEFBQcDATAMBgNVHRMBAf8EAjAAMEAGA1UdEQQ5MDeCBXNydjAyhwSsEQFnhwSs
    EQHIhxD9dbHGNTEAAHwnEV7z71MDhxD9dbHGNTEAAJKxHP/+EmytMA0GCSqGSIb3
    DQEBCwUAA4ICAQC5TZmjwckqbd6Yuzp0fIZLcAcX1AO2O7b/bpohMr3H5AonTftj
    GcaG5p5j0HG25K8PU/YYQJpGLChOj1rRnwLcjsUfpVtNges0uc8KLi6sx9qLH3C3
    Ne1VgWA2Jmx4NCxJChzMdEoxAmszfhDXiyX2/30YRduztxzUBVZ0BR+tnsUN9Qcf
    R+T7hma1c8blx1bGRfd/oEYW7no9cT3dkxNiLZDptlrQH73+5gUBoOJrIhAqiR4t
    i9w1FLtkLLKiOYuqdK14dSo6I9y8HM4lUQEQAwKAQcxgb6QyPOj6y4SDrAj48xZv
    dRcL6RoYRCEievHi1cjCmwb69VCUWyd7R/TnQeA+O1xs2OjuDnkN43uVtn4Yuali
    Y0GlGL9AuyF6bqlXZfHX0zdu/0biy4DBp7gZYhHQLr3Hn/TPrU5KI1P/fP5JfqtQ
    Fem1kX3OUBStGlWHNq0Xs1tQQZ5mTV7vLXqc16GKH4Z+Fc0lVpCGX9LAZhph+pJf
    O07sBMGAla2sG5YCx2XOE4P3J8nbziIoqDHUbcJYSGH3SpQMI1GLbTl/TE5Zx2or
    KFPTXW2asFEnoMcMFOPqPDoC9D3oIB2nAHv6t/4BRp7xdZsgvHbTTc7ZlrLh5c50
    O9k+gi++mYm/eE3Rsp3Suh6lRSgl6ijrFGCWosgmPnyxjiRL9YYN6v0u6A==
    -----END CERTIFICATE-----
  certificatefingerprint: 6389486ba3d1fca8aee777956fea86a81dc226caeb9d6582b9be308753864639
  driver: lxc
  driverversion: 2.0.7
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.8.0-46-generic
  server: lxd
  serverpid: 3856
  serverversion: 2.0.9
  storage: zfs
  storageversion: "5"
```

# Issue description
I am getting the following errors while installing nfs-utils on centos 6 guest container

```
FATAL: Could not load /lib/modules/4.8.0-46-generic/modules.dep: No such file or directory
rpc.nfsd: Unable to access /proc/fs/nfsd errno 2 (No such file or directory).
Please try, as root, 'mount -t nfsd nfsd /proc/fs/nfsd' and then restart rpc.nfsd to correct the problem
```
Container config:
```
architecture: x86_64
config:
  limits.cpu: 2,3
  limits.memory: 4GB
  limits.memory.swap: "false"
  raw.apparmor: |
    mount fstype=rpc_pipefs,
    mount fstype=nfsd,
  volatile.base_image: 489092b254ae3bfe8d780128925b5cb1a1e0da5efa147301b8fb08fd3b1f3c48
  volatile.eth0.hwaddr: 00:16:3e:97:89:e3
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  root:
    path: /
    size: 30GB
    type: disk
ephemeral: false
profiles:
- default
```

I am doing normal installation of NFS server
```
yum install nfs-utils nfs-utils-lib
```
