### ISSUE TITLE
bad d_type in dirent struct

### ISSUE THREAD

**Issue by tatraian** [lxc/lxd#3213]
Hello,

I have a character device (Thermo Printer). I would like to use it in our lxc2 container. I added it to my container with lxc device add. My problem is that the type of the file looks bad in case of `C` `dirent` struct.

I wrote the next program:
```
#include <iostream>                                                                                                                                                                                            
#include <dirent.h>                                                                                                                                                                                            
                                                                                                                                                                                                               
using namespace std;                                                                                                                                                                                           
                                                                                                                                                                                                               
int main(){                                                                                                                                                                                                    
  DIR* dir = opendir("/dev/bus/usb/002");                                                                                                                                                                      
  struct dirent *dp;                                                                                                                                                                                           
  while ((dp = readdir (dir)) != NULL) {                                                                                                                                                                       
    cout << "name: " << dp->d_name  << " type: " << (int)dp->d_type << endl;                                                                                                                                   
  }                                                                                                                                                                                                            
  return 0;                                                                                                                                                                                                    
}
```

This gives back the following result on my machine:
Host:
```
name: 014 type: 2
```

Container:
```
name: 014 type: 8
```

The strange is that `file` or `ls` shows the dev file as character device:
```
Antal.Tatrai@xion:~$ ls -l /dev/bus/usb/002/014
crw-rw-rw- 1 root root 189, 141 ápr   24 16.18 /dev/bus/usb/002/014
Antal.Tatrai@xion:~$ file /dev/bus/usb/002/014
/dev/bus/usb/002/014: character special
```

I use Kubuntu 17.04 as host and CentOS 6 as container OS.
My container's config is the next:
```
architecture: i686
config:
  raw.idmap: both 1000 1000
  volatile.base_image: e26453f545ee3b6008183a1745460412ae8fe5bad441839ee3a699adf0c76124
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":166537,"Nsid":1001,"Maprange":64535},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":166537,"Nsid":1001,"Maprange":64535}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":166537,"Nsid":1001,"Maprange":64535},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":166537,"Nsid":1001,"Maprange":64535}]'
  volatile.last_state.power: RUNNING
  volatile.lxdbr0.hwaddr: 00:16:3e:3b:77:b7
  volatile.lxdbr0.name: eth0
devices:
  barcode:
    mode: "0666"
    productid: "1602"
    type: usb
    vendorid: 05f9
  homedir:
    path: /home/Antal.Tatrai
    source: /var/lib/kobold/Antal.Tatrai
    type: disk
  lxdbr0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  monikey:
    mode: "0666"
    productid: "5321"
    type: usb
    vendorid: 076b
  root:
    path: /
    pool: default
    type: disk
  xiprint:
    mode: "0666"
    productid: "0305"
    type: usb
    vendorid: 0aa7
  xiprint_download:
    gid: "7"
    mode: "0666"
    productid: "8305"
    type: usb
    vendorid: 0aa7
  xiscan:
    mode: "0666"
    productid: "0401"
    type: usb
    vendorid: 0aa7
ephemeral: false
profiles:
- default
```

Output of lxc info:

```
config:
  core.https_address: '[::]:8443'
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 192.168.26.98:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  certificate_fingerprint: ...
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-19-generic
  server: lxd
  server_pid: 1585
  server_version: "2.12"
  storage: btrfs
  storage_version: 4.9.1
```
