### ISSUE TITLE
Is there an example or method to manage the cloud-init configuration separately?

### ISSUE THREAD

**Issue by jehos** [lxc/lxd#3347]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 17.04
 * The output of "lxc info" or if that fails:
  * kernel: Linux
  * kernel_architecture: x86_64
  * kernel_version: 4.4.0-78-generic
  * server: lxd
  * server_pid: 2853
  * server_version: "2.13"
  * storage: zfs
  * storage_version: 0.6.5.6-0ubuntu16

I'm using cloud-init very happily in lxd.
I wanted to manage the common part and the user part.
So I did follow.

# profile 

## common parts
```
jehos@2:~⟫ lxc profile show default
config:
  user.network-config: |
    version: 1
    config:
      - type: physical
        name: eth0
        subnets:
          - type: dhcp
            ipv4: true
            control: auto
      - type: nameserver
        address: 8.8.8.8
  user.user-data: |
    #cloud-config
    package_upgrade: true
    package_reboot_if_required: true
    packages:
      - avahi-daemon
    manage_etc_hosts: "localhost"
    locale: ko_KR.UTF-8
    timezone: Asia/Seoul
description: Default LXD profile
devices:
  eth0:
    nictype: macvlan
    parent: eth0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
```

## user-specific part
```
jehos@2.lxd.gnuxer:~⟫ lxc profile show jehos
config:
  user.user-data: |
    users:
      - name: jehos
        ssh-authorized-keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1hjoag7WosRbmEf1s/4IDwdtsTeHDvgHjzwoxlGwRmhwl/EBkKB0IembioPxNEy/z8DhTgHYCAUiC2eEmetdAkATpJeRoi895fQktI2y7ISeeebrPcyTWazSJMpSecf+jk9JRY8ia15awkyr4hQ9vIErWVtmI7OczQCCee+5KDO0i/s3QGNu23T5JpaeJKxPF9jLrx/brKUkrP83HJd0FqmfUxIC2LfJdtaK90wcVROGOQL6mOqG8H7kw1ravKO6pHTp05UE5stuk0NFSZhS/8CTDTlI4rsEYP/Yu/D0dDj+c2CwzAxHhB2HaNeXvl6VX3Sec+mekLCKUw5701H2d jehos
        sudo: ['ALL=(ALL) NOPASSWD:ALL']
        groups: sudo
        shell: /bin/bash
description: jehos
devices: {}
name: jehos
```

# init & launch container

```
jehos@2:~⟫ lxc init x jehos -p default -p jehos
Creating jehos


jehos@2:~⟫ lxc start jehos
jehos@2:~⟫ lxc start jehos
jehos@2:~⟫ lxc exec jehos bash
root@jehos:~# cat /var/lib/cloud/seed/nocloud-net/user-data 
users:
  - name: jehos
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1hjoag7WosRbmEf1s/4IDwdtsTeHDvgHjzwoxlGwRmhwl/EBkKB0IembioPxNEy/z8DhTgHYCAUiC2eEmetdAkATpJeRoi895fQktI2y7ISeeebrPcyTWazSJMpSecf+jk9JRY8ia15awkyr4hQ9vIErWVtmI7OczQCCee+5KDO0i/s3QGNu23T5JpaeJKxPF9jLrx/brKUkrP83HJd0FqmfUxIC2LfJdtaK90wcVROGOQL6mOqG8H7kw1ravKO6pHTp05UE5stuk0NFSZhS/8CTDTlI4rsEYP/Yu/D0dDj+c2CwzAxHhB2HaNeXvl6VX3Sec+mekLCKUw5701H2d jehos
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
root@jehos:~# 
```

I expected the common part and the user part "user-data" to be combined.
but, it was "last man standing".  Only the last setting left.

So I moved the common part from "user-data" to "vendor-data".
and it work like a charm! but it just another workaround.

Is there an example or method to manage the cloud-init configuration separately?
