### ISSUE TITLE
LXD's zpool backend keeps growing

### ISSUE THREAD

**Issue by sajoupa** [lxc/lxd#3377]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 16.04.2
 * The output of "lxc info":
```
config:
[...]
  storage.zfs_pool_name: lxd
apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
[...]
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-51-generic
  server: lxd
  serverpid: 123622
  serverversion: 2.0.9
  storage: zfs
  storageversion: "5"
```

# Issue description

The ZFS pool that LXD uses keeps growing, very slowly, but continuously, despite having lots of free space:
```
$ sudo zpool list
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
lxd    154G  6.34G   148G         -    17%     4%  1.00x  ONLINE  -

$ sudo zfs list -t all
NAME                                                                                           USED  AVAIL  REFER  MOUNTPOINT
lxd                                                                                           6.31G   143G    19K  none
lxd/containers                                                                                5.65G   143G    19K  none
lxd/containers/juju-2691ab-21-lxd-0                                                           5.65G   143G  5.86G  /var/lib/lxd/containers/juju-2691ab-21-lxd-0.zfs
lxd/deleted                                                                                    346M   143G    19K  none
lxd/deleted/images                                                                             346M   143G    19K  none
lxd/deleted/images/fc6d723a6e662a5a4fe213eae6b7f4c79ee7dd566c99856d96a5ca677a99b15d            346M   143G   346M  none
lxd/deleted/images/fc6d723a6e662a5a4fe213eae6b7f4c79ee7dd566c99856d96a5ca677a99b15d@readonly      0      -   346M  -
lxd/images                                                                                     300M   143G    19K  none
lxd/images/8fa08537ae51c880966626561987153e72d073cbe19dfe5abc062713d929254d                    300M   143G   300M  /var/lib/lxd/images/8fa08537ae51c880966626561987153e72d073cbe19dfe5abc062713d929254d.zfs
lxd/images/8fa08537ae51c880966626561987153e72d073cbe19dfe5abc062713d929254d@readonly              0      -   300M  -
```

```
$ sudo du -sh /var/lib/lxd/zfs.img
113G    /var/lib/lxd/zfs.img

```
```
$ sudo du -sk /var/lib/lxd/zfs.img ; sleep 10 ; sudo du -sk /var/lib/lxd/zfs.img
118270156       /var/lib/lxd/zfs.img
118270200       /var/lib/lxd/zfs.img
```

# Steps to reproduce

unknown

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
```
lvl=info msg="Updating images" t=2017-06-01T08:03:41+0000
lvl=info msg="Done updating images" t=2017-06-01T08:03:44+0000
```
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug
