### ISSUE TITLE
VLAN containers working Non VLAN not working?

### ISSUE THREAD

**Issue by mheroux2** [lxc/lxd#3379]
I have a host LXC machine that uses VLANs for some containers but not for others. I've been able to migrate and get containers VLAN containers working but am unable to figure out how to get containers that operate on the same network to work. Any help would be appreciated - I've read through the docs and tried numerous combinations. I don't want to use the LXD bridge (lxdbr0).

HOST /etc/network/interfaces
```
# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto standard
iface standard inet static
        address 172.x.x.x
        netmask 255.255.x.x
        network 172.x.x.x
        broadcast 172.x.x.x
        dns-nameservers 10.x.x.x 10.x.x.x 10.x.x.x
        dns-search marlboro.edu
        bridge_ports eno1
        post-up route add default gw 172.x.x.x
        pre-down route del default

auto vlan2
iface vlan3 inet manual
        address 0.0.0.0
        vlan-raw-device eno1

auto cad
        iface cad  inet manual
        address 0.0.0.0
        bridge_ports vlan2

auto vlan3
iface vlan3 inet manual
       address 0.0.0.0
       vlan-raw-device eno1

auto admin
  iface admin   inet manual
  address 0.0.0.0
  bridge_ports vlan
```

# lxc info
```
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
  images.auto_update_interval: "0"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 172.x.x.x:8443
  - 10.x.x.x:8443
   architectures:
  - x86_64
  - i686
  certificate: [REMOVED]
  certificate_fingerprint: [REMOVED]
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-78-generic
  server: lxd
  server_pid: 1882
  server_version: "2.14"
  storage: dir
  storage_version: "1"
```
Example of container config that works on VLAN
```
  GNU nano 2.5.3          File: /tmp/lxd_editor_137012770.yaml                          

### This is a yaml representation of the configuration.
### Any line starting with a '# will be ignored.
###
### A sample configuration looks like:
### name: container1
### profiles:
### - default
### config:
###   volatile.eth0.hwaddr: 00:16:3e:e9:xx:xx
### devices:
###   homedir:
###     path: /extra
###     source: /home/user
###     type: disk
### ephemeral: false
###
### Note that the name is shown but cannot be changed

description: ""
architecture: x86_64
config:
  boot.autostart: "true"
  security.privileged: "true"
  volatile.eth0.hwaddr: 00:16:3e:25:xx:xx
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: macvlan
    parent: cad
    type: nic
ephemeral: false
profiles:
- default
stateful: false
```
Container that works /etc/network/interfaces
```
### Cad network ####
auto eth0
iface eth0 inet static
  address 10.x.x.x
  gateway 10.x.x.x
  netmask 255.255.x.x
  dns-nameservers 10.x.x.x 10.x.x.x
  dns-search example.com
```
Container that doesn't work because it uses the same network, not a vlan.
```
  GNU nano 2.5.3          File: /tmp/lxd_editor_111566153.yaml                          

### This is a yaml representation of the configuration.
### Any line starting with a '# will be ignored.
###
### A sample configuration looks like:
### name: container1
### profiles:
### - default
### config:
###   volatile.eth0.hwaddr: 00:16:3e:e9:xx:xx
### devices:
###   homedir:
###     path: /extra
###     source: /home/user
###     type: disk
### ephemeral: false
###
### Note that the name is shown but cannot be changed

description: ""
architecture: x86_64
config:
  security.privileged: "true"
  volatile.eth0.hwaddr: 00:16:3e:25:xx:xx
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: macvlan
    parent: standard
    type: nic
ephemeral: false
profiles:
- default
stateful: false
```
Container that doesn't work 
```

#### Device Network Setup ######
auto eth0
iface eth0 inet static
        address 172.x.x.x
        netmask 255.255.x.x
        network 172.x.x.x
        broadcast 172.x.x.x
        gateway 172.x.x.x
        dns-nameservers 10.x.x.x
        dns-search example.com
```                           
Thanks for any guidance.

**Comment by stgraber** [comment]
So I think you're simply hitting the usual macvlan limitation where a container cannot talk to its host when using macvlan.

Since all your devices are actually bridges, you could simply change the "macvlan" nictype for "bridged" and things should work just fine.

**Comment by mheroux2** [comment]
I made that change and the VLAN containers that were working before are still working. However, no change with the container that doesn't operate on the VLAN, the 

The container that doesn't work operates on the 172.16.x.x network whereas the other containers use the "cad" VLAN. which connects to the 10.1.x.x network. The host machine is on the 172.16 network. Therefore, I would imagine it would use a bridge instead of a VLAN in the /etc/network/interfaces
```

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto standard
iface standard inet static
        address 172.16.x.x
        netmask 255.255.x.x
        network 172.16.x.x
        broadcast 172.16.x.x
        dns-nameservers 10.1.x.x 10.1.x.x 10.2.x.x
        dns-search example.com
        bridge_ports eno1
        post-up route add default gw 172.16.x.x
        pre-down route del default

auto br0
iface br0 inet manual
        bridge-ifaces eno1
        bridge-ports eno1
        ip link set eno1 up
        bridge_ports eno1

auto vlan2
iface vlan2 inet manual
        address 0.0.0.0
        vlan-raw-device eno1

auto cad
        iface cad  inet manual
        address 0.0.0.0
        bridge_ports vlan2

auto vlan3
iface vlan3 inet manual
       address 0.0.0.0
       vlan-raw-device eno1

auto admin
        iface admin   inet manual
        address 0.0.0.0
        bridge_ports vlan
```
And updated the containers config according
```

  GNU nano 2.5.3                                          File: /tmp/lxd_editor_107924994.yaml                                                                                           

### This is a yaml representation of the configuration.
### Any line starting with a '# will be ignored.
###
### A sample configuration looks like:
### name: container1
### profiles:
### - default
### config:
###   volatile.eth0.hwaddr: 00:16:3e:e9:f8:7f
### devices:
###   homedir:
###     path: /extra
###     source: /home/user
###     type: disk
### ephemeral: false
###
### Note that the name is shown but cannot be changed

description: ""
architecture: x86_64
config:
  security.privileged: "true"
  volatile.eth0.hwaddr: 00:16:3e:25:xx:xx
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
ephemeral: false
profiles:
- default
stateful: false
```
container's /etc/network/interfaces
```
#### Device Network Setup ######
auto eth0
iface eth0 inet static
        address 172.16.x.x
        netmask 255.255.x.x
        network 172.16.x.x
        broadcast 172.16.x.x
        gateway 172.16.x.x
        dns-nameservers 10.1.x.x
        dns-search example.com                                                                                                                                                                                                                    
```

Yet still container "c" is the only one not getting an IP address. 
+-----------------+---------+-------------------+------+------------+-----------+
|      NAME       |  STATE  |       IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
+-----------------+---------+-------------------+------+------------+-----------+
| a       | RUNNING | 10.1.x.x (eth0) |      | PERSISTENT | 0         |
+-----------------+---------+-------------------+------+------------+-----------+
| b       | RUNNING | 10.1.x.x (eth0) |      | PERSISTENT | 0         |
+-----------------+---------+-------------------+------+------------+-----------+
| c         | RUNNING |                   |      | PERSISTENT | 0         |
+-----------------+---------+-------------------+------+------------+-----------+
