### ISSUE TITLE
Cannot run KVM inside privileged container with KVM device exposed

### ISSUE THREAD

**Issue by ajthemacboy** [lxc/lxd#3393]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.04
 * LXC version: 2.14 from the upstream repo: https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/lxd-stable
 * The output of "lxc info": https://gist.github.com/ajthemacboy/ff567997f23d47fa08c16d915d7e9a1c

# Issue description

I have created a LXC container, set `security.nesting` and `security.privileged` true, and added `/dev/kvm` with `lxc config device add kvmbox kvm unix-char path=/dev/kvm`. Here is the output of `lxc info`:
```
root@corehub:~# lxc config show kvmbox
description: ""
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 17.04 amd64 (daily) (20170608)
  image.label: daily
  image.os: ubuntu
  image.release: zesty
  image.serial: "20170608"
  image.version: "17.04"
  security.nesting: "true"
  security.privileged: "true"
  volatile.base_image: 6368d66247bbf9283642c2f8ef9310ea3c51ba8dd19a9ecc493bf22cc1931008
  volatile.eth0.hwaddr: 00:16:3e:99:e5:5a
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  kvm:
    path: /dev/kvm
    type: unix-char
  root:
    path: /
    pool: pool2
    type: disk
ephemeral: false
profiles:
- default
stateful: false
```
And the output of `lxc info`: 
```
root@corehub:~# lxc info kvmbox
Name: kvmbox
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/06/08 16:29 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 52009
Ips:
  eth0: inet    10.10.0.150     vethR5H8K7
  eth0: inet6   fe80::216:3eff:fe99:e55a        vethR5H8K7
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
  virbr0:       inet    192.168.122.1
Resources:
  Processes: 55
  CPU usage:
    CPU usage (in seconds): 11
  Memory usage:
    Memory (current): 141.50MB
    Memory (peak): 151.03MB
  Network usage:
    virbr0-nic:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    eth0:
      Bytes received: 177.37kB
      Bytes sent: 256.76kB
      Packets received: 1339
      Packets sent: 761
    lo:
      Bytes received: 504B
      Bytes sent: 504B
      Packets received: 6
      Packets sent: 6
    virbr0:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
```
And the output of `kvm-ok`:
```
root@corehub:~# lxc exec kvmbox bash
root@kvmbox:~# kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used
```
I have enabled SSH to the container and connected to it with `virt-manager`. When I attempt to create a basic virtual machine, with no extra devices enabled, and the CPU set to "Copy CPU host configuration", `virt-manager` has this error:
```
Unable to complete install: 'internal error: process exited while connecting to monitor: Could not access KVM kernel module: Permission denied
failed to initialize KVM: Permission denied'

[snipped trakeback]
libvirtError: internal error: process exited while connecting to monitor: Could not access KVM kernel module: Permission denied
failed to initialize KVM: Permission denied
```
According to the information from https://github.com/lxc/lxd/issues/2718, I've done everything I need to do for KVM to work inside a container, but it does not.

How can I fix this error?
