### ISSUE TITLE
Cannot start unprivileged nested container

### ISSUE THREAD

**Issue by vwvol** [lxc/lxd#3430]
# Required information

 * Distribution: Debian
 * Distribution version: 9.0
 * The output of "lxc info" or if that fails:
```
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.9.0-3-amd64
  server: lxd
  server_pid: 473
  server_version: "2.14"
  storage: dir
  storage_version: "1"
```

# Issue description

Cannot start unprivileged container inside unprivileged container.
And I'm not sure is it a misconfiguration or an issue.

# Steps to reproduce
```
# echo 'root:65536:2000000' > /etc/subuid
# echo 'root:65536:2000000' > /etc/subgid

# lxc init images:debian/stretch nest -c security.nesting=true
# lxc start nest

# lxc exec nest -- mkdir /usr/lib/lxd
# lxc exec nest -- mkdir /var/lib/lxd
# lxc exec nest -- groupadd lxd
# lxc exec nest -- mkdir /var/log/lxd
# lxc exec nest -- chmod 740 /var/log/lxd
# lxc exec nest -- touch /var/log/lxd/lxd.log
# lxc exec nest -- apt-get update
# lxc exec nest -- apt-get install apparmor acl btrfs-tools lxc-dev squashfs-tools -y
# lxc exec nest -- sh -c "echo 'root:65536:1934464' > /etc/subuid"
# lxc exec nest -- sh -c "echo 'root:65536:1934464' > /etc/subgid"

# lxc file push lxd/lxd nest/usr/bin/lxd
# lxc file push lxd/lxc nest/usr/bin/lxc
# lxc file push lxd/lxd.service nest/lib/systemd/system/lxd.service
# lxc file push lxd/lxd-containers.service nest/lib/systemd/system/lxd-containers.service
# lxc file push lxd/lxd.socket nest/lib/systemd/system/lxd.socket
# lxc file push lxd/shutdown nest/usr/lib/lxd/shutdown

# lxc exec nest -- systemctl enable lxd.service
# lxc exec nest -- systemctl start lxd.service

# lxc exec nest -- lxd init # creating dir storage and ipv4 bridge

# lxc exec nest -- lxc init images:debian/stretch c1
# lxc exec nest -- lxc start c1
error: Failed to run: /usr/bin/lxd forkstart c1 /var/lib/lxd/containers /var/log/lxd/c1/lxc.conf
Try `lxc info --show-log c1` for more info
```

# Information to attach

- `lxc info` output on host ([host_lxc_info.txt](https://github.com/lxc/lxd/files/1090951/host_lxc_info.txt))
- `lxc info` output on `nest` contained ([nest_lxc_info.txt](https://github.com/lxc/lxd/files/1090955/nest_lxc_info.txt))
- `/var/log/lxd/lxd.log` from host ([host_lxd_log.txt](https://github.com/lxc/lxd/files/1090952/host_lxd_log.txt))
- `/var/log/lxd/lxd.log` from `nest` container ([nest_lxd_log.txt](https://github.com/lxc/lxd/files/1090954/nest_lxd_log.txt))
- `lxc info --show-log c1` output ([lxc_info_show_log_c1.txt](https://github.com/lxc/lxd/files/1090953/lxc_info_show_log_c1.txt))

**Comment by stgraber** [comment]
Do you have newuidmap and newgidmap in your container?

**Comment by stgraber** [comment]
@brauner does that ring a bell?

**Comment by vwvol** [comment]
@stgraber yes, I have both of them in my container.

**Comment by stgraber** [comment]
Can you paste (all from inside the container):
 - lxc config show --expanded c1
 - ls -lh $(which newuidmap)
 - ls -lh $(which newgidmap)

**Comment by vwvol** [comment]
Sure
```
# lxc exec nest -- lxc config show --expanded c1
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Debian stretch amd64 (20170504_02:41)
  image.os: Debian
  image.release: stretch
  image.serial: "20170504_02:41"
  volatile.base_image: 93e45634460fcd6d8107a2d9ddfb06dba18634d134ac26819af74b33d31add11
  volatile.eth0.hwaddr: 00:16:3e:96:f5:ef
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":65536,"Nsid":0,"Maprange":1934464},{"Isuid":false,"Isgid":true,"Hostid":65536,"Nsid":0,"Maprange":1934464}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":65536,"Nsid":0,"Maprange":1934464},{"Isuid":false,"Isgid":true,"Hostid":65536,"Nsid":0,"Maprange":1934464}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

```
# lxc exec nest -- ls -lh $(which newuidmap)
-rwsr-xr-x 1 root root 37K May 17 14:59 /usr/bin/newuidmap
```

```
# lxc exec nest -- ls -lh $(which newgidmap)
-rwsr-xr-x 1 root root 37K May 17 14:59 /usr/bin/newgidmap
```
