### ISSUE TITLE
How do we lxd import? Instructions are extremely unclear

### ISSUE THREAD

**Issue by akarelas** [lxc/lxd#3479]
I use Ubuntu 16.04, and all i got for importing instructions was the help screen when I type just: lxd import

To test this feature, I had already done a backup of a container from the containers directory, with zfs send | zfs receive.

Then I targz-ed the directory I sent, as root user in order to preserve file ownerships. I took it to a different machine, with a fresh install of the newest lxd (2.15) just like the source machine's lxd.

I didn't know where to untar it, because the instructions were so unclear. So I created a zfs filesystem called test-container under default/containers in the destination machine zfs pool. I untarred (as root again), and did a "mv" of the contents of the untarred directory inside the default/containers/test-container (that was the original name of the container, as well).

Then I did: lxd import test-container

and got:

root@test-vm:/# lxd import test-container
error: The container "test-container" does not seem to exist on any storage pool.

What should I do? The instructions ought to be a lot clearer than this...

**Comment by stgraber** [comment]
We have https://github.com/lxc/lxd/blob/master/doc/backup.md for that. Suggestions on how to extend that documentation would be welcome.

**Comment by akarelas** [comment]
I had read that also, and still couldn't figure out what to do.

I wish this page mentioned that all I need to backup is the container I want (and nothing else is necessary) from zfs (with zfs send, for example).

Also instructions how to restore (with zfs receive -d default).

Before that, I had my backed-up files, and I was placing them in /var/lib/lxd/containers, which was wrong... but how could I know?

After zfs receiving, I must create a link from /var/lib/lxd/containers/my-test-container to the other directory which I don't remember right now. And only then can I lxd import my container.

Also I would like to know whether the above instructions seem enough to you, or whether I will have restored only part of my container if I follow them.

Thanks for a great product!

**Comment by stgraber** [comment]
@brauner can you clarify and then update the documentation?

IIRC we only need the container to be restored in /var/lib/lxd/storage-pools/... with LXD re-creating the symlink in /var/lib/lxd/containers, but maybe I'm wrong and we have a bug :)

**Comment by akarelas** [comment]
lxd import doesn't recreate the bug. Also mention fuidshift of lxd-tools (ubuntu package), as it might be needed after a backup restore operation.

**Comment by stgraber** [comment]
fuidshift shouldn't be needed when using "lxd import" as the container's id map is part of backup.yaml, letting LXD do the remapping on container start.

**Comment by stgraber** [comment]
So assuming that you're using ZFS and have backed up the container with send/receive. You should:
 - Ensure that there are no containers with the same name in your LXD
 - Cleanup any manual restore attempt you may have done such as a direct restore in /var/lib/lxd/containers or leftover files for your container in /var/lib/lxd/storage-pools/
 - Do your "zfs receive" to recreate the ZFS filesystem for the container
 - Ensure that the mountpoint property for that filesystem is /var/lib/lxd/storage-pools/POOL/containers/NAME where POOL is the storage pool name as reported by "lxc storage list" and NAME is the name of your container (and must match the ZFS filesystem)
 - Mount the ZFS filesystem "zfs mount <filesystem>"
 - Run "lxd import NAME" where NAME is the container's name

**Comment by stgraber** [comment]
If that all works and the container fails to start, then please post the error as well as "lxc config show --expanded NAME". It could well be that LXD doesn't recalculate the map on "lxd import", if that's the case, there is a very simple trick to force LXD to do so, which should unstick things.

**Comment by akarelas** [comment]
I followed your steps (all of them as root). Here's the result: When I typed lxd import test-container, I got:

```
error: open /var/lib/lxd/containers/test-container/backup.yaml: no such file or directory
```

which I *believe* means I need to do ln -s from there to there.

I did that, and ran import again. It ran. Now I'm doing start and exec bash. Oops, problem!

```
root@test-vm:~# lxc exec test-container bash
bash: /root/.bashrc: Permission denied
root@test-container:/# ls -al
total 34
drwxr-xr-x  22 nobody nogroup  22 Jun 19 23:52 .
drwxr-xr-x  22 nobody nogroup  22 Jun 19 23:52 ..
drwxr-xr-x   2 nobody nogroup 173 Jul  2 04:41 bin
drwxr-xr-x   3 nobody nogroup   3 Jun 19 23:52 boot
drwxr-xr-x   9 root   root    500 Jul  2 19:41 dev
drwxr-xr-x  92 nobody nogroup 182 Jul  2 04:44 etc
drwxr-xr-x   3 nobody nogroup   3 Jul  2 04:37 home
drwxr-xr-x  20 nobody nogroup  24 Jul  2 04:44 lib
drwxr-xr-x   2 nobody nogroup   3 Jun 19 23:49 lib64
drwxr-xr-x   2 nobody nogroup   2 Jun 19 23:49 media
drwxr-xr-x   2 nobody nogroup   2 Jun 19 23:49 mnt
drwxr-xr-x   2 nobody nogroup   2 Jun 19 23:49 opt
dr-xr-xr-x 875 nobody nogroup   0 Jul  2 19:41 proc
drwx------   3 nobody nogroup   8 Jul  2 04:43 root
drwxr-xr-x  18 root   root    680 Jul  2 19:42 run
drwxr-xr-x   2 nobody nogroup 236 Jul  2 04:44 sbin
drwxr-xr-x   2 nobody nogroup   2 Apr 29 08:38 snap
drwxr-xr-x   2 nobody nogroup   2 Jun 19 23:49 srv
dr-xr-xr-x  13 nobody nogroup   0 Jul  2 19:14 sys
drwxrwxrwt   7 nobody nogroup   7 Jul  2 19:27 tmp
drwxr-xr-x  10 nobody nogroup  10 Jun 19 23:49 usr
drwxr-xr-x  13 nobody nogroup  15 Jun 19 23:52 var
```

**Comment by akarelas** [comment]
What trick do you have to suggest to me? Couldn't you have it do it automatically, without trick?

**Comment by stgraber** [comment]
You didn't provide the "lxc config show" I asked above.

**Comment by stgraber** [comment]
As for the need to make the symlink, yes, that shouldn't be needed as LXD should be able to locate the container in /var/lib/lxd/storage-pools. @brauner I thought you fixed that one?

**Comment by stgraber** [comment]
Can you also provide the following from your ZFS backup filesystem, before running a "lxd import":
 - ls -lh /var/lib/lxd/storage-pools/default/containers/test-container/rootfs/
 - cat /var/lib/lxd/storage-pools/default/containers/test-container/backup.yaml

**Comment by brauner** [comment]
@stgraber, symlinks are not needed for import to work.

**Comment by stgraber** [comment]
@brauner Any idea what cause the error above?
```
error: open /var/lib/lxd/containers/test-container/backup.yaml: no such file or directory
```

**Comment by brauner** [comment]
I want to see the output of `lxc info`.

**Comment by brauner** [comment]
I see one potential problem in the code.

**Comment by akarelas** [comment]
```
karjala@test-vm:~$ lxc config show --expanded test-container
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20170619.1)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20170619.1"
  image.version: "16.04"
  volatile.base_image: 7a7ff654cbd8f5f09bec03aa19d8d7d92649127d18659036a963b1ea63f90d25
  volatile.eth0.hwaddr: 00:16:3e:67:10:f9
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
karjala@test-vm:~$ 
```

More answers coming soon...

**Comment by akarelas** [comment]
```
root@alex-latitude:~# zfs receive -d -n -v backup-white-cyprus/stephan-demo <~karjala/test.stream
would receive full stream of default/containers/test-container@snapshot-snap0 into backup-white-cyprus/stephan-demo/containers/test-container@snapshot-snap0
root@alex-latitude:~# zfs receive -d backup-white-cyprus/stephan-demo <~karjala/test.stream
root@alex-latitude:~# zfs set mountpoint=/here-the-good-containers backup-white-cyprus/stephan-demo/containers/test-container

...

root@alex-latitude:/here-the-good-containers# cat backup.yaml 
container:
  architecture: x86_64
  config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170619.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170619.1"
    image.version: "16.04"
    volatile.base_image: 7a7ff654cbd8f5f09bec03aa19d8d7d92649127d18659036a963b1ea63f90d25
    volatile.eth0.hwaddr: 00:16:3e:3e:10:0f
    volatile.eth0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
    volatile.last_state.power: STOPPED
  devices: {}
  ephemeral: false
  profiles:
  - default
  stateful: false
  description: ""
  created_at: 2017-07-02T04:36:58Z
  expanded_config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170619.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170619.1"
    image.version: "16.04"
    volatile.base_image: 7a7ff654cbd8f5f09bec03aa19d8d7d92649127d18659036a963b1ea63f90d25
    volatile.eth0.hwaddr: 00:16:3e:3e:10:0f
    volatile.eth0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
    volatile.last_state.power: STOPPED
  expanded_devices:
    eth0:
      nictype: bridged
      parent: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: test-container
  status: Stopped
  status_code: 102
  last_used_at: 2017-07-02T16:11:10.271550129Z
snapshots: []
pool:
  config:
    size: 50GB
    source: /var/lib/lxd/disks/default.img
    zfs.pool_name: default
  description: ""
  name: default
  driver: zfs
  used_by: []
volume:
  config: {}
  description: ""
  name: test-container
  type: container
  used_by: []

root@alex-latitude:/here-the-good-containers# ls -al
total 14
drwxr-xr-x  4 165536 165536    6 Ιούλ  2 07:37 .
drwxr-xr-x 26 root   root   4096 Ιούλ  2 23:32 ..
-r--------  1 root   root   2336 Ιούλ  2 22:27 backup.yaml
-rw-r--r--  1 root   root   1568 Ιούν 20 04:03 metadata.yaml
drwxr-xr-x 22 165536 165536   22 Ιούν 20 02:52 rootfs
drwxr-xr-x  2 root   root      8 Ιούν 20 04:03 templates
root@alex-latitude:/here-the-good-containers# ls -alh rootfs/
total 39K
drwxr-xr-x 22 165536 165536  22 Ιούν 20 02:52 .
drwxr-xr-x  4 165536 165536   6 Ιούλ  2 07:37 ..
drwxr-xr-x  2 165536 165536 173 Ιούλ  2 07:41 bin
drwxr-xr-x  3 165536 165536   3 Ιούν 20 02:52 boot
drwxr-xr-x  5 165536 165536  91 Ιούν 20 02:51 dev
drwxr-xr-x 92 165536 165536 182 Ιούλ  2 07:44 etc
drwxr-xr-x  3 165536 165536   3 Ιούλ  2 07:37 home
drwxr-xr-x 20 165536 165536  24 Ιούλ  2 07:44 lib
drwxr-xr-x  2 165536 165536   3 Ιούν 20 02:49 lib64
drwxr-xr-x  2 165536 165536   2 Ιούν 20 02:49 media
drwxr-xr-x  2 165536 165536   2 Ιούν 20 02:49 mnt
drwxr-xr-x  2 165536 165536   2 Ιούν 20 02:49 opt
drwxr-xr-x  2 165536 165536   2 Απρ  12  2016 proc
drwx------  3 165536 165536   8 Ιούλ  2 07:43 root
drwxr-xr-x  3 165536 165536   3 Ιούν 20 02:51 run
drwxr-xr-x  2 165536 165536 236 Ιούλ  2 07:44 sbin
drwxr-xr-x  2 165536 165536   2 Απρ  29 11:38 snap
drwxr-xr-x  2 165536 165536   2 Ιούν 20 02:49 srv
drwxr-xr-x  2 165536 165536   2 Φεβ   5  2016 sys
drwxrwxrwt  7 165536 165536   7 Ιούλ  2 22:27 tmp
drwxr-xr-x 10 165536 165536  10 Ιούν 20 02:49 usr
drwxr-xr-x 13 165536 165536  15 Ιούν 20 02:52 var

This is my ZFS backup filesystem, as you asked. It's not attached to a LXD system at all.

Since I'm not sure that's you wanted (the directories were different in your question), I'm repeating these steps in the RESTORE lxd machine, just before the lxd import command.

root@test-vm:/var/lib/lxd/storage-pools/default/containers/test-container# ls -al
total 11
drwxr-xr-x  4 165536 165536    6 Jul  2 07:37 .
drwxr-xr-x  3 root   root   4096 Jul  2 23:41 ..
-r--------  1 root   root   2336 Jul  2 22:27 backup.yaml
-rw-r--r--  1 root   root   1568 Jun 20 04:03 metadata.yaml
drwxr-xr-x 22 165536 165536   22 Jun 20 02:52 rootfs
drwxr-xr-x  2 root   root      8 Jun 20 04:03 templates

root@test-vm:/var/lib/lxd/storage-pools/default/containers/test-container# ls -al rootfs/
total 39
drwxr-xr-x 22 165536 165536  22 Jun 20 02:52 .
drwxr-xr-x  4 165536 165536   6 Jul  2 07:37 ..
drwxr-xr-x  2 165536 165536 173 Jul  2 07:41 bin
drwxr-xr-x  3 165536 165536   3 Jun 20 02:52 boot
drwxr-xr-x  5 165536 165536  91 Jun 20 02:51 dev
drwxr-xr-x 92 165536 165536 182 Jul  2 07:44 etc
drwxr-xr-x  3 165536 165536   3 Jul  2 07:37 home
drwxr-xr-x 20 165536 165536  24 Jul  2 07:44 lib
drwxr-xr-x  2 165536 165536   3 Jun 20 02:49 lib64
drwxr-xr-x  2 165536 165536   2 Jun 20 02:49 media
drwxr-xr-x  2 165536 165536   2 Jun 20 02:49 mnt
drwxr-xr-x  2 165536 165536   2 Jun 20 02:49 opt
drwxr-xr-x  2 165536 165536   2 Apr 12  2016 proc
drwx------  3 165536 165536   8 Jul  2 07:43 root
drwxr-xr-x  3 165536 165536   3 Jun 20 02:51 run
drwxr-xr-x  2 165536 165536 236 Jul  2 07:44 sbin
drwxr-xr-x  2 165536 165536   2 Apr 29 11:38 snap
drwxr-xr-x  2 165536 165536   2 Jun 20 02:49 srv
drwxr-xr-x  2 165536 165536   2 Feb  5  2016 sys
drwxrwxrwt  7 165536 165536   7 Jul  2 22:27 tmp
drwxr-xr-x 10 165536 165536  10 Jun 20 02:49 usr
drwxr-xr-x 13 165536 165536  15 Jun 20 02:52 var

root@test-vm:/var/lib/lxd/storage-pools/default/containers/test-container# cat backup.yaml 
container:
  architecture: x86_64
  config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170619.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170619.1"
    image.version: "16.04"
    volatile.base_image: 7a7ff654cbd8f5f09bec03aa19d8d7d92649127d18659036a963b1ea63f90d25
    volatile.eth0.hwaddr: 00:16:3e:3e:10:0f
    volatile.eth0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
    volatile.last_state.power: STOPPED
  devices: {}
  ephemeral: false
  profiles:
  - default
  stateful: false
  description: ""
  created_at: 2017-07-02T04:36:58Z
  expanded_config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170619.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170619.1"
    image.version: "16.04"
    volatile.base_image: 7a7ff654cbd8f5f09bec03aa19d8d7d92649127d18659036a963b1ea63f90d25
    volatile.eth0.hwaddr: 00:16:3e:3e:10:0f
    volatile.eth0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
    volatile.last_state.power: STOPPED
  expanded_devices:
    eth0:
      nictype: bridged
      parent: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: test-container
  status: Stopped
  status_code: 102
  last_used_at: 2017-07-02T16:11:10.271550129Z
snapshots: []
pool:
  config:
    size: 50GB
    source: /var/lib/lxd/disks/default.img
    zfs.pool_name: default
  description: ""
  name: default
  driver: zfs
  used_by: []
volume:
  config: {}
  description: ""
  name: test-container
  type: container
  used_by: []

**Comment by akarelas** [comment]
root@test-vm:~# lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
secret
    -----END CERTIFICATE-----
  certificate_fingerprint: .........................secret.............
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-83-generic
  server: lxd
  server_pid: 3707
  server_version: "2.15"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu16

**Comment by stgraber** [comment]
Thanks, so the backup looks good with the right ownership on files which matches what's in backup.yaml.

Can you now create the symlink in /var/lib/lxd/containers/ and then run "lxd import test-container" but don't start the container after that. Instead, post:
 - ls -lh /var/lib/lxd/storage-pools/default/containers/test-container/rootfs/
 - lxc config show --expanded test-container

That should let me figure out exactly what LXD is going to do when you do start the container and see why you'd then end up with broken uid/gid.

**Comment by akarelas** [comment]
```
root@test-vm:/var/lib/lxd/containers# ls -lh /var/lib/lxd/storage-pools/default/containers/test-container/rootfs/
total 36K
drwxr-xr-x  2 165536 165536 173 Jul  2 07:41 bin
drwxr-xr-x  3 165536 165536   3 Jun 20 02:52 boot
drwxr-xr-x  5 165536 165536  91 Jun 20 02:51 dev
drwxr-xr-x 92 165536 165536 182 Jul  2 07:44 etc
drwxr-xr-x  3 165536 165536   3 Jul  2 07:37 home
drwxr-xr-x 20 165536 165536  24 Jul  2 07:44 lib
drwxr-xr-x  2 165536 165536   3 Jun 20 02:49 lib64
drwxr-xr-x  2 165536 165536   2 Jun 20 02:49 media
drwxr-xr-x  2 165536 165536   2 Jun 20 02:49 mnt
drwxr-xr-x  2 165536 165536   2 Jun 20 02:49 opt
drwxr-xr-x  2 165536 165536   2 Apr 12  2016 proc
drwx------  3 165536 165536   8 Jul  2 07:43 root
drwxr-xr-x  3 165536 165536   3 Jun 20 02:51 run
drwxr-xr-x  2 165536 165536 236 Jul  2 07:44 sbin
drwxr-xr-x  2 165536 165536   2 Apr 29 11:38 snap
drwxr-xr-x  2 165536 165536   2 Jun 20 02:49 srv
drwxr-xr-x  2 165536 165536   2 Feb  5  2016 sys
drwxrwxrwt  7 165536 165536   7 Jul  2 22:27 tmp
drwxr-xr-x 10 165536 165536  10 Jun 20 02:49 usr
drwxr-xr-x 13 165536 165536  15 Jun 20 02:52 var
```

```
root@test-vm:/var/lib/lxd/containers# lxc config show --expanded test-container
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20170619.1)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20170619.1"
  image.version: "16.04"
  volatile.base_image: 7a7ff654cbd8f5f09bec03aa19d8d7d92649127d18659036a963b1ea63f90d25
  volatile.eth0.hwaddr: 00:16:3e:e7:3f:1e
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

I haven't started the container yet.
