### ISSUE TITLE
I/O disk limits on mdadm RAID virtual devices

### ISSUE THREAD

**Issue by ogai** [lxc/lxd#3515]
When having 2 disks on a mdadm RAID 1 array, a configuration very common on server hosters like [hetzner.de](https://www.hetzner.de/), I/O limiting the disk of a container has no effect.

Add extra code to track down backing devices for mdadm RAID.

This issue has been discussed on https://discuss.linuxcontainers.org/t/limiting-disk-io-on-lxd-containers/261/7

**Comment by stgraber** [comment]
So actually, I just tried this here and things appear to work with md0 as the backing device.
My setup:
 - /dev/vda2 and /dev/vda3 as /dev/md0 using raid1
 - /dev/md0 mounted on /var/lib/lxd
 - containers using the "dir" storage backend
 - container c1 with root disk device using limits.read=1MB and limits.write=1MB

```
~ # time dd if=/dev/zero of=test.img bs=4M count=10 conv=fsync
10+0 records in
10+0 records out
real	0m 40.36s
user	0m 0.00s
sys	0m 0.04s
```

So that's giving me exactly my 1MB/s of write speed using current LXD 2.15.


```
root@vm02:~# lxc config show c1
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Alpine edge amd64 (20170710_01:44)
  image.os: Alpine
  image.release: edge
  image.serial: "20170710_01:44"
  volatile.base_image: 5834296d2606bd4f6f5a58ab3bc40928aa4e853b800ab5f7fd143bd8fc162380
  volatile.eth0.hwaddr: 00:16:3e:e0:99:87
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  root:
    limits.read: 1MB
    limits.write: 1MB
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

```
root@vm02:~# cat /proc/mdstat 
Personalities : [linear] [multipath] [raid0] [raid1] [raid6] [raid5] [raid4] [raid10] 
md0 : active raid1 vda3[1] vda2[0]
      14639104 blocks super 1.2 [2/2] [UU]
```

```
root@vm02:~# cat /var/log/lxd/c1/lxc.conf 
lxc.cap.drop = sys_time sys_module sys_rawio
lxc.mount.auto = proc:rw sys:rw
lxc.autodev = 1
lxc.pts = 1024
lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file,optional
lxc.mount.entry = /dev/net/tun dev/net/tun none bind,create=file,optional
lxc.mount.entry = /proc/sys/fs/binfmt_misc proc/sys/fs/binfmt_misc none rbind,create=dir,optional
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none rbind,create=dir,optional
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none rbind,create=dir,optional
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none rbind,create=dir,optional
lxc.mount.entry = /sys/kernel/security sys/kernel/security none rbind,create=dir,optional
lxc.mount.entry = /dev/mqueue dev/mqueue none rbind,create=dir,optional
lxc.include = /usr/share/lxc/config/common.conf.d/
lxc.logfile = /var/log/lxd/c1/lxc.log
lxc.loglevel = trace
lxc.arch = linux64
lxc.hook.pre-start = /usr/bin/lxd callhook /var/lib/lxd 1 start
lxc.hook.post-stop = /usr/bin/lxd callhook /var/lib/lxd 1 stop
lxc.tty = 0
lxc.utsname = c1
lxc.mount.entry = /var/lib/lxd/devlxd dev/lxd none bind,create=dir 0 0
lxc.aa_profile = lxd-c1_</var/lib/lxd>//&:lxd-c1_<var-lib-lxd>:
lxc.seccomp = /var/lib/lxd/security/seccomp/c1
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
lxc.cgroup.blkio.throttle.read_bps_device = 9:0 1048576
lxc.cgroup.blkio.throttle.write_bps_device = 9:0 1048576
lxc.network.0.type = veth
lxc.network.0.flags = up
lxc.network.0.link = lxdbr0
lxc.network.0.hwaddr = 00:16:3e:e0:99:87
lxc.network.0.name = eth0
lxc.rootfs.backend = dir
lxc.rootfs = /var/lib/lxd/containers/c1/rootfs
lxc.mount.entry = /var/lib/lxd/shmounts/c1 dev/.lxd-mounts none bind,create=dir 0 0
```

```
root@vm02:~# cat /sys/fs/cgroup/blkio/lxc/c1/blkio.throttle.read_bps_device
9:0 1048576
root@vm02:~# cat /sys/fs/cgroup/blkio/lxc/c1/blkio.throttle.write_bps_device
9:0 1048576
```
