### ISSUE TITLE
IO Limits not working on zfs pool

### ISSUE THREAD

**Issue by wociscz** [lxc/lxd#3524]
Hi, just trying some limiting of containers. I have containers on zfs mirrored pool (created manually, not via lxd init) with two physical drives.
Created with simple `zpool create zfs mirror sdb sdc`

zpool status zfs
```
  pool: zfs
 state: ONLINE
  scan: scrub repaired 0 in 0h2m with 0 errors on Sun Jul  9 00:26:50 2017
config:

	NAME        STATE     READ WRITE CKSUM
	zfs         ONLINE       0     0     0
	  mirror-0  ONLINE       0     0     0
	    sdb     ONLINE       0     0     0
	    sdc     ONLINE       0     0     0

errors: No known data errors
```
zfs list
```
NAME                                                                          USED  AVAIL  REFER  MOUNTPOINT
zfs                                                                          21.6G  1.73T    19K  /zfs
zfs/containers                                                               17.7G  1.73T    19K  none
zfs/containers/logger-67                                                     17.7G  2.30G  17.7G  /var/lib/lxd/storage-pools/default/containers/logger-67
zfs/containers/master-67                                                     35.1M  20.0G   549M  /var/lib/lxd/storage-pools/default/containers/master-67
zfs/custom                                                                     19K  1.73T    19K  none
zfs/deleted                                                                    19K  1.73T    19K  none
zfs/images                                                                   3.83G  1.73T    19K  none
zfs/images/001d4b031b4e66c3e996885fe23223d73edcc36161f792a7ae5942822f366df0   496M  1.73T   496M  none
zfs/images/44022e76724b4baced6b6ad8d997b9e366147609f316fe4a0168de8171cc7f76   515M  1.73T   515M  none
zfs/images/584db839344bf0111dd63ae199e97684c9aba4e225cea9e1474b3951efa070c8   515M  1.73T   515M  none
zfs/images/80ae1d7015bfecab107a71aaf2fd2710875dabfd26947101181f32180140153e   515M  1.73T   515M  none
zfs/images/8b8136757d6da99266712d5d52e37b693f3f7ffc54cf23d486f1cab024dad44f   458M  1.73T   458M  none
zfs/images/900498fe0a6a52ffc51a25aae61755beb54f8da4c00873114b9e682809ece13f   482M  1.73T   482M  none
zfs/images/a3ec935cee7c4ac781c07618eb9bfcfaddfa573d8f82e988085333a8578013e3   457M  1.73T   457M  none
zfs/images/e3cea4f350c8f84177da5a45664f152b9ff07a3eeab9053e391e6bf6b063f4b1   482M  1.73T   482M  none
zfs/snapshots                                                                  38K  1.73T    19K  none
zfs/snapshots/logger-67                                                        19K  1.73T    19K  none
```
lxc storage list
```
+---------+-------------+--------+--------+---------+
|  NAME   | DESCRIPTION | DRIVER | SOURCE | USED BY |
+---------+-------------+--------+--------+---------+
| default |             | zfs    | zfs    | 14      |
+---------+-------------+--------+--------+---------+
```
lxc storage show default
```
config:
  source: zfs
  zfs.pool_name: zfs
description: ""
name: default
driver: zfs
used_by:
- /1.0/containers/logger-67
- /1.0/containers/logger-67/snapshots/postpandora
- /1.0/containers/master-67
- /1.0/images/001d4b031b4e66c3e996885fe23223d73edcc36161f792a7ae5942822f366df0
- /1.0/images/44022e76724b4baced6b6ad8d997b9e366147609f316fe4a0168de8171cc7f76
- /1.0/images/584db839344bf0111dd63ae199e97684c9aba4e225cea9e1474b3951efa070c8
- /1.0/images/80ae1d7015bfecab107a71aaf2fd2710875dabfd26947101181f32180140153e
- /1.0/images/8b8136757d6da99266712d5d52e37b693f3f7ffc54cf23d486f1cab024dad44f
- /1.0/images/900498fe0a6a52ffc51a25aae61755beb54f8da4c00873114b9e682809ece13f
- /1.0/images/a3ec935cee7c4ac781c07618eb9bfcfaddfa573d8f82e988085333a8578013e3
- /1.0/images/e3cea4f350c8f84177da5a45664f152b9ff07a3eeab9053e391e6bf6b063f4b1
- /1.0/profiles/app_br
- /1.0/profiles/master_br
- /1.0/profiles/privileged_br
```
profile used on master-67 (which i trying to limit io)
```
config:
  boot.autostart: "false"
  linux.kernel_modules: ip_tables, ip_vs
  security.privileged: "true"
description: Default master profile
devices:
  eth0:
    nictype: macvlan
    parent: bond0
    type: nic
  eth1:
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: master_br
used_by:
- /1.0/containers/master-67
```

after creating the master-67 i have attached root directly to container with
`lxc config device add master-67 root disk path=/ pool=default`

and set limits with
```
lxc config device set master-67 root size 20GB
lxc config device set master-67 root limits.max 1MB
```

lxc config show master-67 --expanded:
```
architecture: x86_64
config:
  boot.autostart: "false"
  image.architecture: x86_64
  image.description: master
  image.name: master-image
  image.os: ubuntu
  image.release: xenial_
  image.variant: default
  linux.kernel_modules: ip_tables, ip_vs
  security.privileged: "true"
  volatile.base_image: 584db839344bf0111dd63ae199e97684c9aba4e225cea9e1474b3951efa070c8
  volatile.eth0.hwaddr: 00:16:3e:60:a3:84
  volatile.eth0.name: eth0
  volatile.eth1.hwaddr: 00:16:3e:b7:9f:6d
  volatile.eth1.name: eth1
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: macvlan
    parent: bond0
    type: nic
  eth1:
    nictype: bridged
    parent: br0
    type: nic
  root:
    limits.max: 1MB
    limits.read: 1MB
    limits.write: 1MB
    path: /
    pool: default
    size: 20GB
    type: disk
ephemeral: false
profiles:
- master_br
stateful: false
description: ""
```

But inside container only the size limit is in action. When i try
time dd if=/dev/zero of=/testfile bs=1M count=100 conv=fsync
the results is like this (full speed of drives)
```
100+0 records in
100+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 1.27948 s, 82.0 MB/s

real	0m1.282s
user	0m0.000s
sys	0m0.080s
```
at least lxc info:
```
config:
  core.https_address: 10.250.3.4:8443
  core.trust_password: true
  images.auto_update_interval: "15"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.250.3.4:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
 --
    -----END CERTIFICATE-----
  certificate_fingerprint: 67b7999476ec25dcfbf3fab2e399f9d243a9355b1fd4c24062efbac8b6deabe7
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-26-generic
  server: lxd
  server_pid: 3808
  server_version: "2.15"
  storage: zfs
  storage_version: 0.6.5.9-2
```

lxd package versions 2.15-0ubuntu6-ubuntu16.04.1-ppa1
lxcfs 2.0.7-0ubuntu4-ubuntu16.04.1-ppa1

I have tried lvm, dir storage, btrfs and not able to make io limits work. Only the size limits.
Do i missed something in my config/setup or is it supposed to "not work" like this?
