### ISSUE TITLE
Deletion of storage pools always deletes zfs source volume

### ISSUE THREAD

**Issue by stonie08** [lxc/lxd#3657]
# Required information

 * Distribution: Debian
 * Distribution version: Stretch
 * The output of "lxc info" or if that fails:
```
architectures:
  - x86_64
  - i686
driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.9.0-3-amd64
  server: lxd
  server_version: "2.16"
  storage: zfs
  storage_version: 0.6.5.9-5

```
# Issue description
LXC storage pools can be created for existing zfs volumes like tank/volume. Unfortunately those storage pools can't be removed from LXC without deleting the zfs volume as well. Also unsetting the source as a workaround doesn't work in this case. This leads to potential data loss in case the wrong volume has been added and can't be removed from lxc but kept as a volume afterwards.

# Steps to reproduce

 0. Set up a zfs pool `tank`
 1. create a zfs volume `zfs create tank/myvolume`
 2.1 check with `zfs list`
 2. add zfs volume as lxc storage pool `lxc storage create pool1 zfs source=tank/myvolume`
 3. try to delete the lxc storage while retaining the zfs volume `lxc storage delete pool1`
 3.1 check with `zfs list`

[edit] inserted two additional steps
