### ISSUE TITLE
Problem with LXD Import

### ISSUE THREAD

**Issue by renky** [lxc/lxd#3682]
Refering to Issue #3005 

----------

lxd import doesn't work porperly on my system...
OS: Debian Stretch, LXD 2.16 (Snap)

Created a new container from scratch (ubuntu 17.04)
made some changes, created 3 Snapshots of the container (with lxc snapshot ....)
here is zft list -t all:
```
zpool1/lxd/containers/test                                                                   5.68M  1.24T   314M  /var/snap/lxd/common/lxd/storage-pools/pwhost/containers/test        
zpool1/lxd/containers/test@snapshot-erster                                                   51.6K      -   314M  -                                                                    
zpool1/lxd/containers/test@snapshot-zweiter                                                  52.4K      -   314M  -                                                                    
zpool1/lxd/containers/test@snapshot-dritter                                                      0      -   314M  -                                                           
...
...
zpool1/lxd/snapshots/test                                                                    25.4K  1.24T  25.4K  none         
```

then I made a zfs-backup:
```
zfs send -R zpool1/lxd/containers/test@snapshot-dritter > /tmp/test
```

important: i didn't save the snapshots-dataset for this container (maybe this was my failure?)

then destroyed the container:

```
lxc stop test
lxc delete test
```

zfs shows no further datasets of the container, ans no snapshots any more

then restored zfs:

```
zfs receive zpool1/lxd/containers/test < /tmp/test
``` 

worked fine, zfs list -t a shows:
```
zpool1/lxd/containers/test                                                                   5.68M  1.24T   314M  /var/snap/lxd/common/lxd/storage-pools/pwhost/containers/test        
zpool1/lxd/containers/test@snapshot-erster                                                   51.6K      -   314M  -                                                                    
zpool1/lxd/containers/test@snapshot-zweiter                                                  52.4K      -   314M  -                                                                    
zpool1/lxd/containers/test@snapshot-dritter                                                      0      -   314M  -                                                                    
```
but it doesn't show the snapshot dataset -> thats right, I didn't backup it...

then import the container
```
lxd import test
```
seems to be successful:
```
lxc list
+------------+---------+---------------------+------+------------+-----------+                                                                                                         
|    NAME    |  STATE  |        IPV4         | IPV6 |    TYPE    | SNAPSHOTS |                                                                                                         
+------------+---------+---------------------+------+------------+-----------+                                                                                                         
| test       | STOPPED |                     |      | PERSISTENT | 0         |                                                                                                         
+------------+---------+---------------------+------+------------+-----------+                                                                                                         
```
but the snapshots are missing - so lxd didn't find the really existing zfs snapshots...
and now the container cannot be startet:
```
> lxc start test
error: Failed to run: /snap/lxd/3346/bin/lxd forkstart test /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/test/lxc.conf:                                           
Try `lxc info --show-log test` for more info                                                                                                                                           

> lxc info --show-log test
Name: test                                                                                                                                                                             
Remote: unix://                                                                                                                                                                        
Architecture: x86_64                                                                                                                                                                   
Created: 2017/08/14 12:03 UTC                                                                                                                                                          
Status: Stopped                                                                                                                                                                        
Type: persistent                                                                                                                                                                       
Profiles: default                                                                                                                                                                      
                                                                                                                                                                                       
Log:                                                                                                                                                                                   
                                                                                                                                                                                       
            lxc 20170814120333.534 ERROR    lxc_conf - conf.c:run_buffer:416 - Script exited with status 1.                                                                            
            lxc 20170814120333.534 ERROR    lxc_start - start.c:lxc_init:450 - Failed to run lxc.hook.pre-start for container "test".                                                  
            lxc 20170814120333.534 ERROR    lxc_start - start.c:__lxc_start:1314 - Failed to initialize container "test".                                                              
            lxc 20170814120333.534 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.                  
```

to ensure that this is not only because of the missing snapshot-dataset, I retried it again:
with also saving zpool1/lxd/snapshots/test and restoring it...
same result: lxc list doesn't show any snapshots, and container doesn't run.

**Comment by stgraber** [comment]
Can you include the backup.yaml file that's in your zpool1/lxd/containers/test dataset?

**Comment by renky** [comment]
where is this file placed? I cant find any "backup.yaml" on my whole disk?! But I thinks it's only not mounted so that "locate" cannot find it?!

**Comment by stgraber** [comment]
It's in the zfs dataset, so yeah, it's probably just not mounted right now.

**Comment by renky** [comment]
Hmm... i don't get any files - where are the files placed?
zfs list shows me that:
```
zpool1/lxd/containers/test                                                          15.0M  1.24T   308M  /var/snap/lxd/common/lxd/storage-pools/pwhost/containers/test
```
when I try to mount the container it seems already to be mounted:
```
zfs mount zpool1/lxd/containers/test                                                                                                                                  
filesystem 'zpool1/lxd/containers/test' is already mounted 
```
but the directory is empty:
```
l /var/snap/lxd/common/lxd/storage-pools/pwhost/containers/test
total 0
```

**Comment by stgraber** [comment]
Hmm, is the container running? If so, that may be while zfs isn't letting you mount it.

What's in your /proc/self/mountinfo?

**Comment by renky** [comment]
Yes, it is running. So do i have to stop it and then mount offline?

Am 29. August 2017 19:52:57 MESZ schrieb "Stéphane Graber" <notifications@github.com>:

**Comment by renky** [comment]
ok thats it:

```
cat /var/snap/lxd/common/lxd/storage-pools/pwhost/containers/test/backup.yaml
container:
  architecture: x86_64
  config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170815.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170815.1"
    image.version: "16.04"
    volatile.base_image: 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08
    volatile.br0.hwaddr: 00:16:3e:c2:12:fe
    volatile.br0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.power: RUNNING
  devices: {}
  ephemeral: false
  profiles:
  - default
  stateful: false
  description: ""
  created_at: 2017-08-28T09:32:20Z
  expanded_config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170815.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170815.1"
    image.version: "16.04"
    volatile.base_image: 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08
    volatile.br0.hwaddr: 00:16:3e:c2:12:fe
    volatile.br0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.power: RUNNING
  expanded_devices:
    br0:
      nictype: bridged
      parent: br0
      type: nic
    root:
      path: /
      pool: pwhost
      type: disk
  name: test
  status: Running
  status_code: 103
  last_used_at: 2017-08-28T09:32:21.784359996Z
snapshots:
- architecture: x86_64
  config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170815.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170815.1"
    image.version: "16.04"
    volatile.base_image: 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08
    volatile.br0.hwaddr: 00:16:3e:c2:12:fe
    volatile.br0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.power: RUNNING
  created_at: 2017-08-28T09:33:01Z
  devices: {}
  ephemeral: false
  expanded_config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170815.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170815.1"
    image.version: "16.04"
    volatile.base_image: 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08
    volatile.br0.hwaddr: 00:16:3e:c2:12:fe
    volatile.br0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.power: RUNNING
  expanded_devices:
    br0:
      nictype: bridged
      parent: br0
      type: nic
    root:
      path: /
      pool: pwhost
      type: disk
  last_used_at: 1970-01-01T00:00:00Z
  name: test/erster
  profiles:
  - default
  stateful: false
- architecture: x86_64
  config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170815.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170815.1"
    image.version: "16.04"
    volatile.base_image: 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08
    volatile.br0.hwaddr: 00:16:3e:c2:12:fe
    volatile.br0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.power: RUNNING
  created_at: 2017-08-28T09:33:30Z
  devices: {}
  ephemeral: false
  expanded_config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170815.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170815.1"
    image.version: "16.04"
    volatile.base_image: 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08
    volatile.br0.hwaddr: 00:16:3e:c2:12:fe
    volatile.br0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.power: RUNNING
  expanded_devices:
    br0:
      nictype: bridged
      parent: br0
      type: nic
    root:
      path: /
      pool: pwhost
      type: disk
  last_used_at: 1970-01-01T00:00:00Z
  name: test/zweiter
  profiles:
  - default
  stateful: false
- architecture: x86_64
  config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170815.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170815.1"
    image.version: "16.04"
    volatile.base_image: 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08
    volatile.br0.hwaddr: 00:16:3e:c2:12:fe
    volatile.br0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.power: RUNNING
  created_at: 2017-08-28T09:33:44Z
  devices: {}
  ephemeral: false
  expanded_config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170815.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170815.1"
    image.version: "16.04"
    volatile.base_image: 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08
    volatile.br0.hwaddr: 00:16:3e:c2:12:fe
    volatile.br0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.power: RUNNING
  expanded_devices:
    br0:
      nictype: bridged
      parent: br0
      type: nic
    root:
      path: /
      pool: pwhost
      type: disk
  last_used_at: 1970-01-01T00:00:00Z
  name: test/dritter
  profiles:
  - default
  stateful: false
pool:
  config:
    source: zpool1/lxd
    volume.zfs.use_refquota: "true"
    zfs.pool_name: zpool1/lxd
  description: ""
  name: pwhost
  driver: zfs
  used_by: []
volume:
  config: {}
  description: ""
  name: test
  type: container
  used_by: []
```

**Comment by stgraber** [comment]
Cool, that should be enough to try to reproduce this. @brauner can you take a look?

**Comment by brauner** [comment]
Uhm, this smells an aweful lot like the infamous zfs EBUSY bug.

**Comment by brauner** [comment]
Oh, nm the container was running.

**Comment by brauner** [comment]
Which is still the EBUSY bug but we might be able to handle this by telling the user that {s,h}e needs to stop the container before importing.

**Comment by stgraber** [comment]
@brauner the import succeeded. The container got created and is running. The issue is that all snapshots got lost.

The reproducing steps are in the bug description. The rambling after that in comments was just to get to the backup.yaml which did indeed need to workaround the usual EBUSY issue.

**Comment by brauner** [comment]
I'm sorry, I'm still very confused. So any storage entity created under

`<pool-name>/snapshots/<name>`

is supposed to be an ephemeral entity that e.g. gets created on migration and similar things so this is not actually something that LXD is supposed to backup. Especially since it seems the author stated that he didn't back it up. The container itself seemed to have been backed up just fine including snapshots. The proper snapshots for the container are `container/<name>@snapshot-<snap-name>` not `snapshots/<name>`. What am I missing here?

**Comment by brauner** [comment]
Ah, the snapshots itself are not in the database.

**Comment by stgraber** [comment]
Right, that :)

The zfs backup and restore went fine based on this report, the snapshot information is properly contained in the backup.yaml file, yet none of the snapshots actually got created in the LXD database on import.

**Comment by brauner** [comment]
So the explanation seems straightforward:
For the import to succeed the code must have had access to the container's `backup.yaml` file at some point during the import otherwise the import would have failed right away.  My suspicion is that during the import the dataset got umounted for whatever reason (@stgraber, explanation for this?). Then our code checks for discrepancies between snapshots that exist on disk and snapshots that exist in the `backup.yaml` file. Given that the user deleted the prior container **and** exported the datasets none of the snapshot's mountpoints exist on disk anymore which LXD uses to determine what snapshots actually exist. And that's why there not in the db.

**Comment by renky** [comment]
just to clarify: the backup.yaml that i postet up was BEVORE an import... so after I didn't get the conatiner running I deleted everything and started from scratch... this current container "test" was running properly - I added 3 snapshots - but I didn't yet delete it and restore over zfs... do you think the backup.yaml would change then? If so, I can delete it now and then do the lxd import and afterwards again post the backup.yaml...

**Comment by renky** [comment]
ok, now I deleted the container and restored the zfs dataset with snapshots:
zfs list -t all shows the snapshots:
```
zpool1/lxd/containers/test                                                                   5.66M  1.24T   308M  /var/snap/lxd/common/lxd/storage-pools/pwhost/containers/test
zpool1/lxd/containers/test@snapshot-erster                                                    230K      -   308M  -
zpool1/lxd/containers/test@snapshot-zweiter                                                  50.1K      -   308M  -
zpool1/lxd/containers/test@snapshot-dritter                                                  37.4K      -   308M  -
```
but i again didn't backup zpool1/lxd/snapshots/test 

now lxd import test worked without error, but then lxc start test gives me the same error as described  - and the backup.yaml is now about 2k smaller than before - here again:
```
container:
  architecture: x86_64
  config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170815.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170815.1"
    image.version: "16.04"
    volatile.base_image: 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08
    volatile.br0.hwaddr: 00:16:3e:c2:12:fe
    volatile.br0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.power: RUNNING
  devices: {}
  ephemeral: false
  profiles:
  - default
  stateful: false
  description: ""
  created_at: 2017-08-28T09:32:20Z
  expanded_config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170815.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170815.1"
    image.version: "16.04"
    volatile.base_image: 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08
    volatile.br0.hwaddr: 00:16:3e:c2:12:fe
    volatile.br0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.power: RUNNING
  expanded_devices:
    br0:
      nictype: bridged
      parent: br0
      type: nic
    root:
      path: /
      pool: pwhost
      type: disk
  name: test
  status: Running
  status_code: 103
  last_used_at: 2017-08-28T09:32:21.784359996Z
snapshots:
- architecture: x86_64
  config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170815.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170815.1"
    image.version: "16.04"
    volatile.base_image: 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08
    volatile.br0.hwaddr: 00:16:3e:c2:12:fe
    volatile.br0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.power: RUNNING
  created_at: 2017-08-28T09:33:01Z
  devices: {}
  ephemeral: false
  expanded_config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170815.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170815.1"
    image.version: "16.04"
    volatile.base_image: 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08
    volatile.br0.hwaddr: 00:16:3e:c2:12:fe
    volatile.br0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.power: RUNNING
  expanded_devices:
    br0:
      nictype: bridged
      parent: br0
      type: nic
    root:
      path: /
      pool: pwhost
      type: disk
  last_used_at: 1970-01-01T00:00:00Z
  name: test/erster
  profiles:
  - default
  stateful: false
- architecture: x86_64
  config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170815.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170815.1"
    image.version: "16.04"
    volatile.base_image: 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08
    volatile.br0.hwaddr: 00:16:3e:c2:12:fe
    volatile.br0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.power: RUNNING
  created_at: 2017-08-28T09:33:30Z
  devices: {}
  ephemeral: false
  expanded_config:
    image.architecture: amd64
    image.description: ubuntu 16.04 LTS amd64 (release) (20170815.1)
    image.label: release
    image.os: ubuntu
    image.release: xenial
    image.serial: "20170815.1"
    image.version: "16.04"
    volatile.base_image: 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08
    volatile.br0.hwaddr: 00:16:3e:c2:12:fe
    volatile.br0.name: eth0
    volatile.idmap.base: "0"
    volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
    volatile.last_state.power: RUNNING
  expanded_devices:
    br0:
      nictype: bridged
      parent: br0
      type: nic
    root:
      path: /
      pool: pwhost
      type: disk
  last_used_at: 1970-01-01T00:00:00Z
  name: test/zweiter
  profiles:
  - default
  stateful: false
pool:
  config:
    source: zpool1/lxd
    volume.zfs.use_refquota: "true"
    zfs.pool_name: zpool1/lxd
  description: ""
  name: pwhost
  driver: zfs
  used_by: []
volume:
  config: {}
  description: ""
  name: test
  type: container
  used_by: []
```
