### ISSUE TITLE
All containers emit "The configuration file contains legacy configuration keys" after minor LXD upgrade

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#3845]
Upgrading from 2.17-0ubuntu2~ubuntu17.04.1~ppa1 to 2.18-0ubuntu2~ubuntu17.04.1~ppa1 causes all containers to emit the message... when entered via...

```
lxc exec $container bash
```

**The configuration file contains legacy configuration keys.**

As I recall, last time I saw this was on very old versions of LXC upgrades.

Let me know best way to do a mass correct of this problem, across 100s of containers.

Thanks.

**Comment by brauner** [comment]
@davidfavor, LXC 2.1 comes with a lot of configuration key changes but is entirely backwards compatible. If you started a container at a point where you had `liblxc < 2.1` installed the container uses the old library and hence lxd will use the legacy configuration keys when creating a config for the container. When you now update, and call e.g. `lxc exec` then the exec will load the new `liblxc >= 2.1` version at which point you'll get these errors reported. This however is non-crucial and - if you can - you can simply restart the container and the warning should vanish.

LXD generates the config on the fly so there's also nothing that you need to-do on-disk itself.

**Comment by stgraber** [comment]
Hmm, I thought I posted a reply to this, looks like Github ate it.

As @brauner said, this warning just means that liblxc was bumped to 2.1 but your container hasn't been restarted after that, so is still using now-deprecated config keys. Restarting the container will solve this.

**Comment by davidfavor** [comment]
Restarting containers clears message.

Thanks!

**Comment by kattunga** [comment]
Hi, In my case restarting containers doesn't clear the message.
I try stopping all containers and reboot all system but the message remains.

This is my configuration:

lxc info

```
  driver: lxc
  driver_version: 2.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-35-generic
  server: lxd
  server_pid: 26676
  server_version: "2.17"
  storage: zfs
  storage_version: 0.6.5.9-2
```

lxc config edit

```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20170811)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20170811"
  image.version: "16.04"
  volatile.base_image: 0ebf21fb1fef8a9230572cd68c68383018331f3f7865ded0ef86b437e5978370
  volatile.eth0.hwaddr: 00:16:3e:9e:24:e3
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid$
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"$
  volatile.last_state.power: RUNNING
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

**Comment by brauner** [comment]
Can you show your expanded default profile, please?

**Comment by kattunga** [comment]
lxc profile show default

```
config: {}
description: Default LXD profile
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: lxd
    type: disk
name: default
used_by:
- /1.0/containers/dia
- /1.0/containers/fbserver
- /1.0/containers/fbserver25
- /1.0/containers/mongodb
- /1.0/containers/mongodb/min-20170927200501
- /1.0/containers/mongodb/min-20170928070502
- /1.0/containers/mongodb/min-20170928080501
- /1.0/containers/mongodb/min-20170928090502
- /1.0/containers/mongodb/min-20170928100501
- /1.0/containers/mongodb/min-20170928110502
- /1.0/containers/mongodb/min-20170928120502
- /1.0/containers/mongodb/min-20170928130501
- /1.0/containers/mongodb/min-20170928140501
- /1.0/containers/mongodb/min-20170928150503
- /1.0/containers/mongodb/min-20170928160501
- /1.0/containers/mongodb/min-20170928170502
- /1.0/containers/mongodb/min-20170928180501
- /1.0/containers/mongodb/min-20170928190502
- /1.0/containers/mongodb/min-20170928200502
- /1.0/containers/mongodb/min-20170929070502
- /1.0/containers/mongodb/min-20170929080501
- /1.0/containers/mongodb/min-20170929090503
- /1.0/containers/mongodb/min-20170929100502
- /1.0/containers/mongodb/min-20170929110502
- /1.0/containers/mongodb/min-20170929120502
- /1.0/containers/mongodb/min-20170929130503
- /1.0/containers/mongodb/min-20170929140501
- /1.0/containers/mongodb/min-20170929150502
- /1.0/containers/mongodb/min-20170929160502
- /1.0/containers/mongodb/min-20170929170503
- /1.0/containers/mongodb/min-20170929180503
- /1.0/containers/mongodb/min-20170929190501
- /1.0/containers/mongodb/min-20170929200502
- /1.0/containers/mongodb/min-20170930070503
- /1.0/containers/mongodb/min-20170930080501
- /1.0/containers/mongodb/min-20170930090502
- /1.0/containers/mongodb/min-20170930100502
- /1.0/containers/mongodb/min-20170930110502
- /1.0/containers/mongodb/min-20170930120503
- /1.0/containers/mongodb/min-20170930130501
- /1.0/containers/mongodb/min-20170930140503
- /1.0/containers/mongodb/min-20170930150501
- /1.0/containers/mongodb/min-20170930160502
- /1.0/containers/mongodb/min-20170930170501
- /1.0/containers/mongodb/min-20170930180502
- /1.0/containers/mongodb/min-20170930190502
- /1.0/containers/mongodb/min-20170930200502
- /1.0/containers/nginx
- /1.0/containers/olap
- /1.0/containers/php
- /1.0/containers/redmine
- /1.0/containers/sigserver
```

**Comment by kattunga** [comment]
lxc config show --expanded container

```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20170811)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20170811"
  image.version: "16.04"
  volatile.base_image: 0ebf21fb1fef8a9230572cd68c68383018331f3f7865ded0ef86b437e5978370
  volatile.eth0.hwaddr: 00:16:3e:9e:24:e3
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: lxd
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
