### ISSUE TITLE
"The configuration file contains legacy configuration keys." on fresh LXD install from ubuntu-lxc/lxd-stable

### ISSUE THREAD

**Issue by ajthemacboy** [lxc/lxd#3848]
# Required information

 * Distribution: Ubuntu Server
 * Distribution version: 17.04
 * The output of "lxc info": https://pastebin.com/raw/E5b0qKt7

# Issue description

I am getting `error: The device doesn't exist - The configuration file contains legacy configuration keys` on fresh installations of Ubuntu Server 17.04 with LXD updated to 2.18. After installing 17.04, I run the following commands:
```
add-apt-repository -y ppa:ubuntu-lxc/lxd-stable
apt update
apt upgrade -y
lxd init --auto --storage-backend dir
```
After this I get the configuration error when I create profiles, networks, containers, etc.

Just to test, I purged lxcfs and lxd, removed /root/.config/lxc and the config in my home directory as well, and removed /usr/share/lxc and /usr/share/lxcfs. Then I ran `apt install lxd` and configured it again. The errors still occurred.

**Comment by scaleoutsean** [comment]
[Release notes](https://insights.ubuntu.com/2017/09/06/lxc-2-1-has-been-released/) supposedly contain info on how to handle this, but they neither inform where the config files are stored by default. Basic thing, but missing. 

(Separately, I was surprised that this kind of major change was done - as far as I could tell - rather silently; those who have lxc in production and upgrade packages won't be happy when this hits them. I just spent 30 minutes trying to figure what hit me and where the heck the config files are stored - so far no luck.)

**Comment by brauner** [comment]
LXC 2.1 comes with a lot of configuration key changes but is **entirely** backwards compatible. If you started a container at a point where you had liblxc < 2.1 installed the container uses the old library and hence lxd will use the legacy configuration keys when creating a config for the container. When you now update, and call e.g. lxc exec then the exec will load the new liblxc >= 2.1 version at which point you'll get these errors reported. This however is non-crucial and - if you can - you can simply restart the container and the warning should vanish.

LXD generates the config on the fly so there's also nothing that you need to-do on-disk itself.

**Comment by scaleoutsean** [comment]
Oh, I see - you're right, the container does start. The warning looks too scary.
I hope it's within the scope of this issue to ask - where are the config files stored? The message suggests to fix it, but it's not easy to figure out where the config files are stored.

**Comment by brauner** [comment]
@scaleoutsean, there's no need for you to touch any configuration files manually with LXD. This will only be in-memory. :)

**Comment by ajthemacboy** [comment]
I have `2.1.0-0ubuntu1~ubuntu17.04.1~ppa1` installed; my reason for creating this issue is because this error shows up when LXD is first initialized and containers are created **after** the update to 2.18.

**Comment by stgraber** [comment]
@ajthemacboy Can you do:
 - systemctl restart lxd
 - lxc launch ubuntu:16.04 test
 - lxc exec test bash

And see if that shows you the warning (it shouldn't)? If it does, then please show "lxc config show --expanded test" so we can check if there's anything in the container config that may be causing problems.

**Comment by ajthemacboy** [comment]
I did all of that. Here is the result:
```
root@userv1704:~# systemctl restart lxd
root@userv1704:~# lxc launch ubuntu:16.04 test
Creating test

The container you are starting doesn't have any network attached to it.
  To create a new network, use: lxc network create
  To attach a network to a container, use: lxc network attach

Starting test
root@userv1704:~# lxc exec test bash
The configuration file contains legacy configuration keys.
Please update your configuration file!
root@test:~#
```
```
root@userv1704:~# lxc config show test
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20170919)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20170919"
  image.version: "16.04"
  volatile.base_image: 03c2fa6716b5f41684457ca5e1b7316df520715b7fea0378f9306d16fdc646ee
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprang
e":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"M
aprange":65536}]'
  volatile.last_state.power: RUNNING
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
However, after restarting the container the error goes away.
```
root@userv1704:~# lxc restart test
root@userv1704:~# lxc exec test bash
root@test:~#
```
