### ISSUE TITLE
Operationalizing with LXD

### ISSUE THREAD

**Issue by remingtonc** [lxc/lxd#3885]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
```
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- id_map
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - omitted
  architectures:
  - x86_64
  - i686
  certificate: omitted
  certificate_fingerprint: omitted
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-93-generic
  server: lxd
  server_pid: 10656
  server_version: 2.0.10
  storage: dir
  storage_version: ""
```

# Issue description

I am attempting to operationalize an environment and experiencing difficulties. I would appreciate pointers wherever available. I will contribute back to the community with this information/setup once accomplished.

## Use Case
There are multiple hosts. Each user will receive a container. The containers are spread evenly across the hosts. Each container will have multiple macvlan interfaces with statically assigned IP addresses. The containers will run unprivileged as root (currently). This will become a fully automated workflow in deployment of host configurations and containers alike.

### Current Profile Template (Filled)
```
# Starting easy..network and rootfs.
config:
  environment.http_proxy: omitted
  raw.lxc: lxc.aa_profile = lxc-container-default-with-nesting
  raw.lxc: lxc.id_map = u 0 100000 65536
  raw.lxc: lxc.mount.auto = cgroup
description: Template developer profile
devices:
  mgmt:
    name: mgmt
    host_name: remingtonc-mgmt
    nictype: macvlan
    parent: enp1s0f0
    type: nic
    hwaddr: be:7b:95:ae:f2:d1
  rootfs:
    type: disk
    path: /
    source: /opt/remingtonc
name: remingtonc
```

## Questions
1. Are "profiles" for LXD the equivalent of LXC config files? Is it reasonable to have a profile per container given the different network needs? Should we use ```/etc/lxc/default.conf``` any more, or profiles? Which has priority?
2. For macvlan [interfaces](https://github.com/lxc/lxd/blob/master/doc/containers.md#type-nic), is ```parent``` an existing device? Is ```host_name``` an existing device? Will the interface be created automatically? Are the macvlan interfaces configured with IPs from the host, and not within the container? Should I be using ```lxc network``` at all? The above errors out, ```error: Failed to set LXC config: lxc.network.veth.pair=remingtonc-mgmt```
3. How do we specify the root mountpoint? The above errors out, ```Config parsing error: Root disk entry may not have a "source" property set.``` Is there a better way to do this?
4. For many environment variables - should ```lxc init ...``` then ```lxc file push /etc/environment container/etc/environment``` be used?
5. Does ```security.nesting = true``` have the same effect as ```lxc.aa_profile ...``` etc. as specified above in the ```raw.lxc``` sections?
6. How much of this should be done directly in profile versus via the command line? Is there a better practice either way?
