### ISSUE TITLE
Immediately after update to v2.18 from 2.17 containers cannot be restarted gracefully

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#3916]
Updated LXD from 2.17 to 2.18 from PPA on Ubuntu 16.04 

Now if I try to do a lxc stop or lxc restart I get an error message

```
~ # lxc stop webdockbackendstaging 
error: shutting down the container failed
Try `lxc info --show-log webdockbackendstaging` for more info

```

```
~ # lxc info --show-log webdockbackendstaging
Name: webdockbackendstaging
Remote: unix://
Architecture: x86_64
Created: 2017/06/20 12:19 UTC
Status: Stopped
Type: persistent
Profiles: webdock

Log:

            lxc 20171008191802.598 ERROR    lxc_commands_utils - commands_utils.c:lxc_cmd_sock_rcv_state:71 - failed to receive message: Socket operation on non-socket
            lxc 20171008191809.911 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:125 - Command get_cgroup failed to receive response: Connection reset by peer.
```

I tried restarting, as I encountered the message regarding legacy config keys as detailed in issue #3845

`lxc ls` will now show the container as stopped, regardless of whether I used lxc stop or lxc restart. So in effect lxc stop behaves as expected, while lxc restart is failing.

I tried just for kicks doing `service lxd restart` but this doesn't do anything. So this seems container specific, as it was running on v2.17 before the upgrade.

After starting the container again, everything works fine. Reporting this here, as this could be a bit of a gotcha for users with hundreds of production containers (of which I am one)

**Comment by stgraber** [comment]
I can't think of anything in LXD itself that would explain this, however it may well be a liblxc issue that prevented a clean container restart when a container is running using liblxc 2.0.8 and gets upgraded to liblxc 2.1.0.

Closing this issue on the LXD side, but @brauner may want to take a look at 2.0.x to 2.1 upgrade of running liblxc containers and how they behave when being signaled.

**Comment by stgraber** [comment]
(If there is in fact an issue with the upgrade path in liblxc, we should file an issue against lxc)

**Comment by Kramerican** [comment]
Ok thanks, but I'm not sure what this all means.

In any case after having restarted the container by issuing lxc stop, waiting for it to be stopped and then running lxc start clears up the lxd error message

However, I am still seeing the message I was originally trying to fix

```
The configuration file contains legacy configuration keys.
Please update your configuration file!
```

I would like to know what could be causing this. Shall I add this as a comment to issue #3845 ?

**Comment by stgraber** [comment]
Can you show "lxc config show --expanded NAME" for that container?

**Comment by stgraber** [comment]
After upgrading LXD and LXC and restarting all your containers, the message should have gone away
 The main exception being if you're using a raw.lxc key that needs to be converted to its new name.

**Comment by Kramerican** [comment]
Sure thing - I see a single raw key there, but do not recollect having added this, and I do not know what it does

```
architecture: x86_64
config:
  image.description: Webdock Ubuntu LAMP PHP 5.6
  limits.cpu.allowance: 50%
  limits.memory: 4GB
  limits.memory.enforce: soft
  linux.kernel_modules: ip_tables,ip6_tables
  raw.lxc: lxc.aa_allow_incomplete=1
  volatile.base_image: 3405ba4cbd22635c0cb5578c4a5542e7522fccacf85809acf43da678083218dd
  volatile.eth0.hwaddr: 00:16:3e:06:98:0a
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: lxd
    size: 60GB
    type: disk
ephemeral: false
profiles:
- webdock
stateful: false
description: ""
```
