### ISSUE TITLE
Calling lxc list --format json is slow

### ISSUE THREAD

**Issue by leehambley** [lxc/lxd#3942]
Github issues are used for bug reports. For support questions, please use [our forum](https://discuss.linuxcontainers.org).

Please fill the template below as it will greatly help us track down your issue and reproduce it on our side.  
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.04 Zesty
 * The output of "lxc info" or if that fails:

```
# lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  certificate_fingerprint: 61fd08b••••••••••••••••c800ce22563e942e4d9fa1
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-26-generic
  server: lxd
  server_pid: 1969
  server_version: "2.12"
  storage: lvm
  storage_version: 2.02.167(2) (2016-11-05) / 1.02.136 (2016-11-05) / 4.35.0
```

# Issue description

Calling `lxc info --format json` gets progressively slower until something "snaps" and I lose the machine for good. 

Here's a plot of the last ~24 hours from Grafana where we literally log the time 

<img width="958" alt="screenshot 2017-10-13 08 45 17" src="https://user-images.githubusercontent.com/18952/31533604-62af2140-aff3-11e7-908a-4b28252c195c.png">

And a corresponding trace from the CLI:

```
# time lxc list --format=json | jq '.[].name'
"container-3d2739eb-61da-4f55-43cf-accdd7129305"
"container-7853c4c6-5609-40cb-6b04-12fa37544535"
"container-82d9b83d-9c2f-490b-6660-84af548a73ed"
"container-9a9c1643-2e05-4ec5-66c8-90d40f503c39"
"container-9ce5a309-7e7e-4848-4033-8fde79891634"
"container-9d872b72-80b8-45de-7a03-cb400b6aced5"
"container-c5a191a0-8397-4301-5b25-2fd5d7a61029"
"container-f0c78c68-11aa-4f84-4efe-234b21bcb3fb"
"container-fa80d911-d09e-4362-7a47-4c5286365c4d"
"container-fa8467cc-8c32-41a9-51a1-0342c158748d"
"leetest"

real    0m11.326s
user    0m0.060s
sys     0m0.020s
```

A `strace` of the same client call attached:

- https://gist.github.com/leehambley/0f619751c7e77ab8bbc4dab82668cfb9

This trace tries to follow children (without `-f` we hang for 10 sec waiting for a `futex`, see previous gist revision if that's somehow useful.)

Important to note maybe, there's only 10-15 containers at any one time, and the data returned isn't massive:

```
# lxc list --format=json | wc                                                                            
      1      73   23345
```

# Steps to reproduce

 1. Run LXC/D for a while
 2. Have a service that puts containers into service for 30m-2h at a time and replaces them when they're "finished"
 3. Use it's API every few minutes to count containers

*Note:* There seems to be a clue in the output of `# lxc monitor` (`Initializing an LVM driver.`) see below, we paused for quite a long time after a `GET /1.0/containers?recursion=1`.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [x] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

```
# lxc config show container-fa8467cc-8c32-41a9-51a1-0342c158748d --expanded
architecture: x86_64
config:
  image.architecture: x86_64
  image.description: Ubuntu 16.04 LTS server (20160815)
  image.os: ubuntu
  image.release: xenial
  security.nesting: "true"
  volatile.aadisable.hwaddr: 00:16:3e:f2:e3:61
  volatile.aadisable.name: eth1
  volatile.apply_template: create
  volatile.base_image: 4edc4a445f165767eeaf9b1b9b0c7778da2f9c29a5bbca5cb67723dd9fdac06f
  volatile.eth0.hwaddr: 00:16:3e:44:91:6e
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.root.hwaddr: 00:16:3e:9d:25:d9
  volatile.root.name: eth2
devices:
  aadisable:
    path: /sys/module/apparmor/parameters/enabled
    source: /dev/null
    type: disk
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
- docker

```

```
metadata:
  context: {}
  level: dbug
  message: 'New events listener: 79395663-e27b-4df5-bb9b-615b19518371'
timestamp: 2017-10-13T07:06:56.731542483Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:06:59.177366862Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:06:59.234134457Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers?recursion=1
  level: dbug
  message: handling
timestamp: 2017-10-13T07:06:59.245254072Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:02.301601737Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:02.301669912Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:02.368098025Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/container-377e286f-1128-4da3-51d9-33230c9ee9b7/snapshots?recursion=1
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:02.379277957Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:02.381064679Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/container-377e286f-1128-4da3-51d9-33230c9ee9b7/state
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:02.398011385Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:02.45273015Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.280060176Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.280248638Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.280362311Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.280712158Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.280807484Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.280957445Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.281006434Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.281027748Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.281120808Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.281069134Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.28116287Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.281274765Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.281238605Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.281334118Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.281321005Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.281347952Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.281435396Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.281483468Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.281557873Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.281673671Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:09.360203237Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/container-377e286f-1128-4da3-51d9-33230c9ee9b7/state
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.44243855Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:09.441615837Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:09.497665118Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:09.547624752Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:09.584448848Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/container-377e286f-1128-4da3-51d9-33230c9ee9b7/snapshots?recursion=1
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.584679299Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:09.631137283Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:09.631748387Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/container-7853c4c6-5609-40cb-6b04-12fa37544535/snapshots?recursion=1
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.632307128Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/container-9a9c1643-2e05-4ec5-66c8-90d40f503c39/snapshots?recursion=1
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.658075025Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:09.778232969Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:09.778220453Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:09.793408857Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:09.872150934Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/container-c9b6683a-20d2-4b5b-59a0-12352f0f4710/state
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.872380109Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:09.90819218Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/container-9ce5a309-7e7e-4848-4033-8fde79891634/snapshots?recursion=1
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.907803163Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/container-c5a191a0-8397-4301-5b25-2fd5d7a61029/snapshots?recursion=1
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.946172275Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/container-9d872b72-80b8-45de-7a03-cb400b6aced5/snapshots?recursion=1
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.908284869Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:10.006558123Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/container-f0c78c68-11aa-4f84-4efe-234b21bcb3fb/snapshots?recursion=1
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:09.973120602Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/container-c9b6683a-20d2-4b5b-59a0-12352f0f4710/snapshots?recursion=1
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:10.057369022Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:10.058043275Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:10.085797754Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:10.149276207Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/container-fa80d911-d09e-4362-7a47-4c5286365c4d/snapshots?recursion=1
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:10.148819561Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:10.203780682Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:10.241127286Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:10.2798002Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:10.339357342Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/container-fa8467cc-8c32-41a9-51a1-0342c158748d/snapshots?recursion=1
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:10.350156047Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:10.360955041Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/leetest/snapshots?recursion=1
  level: dbug
  message: handling
timestamp: 2017-10-13T07:07:10.37626234Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing an LVM driver.
timestamp: 2017-10-13T07:07:10.528431022Z
type: logging
```
