### ISSUE TITLE
CGroup Mount creating strange directory structure

### ISSUE THREAD

**Issue by tommyknows** [lxc/lxd#3957]
# Required information

 * Distribution: Ubuntu 16.04 (without systemd)
 * The output of "lxc info" or if that fails:
   * Kernel version:  4.10.0-37-generic
   * LXC version: 2.18
   * LXD version: 2.18
   * Storage backend in use: zfs | dir

# Issue description

I'm trying to run kubernetes inside an lxc container, however, the kubelet fails on startup with the following error:
```kubelet[4066]: error: failed to run Kubelet: mountpoint for cpu not found```

After some googling, I found that this is most likely an issue with cgroups. 
These are the cgroups on the host:
``` 
root@ubuntu:~# ls /sys/fs/cgroup
blkio  cpu  cpuacct  cpuset  devices  freezer  hugetlb  memory  net_cls  net_prio  perf_event  pids  systemd
```

The cgroups inside the container look different:
```
root@kubernetes:~# ls /sys/fs/cgroup/
blkio  cpu,cpuacct  cpuset  devices  freezer  hugetlb  memory  net_cls,net_prio  perf_event  pids  systemd
```
(Notice the "cpu,cpuacct" is one folder, instead of two seperate)

```
root@kubernetes:~# cat /proc/self/cgroup
13:name=systemd:/
12:pids:/
11:hugetlb:/
10:net_prio:/
9:perf_event:/
8:net_cls:/
7:freezer:/
6:devices:/
5:memory:/
4:blkio:/
3:cpuacct:/
2:cpu:/
1:cpuset:/
root@kubernetes:~# cat /proc/self/mountinfo | grep cgroup
57 102 0:52 / /sys/fs/cgroup ro,nosuid,nodev,noexec - tmpfs tmpfs ro,mode=755
58 57 0:38 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,name=systemd
59 57 0:31 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,devices
60 57 0:37 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,pids
61 57 0:34 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,perf_event
62 57 0:28 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,blkio
63 57 0:36 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,hugetlb
64 57 0:22 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpuset
65 57 0:29 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,memory
66 57 0:32 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,freezer
```

I use the following two profiles for the container:
```
root@ubuntu:~# lxc profile show docker
config:
  linux.kernel_modules: overlay, nf_nat
  security.nesting: "true"
description: Profile supporting docker in containers
devices:
  aadisable:
    path: /sys/module/apparmor/parameters/enabled
    source: /dev/null
    type: disk
name: docker
used_by:
- /1.0/containers/kubernetes

root@ubuntu:~# lxc profile show kubernetes
config:
  boot.autostart: "true"
  linux.kernel_modules: bridge,br_netfilter,ip_tables,ip6_tables,netlink_diag,nf_nat,overlay
  raw.lxc: |-
    lxc.aa_profile = unconfined
    lxc.cgroup.devices.allow = a
    lxc.mount.auto=proc:rw sys:rw
    lxc.cap.drop =
  security.nesting: "true"
  security.privileged: "true"
description: Profile for kubernetes hosts
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: dirpool
    type: disk
name: kubernetes
used_by:
- /1.0/containers/kubernetes
```

# Steps to reproduce

 1. Start an ubuntu container (```lxc launch ubuntu:16.04 test```)
 2. Check CGroups

Am I missing something? Or is this expected behavior?

Thanks
