### ISSUE TITLE
[Feature Request] Hide columns in "lxc list"

### ISSUE THREAD

**Issue by spacekookie** [lxc/lxd#3967]
Not sure if this is the place to do stuff like this but I couldn't find any other ways mentioned so I'm just gonna suggest it here :smile: 

# Feature Description

Allow users (either via a configuration or whatever) to hide columns from `lxc list`. Namely I would like to be able to hide the ipv6 field but making it something generic would allow users to adjust the standard output of `lxc list` to whatever information they want to see at a glance.

I regularly use terminals of limited width and while most of my containers don't have ipv6 addresses, some do which breaks the formatting of the list completely which makes it unreadable. I would much rather explicitly say "show me ipv6 information" than `lxc list -c ns4tS` to hide it

# Steps to reproduce

 1. Install LXD
 2. Create a container
 3. Have a terminal with a width than less ~130 characters
 4. Be unable to read anything

**Comment by stgraber** [comment]
The standard way of doing this in our client is through command aliases.

```
default-remote: local
remotes:
  images:
    addr: https://images.linuxcontainers.org
    public: true
    protocol: simplestreams
  local:
    addr: unix://
    public: false
  ubuntu:
    addr: https://cloud-images.ubuntu.com/releases
    public: true
    protocol: simplestreams
  ubuntu-daily:
    addr: https://cloud-images.ubuntu.com/daily
    public: true
    protocol: simplestreams
aliases:
  delete: delete -f
  ls: list -c nstS
  shell: exec @ARGS@ -- bash
  ubuntu: exec @ARGS@ -- sudo --login --user ubuntu
```

In my case this defines a "lxc ls" which uses "nstS" as its column layout but as you can see with the "delete" entry, you can also re-define one of the commands, so you could re-define "lxc list".
