### ISSUE TITLE
How to move containers using tar compressed directory (due to poor network connection)?

### ISSUE THREAD

**Issue by gregsifr** [lxc/lxd#3974]
I'm trying to move a container over a VPN however the connection is very poor in between so the transfer idles and does not complete.

In the past when using LXC I've used a similar method to this: https://stackoverflow.com/questions/23427129/how-do-i-backup-move-lxc-containers

I've done a similar approach this time. That is I've compressed the container folder (which is symbolically linked from `/var/lib/lxd/containers/container`) and transferred it over the network. I decompressed the folder to `/var/lib/lxd/storage-pools/default/containers/container` and added the symbolic link `/var/lib/lxd/containers/container` however `lxc list` still does not show the container.

What else needs to be done in order to move the container in such a way?

**Comment by dann1** [comment]
I think lxd keeps a database file with info about containers  **/var/lib/lxd/lxd.db**. Try instead to compress **/var/lib/lxd/containers/container** and import that on the new lxd host via **lxc image import container.tar.xz**

**Comment by gregsifr** [comment]
```
user@pc:~$ lxc image import container.tar.gz 
Transferring image: 100% (371.42MB/s)error: Could not extract image metadata.yaml from tar: Failed to run: tar -O -zxf /var/lib/lxd/images/lxd_build_441005101/lxd_post_579152296 metadata.yaml: tar: metadata.yaml: Not found in archive
tar: Exiting with failure status due to previous errors (tar: metadata.yaml: Not found in archive)
```

When I extract the tarball I can however see the `metadata.yaml` file:
```
user@pc:~$ ls container
backup.yaml  metadata.yaml  rootfs  templates
```

**Comment by dann1** [comment]
Weird, no idea does metadata.yaml has the right info?

**Comment by gregsifr** [comment]
I can't see anything out of the ordinary...
```
architecture: "x86_64"
creation_date: 1479222797
properties:
    architecture: "x86_64"
    description: "Ubuntu 16.04 LTS server (20161115)"
    os: "ubuntu"
    release: "xenial"
templates:
    /etc/hostname:
        when:
            - create
            - copy
        template: hostname.tpl
    /var/lib/cloud/seed/nocloud-net/meta-data:
        when:
            - create
            - copy
        template: cloud-init-meta.tpl
    /var/lib/cloud/seed/nocloud-net/network-config:
        when:
            - create
            - copy
        template: cloud-init-network.tpl
    /var/lib/cloud/seed/nocloud-net/user-data:
        when:
            - create
            - copy
        template: cloud-init-user.tpl
        properties:
            default: |
                #cloud-config
                {}
    /var/lib/cloud/seed/nocloud-net/vendor-data:
        when:
            - create
            - copy
        template: cloud-init-vendor.tpl
        properties:
            default: |
                #cloud-config
                {}
    /etc/init/console.override:
        when:
            - create
        template: upstart-override.tpl
    /etc/init/tty1.override:
        when:
            - create
        template: upstart-override.tpl
    /etc/init/tty2.override:
        when:
            - create
        template: upstart-override.tpl
    /etc/init/tty3.override:
        when:
            - create
        template: upstart-override.tpl
    /etc/init/tty4.override:
        when:
            - create
        template: upstart-override.tpl
```
