### ISSUE TITLE
Requesting example of /etc/netplan YAML file to describe one or more public IPs

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#3977]
With the release of Ubuntu Artful, /etc/netplan is now used, so normal declarations for public container IPs in /etc/network/interfaces no longer works.

Someone please post a working /etc/netplan YAML file to associate one or more public IPs with a container.

Thanks.

**Comment by jfgibbins** [comment]
are you currently using eni format for cloud-init?  If so, update according to this, to use version 1 or 2, preferably 2 going forward.

https://github.com/lxc/lxd/blob/master/doc/cloud-init.md
http://cloudinit.readthedocs.io/en/latest/topics/network-config.html

Example cloud-init version 1:
  user.network-config: |
    ---
    version: 1
    config:
    - type: physical
      name: eth0
    - type: nameserver
      address:
      - x.x.x.x
      search:
      - xxx.local
      - xxx.org
    - type: vlan
      name: mgmt
      vlan_link: eth0
      vlan_id: 1000
      subnets:
      - address: x.x.x.x/12
        control: auto
        type: static
    - type: vlan
      name: eth0.1200
      vlan_link: eth0
      vlan_id: 1200
      subnets:
      - address: x.x.x.x/24
        gateway: x.x.x.x
        control: auto
        type: static
    ...

Below is the stuff for netplan, but remember, with cloud-init, you don't write this file directly.  You do it according to the above.  But if you really want to stick with the removed version, create your own image of artful that includes the package with ifupdown, etc.

http://people.canonical.com/~mtrudel/netplan/
http://manpages.ubuntu.com/manpages/zesty/man5/netplan.5.html
https://wiki.ubuntu.com/Netplan/Design
https://insights.ubuntu.com/2017/07/05/quick-and-easy-network-configuration-with-netplan/

**Comment by davidfavor** [comment]
I'm using a standard install.
```
lxc init ubuntu:artful/amd64 net11-ubuntu-artful
```
Which produces /etc/netplan/50-cloud-init.yaml with contents of...
```
# This file is generated from information provided by
# the datasource.  Changes to it will not persist across an instance.
# To disable cloud-init's network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    version: 2
    ethernets:
        eth0:
            dhcp4: true
```
Normally I'd create an eth0:1 alias with a single IP (addresses: [144.217.34.1/32]) + I the netplan docs are horribly terse.

I've tried many combinations of syntax based on the man pages.

No joy.

The above YAML file you posted will likely not work, because this will mix V1 + V2 netplan files, which the docs suggest won't work.

I'm looking for something like...
```
# Define container's public IP
network:
   version: 2
   ethernets:
      eth0
        match:
          eth0
            set-name: eth0:1
            addresses: [144.217.34.1/32]
```
Just simple syntax to create eth0:1 associated with eth0 with a single IP address assigned.

If you have an example that covers this use case, pass it along.

**Comment by jfgibbins** [comment]
network:
    version: 2
    ethernets:
        eth0:
            dhcp4: true
            addresses:
            - 192.168.22.14/27
            gateway4: 192.168.22.1
            match:
                macaddress: 00:15:0a:08:00:05
            nameservers:
                addresses:
                - 192.168.23.2
                - 8.8.8.8
                search:
                - exemplary
            set-name: eth0

**Comment by jfgibbins** [comment]
Be sure to read https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html#
There are lots of examples, including how to do static and dhcp on same interface including the very first one https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html#examples

**Comment by stgraber** [comment]
thanks @jfgibbins 

Closing this issue as LXD is just passing strings through and we're unfortunately no cloud-init experts :)
I could have dug some local examples but @jfgibbins did that for me :)

**Comment by davidfavor** [comment]
@stgraber, be great if you post how you accomplish this.

The following seems to work + this destroys the 10.X.X.X address inside the container, so may cause problems.

I realize this is not technically an LXD problem + without working networking, LXD is useful as a brick.
```
network:
    version: 2
    ethernets:
        eth0:
            match:
              name: eth0
            addresses:
            - 144.217.34.1/32
            set-name: eth0:1
```

**Comment by jfgibbins** [comment]
@davidfavor You'll have to explain more in depth.  What 10.x address?  There's nothing in your example to either set or get an address other than 144.x loopback address.

**Comment by davidfavor** [comment]
Creating a container produces this...
```
net11 # lxc init ubuntu:artful/amd64 net11-ubuntu-artful

net11 # lxc start net11-ubuntu-artful

net11 # lxc list net11-ubuntu-artful
+---------------------+---------+----------------------+-----------------------------------------------+------------+-----------+
|        NAME         |  STATE  |         IPV4         |                     IPV6                      |    TYPE    | SNAPSHOTS |
+---------------------+---------+----------------------+-----------------------------------------------+------------+-----------+
| net11-ubuntu-artful | RUNNING | 10.118.125.91 (eth0) | fd42:3336:560c:b2c1:216:3eff:fe3b:2998 (eth0) | PERSISTENT | 0         |
+---------------------+---------+----------------------+-----------------------------------------------+------------+-----------+
```
Adding an IPV4 public interface inside a container usually produces both a 10.X.X.X address + the public IP, like this...
```
net11 # lxc list net11-ubuntu-zesty
+--------------------+---------+--------------------------------+-----------------------------------------------+------------+-----------+
|        NAME        |  STATE  |              IPV4              |                     IPV6                      |    TYPE    | SNAPSHOTS |
+--------------------+---------+--------------------------------+-----------------------------------------------+------------+-----------+
| net11-ubuntu-zesty | RUNNING | 144.217.34.0 (eth0)            | fd42:3336:560c:b2c1:216:3eff:feff:4c15 (eth0) | PERSISTENT | 0         |
|                    |         | 10.118.125.29 (eth0)           |                                               |            |           |
+--------------------+---------+--------------------------------+-----------------------------------------------+------------+-----------+
```
This use to be easy to do via a simple entry in the interfaces file, of the form...
```
# Public IP
auto eth0:1
iface eth0:1 inet static
    netmask 255.255.255.255
    address 144.217.34.0
```
Which would simply create an eth0 alias of eth0:1 which left the 10.X.X.X address intact + added the public IP, allowing bi-directional packet flow between host + container + between all containers on the machine.

I'm looking for how to do this via netplan + I haven't found any docs yet which explain how to configure a simple eth0:1 alias.

If you know how, pass it along.

**Comment by jfgibbins** [comment]
But I still don't see in any of your conifig where the 10.x address comes from.  And FYI, there is no alias in netplan.  There treated as secondary IP addresses per the man page as follows.  Same as link above. 

dhcp4: <(bool)>

Enable DHCP for IPv4. Off by default.

dhcp6: <(bool)>

Enable DHCP for IPv6. Off by default.

addresses: <(sequence of scalars)>

Add static addresses to the interface in addition to the ones received through DHCP or RA. Each sequence entry is in CIDR notation, i. e. of the form addr/prefixlen . addr is an IPv4 or IPv6 address as recognized by inet_pton``(3) and ``prefixlen the number of bits of the subnet.

Example: addresses: [192.168.14.2/24, 2001:1::1/64]

**Comment by davidfavor** [comment]
10.118.125.91 == 10.X.X.X

**Comment by davidfavor** [comment]
Problem is this. I can easily set my 144.217.34.1/32 address, except each time I get it set, the 10.X.X.X address is obliterated, which use to be required for various packet flow, between containers + host.

**Comment by jfgibbins** [comment]
Yes, I know the 10 address, but you haven't shown how and where you're getting it from.  It has to be assigned statically or by dhcp and you haven't specified either in your netplan file.  I'm going to take a guess, and assume you're using out of the box networking that LXD typically installs with, and that you're getting the 10.x from a dhcp server.  If so, then if you used my example, or that of the links I sent you, the problem is that you deleted the line that says 'dhcp4: true'.  Read the following:

https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html#common-properties-for-all-device-types  namely the entries for dhcp4 and addresses as well as the first example that shows dhcp and the second example that shows dhcp and static on the same interface.
https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html#examples

Also, from a networking standpoint, the 144.217.34.1/32 is a loopback, so should probably be assigned to a lo interface rather than the eth0.

example for you to try taken from above and link.

network:
    version: 2
    ethernets:
        eth0:
            dhcp4: true
            addresses:
            - 144.217.34.1/32
            match:
                name: eth0
           set-name: eth0

Again, there is NO alias.  They are now secondary interfaces.  You could also take the loopback address off the eth0 and set it up as a loopback interface.

**Comment by davidfavor** [comment]
The 10.X.X.X address is automatically assigned be default when a container is created by invoking /etc/netplan/50-cloud-init.yaml
```
# This file is generated from information provided by
# the datasource.  Changes to it will not persist across an instance.
# To disable cloud-init's network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    version: 2
    ethernets:
        eth0:
            dhcp4: true
```
I'll try your example above.
