### ISSUE TITLE
Feature Request: enable source parameter in rootfs disk

### ISSUE THREAD

**Issue by dann1** [lxc/lxd#4003]
Hello, when using LXD you can specify the location of either a block device or a folder for disk device in a container configuration

```
devices:
  disk1:
    path: /
    pool: storage_pool1
    type: disk
    source: /dev/rbd1
```
But you can't do that for the root filesystem, however in LXC you could specify that using `lxc.rootfs.path`. Is there a way to do that in LXD? As far as I know and for what I've seen LXD expects to find the rootfs mounted on `/var/lib/lxd/containers/container1/rootfs/`. I've been tricking LXD with premounts and postmounts, but that's has led to chaos in the presence of power failures  and I'm looking for a better way.

When I try to force that config into the rootfs disk I get 
`Config parsing error: Root disk entry may not have a "source" property set.`
