### ISSUE TITLE
Support for lxc specific bind options

### ISSUE THREAD

**Issue by h0tw1r3** [lxc/lxd#4005]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.10 (Artful)
 * Kernel version: 4.13.0-16-generic
 * LXC version: 2.1.0
 * LXD version: 2.18
 * Storage backend in use: dir

# Issue description

Ability to supply "create" option to disk type devices.
Without the ability to set create=dir, a container will fail to start if the bind destination folder does not exist.

```
devices:
  somefolder:
    path: /var/lib/somefolder
    source: /opt/somefolder
    type: disk
    options: create=dir
```
