### ISSUE TITLE
Container is not autostarted

### ISSUE THREAD

**Issue by albertodonato** [lxc/lxd#4054]
On LXD 2.18 [2.18-0ubuntu6], I have a container with `boot.autostart="1"`, but it's not started at boot.

This is the config 

```
architecture: x86_64
config:
  boot.autostart: "1"
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20171011)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20171011"
  image.version: "16.04"
  raw.idmap: both 1000 1000
  volatile.base_image: 61d54418874f2f84e24ddd6934b3bb759ca76cbc49820da7d34f8b5b778e4816
  volatile.eth0.hwaddr: 00:16:3e:65:0f:a0
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.maas0.hwaddr: 00:16:3e:bc:d9:60
devices:
  maas0:
    name: maas0
    nictype: bridged
    parent: virbr1
    type: nic
ephemeral: false
profiles:
- maas-dev-ack
stateful: false
description: ""
```

If I start it manually afterwards, it works fine

container lxc.log only contains repeated lines like this:
```
lxc 20171125125112.114 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory
```

lxd.log:
```
lvl=info msg="LXD 2.18 is starting in normal mode" path=/var/lib/lxd t=2017-11-25T13:43:56+0100                                                                           
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-11-25T13:43:56+0100                                                         
lvl=info msg="Kernel uid/gid map:" t=2017-11-25T13:43:56+0100                        
lvl=info msg=" - u 0 0 4294967295" t=2017-11-25T13:43:56+0100                        
lvl=info msg=" - g 0 0 4294967295" t=2017-11-25T13:43:56+0100                        
lvl=info msg="Configured LXD uid/gid map:" t=2017-11-25T13:43:56+0100                
lvl=info msg=" - u 0 100000 65536" t=2017-11-25T13:43:56+0100                        
lvl=info msg=" - g 0 100000 65536" t=2017-11-25T13:43:56+0100                        
lvl=info msg="Expiring log files" t=2017-11-25T13:43:58+0100                         
lvl=info msg="Starting /dev/lxd handler" t=2017-11-25T13:43:58+0100                  
lvl=info msg="LXD is socket activated" t=2017-11-25T13:43:58+0100                    
lvl=info msg="REST API daemon:" t=2017-11-25T13:43:58+0100                           
lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket t=2017-11-25T13:43:58+0100                                                                          
lvl=info msg="Pruning expired images" t=2017-11-25T13:43:58+0100                     
lvl=info msg="Done pruning expired images" t=2017-11-25T13:43:58+0100                
lvl=info msg="Updating images" t=2017-11-25T13:43:58+0100                            
lvl=info msg="Updating instance types" t=2017-11-25T13:43:58+0100                    
lvl=info msg="Done expiring log files" t=2017-11-25T13:43:58+0100                    
lvl=info msg="Done updating images" t=2017-11-25T13:43:59+0100                       
lvl=info msg="Done updating instance types" t=2017-11-25T13:44:00+0100     
```
