### ISSUE TITLE
lxc start fails if there is a space in path

### ISSUE THREAD

**Issue by nickmayer** [lxc/lxd#4064]
Github issues are used for bug reports. For support questions, please use [our forum](https://discuss.linuxcontainers.org).

Please fill the template below as it will greatly help us track down your issue and reproduce it on our side.  
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 17.10
 * The output of "lxc info" or if that fails:
```
$ lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
...
    -----END CERTIFICATE-----
  certificate_fingerprint: 80fd86119bb6b81b05baee8eb34d93d77e7f912dfb04ceafe05a45f76f805d3d
  driver: lxc
  driver_version: 2.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-17-generic
  server: lxd
  server_pid: 1937
  server_version: "2.18"
  storage: btrfs
  storage_version: "4.12"
```
# Issue description

Create a new container `lxc init ubuntu:17.10 plex`
Edit container `lxc config edit plex` 
Using yaml below `lxc start plex` generates an error. Replacing the spaces in `path: share/home/Kid TV` & `path: share/home/Kid Movies` with underscores allows the container to start.
```
### This is a yaml representation of the configuration.
architecture: x86_64
config:
  boot.autostart: "true"
  image.architecture: amd64
  image.description: ubuntu 17.10 amd64 (release) (20171122)
  image.label: release
  image.os: ubuntu
  image.release: artful
  image.serial: "20171122"
  image.version: "17.10"
  limits.cpu.allowance: 50%
  limits.memory: 4GB
  raw.idmap: |-
    uid 2500 2500
    gid 2500 2500
  volatile.base_image: bcd33e96064a1bd5ed2adec3e6103e802c4cd6b524e38cda176f5dc4123535d7
  volatile.eth0.hwaddr: 00:16:3e:b0:74:7a
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":2500},{"Isuid":true,"Isgid":false,"Hostid":2500,"Nsid":2500,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":102501,"Nsid":2501,"Maprange":63035},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":2500},{"Isuid":false,"Isgid":true,"Hostid":2500,"Nsid":2500,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":102501,"Nsid":2501,"Maprange":63035}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":2500},{"Isuid":true,"Isgid":false,"Hostid":2500,"Nsid":2500,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":102501,"Nsid":2501,"Maprange":63035},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":2500},{"Isuid":false,"Isgid":true,"Hostid":2500,"Nsid":2500,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":102501,"Nsid":2501,"Maprange":63035}]'
  volatile.last_state.power: RUNNING
devices:
  dvr:
    path: share/home/DVR
    source: /mnt/storage/home/DVR
    type: disk
  eth0:
    nictype: bridged
    parent: br0
    type: nic
  kid-movies:
    path: share/home/Kid Movies
    source: /mnt/storage/home/Kid Movies
    type: disk
  kid-tv:
    path: share/home/Kid TV
    source: /mnt/storage/home/Kid TV
    type: disk
  movies:
    path: share/home/Movies
    source: /mnt/storage/home/Movies
    type: disk
  tv:
    path: share/home/TV
    source: /mnt/storage/home/TV
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
```
$ lxc info --show-log plex
Name: plex
Remote: unix://
Architecture: x86_64
Created: 2017/11/30 05:34 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

            lxc 20171130080133.474 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171130080133.474 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171130080133.566 WARN     lxc_cgfsng - cgroups/cgfsng.c:chown_cgroup_wrapper:1492 - Error chmoding /sys/fs/cgroup/unified//lxc/plex: No such file or directory
            lxc 20171130080133.606 ERROR    lxc_conf - conf.c:mount_entry:1854 - No such file or directory - Failed to mount "/var/lib/lxd/devices/plex/disk.\"share-home-Kid" on "/usr/lib/x86_64-linux-gnu/lxc/TV\""
            lxc 20171130080133.606 ERROR    lxc_conf - conf.c:lxc_setup:3186 - failed to setup the mount entries for 'plex'
            lxc 20171130080133.606 ERROR    lxc_start - start.c:do_start:921 - Failed to setup container "plex".
            lxc 20171130080133.606 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
            lxc 20171130080133.658 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171130080133.658 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171130080133.658 ERROR    lxc_container - lxccontainer.c:wait_on_daemonized_start:760 - Received container state "ABORTING" instead of "RUNNING"
            lxc 20171130080133.658 ERROR    lxc_start - start.c:__lxc_start:1451 - Failed to spawn container "plex".
            lxc 20171130080133.658 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171130080133.658 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171130080133.791 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171130080133.791 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171130080133.792 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:125 - Command get_cgroup failed to receive response: Connection reset by peer.
```
