### ISSUE TITLE
Problem setting up LXD for Juju

### ISSUE THREAD

**Issue by imrankhakoo** [lxc/lxd#4205]
# Required information

 * Distribution:Ubuntu
 * Distribution version:18.04
 * The output of "lxc info":
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
(removed)
    -----END CERTIFICATE-----
  certificate_fingerprint: (removed)
  driver: lxc
  driver_version: 2.1.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-041500rc9-generic
  server: lxd
  server_pid: 6158
  server_version: "2.21"
  storage: btrfs
  storage_version: 4.13.3

# Issue description

I'm following the instructions at https://jujucharms.com/docs/devel/tut-lxd with Juju-2.X and an Ubuntu 18.04 install. I'm trying to set up LXD and wish to link it to Juju/MAAS. I'm seeing the following issue, which seems to be replicated no matter what address I try (even the "auto" setting gives the same error.)

```
# lxd init
Do you want to configure a new storage pool (yes/no) [default=yes]? 
Name of the new storage pool [default=default]: 
Name of the storage backend to use (dir, btrfs, lvm) [default=btrfs]: 
Create a new BTRFS pool (yes/no) [default=yes]? 
Would you like to use an existing block device (yes/no) [default=no]? 
Size in GB of the new loop device (1GB minimum) [default=100GB]: 10
Would you like LXD to be available over the network (yes/no) [default=no]? 
Would you like stale cached images to be updated automatically (yes/no) [default=yes]? 
Would you like to create a new network bridge (yes/no) [default=yes]? 
What should the new bridge be called [default=lxdbr0]? 
What IPv4 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]? 10.1.1.100/24
Would you like LXD to NAT IPv4 traffic on your bridge? [default=yes]? 
What IPv6 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]? 
error: Failed to run: dnsmasq --strict-order --bind-interfaces --pid-file=/var/lib/lxd/networks/lxdbr0/dnsmasq.pid --except-interface=lo --interface=lxdbr0 --quiet-dhcp --quiet-dhcp6 --quiet-ra --listen-address=10.1.1.100 --dhcp-no-override --dhcp-authoritative --dhcp-leasefile=/var/lib/lxd/networks/lxdbr0/dnsmasq.leases --dhcp-hostsfile=/var/lib/lxd/networks/lxdbr0/dnsmasq.hosts --dhcp-range 10.1.1.2,10.1.1.254,1h --listen-address=fd42:7af7:10fc:60e9::1 --enable-ra --dhcp-range ::,constructor:lxdbr0,ra-stateless,ra-names -s lxd -S /lxd/ --conf-file=/var/lib/lxd/networks/lxdbr0/dnsmasq.raw -u lxd: dnsmasq: failed to create listening socket for 10.1.1.100: Address already in use
```

# Steps to reproduce

 1. Install Ubuntu 18.04, update kernel to 4.15 latest, install and set up MAAS and juju, install lxd and zfsutils-linux
 2. Create a bridge using netplan settings:
```
# cat /etc/netplan/01-netcfg.yaml 
# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    enp6s0f1:
      dhcp4: no
      addresses: [172.26.0.224/22]
      gateway4: 172.26.0.1
      nameservers:
        addresses: [8.8.8.8,10.1.1.1]
    eno1:
      dhcp4: no

  bridges:
    br1:
      interfaces: [eno1]
      dhcp4: no
      addresses: [10.1.1.1/24]
      gateway4: 172.26.0.1
      nameservers:
        addresses: [10.1.1.1]

```

 2. Run lxd init and allow default settings to be used

[lxd_error.txt](https://github.com/lxc/lxd/files/1676702/lxd_error.txt)
