### ISSUE TITLE
some iptables rules created if ipv4.firewall is false

### ISSUE THREAD

**Issue by wociscz** [lxc/lxd#4214]
* Distribution: Ubuntu
 * Distribution version: 16.04.3 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.13.0-32-generic
   * LXC version: 2.0.8-0ubuntu1~16.04.2
   * LXD version: 2.21-0ubuntu2~16.04.1
   * Storage backend in use: dir

# Issue description
lxd generate some iptables rules even if i have ipv{4,6}.firewall set to false. If you have your own iptables rules, these created by lxd are set to the top of your rules after reboot. It should not create any rules when set to false.

# Steps to reproduce

 1. Set ipv4.firewall: false to lxdbr0 config
 2. Clean iptables
 3. restart lxd daemon

After that iptables -L looks like:
```
root@cm[LXD]:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain /* generated for LXD network lxdbr0 */
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain /* generated for LXD network lxdbr0 */
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps /* generated for LXD network lxdbr0 */

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:domain /* generated for LXD network lxdbr0 */
ACCEPT     udp  --  anywhere             anywhere             udp spt:domain /* generated for LXD network lxdbr0 */
ACCEPT     udp  --  anywhere             anywhere             udp spt:bootps /* generated for LXD network lxdbr0 */
```

# Information to attach
configuration of my lxdbr0:
```
root@cm[LXD]:~# lxc network list
+--------+--------+---------+-------------+---------+
|  NAME  |  TYPE  | MANAGED | DESCRIPTION | USED BY |
+--------+--------+---------+-------------+---------+
| lxdbr0 | bridge | YES     |             | 10      |
+--------+--------+---------+-------------+---------+
root@cm[LXD]:~# lxc network show lxdbr0
config:
  dns.domain: cm.lxd
  ipv4.address: 10.93.50.1/24
  ipv4.firewall: "false"
  ipv4.nat: "false"
  ipv6.address: fd42:e025:97ce:7011::1/64
  ipv6.firewall: "false"
  ipv6.nat: "false"
  raw.dnsmasq: conf-file=/etc/dnsmasq.d/local
description: ""
name: lxdbr0
type: bridge
used_by:
- /1.0/containers/elastic
- /1.0/containers/le
- /1.0/containers/mail
- /1.0/containers/mailapi
- /1.0/containers/mda1
- /1.0/containers/mda2
- /1.0/containers/mysql
- /1.0/containers/redis
- /1.0/containers/valvula
- /1.0/containers/webmail
managed: true
```

Regards,
Jan
