### ISSUE TITLE
Problem, huge amount file cache 

### ISSUE THREAD

**Issue by Lychangin** [lxc/lxd#4250]
# Required information

 * Distribution: Ubuntu Server 
 * Distribution version: 16.04.2 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-96-generic
   * LXC version: 2.1.1
   * LXD version: 2.21
   * Storage backend in use: lvm

# Issue description

Hi all. I have on the system, where in the containers a large I/O (Database ex.) There is a large amount of occupied ram
```
              total        used        free      shared  buff/cache   available
Mem:           8.0G        7.5G        485M         32G        2.6M        485M
Swap:            0B          0B          0B
```
And I'm looking at the processes that took up so much memory, but I do not see them:
```
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
postgres  49991  0.0  3.5 458304 294304 ?       Ss   17:18   0:01 postgres: test test 10.0.9.71(55344) idle
postgres  49990  0.0  3.4 451528 287772 ?       Ss   17:18   0:00 postgres: test test 10.0.9.71(55340) idle
postgres  49981  0.0  3.4 451924 287480 ?       Ss   17:18   0:00 postgres: test test 10.0.9.71(55298) idle
postgres  52096  0.0  3.4 450764 285256 ?       Ss   17:32   0:00 postgres: test test 10.0.9.71(53258) idle
postgres  50207  0.0  3.3 451236 285112 ?       Ss   17:20   0:01 postgres: test test 10.0.9.71(58352) idle
postgres  51464  0.0  3.3 451324 283648 ?       Ss   17:28   0:00 postgres: test test 10.0.9.71(45346) idle
postgres  49992  0.0  3.3 453272 283148 ?       Ss   17:18   0:00 postgres: test test 10.0.9.71(55354) idle
postgres 152614  0.0  3.3 445612 282740 ?       Ss   Feb09  23:18 postgres: checkpointer process
postgres 152615  0.0  3.3 445000 280516 ?       Ss   Feb09   1:25 postgres: writer process
postgres  52094  0.0  2.7 451080 227600 ?       Ss   17:32   0:00 postgres: test test 10.0.9.71(53250) idle
postgres  49986  0.0  2.7 453672 226924 ?       Ss   17:18   0:00 postgres: test test 10.0.9.71(55330) idle
postgres  51463  0.0  2.6 449632 222040 ?       Ss   17:28   0:00 postgres: test test 10.0.9.71(45340) idle
postgres  52095  0.0  1.4 454652 119644 ?       Ss   17:32   0:00 postgres: test test 10.0.9.71(53254) idle
root         55  2.8  0.7 101712 61132 ?        Ss    2017 119:16 /lib/systemd/systemd-journald
postgres  51462  0.0  0.4 449560 40084 ?        Ss   17:28   0:00 postgres: test test 10.0.9.71(45336) idle
postgres  52508  0.0  0.4 449816 40004 ?        Ss   17:34   0:00 postgres: test test 10.0.9.71(58292) idle
```
On the main system, I see a large number of  buff/caches:

```
              total        used        free      shared  buff/cache   available
Mem:            62G         10G        1.6G         32G         50G         18G
Swap:            0B          0B          0B
```
Lxc info gives me the following:

```
Name: container
Remote: unix://
Architecture: x86_64
Created: 2017/09/22 11:33 UTC
Status: Running
Type: persistent
Profiles: profile
Pid: 4772
Ips:
  eth1:	inet	192.168.1.1
  eth1:	inet6	fe80::216:3eff:fe18:d305
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 170
  CPU usage:
    CPU usage (in seconds): 976824
  Memory usage:
    Memory (current): 7.39GB
    Memory (peak): 8.00GB
  Network usage:
    eth1:
      Bytes received: 718.94GB
      Bytes sent: 4.66TB
      Packets received: 518617772
      Packets sent: 655774686
    lo:
      Bytes received: 302.40GB
      Bytes sent: 302.40GB
      Packets received: 228068021
      Packets sent: 228068021
```

Container configuration is following:

```
architecture: x86_64
config:
  boot.autostart: "true"
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20170919)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20170919"
  image.version: "16.04"
  limits.cpu: "4"
  limits.memory: 8GB
  raw.lxc: |
    lxc.console = none
    lxc.cgroup.devices.deny = c 5:1 rwm
    lxc.start.auto = 0
    lxc.mount.auto = proc:mixed sys:mixed
    lxc.seccomp =
    lxc.aa_allow_incomplete = 1
  security.privileged: "true"
  volatile.base_image: 03c2fa6716b5f41684457ca5e1b7316df520715b7fea0378f9306d16fdc646ee
  volatile.eth1.hwaddr: 00:16:3e:18:d3:05
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  eth1:
    name: eth1
    nictype: macvlan
    parent: bond0.1009
    type: nic
  root:
    path: /
    pool: lxdpool
    type: disk
ephemeral: false
profiles:
- br1
- root
stateful: false
description: ""
```

I solve this problem as follows:
```
sync && echo 1 > /proc/sys/vm/drop_caches
```
And it helps, but it's a crutch 

It is problem lxc or cgroups?
