### ISSUE TITLE
lxd init --auto doesnt provide option to use existing network bridge

### ISSUE THREAD

**Issue by bitfurry** [lxc/lxd#4332]
Is there any specific reason that while setting up lxd
lxd init --auto

we don't have options to use exiting network bridge ?

**Comment by stgraber** [comment]
We don't add new features to `--auto`, instead you should be using `--preseed` with a yaml input, which is far more flexible and does let you define arbitrary devices against the default, including using any bridge you may already have.

http://lxd.readthedocs.io/en/latest/preseed/

Something like this for the profile would do:
```yaml
profiles:
- name: default
  devices:
    eth0:
      type: nic
      nictype: bridged
      parent: br0
      name: eth0
```

Of course, you should also include any storage configuration you need, so for a standard dir backend, it'd look more like:

```yaml
storage_pools:
- name: default
  driver: dir

profiles:
- name: default
  devices:
    root:
      type: disk
      path: /
      pool: data
    eth0:
      type: nic
      nictype: bridged
      parent: br0
      name: eth0
```
