### ISSUE TITLE
lxd service starts but fails to create bridge If bridge-utils is not installed

### ISSUE THREAD

**Issue by selivan** [lxc/lxd#4338]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04 Xenial
 * The output of "lxc info":

```
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-36-generic
  server: lxd
  server_pid: 26342
  server_version: "2.21"
  storage: dir
  storage_version: "1"
```

# Issue description

If `bridge-utils` package is not installed, lxd service sarts, but does not create bridge.
I suggest this:
 * it should fail to start if it can't find required utils.
 * lxd package should have bridge-utils as dependency.

# Steps to reproduce

 1. Install lxd from standard xenial repository
 1. Run `sudo lxd init`
 1. Install latest stable lxd from xenial-backports. `/etc/default/lxd-bride` is moved to `/etc/default/lxd-bride.upgraded`, configuration is moved somewhere inside lxd
 1. Reboot
 1. Check `ip link` and see no bridge
 1. Try running some containers. They launch, but can't get an IP address.

# Information to attach
