### ISSUE TITLE
Howto migrate to another storage

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#4444]
Hi,
I've 1 container using default LXD storage.
I've a new server with default LXD Storage and another storage called LXD-ZDATA
Now, i want to migrate the container from SERVER1 (Storage LXD) to SERVER 2 (Storage LXD-ZDATA).
How can i achieve this ?
By default, when i migrate, the container goes to SERVER2 LXD Storage, i don't know how to specify the Storage.
Thanks

SERVER 1
```
root@inxovh-hy001 (node1):~# lxc storage list
+----------+-------------+--------+-----------+---------+
|   NAME   | DESCRIPTION | DRIVER |  SOURCE   | USED BY |
+----------+-------------+--------+-----------+---------+
| default  |             | zfs    | zdata/lxd | 34      |
+----------+-------------+--------+-----------+---------+
| lxd-pool |             | ceph   | lxd-pool  | 2       |
+----------+-------------+--------+-----------+---------+
```
SERVER2:
```
root@atxscw-hy006:~# lxc storage list
+-----------+-------------+--------+----------------------------+---------+
|   NAME    | DESCRIPTION | DRIVER |           SOURCE           | USED BY |
+-----------+-------------+--------+----------------------------+---------+
| lxd       |             | zfs    | /var/lib/lxd/disks/lxd.img | 7       |
+-----------+-------------+--------+----------------------------+---------+
| lxd-zdata |             | zfs    | zdata/lxd                  | 0       |
+-----------+-------------+--------+----------------------------+---------+
```

Should i change the default profile ?

```
root@atxscw-hy006:~# lxc profile show default
config:
  raw.lxc: lxc.aa_allow_incomplete=1
description: Default LXD profile
devices:
  root:
    path: /
    pool: lxd <===== to change ????
    size: 10GB
    type: disk
name: default
```

got an error while trying to change it

```
root@atxscw-hy006:~# lxc profile edit default
Config parsing error: At least one container relies on this profile's root disk device.
Press enter to open the editor again
```

I found this way but need to migrate at first the container 

```
root@atxscw-hy006:~# lxc stop test1
root@atxscw-hy006:~# lxc publish -f test1 --alias test1
Container published with fingerprint: a52f8be900912f2917567a6aadcb4121b60534e3746cc68cb03b279ead711df7
root@atxscw-hy006:~# lxc delete test1
root@atxscw-hy006:~# lxc init test1 test1 -s lxd-zdata
Creating test1
The container you are starting doesn't have any network attached to it.
  To create a new network, use: lxc network create
  To attach a network to a container, use: lxc network attach
root@atxscw-hy006:~# lxc start test1
root@atxscw-hy006:~# zfs list |grep test1
zdata/lxd/containers/test1                                                         5.12M   134G   599M  /var/lib/lxd/storage-pools/lxd-zdata/containers/test1
root@atxscw-hy006:~#
```
I lost network when doing this.

i get it back with : 

```
root@atxscw-hy006:~# lxc network attach lxdbr0 inxscw-xmpp002  eth1
root@atxscw-hy006:~#
```

**Comment by brauner** [comment]
Hm, the easiest way would be to add a new flag `-s/--storage` to `lxc copy` which would let you specify a pool on the target server.

**Comment by nlienard** [comment]
this flag ```-s/--storage``` would be also good for ```lxc move``` no ?

**Comment by brauner** [comment]
`copy` and `move` are covered by the same codepath in the `lxc *` tools so that's happening automatically.

We have logic in  `lxd/containers_post.go` that figures out a suitable storage pool based on the profile devices and local devices of the container. That is to say one can send the container even if it has a pool specified in its profile devices or root devices that does not exist on the target. We need to keep this logic for backwards compatibility. This also means that we can't simply override the value in the profile and local devices since we would want to report back to the user when the pool that they targeted failed. But we can't because that would break the valid case of not specifying a pool or just not removing an invalid pool from the profile and local devices. Also, we likely want to have API users have the same benefit.

So, we should add an API extension `storage_api_migration_pool_target` and add a `Pool string` field to `shared/api/container.go/ContainersPost` and to `client/interfaces.go:{ContainerCopyArgs,ContainerSnapshotCopyArgs}` this would let us easily communicate which pool to target even for API-only users.
//@stgraber

**Comment by stgraber** [comment]
@brauner at the API level, we can override Devices during copy/move, so adding `-s` to lxc copy/move should be possible today by just having them add a container-specifc disk with path=/, without requiring any API changes.

@nlienard for now, I think your best bet is to do something like this on your target server:
```
lxc profile create storage-zdata
lxc profile device add storage-zdata root disk path=/ pool=lxd-zdata
```

And then pass `-p default -p storage-zdata` to `lxc copy`. That should result in the new container using the lxd-zdata pool and would be somewhat similar to what a `-s` option would do (except we wouldn't need a profile to hold that device, it'd be directly attached to the container).

**Comment by nlienard** [comment]
Ok i did it on SERVER2 (target)

```
root@atxscw-hy006:~# lxc profile show storage-zfs
config: {}
description: ""
devices:
  root:
    path: /
    pool: lxd-zdata
    size: 10GB
    type: disk
name: storage-zfs
used_by: []
```

so, now, from SERVER 1 (source:

```
lxc copy inxovh-dun001 node16: -p default -p storage-zfs
```
Right ?

**Comment by stgraber** [comment]
Oh, it's a bug we fixed recently I think, the issue is duplicate profiles in container config.

My example was bad, you should just use:

    lxc copy inxovh-dun001 node16: -p storage-zfs

As `-p` doesn't override the profiles but adds to the existing list, so passing `default` isn't needed.

**Comment by nlienard** [comment]
excellent, it worked:

```
root@inxovh-hy001 (node1):~# lxc copy inxovh-dun001 node16: -p storage-zfs
root@inxovh-hy001 (node1):~#
```

On target:

```
root@atxscw-hy006:~# lxc config show inxovh-dun001
architecture: x86_64
config:
  volatile.apply_quota: 10GB
  volatile.apply_template: copy
  volatile.base_image: b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7
  volatile.eth0.hwaddr: 00:16:3e:b6:02:2d
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":493216,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":493216,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br_lan10
    type: nic
ephemeral: false
profiles:
- default
- storage-zfs
stateful: false
description: ""
```

and i can see it on the new zfs pool:

```
root@atxscw-hy006:~# zfs list |grep dun
zdata/lxd/containers/inxovh-dun001                                                          478M  9.53G   478M  /var/lib/lxd/storage-pools/lxd-zdata/containers/inxovh-dun001
```

Thanks !!
