### ISSUE TITLE
Container hangs during start

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#4472]
Still running ubuntu 16.0.4 LTS
```
root@atxscw-hy005:~# lxc --version
2.21
```

After using the lxc copy xxxx -p profile to migrate containers to zfs datavol (instead of default file), i'm experiencing an issue with a container.

the remote copy worked well.

But when i start it, it hangs and never starts.

here the debug of the start

```
root@atxscw-hy005:~# lxc start inxovh-soc001 --debug
DBUG[04-18|18:42:35] Connecting to a local LXD over a Unix socket
DBUG[04-18|18:42:35] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
DBUG[04-18|18:42:35] Got response struct from LXD
DBUG[04-18|18:42:35]
        {
                "config": {
                        "core.https_address": "192.168.2.15",
                        "core.trust_password": true
                },
                "api_extensions": [
                        "storage_zfs_remove_snapshots",
                        "container_host_shutdown_timeout",
                        "container_stop_priority",
                        "container_syscall_filtering",
                        "auth_pki",
                        "container_last_used_at",
                        "etag",
                        "patch",
                        "usb_devices",
                        "https_allowed_credentials",
                        "image_compression_algorithm",
                        "directory_manipulation",
                        "container_cpu_time",
                        "storage_zfs_use_refquota",
                        "storage_lvm_mount_options",
                        "network",
                        "profile_usedby",
                        "container_push",
                        "container_exec_recording",
                        "certificate_update",
                        "container_exec_signal_handling",
                        "gpu_devices",
                        "container_image_properties",
                        "migration_progress",
                        "id_map",
                        "network_firewall_filtering",
                        "network_routes",
                        "storage",
                        "file_delete",
                        "file_append",
                        "network_dhcp_expiry",
                        "storage_lvm_vg_rename",
                        "storage_lvm_thinpool_rename",
                        "network_vlan",
                        "image_create_aliases",
                        "container_stateless_copy",
                        "container_only_migration",
                        "storage_zfs_clone_copy",
                        "unix_device_rename",
                        "storage_lvm_use_thinpool",
                        "storage_rsync_bwlimit",
                        "network_vxlan_interface",
                        "storage_btrfs_mount_options",
                        "entity_description",
                        "image_force_refresh",
                        "storage_lvm_lv_resizing",
                        "id_map_base",
                        "file_symlinks",
                        "container_push_target",
                        "network_vlan_physical",
                        "storage_images_delete",
                        "container_edit_metadata",
                        "container_snapshot_stateful_migration",
                        "storage_driver_ceph",
                        "storage_ceph_user_name",
                        "resource_limits",
                        "storage_volatile_initial_source",
                        "storage_ceph_force_osd_reuse",
                        "storage_block_filesystem_btrfs",
                        "resources",
                        "kernel_limits",
                        "storage_api_volume_rename",
                        "macaroon_authentication",
                        "network_sriov",
                        "console",
                        "restrict_devlxd",
                        "migration_pre_copy",
                        "infiniband",
                        "maas_network"
                ],
                "api_status": "stable",
                "api_version": "1.0",
                "auth": "trusted",
                "public": false,
                "auth_methods": [
                        "tls"
                ],
                "environment": {
                        "addresses": [
                                "192.168.2.15:8443"
                        ],
                        "architectures": [
                                "x86_64",
                                "i686"
                        ],
                        "certificate": "-----BEGIN CERTIFICATE-----\nMIIFWDCCA0CgAwIBAgIQGOkW5Yusi00Ax1JPx+8+vTANBgkqhkiG9w0BAQsFADA6\nMRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRowGAYDVQQDDBFyb290QGF0\neHNjdy1oeTAwNTAeFw0xODA0MDQwNzU5NDRaFw0yODA0MDEwNzU5NDRaMDoxHDAa\nBgNVBAoTE2xpbnV4Y29udGFpbmVycy5vcmcxGjAYBgNVBAMMEXJvb3RAYXR4c2N3\nLWh5MDA1MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsk/lA1xuwuE9\ns4vuGZxPBNv1Fi1l3Q0m+z/cK48ndvz5wAlD3hIP4lbtI3LYmMsFOgy11TOiTA30\ni6Zruqm2pXk43iTP2TUxMpOHWITKvIQqQNWlZGA1T4cRrMRUoaUTGxgzi2F1XxdI\n6S6zPRyvRjRSFoHqklKeq0JHhyZdYFKzqcRo+ymLJ5YTZMnJ22TKUp6fGaydQVeA\nOgM75uosIbRWbj27gCXd015DkCl0yA28B7w+8tPoVpzNdxhuF+6VivPR6NphaqM0\nnuPVD6gtCh6t766p18HfWmgRc2o2+Bm9hjJ7CjeGHGVzei0FumPr/0C8YXJj6QjT\nkWSrXBASk61NfNJz1Q3d3gGKuOuirX4J6sfovBc7pEhh5I+T6YiNIUU1nOQIIu/n\n/TVtJ1PnvRYmwV1e2YHRwEvFCZrBjaFj/19gSpm1QxycXeQiZYizB8vRyrzQjwrz\neUMOw1jItA6ahdzQqMP/pd1NCMaa7RfQt9xs+bpFAUUJBv7/Nh2rFWAwA4exfTR1\nvjWlFE5u2QFzqrnCXSTObX9sWg1tPthLRgzia0WT2DASRyc9ujFxM/WuZ04us39F\nyATtQB7si0XoETreU6NHt4OiAouEEBom2ynsirHlTqLn/poAtFv4jqC1H3Hbo3WN\n/iaDm6Fj70Ej10Z1uM2N2siMe7xAoXkCAwEAAaNaMFgwDgYDVR0PAQH/BAQDAgWg\nMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwIwYDVR0RBBwwGoIM\nYXR4c2N3LWh5MDA1hwQKBwFFhwQKAAMBMA0GCSqGSIb3DQEBCwUAA4ICAQCkLnf2\nPE9yLu2io6OMemIX3UIJlPRC84U0QY05Bz69JaVOeiQ0mrB/UjpfNR+ow1W0JSBQ\nylbmv4QT5zf+jSpa1FA6DhXk41y8NiK5kxww0MzNGKeaLY2ocVoHJ0jy2ZPcnt4d\nySaek5/dufXOywE2MopSiQMOMm5LxaJZW47k5NumaR6WGznMljrlxnNGohHeLDpv\nnlBr7yVFa0UuiNYaqOt/U4BdM/jMKLenvwz4W+rxrp//3hl/pXLCz9xKONqMXU9H\nlvBmM5n6g7oLUczL8MtDqol7fo0Ir7N6/xPzRePVLmHPYrPDZY+LJzFw7/rKesXE\nH0+UkCuCBLoTsnHbXt9u5rUM2bHrcSfHrDg7TnWlBHT+YbTMJkVtQSBLx2mhvS/B\nGTZxFE9i7db73KHqOWjy4Z7G/J4oNoQu9l7YSt/xx4dZz33AcdxM1f1B0D/3gLF7\nqLPgydyuXPN2aC6dV0TxNoXR5H14JjxB5ACKGtIE+vEGQCJdT7EwGOsRxavpeY8m\n5YAHnSGyytJj9q6xRdRx7wjA/VTQWoNC3CyjOG4Ysihf/LbClQmcybOR63feERRh\nVPfmUSxDNE4Vy1b4TmEkDxTtUL5AR9O5lOwGEswTc4fojOjr0H9mSl5kzFjWtPGz\nFllyYpEvOEILYr9eZPrkjzoEOcn/aRc4qWaYIA==\n-----END CERTIFICATE-----\n",
                        "certificate_fingerprint": "4f78527d35e1840f18397a47a51932a93654d01b4d6367006a734bc6bac56931",
                        "driver": "lxc",
                        "driver_version": "2.0.8",
                        "kernel": "Linux",
                        "kernel_architecture": "x86_64",
                        "kernel_version": "4.4.122-mainline-rev1",
                        "server": "lxd",
                        "server_pid": 18477,
                        "server_version": "2.21",
                        "storage": "zfs",
                        "storage_version": "0.6.5.6-0ubuntu19"
                }
        }
DBUG[04-18|18:42:35] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0/containers/inxovh-soc001
DBUG[04-18|18:42:35] Got response struct from LXD
DBUG[04-18|18:42:35]
        {
                "architecture": "x86_64",
                "config": {
                        "limits.cpu": "1",
                        "limits.memory": "4096MB",
                        "volatile.apply_template": "copy",
                        "volatile.base_image": "b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7",
                        "volatile.eth0.hwaddr": "00:16:3e:07:57:f0",
                        "volatile.eth0.name": "eth0",
                        "volatile.idmap.base": "0",
                        "volatile.idmap.next": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536}]",
                        "volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536}]"
                },
                "devices": {
                        "root": {
                                "path": "/",
                                "pool": "lxd-zdata",
                                "size": "50GB",
                                "type": "disk"
                        }
                },
                "ephemeral": false,
                "profiles": [
                        "default",
                        "storage-zfs",
                        "br_lan10"
                ],
                "stateful": false,
                "description": "",
                "created_at": "2018-04-18T16:27:24Z",
                "expanded_config": {
                        "limits.cpu": "1",
                        "limits.memory": "4096MB",
                        "raw.lxc": "lxc.aa_allow_incomplete=1",
                        "volatile.apply_template": "copy",
                        "volatile.base_image": "b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7",
                        "volatile.eth0.hwaddr": "00:16:3e:07:57:f0",
                        "volatile.eth0.name": "eth0",
                        "volatile.idmap.base": "0",
                        "volatile.idmap.next": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536}]",
                        "volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":100000,\"Nsid\":0,\"Maprange\":65536}]"
                },
                "expanded_devices": {
                        "eth0": {
                                "nictype": "bridged",
                                "parent": "br_lan10",
                                "type": "nic"
                        },
                        "root": {
                                "path": "/",
                                "pool": "lxd-zdata",
                                "size": "50GB",
                                "type": "disk"
                        }
                },
                "name": "inxovh-soc001",
                "status": "Stopped",
                "status_code": 102,
                "last_used_at": "1970-01-01T00:00:00Z"
        }
DBUG[04-18|18:42:35] Connected to the websocket
DBUG[04-18|18:42:35] Sending request to LXD                   etag= method=PUT url=http://unix.socket/1.0/containers/inxovh-soc001/state
DBUG[04-18|18:42:35]
        {
                "action": "start",
                "timeout": 0,
                "force": false,
                "stateful": false
        }
DBUG[04-18|18:42:36] Got operation from LXD
DBUG[04-18|18:42:36]
        {
                "id": "5c11e2e7-a451-4bb8-8c38-5a75f02043a7",
                "class": "task",
                "created_at": "2018-04-18T18:42:35.997450317Z",
                "updated_at": "2018-04-18T18:42:35.997450317Z",
                "status": "Running",
                "status_code": 103,
                "resources": {
                        "containers": [
                                "/1.0/containers/inxovh-soc001"
                        ]
                },
                "metadata": null,
                "may_cancel": false,
                "err": ""
        }
DBUG[04-18|18:42:36] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0/operations/5c11e2e7-a451-4bb8-8c38-5a75f02043a7
DBUG[04-18|18:42:36] Got response struct from LXD
DBUG[04-18|18:42:36]
        {
                "id": "5c11e2e7-a451-4bb8-8c38-5a75f02043a7",
                "class": "task",
                "created_at": "2018-04-18T18:42:35.997450317Z",
                "updated_at": "2018-04-18T18:42:35.997450317Z",
                "status": "Running",
                "status_code": 103,
                "resources": {
                        "containers": [
                                "/1.0/containers/inxovh-soc001"
                        ]
                },
                "metadata": null,
                "may_cancel": false,
                "err": ""
        }

```

And then nothing more.

When doing a ```top``` i can see lxd using cpu

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
18477 root      20   0 2041460  32216  16508 S  86.8  0.4   2:38.61 lxd
```
Log is empty:

```
root@atxscw-hy005:/var/log/lxd/inxovh-soc001# tail lxc.log
root@atxscw-hy005:/var/log/lxd/inxovh-soc001#
```

stracing the command directly ```strace -s 64000 -f lxc start inxovh-soc001 ``` is :

```
[pid 30725] read(3, "\201~\0\316{\"metadata\":{\"context\":{\"ip\":\"@\",\"method\":\"GET\",\"url\":\"/1.0/containers/letsencrypt/snapshots?recursion=1\"},\"level\":\"dbug\",\"message\":\"handling\"},\"timestamp\":\"2018-04-18T18:56:25.892888185Z\",\"type\":\"logging\"}", 4096) = 210
[pid 30725] read(3, 0xc420283000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
[pid 30725] epoll_wait(4, [], 128, 0)   = 0
[pid 30725] epoll_wait(4,  <unfinished ...>
[pid 30723] <... futex resumed> )       = 0
[pid 30723] pselect6(0, NULL, NULL, NULL, {0, 20000}, NULL) = 0 (Timeout)
[pid 30723] futex(0xe47798, FUTEX_WAIT, 0, {60, 0} <unfinished ...>
[pid 30725] <... epoll_wait resumed> [{EPOLLIN|EPOLLOUT, {u32=4062867560, u64=140698601549928}}], 128, -1) = 1
[pid 30725] futex(0xe47798, FUTEX_WAKE, 1) = 1
[pid 30725] read(3, "\201~\0\217{\"metadata\":{\"context\":{},\"level\":\"dbug\",\"message\":\"Initializing a ZFS driver.\"},\"timestamp\":\"2018-04-18T18:56:25.900506669Z\",\"type\":\"logging\"}", 4096) = 147
[pid 30725] read(3, 0xc420283000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
[pid 30725] epoll_wait(4, [], 128, 0)   = 0
[pid 30725] epoll_wait(4,  <unfinished ...>
[pid 30723] <... futex resumed> )       = 0
[pid 30723] pselect6(0, NULL, NULL, NULL, {0, 20000}, NULL) = 0 (Timeout)
[pid 30723] futex(0xe47798, FUTEX_WAIT, 0, {60, 0} <unfinished ...>
[pid 30725] <... epoll_wait resumed> [{EPOLLIN|EPOLLOUT, {u32=4062867560, u64=140698601549928}}], 128, -1) = 1
[pid 30725] futex(0xe47798, FUTEX_WAKE, 1) = 1
[pid 30725] read(3, "\201~\0\217{\"metadata\":{\"context\":{},\"level\":\"dbug\",\"message\":\"Initializing a ZFS driver.\"},\"timestamp\":\"2018-04-18T18:56:25.909847036Z\",\"type\":\"logging\"}", 4096) = 147
[pid 30725] read(3, 0xc420283000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
[pid 30725] epoll_wait(4, [], 128, 0)   = 0
[pid 30725] epoll_wait(4,  <unfinished ...>
[pid 30723] <... futex resumed> )       = 0
[pid 30723] pselect6(0, NULL, NULL, NULL, {0, 20000}, NULL) = 0 (Timeout)
[pid 30723] futex(0xe47798, FUTEX_WAIT, 0, {60, 0} <unfinished ...>
[pid 30725] <... epoll_wait resumed> [{EPOLLIN|EPOLLOUT, {u32=4062867560, u64=140698601549928}}], 128, -1) = 1
[pid 30725] futex(0xe47798, FUTEX_WAKE, 1) = 1
[pid 30725] read(3, "\201~\0\217{\"metadata\":{\"context\":{},\"level\":\"dbug\",\"message\":\"Initializing a ZFS driver.\"},\"timestamp\":\"2018-04-18T18:56:25.909428487Z\",\"type\":\"logging\"}", 4096) = 147
[pid 30725] read(3, 0xc420283000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
[pid 30725] epoll_wait(4, [], 128, 0)   = 0
[pid 30725] epoll_wait(4,  <unfinished ...>
[pid 30723] <... futex resumed> )       = 0
[pid 30723] pselect6(0, NULL, NULL, NULL, {0, 20000}, NULL) = 0 (Timeout)
[pid 30723] futex(0xe47798, FUTEX_WAIT, 0, {60, 0} <unfinished ...>
[pid 30725] <... epoll_wait resumed> [{EPOLLIN|EPOLLOUT, {u32=4062867560, u64=140698601549928}}], 128, -1) = 1
[pid 30725] futex(0xe47798, FUTEX_WAKE, 1) = 1
[pid 30725] read(3, "\201~\0\217{\"metadata\":{\"context\":{},\"level\":\"dbug\",\"message\":\"Initializing a ZFS driver.\"},\"timestamp\":\"2018-04-18T18:56:25.936329275Z\",\"type\":\"logging\"}", 4096) = 147
[pid 30725] read(3, 0xc420283000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
[pid 30725] epoll_wait(4, [], 128, 0)   = 0
[pid 30725] epoll_wait(4,  <unfinished ...>
[pid 30723] <... futex resumed> )       = 0
[pid 30723] pselect6(0, NULL, NULL, NULL, {0, 20000}, NULL) = 0 (Timeout)
[pid 30723] futex(0xe47798, FUTEX_WAIT, 0, {60, 0} <unfinished ...>
[pid 30725] <... epoll_wait resumed> [{EPOLLIN|EPOLLOUT, {u32=4062867560, u64=140698601549928}}], 128, -1) = 1
[pid 30725] futex(0xe47798, FUTEX_WAKE, 1) = 1
[pid 30725] read(3, "\201~\0\217{\"metadata\":{\"context\":{},\"level\":\"dbug\",\"message\":\"Initializing a ZFS driver.\"},\"timestamp\":\"2018-04-18T18:56:25.935213201Z\",\"type\":\"logging\"}\201~\0\217{\"metadata\":{\"context\":{},\"level\":\"dbug\",\"message\":\"Initializing a ZFS driver.\"},\"timestamp\":\"2018-04-18T18:56:25.937606163Z\",\"type\":\"logging\"}", 4096) = 294
[pid 30725] read(3, 0xc420283000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
[pid 30725] epoll_wait(4, [{EPOLLOUT, {u32=4062867560, u64=140698601549928}}], 128, 0) = 1
[pid 30725] epoll_wait(4,  <unfinished ...>
[pid 30723] <... futex resumed> )       = 0
[pid 30723] pselect6(0, NULL, NULL, NULL, {0, 20000}, NULL) = 0 (Timeout)
[pid 30723] futex(0xe47798, FUTEX_WAIT, 0, {60, 0} <unfinished ...>
[pid 30725] <... epoll_wait resumed> [{EPOLLIN|EPOLLOUT, {u32=4062867560, u64=140698601549928}}], 128, -1) = 1
[pid 30725] futex(0xe47798, FUTEX_WAKE, 1) = 1
[pid 30725] read(3, "\201~\0\217{\"metadata\":{\"context\":{},\"level\":\"dbug\",\"message\":\"Initializing a ZFS driver.\"},\"timestamp\":\"2018-04-18T18:56:25.978651204Z\",\"type\":\"logging\"}", 4096) = 147
[pid 30725] read(3, 0xc420283000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
[pid 30725] epoll_wait(4, [], 128, 0)   = 0
[pid 30725] epoll_wait(4,  <unfinished ...>
[pid 30723] <... futex resumed> )       = 0
[pid 30723] pselect6(0, NULL, NULL, NULL, {0, 20000}, NULL) = 0 (Timeout)
[pid 30723] futex(0xe47798, FUTEX_WAIT, 0, {60, 0} <unfinished ...>
[pid 30725] <... epoll_wait resumed> [{EPOLLIN|EPOLLOUT, {u32=4062867560, u64=140698601549928}}], 128, -1) = 1
[pid 30725] futex(0xe47798, FUTEX_WAKE, 1) = 1
[pid 30725] read(3, "\201~\0\217{\"metadata\":{\"context\":{},\"level\":\"dbug\",\"message\":\"Initializing a ZFS driver.\"},\"timestamp\":\"2018-04-18T18:56:25.962853393Z\",\"type\":\"logging\"}", 4096) = 147
[pid 30725] read(3, 0xc420283000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
[pid 30725] epoll_wait(4, [], 128, 0)   = 0
[pid 30725] epoll_wait(4,  <unfinished ...>
[pid 30723] <... futex resumed> )       = 0
[pid 30723] pselect6(0, NULL, NULL, NULL, {0, 20000}, NULL) = 0 (Timeout)
[pid 30723] futex(0xe47798, FUTEX_WAIT, 0, {60, 0}
```

1 mn later

```
) = -1 ETIMEDOUT (Connection timed out)
[pid 30723] pselect6(0, NULL, NULL, NULL, {0, 20000}, NULL) = 0 (Timeout)
[pid 30723] futex(0xe47798, FUTEX_WAIT, 0, {60, 0}) = -1 ETIMEDOUT (Connection timed out)
[pid 30723] pselect6(0, NULL, NULL, NULL, {0, 20000}, NULL) = 0 (Timeout)
[pid 30723] futex(0xe47798, FUTEX_WAIT, 0, {60, 0}
```

And still hanging.

On source server, the container is stoped. If i start it, it works fine.

on target server, zfs datavol is present and working fine

```
root@atxscw-hy005:~# zfs list zdata/lxd/containers/inxovh-soc001
NAME                                 USED  AVAIL  REFER  MOUNTPOINT
zdata/lxd/containers/inxovh-soc001  27.3G  22.6G  27.1G  /var/lib/lxd/storage-pools/lxd-zdata/containers/inxovh-soc001
root@atxscw-hy005:~#
```

profile

```
root@atxscw-hy005:~# lxc config show --expanded  inxovh-soc001
architecture: x86_64
config:
  limits.cpu: "1"
  limits.memory: 4096MB
  raw.lxc: lxc.aa_allow_incomplete=1
  volatile.base_image: b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7
  volatile.eth0.hwaddr: 00:16:3e:07:57:f0
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  eth0:
    nictype: bridged
    parent: br_lan10
    type: nic
  root:
    path: /
    pool: lxd-zdata
    size: 50GB
    type: disk
ephemeral: false
profiles:
- default
- storage-zfs
- br_lan10
stateful: false
description: ""
```
and

```
root@atxscw-hy005:/var/log/lxd/inxovh-soc001# lxc profile show storage-zfs
config: {}
description: ""
devices:
  root:
    path: /
    pool: lxd-zdata
    type: disk
name: storage-zfs
used_by:
- /1.0/containers/inxovh-rt001
- /1.0/containers/inxovh-soc001
```

and

```
root@atxscw-hy005:/var/log/lxd/inxovh-soc001# lxc profile show br_lan10
config: {}
description: LAN10 LXD profile
devices:
  eth0:
    nictype: bridged
    parent: br_lan10
    type: nic
name: br_lan10
used_by:
- /1.0/containers/atxscw-le001
- /1.0/containers/inxovh-soc001
- /1.0/containers/inxscw-db004
- /1.0/containers/inxscw-ldap002
- /1.0/containers/inxscw-mx002
- /1.0/containers/inxscw-rdc002
```

and 

```
root@atxscw-hy005:/var/log/lxd/inxovh-soc001# lxc profile show default
config:
  raw.lxc: lxc.aa_allow_incomplete=1
description: Default LXD profile
devices:
  root:
    path: /
    pool: lxd
    size: 10GB
    type: disk
name: default
used_by:
- /1.0/containers/atxscw-ha001
- /1.0/containers/atxscw-le001
- /1.0/containers/dpush
- /1.0/containers/inxovh-rt001
- /1.0/containers/inxovh-soc001
- /1.0/containers/inxovh-xmpp001
- /1.0/containers/inxscw-db004
- /1.0/containers/inxscw-ldap002
- /1.0/containers/inxscw-mx002
- /1.0/containers/inxscw-mx003
- /1.0/containers/inxscw-pro001
- /1.0/containers/inxscw-rdc002
- /1.0/containers/inxscw-xy001
- /1.0/containers/letsencrypt
root@atxscw-hy005:/var/log/lxd/inxovh-soc001#
```

no idea what to do.

**Comment by stgraber** [comment]
Hi,

Can you run `lxc monitor` in a terminal and then in another run `lxc start` again?
When it's hanging, capture the output of the monitor terminal as well as the output of `ps fauxww`.

That should help us figure out what's going on here.

Note that running it under strace is rarely useful as that command talks to the LXD daemon over the API with the daemon then performing the action. So in the case where it's some kernel or filesystem interaction hanging, this won't show anything.

**Comment by nlienard** [comment]
here the monitor
```


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: 2018-04-18T20:10:23.385247826Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/inxovh-soc001
  level: dbug
  message: handling
timestamp: 2018-04-18T20:10:23.395255228Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/events
  level: dbug
  message: handling
timestamp: 2018-04-18T20:10:23.408610506Z
type: logging


metadata:
  context: {}
  level: dbug
  message: 'New events listener: 45056f52-75fe-44ab-afb0-9339befcb44f'
timestamp: 2018-04-18T20:10:23.408837252Z
type: logging


metadata:
  context:
    ip: '@'
    method: PUT
    url: /1.0/containers/inxovh-soc001/state
  level: dbug
  message: handling
timestamp: 2018-04-18T20:10:23.412714887Z
type: logging


metadata:
  context: {}
  level: dbug
  message: 'New task operation: 7b657972-4308-476f-a600-b629c83d8f34'
timestamp: 2018-04-18T20:10:23.417461969Z
type: logging


metadata:
  class: task
  created_at: 2018-04-18T20:10:23.417419715Z
  err: ""
  id: 7b657972-4308-476f-a600-b629c83d8f34
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/inxovh-soc001
  status: Pending
  status_code: 105
  updated_at: 2018-04-18T20:10:23.417419715Z
timestamp: 2018-04-18T20:10:23.417545355Z
type: operation


metadata:
  context: {}
  level: dbug
  message: 'Started task operation: 7b657972-4308-476f-a600-b629c83d8f34'
timestamp: 2018-04-18T20:10:23.417677157Z
type: logging


metadata:
  class: task
  created_at: 2018-04-18T20:10:23.417419715Z
  err: ""
  id: 7b657972-4308-476f-a600-b629c83d8f34
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/inxovh-soc001
  status: Running
  status_code: 103
  updated_at: 2018-04-18T20:10:23.417419715Z
timestamp: 2018-04-18T20:10:23.4177047Z
type: operation


metadata:
  context: {}
  level: dbug
  message: Container idmap changed, remapping
timestamp: 2018-04-18T20:10:23.436862593Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting ZFS storage volume for container "inxovh-soc001" on storage pool
    "lxd-zdata".
timestamp: 2018-04-18T20:10:23.440951043Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing a ZFS driver.
timestamp: 2018-04-18T20:10:23.440872708Z
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounted ZFS storage volume for container "inxovh-soc001" on storage pool
    "lxd-zdata".
timestamp: 2018-04-18T20:10:23.444211064Z
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/operations/7b657972-4308-476f-a600-b629c83d8f34
  level: dbug
  message: handling
timestamp: 2018-04-18T20:10:23.448587739Z
type: logging
```
ps output
```
root     20472  0.0  0.0  65508  1064 ?        Ss   Apr04   0:09 /usr/sbin/sshd -D
root      2941  0.0  0.0  92532  1100 ?        Ss   Apr12   0:09  \_ sshd: root@pts/3,pts/4,pts/8,pts/11
root     22840  0.0  0.0  20968  4060 pts/3    Ss   16:25   0:00      \_ -bash
root      2816  0.0  0.0  36232  3472 pts/3    R+   20:11   0:00      |   \_ ps fauxww
root     11157  0.0  0.0  21060  1680 pts/4    Ss+  18:38   0:00      \_ -bash
root     15635  0.0  0.0  21068  3736 pts/8    Ss   18:39   0:00      \_ -bash
root      2272  0.1  0.1 345936 12104 pts/8    Sl+  20:10   0:00      |   \_ lxc monitor
root     25496  0.0  0.0  21072  4232 pts/11   Ss   18:52   0:00      \_ -bash
root      2396  0.0  0.1 196612 10572 pts/11   Sl+  20:10   0:00          \_ lxc start inxovh-soc001
```
