### ISSUE TITLE
Networking does not work in fresh Bionic container

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#4510]
Tried with LXD v2.21 on Ubuntu 16.04 and LXD v3.0.0 on 18.04 (system upgraded from 16.04)

Networking does not come up and container does not get an Ip assigned on my network bridge.

On both my 16.04 and 18.04 host system, a xenial image comes up just fine.

I have tried provisioning from `ubuntu:bionic `as well as `images:ubuntu/bionic/amd64` with identical results.

`/var/log/syslog` on the host shows in all cases lines similar to

```
Apr 29 20:25:15 krellide kernel: [6056886.886248] audit: type=1400 audit(1525026315.592:23530): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxd-bionic-template-xlemp72_</var/lib/lxd>" name="/sys/fs/cgroup/unified/" pid=19042 comm="systemd" fstype="cgroup2" srcname="cgroup" flags="rw, nosuid, nodev, noexec"
Apr 29 20:25:15 krellide kernel: [6056886.886297] audit: type=1400 audit(1525026315.592:23531): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxd-bionic-template-xlemp72_</var/lib/lxd>" name="/sys/fs/cgroup/unified/" pid=19042 comm="systemd" fstype="cgroup2" srcname="cgroup" flags="rw, nosuid, nodev, noexec"
Apr 29 20:25:16 krellide kernel: [6056887.323323] audit: type=1400 audit(1525026316.029:23532): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxd-bionic-template-xlemp72_</var/lib/lxd>" name="/run/systemd/unit-root/var/lib/lxcfs/" pid=19482 comm="(networkd)" flags="ro, nosuid, nodev, remount, bind"
```

These lines are not present in syslog when provisioning other versions of Ubuntu (Xenial/Zesty). Interestingly upgrading an existing Xenial container to Bionic does not cause any networking issues.

Without knowing much about apparmor, I am assuming that the `DENIED ... networkd` line is an indicator of the culprit here. Any assistance would be much appreciated :)

**Comment by Kramerican** [comment]
Ah beaverballs ... I was really hoping this would not be something specific to my system(s). Anyway, as requested `lxc config show --expanded NAME`

```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20180426.2)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20180426.2"
  image.version: "18.04"
  limits.cpu.allowance: 50%
  limits.memory: 4GB
  limits.memory.enforce: soft
  linux.kernel_modules: ip_tables,ip6_tables
  volatile.base_image: b36ec647e374da4816104a98807633a2cc387488083d3776557081c4d0333618
  volatile.eth0.hwaddr: 00:16:3e:bf:58:5a
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: lxd
    size: 60GB
    type: disk
ephemeral: false
profiles:
- webdock
stateful: false
description: ""
```

Thank you for your assistance as always

**Comment by stgraber** [comment]
Ok, that looks reasonable.

What does `ps fauxww` look like inside the container?

**Comment by Kramerican** [comment]
`ps fauxww`

```
root@bionic-template:~# ps fauxwww
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       263  0.0  0.0  21900  2584 ?        Ss   08:50   0:00 bash
root       273  0.0  0.0  37792  2156 ?        R+   08:50   0:00  \_ ps fauxwww
root         1  0.0  0.0  77484  6004 ?        Ss   08:07   0:00 /sbin/init
root        58  0.0  0.0  42104  2016 ?        Ss   08:07   0:00 /lib/systemd/systemd-udevd
root        62  0.0  0.0  78436  7604 ?        Ss   08:07   0:00 /lib/systemd/systemd-journald
systemd+   112  0.0  0.0  71816  3844 ?        Ss   08:07   0:00 /lib/systemd/systemd-networkd
systemd+   113  0.0  0.0  70608  4024 ?        Ss   08:07   0:00 /lib/systemd/systemd-resolved
root       150  0.0  0.0  61996  3780 ?        Ss   08:09   0:00 /lib/systemd/systemd-logind
daemon     154  0.0  0.0  28332  1568 ?        Ss   08:09   0:00 /usr/sbin/atd -f
root       156  0.0  0.0  31748  1880 ?        Ss   08:09   0:00 /usr/sbin/cron -f
syslog     159  0.0  0.0 197636  2824 ?        Ssl  08:09   0:00 /usr/sbin/rsyslogd -n
message+   160  0.0  0.0  49928  2836 ?        Ss   08:09   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root       163  0.0  0.0 170860 14264 ?        Ssl  08:09   0:00 /usr/bin/python3 /usr/bin/networkd-dispatcher
root       164  0.0  0.0 287980  4496 ?        Ssl  08:09   0:00 /usr/lib/accountsservice/accounts-daemon
root       165  0.0  0.0 1210256 14000 ?       Ssl  08:09   0:00 /usr/lib/snapd/snapd
root       166  0.0  0.0  72296  3652 ?        Ss   08:09   0:00 /usr/sbin/sshd -D
root       173  0.0  0.0  16412  1484 console  Ss+  08:09   0:00 /sbin/agetty -o -p -- \u --noclear --keep-baud console 115200,38400,9600 linux
root       179  0.0  0.0 288868  4480 ?        Ssl  08:09   0:00 /usr/lib/policykit-1/polkitd --no-debug
```

**Comment by stgraber** [comment]
Also, what kernel are you running? You mentioned 18.04, so that's LXD 3.0.0 from the archive running on Ubuntu 18.04 with the 4.15 kernel correct?

**Comment by Kramerican** [comment]
@stgraber Yes that is correct, although the command outputs here are from my test container on my 16.04 system. I just provisioned a container with `lxc init ubuntu:bionic` on my 18.04 system and ran the same commands:

`lxc config show --expanded NAME`

```
architecture: x86_64
config:
  boot.autostart: "true"
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20180426.2)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20180426.2"
  image.version: "18.04"
  limits.cpu.allowance: 50%
  limits.memory: 8GB
  limits.memory.enforce: soft
  linux.kernel_modules: ip_tables,ip6_tables
  volatile.base_image: b36ec647e374da4816104a98807633a2cc387488083d3776557081c4d0333618
  volatile.eth0.hwaddr: 00:16:3e:d3:ff:75
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    limits.read: 40000iops
    limits.write: 10000iops
    path: /
    pool: lxd
    size: 50GB
    type: disk
ephemeral: false
profiles:
- webdockssd50
stateful: false
description: ""
```

`ps fauxwww`

```
root@bionic-template:~# ps fauxwww
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       169  0.0  0.0  21900  2572 ?        Ss   09:54   0:00 bash
root       294  0.0  0.0  37792  2104 ?        R+   09:55   0:00  \_ ps fauxwww
root         1  0.0  0.0  77544  5980 ?        Ss   09:53   0:00 /sbin/init
root        54  0.0  0.0  78436  7580 ?        Ss   09:53   0:00 /lib/systemd/systemd-journald
root        63  0.0  0.0  42104  2104 ?        Ss   09:53   0:00 /lib/systemd/systemd-udevd
systemd+   166  0.0  0.0  71816  3932 ?        Ss   09:53   0:00 /lib/systemd/systemd-networkd
systemd+   167  0.0  0.0  70608  4148 ?        Ss   09:53   0:00 /lib/systemd/systemd-resolved
root       212  0.0  0.0 767224 14912 ?        Ssl  09:55   0:00 /usr/lib/snapd/snapd
root       213  0.0  0.0 170864 14232 ?        Ssl  09:55   0:00 /usr/bin/python3 /usr/bin/networkd-dispatcher
root       217  0.0  0.0  61996  3792 ?        Ss   09:55   0:00 /lib/systemd/systemd-logind
syslog     218  0.0  0.0 197636  2812 ?        Ssl  09:55   0:00 /usr/sbin/rsyslogd -n
root       219  0.0  0.0 287980  4432 ?        Ssl  09:55   0:00 /usr/lib/accountsservice/accounts-daemon
message+   221  0.0  0.0  49928  2880 ?        Ss   09:55   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
daemon     235  0.0  0.0  28332  1612 ?        Ss   09:55   0:00 /usr/sbin/atd -f
root       236  0.0  0.0  31748  1996 ?        Ss   09:55   0:00 /usr/sbin/cron -f
root       237  0.0  0.0  72296  3712 ?        Ss   09:55   0:00 /usr/sbin/sshd -D
root       239  0.0  0.0 288868  4432 ?        Ssl  09:55   0:00 /usr/lib/policykit-1/polkitd --no-debug
root       244  0.0  0.0  16412  1496 console  Ss+  09:55   0:00 /sbin/agetty -o -p -- \u --noclear --keep-baud console 115200,38400,9600 linux
```

for completeness, on my 16.04 system inside the container `uname -r` shows `4.13.0-32-generic`

And on 18.04 `4.15.0-20-generic`
