### ISSUE TITLE
Machine update from Artful to Bionic kills all container networking

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#4514]
Machine level lxdbr0 interface get set intermittently. Sometimes at boot it's there + sometimes it's missing.

At machine level - when lxdbr0 exists, all the veth* adapters appear to be created correctly at machine level.

At container level - all containers are missing their 10.X.X.X address, so no communications outside container can occur.

Let me know best way to debug this.

Thanks.

**Comment by davidfavor** [comment]
This was a fresh Artful install done a few weeks ago, so Netplan being used at machine level.

Details of one failing container.

```
net10 # lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
net10 # uname -a
Linux net10.bizcooker.com 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
net10 # lxc config show --expanded net10-mail
architecture: x86_64
config:
  boot.autostart: "1"
  image.architecture: amd64
  image.description: ubuntu 17.10 amd64 (release) (20180126)
  image.label: release
  image.os: ubuntu
  image.release: artful
  image.serial: "20180126"
  image.version: "17.10"
  volatile.base_image: 41eb905c444d169b9dbb2d8435692699872680441269789ca740ea7c1dbde9d7
  volatile.eth0.hwaddr: 00:16:3e:c7:c1:07
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  david-favor:
    path: /david-favor
    source: /david-favor
    type: disk
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
```
lxd: net10-mail # ps fauxww
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        554  0.0  0.0  22952  4816 ?        Ss   12:30   0:00 bash
root        563  0.0  0.0  37792  3252 ?        R+   12:30   0:00  \_ ps fauxww
root          1  0.1  0.0 225208  8892 ?        Ss   12:07   0:01 /sbin/init
root         51  0.0  0.0 152132 32256 ?        Ss   12:07   0:00 /lib/systemd/systemd-journald
root         85  0.1  0.0  33352  3484 ?        Ss   12:07   0:01 /lib/systemd/systemd-udevd
systemd+    164  0.0  0.0  71816  5244 ?        Ss   12:08   0:00 /lib/systemd/systemd-networkd
daemon      183  0.0  0.0  28332  2392 ?        Ss   12:10   0:00 /usr/sbin/atd -f
root        185  0.0  0.0 287988  6824 ?        Ssl  12:10   0:00 /usr/lib/accountsservice/accounts-daemon
syslog      188  0.0  0.0 193400  4040 ?        Ssl  12:10   0:00 /usr/sbin/rsyslogd -n
root        189  0.0  0.0 1401944 31348 ?       Ss   12:10   0:00 php-fpm: master process (/etc/php/7.2/fpm/php-fpm.conf)
www-data    433  0.0  0.0 1404244 16888 ?       S    12:10   0:00  \_ php-fpm: pool www
www-data    434  0.0  0.0 1404244 16888 ?       S    12:10   0:00  \_ php-fpm: pool www
root        194  0.0  0.0  61996  5500 ?        Ss   12:10   0:00 /lib/systemd/systemd-logind
message+    196  0.0  0.0  49928  4028 ?        Ss   12:10   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root        209  0.0  0.0  31748  3160 ?        Ss   12:10   0:00 /usr/sbin/cron -f
root        213  0.0  0.0 1801680 16904 ?       Ssl  12:10   0:00 /usr/lib/snapd/snapd
root        214  0.0  0.0 170820 17060 ?        Ssl  12:10   0:00 /usr/bin/python3 /usr/bin/networkd-dispatcher
root        217  0.1  0.0 444676 20472 ?        Ssl  12:10   0:01 /usr/bin/python3 /usr/bin/fail2ban-server -xf start
root        223  0.0  0.0  72296  5580 ?        Ss   12:10   0:00 /usr/sbin/sshd -D
root        248  0.0  0.0 288868  6520 ?        Ssl  12:10   0:00 /usr/lib/policykit-1/polkitd --no-debug
root        283  0.0  0.0 105604  7904 ?        Ss   12:10   0:00 /usr/sbin/apache2 -k start
www-data    284  0.0  0.0 109068  5864 ?        S    12:10   0:00  \_ /usr/sbin/apache2 -k start
www-data    285  0.0  0.0 2406708 6868 ?        Sl   12:10   0:00  \_ /usr/sbin/apache2 -k start
www-data    286  0.0  0.0 2406708 6868 ?        Sl   12:10   0:00  \_ /usr/sbin/apache2 -k start
root        477  0.0  0.0  53328  3824 ?        S    12:10   0:00 dnsmasq -d -C /etc/dnsmasq-caching.conf
root        507  0.0  0.0  82268 25520 ?        S    12:10   0:00 /usr/bin/perl -Tw ./qpsmtpd-forkserver --no-rdns --listen 149.56.39.188 --user root -p 25 -p 587
root        520  0.0  0.0  16412  2348 console  Ss+  12:10   0:00 /sbin/agetty -o -p -- \u --noclear --keep-baud console 115200,38400,9600 linux
```
