### ISSUE TITLE
Only 3 interfaces active per container

### ISSUE THREAD

**Issue by jlec** [lxc/lxd#4516]
# Required information

 * Distribution: Ubuntu Xenial
 * Distribution version: 16.04.4
 * The output of "lxc info" or if that fails:
```
config:
  core.https_address: 10.96.64.13:8443
  core.proxy_http: http://proxy.srv:3128
  core.proxy_https: http://proxy.srv:3128
  core.proxy_ignore_hosts: localhost,127.0.0.1,127.0.0.2,
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.96.64.13:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
.....
    -----END CERTIFICATE-----
  certificate_fingerprint: f3f0177430c90e5d3571375bdbe5ba6a48895b60a7e862b69521013924ae31ec
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-116-generic
  server: lxd
  server_pid: 7639
  server_version: "2.21"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu16
```

# Issue description

I am attaching 4 bridges via profiles to a container, but only 3 are accessible at a time. removing one profile and reattaching it, enables the defined interface in this profile and drops the last interface.

# Steps to reproduce

Container config
```
architecture: x86_64
config:
  image.description: SCP Ubuntu 16.04 LTS lXD image (2017-08-06)
  limits.cpu: "8"
  limits.memory: 8GB
  security.privileged: "true"
  user.network-config: |
    version: 1
    config:
      - type: physical
        name: brprim
        subnets:
          - type: dhcp
            gateway: "10.96.64.1"
            dns_servers: [10.96.64.7, 10.96.64.8, 10.96.64.9]

            dns_search: []
  user.user-data: |
    #cloud-config
    bootcmd:
      - mkdir /var/lib/home
    users:
      - name: scp
        uid: "900"
        homedir: "/var/lib/home/scp"
        ssh-authorized-keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCoClD4tHCU00rW6x14+33VBkLQKjxsQtBQKbWKzQQdl+l7tdkJGw7+WORdYDMrX08oI+siXv7PLlKCvh6VMKS3w/lzh2Steo13k27gsJVrmBymR7f65KCB1570Yj/m9RH0T8JiWfSLYSw45LzxPBwu3sZslJ+HEsZe2b0/Q6uPEoHG97gvE6eq52r6XTwfvB9YohFBd3Qse0GN1AzMKKWVyLyetVgj1OTcLc0dNznW3Jquj5s/DQK0tqgYmVtdjBFIrCuSFU5P1tKbV43v2H89ywGhLp0YrN9Mqr5v6OnNWRZ05aOIEOH8t66q75ihhEi6oCdw9nz9s7OVegmQWOzT "Aleksei Philippov"
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBFO5OkWMxDJJTE6mrcDZIfkknZw5+ELss8VeAyWMrtw "Richard Andersson"
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDKD/5HS5eNl88XcnNxDinJ7/+yyvUNqAhph+n1K7m/XOg/uPEm/zB5R6oTC9GSl7A0MKaIgZcAIBxicwLbrafNDqcN7F4CvegRLFc1v0RT7jiLHVycKd1egTLmpNOVSBncnQcgfiLJgO7JKV6HI2+WZVJmilt6RgOjUulOsps/i8taft/koVCX5+b8P4ASzyKsFxIU6RtNbDsrlTHjsFxXdn5il+cSgtFZhw+P8UbACsza1u/C3jNKypcHem85jWfO4o/sirn1sYOHs+FSywiTd68cgYv7ouNZJP12B5YFVOWKLja9xgaSC/iw19EshxSwCLQ4Fwob/3tAG5nhvnq0UE1y62hu7YTsmXVvXsiMfRyCh0u4s+5wVLDZyIZskaDueXlmT4PBZnm7dnjj0Ue1Y2mB6xDHUggAePb32hPtXtHQjfq5CWSPutmQlzITvNMwkiRJFTH5nQeZFQPjRNY5TqKHBNxWJhEN/LpnSb/Q+5tYMKpxf53jE8GawZHau3dACVwxcgYXFjv154wrHQAt+c5BQ0wsrm+IbPF/BLttundyRUcaQNq8y0kCoEojVo5JVAhUekDBwsa/LGbZTHEcXqio+JDLF2xE4vL5PDnGU1uOzG+Ygdlb8OxtYBsS5ECrDe68AbirUl9EdBNArBQBqvGVabOfDmuWWpUUSKvrdw== "Richard Andersson"
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDVYbu6pb8Csw3nJOJNbHZlaWZD9sQKqz7SQeELr7jnrxW9smr9XGqbQDinoIkNbNOPRDDceZsDtIKWwsu7TmGhqcnM7mbmrYaOAM4Y7yRR7l/LAvcQpcLrc8ZfRRZ/sPFAJrP2x5mFVk3cUdpVDh91mOopVm0xw0zRG4JX5KFJGq3xrS8l4f40kTiNnDwmKr3PLQtPK0rW+H5gHaObetq9dSQYDB9voTIrlLiMeNAA601w7Dr5bN5itawKwxyGDRWOa/y3hB+k1sAp4loQZ40MH4h+MJO4sNKn8C27mUEWS5S+p1e+25yXcMyXXqerhydldvQpvpUHzEip8sU1hFn "Oleg Gurov"
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCvt4FW4U0yObRRJkdYYiUm1syUjo1ZWdqeD5iNQ86aB7knp8ojFIjbYT9X6lM2JRKj3aK2Recvi90YfNcMz/fpx/+Y/BrR1EXeFbHa9t+AY1QMTE2wp9HRfYNzvQCFpPD9DwdkHBNa7vMsnbfVi8xjMwoSKxXaO9Yf/+GmQ0GHws4RGIH6Apn/ofDAoDMLVaECkNM7KOm4wJe9Rms74JdeXxt5X3hqxBowipmFDvl6XNX9YkfZ4pxcIFdkZXC2wl4giXq5dnzPDd2nebyy/YXrUrAm0hW/UK/QWOOqG7ys6op4eCT+lKUQgvz7Mme43HqUSh2xvjs5DV+YfNYCSpTkJOAOuno7Pp5UFJ5AlakcxlI2rLLPM8c6liSDtpR9N/Hj6/0DsRCvbR8V8/sGaF9t/8k5SBJnndZO7F+U2DKCleslMDcReL70wj1MwAkNcYoWk2VcmD5n0oyjRacaJCSo0vATL1KwEL6TD4fnp6vodjHgoR6o3zAGXI0b1fRt5gJ2hScx9FRQgiMqSmvPLYUXnvOUzrWEqx6U2H9MRTfW/zYzosdicXWhJle5YZwVKJLNyixdKJDL3XfwsTi7WuIY5/mOX0l443Jrpr5Ps2i6CImCq18AInDZXKkYVnwNGMNXqZYZfRgoP0L4Y5aIw/wt6j2O8DQABCLxwXeH0Zkexw== "Kaushik Shetgaonkar"
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDerzW6HV8XZ+VrOgOdTbSF+vOcFtUPutQdLoJI4e0gnQz56e2/C2g6ahTyrfqCYqNHwwToWzOvN6QMR1/s8fr3XjnVNLUUWBQibloIAeFnRkLMtSrqdtALXRvZufiyMtx3wQOrygpFBJrUeJ81BHXCVF2s+irU+OHa7ghx2Pc4PyOIxcDl5E1sTZ1eN8X/hfAUFH+zdgVm0qdH8LKccs9Jz2LkcrKCjiXtNMnT2b+oqd4KgwTTD8uyL5bFqDcXu7GUwHDWhWUFcoGCLeTb/Bs+hNc6ndR+pJVSHX8qOmT2F/NyoFlg9Mybc0A37haBDzZREO7vWF69bxkHDUAw3abvfmlMt3RCuLMNM6MVZaKtM9+Ey3BFkCo7K7WFIQN86pkxrSWQqmsbhEHYTF1kL92x8pn/iz+uM3JyttFNs0oy9H8PnGAFk2NEQmiiLjbCiwFGM2Ty+7MRdxBjGxG/qSOVMFLuCyR/2j0XXPRkFx20I7VUmhM+FAMkhU4pC5SqliILHd8FTu1GjFpfIOZ2LHcuG4lpibiTkJc+6ZX4HdZwiLuC2b8DJ3qDzs8b0xa8MM6RfR5TMJ+L3Edj/Jnri+EDSv4PoSiBQPSM88QCHE2cZDH3s9iJKac5p26y6Nixg8ej7yTSxtx9q+ppCd0Rrlj5ml5MM3pXT94QMd+EkTmHlQ== "Maksym Nohin"
          - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEAy9pYUE2d6vIQMPCKl7mbKynFqhKFGIvSv/qmQ91CXhzEfQLcQOKWEdAHZ8TfwlQtGyzQrEb5Khrlq+km3gf1qACV96pYt/JB55tnRBt3XzrP/9SaYoEg0rPrBy6qxS0SJo/VDZjyNzBPuetQPRxSDcI28wypjpmPS0MCEWsykOJfTzH3E7BOWMcRdRP5Ca5HFS/4jkyrGqyk+5Xydf3Zl5Y0XNCx77gVoXNSmQ/U+sVFKyCFIplHS9QJDwGq4gaLFDDGd/OdB9oqPKZ9cm/Y5h/vpNvBGN8txxFVpvbe1FQy8ujnL9sp/esVdFihtX93oGpSEQB7q46VVEEekhR361t5IfTZ5KiMabQ8T+5ydl5MZ+qLhwWras/ZRRp4aFrfbbfBtoVpofnN/3a9M9u3ZaHUgQ1fmvfvE0Aicnf7H6LlJYYfVDpC2nrYCKmBCoptVTF3d56/f8DxtgarLQxPkrwo3kRcbcp0wEXeLHOM/D3ywIlo7082+mQaaJBktfsP8nu2MAH366L+kZC1ND+9NtFnhBVeJmjzMC9Rwnf8olyU9UYU1zqPL4ZNPMeLI+zaY/YsHDFyhqDW83dLQuUq2dOHgIDZZF/U6+rT8AAv3e/S0oMBxzLsMBX/5FQ/oOWZxS7N2L65o7s0rhDi6uAxcsh37Es5FLfHwGLWuwdXN1s= "Martin Cawley"
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDyWQrx+3LJ/V1RiMF8E1m+byOy6BCUVBbGcF9e35ViE+nTV53seBlN3WLGUOcVX+/6rN6IrtpyWAunnTDSviStU1P2vla9oRuYApO31pfmT9RClIGShE99YPGILKT9aXzAoTe70VUqBiZbCEE9TGpf6AvdN8EOtv/EImi7sE4NHLXOMtRNLnZyZ3V284ISTqYmI5qJu7PAfhFN99jvwG+TXm/8Wz+t5FGa5iY7kThybmV2IIip07tStqb7NiKTqkUeGD5kjSUWSwJIYHkp/3hoOr8esoW96ZjjmSoQQ413K5jFMMU1qT3k13gZBPolr9UaZzugdJC2e50Kc8+6jsN/ "Ritika Chaudhary"
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO6iMH8TsY8mp99eem5W3biOGPBhSuPMSJUMoOgvA9gl "Justin Lecher"
          - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAgEAgqxafYwUZQeVul3AsoDAW5C+b5JufqgY/2w5JNuUXNkTqCcoU4ul3U7BpEc7aKZKHlEu+7dwx+0AcrvUzpCLtSn1MP4uCRCY7gD2A9EndXC/ni4hg8kMpl5iUYb4kreXDa6tOBTMmyuiv01TUyPDwS34QhcLnthKfiWAwmCM/nJdujaBPVNh8MbF6hwzZn4EycE2K2v53YCSjGBuKLEhPvl38vJ1ZfWVLYLuNxQPLG8CIPxiY1GZ1CpRqqs9+7LWK1HujDtiOsR5DKYKglq5s/RO+ceRcCCReJQfH0cXIjSBiMIPEEw2WvFrftr4sboh7IAjnAWeKpuzwTJ25KqypbfBTbYQRNJj5u2Vd7LWReQ0d/Wxwaitb314WfQsKO91PONF/95o0e8W/dZl1eJ0oa3sXmtmpxYG67hIbDrFv+LHOj7JfF3CAOdrZ6ZfQEm4cmyzOfN+USjxLSMxuBFTU32qaXoxm8TssoSJYP3stwL3/sRvIvmV87STkwuzhG0G9FDAFtqJGadVW6T69q8CCEh9gAUKvirhS7jsugfqQkw8yqi38XCA0yhm9naYIPCQThqP86YhClFTi8Q86shidBjsbWiYq8SiHpszw3Vyd9Z0/THW+VtWpHxyygUlxrhaD+zWhSbZSqF3VZ2wIq0Be4ZiFABWaW9jx3X941WCWGc= "Justin Lecher"
          - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEAzLQJZugeHYzKwG3+m6BtuP9ZfRFnEFWZo2UyZPsr4xBZCq+juniCEw73cmQ7EZ2BPHuEtZ+996UIwdkrpbBbCXLlRDUpY3MdvXh7aHcktHOy5ZJMqu1SEwIbXR0TYNd07TFp5LwGX6/N6u5YYhs6YEiV4PR4ypu0Hxt0UfD4F3epSPqWi2FwZ+KJKMil62PoZOXEeV13NJvjKbF/OZEeOX+dwIDGLfYQ8xoygKrNj35pIO1Ssh2+er7cq1dBiUuhZyM8oQGfdESxdFhdmfxK54sAnU50Rgtiy/g1lm04NHPSPjqx9NmJIOFjc6rny+IcsIT3O61Q3MyRUSjMehz9vIE0mWJTA4FgtWiTHvoGFuEYW3g+UCdhVqVqgZsJUgi61crVHffcDZbTMZD8HFyaoBRRJt8XLq5n30sAOUjJJka1Ha0Fj99bsX9h8vtpZFudVviyyKLdrgopN453t0pnfOgd6i0MCFpx66Ns2mpTxOgUnwAx8XwlqetIzrCrFgQNuyCJNE5kUlHZxqMAYQ7ksSXtGxZxKS48+KAfzssCT0voyw0Na8dJkVB/Dqz6oHRBd8UCN52qrhysL5SHKbdXvwUdwpoqLDT1Jg3++5BtGlnOSdI7qtxaruOTJY7XZKL6the317qj6ui9GXlFDddOFwihsEXvP+fr44Yr8F2DOTs= "Justin Lecher"
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC0iCIkKjaXKl6Rs6cpQDqGO9JEi3CEitoXQ5plNJLGj "Vijay Arangarajan"
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDK9MqumSLmFECLBUIY+utGtc53VSdkHzH12fvHJdjtfrD8i78Wkl3PTNpiC7C6k2a1WpXxEMZvJRz2b/Tj8Gxj1MY3GG//s5SXv4J9kRElyNbe2K8EX911tNO/xNe8/HThJZSLbH7/btYx3W4wFC0rg+WwJ6icTdsG2O/t0dr2j20zDB/x1k0ITQeI3CxRXojN5TCaxAwRTJYLwCdbnqYLLGAdePmudj4+/WSrFoL1aI1o5fG8Izmz/fQG/pvjrjUc59cjgUH3UqJEC/q0sX4ybbO7/TBX1NAB3xW1qZc1zLiK63D9mAUhFZKkwYCSQpj+sL6LLlwPIsu1FLvK0jgPxwyp04h/N2eptGT4glwryMvhQznedJotgQUcBAIESmUvQ7uJwY6YgtUrc3e3WmsN7Cq6E9SWDa+lx/XKp2EKnDmE9N98wgiBzxs16RxEZHA/fMb6j982e2c3xxvzWlGu60FswSqCZI+MwyHwiPYQdW7hxikMeKC34kvjGH+X+FHeqjzJKcJ+ht/wM8tIl7lPV6m4oR9ewTvqP7Q7Yk/4hkuxBd2v1lhwZP6zw4RW2NQ5TrZBGx1B3CrWg6xUFvWK1nlf0uJX4/S7doTB5Jkx59KV15iltNDgPV5NkIAcJjJAN//GckbvCmp7BsNwy5sY1hKviQr/SSPQZGYdmz2lyw== "Vijay Arangarajan"
          - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEAyRbTEf8wGwd+yezJ9S2f01aKGfvkKft0EGnzyCc8qmGf35paRDRhlERnVwVIpZrXNVQxb4Jvwib+5IK7UYhT7skoA/NgsA+32zWYEaID351anKJPVVikWhJEb25YhZFfqqgfUBGALcBoRBFfICVa1orkr/FiYyok75uMGPrrqDAo626Jn2DFJphL3bbmOHRP1V8y8liO3BBY/zUDtyJHIH1SzAPMxhV3BpTfmQufBnr6QU/zxRSqe30tJyE5bXzn2wYv6JxKriGIKSbIybeAhsf4gC7VoTLe+qXJJ3OM8gFL4WRViq380N6qR5Z9J6DvEGO1bf+VCgKbJFeIn8l/I4Dy4TpIC6kGxrXI3pL1hmjr9r3VaiQr2vhMuXIA5K3KZCZa+ZC7sXXFYIts4mAaWsfMVIH+H3pwPQfUuLXV2X7Azsj1b6WPo6fxPa6EnoN83aSagbWB8FawMQSOa6DGa7vciPhulGjOcVXJHSyyhLv4t6lhFcoziiESyYbjG/ZQB4Qa66vvj9xWvcbw0CNanqpBjAj96V71ZZDPTezZ28ul08MFZxTTnoArCfI14quWrljXzD6VH7qKeeLOCxC2GSL6RnuhmOKey+sz//BVe3a76/HqRNHAfknv30gfhhmZfPRKGUSvBIsGXnDaKmzM0ADN0Xk0CHCq7lnxB1V54jE= "Sandra McLaughlin"
          - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAgEAjQNAQfspRcBSi964uWNyZcGBr+NTbwDyTwMtb1X2mKalFOXY/gnh9E5BDV2VICkYlCC+0EpZhDbt9lfa0rNQm1vSgDEysTja6ObUgBEmexp+Q90Wj8VWB0y3RRJ+6rwhYMVoa+TTLchP6m6AX6EllgIJm6nMR8vfsdHi3/SzCxFNWGs//el6a3a/qPnkx81eNOuZjPqSRXDH5mEAOQVTjO/vKkgQDRwj6NJXXzAR3DfYrZftXU645ZmRZnF518br7vPBhov0hkPHx4ur6ymqRUZzLcFlD2zekLzsXBKR50qR2e4O26zmPgNEx8JzaDRw0vhnR7AJ/AxiNhVACTBC4uAKePn5wDa0AhLAThBkymkTpyK/BxE3G5F/B7+8pf+2982XgBidUeFX+RMuJO5VZTubEClq+fQByWjDPlOzuJ34PU3jrwzZXkDMV4DZbx/kPmGiwnMIxSRU2p/7htuSdNYg/8OK1e0pNpIjGMqecDkG93yvWL7SG+2loUsVIDDg1OhVr1DG+fSGZ9lLO8DkPN1hM3ztUZHXtPEK+bA438762XqY9ZmkLZKMoJp5MmLkRdZlHmkH3DJQJ1Crur1ZnH3MI0l5UByrJAssCca2UKtPtnWyhC2JZjhdN522aGuo3M5cMXSsGg4TSsaRH0JmLZMQBkSCXlZ1S5Qt7b4nKUs= "Sandra McLaughlin"
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQsIHq4+wrC43GuYE6UecjkljbS7Sda7LpdqpXYewiF72YUTmo24VKEBnd/fQ3thwiLZzxERS0CpMrJm1BwtZ+xjRv3OJrUX1rF2Aiti/7puoeYlCaSWtSjaLvmsZaeFP4C4iANdo6pNppa8ZPyVbXI1wk9thmS70buGtiyjhtNxfH2QlyWBt0sgyIIw3v4NGHHoE5uQEWMN1G9R91ATyL0U1cs7XKG95FTZAgQWCykosptT31plHtZtxQuReROmrE51lsQgAMMlsISrhYQbf40SWUtoAbbnVkEhCYdDLZHPCmLKEuYXPA+FE1idAZkQh+A7WK7mptnDY9V61UqcrM0qX6px1v8yA6rlYYBAoU53YNFK2BKYyGwxVcOgDlmn0QaRBqbYzBMDSy3yMarmZy5v9IYE1nwb52trtphBpQ3AedvvRsQuuTX3MMyQIaFu38Mx4gZKcbSf4tvCBpHufSpjHo5bi0ZHuAuvUJ0A1Zuee+G1gLa6yV1KN5cYpOBdYyAeG9ElhV4gdZrLlJIVfRx2enXOk6dgky7ieSHjRr/FJPKpCx8uwL1+iBptXCXIcgjJhIQF6egf+g/bCc00i+a8H2tNP8xvz/8YPWCNBRQxxrhsvFOfo+ZVg/IbvHHbZHZr+HbRnQdQKtEChwFO4GaYSQ5wNt+1mNtsRJxgOcjQ== "Pankaj Jha"
          - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEAm1/MMky4CmG4tqwS9pyzEXFfdnRX7hRZyI8z1UQs8Wn2KhPLnUfNiJBlYq+/BtMcyuxmymBnQFlYXXZxDRw9IUoKLWdnPfzdc+iORmdFDusF40o1ckcn2Aq4f5X3JD51nzk6CnJfgSTHDs59ium8/PaZo11kB/4yekHVaS1rQXlCb7fLAfhfyJXiXf3kD89ICV1dsrzAPEYpykB8QfkIe2KEfDbxwRWNBcdIR13m5PVaVa24PlMV2DaJd+s45XIY12ZYp84+UvDC8Xa7UX2twcJz5Jd7Nb+GRpy9ziY5f29zcv+a/jVfEZ5yAhWeFcB8SvPqy38V9I6zhltGRZyY+mRrMJnLHq88KIPKS8Kq6NjjkcEpTPmRvjYkzJnbff/UE0bVYnuB4qEQ4Q3driF2t3kqk7leK4KmzH3W43w1d+utB4z9Hi56QyzvpwZExmQBTMRB3kQYOJC07NAGajxUeJM+lEgXbMskXEDpVguerK2/4hQU0kuJfc42eR9BUqnyUOWr9AavxAA1kh6IkXe0j00V5fKmbXKGmoq+BR/SaTW/ULTnZFqhbW9x5rmsTgzhTs85UyxgiWBRzIt2V9+B3SMvbYfgWr8JDrTBdKlmMofzornFeDodm/kq+Te+qugAaIx0jnW2Yak2p+RJGApD1shlzZOyTJK2qLM8V3/UUUc= "Sathish Ranganathan"
          - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAwtvJNeZMdExp29UGSNm35zqD344HOKEbuY4IttQJ3h956uyoJVHniUgQvWgnjOOfu9Osob5x6A4+VIm59plzw4pnp5dHl85gvsi+AnbZnIiy1JIW+IU+58qRXh0+ofuB6+6zLFYj22KSStzZ8muJV3tb/czTro0wIEFA9OmBYL+lSkN36Y8OnrjFXHdHf8/VY485KRSvjJ8ECt74c8xDYqqpmOQowIWiYvftNpmGWqc8p1aIOf84rO4DyErXxewg+4E5ibupCWU8Qb39hBUiVmhnsSyM/lq6RIkDh90aqQ2GUZ0P5XvSQakXbmtJrhHcSbJ939ow5y7QRcWNAi505w== "Rohit Mukherjee"
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDH5kSQhHzPXLFY5LQJiKcZkIYKGZJZDDJVgQfKmnhPrlEH6ZhuLONs+eGBKo5tgVfqGlQHAu7HCFEYRblEWRt/LJJXrhANQJqh4mEd0FlUn271ohT2kqnm3xk7uLXRwDGF7PzFSK3dGP/Awdq+b1jW1RP53jGv9w3yjhU7tC01tQ63d6RiWhfk1v8T+eGk7enCT365BhL8P6fBl0MRGHe5fl0dfpOKfhwo/yZH/fYWP21/Nfb6OeQHjcFQ5thc9hxhUrj9rIqfyq8ranLi2tzta4OS+wf0G78hdElxhvPXn0dlaW/mF4touOFeOvlgYXqnwzE6we72Yk7MtRjExYe9 "Suyash Janoriya"
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCvqGlw2pKi/smwQoGn8x+lAKDUS6JTQBhH0lAoLtmMSAUbWP0MabQ42WRn4B1qExiRLJNecjCnIpvMR8IqdUT5tS1ATlWrXo9PrDocXZVP0SHw0J4NpgVt9urxtg+OWLNu0XmK10rFKSBOzEbXchkugBGx8pJl8Xz+3wbV0pkEbAKFE6RoCn2rgbNJp6MHRJAHxYKE3HEq1VOr5V2bpurBppwZelUH7mtt9MO+Ak4zptlJjYSI9pbqGQEf9NW/5iP+xNmhaCPrDulZ9XSbGHDIp0mpz9RNBQLBVSJAKDObrgYyATS2aICSGbTscH1DhAaCdrlza3Ww+L5ebbvN2ebMFFhpXFjlaJFixAPrDNJKv2eg2OsQwecB3env7NOfOSgn2cMD2Dv5QLUfh1XWodkAQP+fCf+5OK2MnYf6ebXraZJcegVNvbF2fb6oOJNvn2EF5IDfTklVwqJNJM3i1PW5+/IPrWtfr0F2m0ZkFLscEyQaYFwGBtCOrzWbgyYnBWBJlM1CaSM/QcuTTtwqPE1XZa5fs5X2tSPZlkao3dNxE30sleC5H28n6iiN3/0sE3viCpYJoaOty7V0QXYp2HVeekl9xGr/Uwi3FkzdOxKlkgN1UFhU/9oxcEortgMzp8Gyh8kE+UlpzeIPk7QZq2X0TUhfYTZq7LwGH2yVset1Cw== "Aleksandr Usov"
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/d1LbG0CfLDvSQSlCa7t+96yE35uRFr/MKSSr7NkmNpiIQX6/WxScbpz4fNPbUAcl2pkpm6vjrX4X08VWTblNZIVl8D/FEqWkrbv5shF4Ze6viWULCl50m1okLfYJjln5jKUq4n/+iZxTKgV/cg1X6z/5Qy9r/72OVZGLtI2yLmFuNr21r4kJZmdQEym6jA/OBmQodzlzmBOoepxrWoRSwgNzWU3cehwwnhcteLYjo9KI9xArvD4YLb7iiTTd7lkj0H7rVGd07AaZ655iHYVBmnbQ7LoILCobZvCzTN86cvml4q5Cd1OeXnceg4AkK7X4ueMIkwBedCxSWTfERzjh "Stanislav Gabenov"
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
  volatile.base_image: 7e142471d1ac533ecf91ea0d7709bb0a7945c4eda6ff0690e23ce5d5c53ed985
  volatile.brext.hwaddr: 00:16:3e:e7:72:95
  volatile.brmgt.hwaddr: 00:16:3e:44:10:49
  volatile.brprim.hwaddr: 00:16:3e:12:e4:e9
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  backup:
    path: /mnt/backup
    source: /mnt/backup
    type: disk
  brext:
    name: brext
    nictype: bridged
    parent: brext
    type: nic
  brmgt:
    name: brmgt
    nictype: bridged
    parent: brmgt
    type: nic
  brprim:
    name: brprim
    nictype: bridged
    parent: brprim
    type: nic
  data:
    path: /mnt/data
    source: /mnt/data
    type: disk
  root:
    path: /
    pool: default
    type: disk
  shared:
    path: /mnt/shared
    source: /mnt/shared
    type: disk
ephemeral: false
profiles:
- M
- scp
- data
- shared
- net_prim
- net_ext
- net_osdmz
- net_mgt
stateful: false
description: ""
```

In the container, after boot, the network is defined as
```
$ ip l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
17: brext@if18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:3e:e7:72:95 brd ff:ff:ff:ff:ff:ff link-netnsid 0
19: brosdmz@if20: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:3e:44:10:49 brd ff:ff:ff:ff:ff:ff link-netnsid 0
21: brprim@if22: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:3e:12:e4:e9 brd ff:ff:ff:ff:ff:ff link-netnsid 0
```

Running `lxc profile remove admin00 net_mgt && lxc profile add admin00 net_mgt` changes the configuration into

```
$ ip l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
17: brext@if18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:3e:e7:72:95 brd ff:ff:ff:ff:ff:ff link-netnsid 0
21: brprim@if22: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:3e:12:e4:e9 brd ff:ff:ff:ff:ff:ff link-netnsid 0
73: brmgt@if74: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:3e:44:10:49 brd ff:ff:ff:ff:ff:ff link-netnsid 0
```

The brosdmz interface is exchanged by the brmgt.
