### ISSUE TITLE
error: ZFS storage pool "production" could not be imported: cannot import 'production': no such pool available

### ISSUE THREAD

**Issue by elbrinke** [lxc/lxd#4528]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 2.21
   * LXD version: 2.21
   * Storage backend in use: ZFS

# Issue description

I created two storage zfs storage pools. The default storage pool and a storage pool called "production" which is mounted to a LVM storage location inside the server. 

# Steps to reproduce

 1. Reboot Server running Ubuntu 16.04
 2. LXD fails to start up with error: 

```
lxd.service - LXD - main daemon
   Loaded: loaded (/lib/systemd/system/lxd.service; indirect; vendor preset: enabled)
   Active: activating (start-post) (Result: exit-code) since Thu 2018-05-03 09:30:28 SAST; 8min ago
     Docs: man:lxd(1)
  Process: 17862 ExecStart=/usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log (code=exited, status=1/FAILURE)
  Process: 17851 ExecStartPre=/usr/lib/x86_64-linux-gnu/lxc/lxc-apparmor-load (code=exited, status=0/SUCCESS)
 Main PID: 17862 (code=exited, status=1/FAILURE);         : 17863 (lxd)
    Tasks: 6
   Memory: 2.3M
      CPU: 117ms
   CGroup: /system.slice/lxd.service
           └─control
             └─17863 /usr/bin/lxd waitready --timeout=600

May 03 09:30:28 samwise.eighty20.network systemd[1]: Starting LXD - main daemon...
May 03 09:30:29 samwise.eighty20.network lxd[17862]: error: ZFS storage pool "production" could not be imported: cannot import 'production': no such pool available
May 03 09:30:29 samwise.eighty20.network systemd[1]: lxd.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by stgraber** [comment]
What does `zpool status` show you?

**Comment by elbrinke** [comment]
**zpool status:** 

```
  pool: containers
 state: ONLINE
  scan: none requested
config:

	NAME          STATE     READ WRITE CKSUM
	containers    ONLINE       0     0     0
	  containers  ONLINE       0     0     0

errors: No known data errors

  pool: default
 state: ONLINE
  scan: none requested
config:

	NAME                              STATE     READ WRITE CKSUM
	default                           ONLINE       0     0     0
	  /var/lib/lxd/disks/default.img  ONLINE       0     0     0

errors: No known data errors
```

**Comment by elbrinke** [comment]
**sudo zpool import production**
Results:
`cannot import 'production': no such pool available`

**Comment by elbrinke** [comment]
When i run: **sudo zpool create production /mnt/containers/lxd/production.img**
I get:
```
invalid vdev specification
use '-f' to override the following errors:
/mnt/containers/lxd/production.img is part of potentially active pool 'production'
```

**Comment by elbrinke** [comment]
**sudo lxd --debug --group lxd**

```
INFO[05-03|11:03:31] LXD 2.21 is starting in normal mode      path=/var/lib/lxd
INFO[05-03|11:03:31] Kernel uid/gid map: 
INFO[05-03|11:03:31]  - u 0 0 4294967295 
INFO[05-03|11:03:31]  - g 0 0 4294967295 
INFO[05-03|11:03:31] Configured LXD uid/gid map: 
INFO[05-03|11:03:31]  - u 0 100000 65536 
INFO[05-03|11:03:31]  - g 0 100000 65536 
DBUG[05-03|11:03:31] Initializing and checking storage pool "default". 
DBUG[05-03|11:03:31] Initializing a ZFS driver. 
DBUG[05-03|11:03:31] Checking ZFS storage pool "default". 
DBUG[05-03|11:03:31] Initializing and checking storage pool "production". 
DBUG[05-03|11:03:31] Initializing a ZFS driver. 
DBUG[05-03|11:03:31] Checking ZFS storage pool "production". 
DBUG[05-03|11:03:31] ZFS storage pool "production" does not exist. Trying to import it. 
INFO[05-03|11:03:32] Unmounting temporary filesystems 
INFO[05-03|11:03:32] Done unmounting temporary filesystems 
INFO[05-03|11:03:32] Closing the database 
INFO[05-03|11:03:32] Saving simplestreams cache 
INFO[05-03|11:03:32] Saved simplestreams cache 
error: ZFS storage pool "production" could not be imported: cannot import 'production': no such pool available
```
Therefore lxd cannot start. _Why would lxd not see the pool anymore?_

**Comment by stgraber** [comment]
LXD can't know that your pool is file backed in a non-standard path, so it can't bring it up.

Running `zpool import -d /mnt/containers/lxd production` should get the pool to show up again, at which point LXD should start fine.

**Comment by elbrinke** [comment]
Is it better to rather create zfs pools on block/devices and not zfs images (.img)...?

**Comment by stgraber** [comment]
That's unfortunate. LXD did start after you did the `zpool import -d...` though right?

**Comment by stgraber** [comment]
If that's the case, what does `lxc storage show production` get you?

**Comment by elbrinke** [comment]
**lxc storage show production**

```
config:
  source: production
  volatile.initial_source: production
  zfs.pool_name: production
description: ""
name: production
driver: zfs
used_by:
- /1.0/containers/IPA
- /1.0/containers/MYSQL
- /1.0/containers/NFS
- /1.0/containers/NS1
- /1.0/containers/NS1/snapshots/NS1-2018-05-02-PRODUCTION
- /1.0/containers/NS2
- /1.0/containers/NS2/snapshots/NS2-2018-05-02-PRODUCTION
- /1.0/images/29d86a955112c2aa2eafc857f98688f65c5962f9912aee98049895c46f155628
- /1.0/images/3605ed8ffc7bd4b942a0f33f6162256370f57c925e1f14ff135bdbc2b1f88360
- /1.0/images/97212795032475aab73c62d2c36c145e8c5ba5965db7af492cb86a274dafed35
- /1.0/images/bdfef38dbeeecbdc4e635b0c5a8e03e96fe6d6891af15b40974249174bb1bb5c
- /1.0/images/be7cec7c948958adfbb9bc7dbd292762d2388cc883466815fc2b6bc06bf06f5a

```
