### ISSUE TITLE
Update container device limits by profile

### ISSUE THREAD

**Issue by kaszuba** [lxc/lxd#4547]
Hi, im looking for solution which allow me to change device limits by changing profile attached to container. If im correct it is possible only for root device (when containers use the same backend) or when containers share some directory/storage.

Maybe you could implement solution which allow to create profile with device limits only.
For example it could be additional type of device, something like none but only for limits, and it will include device limits from parent profile only when device with such name exists in container.

I mean about something like this:
- containers with attached additional directory
```
test1:
  devices:
    ssd:
      type: disk
      path: /ssd
      source: /mnt/ssd/test1
profiles:
- ssd-speed1

test2:
  devices:
    ssd:
      type: disk
      path: /ssd
      source: /mnt/ssd/test2
profiles:
- ssd-speed2
```

- profiles with different limits for ssd device, something like this:
```
ssd-speed1:
  devices:
    ssd:
      type: limits
      limits.read: 1000iops
      limits.write: 1000iops
ssd-speed2:
  devices:
    ssd:
      type: limits
      limits.read: 2000iops
      limits.write: 2000iops
```
