### ISSUE TITLE
Strange behavior on publishing image with LVM storage

### ISSUE THREAD

**Issue by esosan** [lxc/lxd#4570]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-124-generic
   * LXC version: 3.0.0
   * LXD version: 3.0.0 (snap)
   * Storage backend in use: LVM

# Issue description

I use as storage pure LVM, without thinpool. My VG (it's a nested vg) is named pool_0 and my lxc storage pool0.
On publishing a snap image (or copy the container) I have this error:
Error: lstat /var/snap/lxd/common/lxd/storage-pools/**pool_0**/snapshots/srvG/snap0: no such file or directory.

It's look as the scripts use the wrong variable... 

As workaround I soft linked pool_0 with pool0 in /storage-pools/ and everything work well (I deleted the link just after the image publishing).

# Steps to reproduce

 1. lxc snapshot c1
 2. lxc publish c1/snap0

# Information to attach
my storage config:
```
config:
  lvm.use_thinpool: "false"
  lvm.vg_name: pool_0
  source: pool_0
  volatile.initial_source: pool_0
  volume.block.filesystem: xfs
  volume.size: "3221225472"
description: ""
name: pool0
driver: lvm
```

Regards, Davide
