### ISSUE TITLE
Proxy Device -- Multiple devices issue and list

### ISSUE THREAD

**Issue by Wulfklaue** [lxc/lxd#4612]
Is it possible to have a command or list, where one can see a list of the ports, that are connected using the proxy command.

```
lxc config device add a1 http proxy listen=tcp:0.0.0.0:8080 connect=tcp:127.0.0.1:8080
```

So its easier to manage what proxy is doing what? One can manually name the device to sidestep but this is also missing from the documentation. And then people need to figure out how to pull the device names. In other words, it lacks a bit of user easiness.

Another issue i noticed:

```
 lxc config device add a1 http2 proxy listen=tcp:0.0.0.0:8081 connect=tcp:127.0.0.1:8081
 lxc config device add a1 http3 proxy listen=tcp:0.0.0.0:8081 connect=tcp:127.0.0.1:8081
```

Assigning multiple proxy devices with the same port ranges, can be a issue and normally need to error stating that this configuration is already present.

**Comment by stgraber** [comment]
`lxc config show a1 --expanded` would be the expected way to see all configured proxy devices, same as with every other device types.

We can't easily validate port availability on the system when updating the configuration but I'd expect the proxy to error out when attempting to bind the port a second time. Will take a look and see why it wouldn't be doing that now.

**Comment by Wulfklaue** [comment]
@stgraber 

>lxc config show a1 --expanded

That works. Thanks. Just a bit hidden :)

> Will take a look and see why it wouldn't be doing that now.

Here is the result:

```
  http:
    connect: tcp:127.0.0.1:8080
    listen: tcp:0.0.0.0:8080
    type: proxy
  http2:
    connect: tcp:127.0.0.1:8081
    listen: tcp:0.0.0.0:8081
    type: proxy
  http3:
    connect: tcp:127.0.0.1:8081
    listen: tcp:0.0.0.0:8081
    type: proxy
```

Clearly we have http2 and http3 bound on the same ip and port. Its too easy for people to mistakenly bind several ports and then spend potentially hours trying to figure strange responses. So any errors on attempting that is very much appreciated.
