### ISSUE TITLE
Unable to remove device from container with dead sshfs mountpoint

### ISSUE THREAD

**Issue by dnegreira** [lxc/lxd#4620]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info":
```
config:
  core.https_address: 10.31.129.152:8443
  core.trust_password: true
api_extensions:
- id_map
- id_map_base
- resource_limits
api_status: stable
api_version: "1.0"
auth: trusted
auth_methods: []
public: false
environment:
  addresses:
  - [removed]
  architectures:
  - x86_64
  - i686
  certificate:  [very cool certificate]
  certificate_fingerprint: [very cool fingerprint]
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-51-generic
  server: lxd
  server_pid: 110416
  server_version: 2.0.11
  storage: dir
  storage_version: ""
```
```
lxc config show container
architecture: x86_64
config:
  volatile.base_image: c8948ee42ef1de2b8a5258cfe0b668ae47abb16a365eb50f1bc9ef9f3849bd32
  volatile.eth0.hwaddr: 00:16:3e:37:75:c3
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  data_backup:
    path: /data/mount_sshfs_backup
    source: /data/backup
    type: disk
  root:
    path: /
    type: disk
  vg_cache:
    path: /data/postgres_ssd_tablespace
    source: /data/vg_cache
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
# Issue description

We added a disk device on a container, based on mount point on the host with sshfs, the sshfs dropped and we cannot remove the device from the container anymore without stopping the container.

```
lxc config device remove container data_backup
error: Error unmounting the device: Error calling 'lxd forkumount 64528 /data/mount_sshfs_backup': err='Failed to run: /usr/bin/lxd forkumount 64528 /data/mount_sshfs_backup: Error unmounting /data/mount_sshfs_backup: Invalid argument'
```

# Steps to reproduce

 1. Step one
```
sshfs user@server6:/backup/ /data/backup/ -o allow_other
lxc config device add container data_backup disk path=/data/mount_sshfs_backup source=/data/backup
```
 2. Step two
reboot/restart remote server or reset the ssh connection somehow

 3. Step three
unmount sshfs from the host
lxc config device remove container data_backup
