### ISSUE TITLE
Many syslog entries for some, but not all containers: Failed to load config for xxxx

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#4624]
Ubuntu Bionic
LXD v3.0.0

Got errors in my backup jobs today on one of my hosts where lxc returned a notfound error when enumerating containers. This worried me and when doing `lxc ls` on the system a bunch of containers were listed as having ERROR status.

I checked my zfs backend in case something might have gone wrong with my storage, but that was all fine, and I could still reach my containers (webservers)

I restarted the lxd daemon `systemctl restart lxd` and now all containers listed as running and all seems to be well.

In my syslog I have entries going back a couple of days (every 5 minutes) :

```
Jun  4 12:25:06 jadzia lxd[8074]: Failed to load config for containername
Jun  4 12:25:06 jadzia lxd[8074]: Failed to load config for anothercontainer
etc ...
```

After the restart I see the following messages in the log, but I suspect this is nothing to worry about:

```
Jun  5 00:07:28 jadzia systemd[1]: lxd.service: Found left-over process 14714 (lxd) in control group while starting unit. Ignoring.
Jun  5 00:07:28 jadzia systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
```

So yeah ... Any idea what happened here? Anything I can dig around in, and help you guys figure it out? :)

It should be mentioned this is an upgraded system from Ubuntu Xenial. I seem to remember reading you changed how config is stored, maybe some funkyness has cropped up here in connection with that.

**Comment by stgraber** [comment]
Was the system rebooted following the upgrade?

Normally that ERROR state can show up right after the upgrade to 3.0 and before the container is restarted to actually boot with 3.0

**Comment by Kramerican** [comment]
Yes, the system was rebooted following the upgrade :)

**Comment by stgraber** [comment]
That can also happen if you have a now invalid `raw.lxc` set somewhere as some of the liblxc config keys change names with 3.0.

`lxc config show NAME --expanded` for one of the affected containers may help track this down.

**Comment by Kramerican** [comment]
Maybe it's been too long since the error state?

```
~# lxc info daars
Name: daars
Remote: unix://
Architecture: x86_64
Created: 2017/08/08 08:43 UTC
Status: Running
Type: persistent
Profiles: webdock
Pid: 11577
Ips:
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
  eth0: inet    136.243.249.36  vethDCKFI7
  eth0: inet6   2a01:4f8:212:caa::604   vethDCKFI7
  eth0: inet6   fe80::216:3eff:fe09:7269        vethDCKFI7
Resources:
  Processes: 139
  Disk usage:
    root: 1.04GB
  CPU usage:
    CPU usage (in seconds): 12421
  Memory usage:
    Memory (current): 763.08MB
    Memory (peak): 865.55MB
  Network usage:
    eth0:
      Bytes received: 1.66GB
      Bytes sent: 2.40GB
      Packets received: 2037046
      Packets sent: 1753837
    lo:
      Bytes received: 139.98kB
      Bytes sent: 139.98kB
      Packets received: 1269
      Packets sent: 1269

```

```
~# lxc config show daars --expanded
architecture: x86_64
config:
  boot.autostart: "true"
  boot.autostart.delay: "10"
  image.description: Webdock Ubuntu LEMP PHP 7.1
  limits.cpu.allowance: 50%
  limits.memory: 4GB
  limits.memory.enforce: soft
  linux.kernel_modules: ip_tables,ip6_tables
  volatile.base_image: b20779efd4db91e42e3b85e9f1bd045d6b992fa34f2548c7bcb0a39d28125c41
  volatile.eth0.hwaddr: 00:16:3e:09:72:69
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: lxd
    size: 60GB
    type: disk
ephemeral: false
profiles:
- webdock
stateful: false
description: ""
```
