### ISSUE TITLE
Error: Failed container creation: Error transferring container data: No root device could be found.

### ISSUE THREAD

**Issue by itcrowdsource** [lxc/lxd#4633]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux 4.4.0-127-generic x86_64
   * LXC version: 3.0.1
   * LXD version: 3.1
   * Storage backend in use: ZFS

# Issue description

Trying to move containers from a single LXD node to a LXD cluster node. I managed to move most containers properly except one.

I issued the command:

```
lxc move c1 vm1:
Error: Failed container creation: Error transferring container data: No root device could be found.
```

The target LXD server is showing this in the logs:
daemon log:
```
ephemeral=false lvl=info msg="Created container" name=c1 t=2018-06-08T06:00:52+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=c1 t=2018-06-08T06:00:52+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=c1 t=2018-06-08T06:00:52+0000
ephemeral=false lvl=info msg="Creating container" name=c1/daily t=2018-06-08T06:00:52+0000
created=2018-06-07T11:01:22+0000 ephemeral=false lvl=info msg="Deleting container" name=c1/daily t=2018-06-08T06:00:52+0000 used=1970-01-01T00:00:00+0000
created=2018-06-07T11:01:22+0000 ephemeral=false lvl=info msg="Deleted container" name=c1/daily t=2018-06-08T06:00:53+0000 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=eror msg="Failed creating container" name=c1/daily t=2018-06-08T06:00:53+0000
err="No root device could be found." lvl=eror msg="Error during migration sink" t=2018-06-08T06:00:53+0000
created=2018-06-08T06:00:51+0000 ephemeral=false lvl=info msg="Deleting container" name=c1 t=2018-06-08T06:00:53+0000 used=1970-01-01T00:00:00+0000
created=2018-06-08T06:00:51+0000 ephemeral=false lvl=info msg="Deleted container" name=c1 t=2018-06-08T06:00:53+0000 used=1970-01-01T00:00:00+0000
```
monitor log:
```
No valid storage pool in the container's local root disk device and profiles
```
The container config everything appears to be normal, its using the same profile as other containers:

```
lxc config show c1
Name: c1
Remote: unix://
Architecture: x86_64
architecture: x86_64
config:
  environment.http_proxy: ""
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20170919)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20170919"
  image.version: "16.04"
  raw.lxc: lxc.apparmor.allow_incomplete=1
  security.privileged: "true"
  user.network_mode: ""
  volatile.base_image: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  volatile.eth0.hwaddr: xx:xx:xx:xx:xx:xx
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: lxd
    type: disk
ephemeral: false
profiles:
- default
stateful: false
```

The strange thing is that I'm able to move this container to another standalone LXD server but not to the LXD cluster.
So it seems to be related to the LXD cluster environment. The LXD cluster is on the same OS/kernel and LXD version as the standalone LXD servers.

# Steps to reproduce

 1. lxc stop c1
 2. lxc move c1 vm1:
 3. Error: Failed container creation: Error transferring container data: No root device could be found.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
[container_log.txt](https://github.com/lxc/lxd/files/2083195/container_log.txt)
[dmesg.txt](https://github.com/lxc/lxd/files/2083196/dmesg.txt)
[lxc_client_debug.txt](https://github.com/lxc/lxd/files/2083197/lxc_client_debug.txt)
[lxc_config_expanded_view.txt](https://github.com/lxc/lxd/files/2083198/lxc_config_expanded_view.txt)
[lxc_monitor_source.txt](https://github.com/lxc/lxd/files/2083199/lxc_monitor_source.txt)
[lxc_monitor_target.txt](https://github.com/lxc/lxd/files/2083200/lxc_monitor_target.txt)
[LXD_daemon_source_server.txt](https://github.com/lxc/lxd/files/2083201/LXD_daemon_source_server.txt)
[LXD_daemon_target_server.txt](https://github.com/lxc/lxd/files/2083202/LXD_daemon_target_server.txt)

**Comment by stgraber** [comment]
What does `lxc profile show vm1:default` show you?

**Comment by stgraber** [comment]
And `lxc storage list vm1:` too

**Comment by itcrowdsource** [comment]
sudo lxc profile show default

```
config:
  raw.lxc: lxc.apparmor.allow_incomplete=1
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: local
    type: disk
name: default
used_by:
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
```

sudo lxc storage list

```
+-------+-------------+--------+---------+---------+
| NAME  | DESCRIPTION | DRIVER |  STATE  | USED BY |
+-------+-------------+--------+---------+---------+
| local |             | zfs    | CREATED | 12      |
+-------+-------------+--------+---------+---------+
```

**Comment by stgraber** [comment]
Is that from vm1?

**Comment by itcrowdsource** [comment]
Yes, and vm1 is the target machine.
This is the output of the source machine vm01:

sudo lxc profile show default

```
config:
  environment.http_proxy: ""
  raw.lxc: lxc.apparmor.allow_incomplete=1
  user.network_mode: ""
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: lxd
    type: disk
name: default
used_by:
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
- /1.0/containers/xxxx
```

sudo lxc storage list

```
+------+-------------+--------+----------------------------------------+---------+
| NAME | DESCRIPTION | DRIVER |                 SOURCE                 | USED BY |
+------+-------------+--------+----------------------------------------+---------+
| lxd  |             | zfs    | /var/snap/lxd/common/lxd/disks/lxd.img | 23      |
+------+-------------+--------+----------------------------------------+---------+

```

**Comment by stgraber** [comment]
Ok, can you try `lxc config device remove c1 root`?

That should remove the locally defined `root` device for the `c1` container, making it inherit from the `default` profile instead, at which point the pool resolution should work fine during transfer.

With LXD 3.2, we'll have a `-s` flag to `lxc move` and `lxc copy` which lets you override the target pool, making remapping storage like in this case a bit nicer, but the `device remove` should work fine now.

**Comment by itcrowdsource** [comment]
That does not work, might this be the culprit? The other containers were migrated successfully. There seems to be something wrong with this specific container.

lxc config device remove c1 root

```
Error: The device doesn't exist
```

**Comment by stgraber** [comment]
That's odd, can you post the `lxc config show c1` output again for that container (don't pass --expanded).

**Comment by itcrowdsource** [comment]
The minimal view doesn't show the root device, the expanded view does.

lxc config show c1

```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20170919)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20170919"
  image.version: "16.04"
  security.privileged: "true"
  volatile.base_image: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  volatile.eth0.hwaddr: xx:xx:xx:xx:xx:xx
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

lxc config show c1 --expanded
```
architecture: x86_64
config:
  environment.http_proxy: ""
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20170919)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20170919"
  image.version: "16.04"
  raw.lxc: lxc.apparmor.allow_incomplete=1
  security.privileged: "true"
  user.network_mode: ""
  volatile.base_image: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  volatile.eth0.hwaddr: xx:xx:xx:xx:xx:xx
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: lxd
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
