### ISSUE TITLE
How to copy or publish container without mounts

### ISSUE THREAD

**Issue by elbrinke** [lxc/lxd#4639]
# Required information

 * Distribution: **Ubuntu**
 * Distribution version: **18.04**
 * The output of "lxc info" or if that fails:
   * Kernel version: **4.4.0-116-generic**
   * LXC version: **3.0**
   * LXD version: **3.0**
   * Storage backend in use: **ZFS**

# Issue description

I create containers which run services. Some containers have mounts to host directories for persistent storage. When i try to copy or publish a container that has a mount on it, it tries to copy not just the container but the entire mount as well. 

# Steps to reproduce

 1. I run this command to copy a container from one host to another host. 

> lxc copy ftp-container repository:ftp-container

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
Can you show `lxc config show ftp-container --expanded`

**Comment by elbrinke** [comment]
```
architecture: x86_64
config:
  environment.http_proxy: ""
  image.architecture: amd64
  image.description: Centos 7 amd64 (20180514_02:16)
  image.os: Centos
  image.release: "7"
  image.serial: "20180514_02:16"
  raw.lxc: lxc.mount.auto = cgroup
  security.privileged: "true"
  user.network_mode: ""
  volatile.base_image: 83465d9a9af4a843c6e9f7bde4bcb7170c7352cc555f8d6b637039006f3f49af
  volatile.eth0.hwaddr: 
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

```
