### ISSUE TITLE
Container config failing to load after upgrade to 3.0.1

### ISSUE THREAD

**Issue by bigjools** [lxc/lxd#4713]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description

```
apt dist-upgrade
.... [snip]
Setting up lxd-client (3.0.1-0ubuntu1~16.04.1) ...
Setting up wireless-regdb (2018.05.09-0ubuntu1~16.04.1) ...
Setting up liblxc1 (3.0.1-0ubuntu1~16.04.1) ...
Setting up liblxc-common (3.0.1-0ubuntu1~16.04.1) ...
Installing new version of config file /etc/apparmor.d/abstractions/lxc/start-container ...
Setting up lxd (3.0.1-0ubuntu1~16.04.1) ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
insserv: warning: script 'screen-cleanup' missing LSB tags and overrides
insserv: Default-Start undefined, assuming empty start runlevel(s) for script `screen-cleanup'
insserv: Default-Stop  undefined, assuming empty stop  runlevel(s) for script `screen-cleanup'
Processing triggers for initramfs-tools (0.122ubuntu8.11) ...
update-initramfs: Generating /boot/initrd.img-4.4.0-128-generic
cryptsetup: WARNING: failed to detect canonical device of /dev/sda
cryptsetup: WARNING: could not determine root device from /etc/fstab
Processing triggers for libc-bin (2.23-0ubuntu10) ...
root@li157-164:~# lxc exec wordpress bash
Error: EOF
root@li157-164:~# lxc exec wordpress bash
Error: Error opening startup config file: "loading config file for the container failed"
Error: EOF
root@li157-164:~# 

```

In the lxd log I see:
```
lvl=eror msg="Failed to retrieve PID of executing child process: EOF" t=2018-07-01T10:00:40-0400
lvl=warn msg="Detected poll(POLLNVAL) event: exiting." t=2018-07-01T10:00:40-0400

```

This is happening on both of my personal servers. I restarted LXD on one of them to see if it would fix it and it doesn't. The exec command ran perfectly fine immediately before the upgrade.

# Steps to reproduce

See above.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)

```
root@li157-164:~# lxc config show wordpress --expanded
architecture: i686
config:
  boot.autostart: "1"
  volatile.base_image: 615070e4260de515886f2368daeb4bd0d0cd84fe5b53bacacda0873492ccbd4e
  volatile.eth0.hwaddr: 00:16:3e:73:9e:2c
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

```

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)

```
lvl=info msg="LXD 3.0.1 is starting in normal mode" path=/var/lib/lxd t=2018-07-01T10:00:40-0400
lvl=info msg="Kernel uid/gid map:" t=2018-07-01T10:00:40-0400
lvl=info msg=" - u 0 0 4294967295" t=2018-07-01T10:00:40-0400
lvl=info msg=" - g 0 0 4294967295" t=2018-07-01T10:00:40-0400
lvl=info msg="Configured LXD uid/gid map:" t=2018-07-01T10:00:40-0400
lvl=info msg=" - u 0 100000 65536" t=2018-07-01T10:00:40-0400
lvl=info msg=" - g 0 100000 65536" t=2018-07-01T10:00:40-0400
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2018-07-01T10:00:40-0400
lvl=info msg="Initializing local database" t=2018-07-01T10:00:40-0400
lvl=info msg="Renaming local database file from lxd.db to database/local.db" t=2018-07-01T10:00:40-0400
lvl=info msg="Updating the LXD database schema. Backup made as \"local.db.bak\"" t=2018-07-01T10:00:40-0400
lvl=info msg="Initializing database gateway" t=2018-07-01T10:00:40-0400
address= id=1 lvl=info msg="Start database node" t=2018-07-01T10:00:40-0400
lvl=info msg="Raft: Initial configuration (index=1): [{Suffrage:Voter ID:1 Address:0}]" t=2018-07-01T10:00:40-0400
lvl=info msg="Raft: Node at 0 [Leader] entering Leader state" t=2018-07-01T10:00:40-0400
lvl=info msg="LXD is socket activated" t=2018-07-01T10:00:40-0400
lvl=info msg="Starting /dev/lxd handler:" t=2018-07-01T10:00:40-0400
lvl=info msg=" - binding devlxd socket" socket=/var/lib/lxd/devlxd/sock t=2018-07-01T10:00:40-0400
lvl=info msg="REST API daemon:" t=2018-07-01T10:00:40-0400
lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket t=2018-07-01T10:00:40-0400
lvl=info msg="Initializing global database" t=2018-07-01T10:00:40-0400
lvl=info msg="Migrating data from local to global database" t=2018-07-01T10:00:40-0400
lvl=info msg="Initializing storage pools" t=2018-07-01T10:00:40-0400
lvl=info msg="Applying patch: storage_api_permissions" t=2018-07-01T10:00:40-0400
lvl=info msg="Initializing networks" t=2018-07-01T10:00:40-0400
lvl=info msg="Loading configuration" t=2018-07-01T10:00:40-0400
lvl=info msg="Pruning expired images" t=2018-07-01T10:00:40-0400
lvl=info msg="Done pruning expired images" t=2018-07-01T10:00:40-0400
lvl=info msg="Updating instance types" t=2018-07-01T10:00:40-0400
lvl=info msg="Expiring log files" t=2018-07-01T10:00:40-0400
lvl=info msg="Updating images" t=2018-07-01T10:00:40-0400
lvl=info msg="Done expiring log files" t=2018-07-01T10:00:40-0400
lvl=info msg="Done updating images" t=2018-07-01T10:00:40-0400
lvl=eror msg="Failed to retrieve PID of executing child process: EOF" t=2018-07-01T10:00:40-0400
lvl=warn msg="Detected poll(POLLNVAL) event: exiting." t=2018-07-01T10:00:40-0400
lvl=eror msg="Failed to retrieve PID of executing child process: EOF" t=2018-07-01T10:00:42-0400
lvl=info msg="Done updating instance types" t=2018-07-01T10:00:43-0400
lvl=warn msg="Detected poll(POLLNVAL) event: exiting." t=2018-07-01T10:01:15-0400

```

 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
