### ISSUE TITLE
LXD daemon: increasing memory usage in runtime.systemstack

### ISSUE THREAD

**Issue by ko-zu** [lxc/lxd#4725]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04 bionic (server)
 * The output of "lxc info" or if that fails:
```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |

  certificate_fingerprint: 
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-23-generic
  server: lxd
  server_pid: 8882
  server_version: 3.0.1
  storage: btrfs
  storage_version: 4.15.1
  server_clustered: false

```
# Issue description

Memory usage of LXD daemon is steadly increasing.
From pprof, possible memory leak in the runtime.systemstack. The increasing rate would be a few MB per hour.
I have seen lxd eating 300MB residential on a server few weeks uptime.

# Steps to reproduce

 1. Install lxd on ubuntu bionic from ubuntu deb repository
```
lxd/bionic-updates,now 3.0.1-0ubuntu1~18.04.1 amd64 [installed]
```
 2. run lxd with memory profile enabled
```
# systemctl edit lxd
[Service]
ExecStart=
#ExecStart=/usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
ExecStart=/usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log --memory-profile=/tmp/lxd.pprof
```
3. run a container on it
4. send USR1 every few hours and save the pprof.
```
# go tool pprof --base lxd.pprof.0 lxd.pprof.1
text
Showing nodes accounting for 11.50MB, 100% of 11.50MB total
      flat  flat%   sum%        cum   cum%
   11.50MB   100%   100%    11.50MB   100%  runtime.systemstack
         0     0%   100%    11.50MB   100%  runtime.mstart
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
could not find something related with lxd except apparmor audits
```
[748891.660258] audit: type=1400 audit(1530500900.992:123): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" label="lxd-nc_</var/lib/lxd>//&:lxd-nc_<var-lib-lxd>:unconfined" name="/usr/bin/man" pid=19218 comm="apparmor_parser"
```
 - [ ] Container log (`lxc info NAME --show-log`)
```
Name: nc
Remote: unix://
Architecture: x86_64
Created: 2018/06/02 07:39 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 1593
Ips:
  eth0: inet    ****
  eth0: inet6   ****
  eth0: inet6  ***
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 29
  CPU usage:
    CPU usage (in seconds): 888
  Memory usage:
    Memory (current): 73.36MB
    Memory (peak): 237.45MB
  Network usage:
    lo:
      Bytes received: 69.59kB
      Bytes sent: 69.59kB
      Packets received: 782
      Packets sent: 782
    eth0:
      Bytes received: 71.61MB
      Bytes sent: 2.25MB
      Packets received: 121604
      Packets sent: 23824
Snapshots:
  snap0 (taken at 2018/06/02 08:24 UTC) (stateless)
  pre_inst_bind (taken at 2018/06/02 08:55 UTC) (stateless)

Log:


```
 - [ ] Container configuration (`lxc config show NAME --expanded`)
```
architecture: x86_64
config:
  boot.autostart: "1"
  environment.http_proxy: ""
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20180522)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20180522"
  image.version: "18.04"
  user.network_mode: ""
  user.user-data: |
    #cloud-config
    ssh_authorized_keys:
      - ecdsa-sha2-nistp256 ****
  volatile.base_image: 9879a79ac2b208c05af769089f0a6c3cbea8529571e056c82e96f1468cd1f610
  volatile.eth0.hwaddr: 00:16:3e:44:a8:36
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    ipv4.address: ****
    ipv6.address: ****
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
```
lvl=info msg="Updating images" t=2018-07-03T08:15:19+0900
lvl=info msg="Done updating images" t=2018-07-03T08:15:19+0900
lvl=info msg="Updating images" t=2018-07-03T14:15:19+0900
lvl=info msg="Done updating images" t=2018-07-03T14:15:19+0900
lvl=info msg="Expiring log files" t=2018-07-03T20:07:34+0900
lvl=info msg="Pruning expired images" t=2018-07-03T20:07:34+0900
lvl=info msg="Done pruning expired images" t=2018-07-03T20:07:34+0900
lvl=info msg="Done expiring log files" t=2018-07-03T20:07:34+0900
lvl=info msg="Updating instance types" t=2018-07-03T20:08:21+0900
lvl=info msg="Done updating instance types" t=2018-07-03T20:08:28+0900
lvl=info msg="Updating images" t=2018-07-03T20:15:19+0900
lvl=info msg="Done updating images" t=2018-07-03T20:15:19+0900
lvl=info msg="Received 'terminated signal', exiting." t=2018-07-03T20:22:35+0900
lvl=info msg="Starting shutdown sequence" t=2018-07-03T20:22:35+0900
lvl=info msg="Stopping REST API handler:" t=2018-07-03T20:22:35+0900
lvl=info msg=" - closing socket" socket=/var/lib/lxd/unix.socket t=2018-07-03T20:22:35+0900
lvl=info msg="Stopping /dev/lxd handler" t=2018-07-03T20:22:35+0900
lvl=info msg=" - closing socket" socket=/var/lib/lxd/devlxd/sock t=2018-07-03T20:22:35+0900
lvl=info msg="Closing the database" t=2018-07-03T20:22:36+0900
lvl=info msg="Stop database gateway" t=2018-07-03T20:22:37+0900
lvl=info msg="Stop raft instance" t=2018-07-03T20:22:37+0900
lvl=info msg="Raft: Starting snapshot up to 663" t=2018-07-03T20:22:40+0900
lvl=info msg="Raft: Compacting logs from 495 to 535" t=2018-07-03T20:22:41+0900
lvl=info msg="Raft: Snapshot to 663 complete" t=2018-07-03T20:22:42+0900
lvl=info msg="Stopping REST API handler:" t=2018-07-03T20:22:42+0900
lvl=info msg="Stopping /dev/lxd handler" t=2018-07-03T20:22:42+0900
lvl=info msg="Stopping REST API handler:" t=2018-07-03T20:22:42+0900
lvl=info msg="Stopping /dev/lxd handler" t=2018-07-03T20:22:42+0900
lvl=info msg="Saving simplestreams cache" t=2018-07-03T20:22:42+0900
lvl=info msg="Saved simplestreams cache" t=2018-07-03T20:22:43+0900
lvl=info msg="LXD 3.0.1 is starting in normal mode" path=/var/lib/lxd t=2018-07-03T20:22:47+0900
lvl=info msg="Kernel uid/gid map:" t=2018-07-03T20:22:48+0900
lvl=info msg=" - u 0 0 4294967295" t=2018-07-03T20:22:48+0900
lvl=info msg=" - g 0 0 4294967295" t=2018-07-03T20:22:48+0900
lvl=info msg="Configured LXD uid/gid map:" t=2018-07-03T20:22:48+0900
lvl=info msg=" - u 0 100000 65536" t=2018-07-03T20:22:48+0900
lvl=info msg=" - g 0 100000 65536" t=2018-07-03T20:22:48+0900
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2018-07-03T20:22:48+0900
lvl=info msg="Initializing local database" t=2018-07-03T20:22:48+0900
lvl=info msg="Initializing database gateway" t=2018-07-03T20:22:48+0900
address= id=1 lvl=info msg="Start database node" t=2018-07-03T20:22:48+0900
lvl=info msg="Raft: Restored from snapshot 1-663-1530616960298" t=2018-07-03T20:22:48+0900
lvl=info msg="Raft: Initial configuration (index=1): [{Suffrage:Voter ID:1 Address:0}]" t=2018-07-03T20:22:48+0900
lvl=info msg="Raft: Node at 0 [Leader] entering Leader state" t=2018-07-03T20:22:48+0900
lvl=info msg="LXD is socket activated" t=2018-07-03T20:22:48+0900
lvl=info msg="Starting /dev/lxd handler:" t=2018-07-03T20:22:48+0900
lvl=info msg=" - binding devlxd socket" socket=/var/lib/lxd/devlxd/sock t=2018-07-03T20:22:48+0900
lvl=info msg="REST API daemon:" t=2018-07-03T20:22:48+0900
lvl=info msg=" - binding Unix socket" socket=/var/lib/lxd/unix.socket t=2018-07-03T20:22:48+0900
lvl=info msg="Initializing global database" t=2018-07-03T20:22:48+0900
lvl=info msg="Initializing storage pools" t=2018-07-03T20:22:49+0900
lvl=info msg="Initializing networks" t=2018-07-03T20:22:49+0900
lvl=info msg="Loading configuration" t=2018-07-03T20:22:53+0900
lvl=info msg="Pruning expired images" t=2018-07-03T20:22:53+0900
lvl=info msg="Done pruning expired images" t=2018-07-03T20:22:53+0900
lvl=info msg="Updating instance types" t=2018-07-03T20:22:53+0900
lvl=info msg="Expiring log files" t=2018-07-03T20:22:53+0900
lvl=info msg="Updating images" t=2018-07-03T20:22:53+0900
lvl=info msg="Done expiring log files" t=2018-07-03T20:22:53+0900
lvl=info msg="Done updating images" t=2018-07-03T20:22:53+0900
lvl=info msg="Done updating instance types" t=2018-07-03T20:22:58+0900
```
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
