### ISSUE TITLE
LXD unconditionally adds iptables rules even with ipv4.firewall and ipv4.nat set to false

### ISSUE THREAD

**Issue by betafive** [lxc/lxd#4739]
I'm trying to use LXD on Ubuntu 18.04 with an nftables firewall (instead of iptables). I understand this needs a bit of manual configuration and I'm happy with that. I'm currently unable to do NAT in nftables though as there are conflicting iptables rules being injected.

My network configuration is as follows (with IP addresses removed):

```
config:
  ipv4.address: ...
  ipv4.dhcp: "false"
  ipv4.firewall: "false"
  ipv4.nat: "false"
  ipv6.address: ...
  ipv6.dhcp: "false"
  ipv6.firewall: "false"
  ipv6.nat: "false"
description: ""
name: lxdbr0
type: bridge
used_by: []
managed: true
status: Created
locations:
- none
```

With ipv4.firewall, ipv4.nat, ipv6.firewall and ipv6.nat all set to false, I expect no iptables rules to be injected. However, there is still a mangle rule injected:

```
$ sudo iptables -L -v -n -t mangle
Chain PREROUTING (policy ACCEPT 1967 packets, 148K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 1967 packets, 148K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 1600 packets, 549K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 1600 packets, 549K bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 CHECKSUM   udp  --  *      lxdbr0  0.0.0.0/0            0.0.0.0/0            udp dpt:68 /* generated for LXD network lxdbr0 */ CHECKSUM fill
```

Looking at the code it looks like this rule is injected unconditionally (https://github.com/lxc/lxd/blob/e4b2a743da9febea35410db52e5d3a0353b4c174/lxd/networks.go#L1129).

Is there any way to disable this injection? Should there be a test that ipv4.firewall is true before injecting that?
