### ISSUE TITLE
Containers getting issues-ridden including shmounts failure, forkstart failure, and zfs delete failure

### ISSUE THREAD

**Issue by zertrin** [lxc/lxd#4749]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04 LTS
 * The output of "lxc info" or if that fails:

```
lxc info
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
  images.auto_update_interval: "0"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 172.25.187.93:8443
  - 172.17.0.1:8443
  - 10.70.242.1:8443
  - '[fd42:835b:2b82:ec76::1]:8443'
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    redacted
    -----END CERTIFICATE-----
  certificate_fingerprint: 962b0f4313a6d2a81f67ae5457f4a1cb3f1d4726c2fdb11e078647eba2e0341b
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-43-generic
  server: lxd
  server_pid: 29291
  server_version: 3.0.1
  storage: zfs
  storage_version: 0.6.5.11-1ubuntu3.3
  server_clustered: false
  server_name: redacted
```

# Issue description

Everything is going south recently (last 2 to 3 weeks) with my lxd containers. Since sometime recently, I get hit by bugs chaining into each other apparently.

- a container has been running fine **for some days** (1week+)

- to enter inside it, I have a small wrapper script that does `lxc config device add $CONTAINER_NAME ${XDEVICENAME} disk path=/tmp/.X11-unix/${XDEVICENAME} source=/tmp/.X11-unix/${XDEVICENAME}` only if the device is not already added as part of the steps before calling `lxc exec ${CONTAINER_NAME} -- sudo -i -u ubuntu env DISPLAY=${DISPLAY} zsh -l`

- I notice an error while entering that matches symptoms from issue #4626:

```
Error: Failed to add mount for device: Failed to create shmounts path: open /var/snap/lxd/common/lxd/shmounts/texlive-bionic-test/lxdmount_791525747: no such file or directory
```

- I try to restart the container as indicated in issue #4626, and enter the rabbit hole a bit further with forkstart errors:

```
Error: Failed to run: /snap/lxd/current/bin/lxd forkstart texlive-bionic-test /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/texlive-bionic-test/lxc.conf: 
Try `lxc info --show-log texlive-bionic-test` for more info
```

- Then the container is stopped and unable to start, getting the error mentioned above if I try again.

- Since unfortunately **I am not at liberty to reboot the server**, the only **workaround** I found is to do `lxc copy failed-container new-container` and use the copy of the container instead of the original one.

- After this workaround, if I try to delete the failed container, it fails again like in issue #4656 with:

```
lxc delete CONTAINER_NAME
Error: Failed to destroy ZFS filesystem: cannot destroy 'lxd/containers/CONTAINER_NAME': dataset is busy
```

- Something to note is that if the failed container had snapshots, those seem to get successfully deleted, but not the base.

- I also experience a huge lag like reported in #4708

- some more debug info taken from troubleshooting requests in issue #4656 

```
$ grep containers/texlive-bionic-test /proc/*/mountinfo
/proc/4435/mountinfo:541 366 0:123 / /var/snap/lxd/common/lxd/storage-pools/lxd/containers/texlive-bionic-test rw,relatime - zfs lxd/containers/texlive-bionic-test rw,xattr,noacl
/proc/6355/mountinfo:541 366 0:123 / /var/snap/lxd/common/lxd/storage-pools/lxd/containers/texlive-bionic-test rw,relatime - zfs lxd/containers/texlive-bionic-test rw,xattr,noacl
```

- and also some troubleshooting from issue #2814

```
sudo ls -al /var/snap/lxd/common/lxd/storage-pools/lxd/containers
[sudo] password for marc.gallet: 
total 40
drwx--x--x 10 root    root    4096 Jul  4 11:47 .
drwx--x--x  6 root    root    4096 May  1 15:04 ..
drwx--x--x  2 root    root    4096 Jun 15 11:30 redacted-1
drwx--x--x  2 1000000 1000000 4096 Jun  4 09:45 redacted-dev-2        <------ *
drwx--x--x  2 root    root    4096 Jun 29 12:36 redacted-dev-3
drwx--x--x  2 1000000 1000000 4096 Jun 11 16:15 redacted-z-2        <------ *
drwx--x--x  2 root    root    4096 Jul  4 11:47 redacted-z-3
drwx--x--x  2 root    root    4096 May 10 15:46 mybase-20180510
drwx--x--x  2 root    root    4096 May 10 16:04 testgui
drwx--x--x  2 1000000 1000000 4096 Jun 26 19:28 texlive-bionic-test        <------ *

* = those I can't start or delete anymore, but i can copy
```

A consistent pattern is that the UID and GID are not root anymore for all the containers that are failing after trying to restart them.

- `cat /proc/mounts | grep texlive` is empty

- `sudo zfs list -t all | grep texlive` takes some time and outputs

```
lxd/containers/texlive-bionic-test                                                    3.84G   122G  4.06G  /var/snap/lxd/common/lxd/storage-pools/lxd/containers/texlive-bionic-test
lxd/containers/texlive-bionic-test@snapshot-after-texlive-install                     86.4M      -  4.06G  -
lxd/snapshots/texlive-bionic-test                                                       19K   122G    19K  none
```

Everything points to a bug with ZFS mounts. The annoying part is that it seems to affect more and more containers over time. I can't just reboot the server because long running critical tasks (unrelated to the containers) are being run by other users.

# Information to attach

```
$ sudo zpool list
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
lxd    149G  22.0G   127G         -     7%    14%  1.00x  ONLINE  -
```

 - [ ] Any relevant kernel output (`dmesg`)

 - [x] Container log (`lxc info NAME --show-log`)

```
$ lxc info --show-log texlive-bionic-test
Name: texlive-bionic-test
Remote: unix://
Architecture: x86_64
Created: 2018/06/26 11:28 UTC
Status: Stopped
Type: persistent
Profiles: default
Snapshots:
  after-texlive-install (taken at 2018/06/27 05:17 UTC) (stateless)

Log:

lxc texlive-bionic-test 20180706094712.776 ERROR    lxc_conf - conf.c:run_buffer:348 - Script exited with status 1
lxc texlive-bionic-test 20180706094712.776 ERROR    lxc_start - start.c:lxc_init:820 - Failed to run lxc.hook.pre-start for container "texlive-bionic-test"
lxc texlive-bionic-test 20180706094712.776 ERROR    lxc_start - start.c:__lxc_start:1853 - Failed to initialize container "texlive-bionic-test"
lxc texlive-bionic-test 20180706094712.777 ERROR    lxc_container - lxccontainer.c:wait_on_daemonized_start:825 - No such file or directory - Failed to receive the container state
```

 - [x] Container configuration (`lxc config show NAME --expanded`)

```
$ lxc config show --expanded $CONTAINER_NAME 
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20180617)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20180617"
  image.version: "18.04"
  raw.idmap: both 1001 1000
  volatile.base_image: b190d5ec0c537468465e7bd122fe127d9f3509e3a09fb699ac33b0c5d4fe050f
  volatile.eth0.hwaddr: 00:16:3e:11:4a:4e
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":true,"Hostid":1001,"Nsid":1000,"Maprange":1},{"Isuid":true,"Isgid":true,"Hostid":1001001,"Nsid":1001,"Maprange":999998999}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":true,"Hostid":1001,"Nsid":1000,"Maprange":1},{"Isuid":true,"Isgid":true,"Hostid":1001001,"Nsid":1001,"Maprange":999998999}]'
  volatile.last_state.power: RUNNING
devices:
  bedap:
    path: /work/bedap
    source: /home/redacted/Documents/bedap-lxc
    type: disk
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  latexdiff:
    path: /work/latexdiff
    source: /home/redacted/Documents/latexdiff
    type: disk
  root:
    path: /
    pool: lxd
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)

```
action=shutdown created=2018-06-26T11:28:37+0000 ephemeral=false lvl=info msg="Shutting down container" name=texlive-bionic-test t=2018-07-06T09:38:34+0000 timeout=-1s used=2018-06-27T05:21:26+0000
action=shutdown created=2018-06-26T11:28:37+0000 ephemeral=false lvl=info msg="Shut down container" name=texlive-bionic-test t=2018-07-06T09:38:37+0000 timeout=-1s used=2018-06-27T05:21:26+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=texlive-bionic-test t=2018-07-06T09:38:37+0000
lvl=warn msg="ZFS returned EBUSY while \"/var/snap/lxd/common/lxd/storage-pools/lxd/containers/texlive-bionic-test\" is actually not a mountpoint." t=2018-07-06T09:38:47+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=texlive-bionic-test t=2018-07-06T09:38:47+0000
lvl=warn msg="ZFS returned EBUSY while \"/var/snap/lxd/common/lxd/storage-pools/lxd/containers/texlive-bionic-test\" is actually not a mountpoint." t=2018-07-06T09:38:57+0000
action=start created=2018-06-26T11:28:37+0000 ephemeral=false lvl=info msg="Starting container" name=texlive-bionic-test stateful=false t=2018-07-06T09:38:57+0000 used=2018-06-27T05:21:26+0000
lvl=warn msg="ZFS returned EBUSY while \"/var/snap/lxd/common/lxd/storage-pools/lxd/containers/texlive-bionic-test\" is actually not a mountpoint." t=2018-07-06T09:39:08+0000
container=texlive-bionic-test err="device or resource busy" lvl=eror msg="start hook failed" t=2018-07-06T09:39:08+0000
action=start created=2018-06-26T11:28:37+0000 ephemeral=false lvl=eror msg="Failed starting container" name=texlive-bionic-test stateful=false t=2018-07-06T09:39:08+0000 used=2018-06-27T05:21:26+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=texlive-bionic-test t=2018-07-06T09:46:29+0000
lvl=warn msg="ZFS returned EBUSY while \"/var/snap/lxd/common/lxd/storage-pools/lxd/containers/texlive-bionic-test\" is actually not a mountpoint." t=2018-07-06T09:46:39+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=texlive-bionic-test t=2018-07-06T09:46:39+0000
lvl=warn msg="ZFS returned EBUSY while \"/var/snap/lxd/common/lxd/storage-pools/lxd/containers/texlive-bionic-test\" is actually not a mountpoint." t=2018-07-06T09:47:02+0000
action=start created=2018-06-26T11:28:37+0000 ephemeral=false lvl=info msg="Starting container" name=texlive-bionic-test stateful=false t=2018-07-06T09:47:02+0000 used=2018-07-06T09:38:47+0000
lvl=warn msg="ZFS returned EBUSY while \"/var/snap/lxd/common/lxd/storage-pools/lxd/containers/texlive-bionic-test\" is actually not a mountpoint." t=2018-07-06T09:47:12+0000
container=texlive-bionic-test err="device or resource busy" lvl=eror msg="start hook failed" t=2018-07-06T09:47:12+0000
action=start created=2018-06-26T11:28:37+0000 ephemeral=false lvl=eror msg="Failed starting container" name=texlive-bionic-test stateful=false t=2018-07-06T09:47:12+0000 used=2018-07-06T09:38:47+0000
```

 - [x] Output of the client with --debug

```
$ lxc start --debug $CONTAINER_NAME
DBUG[07-06|10:01:41] Connecting to a local LXD over a Unix socket 
DBUG[07-06|10:01:41] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
DBUG[07-06|10:01:41] Got response struct from LXD 
DBUG[07-06|10:01:41] 
	{
		"config": {
			"core.https_address": "[::]:8443",
			"core.trust_password": true,
			"images.auto_update_interval": "0"
		},
		"api_extensions": [
			"storage_zfs_remove_snapshots",
			"container_host_shutdown_timeout",
			"container_stop_priority",
			"container_syscall_filtering",
			"auth_pki",
			"container_last_used_at",
			"etag",
			"patch",
			"usb_devices",
			"https_allowed_credentials",
			"image_compression_algorithm",
			"directory_manipulation",
			"container_cpu_time",
			"storage_zfs_use_refquota",
			"storage_lvm_mount_options",
			"network",
			"profile_usedby",
			"container_push",
			"container_exec_recording",
			"certificate_update",
			"container_exec_signal_handling",
			"gpu_devices",
			"container_image_properties",
			"migration_progress",
			"id_map",
			"network_firewall_filtering",
			"network_routes",
			"storage",
			"file_delete",
			"file_append",
			"network_dhcp_expiry",
			"storage_lvm_vg_rename",
			"storage_lvm_thinpool_rename",
			"network_vlan",
			"image_create_aliases",
			"container_stateless_copy",
			"container_only_migration",
			"storage_zfs_clone_copy",
			"unix_device_rename",
			"storage_lvm_use_thinpool",
			"storage_rsync_bwlimit",
			"network_vxlan_interface",
			"storage_btrfs_mount_options",
			"entity_description",
			"image_force_refresh",
			"storage_lvm_lv_resizing",
			"id_map_base",
			"file_symlinks",
			"container_push_target",
			"network_vlan_physical",
			"storage_images_delete",
			"container_edit_metadata",
			"container_snapshot_stateful_migration",
			"storage_driver_ceph",
			"storage_ceph_user_name",
			"resource_limits",
			"storage_volatile_initial_source",
			"storage_ceph_force_osd_reuse",
			"storage_block_filesystem_btrfs",
			"resources",
			"kernel_limits",
			"storage_api_volume_rename",
			"macaroon_authentication",
			"network_sriov",
			"console",
			"restrict_devlxd",
			"migration_pre_copy",
			"infiniband",
			"maas_network",
			"devlxd_events",
			"proxy",
			"network_dhcp_gateway",
			"file_get_symlink",
			"network_leases",
			"unix_device_hotplug",
			"storage_api_local_volume_handling",
			"operation_description",
			"clustering",
			"event_lifecycle",
			"storage_api_remote_volume_handling",
			"nvidia_runtime"
		],
		"api_status": "stable",
		"api_version": "1.0",
		"auth": "trusted",
		"public": false,
		"auth_methods": [
			"tls"
		],
		"environment": {
			"addresses": [
				"172.25.187.93:8443",
				"172.17.0.1:8443",
				"10.70.242.1:8443",
				"[fd42:835b:2b82:ec76::1]:8443"
			],
			"architectures": [
				"x86_64",
				"i686"
			],
			"certificate": "-----BEGIN CERTIFICATE-----\nredacted\n-----END CERTIFICATE-----\n",
			"certificate_fingerprint": "962b0f4313a6d2a81f67ae5457f4a1cb3f1d4726c2fdb11e078647eba2e0341b",
			"driver": "lxc",
			"driver_version": "3.0.1",
			"kernel": "Linux",
			"kernel_architecture": "x86_64",
			"kernel_version": "4.13.0-43-generic",
			"server": "lxd",
			"server_pid": 29291,
			"server_version": "3.0.1",
			"storage": "zfs",
			"storage_version": "0.6.5.11-1ubuntu3.3",
			"server_clustered": false,
			"server_name": "redacted"
		}
	} 
DBUG[07-06|10:01:41] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0/containers/texlive-bionic-test
DBUG[07-06|10:01:41] Got response struct from LXD 
DBUG[07-06|10:01:41] 
	{
		"architecture": "x86_64",
		"config": {
			"image.architecture": "amd64",
			"image.description": "ubuntu 18.04 LTS amd64 (release) (20180617)",
			"image.label": "release",
			"image.os": "ubuntu",
			"image.release": "bionic",
			"image.serial": "20180617",
			"image.version": "18.04",
			"raw.idmap": "both 1001 1000",
			"volatile.base_image": "b190d5ec0c537468465e7bd122fe127d9f3509e3a09fb699ac33b0c5d4fe050f",
			"volatile.eth0.hwaddr": "00:16:3e:11:4a:4e",
			"volatile.idmap.base": "0",
			"volatile.idmap.next": "[{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1001,\"Nsid\":1000,\"Maprange\":1},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1001001,\"Nsid\":1001,\"Maprange\":999998999}]",
			"volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1001,\"Nsid\":1000,\"Maprange\":1},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1001001,\"Nsid\":1001,\"Maprange\":999998999}]",
			"volatile.last_state.power": "RUNNING"
		},
		"devices": {
			"bedap": {
				"path": "/work/bedap",
				"source": "/home/redacted/Documents/bedap-lxc",
				"type": "disk"
			},
			"latexdiff": {
				"path": "/work/latexdiff",
				"source": "/home/redacted/Documents/latexdiff",
				"type": "disk"
			}
		},
		"ephemeral": false,
		"profiles": [
			"default"
		],
		"stateful": false,
		"description": "",
		"created_at": "2018-06-26T11:28:37Z",
		"expanded_config": {
			"image.architecture": "amd64",
			"image.description": "ubuntu 18.04 LTS amd64 (release) (20180617)",
			"image.label": "release",
			"image.os": "ubuntu",
			"image.release": "bionic",
			"image.serial": "20180617",
			"image.version": "18.04",
			"raw.idmap": "both 1001 1000",
			"volatile.base_image": "b190d5ec0c537468465e7bd122fe127d9f3509e3a09fb699ac33b0c5d4fe050f",
			"volatile.eth0.hwaddr": "00:16:3e:11:4a:4e",
			"volatile.idmap.base": "0",
			"volatile.idmap.next": "[{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1001,\"Nsid\":1000,\"Maprange\":1},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1001001,\"Nsid\":1001,\"Maprange\":999998999}]",
			"volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1001,\"Nsid\":1000,\"Maprange\":1},{\"Isuid\":true,\"Isgid\":true,\"Hostid\":1001001,\"Nsid\":1001,\"Maprange\":999998999}]",
			"volatile.last_state.power": "RUNNING"
		},
		"expanded_devices": {
			"bedap": {
				"path": "/work/bedap",
				"source": "/home/redacted/Documents/bedap-lxc",
				"type": "disk"
			},
			"eth0": {
				"name": "eth0",
				"nictype": "bridged",
				"parent": "lxdbr0",
				"type": "nic"
			},
			"latexdiff": {
				"path": "/work/latexdiff",
				"source": "/home/redacted/Documents/latexdiff",
				"type": "disk"
			},
			"root": {
				"path": "/",
				"pool": "lxd",
				"type": "disk"
			}
		},
		"name": "texlive-bionic-test",
		"status": "Stopped",
		"status_code": 102,
		"last_used_at": "2018-07-06T09:59:43Z",
		"location": ""
	} 
DBUG[07-06|10:01:41] Connected to the websocket 
DBUG[07-06|10:01:41] Sending request to LXD                   etag= method=PUT url=http://unix.socket/1.0/containers/texlive-bionic-test/state
DBUG[07-06|10:01:41] 
	{
		"action": "start",
		"timeout": 0,
		"force": false,
		"stateful": false
	} 
DBUG[07-06|10:01:41] Got operation from LXD 
DBUG[07-06|10:01:41] 
	{
		"id": "6b9d97ab-22a9-4f28-82a6-f42ab0a838f9",
		"class": "task",
		"description": "Starting container",
		"created_at": "2018-07-06T10:01:41.287255255Z",
		"updated_at": "2018-07-06T10:01:41.287255255Z",
		"status": "Running",
		"status_code": 103,
		"resources": {
			"containers": [
				"/1.0/containers/texlive-bionic-test"
			]
		},
		"metadata": null,
		"may_cancel": false,
		"err": ""
	} 
DBUG[07-06|10:01:41] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0/operations/6b9d97ab-22a9-4f28-82a6-f42ab0a838f9
DBUG[07-06|10:01:41] Got response struct from LXD 
DBUG[07-06|10:01:41] 
	{
		"id": "6b9d97ab-22a9-4f28-82a6-f42ab0a838f9",
		"class": "task",
		"description": "Starting container",
		"created_at": "2018-07-06T10:01:41.287255255Z",
		"updated_at": "2018-07-06T10:01:41.287255255Z",
		"status": "Running",
		"status_code": 103,
		"resources": {
			"containers": [
				"/1.0/containers/texlive-bionic-test"
			]
		},
		"metadata": null,
		"may_cancel": false,
		"err": ""
	} 
Error: Failed to run: /snap/lxd/current/bin/lxd forkstart texlive-bionic-test /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/texlive-bionic-test/lxc.conf: 
Try `lxc info --show-log texlive-bionic-test` for more info
```

 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

```
lxc monitor
metadata:
  context: {}
  level: dbug
  message: 'New event listener: 0594554f-2681-43bc-ac20-1b3363ea8b12'
timestamp: "2018-07-06T10:01:38.055215021Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2018-07-06T10:01:41.253768738Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/texlive-bionic-test
  level: dbug
  message: handling
timestamp: "2018-07-06T10:01:41.261604415Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/events
  level: dbug
  message: handling
timestamp: "2018-07-06T10:01:41.274466432Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'New event listener: 6bf3f1eb-dcec-4691-9af3-d1a129d24a47'
timestamp: "2018-07-06T10:01:41.274663108Z"
type: logging


metadata:
  context:
    ip: '@'
    method: PUT
    url: /1.0/containers/texlive-bionic-test/state
  level: dbug
  message: handling
timestamp: "2018-07-06T10:01:41.276450023Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'New task operation: 6b9d97ab-22a9-4f28-82a6-f42ab0a838f9'
timestamp: "2018-07-06T10:01:41.359620673Z"
type: logging


metadata:
  class: task
  created_at: "2018-07-06T10:01:41.287255255Z"
  description: Starting container
  err: ""
  id: 6b9d97ab-22a9-4f28-82a6-f42ab0a838f9
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/texlive-bionic-test
  status: Pending
  status_code: 105
  updated_at: "2018-07-06T10:01:41.287255255Z"
timestamp: "2018-07-06T10:01:41.359708395Z"
type: operation


metadata:
  class: task
  created_at: "2018-07-06T10:01:41.287255255Z"
  description: Starting container
  err: ""
  id: 6b9d97ab-22a9-4f28-82a6-f42ab0a838f9
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/texlive-bionic-test
  status: Running
  status_code: 103
  updated_at: "2018-07-06T10:01:41.287255255Z"
timestamp: "2018-07-06T10:01:41.359888519Z"
type: operation


metadata:
  context: {}
  level: dbug
  message: 'Started task operation: 6b9d97ab-22a9-4f28-82a6-f42ab0a838f9'
timestamp: "2018-07-06T10:01:41.359817768Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/operations/6b9d97ab-22a9-4f28-82a6-f42ab0a838f9
  level: dbug
  message: handling
timestamp: "2018-07-06T10:01:41.362092043Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing a ZFS driver.
timestamp: "2018-07-06T10:01:41.373381911Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/texlive-bionic-test
timestamp: "2018-07-06T10:01:41.475116783Z"
type: lifecycle


metadata:
  context:
    name: texlive-bionic-test
  level: warn
  message: Unable to update backup.yaml at this time.
timestamp: "2018-07-06T10:01:41.474921015Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting ZFS storage volume for container "texlive-bionic-test" on storage
    pool "lxd"
timestamp: "2018-07-06T10:01:41.534211606Z"
type: logging


metadata:
  context: {}
  level: warn
  message: ZFS returned EBUSY while "/var/snap/lxd/common/lxd/storage-pools/lxd/containers/texlive-bionic-test"
    is actually not a mountpoint.
timestamp: "2018-07-06T10:01:51.5648929Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Unmounting ZFS storage volume for container "texlive-bionic-test" on storage
    pool "lxd".
timestamp: "2018-07-06T10:01:51.565514776Z"
type: logging


metadata:
  context:
    name: texlive-bionic-test
  level: warn
  message: Unable to update backup.yaml at this time.
timestamp: "2018-07-06T10:01:51.565370062Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Unmounted ZFS storage volume for container "texlive-bionic-test" on storage
    pool "lxd".
timestamp: "2018-07-06T10:01:51.56785575Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting ZFS storage volume for container "texlive-bionic-test" on storage
    pool "lxd"
timestamp: "2018-07-06T10:01:51.645109011Z"
type: logging


metadata:
  context: {}
  level: warn
  message: ZFS returned EBUSY while "/var/snap/lxd/common/lxd/storage-pools/lxd/containers/texlive-bionic-test"
    is actually not a mountpoint.
timestamp: "2018-07-06T10:02:01.673967771Z"
type: logging


metadata:
  context:
    action: start
    created: 2018-06-26 11:28:37 +0000 UTC
    ephemeral: "false"
    name: texlive-bionic-test
    stateful: "false"
    used: 2018-07-06 09:59:43 +0000 UTC
  level: info
  message: Starting container
timestamp: "2018-07-06T10:02:01.674310347Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2018-07-06T10:02:01.715279279Z"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /internal/containers/15/onstart
  level: dbug
  message: handling
timestamp: "2018-07-06T10:02:01.722260855Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting ZFS storage volume for container "texlive-bionic-test" on storage
    pool "lxd"
timestamp: "2018-07-06T10:02:01.736500791Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Initializing a ZFS driver.
timestamp: "2018-07-06T10:02:01.736444987Z"
type: logging


metadata:
  context:
    container: texlive-bionic-test
    err: device or resource busy
  level: eror
  message: start hook failed
timestamp: "2018-07-06T10:02:11.764494484Z"
type: logging


metadata:
  context: {}
  level: warn
  message: ZFS returned EBUSY while "/var/snap/lxd/common/lxd/storage-pools/lxd/containers/texlive-bionic-test"
    is actually not a mountpoint.
timestamp: "2018-07-06T10:02:11.764275458Z"
type: logging


metadata:
  context:
    action: start
    created: 2018-06-26 11:28:37 +0000 UTC
    ephemeral: "false"
    name: texlive-bionic-test
    stateful: "false"
    used: 2018-07-06 09:59:43 +0000 UTC
  level: eror
  message: Failed starting container
timestamp: "2018-07-06T10:02:11.769792231Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Failure for task operation: 6b9d97ab-22a9-4f28-82a6-f42ab0a838f9: Failed
    to run: /snap/lxd/current/bin/lxd forkstart texlive-bionic-test /var/snap/lxd/common/lxd/containers
    /var/snap/lxd/common/lxd/logs/texlive-bionic-test/lxc.conf: '
timestamp: "2018-07-06T10:02:11.769902303Z"
type: logging


metadata:
  class: task
  created_at: "2018-07-06T10:01:41.287255255Z"
  description: Starting container
  err: 'Failed to run: /snap/lxd/current/bin/lxd forkstart texlive-bionic-test /var/snap/lxd/common/lxd/containers
    /var/snap/lxd/common/lxd/logs/texlive-bionic-test/lxc.conf: '
  id: 6b9d97ab-22a9-4f28-82a6-f42ab0a838f9
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/texlive-bionic-test
  status: Failure
  status_code: 400
  updated_at: "2018-07-06T10:01:41.287255255Z"
timestamp: "2018-07-06T10:02:11.769982412Z"
type: operation
```
