### ISSUE TITLE
Cloud-init not executed on new install.

### ISSUE THREAD

**Issue by Pekkari** [lxc/lxd#4767]
Morning,

I did a new setup of lxd creating a thinpool for lvm, and adding a profile that will be
detailed shortly. Launching containers renders in cloud-init not generating any file
under /etc/networks/interfaces.d, nor acting on the rest of the system. The image
in use is ubuntu:xenial.

 * Distribution: Gentoo
 * Kernel version: 4.17.5
 * LXC version: 2.1.1
 * LXD version: 3.2
 * Storage backend in use: LVM

# Steps to reproduce

 1. lvcreate -L 150G -T mole-vg0/LXDPool
 2. rc-service lxd start
 3. lxc storage create LXDPool lvm source=mole-vg0 lvm.thinpool_name=LXDPool
 4. lxc profile create fce
 5. lxc profile edit fce and add:

```
config:
  boot.autostart: "0"
  limits.cpu: "2"
  limits.memory: 2GB
  security.privileged: "True"
  user.user-data: |
    #cloud-config
    - ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDGb0I+spRIet/GMCwR06VpyceewTTsEwCeoOW+4vO12m9jUuUml9+/KEJAy+uwbl7H2MZ4Khdy1RZJfyAQ9Ix1ROABB4iM3tvjhRpzQaxf/Hh0nsBBByOfBZKMKITcvEAGCTSZl7mUTi3EJiSh1rhAF5XMjsXFvRnfwdOXCkVQBX5r0Mh5teTATJKXXEAHrvcfDqEPZ578U3uygnybi0djtcdIS0NCHryUUEri0WUygFR14nT5pwAQDUNawl4tdXm6k8/3qMPdJxIckFjs3p9f/HzVjo6OoPX6L7pyxhpBq1kqJX3KhdqfAjOVma/BXdss26p1SnOc7CG/yRW2wdq8DZcyxSgpr/490V6SrY5X3iPOsBzCIUS0jrVUoEYPvLCmNevmYkFTDbZuZ3wL/1/TJt94YRs235fMhZhHjdhL+dp+XmJiZJffBNxv6EOK6LHwzqNs7JAfJGCrMFXzC5e1xGV9BQHGe7IZDWZSYXHheDmvuXSgQry2tuFXFMu1obNA5xd5ckTlkBupv6XspRh+kct6M9ImK8DWcpxg+6GZV1SPhiUN54Y8Zrih3HANbHxlg7lBPRMCHnWJchkU8qDIOfrK14mEBdz0Tgbjo55uHbuUaRywTKQ3obJcz0dVxQi1vgYTZOpB14HDMhogpIpl0rHB0uby2uYw9uX8biq7Uw== cardno:000604258140
description: FCE LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  eth1:
    name: eth1
    nictype: bridged
    parent: virbr0
    type: nic
  kvm:
    path: /dev/kvm
    type: unix-char
  root:
    path: /
    pool: LXDPool
    type: disk
name: fce
```

  6. lxc launch -p fce ubuntu:xenial fce-1

After this, the container turns up, but it doesn't configure networking, ubuntu user is not
populated, and authorized_key not added. performing dhclient makes it get an ip, so it
doesn't look like a firewall issue:

```
$ lxc exec fce-1 dhclient eth0
$ lxc list
+-------+---------+---------------------+-----------------------------------------------+------------+-----------+
| NAME  |  STATE  |        IPV4         |                     IPV6                      |    TYPE    | SNAPSHOTS |
+-------+---------+---------------------+-----------------------------------------------+------------+-----------+
| fce-1 | RUNNING | 192.168.0.51 (eth0) | fdb4:6fc8:79c2:0:216:3eff:fe95:9dbb (eth0)    | PERSISTENT | 0         |
|       |         |                     | 2001:14ba:1efe:e9f0:216:3eff:fe95:9dbb (eth0) |            |           |
+-------+---------+---------------------+-----------------------------------------------+------------+-----------+
```

   Thanks!

   José.
