### ISSUE TITLE
LXD 3.2 snap containers up but LXD daemon won't start [urgent]

### ISSUE THREAD

**Issue by hmilkovi** [lxc/lxd#4807]
# Required information

 * Distribution: 16.0.4
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 3.2
   * LXD version: 3.2
   * Storage backend in use: Only DIR (2 of them)

# Issue description

After some time as I look ones weekly on the host if all is okey the LXD stopped and failed to start
witch error I tried to debug ` sudo lxd --group lxd `:
```
EROR[07-19|13:18:44] Failed to start the daemon: saving config file for the container failed
```

LXC returns of course with:
```
Error: Get http://unix.socket/1.0: dial unix /var/snap/lxd/common/lxd/unix.socket: connect: no such file or directory
```

Interesting part is that I have some **production** and develop servers on it and they are up and working, just the LXD demon is down.

# Steps to reproduce
None just stopped

# Information to attach

Main log file part ` /var/snap/lxd/common/lxd/logs/lxd.log `:
```
lvl=info msg="Initializing global database" t=2018-07-19T12:43:32+0000
lvl=info msg="Initializing storage pools" t=2018-07-19T12:43:32+0000
lvl=info msg="Applying patch: container_config_regen" t=2018-07-19T12:43:32+0000
lvl=eror msg="Failed to start the daemon: saving config file for the container failed" t=2018-07-19T12:43:32+0000
lvl=info msg="Starting shutdown sequence" t=2018-07-19T12:43:32+0000
lvl=info msg="Stopping REST API handler:" t=2018-07-19T12:43:32+0000
lvl=info msg=" - closing socket" socket=10.251.0.1:8443 t=2018-07-19T12:43:32+0000
lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/unix.socket t=2018-07-19T12:43:32+0000
lvl=info msg="Stopping /dev/lxd handler" t=2018-07-19T12:43:32+0000
lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/devlxd/sock t=2018-07-19T12:43:32+0000
lvl=info msg="Closing the database" t=2018-07-19T12:43:32+0000
lvl=info msg="Stop database gateway" t=2018-07-19T12:43:32+0000
lvl=info msg="Stop raft instance" t=2018-07-19T12:43:32+0000
lvl=info msg="Raft: Starting snapshot up to 2998" t=2018-07-19T12:43:33+0000
```

Log from ` /snap/bin/lxd --trace --verbose --debug --group lxd ` :
```
INFO[07-19|15:06:27] Initializing global database
INFO[07-19|15:06:27] Initializing storage pools
DBUG[07-19|15:06:27] Initializing and checking storage pool "prod_storage"
DBUG[07-19|15:06:27] Initializing a DIR driver
DBUG[07-19|15:06:27] Checking DIR storage pool "prod_storage"
DBUG[07-19|15:06:27] Initializing and checking storage pool "dev_staging_storage"
DBUG[07-19|15:06:27] Initializing a DIR driver
DBUG[07-19|15:06:27] Checking DIR storage pool "dev_staging_storage"
DBUG[07-19|15:06:27] Initializing a DIR driver
INFO[07-19|15:06:27] Applying patch: container_config_regen
EROR[07-19|15:06:27] Failed to start the daemon: saving config file for the container failed
INFO[07-19|15:06:27] Starting shutdown sequence
```
If needed just request more info as I think it's all thats relevant.

For now I just need a solution to fix it, as I can't spawn new containers or do backups.
Thanks for your time.

**Comment by hmilkovi** [comment]
If I try to reinstall lxd with snap will it remove the existing containers or?

**Comment by stgraber** [comment]
Don't remove the snap as it will indeed delete your containers.
I can get you a binary which will not treat failures to save configs as critical, it's a bit concerning though and hints as you having a serious configuration problem with that container.

**Comment by stgraber** [comment]
You may run:
 - curl https://dl.stgraber.org/lxd-4807 -o /var/snap/lxd/common/lxd.debug
 - chmod +x /var/snap/lxd/common/lxd.debug
 - systemctl restart snap.lxd.daemon
 - lxd waitready
 - rm /var/snap/lxd/common/lxd.debug
 - systemctl reload snap.lxd.daemon

This will run the updated binary which will skip the broken containers, then remove that binary and switch you back to the orignal binary which should then work just fine.

**Comment by hmilkovi** [comment]
I go to try it right now.

**Comment by hmilkovi** [comment]
Just one question: How do I fix broken containers? Or is this is hot fix and will continue to work
from now?

**Comment by hmilkovi** [comment]
Hm strange as all my affected containers have the same config as the others:
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20180522)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20180522"
  image.version: "16.04"
  user.user-data: |
    #cloud-config
    package_upgrade: true
    package_reboot_if_required: true
    users:
      - name: ubuntu
        gecos: ubuntu
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/bash
        ssh_authorized_keys:
          - ssh-rsa .....
          - ssh-rsa .....
          - ssh-rsa .....
  volatile.base_image: 08bbf441bb737097586e9f313b239cecbba96222e58457881b3718c45c17e074
  volatile.eth0.hwaddr: 00:16:3e:fc:99:b0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: prod_storage
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
