### ISSUE TITLE
lxc network unset doesn't work in 3.0.1

### ISSUE THREAD

**Issue by JoshDaone** [lxc/lxd#4824]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 18.04 LTS (Bionic Beaver)
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-29-generic 
   * LXC version: 3.0.1
   * LXD version: 3.0.1
   * Storage backend in use:

# Issue description

Fresh install with Ubuntu 18.04 and installed with conjure-up + LXD, everything was fine util I added ipv4.routes in default lxdbr0 adapter. Then all containers lost its IPv4 address, now trying to remove ipv4.routes key but cannot be done.

```
root@pnbionic:/tmp# lxc network show lxdbr0
config:
  ipv4.address: 10.80.231.1/24
  ipv4.nat: "true"
  ipv4.routes: 10.80.231.224/24
  ipv6.address: none
description: ""
name: lxdbr0
type: bridge
used_by:
- /1.0/containers/first
- /1.0/containers/juju-c6597f-0
- /1.0/containers/juju-c6597f-1
- /1.0/containers/juju-c6597f-10
- /1.0/containers/juju-c6597f-11
- /1.0/containers/juju-c6597f-12
- /1.0/containers/juju-c6597f-13
- /1.0/containers/juju-c6597f-14
- /1.0/containers/juju-c6597f-15
- /1.0/containers/juju-c6597f-16
- /1.0/containers/juju-c6597f-2
- /1.0/containers/juju-c6597f-3
- /1.0/containers/juju-c6597f-4
- /1.0/containers/juju-c6597f-5
- /1.0/containers/juju-c6597f-6
- /1.0/containers/juju-c6597f-7
- /1.0/containers/juju-c6597f-8
- /1.0/containers/juju-c6597f-9
- /1.0/containers/juju-ceb504-0
managed: true
status: Created
locations:
- none
```

I added ipv4.routes by using:

`lxc network set lxdbr0 ipv4.routes 10.80.231.224/24`

So I'm trying to unset the ipv4.routes with

`lxc network unset lxdbr0 ipv4.routes 10.80.231.224/24`

This doesn't help with output:

```
Description:
  Unset network configuration keys

Usage:
  lxc network unset [<remote>:]<network> <key> [flags]
```
But re-run without value its can be proceed. However, the ipv4.routes remains.

`lxc network unset lxdbr0 ipv4.routes`

Tried with `lxc network edit lxdbr0` to manually remove the line but didn't help. Enabled debug flag as `lxc network unset lxdbr0 ipv4.routes --debug` and got:

```
DBUG[07-24|21:55:52] Got response struct from LXD
DBUG[07-24|21:55:52]
        {
                "config": {
                        "ipv4.address": "10.80.231.1/24",
                        "ipv4.nat": "true",
                        "ipv4.routes": "10.80.231.224/24",
                        "ipv6.address": "none"
                },
                "description": "",
                "name": "lxdbr0",
                "type": "bridge",
                "used_by": [
                        "/1.0/containers/first",
                        "/1.0/containers/juju-c6597f-0",
                        "/1.0/containers/juju-c6597f-1",
                        "/1.0/containers/juju-c6597f-10",
                        "/1.0/containers/juju-c6597f-11",
                        "/1.0/containers/juju-c6597f-12",
                        "/1.0/containers/juju-c6597f-13",
                        "/1.0/containers/juju-c6597f-14",
                        "/1.0/containers/juju-c6597f-15",
                        "/1.0/containers/juju-c6597f-16",
                        "/1.0/containers/juju-c6597f-2",
                        "/1.0/containers/juju-c6597f-3",
                        "/1.0/containers/juju-c6597f-4",
                        "/1.0/containers/juju-c6597f-5",
                        "/1.0/containers/juju-c6597f-6",
                        "/1.0/containers/juju-c6597f-7",
                        "/1.0/containers/juju-c6597f-8",
                        "/1.0/containers/juju-c6597f-9",
                        "/1.0/containers/juju-ceb504-0"
                ],
                "managed": true,
                "status": "Created",
                "locations": [
                        "none"
                ]
        }
DBUG[07-24|21:55:52] Sending request to LXD                   etag=77c6c9758c7cb6c3bd03a1db9f641367be29f22dc918706f2e836875956d98bf method=PUT url=http://unix.socket/1.0/networks/lxdbr0
DBUG[07-24|21:55:52]
        {
                "config": {
                        "ipv4.address": "10.80.231.1/24",
                        "ipv4.nat": "true",
                        "ipv4.routes": "",
                        "ipv6.address": "none"
                },
                "description": ""
        }
```
The ipv4.routes value is purged, but lxc network show lxdbr0 still has old value.

# Steps to reproduce

1. Fresh install Ubuntu 18.04 in VirtualBox with Bridge model, install Conjure-up using SNAP install.
2. Rerun the lxc set as mentioned above, then restart the lxd by service lxd restart.
