### ISSUE TITLE
Removing fantom containers?

### ISSUE THREAD

**Issue by ne-vlezay80** [lxc/lxd#5018]
```
user@lxd:~$ lxc storage show st
config:
  lvm.thinpool_name: LXDThinPool
  lvm.vg_name: st
  size: 15GB
  source: /var/snap/lxd/common/lxd/disks/st.img
description: ""
name: st
driver: lvm
used_by:
- /1.0/containers/eee1
- /1.0/images/8050e18044049ba33918b78a541c4a5bd7852bcdd18cca0f64d5e0dc2fbc17d8
status: Created
locations:
- none
```

user@lxd:~$ lxc list
+------------+---------+------+------+------------+-----------+
|    NAME    |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------------+---------+------+------+------------+-----------+
| krasotka01 | STOPPED |      |      | PERSISTENT |           |
+------------+---------+------+------+------------+-----------+
| nevl80c    | STOPPED |      |      | PERSISTENT |           |
+------------+---------+------+------+------------+-----------+

The fantom containers is formed from old kernel lvm bug.
