### ISSUE TITLE
projects: Container using profiles from "default" rather than project

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#5137]
Note that I'm disabling the `images` feature here to avoid #5136 

```
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc project create blah -c features.images=false
Project blah created
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc project switch blah

stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc launch images:alpine/edge c1
Creating c1
Starting c1

stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc profile show default
config: {}
description: Default LXD profile for project blah
devices: {}
name: default
used_by: []

stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc config show c1
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Alpine edge amd64 (20181004_13:00)
  image.os: Alpine
  image.release: edge
  image.serial: "20181004_13:00"
  volatile.base_image: 87530b2678f03cbc51a7e1732acfed679c4a15ba1939197cbda733346ef28ad9
  volatile.eth0.hwaddr: 00:16:3e:50:73:41
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""

stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc config show c1 --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Alpine edge amd64 (20181004_13:00)
  image.os: Alpine
  image.release: edge
  image.serial: "20181004_13:00"
  volatile.base_image: 87530b2678f03cbc51a7e1732acfed679c4a15ba1939197cbda733346ef28ad9
  volatile.eth0.hwaddr: 00:16:3e:50:73:41
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxd sql global "SELECT containers_profiles.* FROM containers_profiles LEFT JOIN containers ON containers_profiles.container_id=containers.id WHERE containers.name='c1';"
+-----+--------------+------------+-------------+
| id  | container_id | profile_id | apply_order |
+-----+--------------+------------+-------------+
| 458 | 62           | 1          | 1           |
+-----+--------------+------------+-------------+

stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxd sql global "SELECT * FROM profiles;"
+----+---------+--------------------------------------+------------+
| id |  name   |             description              | project_id |
+----+---------+--------------------------------------+------------+
| 1  | default | Default LXD profile                  | 1          |
| 9  | default | Default LXD profile for project blah | 8          |
+----+---------+--------------------------------------+------------+
```

In this case, we can see that I'm launching a container despite not having a storage pool set in my default profile (it should fail with the missing storage error) and the reason why it succeeds is because my container is tied to the `default` profile from the `default` project rather than the `blah` project.
