### ISSUE TITLE
projects: UsedBy fields often wrong

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#5149]
Setup a project with profiles and images disabled:
```
stgraber@castiana:~$ lxc project create demo -c features.images=false -c features.profiles=false
Project demo created
stgraber@castiana:~$ lxc project switch demo
stgraber@castiana:~$ lxc launch ubuntu:18.04 c1
Creating c1
Starting c1
stgraber@castiana:~$ lxc list
+------+---------+----------------------+----------------------------------------------+------------+-----------+
| NAME |  STATE  |         IPV4         |                     IPV6                     |    TYPE    | SNAPSHOTS |
+------+---------+----------------------+----------------------------------------------+------------+-----------+
| c1   | RUNNING | 10.166.11.147 (eth0) | 2001:470:b368:4242:216:3eff:fef6:58a8 (eth0) | PERSISTENT |           |
+------+---------+----------------------+----------------------------------------------+------------+-----------+
```

Look at usage for the default bridge:
```
stgraber@castiana:~$ lxc network show lxdbr0
config:
  ipv4.address: 10.166.11.1/24
  ipv4.nat: "true"
  ipv6.address: 2001:470:b368:4242::1/64
  ipv6.nat: "true"
description: ""
name: lxdbr0
type: bridge
used_by:
- /1.0/containers/centos3
- /1.0/containers/centos4
- /1.0/containers/keybase
- /1.0/containers/snapcraft
- /1.0/containers/tutorials
- /1.0/containers/ups-monitor
- /1.0/containers/zerotier
managed: true
status: Created
locations:
- none
```

This is missing `/1.0/containers/c1?project=demo`.

Let's look at the default profile:
```
stgraber@castiana:~$ lxc profile show default
config:
  user.vendor-data: |
    #cloud-config
    apt_mirror: http://us.archive.ubuntu.com/ubuntu/
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/snapcraft?project=default
- /1.0/containers/centos3?project=default
- /1.0/containers/centos4?project=default
- /1.0/containers/zerotier?project=default
- /1.0/containers/ups-monitor?project=default
- /1.0/containers/keybase?project=default
- /1.0/containers/snapcraft/snap0?project=default
- /1.0/containers/tutorials?project=default
- /1.0/containers/c1?project=default
```
This is showing needless (potentially client breaking) `?project=default` AND is mistakenly showing `project=default` for c1 when it should be `project=demo`
