### ISSUE TITLE
lxd live migration fails with rsync protocol error

### ISSUE THREAD

**Issue by danielrobbins** [lxc/lxd#5243]
When attempting a live migration, migration fails at the very end. Here is lxc monitor output from the sender. This is running a fairly recent master version:

```
metadata:
  context:
    actionscript: "false"
    created: 2018-11-01 21:00:29.198840541 +0000 -00
    ephemeral: "false"
    features: "0"
    name: illdrive
    predumpdir: ""
    project: default
    statedir: /tmp/lxd_checkpoint_328453908
    stop: "false"
    used: 2018-11-01 21:02:35.300719305 +0000 -00
  level: info
  message: Migrated container
project: ""
timestamp: "2018-11-05T07:00:26.476632406Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: sending write barrier
project: ""
timestamp: "2018-11-05T07:00:26.695774443Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Got message barrier, resetting stream
project: ""
timestamp: "2018-11-05T07:00:26.695518342Z"
type: logging


metadata:
  context: {}
  level: eror
  message: |
    Rsync send failed: /tmp/lxd_checkpoint_328453908/: exit status 12: rsync: connection unexpectedly closed (0 bytes received so far) [sender]
    rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.3]
project: ""
timestamp: "2018-11-05T07:00:26.698179436Z"
type: logging
```

Unfortunately there does not appear to be very much additional information. It looks like the pre-dump completed successfully on the sender system.
