### ISSUE TITLE
Issue with LXC Config Cloud Init Bionic Beaver

### ISSUE THREAD

**Issue by mrheroux** [lxc/lxd#5273]
I'm using LXD version 3.0.2 to trying to launch a Ubuntu:18.04 container with a Cloud Init in the LXC config to set a static IP address automatically when the container is created as described in the docs https://lxd.readthedocs.io/en/latest/cloud-init/ . Here is the LXC config:

```
architecture: x86_64
config:
  image.architecture: amd64
  image.build: "20181101_07:42"
  image.description: Ubuntu bionic amd64 (20181101_07:42)
  image.distribution: ubuntu
  image.name: ubuntu-bionic-amd64-default-20181101_07:42
  image.os: ubuntu
  image.release: bionic
  image.serial: "20181101_07:42"
  image.variant: default
  user.network-config: |
    # cloud-config
    version: 1
    config:
      - type: physical
        name: eth1
        subnets:
          - type: static
            ipv4: true
            address: 10.1.2.28
            netmask: 255.255.0.0
            gateway: 10.1.2.1
            control: auto
      - type: nameserver
        address: 10.1.2.2
  volatile.base_image: 72f74ccbb968fca13a680b22d00bbc64636bbc65a870dec79d7c711f7f8b9d85
  volatile.eth0.hwaddr: 00:16:3e:3d:af:47
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.base_image: 72f74ccbb968fca13a680b22d00bbc64636bbc65a870dec79d7c711f7f8b9d85
  volatile.eth0.hwaddr: 00:16:3e:3d:af:47
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: acad
    type: nic
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
This container and its config is automatically created using the following Ansible task. https://docs.ansible.com/ansible/latest/modules/lxd_container_module.html

```
          - name: Create a started container
            lxd_container:
                    name: "{{ container_hostname }}"
                    state: started
                    source:
                            type: image
                            mode: pull
                            server: https://images.linuxcontainers.org
                            protocol: lxd
                            alias: ubuntu/bionic/amd64
                    profiles: ["default"]
                    timeout: 600
                    config:
                        user.network-config: |
                                # cloud-config
                                version: 1
                                config:
                                      - type: physical
                                        name: eth1
                                        subnets:
                                          - type: static
                                            ipv4: true
                                            address: 10.1.2.28
                                            netmask: 255.255.0.0
                                            gateway: 10.1.2.1
                                            control: auto
                                      - type: nameserver
                                        address: 10.1.2.2
                    devices: {"eth0":{"name":"eth0","nictype":"bridged","parent":"acad","type":"nic"}}
                    wait_for_ipv4_addresses: true

```

When the container starts the config looks alright. Trouble is, it has a DHCP address and there is a /etc/netplan/10-lxc.yaml file that contains the following:

```
network:
  version: 2
  ethernets:
    eth0: {dhcp4: true}
```
Ideally, I'd like this file to contain my netplan, e.g.

```
                              network:
                                   ethernets:
                                      eth0:
                                           addresses: [10.1.2.28/16]
                                            gateway4: 10.1.2.1
                                           nameservers:
                                                - 10.1.2.2
                                            dhcp4: no
                                   version: 2

```
Am I missing something or is this broken?
