### ISSUE TITLE
Features request: lxc up aka read a list of containers to be created

### ISSUE THREAD

**Issue by karlfiabeschi** [lxc/lxd#5287]
Hi guys,
'This feature request because i saw this project: https://github.com/lxdock/lxdock.
It's possible to implement a simplify version directly in lxd?
Something extremely simple: the possibily to read from a file a list of containers to be created, practically a lxd launch repeated but easier to write and execute.

something like:

`lxc up`

or

`lxc launch up`

wich search in the current directory a _lxdfile_, with lxdfile like this:

```
---
mycontainer1:
  image: archlinux
  profle: default
  remote: 
  project: test

mycontainer2:
  image: centos7/current
  profile: lan
  remote: myremote1

```

or maybe a json one? 

I'm know that it's not your priority but it would be nice as features especially for many project with github / gitlab repository, i dream filled with a lxdifle to start immediately a certain series of containers.

thanks regardless for this fantastic project and sorry for bad english

KF
