### ISSUE TITLE
Size prompt is misleading

### ISSUE THREAD

**Issue by jameinel** [lxc/lxd#5295]
# Required information

 * Distribution: Ubuntu
 * Distribution version: bionic
 * The output of "lxc info" or if that fails:
```
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 3.0.2
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-39-generic
  server: lxd
  server_pid: 4264
  server_version: "3.7"
  storage: ""
  storage_version: ""
  server_clustered: false
  server_name: bio
  project: default
```
# Issue description

When running `lxd init` it gives you:

Size in GB of the new loop device (1GB minimum) [default=15GB]: 

However, that "default=15GB" makes me think I should write "10GB" or "10G", when neither is allowed, you have to type "10".
I realize that it does say "Size in GB", but the "default=X" heavily encourages you to follow suite with what you type.

# Steps to reproduce

 1. lxd init on a new machine
 2. follow the prompts to configure a new storage pool
 3. try to change the default size

# Information to attach

```
Size in GB of the new loop device (1GB minimum) [default=15GB]: 10GB
Invalid input, try again.

Size in GB of the new loop device (1GB minimum) [default=15GB]: 10G
Invalid input, try again.

Size in GB of the new loop device (1GB minimum) [default=15GB]: 10
```

I'd be happy with either accepting the string, or possibly changing the default= prompt.
