### ISSUE TITLE
subvolumes not working with volume.block.filesystem: btrfs

### ISSUE THREAD

**Issue by bit** [lxc/lxd#5301]
using btrfs as filesystem for ceph volumes,
lxd containers should be able to use subvolumes.

right now i.e. listing subvolumes is not working:
```
btrfs subvolume list /
ERROR: can't perform the search - Operation not permitted
```

```
config:
  ...
  ceph.osd.pool_name: lxd                                                
  volume.block.filesystem: btrfs
```
