### ISSUE TITLE
Nested container: unable to negotiate SSL connection (OpenSSL SSL_connect: SSL_ERROR_SYSCALL)

### ISSUE THREAD

**Issue by palica** [lxc/lxd#5314]
# Required information

 * Distribution: gentoo
 * Distribution version: current
 * The output of "lxc info" or if that fails: 

* _server_ host
```
  driver: lxc
  driver_version: 3.0.2
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.18.5-dl3x0-g7-r1
  server: lxd
  server_pid: 6282
  server_version: 3.0.0
  storage: btrfs
  storage_version: 4.17.1
  server_clustered: false
  server_name: robor
```
 
* _parent-container_
```
  driver: lxc
  driver_version: 3.0.2
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.18.5-dl3x0-g7-r1
  server: lxd
  server_pid: 11772
  server_version: "3.6"
  storage: dir
  storage_version: "1"
  server_clustered: false
  server_name: metro-build-server
  project: default
```

# Issue description

When running nested container I am experiencing problems while downloading a tarball from https protocol. 

# Steps to reproduce

I have a _server_ with LXD 3.0.0 - this is hosting an unprivileged _parent-container_ - that in turn is running LXD 3.6 and hosting an unprivileged _nested-container_.
I was trying to download iptables tarball over https. It ends with an error:
```
nested-container # curl -v https://www.netfilter.org/projects/iptables/files/iptables-1.8.2.tar.bz2 -o iptables-1.8.2.tar.bz2
*   Trying 150.214.142.167...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to www.netfilter.org (150.214.142.167) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
  0     0    0     0    0     0      0      0 --:--:--  0:03:24 --:--:--     0* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.netfilter.org:443
  0     0    0     0    0     0      0      0 --:--:--  0:03:24 --:--:--     0
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.netfilter.org:443
nested-container #
```
The same download works fine from the _parent-container_:

```
parent-container # curl -v https://www.netfilter.org/projects/iptables/files/iptables-1.8.2.tar.bz2 -o iptables-1.8.2.tar.bz2
*   Trying 150.214.142.167...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to www.netfilter.org (150.214.142.167) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [98 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2860 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [589 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=netfilter.org
*  start date: Nov 12 07:11:53 2018 GMT
*  expire date: Feb 10 07:11:53 2019 GMT
*  subjectAltName: host "www.netfilter.org" matched cert's "www.netfilter.org"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
} [5 bytes data]
> GET /projects/iptables/files/iptables-1.8.2.tar.bz2 HTTP/1.1
> Host: www.netfilter.org
> User-Agent: curl/7.61.0
> Accept: */* 
> 
{ [5 bytes data]
< HTTP/1.1 200 OK
< Date: Wed, 28 Nov 2018 09:04:56 GMT
< Server: Apache/2.4.10 (Debian) OpenSSL/1.0.1t
< Last-Modified: Tue, 13 Nov 2018 10:42:51 GMT
< ETag: "a5fb2-57a897abdce01"
< Accept-Ranges: bytes
< Content-Length: 679858
< Content-Type: application/x-bzip2
< 
{ [5 bytes data]
100  663k  100  663k    0     0  1459k      0 --:--:-- --:--:-- --:--:-- 1462k
* Connection #0 to host www.netfilter.org left intact
parent-container #
```
and also from the _server_.

# Information to attach

nested-container config:
```
architecture: x86_64
config:
  environment.LANG: en_US.UTF-8
  environment.LC_ALL: en_US.UTF-8
  environment.LC_COLLATE: POSIX
  image.description: 1.3 Release Westmere 64bit [std] 2018-11-24
  image.name: 1.3-release-std-x86-64bit-intel64-westmere
  migration.incremental.memory: "true"
  raw.lxc: lxc.mount.entry = none dev/shm tmpfs rw,nosuid,nodev,create=dir
  volatile.base_image: bdc7552a59e2e93de1f8a8bd6c9f0933268b425312902197ffc5a47c4ae697c1
  volatile.eth0.hwaddr: 00:16:3e:2d:04:15
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":65536,"Nsid":0,"Maprange":131072},{"Isuid":false,"Isgid":true,"Hostid":65536,"Nsid":0,"Maprange":131072}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":65536,"Nsid":0,"Maprange":131072},{"Isuid":false,"Isgid":true,"Hostid":65536,"Nsid":0,"Maprange":131072}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
parent-container config:
```
architecture: x86_64
config:
  environment.LANG: en_US.UTF-8
  environment.LC_ALL: en_US.UTF-8
  environment.LC_COLLATE: POSIX
  migration.incremental.memory: "true"
  raw.lxc: lxc.mount.entry = none dev/shm tmpfs rw,nosuid,nodev,create=dir
  security.idmap.isolated: "true"
  security.idmap.size: "200000"
  security.nesting: "true"
  security.privileged: "false"
  volatile.base_image: 424bb25173754bf2373ee49db389c287819953d6f0acce29ac7fe5495310f666
  volatile.eth0.hwaddr: 00:16:3e:51:e8:bc
  volatile.idmap.base: "8600000"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":8600000,"Nsid":0,"Maprange":200000},{"Isuid":false,"Isgid":true,"Hostid":8600000,"Nsid":0,"Maprange":200000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":8600000,"Nsid":0,"Maprange":200000},{"Isuid":false,"Isgid":true,"Hostid":8600000,"Nsid":0,"Maprange":200000}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: vxlanbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

Please let me know if I can provide any more information. Thank you for your help.
