### ISSUE TITLE
device not loaded from profile

### ISSUE THREAD

**Issue by GPelz** [lxc/lxd#5382]
I got the following default profile:
```
lxc profile show default

config:
  environment.http_proxy: ""
  user.network_mode: ""
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    type: disk
  sdb:
    path: /home
    source: /home
    type: disk
  sdc:
    path: /var/nfs
    source: /var/nfs
    type: disk
name: default
used_by:
- /1.0/containers/server101
- /1.0/containers/server102
- /1.0/containers/server103
- /1.0/containers/server104
- /1.0/containers/server105
```
and my configs looks like these:
```
lxc config show server101

architecture: x86_64
config:
  boot.autostart: "true"
  volatile.base_image: 0c85c33e8528b21910364dfa12328ba91416edf4bc3c2d606b2224075e9b79ba
  volatile.eth0.hwaddr: 00:16:3e:49:0e:02
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
yesterday I did a dist-upgrade (running Ubuntu 18.04 server) which also updated lxc/lxd and now none of my instances will start,..
I just get:
```
lxc start server101

Error: Common start logic: Set volatile.last_state.idmap config key on container "server101" (id 1): Containers must have a root disk device (directly or inherited)
```
runing 'lxc info --show-log server101', I get:
```
Name: server101
Remote: unix://
Architektur: x86_64
Erstellt: 2018/06/11 10:41 UTC
Status : Stopped
Type: persistent
Profile: default

Protokoll:

```
seems to me like the root disk device isn't taken from the profile like it was before the update.

'lxc storage list'
gives me:
```
+---------+--------------+--------+------------------------------------+-------------+
|  NAME   | BESCHREIBUNG | DRIVER |               SOURCE               | BENUTZT VON |
+---------+--------------+--------+------------------------------------+-------------+
| default |              | btrfs  | /var/lib/lxd/storage-pools/default | 5           |
+---------+--------------+--------+------------------------------------+-------------+
```

Since I'm fairly inexperienced with lxc&co I hope someone can tell me how to fix this.
(Like I wrote, this setup did run fine till the update, so the configs shouldn't be that messed up. :))

Thanks!

**Comment by stgraber** [comment]
Your root device in the default profile above is missing the pool property which in your case should be set to default

**Comment by GPelz** [comment]
Calling 'lxc profile edit default' and changing
```
  root:
    path: /
    type: disk
```
to
```
  root:
    path: /
    type: disk
    pool: default
```
gives me
```
Config parsing error: At least one container relies on this profile's root disk device
```
saving the file before closing (not while) gives me:
```
Config parsing error: The following containers failed to update (profile change still saved):
 - server101: Containers must have a root disk device (directly or inherited)
 - server102: Containers must have a root disk device (directly or inherited)
 - server103: Containers must have a root disk device (directly or inherited)
 - server104: Containers must have a root disk device (directly or inherited)
 - server105: Containers must have a root disk device (directly or inherited)
```
-> Any idea on how to fix this?

**Comment by stgraber** [comment]
What's `lxc config show --expanded server101` showing you now?

**Comment by stgraber** [comment]
As per the error above, the profile change should have been saved regardless, so assuming there's nothing wrong, the container configuration should be correct now.

**Comment by GPelz** [comment]
it didn't change the profile
I tried saving using 'CTRL+O' and then exiting, which gave the above error but it still wants to go back to nano and edit the file. :(
which is why 'lxc config show --expanded server101' still looks like this:
```
architecture: x86_64
config:
  boot.autostart: "true"
  environment.http_proxy: ""
  user.network_mode: ""
  volatile.base_image: 0c85c33e8528b21910364dfa12328ba91416edf4bc3c2d606b2224075e9b79ba
  volatile.eth0.hwaddr: 00:16:3e:49:0e:02
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    type: disk
  sdb:
    path: /home
    source: /home
    type: disk
  sdc:
    path: /var/nfs
    source: /var/nfs
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

**Comment by stgraber** [comment]
That's odd, okay, then, this should unstick things:
 - lxc config device add server101 root disk path=/ pool=default
 - lxc config device add server102 root disk path=/ pool=default
 - lxc config device add server103 root disk path=/ pool=default
 - lxc config device add server104 root disk path=/ pool=default
 - lxc config device add server105 root disk path=/ pool=default
 - lxc profile device set default root pool default

So effectively first manually fixing all the containers individually and then applying the profile change which should then be happy to comply.

**Comment by GPelz** [comment]
``
lxc config device add server101 root disk path=/ pool=default
``
gives me:
``
Error: The storage pool of the root disk can only be changed through move
``

**Comment by GPelz** [comment]
```
lxd sql global "INSERT INTO profiles_devices_config (profile_device_id, key, value) VALUES (23, 'pool', 'default');"
Rows affected: 1
```
added the pool to the default profile :+1: 
and to the container :+1: 
```
lxc config show --expanded server101
architecture: x86_64
config:
  boot.autostart: "true"
  environment.http_proxy: ""
  user.network_mode: ""
  volatile.base_image: 0c85c33e8528b21910364dfa12328ba91416edf4bc3c2d606b2224075e9b79ba
  volatile.eth0.hwaddr: 00:16:3e:49:0e:02
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
  sdb:
    path: /home
    source: /home
    type: disk
  sdc:
    path: /var/nfs
    source: /var/nfs
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
Thanks a lot, you really saved my day here!
