### ISSUE TITLE
Edit: LXD 3.0.3 as well as 3.9 - Setting disk iops limits prevent LXD from mounting ZFS dataset

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#5429]
Ubuntu Bionic
Upgraded to 3.0.3 with apt from 3.0.2

Run lxd init with a custom profile where you have something like

```
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    limits.read: 40000iops
    limits.write: 10000iops
    path: /
    pool: lxd
    size: 8GB
    type: disk
```

Gets you something like:

```
root@keiko # lxc init ubuntu:bionic testkeiko --profile webdockssd3
Creating testkeiko
Error: Failed container creation: Create LXC container: Initialize LXC: no such file or directory
```

Output of /var/log/lxd/lxd.log

```
t=2019-01-23T11:00:19+0100 lvl=info msg="Creating container" ephemeral=false name=testkeiko
t=2019-01-23T11:00:29+0100 lvl=eror msg="Failed to mount ZFS dataset \"lxd/containers/testkeiko\" onto \"/var/lib/lxd/storage-pools/lxd/containers/testkeiko\"" 
t=2019-01-23T11:00:39+0100 lvl=eror msg="Failed to mount ZFS dataset \"lxd/containers/testkeiko\" onto \"/var/lib/lxd/storage-pools/lxd/containers/testkeiko\"" 
```

Removing 
    limits.read: 40000iops
    limits.write: 10000iops

From the profile enables LXD to create the container without problems. Size limit works as usual.

**Edit:** Tried upgrading to v3.9 via snap to see if behavior changes. I get the same result - lxc monitor excerpt:

```
metadata:
  context:
    image: 485d20511dd421d05d45bf16d4becc090cb8692bf1e459317a2d069fdd3745dd
  level: dbug
  message: Image already exists in the db
timestamp: "2019-01-25T06:04:57.739295498-06:00"
type: logging


metadata:
  context:
    ephemeral: "false"
    name: testnew
    project: default
  level: info
  message: Creating container
timestamp: "2019-01-25T06:04:57.772237979-06:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting ZFS storage volume for container "testnew" on storage pool "lxd"
timestamp: "2019-01-25T06:04:57.824807133-06:00"
type: logging


metadata:
  context: {}
  level: eror
  message: 'Failed to mount ZFS dataset "lxd/containers/testnew" onto "/var/snap/lxd/common/lxd/storage-pools/lxd/containers/testnew":
    no such file or directory'
timestamp: "2019-01-25T06:05:07.840196967-06:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting ZFS storage volume for container "testnew" on storage pool "lxd"
timestamp: "2019-01-25T06:05:07.841071631-06:00"
type: logging


metadata:
  context: {}
  level: eror
  message: 'Failed to mount ZFS dataset "lxd/containers/testnew" onto "/var/snap/lxd/common/lxd/storage-pools/lxd/containers/testnew":
    no such file or directory'
timestamp: "2019-01-25T06:05:17.855346568-06:00"
type: logging


metadata:
  context:
    created: 2019-01-25 06:04:57.7431599 -0600 CST
    ephemeral: "false"
    name: testnew
    project: default
    used: 1969-12-31 18:00:00 -0600 CST
  level: info
  message: Deleting container
timestamp: "2019-01-25T06:05:17.855507683-06:00"
type: logging
```

Creating the directory beforehand has no effect - I thought I might as well try. What is going on here? I was expecting this to be a v3.0.3 specific issue - and I have doublechecked the docs, the syntax for iops limiting seems not to have changed.

This is somewhat critical as without IOPS limits we run into ZFS deadlocks which kills disk I/O on our busy systems, which is quite catastrophic as we then need to reboot the host :(

It seems I cannot downgrade to v3.0.2 - is this correct? Oh how I miss the stable days of 3.0.2 right now :D
