### ISSUE TITLE
Restarting a CentOS6 container makes host filesystems read-only

### ISSUE THREAD

**Issue by erikmouw** [lxc/lxd#5486]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.2
 * The output of "lxc info" or if that fails:
```
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- candid_authentication
- candid_config
- candid_config_key
- usb_optional_vendorid
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.124.246:8443
  - 192.168.122.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFRjCCAy6gAwIBAgIQV+cV7i5py5w6e6q3Dr71ejANBgkqhkiG9w0BAQsFADA0
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRQwEgYDVQQDDAtyb290QHVi
    dW50dTAeFw0xOTAyMDgxMzU0NDRaFw0yOTAyMDUxMzU0NDRaMDQxHDAaBgNVBAoT
    E2xpbnV4Y29udGFpbmVycy5vcmcxFDASBgNVBAMMC3Jvb3RAdWJ1bnR1MIICIjAN
    BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxS0cJbs0rwBlTJGsrtRdDYWYKgfj
    yfG1V2KjlKvBU8OqJm2DlI0a3kcic7Thbesc4TKgFmuKFy+Z1PLTq+LQMKgspe8G
    A/xt0M9Nehr/MbgLzSyQ9gwElSL19kgo/xApPUovymM/yC3sgC60UT5/2mUNf0fh
    fEj/xqeawGHILEmGaSBxlof9fNLi1ZtMgqbMgs9SppRCyqHcSORutGWvp74p9MpP
    O8DViHtNj0C0sGoKDcRA6Lqj70U90NKFDvK7pFS6ecMNbrqw+U/93pOWutst87od
    o4/Zohi3RdYekc0iohlK9QtgIPpbS20gft9NnG4G/PxeCO3ReqXbd6Xc0S+Ne8vY
    6YtRwvpwfHWfScTczlTEBJ7qZCtz1qG9VjLtKj1CA5ABFuVDXM9QQ9TFyU276RI5
    hyQOkLHGoKL6y3QUb2oJdoQVcwYRhTdvHma3he9d54kDHcUp3c0wvNcgTFNuwaPk
    zVzyBmrJ3MJFdlcAeQMocs+RrlljXOb1yRC3cAUfpCp7lpqnFjvCLJa0IUSvCBIU
    NYwK6p0IEhic4nNUDlWuPSpB4VCOYVgui8hC8vP/z817Oy0Ra4Z4mpe5Hqr9vSd8
    VIDyKHw6MGITUUh+8tXOOOEM2KeGbYAFj9+yTNFpdX8tC/kIve38hrdsibdQ62P3
    TENAu/myr/YPxJECAwEAAaNUMFIwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoG
    CCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwHQYDVR0RBBYwFIIGdWJ1bnR1hwTAqHz2
    hwTAqHoBMA0GCSqGSIb3DQEBCwUAA4ICAQBhRgf9h9IZRrInRRtRFCfAuWnvB2ep
    hL5AAA+8hRLT9OSxk/k7gZqrto9eagbumuaU5nBLtsdPLWZCwzLyrKNyQLHA1V9b
    ikc6H8/4+1o4zd5G8zk4LrpjjPnuR4hBtcUZ3LfbeNsJODm92altHWvsA/tCExMw
    dUl4J9B0KjCfZMOP87pgM/yitBRHjaHVKjZ0s5heuBvv1J5XvbgPF07TXUhIUX65
    Yx2YDuUlYsQ4YK9KotOL9/H5a00IvQ2mp9ZHOGbWcLj9083KW4KFYAYPqK4uWGYl
    hsxVA9LtTv4+PPsQLE+O//jWiPqY8kGd3yT3dNO1Y6kxId4UFw2Kly8TzW3/KDk3
    JfzL1r004RO8m5gYg1MkN3moGRF0oZD1LpznfBOIJzHjGHpDWztMgeG4ncXunVkG
    ptPANMqQbX5dCeiXLxQUo1mI9NECSbdn5YFjKOdWijCT0bP6T50co5geR0wll7N+
    /SluZuK/UgKdV9pvAl5awC6W0A9/Y4Mm++QUL/FYDIdubeWauR6/yR3DCXdqh8Yi
    KKCabOy07q0Dud+KqfSvzqDLbEkZYVPO7Ihv9kAXZ8f4Nnogy6Md6JMXKEHffyPy
    kTNN/mfgt+Vcj7zsBCUjAykquxBq9zWzH5DR1XsbHCEt54ShmKfcDLHO+ocnha6Q
    2piduMxu7TE28g==
    -----END CERTIFICATE-----
  certificate_fingerprint: 8aaac38120a940213cc9c48f656396366e9265f33e7494d9f72faf920875b402
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-45-generic
  server: lxd
  server_pid: 1113
  server_version: 3.0.3
  storage: btrfs
  storage_version: 4.15.1
  server_clustered: false
  server_name: ubuntu
  project: ""
```

# Issue description

Restarting a privileged CentOS6 container on a host with AppArmor disabled makes filesystems on the host read-only and prevents restarting the container, prevent restart of other containers, or creation of new containers.

AppArmor is disabled and containers are privileged to make autofs and NFS work in the container.

Restarting a privileged CentOS 7 or Ubuntu 18.04 container on the same host works as expected (i.e.: no read-only filesystems)

# Steps to reproduce

 1. DIsable AppArmor on the host (add `apparmor=0` to /etc/default/grub, run `update-grub` and reboot host)
 2. Launch a privileged CentOS6 container: `lxc launch images:centos/6/amd64 test -c security.privileged=true`
 3. Restart the container: `lxc restart test`

Result:

```
ubuntu@ubuntu:~$ lxc restart test
Error: Failed to run: /usr/lib/lxd/lxd forkstart test /var/lib/lxd/containers /var/log/lxd/test/lxc.conf:
Try `lxc info --show-log test` for more info
ubuntu@ubuntu:~$ lxc info --show-log test
Name: test
Remote: unix://
Architecture: x86_64
Created: 2019/02/12 12:19 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

lxc test 20190212121942.878 ERROR    conf - conf.c:lxc_setup_dev_console:1761 - Read-only file system - Failed to set mode "0110" to "/dev/pts/2"
lxc test 20190212121942.878 ERROR    conf - conf.c:lxc_setup:3625 - Failed to setup console
lxc test 20190212121942.878 ERROR    start - start.c:do_start:1263 - Failed to setup container "test"
lxc test 20190212121942.879 ERROR    sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 5)
lxc test 20190212121942.879 WARN     network - network.c:lxc_delete_network_priv:2589 - Operation not permitted - Failed to remove interface "eth0" with index 24
lxc test 20190212121942.879 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:842 - Received container state "ABORTING" instead of "RUNNING"
lxc test 20190212121942.879 ERROR    start - start.c:__lxc_start:1939 - Failed to spawn container "test"
lxc 20190212121942.880 WARN     commands - commands.c:lxc_cmd_rsp_recv:132 - Connection reset by peer - Failed to receive response for command "get_state"

ubuntu@ubuntu:~$ mount | grep 'ro,'
udev on /dev type devtmpfs (ro,nosuid,relatime,size=978856k,nr_inodes=244714,mode=755)
devpts on /dev/pts type devpts (ro,nosuid,noexec,relatime,mode=600,ptmxmode=000)
/dev/mapper/ubuntu--vg-root on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (ro,relatime)
lxcfs on /var/lib/lxcfs type fuse.lxcfs (ro,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
tmpfs on /var/lib/lxd/shmounts type tmpfs (ro,relatime,size=100k,mode=711)
tmpfs on /var/lib/lxd/devlxd type tmpfs (ro,relatime,size=100k,mode=755)
```

# Information to attach

 - [x] Any relevant kernel output (`dmesg`)
    Kernel output contains only information about the bridge network device
 - [x] Container log (`lxc info NAME --show-log`)
   See above
 - [x] Container configuration (`lxc config show NAME --expanded`)
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Centos 6 amd64 (20190212_07:09)
  image.os: Centos
  image.release: "6"
  image.serial: "20190212_07:09"
  security.privileged: "true"
  volatile.base_image: 3ffbaf96fa5f317be049384e1ec3396e5339db819d8521379597f77b3e47cc8d
  volatile.eth0.hwaddr: 00:16:3e:66:32:5c
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
```
t=2019-02-12T13:19:10+0100 lvl=info msg="Created container" ephemeral=false name=test
t=2019-02-12T13:19:10+0100 lvl=info msg="Starting container" action=start created=2019-02-12T13:19:10+0100 ephemeral=false name=test stateful=false used=1970-01-01T01:00:00+0100
t=2019-02-12T13:19:11+0100 lvl=info msg="Started container" action=start created=2019-02-12T13:19:10+0100 ephemeral=false name=test stateful=false used=1970-01-01T01:00:00+0100
t=2019-02-12T13:19:38+0100 lvl=info msg="Shutting down container" action=shutdown created=2019-02-12T13:19:10+0100 ephemeral=false name=test timeout=-1s used=2019-02-12T13:19:10+0100
t=2019-02-12T13:19:42+0100 lvl=info msg="Shut down container" action=shutdown created=2019-02-12T13:19:10+0100 ephemeral=false name=test timeout=-1s used=2019-02-12T13:19:10+0100
t=2019-02-12T13:19:42+0100 lvl=info msg="Starting container" action=start created=2019-02-12T13:19:10+0100 ephemeral=false name=test stateful=false used=2019-02-12T13:19:10+0100
t=2019-02-12T13:19:42+0100 lvl=eror msg="Failed starting container" action=start created=2019-02-12T13:19:10+0100 ephemeral=false name=test stateful=false used=2019-02-12T13:19:10+0100
t=2019-02-12T13:19:43+0100 lvl=info msg="Container initiated stop" action=stop created=2019-02-12T13:19:10+0100 ephemeral=false name=test stateful=false used=2019-02-12T13:19:42+0100
```
 - [x] Output of the client with --debug
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by erikmouw** [comment]
Output of the client with --debug

```
ubuntu@ubuntu:~$ lxc restart test --debug
DBUG[02-12|13:32:32] Connecting to a local LXD over a Unix socket
DBUG[02-12|13:32:32] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
DBUG[02-12|13:32:32] Got response struct from LXD
DBUG[02-12|13:32:32]
	{
		"config": {
			"core.https_address": "[::]:8443",
			"core.trust_password": true
		},
		"api_extensions": [
			"storage_zfs_remove_snapshots",
			"container_host_shutdown_timeout",
			"container_stop_priority",
			"container_syscall_filtering",
			"auth_pki",
			"container_last_used_at",
			"etag",
			"patch",
			"usb_devices",
			"https_allowed_credentials",
			"image_compression_algorithm",
			"directory_manipulation",
			"container_cpu_time",
			"storage_zfs_use_refquota",
			"storage_lvm_mount_options",
			"network",
			"profile_usedby",
			"container_push",
			"container_exec_recording",
			"certificate_update",
			"container_exec_signal_handling",
			"gpu_devices",
			"container_image_properties",
			"migration_progress",
			"id_map",
			"network_firewall_filtering",
			"network_routes",
			"storage",
			"file_delete",
			"file_append",
			"network_dhcp_expiry",
			"storage_lvm_vg_rename",
			"storage_lvm_thinpool_rename",
			"network_vlan",
			"image_create_aliases",
			"container_stateless_copy",
			"container_only_migration",
			"storage_zfs_clone_copy",
			"unix_device_rename",
			"storage_lvm_use_thinpool",
			"storage_rsync_bwlimit",
			"network_vxlan_interface",
			"storage_btrfs_mount_options",
			"entity_description",
			"image_force_refresh",
			"storage_lvm_lv_resizing",
			"id_map_base",
			"file_symlinks",
			"container_push_target",
			"network_vlan_physical",
			"storage_images_delete",
			"container_edit_metadata",
			"container_snapshot_stateful_migration",
			"storage_driver_ceph",
			"storage_ceph_user_name",
			"resource_limits",
			"storage_volatile_initial_source",
			"storage_ceph_force_osd_reuse",
			"storage_block_filesystem_btrfs",
			"resources",
			"kernel_limits",
			"storage_api_volume_rename",
			"macaroon_authentication",
			"network_sriov",
			"console",
			"restrict_devlxd",
			"migration_pre_copy",
			"infiniband",
			"maas_network",
			"devlxd_events",
			"proxy",
			"network_dhcp_gateway",
			"file_get_symlink",
			"network_leases",
			"unix_device_hotplug",
			"storage_api_local_volume_handling",
			"operation_description",
			"clustering",
			"event_lifecycle",
			"storage_api_remote_volume_handling",
			"nvidia_runtime",
			"candid_authentication",
			"candid_config",
			"candid_config_key",
			"usb_optional_vendorid"
		],
		"api_status": "stable",
		"api_version": "1.0",
		"auth": "trusted",
		"public": false,
		"auth_methods": [
			"tls"
		],
		"environment": {
			"addresses": [
				"192.168.124.246:8443",
				"192.168.122.1:8443"
			],
			"architectures": [
				"x86_64",
				"i686"
			],
			"certificate": "-----BEGIN CERTIFICATE-----\nMIIFRjCCAy6gAwIBAgIQV+cV7i5py5w6e6q3Dr71ejANBgkqhkiG9w0BAQsFADA0\nMRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRQwEgYDVQQDDAtyb290QHVi\ndW50dTAeFw0xOTAyMDgxMzU0NDRaFw0yOTAyMDUxMzU0NDRaMDQxHDAaBgNVBAoT\nE2xpbnV4Y29udGFpbmVycy5vcmcxFDASBgNVBAMMC3Jvb3RAdWJ1bnR1MIICIjAN\nBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxS0cJbs0rwBlTJGsrtRdDYWYKgfj\nyfG1V2KjlKvBU8OqJm2DlI0a3kcic7Thbesc4TKgFmuKFy+Z1PLTq+LQMKgspe8G\nA/xt0M9Nehr/MbgLzSyQ9gwElSL19kgo/xApPUovymM/yC3sgC60UT5/2mUNf0fh\nfEj/xqeawGHILEmGaSBxlof9fNLi1ZtMgqbMgs9SppRCyqHcSORutGWvp74p9MpP\nO8DViHtNj0C0sGoKDcRA6Lqj70U90NKFDvK7pFS6ecMNbrqw+U/93pOWutst87od\no4/Zohi3RdYekc0iohlK9QtgIPpbS20gft9NnG4G/PxeCO3ReqXbd6Xc0S+Ne8vY\n6YtRwvpwfHWfScTczlTEBJ7qZCtz1qG9VjLtKj1CA5ABFuVDXM9QQ9TFyU276RI5\nhyQOkLHGoKL6y3QUb2oJdoQVcwYRhTdvHma3he9d54kDHcUp3c0wvNcgTFNuwaPk\nzVzyBmrJ3MJFdlcAeQMocs+RrlljXOb1yRC3cAUfpCp7lpqnFjvCLJa0IUSvCBIU\nNYwK6p0IEhic4nNUDlWuPSpB4VCOYVgui8hC8vP/z817Oy0Ra4Z4mpe5Hqr9vSd8\nVIDyKHw6MGITUUh+8tXOOOEM2KeGbYAFj9+yTNFpdX8tC/kIve38hrdsibdQ62P3\nTENAu/myr/YPxJECAwEAAaNUMFIwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoG\nCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwHQYDVR0RBBYwFIIGdWJ1bnR1hwTAqHz2\nhwTAqHoBMA0GCSqGSIb3DQEBCwUAA4ICAQBhRgf9h9IZRrInRRtRFCfAuWnvB2ep\nhL5AAA+8hRLT9OSxk/k7gZqrto9eagbumuaU5nBLtsdPLWZCwzLyrKNyQLHA1V9b\nikc6H8/4+1o4zd5G8zk4LrpjjPnuR4hBtcUZ3LfbeNsJODm92altHWvsA/tCExMw\ndUl4J9B0KjCfZMOP87pgM/yitBRHjaHVKjZ0s5heuBvv1J5XvbgPF07TXUhIUX65\nYx2YDuUlYsQ4YK9KotOL9/H5a00IvQ2mp9ZHOGbWcLj9083KW4KFYAYPqK4uWGYl\nhsxVA9LtTv4+PPsQLE+O//jWiPqY8kGd3yT3dNO1Y6kxId4UFw2Kly8TzW3/KDk3\nJfzL1r004RO8m5gYg1MkN3moGRF0oZD1LpznfBOIJzHjGHpDWztMgeG4ncXunVkG\nptPANMqQbX5dCeiXLxQUo1mI9NECSbdn5YFjKOdWijCT0bP6T50co5geR0wll7N+\n/SluZuK/UgKdV9pvAl5awC6W0A9/Y4Mm++QUL/FYDIdubeWauR6/yR3DCXdqh8Yi\nKKCabOy07q0Dud+KqfSvzqDLbEkZYVPO7Ihv9kAXZ8f4Nnogy6Md6JMXKEHffyPy\nkTNN/mfgt+Vcj7zsBCUjAykquxBq9zWzH5DR1XsbHCEt54ShmKfcDLHO+ocnha6Q\n2piduMxu7TE28g==\n-----END CERTIFICATE-----\n",
			"certificate_fingerprint": "8aaac38120a940213cc9c48f656396366e9265f33e7494d9f72faf920875b402",
			"driver": "lxc",
			"driver_version": "3.0.3",
			"kernel": "Linux",
			"kernel_architecture": "x86_64",
			"kernel_version": "4.15.0-45-generic",
			"server": "lxd",
			"server_pid": 5813,
			"server_version": "3.0.3",
			"storage": "btrfs",
			"storage_version": "4.15.1",
			"server_clustered": false,
			"server_name": "ubuntu",
			"project": ""
		}
	}
DBUG[02-12|13:32:32] Connected to the websocket
DBUG[02-12|13:32:32] Sending request to LXD                   method=PUT url=http://unix.socket/1.0/containers/test/state etag=
DBUG[02-12|13:32:32]
	{
		"action": "restart",
		"timeout": -1,
		"force": false,
		"stateful": false
	}
DBUG[02-12|13:32:32] Got operation from LXD
DBUG[02-12|13:32:32]
	{
		"id": "0c293373-3b3e-4564-8607-553a8ebdf7da",
		"class": "task",
		"description": "Restarting container",
		"created_at": "2019-02-12T13:32:32.45394982+01:00",
		"updated_at": "2019-02-12T13:32:32.45394982+01:00",
		"status": "Running",
		"status_code": 103,
		"resources": {
			"containers": [
				"/1.0/containers/test"
			]
		},
		"metadata": null,
		"may_cancel": false,
		"err": ""
	}
DBUG[02-12|13:32:32] Sending request to LXD                   method=GET url=http://unix.socket/1.0/operations/0c293373-3b3e-4564-8607-553a8ebdf7da etag=
DBUG[02-12|13:32:32] Got response struct from LXD
DBUG[02-12|13:32:32]
	{
		"id": "0c293373-3b3e-4564-8607-553a8ebdf7da",
		"class": "task",
		"description": "Restarting container",
		"created_at": "2019-02-12T13:32:32.45394982+01:00",
		"updated_at": "2019-02-12T13:32:32.45394982+01:00",
		"status": "Running",
		"status_code": 103,
		"resources": {
			"containers": [
				"/1.0/containers/test"
			]
		},
		"metadata": null,
		"may_cancel": false,
		"err": ""
	}
Error: Failed to run: /usr/lib/lxd/lxd forkstart test /var/lib/lxd/containers /var/log/lxd/test/lxc.conf:
Try `lxc info --show-log test` for more info
```

**Comment by erikmouw** [comment]
Output of `lxc monitor`:

```
root@ubuntu:~# lxc monitor
metadata:
  context: {}
  level: dbug
  message: 'New event listener: 14eb8f74-8c49-4bb7-ba64-91ba3b0336b5'
timestamp: "2019-02-12T13:32:11.664805135+01:00"
type: logging




^C
root@ubuntu:~# lxc monitor
metadata:
  context: {}
  level: dbug
  message: 'New event listener: eec66f03-7ff3-4236-b0e7-4d3d16bcf57d'
timestamp: "2019-02-12T13:32:17.023773659+01:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-12T13:32:32.446083104+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'New event listener: 7f1702b7-db1e-49cd-86d5-e507dff89380'
timestamp: "2019-02-12T13:32:32.450409027+01:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/events?project=
  level: dbug
  message: handling
timestamp: "2019-02-12T13:32:32.450294194+01:00"
type: logging


metadata:
  context:
    ip: '@'
    method: PUT
    url: /1.0/containers/test/state
  level: dbug
  message: handling
timestamp: "2019-02-12T13:32:32.452312879+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'New task operation: 0c293373-3b3e-4564-8607-553a8ebdf7da'
timestamp: "2019-02-12T13:32:32.455539891+01:00"
type: logging


metadata:
  class: task
  created_at: "2019-02-12T13:32:32.45394982+01:00"
  description: Restarting container
  err: ""
  id: 0c293373-3b3e-4564-8607-553a8ebdf7da
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/test
  status: Pending
  status_code: 105
  updated_at: "2019-02-12T13:32:32.45394982+01:00"
timestamp: "2019-02-12T13:32:32.455562517+01:00"
type: operation


metadata:
  context:
    action: shutdown
    created: 2019-02-12 13:31:18 +0100 CET
    ephemeral: "false"
    name: test
    timeout: -1s
    used: 2019-02-12 13:31:18.630634306 +0100 CET
  level: info
  message: Shutting down container
timestamp: "2019-02-12T13:32:32.456050765+01:00"
type: logging


metadata:
  class: task
  created_at: "2019-02-12T13:32:32.45394982+01:00"
  description: Restarting container
  err: ""
  id: 0c293373-3b3e-4564-8607-553a8ebdf7da
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/test
  status: Running
  status_code: 103
  updated_at: "2019-02-12T13:32:32.45394982+01:00"
timestamp: "2019-02-12T13:32:32.455592435+01:00"
type: operation


metadata:
  context: {}
  level: dbug
  message: 'Started task operation: 0c293373-3b3e-4564-8607-553a8ebdf7da'
timestamp: "2019-02-12T13:32:32.455583943+01:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/operations/0c293373-3b3e-4564-8607-553a8ebdf7da
  level: dbug
  message: handling
timestamp: "2019-02-12T13:32:32.462500428+01:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-12T13:32:36.740878842+01:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /internal/containers/14/onstop?target=stop
  level: dbug
  message: handling
timestamp: "2019-02-12T13:32:36.744114866+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: container test stopped: re-balancing'
timestamp: "2019-02-12T13:32:36.749402267+01:00"
type: logging


metadata:
  action: container-shutdown
  source: /1.0/containers/test
timestamp: "2019-02-12T13:32:36.760296614+01:00"
type: lifecycle


metadata:
  context:
    action: shutdown
    created: 2019-02-12 13:31:18 +0100 CET
    ephemeral: "false"
    name: test
    timeout: -1s
    used: 2019-02-12 13:31:18.630634306 +0100 CET
  level: info
  message: Shut down container
timestamp: "2019-02-12T13:32:36.760259715+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounted BTRFS storage volume for container "test" on storage pool "default"
timestamp: "2019-02-12T13:32:36.78256506+01:00"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/test
timestamp: "2019-02-12T13:32:36.779951378+01:00"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: Mounting BTRFS storage pool "default"
timestamp: "2019-02-12T13:32:36.782373166+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting BTRFS storage volume for container "test" on storage pool "default"
timestamp: "2019-02-12T13:32:36.782349595+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting BTRFS storage pool "default"
timestamp: "2019-02-12T13:32:36.785945481+01:00"
type: logging


metadata:
  context:
    action: start
    created: 2019-02-12 13:31:18 +0100 CET
    ephemeral: "false"
    name: test
    stateful: "false"
    used: 2019-02-12 13:31:18.630634306 +0100 CET
  level: info
  message: Starting container
timestamp: "2019-02-12T13:32:36.786156734+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting BTRFS storage volume for container "test" on storage pool "default"
timestamp: "2019-02-12T13:32:36.78592468+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounted BTRFS storage volume for container "test" on storage pool "default"
timestamp: "2019-02-12T13:32:36.786109016+01:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-12T13:32:36.816162882+01:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /internal/containers/14/onstart
  level: dbug
  message: handling
timestamp: "2019-02-12T13:32:36.819171381+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting BTRFS storage volume for container "test" on storage pool "default"
timestamp: "2019-02-12T13:32:36.824156257+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting BTRFS storage pool "default"
timestamp: "2019-02-12T13:32:36.824173283+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounted BTRFS storage volume for container "test" on storage pool "default"
timestamp: "2019-02-12T13:32:36.824355774+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: container test started: re-balancing'
timestamp: "2019-02-12T13:32:36.826649651+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth4IG8JL has been added: updating network priorities'
timestamp: "2019-02-12T13:32:36.970116805+01:00"
type: logging


metadata:
  context:
    action: start
    created: 2019-02-12 13:31:18 +0100 CET
    ephemeral: "false"
    name: test
    stateful: "false"
    used: 2019-02-12 13:31:18.630634306 +0100 CET
  level: eror
  message: Failed starting container
timestamp: "2019-02-12T13:32:36.970696761+01:00"
type: logging


metadata:
  class: task
  created_at: "2019-02-12T13:32:32.45394982+01:00"
  description: Restarting container
  err: 'Failed to run: /usr/lib/lxd/lxd forkstart test /var/lib/lxd/containers /var/log/lxd/test/lxc.conf: '
  id: 0c293373-3b3e-4564-8607-553a8ebdf7da
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/test
  status: Failure
  status_code: 400
  updated_at: "2019-02-12T13:32:32.45394982+01:00"
timestamp: "2019-02-12T13:32:36.970745702+01:00"
type: operation


metadata:
  context: {}
  level: dbug
  message: 'Failure for task operation: 0c293373-3b3e-4564-8607-553a8ebdf7da: Failed
    to run: /usr/lib/lxd/lxd forkstart test /var/lib/lxd/containers /var/log/lxd/test/lxc.conf: '
timestamp: "2019-02-12T13:32:36.970730244+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Disconnected event listener: 7f1702b7-db1e-49cd-86d5-e507dff89380'
timestamp: "2019-02-12T13:32:36.973771829+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth3C0DBN has been added: updating network priorities'
timestamp: "2019-02-12T13:32:36.97368685+01:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2019-02-12T13:32:37.490641928+01:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /internal/containers/14/onstop?target=stop
  level: dbug
  message: handling
timestamp: "2019-02-12T13:32:37.494177004+01:00"
type: logging


metadata:
  context:
    action: stop
    created: 2019-02-12 13:31:18 +0100 CET
    ephemeral: "false"
    name: test
    stateful: "false"
    used: 2019-02-12 13:32:36.785024285 +0100 CET
  level: info
  message: Container initiated stop
timestamp: "2019-02-12T13:32:37.502162567+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: container test stopped: re-balancing'
timestamp: "2019-02-12T13:32:37.504737357+01:00"
type: logging

```
