### ISSUE TITLE
Progress percentage during publication is quite wrong

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#5503]
```
metadata:
  class: task
  created_at: "2019-02-17T16:24:39.596102399-05:00"
  description: Downloading image
  err: ""
  id: 6307a2bb-823b-4df1-a804-238162fd55a1
  may_cancel: false
  metadata:
    create_image_from_container_pack_progress: 'Image pack: 979531264% (44.50MB/s)'
    progress:
      percent: "979531264"
      speed: "44501347"
      stage: create_image_from_container_pack
  resources: null
  status: Running
  status_code: 103
  updated_at: "2019-02-17T16:25:02.790891438-05:00"
timestamp: "2019-02-17T16:25:02.790985077-05:00"
type: operation
```

`979531264%` is obviously a bit wrong :)

@joelhockey is that something you can look into?
