### ISSUE TITLE
lxd init --dump yaml output can't be parsed due to missing quotes around fields with colons

### ISSUE THREAD

**Issue by sachin-0chain** [lxc/lxd#5547]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. lxd init --dump 
 2. Capture the output and try to parse as YAML
 3. Ansible gives error parsing the YAML output.

```
TASK [lxd : LXC-REMOVE-CONTAINERS | Read contents from the file] ****************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [tito-controller]: FAILED! => changed=false 
  ansible_facts:
    LXC_CONTAINERS: {}
  ansible_included_var_files: []
  message: /Volumes/work/imagestore/generated/tito-controller/lxc_containers.yml must be stored as a dictionary/hash

```
4. Fix the lxc_containers.yml file replacing all the colons with quotes. Example of few such fields...

```
          packets_received: 0
          packets_sent: 0
        hwaddr: '02:42:55:4f:5e:f4'
        host_name: ""
        mtu: 1500
        state: up
        type: broadcast
      eth0:
        addresses:
        - family: inet
          address: 10.1.15.178
          netmask: "24"
          scope: global
        - family: inet6
          address: 'fe80::216:3eff:fe55:a05e'
          netmask: "64"

```
5. Running with the fixed file works...
Here is the diff of the two files...

```
➜  tito-controller git:(master) ✗ diff lxc_containers.yml lxc_containers_fixed.yml 
<     volatile.eth0.hwaddr: 00:16:3e:55:a0:5e
---
>     volatile.eth0.hwaddr: '00:16:3e:55:a0:5e'
<   created_at: 2019-03-04T18:14:08.498673555Z
---
>   created_at: '2019-03-04T18:14:08.498673555Z'
<     volatile.eth0.hwaddr: 00:16:3e:55:a0:5e
---
>     volatile.eth0.hwaddr: '00:16:3e:55:a0:5e'
<   last_used_at: 2019-03-05T01:14:38.128121944Z
---
>   last_used_at: '2019-03-05T01:14:38.128121944Z'
---
>         hwaddr: '02:42:55:4f:5e:f4'
>           address: 'fe80::216:3eff:fe55:a05e'
>           netmask: "64"
>           scope: link
>         hwaddr: '00:16:3e:55:a0:5e'
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
