### ISSUE TITLE
How to import container to a different storage?

### ISSUE THREAD

**Issue by adamryczkowski** [lxc/lxd#5589]
My server on `btrfs` has broken and now I setup a new one on `zfs`. Now I want to restore the backups of my containers to the new server. How to do it properly? Perhaps I can just rsync rootfs between the uncompressed backup and the newly created blank container? 

The documentation does not mention it, and doing `lxc import <container_backup.tar.xz>` complains about incompatible storages.

**Comment by huegelc** [comment]
AFAIK you have to edit `backup.yml` and change the driver option in the pool section (eventually the source path as well if this differs):

```
pool:
  config:
    source: /var/lib/lxd/storage-pools/default
  description: ""
  name: default
  driver: dir
  used_by: []
  status: Created
  locations:
  - none
```
rsync the container to `/var/lib/lxd/storage-pools/default/containers/<your_container>

create a symbolic link `ln -s /var/lib/lxd/storage-pools/default/containers/<your_container>  /var/lib/lxd/containers/<your_container>`

`lxd import <your_container> && lxc start <your_container>`


But perhaps there is a better way to achieve that.
