### ISSUE TITLE
Void Linux container hangs on stop

### ISSUE THREAD

**Issue by Anachron** [lxc/lxd#5592]
# Required information

 * Distribution: Void Linux
 * Distribution version: latest (rolling-release)
 * The output of "lxc info" or if that fails:
```
config:
  images.auto_update_interval: "0"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICITCCAaegAwIBAgIQKmiVis4bMCFZrnuJ4+HeTjAKBggqhkjOPQQDAzA2MRww
    GgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRYwFAYDVQQDDA1yb290QHZvaWQt
    bGFwMB4XDTE5MDMyMjA4NDUxOVoXDTI5MDMxOTA4NDUxOVowNjEcMBoGA1UEChMT
    bGludXhjb250YWluZXJzLm9yZzEWMBQGA1UEAwwNcm9vdEB2b2lkLWxhcDB2MBAG
    ByqGSM49AgEGBSuBBAAiA2IABIfI/kGxiaueDaYgc7a1AoT/BW8t6uaxLn2ZTVUZ
    G74SUCjTKYSmkpYtlO4vby+HYLVsAHH4jqOgkTKg+I/A0OzxBHfx4dnKtOezdS+F
    dB4Loxu0nxxhOJ/KN6bfTqthfqN6MHgwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQM
    MAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwQwYDVR0RBDwwOoIIdm9pZC1sYXCH
    BMCoAmiHECADAM0HAesEQA/PPNoSWKiHBAoiPgGHEP1C0vPYiR6eAAAAAAAAAAEw
    CgYIKoZIzj0EAwMDaAAwZQIwOfRXn4o9TyBMw0kPmAAoWt6yEzsv8rhWrXM17u+t
    G3mPVhA1xbPbkf8NYv4WYFMAAjEAwxg07u4x1NM8r8IVwlpGwO7VdQMXpypyu8Id
    +tmbuO9tSxrT6ZL4M6Kb3sEXbfM4
    -----END CERTIFICATE-----
  certificate_fingerprint: 426d935737c582e1df79ad9493048b3fd86160f836ce443ce33b14d0a43255b9
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.19.30_1
  server: lxd
  server_pid: 17482
  server_version: "3.11"
  storage: dir
  storage_version: "1"
  server_clustered: false
  server_name: void-lap
  project: default
```

   * Kernel version: Linux void-lap 4.19.30_1 #1 SMP PREEMPT Wed Mar 20 09:17:21 UTC 2019 x86_64 GNU/Linux
   * LXC version: lxc-3.0.3_4
   * LXD version: lxd-3.11_1
   * Storage backend in use: dir

# Issue description

Trying to shutdown my container using `lxc stop <container>` hangs. 
I can however stop the container either by:
- manually using `lxc exec <container> bash` and then running `shutdown -P now`
- or by executing `lxc exec test -- poweroff`.

Void Linux uses `runit` as init  system (PID 1).

# Steps to reproduce

- Create a Void-Linux container & start it (`lxc create void test`)
- Try to stop container using `lxc stop test`

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`) -- nothing!
 - [x] Container log (`lxc info NAME --show-log`)
```
Name: test
Location: none
Remote: unix://
Architecture: x86_64
Created: 2019/03/22 18:31 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 19198
Ips:
  eth0:	inet	10.190.191.235	vethDY0HSJ
  eth0:	inet6	fd42:1ea:1d1a:4709:9997:f2bc:4dbb:9b62	vethDY0HSJ
  eth0:	inet6	fe80::216:3eff:fe0b:3a7c	vethDY0HSJ
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 22
  CPU usage:
    CPU usage (in seconds): 0
  Memory usage:
    Memory (current): 8.93MB
    Memory (peak): 9.87MB
  Network usage:
    eth0:
      Bytes received: 10.39kB
      Bytes sent: 2.98kB
      Packets received: 65
      Packets sent: 27
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0

Log:

lxc test 20190322192019.182 WARN     conf - conf.c:lxc_setup_devpts:1616 - Invalid argument - Failed to unmount old devpts instance
```
 - [x] Container configuration (`lxc config show NAME --expanded`)
```
architecture: x86_64
config:
  volatile.base_image: 255fe67d74307802e5a2ac18ff496bd29714a7883847ce542175581421278dd5
  volatile.eth0.hwaddr: 00:16:3e:0b:3a:7c
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log) -- nothing!
 - [x] Output of the client with --debug
```
t=2019-03-22T20:23:06+0100 lvl=dbug msg="Connecting to a local LXD over a Unix socket" 
t=2019-03-22T20:23:06+0100 lvl=dbug msg="Sending request to LXD" etag= method=GET url=http://unix.socket/1.0
t=2019-03-22T20:23:06+0100 lvl=dbug msg="Got response struct from LXD" 
t=2019-03-22T20:23:06+0100 lvl=dbug msg="\n\t{\n\t\t\"config\": {\n\t\t\t\"images.auto_update_interval\": \"0\"\n\t\t},\n\t\t\"api_extensions\": [\n\t\t\t\"storage_zfs_remove_snapshots\",\n\t\t\t\"container_host_shutdown_timeout\",\n\t\t\t\"container_stop_priority\",\n\t\t\t\"container_syscall_filtering\",\n\t\t\t\"auth_pki\",\n\t\t\t\"container_last_used_at\",\n\t\t\t\"etag\",\n\t\t\t\"patch\",\n\t\t\t\"usb_devices\",\n\t\t\t\"https_allowed_credentials\",\n\t\t\t\"image_compression_algorithm\",\n\t\t\t\"directory_manipulation\",\n\t\t\t\"container_cpu_time\",\n\t\t\t\"storage_zfs_use_refquota\",\n\t\t\t\"storage_lvm_mount_options\",\n\t\t\t\"network\",\n\t\t\t\"profile_usedby\",\n\t\t\t\"container_push\",\n\t\t\t\"container_exec_recording\",\n\t\t\t\"certificate_update\",\n\t\t\t\"container_exec_signal_handling\",\n\t\t\t\"gpu_devices\",\n\t\t\t\"container_image_properties\",\n\t\t\t\"migration_progress\",\n\t\t\t\"id_map\",\n\t\t\t\"network_firewall_filtering\",\n\t\t\t\"network_routes\",\n\t\t\t\"storage\",\n\t\t\t\"file_delete\",\n\t\t\t\"file_append\",\n\t\t\t\"network_dhcp_expiry\",\n\t\t\t\"storage_lvm_vg_rename\",\n\t\t\t\"storage_lvm_thinpool_rename\",\n\t\t\t\"network_vlan\",\n\t\t\t\"image_create_aliases\",\n\t\t\t\"container_stateless_copy\",\n\t\t\t\"container_only_migration\",\n\t\t\t\"storage_zfs_clone_copy\",\n\t\t\t\"unix_device_rename\",\n\t\t\t\"storage_lvm_use_thinpool\",\n\t\t\t\"storage_rsync_bwlimit\",\n\t\t\t\"network_vxlan_interface\",\n\t\t\t\"storage_btrfs_mount_options\",\n\t\t\t\"entity_description\",\n\t\t\t\"image_force_refresh\",\n\t\t\t\"storage_lvm_lv_resizing\",\n\t\t\t\"id_map_base\",\n\t\t\t\"file_symlinks\",\n\t\t\t\"container_push_target\",\n\t\t\t\"network_vlan_physical\",\n\t\t\t\"storage_images_delete\",\n\t\t\t\"container_edit_metadata\",\n\t\t\t\"container_snapshot_stateful_migration\",\n\t\t\t\"storage_driver_ceph\",\n\t\t\t\"storage_ceph_user_name\",\n\t\t\t\"resource_limits\",\n\t\t\t\"storage_volatile_initial_source\",\n\t\t\t\"storage_ceph_force_osd_reuse\",\n\t\t\t\"storage_block_filesystem_btrfs\",\n\t\t\t\"resources\",\n\t\t\t\"kernel_limits\",\n\t\t\t\"storage_api_volume_rename\",\n\t\t\t\"macaroon_authentication\",\n\t\t\t\"network_sriov\",\n\t\t\t\"console\",\n\t\t\t\"restrict_devlxd\",\n\t\t\t\"migration_pre_copy\",\n\t\t\t\"infiniband\",\n\t\t\t\"maas_network\",\n\t\t\t\"devlxd_events\",\n\t\t\t\"proxy\",\n\t\t\t\"network_dhcp_gateway\",\n\t\t\t\"file_get_symlink\",\n\t\t\t\"network_leases\",\n\t\t\t\"unix_device_hotplug\",\n\t\t\t\"storage_api_local_volume_handling\",\n\t\t\t\"operation_description\",\n\t\t\t\"clustering\",\n\t\t\t\"event_lifecycle\",\n\t\t\t\"storage_api_remote_volume_handling\",\n\t\t\t\"nvidia_runtime\",\n\t\t\t\"container_mount_propagation\",\n\t\t\t\"container_backup\",\n\t\t\t\"devlxd_images\",\n\t\t\t\"container_local_cross_pool_handling\",\n\t\t\t\"proxy_unix\",\n\t\t\t\"proxy_udp\",\n\t\t\t\"clustering_join\",\n\t\t\t\"proxy_tcp_udp_multi_port_handling\",\n\t\t\t\"network_state\",\n\t\t\t\"proxy_unix_dac_properties\",\n\t\t\t\"container_protection_delete\",\n\t\t\t\"unix_priv_drop\",\n\t\t\t\"pprof_http\",\n\t\t\t\"proxy_haproxy_protocol\",\n\t\t\t\"network_hwaddr\",\n\t\t\t\"proxy_nat\",\n\t\t\t\"network_nat_order\",\n\t\t\t\"container_full\",\n\t\t\t\"candid_authentication\",\n\t\t\t\"backup_compression\",\n\t\t\t\"candid_config\",\n\t\t\t\"nvidia_runtime_config\",\n\t\t\t\"storage_api_volume_snapshots\",\n\t\t\t\"storage_unmapped\",\n\t\t\t\"projects\",\n\t\t\t\"candid_config_key\",\n\t\t\t\"network_vxlan_ttl\",\n\t\t\t\"container_incremental_copy\",\n\t\t\t\"usb_optional_vendorid\",\n\t\t\t\"snapshot_scheduling\",\n\t\t\t\"container_copy_project\",\n\t\t\t\"clustering_server_address\",\n\t\t\t\"clustering_image_replication\",\n\t\t\t\"container_protection_shift\",\n\t\t\t\"snapshot_expiry\",\n\t\t\t\"container_backup_override_pool\",\n\t\t\t\"snapshot_expiry_creation\"\n\t\t],\n\t\t\"api_status\": \"stable\",\n\t\t\"api_version\": \"1.0\",\n\t\t\"auth\": \"trusted\",\n\t\t\"public\": false,\n\t\t\"auth_methods\": [\n\t\t\t\"tls\"\n\t\t],\n\t\t\"environment\": {\n\t\t\t\"addresses\": [],\n\t\t\t\"architectures\": [\n\t\t\t\t\"x86_64\",\n\t\t\t\t\"i686\"\n\t\t\t],\n\t\t\t\"certificate\": \"-----BEGIN CERTIFICATE-----\\nMIICITCCAaegAwIBAgIQKmiVis4bMCFZrnuJ4+HeTjAKBggqhkjOPQQDAzA2MRww\\nGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRYwFAYDVQQDDA1yb290QHZvaWQt\\nbGFwMB4XDTE5MDMyMjA4NDUxOVoXDTI5MDMxOTA4NDUxOVowNjEcMBoGA1UEChMT\\nbGludXhjb250YWluZXJzLm9yZzEWMBQGA1UEAwwNcm9vdEB2b2lkLWxhcDB2MBAG\\nByqGSM49AgEGBSuBBAAiA2IABIfI/kGxiaueDaYgc7a1AoT/BW8t6uaxLn2ZTVUZ\\nG74SUCjTKYSmkpYtlO4vby+HYLVsAHH4jqOgkTKg+I/A0OzxBHfx4dnKtOezdS+F\\ndB4Loxu0nxxhOJ/KN6bfTqthfqN6MHgwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQM\\nMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwQwYDVR0RBDwwOoIIdm9pZC1sYXCH\\nBMCoAmiHECADAM0HAesEQA/PPNoSWKiHBAoiPgGHEP1C0vPYiR6eAAAAAAAAAAEw\\nCgYIKoZIzj0EAwMDaAAwZQIwOfRXn4o9TyBMw0kPmAAoWt6yEzsv8rhWrXM17u+t\\nG3mPVhA1xbPbkf8NYv4WYFMAAjEAwxg07u4x1NM8r8IVwlpGwO7VdQMXpypyu8Id\\n+tmbuO9tSxrT6ZL4M6Kb3sEXbfM4\\n-----END CERTIFICATE-----\\n\",\n\t\t\t\"certificate_fingerprint\": \"426d935737c582e1df79ad9493048b3fd86160f836ce443ce33b14d0a43255b9\",\n\t\t\t\"driver\": \"lxc\",\n\t\t\t\"driver_version\": \"3.0.3\",\n\t\t\t\"kernel\": \"Linux\",\n\t\t\t\"kernel_architecture\": \"x86_64\",\n\t\t\t\"kernel_version\": \"4.19.30_1\",\n\t\t\t\"server\": \"lxd\",\n\t\t\t\"server_pid\": 17482,\n\t\t\t\"server_version\": \"3.11\",\n\t\t\t\"storage\": \"dir\",\n\t\t\t\"storage_version\": \"1\",\n\t\t\t\"server_clustered\": false,\n\t\t\t\"server_name\": \"void-lap\",\n\t\t\t\"project\": \"default\"\n\t\t}\n\t}" 
t=2019-03-22T20:23:06+0100 lvl=dbug msg="Connected to the websocket" 
t=2019-03-22T20:23:06+0100 lvl=dbug msg="Sending request to LXD" etag= method=PUT url=http://unix.socket/1.0/containers/test/state
t=2019-03-22T20:23:06+0100 lvl=dbug msg="\n\t{\n\t\t\"action\": \"stop\",\n\t\t\"timeout\": -1,\n\t\t\"force\": false,\n\t\t\"stateful\": false\n\t}" 
t=2019-03-22T20:23:06+0100 lvl=dbug msg="Got operation from LXD" 
t=2019-03-22T20:23:06+0100 lvl=dbug msg="\n\t{\n\t\t\"id\": \"a3e14cff-acc5-4574-a138-b19a7376f170\",\n\t\t\"class\": \"task\",\n\t\t\"description\": \"Stopping container\",\n\t\t\"created_at\": \"2019-03-22T20:23:06.816134463+01:00\",\n\t\t\"updated_at\": \"2019-03-22T20:23:06.816134463+01:00\",\n\t\t\"status\": \"Running\",\n\t\t\"status_code\": 103,\n\t\t\"resources\": {\n\t\t\t\"containers\": [\n\t\t\t\t\"/1.0/containers/test\"\n\t\t\t]\n\t\t},\n\t\t\"metadata\": null,\n\t\t\"may_cancel\": false,\n\t\t\"err\": \"\"\n\t}" 
t=2019-03-22T20:23:06+0100 lvl=dbug msg="Sending request to LXD" etag= method=GET url=http://unix.socket/1.0/operations/a3e14cff-acc5-4574-a138-b19a7376f170
t=2019-03-22T20:23:06+0100 lvl=dbug msg="Got response struct from LXD" 
t=2019-03-22T20:23:06+0100 lvl=dbug msg="\n\t{\n\t\t\"id\": \"a3e14cff-acc5-4574-a138-b19a7376f170\",\n\t\t\"class\": \"task\",\n\t\t\"description\": \"Stopping container\",\n\t\t\"created_at\": \"2019-03-22T20:23:06.816134463+01:00\",\n\t\t\"updated_at\": \"2019-03-22T20:23:06.816134463+01:00\",\n\t\t\"status\": \"Running\",\n\t\t\"status_code\": 103,\n\t\t\"resources\": {\n\t\t\t\"containers\": [\n\t\t\t\t\"/1.0/containers/test\"\n\t\t\t]\n\t\t},\n\t\t\"metadata\": null,\n\t\t\"may_cancel\": false,\n\t\t\"err\": \"\"\n\t}" 

```
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

```
metadata:
  context: {}
  level: dbug
  message: 'New event listener: adfb01a5-1130-49d5-9081-f78267a21a4c'
timestamp: "2019-03-22T20:24:54.069162117+01:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-03-22T20:24:58.369332928+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'New event listener: 00ff7695-4e39-4f49-ba4e-eb75c8fbcf89'
timestamp: "2019-03-22T20:24:58.376457112+01:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/events?project=
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-03-22T20:24:58.376322365+01:00"
type: logging


metadata:
  context:
    ip: '@'
    method: PUT
    url: /1.0/containers/test/state
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-03-22T20:24:58.379413988+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Started task operation: 1535cb52-2526-4505-a2a1-fef26376fb2c'
timestamp: "2019-03-22T20:24:58.410885468+01:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'New task operation: 1535cb52-2526-4505-a2a1-fef26376fb2c'
timestamp: "2019-03-22T20:24:58.410757823+01:00"
type: logging


metadata:
  class: task
  created_at: "2019-03-22T20:24:58.384408005+01:00"
  description: Stopping container
  err: ""
  id: 1535cb52-2526-4505-a2a1-fef26376fb2c
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/test
  status: Pending
  status_code: 105
  updated_at: "2019-03-22T20:24:58.384408005+01:00"
timestamp: "2019-03-22T20:24:58.410838792+01:00"
type: operation


metadata:
  class: task
  created_at: "2019-03-22T20:24:58.384408005+01:00"
  description: Stopping container
  err: ""
  id: 1535cb52-2526-4505-a2a1-fef26376fb2c
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/test
  status: Running
  status_code: 103
  updated_at: "2019-03-22T20:24:58.384408005+01:00"
timestamp: "2019-03-22T20:24:58.410940561+01:00"
type: operation


metadata:
  context:
    action: shutdown
    created: 2019-03-22 19:31:04.120142654 +0100 CET
    ephemeral: "false"
    name: test
    project: default
    timeout: -1s
    used: 2019-03-22 20:20:19.047253331 +0100 CET
  level: info
  message: Shutting down container
timestamp: "2019-03-22T20:24:58.413030774+01:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/operations/1535cb52-2526-4505-a2a1-fef26376fb2c
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-03-22T20:24:58.413409138+01:00"
type: logging



```
