### ISSUE TITLE
Idmaps of container and storage volume are not identical 

### ISSUE THREAD

**Issue by wiseflat** [lxc/lxd#5653]
# Required information

 * Distribution: ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.18.0-1013-azure
   * LXC version: 3.12
   * LXD version: 3.12
   * Storage backend in use: zfs

# Issue description

Since, lxd 3.12 I have a problem with shared volume.
When I want to add to c1 a volume of another lxc container I have this error now

```
lxc config device add c1 data-c2 disk path=/data/c2 pool=data-01 source=c2

Error: Add disk devices: Failed to setup device: Failed to initialize storage volume "c2" of type "custom" on storage pool "data-01": idmaps of container and storage volume are not identical
```

**Comment by stgraber** [comment]
Ok, I need more information to see what's going on here:
 - lxc config show --expanded FIRST-CONTAINER
 - lxc config show --expanded SECOND-CONTAINER
 - lxc storage volume show data-01 c2

**Comment by stgraber** [comment]
@wiseflat

**Comment by wiseflat** [comment]
Hello Stephane,

**c1 (this is a container used to share many zfs volume)**

```
architecture: x86_64
config:
  boot.autostart: "true"
  image.architecture: amd64
  image.description: Ubuntu Bionic 18.04 LTS amd64
  image.label: mycompany
  image.os: ubuntu
  image.release: bionic
  image.serial: "20181113"
  image.version: 18.04.1
  limits.cpu: "1"
  limits.cpu.allowance: 30%
  limits.memory: 1024MB
  limits.memory.enforce: hard
  limits.memory.swap: "false"
  limits.processes: "200"
  security.privileged: "false"
  volatile.base_image: d2478d446e13a7d991222d29fc9aee49bd6c84a20309bad377735ba76efcda0a
  volatile.eth0.hwaddr: 00:16:3e:d7:7c:a2
  volatile.eth1.hwaddr: 00:16:3e:2d:ef:75
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  data-c3:
    path: /data/c3
    pool: data-01
    source: c3
    type: disk
  data-c4:
    path: /data/c4
    pool: data-01
    source: c4
    type: disk
  data-c5:
    path: /data/c5
    pool: data-01
    source: c5
    type: disk
  eth0:
    mtu: "1400"
    name: eth0
    nictype: bridged
    parent: ovsbr0
    type: nic
  eth1:
    name: eth1
    nictype: bridged
    parent: ovsbr1
    type: nic
  root:
    path: /
    pool: lxc-01
    type: disk
ephemeral: false
profiles:
- infra-default
- size-s
stateful: false
description: ""
```

**c2** 

```
architecture: x86_64
config:
  boot.autostart: "true"
  image.architecture: amd64
  image.description: Ubuntu Bionic 18.04 LTS amd64
  image.label: mycompany
  image.os: ubuntu
  image.release: bionic
  image.serial: "20181113"
  image.version: 18.04.1
  limits.cpu: "2"
  limits.cpu.allowance: 30%
  limits.memory: 2048MB
  limits.memory.enforce: hard
  limits.memory.swap: "false"
  limits.processes: "300"
  security.privileged: "false"
  volatile.base_image: 502e4ade9e51c3b4ba373d9d9401a2be501e7648ebf508d662e7dc44c4169960
  volatile.eth0.hwaddr: 00:16:3e:ce:94:61
  volatile.eth1.hwaddr: 00:16:3e:93:38:15
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    mtu: "1400"
    name: eth0
    nictype: bridged
    parent: ovsbr0
    type: nic
  eth1:
    name: eth1
    nictype: bridged
    parent: ovsbr1
    type: nic
  root:
    path: /
    pool: lxc-01
    type: disk
ephemeral: false
profiles:
- hosting-default
- size-l
stateful: false
description: ""
```

**And the volumes**

```
(obviously, this is why I created this issue)
$ lxc storage volume show data-01 c2
Error: not found


$ lxc storage volume list data-01
+--------+--------------+-------------+---------+
|  TYPE  |     NAME     | DESCRIPTION | USED BY |
+--------+--------------+-------------+---------+
| custom | c3           |             | 2       |
+--------+--------------+-------------+---------+
| custom | c4           |             | 2       |
+--------+--------------+-------------+---------+
| custom | c5           |             | 2       |
+--------+--------------+-------------+---------+
```
