### ISSUE TITLE
Use migration sink/source mechanism for local copies/moves

### ISSUE THREAD

**Issue by cab404** [lxc/lxd#5776]
# Required information
 * Distribution: CentOS 7
 * lxc-info
``` 
...
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.0.11-1.el7.elrepo.x86_64
  lxc_features:
    mount_injection_file: "true"
    network_gateway_device_route: "false"
    network_ipvlan: "false"
    network_l2proxy: "false"
    seccomp_notify: "false"
  project: default
  server: lxd
  server_clustered: false
  server_name: killer-queen
  server_pid: 31367
  server_version: "3.13"
  storage: btrfs
  storage_version: "4.4"
...
```

I have two storage volumes, both are using btrfs. I moved an existing container from one to another using `lxc move container_name --target volume_2 container_2`, and after that docker stopped working on that machine.

After closer inspection I found that subvolumes were treated as regular directories during move.

## Steps to reproduce

Initialize two btrfs pools, e.g C1 and C2.

 1. `lxc launch -s C1 ubuntu box1`
 2. In box1: `btrfs su cr /testVol`. Make sure subvolume is created via `btrfs su sh /testVol`
 3. `lxc move box1 -s C2 box2`
 4. In box2: `btrfs su sh /testVol`. No subvolume will be found.
