### ISSUE TITLE
Ipvlan documentation

### ISSUE THREAD

**Issue by Matt-Yorkley** [lxc/lxd#5830]
Is there any plan to add ipvlan documentation? After a bit of experimenting I managed to get it to work by using the `edge` snap and adding this to my container's profile, but it's not documented anywhere.

```
config:
  user.network-config: 
    version: 1
    config:
      - type: nameserver
        address: 8.8.8.8
devices:
  eth0:
    nictype: ipvlan
    parent: wlan0
    ipv4.address: <static-ip-for-the-container>
    type: nic
```

Also @tomponline hinted in [discourse](https://discuss.linuxcontainers.org/t/lxd-3-13-has-been-released/4738/6) it's possible to get the host to communicate with the containers:

> ipvlan like macvlan stops containers and the host communicating. You can add an ipvlan interface to host though to overcome this I believe.

Do you have any examples of how to do that? I think this could solve a lot of networking needs.
