### ISSUE TITLE
cannot delete lxc storage volumes (storage volumes of type "container" cannot be deleted with the storage api)

### ISSUE THREAD

**Issue by blinkeye** [lxc/lxd#5857]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 18.04.2 LTS
 * The output of "lxc info":
```
...
  driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 4.18.0-21-generic
  lxc_features:
    mount_injection_file: "true"
    network_gateway_device_route: "false"
    network_ipvlan: "false"
    network_l2proxy: "false"
    network_phys_macvlan_mtu: "false"
    seccomp_notify: "false"
  project: default
  server: lxd
  server_clustered: false
  server_name: quadux
  server_pid: 28734
  server_version: "3.14"
  storage: btrfs
  storage_version: "4.4"
```

# Issue description

Delete storage pool

# Steps to reproduce

 1. lxc storage delete kubedee
```
Error: storage pool "kubedee" has volumes attached to it
```
 2. lxc storage volume ls kubedee
```
+-----------+------------------------------------------------------------------+-------------+---------+
|   TYPE    |                               NAME                               | DESCRIPTION | USED BY |
+-----------+------------------------------------------------------------------+-------------+---------+
| container | kubedee-my-kubernetes-v1-14-2-controller                         |             | 1       |
+-----------+------------------------------------------------------------------+-------------+---------+
| container | kubedee-my-kubernetes-v1-14-2-etcd                               |             | 1       |
+-----------+------------------------------------------------------------------+-------------+---------+
| container | kubedee-my-kubernetes-v1-14-2-worker-3zvv4b                      |             | 1       |
+-----------+------------------------------------------------------------------+-------------+---------+
| container | kubedee-my-kubernetes-v1-14-2-worker-cknwdt                      |             | 1       |
+-----------+------------------------------------------------------------------+-------------+---------+
| image     | 1ee31e5f12f654209c22b55e61b8c25f05f7e8a6435a2fa827243bebc4ce719d |             | 1       |
+-----------+------------------------------------------------------------------+-------------+---------+
```
 3. lxc storage volume delete kubedee container/kubedee-my-kubernetes-v1-14-2-controller
```
Error: storage volumes of type "container" cannot be deleted with the storage api
```

## Workaround
I then followed the instructions given by @stgraber  in #5319 and was able to delete the storage pool with:

 ```
$ lxd sql global "SELECT * FROM storage_volumes;"

+----+------------------------------------------------------------------+-----------------+---------+------+-------------+----------+------------+
| id |                               name                               | storage_pool_id | node_id | type | description | snapshot | project_id |
+----+------------------------------------------------------------------+-----------------+---------+------+-------------+----------+------------+
| 52 | kubedee-my-kubernetes-v1-14-2-etcd                               | 3               | 1       | 0    |             | 0        | 1          |
| 54 | kubedee-my-kubernetes-v1-14-2-controller                         | 3               | 1       | 0    |             | 0        | 1          |
| 55 | kubedee-my-kubernetes-v1-14-2-worker-cknwdt                      | 3               | 1       | 0    |             | 0        | 1          |
| 56 | kubedee-my-kubernetes-v1-14-2-worker-3zvv4b                      | 3               | 1       | 0    |             | 0        | 1          |
| 57 | 1ee31e5f12f654209c22b55e61b8c25f05f7e8a6435a2fa827243bebc4ce719d | 3               | 1       | 1    |             | 0        | 1          |
| 58 | kubespray                                                        | 1               | 1       | 0    |             | 0        | 1          |
| 59 | 1ee31e5f12f654209c22b55e61b8c25f05f7e8a6435a2fa827243bebc4ce719d | 1               | 1       | 1    |             | 0        | 1          |
+----+------------------------------------------------------------------+-----------------+---------+------+-------------+----------+------------+
```
followed by:
```
$ lxd sql global "DELETE FROM storage_volumes WHERE storage_pool_id=3"
Rows affected: 5

$ lxc storage volume ls kubedee
+------+------+-------------+---------+
| TYPE | NAME | DESCRIPTION | USED BY |
+------+------+-------------+---------+

$ lxc storage delete kubedee
Storage pool kubedee deleted
```
Is that the idea?
