### ISSUE TITLE
LXD appears to have a broken /etc/resolv.conf

### ISSUE THREAD

**Issue by lhorace** [lxc/lxd#5899]
<!--
Github issues are used for bug reports. For support questions, please use [our forum](https://discuss.linuxcontainers.org).

Please fill the template below as it will greatly help us track down your issue and reproduce it on our side.  
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.
-->

# Required information

 * Distribution: openSUSE 
 * Distribution version: Tumbleweed
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.1.10-1-default
   * LXC version: lxc-3.1.0-4.2.x86_64
   * LXD version: 3.14
   * Storage backend in use: btrfs

# Issue description

LXD incorrectly queries localhost for dns names.

```
location: none
metadata:
  context: {}
  level: dbug
  message: 'Failure for task operation: fbb64d76-ba10-4382-b4f3-3bbb9cf939a6: Get
    https://images.linuxcontainers.org:8443/1.0: lookup images.linuxcontainers.org
    on [::1]:53: read udp [::1]:40439->[::1]:53: read: connection refused'
timestamp: "2019-07-01T12:57:21.843719456-04:00"
type: logging
```
# Steps to reproduce

 1. lxc image copy images:centos/6/amd64 local: 

# Actual result

```                                                                                                                                                                                                           
Error: Failed remote image download: Get https://images.linuxcontainers.org/streams/v1/index.json: lookup images.linuxcontainers.org on [::1]:53: read udp [::1]:44916->[::1]:53: read: connection refused
```

# Expected result

Download image

# Notes:

I distro-hopped to openSUSE and did in-place move of LXD files. I'm not sure if that broken anything but further investigation. LXD snap has a broken resolv.conf

```
lrwxrwxrwx 1 root root  35 Jun 30 23:24 alternatives -> /snap/core/current/etc/alternatives
lrwxrwxrwx 1 root root  31 Jun 30 23:24 apparmor -> /snap/core/current/etc/apparmor
lrwxrwxrwx 1 root root  33 Jun 30 23:24 apparmor.d -> /snap/core/current/etc/apparmor.d
lrwxrwxrwx 1 root root  30 Jun 30 23:24 ceph -> /var/lib/snapd/hostfs/etc/ceph
lrwxrwxrwx 1 root root  31 Jun 30 23:24 group -> /var/lib/snapd/hostfs/etc/group
lrwxrwxrwx 1 root root  34 Jun 30 23:24 hostname -> /var/lib/snapd/hostfs/etc/hostname
lrwxrwxrwx 1 root root  31 Jun 30 23:24 hosts -> /var/lib/snapd/hostfs/etc/hosts
-rw-r--r-- 1 root root 14K Jun 30 23:24 ld.so.cache
lrwxrwxrwx 1 root root  35 Jun 30 23:24 localtime -> /var/lib/snapd/hostfs/etc/localtime
-rw-r--r-- 1 root root  87 Jun 30 23:24 logrotate.status
drwxr-xr-x 2 root root  60 Jun 30 23:24 lvm
lrwxrwxrwx 1 root root  12 Jun 30 23:24 mtab -> /proc/mounts
lrwxrwxrwx 1 root root  39 Jun 30 23:24 nsswitch.conf -> /var/lib/snapd/hostfs/etc/nsswitch.conf
lrwxrwxrwx 1 root root  36 Jun 30 23:24 os-release -> /var/lib/snapd/hostfs/etc/os-release
lrwxrwxrwx 1 root root  32 Jun 30 23:24 passwd -> /var/lib/snapd/hostfs/etc/passwd
-rw-r--r-- 1 root root   0 Jun 30 23:24 resolv.conf
lrwxrwxrwx 1 root root  26 Jun 30 23:24 ssl -> /snap/core/current/etc/ssl
lrwxrwxrwx 1 root root  26 Jun 30 23:24 vim -> /snap/core/current/etc/vim
```

```
# cat /proc/2141/root/etc/resolv.conf
#
```
