### ISSUE TITLE
Kubernetes can't start inside LXD on a BTRFS volume

### ISSUE THREAD

**Issue by divanikus** [lxc/lxd#6013]
# Required information

 * Distribution: Debian
 * Distribution version: 10.0 (Buster)
 * Kubernetes version: 1.15.1
 * Docker version: 18.09
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.19.0-5-amd64
   * LXC version: snap
   * Storage backend in use: BTRFS

# Issue description

I'm not sure if it is the right place to report the problem, but let's find out.
I'm trying to spin up a kubernetes cluster inside LXD managed containers. My LXD storage pool is the BTRFS one. Everything is going smooth, until I actually try to spin up the `kubeadm init`, which should bring up the `kubelet` and start infrastructure related pods. But the `kubelet` daemon simply dies and doesn't spin up anything.

The two major problems are:

```
Jul 25 21:48:23 onekube-ip-192-168-15-2.localdomain kubelet[673]: I0725 21:48:23.606870     673 server.go:144] Starting to listen on 0.0.0.0:10250
Jul 25 21:48:23 onekube-ip-192-168-15-2.localdomain kubelet[673]: F0725 21:48:23.607149     673 kubelet.go:1405] Failed to start OOM watcher open /dev/kmsg: no such file or directory
Jul 25 21:48:23 onekube-ip-192-168-15-2.localdomain systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
```
and
```

Jul 25 21:49:55 onekube-ip-192-168-15-2.localdomain kubelet[796]: W0725 21:49:55.139425     796 fs.go:544] stat failed on /dev/nvme0n1p5 with error: no such file or directory
Jul 25 21:49:55 onekube-ip-192-168-15-2.localdomain kubelet[796]: F0725 21:49:55.139431     796 kubelet.go:1370] Failed to start ContainerManager failed to get rootfs info: failed to get device for dir "/var/lib/kubelet": could not find device with major: 0, minor: 70 in cached partitions map
Jul 25 21:49:55 onekube-ip-192-168-15-2.localdomain systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
```

So, `kubelet` simply trying to access `/dev/kmsg` and `/dev/nvme0n1p5` which is the block device containing my BTRFS pool system. 

I'm using the following settings from that article: https://github.com/corneliusweig/kubernetes-lxd
```
config:
  linux.kernel_modules: ip_tables,ip6_tables,netlink_diag,nf_nat,overlay
  raw.lxc: "lxc.apparmor.profile=unconfined\nlxc.cap.drop= \nlxc.cgroup.devices.allow=a\nlxc.mount.auto=proc:rw
    sys:rw"
  security.privileged: "true"
  security.nesting: "true"
```

I can proceed further if I manually add those devices to `/dev` with mknod. And it would be kind of ok in the case of `/dev/kmsg`, but in case of BTRFS, different machine might have different block device name, major and minor numbers and so on, and I want to have an ability to automatically provision containers without bothering about hardware details. Also, I don't feel like exposing the whole block device is "secure" by any means.

Any suggestions?

**Comment by stgraber** [comment]
I actually had to deal with most of that today when running kubelet inside of LXD.

The /dev/kmsg you can workaround by adding a unix-char device to pass it in.
The filesystem issue I didn't get, presumably because I was using an ext4 custom storage volume for /var/lib/docker (or because I was using docker to run the containers).

Your configuration is terribly unsafe as you're turning off apparmor. This will cause the container runtime inside your LXD container to directly load apparmor profiles on the host, potentially conflicting with existing ones and causing a giant mess. In my case, I did not need to use any `raw.lxc` trickery and kept apparmor enabled.

However, when disabling apparmor, you do run into another problem with kubelet trying to modify system-wide parameters through /proc/sys. In your case, those succeeded and are now applied to your entire system (probably not ideal). In my case, I had to do some trickery to bind-mount files into those files it attempted to modify and pretend that the expected values were already set.

For anyone interested, this is my entire LXD config:
```
root@nuturo:~# lxc config show --expanded k8s-kubelet
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20190722.1)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20190722.1"
  image.version: "18.04"
  security.nesting: "true"
  security.privileged: "true"
  volatile.base_image: 368bb7174b679ece9bd0dfe2ab953c02c47ff4451736cb255655ba8348f17bc0
  volatile.eth0.host_name: vethUKNE15
  volatile.eth0.hwaddr: 00:16:3e:52:79:ae
  volatile.idmap.base: "0"
  volatile.idmap.current: '[]'
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  docker:
    path: /var/lib/docker
    pool: ext4
    source: k8s-kubelet
    type: disk
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  kmsg:
    path: /dev/kmsg
    type: unix-char
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

And the sysctl trickery looks like:
```
root@k8s-kubelet:~# cat /etc/rc.local 
#!/bin/sh
for file in /proc/sys/vm/overcommit_memory /proc/sys/kernel/panic /proc/sys/kernel/panic_on_oops; do
    BASENAME=$(basename ${file})
    cat ${file} > /tmp/${BASENAME}
    mount -o bind /tmp/${BASENAME} ${file}
done

echo 1 > /tmp/overcommit_memory
echo 10 > /tmp/panic
echo 1 > /tmp/panic_on_oops
```

Ultimately all of those are issues that need to be addressed inside kubelet.

It really shouldn't crash because it can't modify some kernel settings, it should just respect being told no by the kernel and move on.

Same goes for the disk usage details, if it can't track down the particular block device, just move on,  this information isn't needed for operation, just don't record it and that'll be fine.

Same goes for /dev/kmsg, kubelet probably uses it to detect situations like OOM, that seems quite useful but also shouldn't be a blocker. If it can't get that information, just assume you're not getting any OOM and move on.

I'd love to see someone pushing such fixes upstream. They seem reasonably straightforward, grep around for the error you're seeing and make the code a bit more robust by handling things like missing files and permission denied errors in there.


Closing as there's really nothing that LXD can do about those. Just allowing what kubelet wants would be a huge security bypass allowing for trivial exploitation of the host and/or data leakage, so we're not going to be recommending doing things like passing full block devices or allowing read/write access to the kernel log and sysctls :)
