### ISSUE TITLE
Unable to assing a WiFi interface to a container using profile, on Ubuntu 18.04

### ISSUE THREAD

**Issue by gabrik** [lxc/lxd#6015]
#5318 Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.2
 * The output of "lxc info" or if that fails:
```
$ lxc info
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.86.168:8443
  - 192.168.122.1:8443
  - 10.67.94.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICCDCCAY2gAwIBAgIRALLRklgzGYoAzSRffOFv9YcwCgYIKoZIzj0EAwMwOzEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEbMBkGA1UEAwwScm9vdEBhdG8t
    TlVDN2k3Qk5IMB4XDTE4MTEyMjE0MDkyNVoXDTI4MTExOTE0MDkyNVowOzEcMBoG
    A1UEChMTbGludXhjb250YWluZXJzLm9yZzEbMBkGA1UEAwwScm9vdEBhdG8tTlVD
    N2k3Qk5IMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEUapHAjCWOfzK5YnPq1O3l/Pi
    cXjYBDaPPVJlbpF8LKlKPn9Wkrf9KVVv6x2gbaczph3PQxkyZP8CwPSp806E1JFA
    Va+d+2gsEa9sk3FENkhFniG1W9WA7iBUD886C1Wuo1UwUzAOBgNVHQ8BAf8EBAMC
    BaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAeBgNVHREEFzAV
    gg1hdG8tTlVDN2k3Qk5IhwTAqFYsMAoGCCqGSM49BAMDA2kAMGYCMQCLHecfEiE2
    S+zEqTE11NAIRGuSTeg+E9Bbc7l0TkKyolfiet/kDJBjYAvac07rTJICMQDfNzai
    QsHwK2HEw6K9XI8v4RqpVua8faqUY+hNkthVv6e1r/3Mej7lMXzbg+fhwx4=
    -----END CERTIFICATE-----
  certificate_fingerprint: 30d3feda0c89966c47c4954a27c44843dd4a59818e63d3bfc642f9ad1895f2d1
  driver: lxc
  driver_version: 3.2.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    shiftfs: "false"
    uevent_injection: "false"
    unpriv_fscaps: "true"
  kernel_version: 4.15.0-54-generic
  lxc_features:
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    seccomp_notify: "true"
  project: default
  server: lxd
  server_clustered: false
  server_name: nuc
  server_pid: 30910
  server_version: "3.15"
  storage: zfs
  storage_version: 0.7.5-1ubuntu16.4
```

   * Kernel version: 4.15.0-54-generic
   * LXC version: 3.15
   * LXD version: 3.15
   * Storage backend in use: zfs

# Issue description

I want to attach a WiFi interface to a container using a profile, but the container will not start because the interface cannot be moved to the container namespace, same scenario **works** in Ubuntu 16.

Interface is an Intel one, but I have the same issue also with a Realtek one, both were working on Ubuntu 16

# Steps to reproduce

 1. lxc profile copy default wifi
 2. lxc profile device add wifi wlp58s0 nic nictype=physical parent=wlp58s0 name=wlp58s0
 3. lxc launch images:alpine/edge -p wifi test

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`)
 - [x] Container configuration (`lxc config show NAME --expanded`)
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [x] Output of the client with --debug
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

 ## container log:
```
Name: test
Location: none
Remote: unix://
Architecture: x86_64
Created: 2019/07/26 08:53 UTC
Status: Stopped
Type: persistent
Profiles: wifi

Log:

lxc test 20190726091012.299 ERROR    start - start.c:proc_pidfd_open:1644 - Function not implemented - Failed to send signal through pidfd
lxc test 20190726091012.137 ERROR    network - network.c:lxc_network_move_created_netdev_priv:3292 - Operation not permitted - Failed to move network device "wlp58s0" with ifindex 3 to network namespace 12960
lxc test 20190726091012.137 ERROR    start - start.c:lxc_spawn:1846 - Failed to create the network
lxc test 20190726091012.177 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:873 - Received container state "ABORTING" instead of "RUNNING"
lxc test 20190726091012.178 ERROR    start - start.c:__lxc_start:2036 - Failed to spawn container "test"
lxc 20190726091012.215 WARN     commands - commands.c:lxc_cmd_rsp_recv:135 - Connection reset by peer - Failed to receive response for command "get_state"
```

## container config

```
$ lxc config show test --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Alpine edge amd64 (20190725_13:00)
  image.os: Alpine
  image.release: edge
  image.serial: "20190725_13:00"
  volatile.base_image: 66fe65ebc6f3eee97515fb3e39e495f31628eb8a03088cf25ebb595c3a635148
  volatile.eth0.hwaddr: 00:16:3e:ca:1d:7a
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: STOPPED
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
  wlp58s0:
    name: wlp58s0
    nictype: physical
    parent: wlp58s0
    type: nic
ephemeral: false
profiles:
- wifi
stateful: false
description: ""
```

## daemon log

```
t=2019-07-26T11:10:11+0200 lvl=info msg="Starting container" action=start created=2019-07-26T10:53:23+0200 ephemeral=false name=test project=default stateful=false used=2019-07-26T10:57:12+0200
t=2019-07-26T11:10:12+0200 lvl=eror msg="Failed starting container" action=start created=2019-07-26T10:53:23+0200 ephemeral=false name=test project=default stateful=false used=2019-07-26T10:57:12+0200
t=2019-07-26T11:10:12+0200 lvl=info msg="Container initiated stop" action=stop created=2019-07-26T10:53:23+0200 ephemeral=false name=test project=default stateful=false used=2019-07-26T11:10:12+0200
```

## client debug output:
```
DBUG[07-26|11:13:14] Connecting to a local LXD over a Unix socket
DBUG[07-26|11:13:14] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
DBUG[07-26|11:13:14] Got response struct from LXD
DBUG[07-26|11:13:14]
	{
		"config": {
			"core.https_address": "[::]:8443",
			"core.trust_password": true
		},
		"api_extensions": [
			"storage_zfs_remove_snapshots",
			"container_host_shutdown_timeout",
			"container_stop_priority",
			"container_syscall_filtering",
			"auth_pki",
			"container_last_used_at",
			"etag",
			"patch",
			"usb_devices",
			"https_allowed_credentials",
			"image_compression_algorithm",
			"directory_manipulation",
			"container_cpu_time",
			"storage_zfs_use_refquota",
			"storage_lvm_mount_options",
			"network",
			"profile_usedby",
			"container_push",
			"container_exec_recording",
			"certificate_update",
			"container_exec_signal_handling",
			"gpu_devices",
			"container_image_properties",
			"migration_progress",
			"id_map",
			"network_firewall_filtering",
			"network_routes",
			"storage",
			"file_delete",
			"file_append",
			"network_dhcp_expiry",
			"storage_lvm_vg_rename",
			"storage_lvm_thinpool_rename",
			"network_vlan",
			"image_create_aliases",
			"container_stateless_copy",
			"container_only_migration",
			"storage_zfs_clone_copy",
			"unix_device_rename",
			"storage_lvm_use_thinpool",
			"storage_rsync_bwlimit",
			"network_vxlan_interface",
			"storage_btrfs_mount_options",
			"entity_description",
			"image_force_refresh",
			"storage_lvm_lv_resizing",
			"id_map_base",
			"file_symlinks",
			"container_push_target",
			"network_vlan_physical",
			"storage_images_delete",
			"container_edit_metadata",
			"container_snapshot_stateful_migration",
			"storage_driver_ceph",
			"storage_ceph_user_name",
			"resource_limits",
			"storage_volatile_initial_source",
			"storage_ceph_force_osd_reuse",
			"storage_block_filesystem_btrfs",
			"resources",
			"kernel_limits",
			"storage_api_volume_rename",
			"macaroon_authentication",
			"network_sriov",
			"console",
			"restrict_devlxd",
			"migration_pre_copy",
			"infiniband",
			"maas_network",
			"devlxd_events",
			"proxy",
			"network_dhcp_gateway",
			"file_get_symlink",
			"network_leases",
			"unix_device_hotplug",
			"storage_api_local_volume_handling",
			"operation_description",
			"clustering",
			"event_lifecycle",
			"storage_api_remote_volume_handling",
			"nvidia_runtime",
			"container_mount_propagation",
			"container_backup",
			"devlxd_images",
			"container_local_cross_pool_handling",
			"proxy_unix",
			"proxy_udp",
			"clustering_join",
			"proxy_tcp_udp_multi_port_handling",
			"network_state",
			"proxy_unix_dac_properties",
			"container_protection_delete",
			"unix_priv_drop",
			"pprof_http",
			"proxy_haproxy_protocol",
			"network_hwaddr",
			"proxy_nat",
			"network_nat_order",
			"container_full",
			"candid_authentication",
			"backup_compression",
			"candid_config",
			"nvidia_runtime_config",
			"storage_api_volume_snapshots",
			"storage_unmapped",
			"projects",
			"candid_config_key",
			"network_vxlan_ttl",
			"container_incremental_copy",
			"usb_optional_vendorid",
			"snapshot_scheduling",
			"container_copy_project",
			"clustering_server_address",
			"clustering_image_replication",
			"container_protection_shift",
			"snapshot_expiry",
			"container_backup_override_pool",
			"snapshot_expiry_creation",
			"network_leases_location",
			"resources_cpu_socket",
			"resources_gpu",
			"resources_numa",
			"kernel_features",
			"id_map_current",
			"event_location",
			"storage_api_remote_volume_snapshots",
			"network_nat_address",
			"container_nic_routes",
			"rbac",
			"cluster_internal_copy",
			"seccomp_notify",
			"lxc_features",
			"container_nic_ipvlan",
			"network_vlan_sriov",
			"storage_cephfs",
			"container_nic_ipfilter",
			"resources_v2",
			"container_exec_user_group_cwd"
		],
		"api_status": "stable",
		"api_version": "1.0",
		"auth": "trusted",
		"public": false,
		"auth_methods": [
			"tls"
		],
		"environment": {
			"addresses": [
				"192.168.86.168:8443",
				"192.168.122.1:8443",
				"10.67.94.1:8443"
			],
			"architectures": [
				"x86_64",
				"i686"
			],
			"certificate": "-----BEGIN CERTIFICATE-----\nMIICCDCCAY2gAwIBAgIRALLRklgzGYoAzSRffOFv9YcwCgYIKoZIzj0EAwMwOzEc\nMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEbMBkGA1UEAwwScm9vdEBhdG8t\nTlVDN2k3Qk5IMB4XDTE4MTEyMjE0MDkyNVoXDTI4MTExOTE0MDkyNVowOzEcMBoG\nA1UEChMTbGludXhjb250YWluZXJzLm9yZzEbMBkGA1UEAwwScm9vdEBhdG8tTlVD\nN2k3Qk5IMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEUapHAjCWOfzK5YnPq1O3l/Pi\ncXjYBDaPPVJlbpF8LKlKPn9Wkrf9KVVv6x2gbaczph3PQxkyZP8CwPSp806E1JFA\nVa+d+2gsEa9sk3FENkhFniG1W9WA7iBUD886C1Wuo1UwUzAOBgNVHQ8BAf8EBAMC\nBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAeBgNVHREEFzAV\ngg1hdG8tTlVDN2k3Qk5IhwTAqFYsMAoGCCqGSM49BAMDA2kAMGYCMQCLHecfEiE2\nS+zEqTE11NAIRGuSTeg+E9Bbc7l0TkKyolfiet/kDJBjYAvac07rTJICMQDfNzai\nQsHwK2HEw6K9XI8v4RqpVua8faqUY+hNkthVv6e1r/3Mej7lMXzbg+fhwx4=\n-----END CERTIFICATE-----\n",
			"certificate_fingerprint": "30d3feda0c89966c47c4954a27c44843dd4a59818e63d3bfc642f9ad1895f2d1",
			"driver": "lxc",
			"driver_version": "3.2.1",
			"kernel": "Linux",
			"kernel_architecture": "x86_64",
			"kernel_features": {
				"netnsid_getifaddrs": "false",
				"seccomp_listener": "false",
				"shiftfs": "false",
				"uevent_injection": "false",
				"unpriv_fscaps": "true"
			},
			"kernel_version": "4.15.0-54-generic",
			"lxc_features": {
				"mount_injection_file": "true",
				"network_gateway_device_route": "true",
				"network_ipvlan": "true",
				"network_l2proxy": "true",
				"network_phys_macvlan_mtu": "true",
				"seccomp_notify": "true"
			},
			"project": "default",
			"server": "lxd",
			"server_clustered": false,
			"server_name": "nuc",
			"server_pid": 30910,
			"server_version": "3.15",
			"storage": "zfs",
			"storage_version": "0.7.5-1ubuntu16.4"
		}
	}
DBUG[07-26|11:13:14] Sending request to LXD                   method=GET url=http://unix.socket/1.0/containers/test etag=
DBUG[07-26|11:13:14] Got response struct from LXD
DBUG[07-26|11:13:14]
	{
		"architecture": "x86_64",
		"config": {
			"image.architecture": "amd64",
			"image.description": "Alpine edge amd64 (20190725_13:00)",
			"image.os": "Alpine",
			"image.release": "edge",
			"image.serial": "20190725_13:00",
			"volatile.base_image": "66fe65ebc6f3eee97515fb3e39e495f31628eb8a03088cf25ebb595c3a635148",
			"volatile.eth0.hwaddr": "00:16:3e:ca:1d:7a",
			"volatile.idmap.base": "0",
			"volatile.idmap.current": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}]",
			"volatile.idmap.next": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}]",
			"volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}]",
			"volatile.last_state.power": "STOPPED"
		},
		"devices": {},
		"ephemeral": false,
		"profiles": [
			"wifi"
		],
		"stateful": false,
		"description": "",
		"created_at": "2019-07-26T10:53:23.976687946+02:00",
		"expanded_config": {
			"image.architecture": "amd64",
			"image.description": "Alpine edge amd64 (20190725_13:00)",
			"image.os": "Alpine",
			"image.release": "edge",
			"image.serial": "20190725_13:00",
			"volatile.base_image": "66fe65ebc6f3eee97515fb3e39e495f31628eb8a03088cf25ebb595c3a635148",
			"volatile.eth0.hwaddr": "00:16:3e:ca:1d:7a",
			"volatile.idmap.base": "0",
			"volatile.idmap.current": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}]",
			"volatile.idmap.next": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}]",
			"volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":1000000,\"Nsid\":0,\"Maprange\":1000000000}]",
			"volatile.last_state.power": "STOPPED"
		},
		"expanded_devices": {
			"eth0": {
				"name": "eth0",
				"nictype": "bridged",
				"parent": "lxdbr0",
				"type": "nic"
			},
			"root": {
				"path": "/",
				"pool": "default",
				"type": "disk"
			},
			"wlp58s0": {
				"name": "wlp58s0",
				"nictype": "physical",
				"parent": "wlp58s0",
				"type": "nic"
			}
		},
		"name": "test",
		"status": "Stopped",
		"status_code": 102,
		"last_used_at": "2019-07-26T11:10:12.023464264+02:00",
		"location": "none"
	}
DBUG[07-26|11:13:14] Connected to the websocket
DBUG[07-26|11:13:14] Sending request to LXD                   method=PUT url=http://unix.socket/1.0/containers/test/state etag=
DBUG[07-26|11:13:14]
	{
		"action": "start",
		"timeout": 0,
		"force": false,
		"stateful": false
	}
DBUG[07-26|11:13:14] Got operation from LXD
DBUG[07-26|11:13:14]
	{
		"id": "4d0b3ca2-5224-4b1f-97f0-af17b7e766ba",
		"class": "task",
		"description": "Starting container",
		"created_at": "2019-07-26T11:13:14.22693896+02:00",
		"updated_at": "2019-07-26T11:13:14.22693896+02:00",
		"status": "Running",
		"status_code": 103,
		"resources": {
			"containers": [
				"/1.0/containers/test"
			]
		},
		"metadata": null,
		"may_cancel": false,
		"err": "",
		"location": "none"
	}
DBUG[07-26|11:13:14] Sending request to LXD                   method=GET url=http://unix.socket/1.0/operations/4d0b3ca2-5224-4b1f-97f0-af17b7e766ba etag=
DBUG[07-26|11:13:14] Got response struct from LXD
DBUG[07-26|11:13:14]
	{
		"id": "4d0b3ca2-5224-4b1f-97f0-af17b7e766ba",
		"class": "task",
		"description": "Starting container",
		"created_at": "2019-07-26T11:13:14.22693896+02:00",
		"updated_at": "2019-07-26T11:13:14.22693896+02:00",
		"status": "Running",
		"status_code": 103,
		"resources": {
			"containers": [
				"/1.0/containers/test"
			]
		},
		"metadata": null,
		"may_cancel": false,
		"err": "",
		"location": "none"
	}
Error: Failed to run: /snap/lxd/current/bin/lxd forkstart test /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/test/lxc.conf:
Try `lxc info --show-log test` for more info
```
## lxc monitor 

```
location: none
metadata:
  context: {}
  level: dbug
  message: 'New event listener: 2466e0b3-4db6-40c2-9ead-83466792a06e'
timestamp: "2019-07-26T11:14:47.069816612+02:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-07-26T11:14:47.921646058+02:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/test
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-07-26T11:14:47.92421618+02:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/events
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-07-26T11:14:47.926379841+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'New event listener: 1aabbb7d-ba8a-4d19-b909-55944be6923b'
timestamp: "2019-07-26T11:14:47.926537166+02:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: PUT
    url: /1.0/containers/test/state
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-07-26T11:14:47.927103924+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'New task operation: 0b271eb5-1538-407e-aab2-b0f56769e12b'
timestamp: "2019-07-26T11:14:47.931594969+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'Started task operation: 0b271eb5-1538-407e-aab2-b0f56769e12b'
timestamp: "2019-07-26T11:14:47.931755254+02:00"
type: logging


location: none
metadata:
  class: task
  created_at: "2019-07-26T11:14:47.928075+02:00"
  description: Starting container
  err: ""
  id: 0b271eb5-1538-407e-aab2-b0f56769e12b
  location: none
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/test
  status: Pending
  status_code: 105
  updated_at: "2019-07-26T11:14:47.928075+02:00"
timestamp: "2019-07-26T11:14:47.931747159+02:00"
type: operation


location: none
metadata:
  class: task
  created_at: "2019-07-26T11:14:47.928075+02:00"
  description: Starting container
  err: ""
  id: 0b271eb5-1538-407e-aab2-b0f56769e12b
  location: none
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/test
  status: Running
  status_code: 103
  updated_at: "2019-07-26T11:14:47.928075+02:00"
timestamp: "2019-07-26T11:14:47.932038394+02:00"
type: operation


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/operations/0b271eb5-1538-407e-aab2-b0f56769e12b
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-07-26T11:14:47.933182281+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: Mounting ZFS storage volume for container "test" on storage pool "default"
timestamp: "2019-07-26T11:14:47.937874535+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: Mounted ZFS storage volume for container "test" on storage pool "default"
timestamp: "2019-07-26T11:14:47.939514562+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: Mounting ZFS storage volume for container "test" on storage pool "default"
timestamp: "2019-07-26T11:14:47.942419994+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: Mounted ZFS storage volume for container "test" on storage pool "default"
timestamp: "2019-07-26T11:14:47.942748978+02:00"
type: logging


location: none
metadata:
  context:
    action: start
    created: 2019-07-26 10:53:23.976687946 +0200 CEST
    ephemeral: "false"
    name: test
    project: default
    stateful: "false"
    used: 2019-07-26 11:14:29.814917642 +0200 CEST
  level: info
  message: Starting container
timestamp: "2019-07-26T11:14:47.942798358+02:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /internal/containers/494/onstart
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-07-26T11:14:47.969193987+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: Mounting ZFS storage volume for container "test" on storage pool "default"
timestamp: "2019-07-26T11:14:47.971092958+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: Mounted ZFS storage volume for container "test" on storage pool "default"
timestamp: "2019-07-26T11:14:47.971388515+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'Scheduler: container test started: re-balancing'
timestamp: "2019-07-26T11:14:47.975235519+02:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-07-26T11:14:47.981193489+02:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers?recursion=2
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-07-26T11:14:47.990727414+02:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /internal/containers/494/onnetwork-up?device=eth0&host_name=veth0XPVQD
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-07-26T11:14:48.11465378+02:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /internal/containers/494/onstopns?target=stop&netns=/proc/25219/fd/11
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-07-26T11:14:48.218350825+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth3BE2KY has been added: updating network priorities'
timestamp: "2019-07-26T11:14:48.228674651+02:00"
type: logging


location: none
metadata:
  context:
    action: start
    created: 2019-07-26 10:53:23.976687946 +0200 CEST
    ephemeral: "false"
    name: test
    project: default
    stateful: "false"
    used: 2019-07-26 11:14:29.814917642 +0200 CEST
  level: eror
  message: Failed starting container
timestamp: "2019-07-26T11:14:48.228901448+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'Failure for task operation: 0b271eb5-1538-407e-aab2-b0f56769e12b: Failed
    to run: /snap/lxd/current/bin/lxd forkstart test /var/snap/lxd/common/lxd/containers
    /var/snap/lxd/common/lxd/logs/test/lxc.conf: '
timestamp: "2019-07-26T11:14:48.228921062+02:00"
type: logging


location: none
metadata:
  class: task
  created_at: "2019-07-26T11:14:47.928075+02:00"
  description: Starting container
  err: 'Failed to run: /snap/lxd/current/bin/lxd forkstart test /var/snap/lxd/common/lxd/containers
    /var/snap/lxd/common/lxd/logs/test/lxc.conf: '
  id: 0b271eb5-1538-407e-aab2-b0f56769e12b
  location: none
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/test
  status: Failure
  status_code: 400
  updated_at: "2019-07-26T11:14:47.928075+02:00"
timestamp: "2019-07-26T11:14:48.230189242+02:00"
type: operation


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /internal/containers/494/onstop?target=stop
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-07-26T11:14:48.78337561+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'Disconnected event listener: 1aabbb7d-ba8a-4d19-b909-55944be6923b'
timestamp: "2019-07-26T11:14:48.783575463+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: Unmounting ZFS storage volume for container "test" on storage pool "default"
timestamp: "2019-07-26T11:14:48.788512284+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: Unmounted ZFS storage volume for container "test" on storage pool "default"
timestamp: "2019-07-26T11:14:48.828792978+02:00"
type: logging


location: none
metadata:
  context:
    action: stop
    created: 2019-07-26 10:53:23.976687946 +0200 CEST
    ephemeral: "false"
    name: test
    project: default
    stateful: "false"
    used: 2019-07-26 11:14:47.975514857 +0200 CEST
  level: info
  message: Container initiated stop
timestamp: "2019-07-26T11:14:48.828965282+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'Scheduler: container test stopped: re-balancing'
timestamp: "2019-07-26T11:14:48.957177184+02:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-07-26T11:14:49.315989058+02:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers?recursion=2
    user: ""
  level: dbug
  message: Handling
timestamp: "2019-07-26T11:14:49.318363571+02:00"
type: logging
```
