### ISSUE TITLE
Error: Common start logic: Load go-lxc struct: Failed to load raw.lxc

### ISSUE THREAD

**Issue by helamonster** [lxc/lxd#6049]
Someone please help, I can't look at this any more... All I'm trying to do is start a container I had running perfectly fine under 16.04. Once I upgraded to 18.04, this started happening:

```
root@util ~ # lxc start boot
Error: Common start logic: Load go-lxc struct: Failed to load raw.lxc
```
Sure, it looks like #4501, but what does  "You should simply replace lxc.aa_profile with lxc.apparmor.profile" mean, if not the following:
```lxc config set boot  raw.lxc "lxc.apparmor.profile = unconfined"```

Current config:
```
root@util ~ # lxc info
environment:
  addresses:
  - 10.0.0.20:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
...
    -----END CERTIFICATE-----
  certificate_fingerprint: 74c09bb11b23481cb34dc5b762b694b4776f8551493f3cf4f8fc4b1027d5be64
  driver: lxc
  driver_version: 3.2.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    shiftfs: "false"
    uevent_injection: "false"
    unpriv_fscaps: "true"
  kernel_version: 4.15.0-15-generic
  lxc_features:
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    seccomp_notify: "true"
  project: default
  server: lxd
  server_clustered: false
  server_name: util.subdomain.redacted.com
  server_pid: 1848
  server_version: "3.15"
  storage: zfs
  storage_version: 0.8.1-3~18.04.york0
```

How I got there:
```
root@util ~ # lxc --version
3.0.3
root@util ~ # lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

root@util ~ # pgrep -fa lx

root@util ~ # tree /run/lxc*
/run/lxc
└── lock
    └── var
        └── lib
            └── lxd
                └── containers
/run/lxcfs
├── controllers
└── root

7 directories, 0 files

root@util ~ # systemctl  list-jobs
No jobs running.

root@util ~ # systemctl status lxd
● lxd.service - LXD - main daemon
   Loaded: loaded (/lib/systemd/system/lxd.service; indirect; vendor preset: enabled)
   Active: inactive (dead) (Result: signal) since Thu 2019-08-08 02:06:23 EDT; 2min 7s ago
     Docs: man:lxd(1)
  Process: 24463 ExecStartPost=/usr/bin/lxd waitready --timeout=600 (code=killed, signal=KILL)
  Process: 24462 ExecStart=/usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log (code=killed, signal=KILL)
  Process: 24546 ExecStartPre=/usr/lib/x86_64-linux-gnu/lxc/lxc-apparmor-load (code=killed, signal=KILL)
 Main PID: 24462 (code=killed, signal=KILL)

Aug 08 02:06:23 util.subdomain.redacted.com systemd[1]: Dependency failed for LXD - main daemon.
Aug 08 02:06:23 util.subdomain.redacted.com systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency'.
Aug 08 02:06:23 util.subdomain.redacted.com systemd[1]: Dependency failed for LXD - main daemon.
Aug 08 02:06:23 util.subdomain.redacted.com systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency'.
Aug 08 02:06:23 util.subdomain.redacted.com systemd[1]: Dependency failed for LXD - main daemon.
Aug 08 02:06:23 util.subdomain.redacted.com systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency'.
Aug 08 02:06:23 util.subdomain.redacted.com systemd[1]: Dependency failed for LXD - main daemon.
Aug 08 02:06:23 util.subdomain.redacted.com systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency'.
Aug 08 02:06:23 util.subdomain.redacted.com systemd[1]: Dependency failed for LXD - main daemon.
Aug 08 02:06:23 util.subdomain.redacted.com systemd[1]: lxd.service: Job lxd.service/start failed with result 'dependency'.




# This hangs
root@util ~ # systemctl start lxd




# In another terminal...
root@util ~ # systemctl list-jobs
   JOB UNIT        TYPE  STATE  
103281 lxd.service start running


root@util ~ # systemctl status lxd
● lxd.service - LXD - main daemon
   Loaded: loaded (/lib/systemd/system/lxd.service; indirect; vendor preset: enabled)
   Active: activating (start-post) (Result: exit-code) since Thu 2019-08-08 02:09:19 EDT; 6min ago
     Docs: man:lxd(1)
  Process: 27101 ExecStart=/usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log (code=exited, status=1/FAILURE)
  Process: 27082 ExecStartPre=/usr/lib/x86_64-linux-gnu/lxc/lxc-apparmor-load (code=exited, status=0/SUCCESS)
 Main PID: 27101 (code=exited, status=1/FAILURE); Control PID: 27102 (lxd)
    Tasks: 6
   CGroup: /system.slice/lxd.service
           └─27102 /usr/lib/lxd/lxd waitready --timeout=600

Aug 08 02:09:19 util.subdomain.redacted.com systemd[1]: Starting LXD - main daemon...
Aug 08 02:09:19 util.subdomain.redacted.com lxd[27101]: t=2019-08-08T02:09:19-0400 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored."
Aug 08 02:09:19 util.subdomain.redacted.com lxd[27101]: t=2019-08-08T02:09:19-0400 lvl=eror msg="Failed to start the daemon: Both legacy and new local database files exists"
Aug 08 02:09:19 util.subdomain.redacted.com lxd[27101]: Error: Both legacy and new local database files exists
Aug 08 02:09:19 util.subdomain.redacted.com systemd[1]: lxd.service: Main process exited, code=exited, status=1/FAILURE



root@util ~ # systemctl stop lxd
Warning: Stopping lxd.service, but it can still be activated by:
  lxd.socket

root@util ~ # systemctl stop lxd.socket

root@util ~ # systemctl stop lxcfs

root@util ~ # pgrep -fa  lx


root@util ~ # tree /run/lx*
/run/lxc
└── lock
    └── var
        └── lib
            └── lxd
                └── containers
/run/lxcfs
├── controllers
└── root

7 directories, 0 files


root@util ~ # systemctl --all | grep -i lx
  sys-devices-virtual-net-lxdbr0.device          loaded    active   plugged   /sys/devices/virtual/net/lxdbr0
  sys-subsystem-net-devices-lxdbr0.device        loaded    active   plugged   /sys/subsystem/net/devices/lxdbr0
  ifup@lxdbr0.service                            loaded    active   exited    ifup for lxdbr0
● lxc-net.service                                masked    inactive dead      lxc-net.service
● lxc.service                                    masked    inactive dead      lxc.service
  lxcfs.service                                  loaded    inactive dead      FUSE filesystem for LXC
  lxd-containers.service                         loaded    inactive dead      LXD - container startup/shutdown
● lxd.service                                    loaded    failed   failed    LXD - main daemon
  lxd.socket                                     loaded    inactive dead      LXD - unix socket


root@util ~ # systemctl start lxcfs
root@util ~ # 

root@util ~ # systemctl status lxcfs
● lxcfs.service - FUSE filesystem for LXC
   Loaded: loaded (/lib/systemd/system/lxcfs.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-08-08 02:53:55 EDT; 23s ago
     Docs: man:lxcfs(1)
  Process: 27858 ExecStopPost=/bin/fusermount -u /var/lib/lxcfs (code=exited, status=1/FAILURE)
 Main PID: 29174 (lxcfs)
    Tasks: 3 (limit: 4677)
   CGroup: /system.slice/lxcfs.service
           └─29174 /usr/bin/lxcfs /var/lib/lxcfs/

Aug 08 02:53:55 util.subdomain.redacted.com lxcfs[29174]:   3: fd:   9: perf_event
Aug 08 02:53:55 util.subdomain.redacted.com lxcfs[29174]:   4: fd:  10: pids
Aug 08 02:53:55 util.subdomain.redacted.com lxcfs[29174]:   5: fd:  11: rdma
Aug 08 02:53:55 util.subdomain.redacted.com lxcfs[29174]:   6: fd:  12: devices
Aug 08 02:53:55 util.subdomain.redacted.com lxcfs[29174]:   7: fd:  13: cpuset
Aug 08 02:53:55 util.subdomain.redacted.com lxcfs[29174]:   8: fd:  14: net_cls,net_prio
Aug 08 02:53:55 util.subdomain.redacted.com lxcfs[29174]:   9: fd:  15: blkio
Aug 08 02:53:55 util.subdomain.redacted.com lxcfs[29174]:  10: fd:  16: hugetlb
Aug 08 02:53:55 util.subdomain.redacted.com lxcfs[29174]:  11: fd:  17: name=systemd
Aug 08 02:53:55 util.subdomain.redacted.com lxcfs[29174]:  12: fd:  18: unified







root@util ~ # lxd --debug --group lxd
DBUG[08-08|02:55:01] Connecting to a local LXD over a Unix socket 
DBUG[08-08|02:55:01] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
INFO[08-08|02:55:01] LXD 3.0.3 is starting in normal mode     path=/var/lib/lxd
INFO[08-08|02:55:01] Kernel uid/gid map: 
INFO[08-08|02:55:01]  - u 0 0 4294967295 
INFO[08-08|02:55:01]  - g 0 0 4294967295 
INFO[08-08|02:55:01] Configured LXD uid/gid map: 
INFO[08-08|02:55:01]  - u 0 165536 65536 
INFO[08-08|02:55:01]  - g 0 165536 65536 
WARN[08-08|02:55:01] CGroup memory swap accounting is disabled, swap limits will be ignored. 
INFO[08-08|02:55:01] Kernel features: 
INFO[08-08|02:55:01]  - netnsid-based network retrieval: no 
INFO[08-08|02:55:01]  - unprivileged file capabilities: yes 
INFO[08-08|02:55:01] Initializing local database 
EROR[08-08|02:55:01] Failed to start the daemon: Both legacy and new local database files exists 
INFO[08-08|02:55:01] Starting shutdown sequence 
DBUG[08-08|02:55:01] Not unmounting temporary filesystems (containers are still running) 
INFO[08-08|02:55:01] Saving simplestreams cache 
INFO[08-08|02:55:01] Saved simplestreams cache 
Error: Both legacy and new local database files exists


root@util ~ # rm /var/lib/lxd/lxd.db
rm: remove regular empty file '/var/lib/lxd/lxd.db'? y
removed '/var/lib/lxd/lxd.db'


root@util ~ # systemctl restart lxd
root@util ~ # 


root@util ~ # systemctl status lxd
● lxd.service - LXD - main daemon
   Loaded: loaded (/lib/systemd/system/lxd.service; indirect; vendor preset: enabled)
   Active: active (running) since Thu 2019-08-08 02:59:35 EDT; 17s ago
     Docs: man:lxd(1)
  Process: 1380 ExecStartPost=/usr/bin/lxd waitready --timeout=600 (code=exited, status=0/SUCCESS)
  Process: 1365 ExecStartPre=/usr/lib/x86_64-linux-gnu/lxc/lxc-apparmor-load (code=exited, status=0/SUCCESS)
 Main PID: 1379 (lxd)
    Tasks: 14
   CGroup: /system.slice/lxd.service
           └─1379 /usr/lib/lxd/lxd --group lxd --logfile=/var/log/lxd/lxd.log

Aug 08 02:59:34 util.subdomain.redacted.com systemd[1]: Starting LXD - main daemon...
Aug 08 02:59:34 util.subdomain.redacted.com lxd[1379]: t=2019-08-08T02:59:34-0400 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored."
Aug 08 02:59:35 util.subdomain.redacted.com systemd[1]: Started LXD - main daemon.


root@util ~ # lxc list
+-------------+---------+------+------+------------+-----------+
|    NAME     |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+-------------+---------+------+------+------------+-----------+
| boot        | STOPPED |      |      | PERSISTENT | 1         |
+-------------+---------+------+------+------------+-----------+
| letsencrypt | STOPPED |      |      | PERSISTENT | 1         |
+-------------+---------+------+------+------------+-----------+
| mail        | STOPPED |      |      | PERSISTENT | 1         |
+-------------+---------+------+------+------------+-----------+
| openvpn     | STOPPED |      |      | PERSISTENT | 0         |
+-------------+---------+------+------+------------+-----------+



root@util ~ # lxc start boot
Error: Common start logic: Load go-lxc struct: Failed to load raw.lxc



root@util ~ # lxc config device show boot   
root:
  path: /
  type: disk

root@util ~ # lxc config show boot   
architecture: x86_64
config:

  raw.apparmor: mount fstype=nfs,mount fstype=nfs4,mount fstype=nfsd,mount fstype=rpc_pipefs,
  raw.lxc: lxc.aa_profile=unconfined
  security.privileged: "true"
  volatile.base_image: 577a2539b39e698a945e9024e7ff878890df07704993af4dec0dc9c1f117b960
  volatile.eth0.hwaddr: 00:16:3e:5f:78:4c
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
devices:
  root:
    path: /
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""


root@util ~ # lxc config set boot  raw.lxc "lxc.apparmor.profile = unconfined"
Error: Containers must have a root disk device (directly or inherited)

root@util ~ # lxc config set boot  raw.lxc ""
Error: Containers must have a root disk device (directly or inherited)

root@util ~ #  lxc config unset  boot  raw.lxc   
Error: Containers must have a root disk device (directly or inherited)

root@util ~ # lxc config device set boot root pool default
Error: Initialize LXC: Failed to load raw.lxc



root@util ~ # lxc config get  boot  raw.lxc 
lxc.aa_profile=unconfined


root@util ~ # lxc config show --expanded boot
architecture: x86_64
config:
  environment.http_proxy: ""
  'environment.http_proxy:': ""
  raw.apparmor: mount fstype=nfs,mount fstype=nfs4,mount fstype=nfsd,mount fstype=rpc_pipefs,
  raw.lxc: lxc.aa_profile=unconfined
  security.privileged: "true"
  user.network_mode: ""
  volatile.base_image: 577a2539b39e698a945e9024e7ff878890df07704993af4dec0dc9c1f117b960
  volatile.eth0.hwaddr: 00:16:3e:5f:78:4c
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""



root@util ~ # lxc storage list
+---------+-------------+--------+-----------+---------+
|  NAME   | DESCRIPTION | DRIVER |  SOURCE   | USED BY |
+---------+-------------+--------+-----------+---------+
| default |             | zfs    | rpool/lxd | 8       |
+---------+-------------+--------+-----------+---------+
root@util ~ # lxc storage show default
config:
  source: rpool/lxd
  zfs.pool_name: rpool/lxd
description: ""
name: default
driver: zfs
used_by:
- /1.0/containers/boot
- /1.0/containers/boot/snapshots/snap0
- /1.0/containers/letsencrypt
- /1.0/containers/letsencrypt/snapshots/snap0
- /1.0/containers/mail
- /1.0/containers/mail/snapshots/snap0
- /1.0/containers/openvpn
- /1.0/profiles/default
status: Created
locations:
- none

Error: not found

root@util ~ # lxc storage volume show default boot
Error: not found



root@util ~ # lxc storage volume list default
+----------------------+-------------------+-------------+---------+
|         TYPE         |       NAME        | DESCRIPTION | USED BY |
+----------------------+-------------------+-------------+---------+
| container            | boot              |             | 1       |
+----------------------+-------------------+-------------+---------+
| container            | letsencrypt       |             | 1       |
+----------------------+-------------------+-------------+---------+
| container            | mail              |             | 1       |
+----------------------+-------------------+-------------+---------+
| container            | openvpn           |             | 1       |
+----------------------+-------------------+-------------+---------+
| container (snapshot) | boot/snap0        |             | 1       |
+----------------------+-------------------+-------------+---------+
| container (snapshot) | letsencrypt/snap0 |             | 1       |
+----------------------+-------------------+-------------+---------+
| container (snapshot) | mail/snap0        |             | 1       |
+----------------------+-------------------+-------------+---------+


...
Ok, I decide to use snap package
...


root@util ~ # sudo apt update

root@util ~ # sudo apt install snapd

root@util ~ # snap install lxd

root@util ~ # snap list
Name  Version    Rev    Tracking  Publisher   Notes
core  16-2.39.3  7270   stable    canonical✓  core
lxd   3.15       11437  stable    canonical✓  -
root@util ~ # snap services
Service       Startup  Current   Notes
lxd.activate  enabled  inactive  -
lxd.daemon    enabled  inactive  socket-activated


root@util ~ # sudo snap services lxd 
Service       Startup  Current   Notes
lxd.activate  enabled  inactive  -
lxd.daemon    enabled  inactive  socket-activated

root@util ~ # snap start lxd
Started.

root@util ~ # sudo snap services lxd 
Service       Startup  Current   Notes
lxd.activate  enabled  inactive  -
lxd.daemon    enabled  active    socket-activated



root@util ~ # apt-get remove python3-lxc  lxd-tools lxd-client lxd  lxcfs liblxc1 liblxc-common

root@util ~ # apt-get remove   libxslt1.1 python-bs4 python-chardet python-html5lib python-webencodings



root@util ~ # lxd.migrate


root@util ~ #    sudo apt install -y lxd lxd-client lxd-tools criu



root@util ~ # lxc list
+-------------+---------+------+------+------------+-----------+
|    NAME     |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+-------------+---------+------+------+------------+-----------+
| boot        | STOPPED |      |      | PERSISTENT | 1         |
+-------------+---------+------+------+------------+-----------+
| letsencrypt | STOPPED |      |      | PERSISTENT | 1         |
+-------------+---------+------+------+------------+-----------+
| mail        | STOPPED |      |      | PERSISTENT | 1         |
+-------------+---------+------+------+------------+-----------+
| openvpn     | STOPPED |      |      | PERSISTENT | 0         |
+-------------+---------+------+------+------------+-----------+
root@util ~ # lxc start boot
Error: Common start logic: Load go-lxc struct: Failed to load raw.lxc

```

**I give up.**

**Comment by stgraber** [comment]
Can you try `lxc config edit boot` and then change both:
 - Add `pool` property to the `root` device
 - Change raw.lxc to be `lxc.apparmor.profile` instead of `lxc.aa_profile`

Assuming that those are the only two issues, the config should then validate.

**Comment by helamonster** [comment]
```root@util ~ # lxc config  edit boot```


```### This is a yaml representation of the configuration.
### Any line starting with a '# will be ignored.
###
### A sample configuration looks like:
### name: container1
### profiles:
### - default
### config:
###   volatile.eth0.hwaddr: 00:16:3e:e9:f8:7f
### devices:
###   homedir:
###     path: /extra
###     source: /home/user
###     type: disk
### ephemeral: false
###
### Note that the name is shown but cannot be changed

architecture: x86_64
config:
  raw.apparmor: mount fstype=nfs,mount fstype=nfs4,mount fstype=nfsd,mount fstype=rpc_pipefs,
  raw.lxc: lxc.apparmor.profile=unconfined
  security.privileged: "true"
  volatile.base_image: 577a2539b39e698a945e9024e7ff878890df07704993af4dec0dc9c1f117b960
  volatile.eth0.hwaddr: 00:16:3e:5f:78:4c
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
devices:
  root:
    path: /
    type: disk
    pool: 
ephemeral: false
profiles:
- default
stateful: false
description: ""
~                                                                                                                                                   
~                                                                                                                                                   
"/tmp/lxd_editor_359990159.yaml" 39L, 1013C
```


```
Config parsing error: Containers must have a root disk device (directly or inherited)
Press enter to start the editor again
```



```
### This is a yaml representation of the configuration.
### Any line starting with a '# will be ignored.
###
### A sample configuration looks like:
### name: container1
### profiles:
### - default
### config:
###   volatile.eth0.hwaddr: 00:16:3e:e9:f8:7f
### devices:
###   homedir:
###     path: /extra
###     source: /home/user
###     type: disk
### ephemeral: false
###
### Note that the name is shown but cannot be changed

architecture: x86_64
config:
  raw.apparmor: mount fstype=nfs,mount fstype=nfs4,mount fstype=nfsd,mount fstype=rpc_pipefs,
  raw.lxc: lxc.apparmor.profile=unconfined
  security.privileged: "true"
  volatile.base_image: 577a2539b39e698a945e9024e7ff878890df07704993af4dec0dc9c1f117b960
  volatile.eth0.hwaddr: 00:16:3e:5f:78:4c
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
devices:
  root:
    path: /
    type: disk
    pool: default
ephemeral: false
profiles:
- default
stateful: false
description: ""
~                                                                                                                                                   
~                                                                                                                                                   
"/tmp/lxd_editor_782043940.yaml" 39L, 1013C
```



```
Config parsing error: The storage pool of the root disk can only be changed through move
Press enter to start the editor again
```

**Comment by stgraber** [comment]
Interesting, this appears to be a rather old data migration bug, probably dating back from way back when we introduce the concept of storage pools.

Can you show:
 - lxc storage pool list
 - lxc profile list
 - lxc profile show default

With that, I can figure out instructions to fix the database entries at which point you'll be able to fix the raw.lxc entry and be back in business.

**Comment by helamonster** [comment]
Yes, very strange indeed...

```
root@util ~ # lxc storage pool list
Description:
  Manage storage pools and volumes

Usage:
  lxc storage [command]

Available Commands:
  create      Create storage pools
  delete      Delete storage pools
  edit        Edit storage pool configurations as YAML
  get         Get values for storage pool configuration keys
  info        Show useful information about storage pools
  list        List available storage pools
  set         Set storage pool configuration keys
  show        Show storage pool configurations and resources
  unset       Unset storage pool configuration keys
  volume      Manage storage volumes

Global Flags:
      --debug            Show all debug messages
      --force-local      Force using the local unix socket
  -h, --help             Print help
      --project string   Override the source project
  -q, --quiet            Don't show progress information
  -v, --verbose          Show all information messages
      --version          Print version number

Use "lxc storage [command] --help" for more information about a command.

root@util ~ # lxc profile list
+---------+---------+
|  NAME   | USED BY |
+---------+---------+
| default | 7       |
+---------+---------+
| docker  | 0       |
+---------+---------+
root@util ~ # lxc profile show default
config:
  environment.http_proxy: ""
  'environment.http_proxy:': ""
  raw.apparmor: |-
    mount fstype=nfs,
    mount fstype=nfs4,
    mount fstype=nfsd,
    mount fstype=rpc_pipefs,
  raw.lxc: lxc.apparmor.profile=unconfined
  user.network_mode: ""
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/boot
- /1.0/containers/mail
- /1.0/containers/mail/snap0
- /1.0/containers/letsencrypt
- /1.0/containers/letsencrypt/snap0
- /1.0/containers/boot/snap0
- /1.0/containers/openvpn


```

**Comment by stgraber** [comment]
Ok, excellent, so your profile looks right, it's just the per-container entries that are incorrect.

The easiest fix likely is:
```
lxd sql global "DELETE FROM containers_devices WHERE name='root' AND type='disk';
```

This will immediately make all containers inherit from the default profile.

**Comment by helamonster** [comment]
I don't want to assume that I should use "2" instead of "'disk'" but here's what I have:

```
root@util ~ # lxd sql global "DELETE FROM containers_devices WHERE name='root' AND type='disk';"
Rows affected: 0
root@util ~ # lxd sql global "SELECT * FROM containers_devices;"
+-----+--------------+------+------+
| id  | container_id | name | type |
+-----+--------------+------+------+
| 105 | 1            | root | 2    |
| 110 | 8            | root | 2    |
| 111 | 7            | root | 2    |
| 112 | 4            | root | 2    |
| 183 | 6            | root | 2    |
| 184 | 3            | root | 2    |
+-----+--------------+------+------+
root@util ~ # lxd sql global "SELECT * FROM containers_devices_ref;"
+---------+------+-------------------+--------+------+------+---------+
| project | node |       name        | device | type | key  |  value  |
+---------+------+-------------------+--------+------+------+---------+
| default | none | boot              | root   | 2    | path | /       |
| default | none | boot/snap0        | root   | 2    | path | /       |
| default | none | boot/snap0        | root   | 2    | pool | default |
| default | none | letsencrypt/snap0 | root   | 2    | path | /       |
| default | none | letsencrypt/snap0 | root   | 2    | pool | default |
| default | none | mail/snap0        | root   | 2    | path | /       |
| default | none | mail/snap0        | root   | 2    | pool | default |
| default | none | letsencrypt       | root   | 2    | path | /       |
| default | none | letsencrypt       | root   | 2    | pool | default |
| default | none | mail              | root   | 2    | path | /       |
| default | none | mail              | root   | 2    | pool | default |
+---------+------+-------------------+--------+------+------+---------+
```

**Comment by stgraber** [comment]
Oh, sorry about that, yes, 2 is correct.

```
lxd sql global "DELETE FROM containers_devices WHERE name='root' AND type=2;"
```

In your case that will effectively empty that whole table as you don't have devices other than the root of the containers.

**Comment by helamonster** [comment]
Getting closer...

```
root@util ~ # lxd sql global "DELETE FROM containers_devices WHERE name='root' AND type=2;"
Rows affected: 6
root@util ~ # lxc start boot;      
Error: Common start logic: Load go-lxc struct: Failed to load raw.lxc
root@util ~ # lxc config edit boot
```

```
### This is a yaml representation of the configuration.
### Any line starting with a '# will be ignored.
###
### A sample configuration looks like:
### name: container1
### profiles:
### - default
### config:
###   volatile.eth0.hwaddr: 00:16:3e:e9:f8:7f
### devices:
###   homedir:
###     path: /extra
###     source: /home/user
###     type: disk
### ephemeral: false
###
### Note that the name is shown but cannot be changed

architecture: x86_64
config:
  raw.apparmor: mount fstype=nfs,mount fstype=nfs4,mount fstype=nfsd,mount fstype=rpc_pipefs,
  raw.lxc: lxc.apparmor.profile=unconfined
  security.privileged: "true"
  volatile.base_image: 577a2539b39e698a945e9024e7ff878890df07704993af4dec0dc9c1f117b960
  volatile.eth0.hwaddr: 00:16:3e:5f:78:4c
  volatile.idmap.base: "0"
  volatile.idmap.current: '[]'
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

```
root@util ~ # lxc start boot
Error: Common start logic: no such file or directory
Try 'lxc info --show-log boot' for more info
root@util ~ # lxc info --show-log boot
Name: boot
Location: none
Remote: unix://
Architecture: x86_64
Created: 2019/02/25 20:52 UTC
Status: Stopped
Type: persistent
Profiles: default
Snapshots:
  snap0 (taken at 2019/02/28 20:33 UTC) (stateless)

Log:
root@util ~ #  sudo snap restart lxd
Restarted.
root@util ~ # lxc list
+-------------+---------+------+------+------------+-----------+
|    NAME     |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+-------------+---------+------+------+------------+-----------+
| boot        | STOPPED |      |      | PERSISTENT | 1         |
+-------------+---------+------+------+------------+-----------+
| letsencrypt | STOPPED |      |      | PERSISTENT | 1         |
+-------------+---------+------+------+------------+-----------+
| mail        | STOPPED |      |      | PERSISTENT | 1         |
+-------------+---------+------+------+------------+-----------+
| openvpn     | STOPPED |      |      | PERSISTENT | 0         |
+-------------+---------+------+------+------------+-----------+
root@util ~ # lxc start boot
Error: Common start logic: no such file or directory
Try 'lxc info --show-log boot' for more info
root@util ~ # lxc info --show-log boot
Name: boot
Location: none
Remote: unix://
Architecture: x86_64
Created: 2019/02/25 20:52 UTC
Status: Stopped
Type: persistent
Profiles: default
Snapshots:
  snap0 (taken at 2019/02/28 20:33 UTC) (stateless)

Log:
```

```
root@util ~ # lxc storage list
+---------+-------------+--------+-----------+---------+
|  NAME   | DESCRIPTION | DRIVER |  SOURCE   | USED BY |
+---------+-------------+--------+-----------+---------+
| default |             | zfs    | rpool/lxd | 8       |
+---------+-------------+--------+-----------+---------+
root@util ~ # lxc config device add boot root disk pool=default path=/
Device root added to boot
root@util ~ # lxc config show boot
architecture: x86_64
config:
  raw.apparmor: mount fstype=nfs,mount fstype=nfs4,mount fstype=nfsd,mount fstype=rpc_pipefs,
  raw.lxc: lxc.apparmor.profile=unconfined
  security.privileged: "true"
  volatile.base_image: 577a2539b39e698a945e9024e7ff878890df07704993af4dec0dc9c1f117b960
  volatile.eth0.hwaddr: 00:16:3e:5f:78:4c
  volatile.idmap.base: "0"
  volatile.idmap.current: '[]'
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
devices:
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
root@util ~ # lxc start boot
Error: Common start logic: no such file or directory
Try 'lxc info --show-log boot' for more info
root@util ~ # lxc info --show-log boot
Name: boot
Location: none
Remote: unix://
Architecture: x86_64
Created: 2019/02/25 20:52 UTC
Status: Stopped
Type: persistent
Profiles: default
Snapshots:
  snap0 (taken at 2019/02/28 20:33 UTC) (stateless)

Log:
```

```
root@util ~ # zfs list -r rpool/lxd
NAME                                                                                USED  AVAIL     REFER  MOUNTPOINT
rpool/lxd                                                                          34.8G  1.67T      192K  none
rpool/lxd/containers                                                               34.3G  1.67T      192K  none
rpool/lxd/containers/boot                                                          34.3G  1.67T     29.5G  /var/snap/lxd/common/lxd/containers/boot.zfs
rpool/lxd/deleted                                                                   384K  1.67T      192K  none
rpool/lxd/deleted/images                                                            192K  1.67T      192K  none
rpool/lxd/images                                                                    453M  1.67T      192K  none
rpool/lxd/images/038e22932b77f19b7d9907940f5c59299235ff5560b147888a7067879fbe2433   453M  1.67T      453M  none
```
