### ISSUE TITLE
Unable to set snapshots.pattern key in profile on LXD 3.17

### ISSUE THREAD

**Issue by truelai** [lxc/lxd#6229]
```
root@R510-LXD6-Backup:~# lxd --version
3.17
```
When attempting to add _snapshots.pattern_ to an LXD profile, the following error is thrown:
`Config parsing error: yaml: line 23: did not find expected key`

Shouldn't I be able to set this in a profile? Per docs:

> Profiles can store any configuration that a container can (key/value or devices) and any number of profiles can be applied to a container.

**Comment by stgraber** [comment]
```
stgraber@castiana:~$ lxc profile set default snapshots.pattern "* * * *"
stgraber@castiana:~$ 
```

**Comment by stgraber** [comment]
```
stgraber@castiana:~$ lxc profile show default
config:
  snapshots.pattern: '* * * *'
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
```

**Comment by stgraber** [comment]
@truelai how exactly did you set the key and to what value?

The error you got suggests that the YAML input was invalid, which would suggest you used `lxc profile edit` or the API directly and mis-indented something or didn't quote the pattern as seen in my `lxc profile show` output above.

**Comment by truelai** [comment]
Yes, I used lxc profile edit. Why is this wrong?

Ideally, I'd like to have:
`snapshots.pattern: "{{ creation_date|date:"2006-01-02_15-04-05" }}"`

**Comment by truelai** [comment]
Looks like it works but it stripped the internal quotes:

root@R510-LXD6-Backup:~# lxc profile show default 
```
config:
  limits.memory: 22GB
  limits.memory.swap: "false"
  snapshots.pattern: '{{ creation_date|date:2006-01-02_15-04-05 }}'
  snapshots.schedule: '* * * * 1'
  snapshots.schedule.stopped: "false"
```
