### ISSUE TITLE
Can't create custom storage volumes on cephfs storage

### ISSUE THREAD

**Issue by suprasoil** [lxc/lxd#6477]
## Box

Ubuntu 18.04
```
root@alpha-0001:/# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```
```
root@alpha-0001:/# uname -a
Linux alpha-0001 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Latest snap:
```
root@alpha-0001:/# snap list
Name  Version    Rev    Tracking  Publisher   Notes
core  16-2.42.1  8039   stable    canonical✓  core
lxd   3.18       12317  3.18      canonical✓  -
```

## Cluster
I have a working cephfs (i can mount it manually and add/remove data)
```
root@alpha-0001:/# ceph fs ls
name: forest, metadata pool: forest_meta, data pools: [forest_data ]
```

I'm running LXD clustered and added the storage

First node:
```
config:
  core.https_address: 10.254.0.4:8443
  core.trust_password: secret
cluster:
  server_name: alpha-0001
  enabled: true
  member_config: []
  cluster_address: ""
  cluster_certificate: ""
  server_address: "10.254.0.4:8443"
  cluster_password: ""
networks: []
storage_pools:
- config:
    source: forest/lxd
  description: ""
  name: local
  driver: zfs
- config:
    cephfs.cluster_name: ceph
    source: forest
  description: ""
  name: remote
  driver: cephfs
profiles:
- config:
    boot.autostart: "1"
  description: Clients LXD profile
  devices:
    eth0:
      nictype: bridged
      parent: clients
      type: nic
    root:
      path: /
      pool: local
      type: disk
  name: default
```

Other nodes (with unique names/addresses obviously)
```
cluster:
  server_name: alpha-0002
  enabled: true
  cluster_address: 10.254.0.4:8443
  cluster_certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
    
  server_address: 10.254.0.3:8443
  cluster_password: secret
  member_config:
  - entity: storage-pool
    name: local
    key: source
    value: "forest/lxd"
  - entity: storage-pool
    name: local
    key: zfs.pool_name
    value: "forest/lxd"
  - entity: storage-pool
    name: remote
    key: source
    value: "forest"
```

Cluster setup completes without errors, storage shows up fine:
```
root@alpha-0001:/# lxc storage list
+--------+-------------+--------+---------+---------+
|  NAME  | DESCRIPTION | DRIVER |  STATE  | USED BY |
+--------+-------------+--------+---------+---------+
| local  |             | zfs    | CREATED | 1       |
+--------+-------------+--------+---------+---------+
| remote |             | cephfs | CREATED | 0       |
+--------+-------------+--------+---------+---------+
```

## Errors

I can't create volumes:
```
root@alpha-0001:/# lxc storage volume create remote testing
Error: mkdir /var/snap/lxd/common/lxd/storage-pools/remote/custom/testing: read-only file system
```

```
root@alpha-0002:/# lxc storage volume create remote testing
Error: mkdir /var/snap/lxd/common/lxd/storage-pools/remote/custom: file exists
```

I've set the cluster up manually and automated, both resulting in this problem.

Is there something i missed? Do i need to set some kind of permissions on the cephfs?

**Comment by stgraber** [comment]
Can you show `nsenter -t $(pgrep daemon.start) -m -- grep ceph /proc/mounts`?

**Comment by suprasoil** [comment]
```
root@alpha-0001:/# nsenter -t $(pgrep daemon.start) -m -- grep ceph /proc/mounts
tmpfs /var/lib/snapd/hostfs/var/lib/ceph/osd/ceph-0 tmpfs rw,relatime 0 0
10.254.0.4:6789:// /var/snap/lxd/common/lxd/storage-pools/remote ceph rw,relatime,name=admin,secret=<hidden>,acl,mds_namespace=forest,wsize=33554432 0 0
```

**Comment by stgraber** [comment]
Ok, so the Ceph filesystem is indeed mounted, good.

Can you try:
 - `nsenter -t $(pgrep daemon.start) -m -- mkdir /var/snap/lxd/common/lxd/storage-pools/remote/test`
 - `nsenter -t $(pgrep daemon.start) -m -- rmdir /var/snap/lxd/common/lxd/storage-pools/remote/test`

If that similarly fails with the `read-only` error, then that'd suggest some kind of ceph fs issue preventing new writes.

**Comment by suprasoil** [comment]
```
root@alpha-0001:/# nsenter -t $(pgrep daemon.start) -m -- mkdir /var/snap/lxd/common/lxd/storage-pools/remote/test
root@alpha-0001:/# nsenter -t $(pgrep daemon.start) -m -- ls /var/snap/lxd/common/lxd/storage-pools/remote
test
root@alpha-0001:/# nsenter -t $(pgrep daemon.start) -m -- rmdir /var/snap/lxd/common/lxd/storage-pools/remote/test
root@alpha-0001:/# lxc storage volume create remote testing
Error: mkdir /var/snap/lxd/common/lxd/storage-pools/remote/custom/testing: read-only file system
root@alpha-0001:/# nsenter -t $(pgrep daemon.start) -m -- ls /var/snap/lxd/common/lxd/storage-pools/remote
custom
root@alpha-0001:/# nsenter -t $(pgrep daemon.start) -m -- ls /var/snap/lxd/common/lxd/storage-pools/remote/custom
root@alpha-0001:/# 
```

**Comment by suprasoil** [comment]
When i mount it manually as root like this:
```
root@alpha-0001:/# cat /etc/fstab 
10.254.0.4,10.254.0.3,10.254.0.5:/ /mnt/cephfs ceph relatime,name=admin,secret=AQDxJ8Rd6XXfLRAAXRCbEtKF9bXoLZwj1tjwEw==,mds_namespace=forest 0 0
```
```
root@alpha-0001:/# mount | grep cephfs
10.254.0.4,10.254.0.3,10.254.0.5:/ on /mnt/cephfs type ceph (rw,relatime,name=admin,secret=<hidden>,acl,mds_namespace=forest,wsize=33554432)
```

I *can* create subdirectories, do you have any idea what's going on?

**Comment by suprasoil** [comment]
Ah, when i mount it like this:
```
10.254.0.4:6789:/ on /mnt/cephfs type ceph (rw,relatime,name=admin,secret=<hidden>,acl,mds_namespace=forest,wsize=33554432)
```
Everything is fine.

When i mount it like this:
```
10.254.0.4:6789:// on /mnt/cephfs type ceph (rw,relatime,name=admin,secret=<hidden>,acl,mds_namespace=forest,wsize=33554432)
```

I'm getting these errors. I don't know what path `//` is pointing to, but it seems to be causing this behaviour.

**Comment by stgraber** [comment]
Oh, that's interesting.

What's your `lxc storage show remote` showing? I suspect we need to better handle `source=/`.

**Comment by suprasoil** [comment]
I'm using the default, storage has been setup with:
```
- config:
    cephfs.cluster_name: ceph
    source: forest
  description: ""
  name: remote
  driver: cephfs
```

I don't get why cephfs.path is showing forest here as i did not pass that as config.
```
root@alpha-0001:/# lxc storage show remote
config:
  cephfs.cluster_name: ceph
  cephfs.path: forest
description: ""
name: remote
driver: cephfs
used_by: []
status: Created
locations:
- alpha-0001
- alpha-0002
- alpha-0003
```

----------------------------------

Now that i know the path is causing problems, i tried to setup the storage with the `cephfs.path` config set, but this seems to be ignored:
```
- config:                     
    cephfs.cluster_name: ceph
    cephfs.path: forest
    source: forest
  description: ""
  name: remote
  driver: cephfs
```
results in:
```
root@alpha-0001:/# lxc storage show remote
config:
  cephfs.cluster_name: ceph
  cephfs.path: forest
description: ""
name: remote
driver: cephfs
used_by: []
status: Created
locations:
- alpha-0001
- alpha-0002
- alpha-0003
```
and:
```
root@alpha-0001:/# nsenter -t $(pgrep daemon.start) -m -- grep ceph /proc/mounts
tmpfs /var/lib/snapd/hostfs/var/lib/ceph/osd/ceph-0 tmpfs rw,relatime 0 0
10.254.0.4:6789:// /var/snap/lxd/common/lxd/storage-pools/remote ceph rw,relatime,name=admin,secret=<hidden>,acl,mds_namespace=forest,wsize=33554432 0 0
```
