### ISSUE TITLE
Can't join cluster that is using a cephfs storage pool

### ISSUE THREAD

**Issue by suprasoil** [lxc/lxd#6537]
I'm running edge to test if i can use cephfs after https://github.com/lxc/lxd/issues/6477 was resolved, i can now add a cephfs remote storage pool and use it, but can't setup a cluster using a cephfs pool.

```
root@alpha-0001:/# uname -a
Linux alpha-0001 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
```
root@alpha-0001:/# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```
```
root@alpha-0001:/# snap list
Name  Version      Rev    Tracking  Publisher   Notes
core  16-2.42.1    8039   stable    canonical✓  core
lxd   git-a75e207  12625  edge      canonical✓  -
```

When setting up the first node with this config:
```
storage_pools:
- config:
    source: forest/lxd
  description: ""
  name: local
  driver: zfs
- config:
    cephfs.cluster_name: ceph
    source: forest
  description: ""
  name: remote
  driver: cephfs
```

and try to init the second & third nodes with this:
```
member_config:
- entity: storage-pool
  name: local
  key: source
  value: "forest/lxd"
- entity: storage-pool
  name: local
  key: zfs.pool_name
  value: "forest/lxd"
- entity: storage-pool
  name: remote
  key: source
  value: "forest"
```

I run into the following error when trying to init LXD with a cephfs remote storage pool.
```
Error: Failed to join cluster: Failed to initialize member: Failed to initialize storage pools and networks: Failed to create storage pool 'remote': Only empty CEPHFS paths can be used as a LXD storage pool
```

I have tried this scripted & manually, both with & without the config for the remote pool passed as `member_config` to the second & third node, all resulting in this issue.
