### ISSUE TITLE
Initialize LXC: Failed to load raw.lxc

### ISSUE THREAD

**Issue by zanzara** [lxc/lxd#6661]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.6 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version:  4.20.17-042017-generic
   * LXC version: 3.0.3
   * LXD version: 3.0.3.
   * Storage backend in use: dir

# Issue description

I have update lxd/lxc from V2.x to V3.0.3 but now it is not anymore possible to start container. I always get the error "Initialize LXC: Failed to load raw.lxc".

The main issue will be , that my container is privileged and I've had to set set aa_profile=unconfined.
 `lxc config set webserver raw.lxc "lxc.aa_profile=unconfined"`
Then it worked fine under lxd V2.x as expected.
Now i wanted to copy container to a remote one (which has lxd V3.0.3) and I got also this error while copying. Therefore i tried to update my local lxd to Ver. 3.0.3.  but I'm having the same troubles.

No I don't have any clue how to get out this misery, because **any `lxc config set`
leads** to this error for my container.
I think , that this is a migration bug.

If I try to edit config file this way:
`lxc config edit webserver < newconfig.yaml`
overwriting 
aa_profile=unconfined   with the new keyword lxc.apparmor.profile=unconfined
then I receive other errors like i.e.
`Error: The storage pool of the root disk can only be changed through move`

Is there a chance to get my container running fine again?

# Steps to reproduce

 1. Step one
Install lxd V. 2x  and create a pivileged container and set config raw.lxc lxc.aa_profile=unconfined
 2. Step two
Update to lxd V3.0.3
 3. Step three
Try to start container

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [x] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

```
architecture: x86_64
config:
  environment.http_proxy: ""
  raw.apparmor: mount fstype=cfis,
  raw.idmap: both 1000 1000
  raw.lxc: lxc.aa_profile=unconfined
  security.privileged: "true"
  user.network_mode: ""
  volatile.base_image: f75468c572cc50eca7f76391182e6fdaf58431f84c3d35a2c92e83814e701698
  volatile.eth0.hwaddr: 00:16:3e:cf:f9:a2
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    type: disk
  sharedir:
    path: /var/www/html
    source: /home/sfn/VirtualBox VMs/TBS_Development/Exchange/www
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""


```

**Comment by stgraber** [comment]
Hmm, okay, so you have two problems:
 - Your disk entry is lacking the `pool` property
 - Your `raw.lxc` is invalid.

Can you show `lxc config show NAME` (without --expanded).

The fix for the `root` disk may need database surgery to fix, at which point LXD will behave as expected and you'll be able to fix the raw.lxc part with `lxc config edit`.

**Comment by zanzara** [comment]
Hi
thanks for your repley. 
this is `lxc config show NAME` :

```
architecture: x86_64
config:
  raw.apparmor: mount fstype=cfis,
  raw.idmap: both 1000 1000
  raw.lxc: lxc.aa_profile=unconfined
  security.privileged: "true"
  volatile.base_image: f75468c572cc50eca7f76391182e6fdaf58431f84c3d35a2c92e83814e701698
  volatile.eth0.hwaddr: 00:16:3e:cf:f9:a2
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
devices:
  root:
    path: /
    type: disk
  sharedir:
    path: /var/www/html
    source: /home/sfn/VirtualBox VMs/TBS_Development/Exchange/www
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
How to make a database surgery in that case?
As you can see above, i made a `newconfig.yaml` file, where I added the lacking pool entry and change the to new apparmor key.
but after lxc config edit NAME < newconfig.yaml
I got this error I mentioned above.  I see no chance at the moment to fix it.

```
architecture: x86_64
config:
  raw.apparmor: mount fstype=cfis,
  raw.idmap: both 1000 1000
  raw.lxc: lxc.apparmor.profile="unconfined"
  security.privileged: "true"
  volatile.base_image: f75468c572cc50eca7f76391182e6fdaf58431f84c3d35a2c92e83814e701698
  volatile.eth0.hwaddr: 00:16:3e:cf:f9:a2
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
devices:
  root:
    path: /
    pool: default
    type: disk
  sharedir:
    path: /var/www/html
    source: /home/sfn/VirtualBox VMs/TBS_Development/Exchange/www
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 
Appreciating furtheron any help.
