### ISSUE TITLE
lxc image export does not include image parameters

### ISSUE THREAD

**Issue by wbyrnetx** [lxc/lxd#6674]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.3
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-72-generic
   * LXC version: 3.2.1
   * LXD version: 3.18
   * Storage backend in use: dir

# Issue description

I would expect that properties of an image are retained after exporting an image to a file and then re-importing that file as an image. This does not happen. No matter what properties were set on the image, the export's metadata.yml always looks like this (these are ubuntu:bionic based images)...
```
properties:
    architecture: "x86_64"
    description: "Ubuntu 18.04 LTS server (20191218)"
    os: "ubuntu"
    release: "bionic"
```

# Steps to reproduce

1. Set properties on a custom image in your store
`lxc image edit abcdefg`

2. Export your image to a file
`lxc image export abcdefg ./my-image`

3. Delete your image
`lxc image delete abcdefg`

4. Import image from file
`lxc image import ./my-image.tar.gz`

5. Inspect properties
`lxc image show abcdefg`
