### ISSUE TITLE
lxc copy sometimes broken with LXD 3.19?

### ISSUE THREAD

**Issue by tchwpkgorg** [lxc/lxd#6769]
All lxd servers run the following:

```
lxd   3.19       13098  stable    canonical✓  -
```

Which is also the newest lxd:

```
# snap refresh lxd
snap "lxd" has no updates available
```

This works fine to some servers:

```
# lxc copy tomasztest work02:tomasztest
# echo $?
0
```

But fails to others:
```
# time lxc copy tomasztest work01:tomasztest
Error: Failed instance creation:
 - https://10.0.0.238:8443: Error transferring container data: exit status 22
 - https://10.196.139.1:8443: Error transferring container data: Unable to connect to: 10.196.139.1:8443

real    0m11.530s
user    0m0.150s
sys     0m0.034s
```

10.0.0.238 - this is "eth0" IP of the server I'm trying to copy FROM.
10.196.139.1 - this is the "lxdbr0" IP of the server I'm trying to copy FROM.

It works from the same server:

```
# curl https://10.196.139.1:8443 -k
{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":["/1.0"]}
```

This used to work fine for the past months and there weren't any changes (other than snap auto upgrades).

**Comment by tchwpkgorg** [comment]
More info - why does it do it?

"work01" server (the one I'm unable to copy the data to) won't be able to connect there - 10.196.139.1 is lxdbr0 IP of the server I'm copying the data FROM.
"work02" server (which succeeds) does not do it.

```
root@work01:~# tcpdump -i any -v -n host 10.196.139.1
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
13:13:23.232420 IP (tos 0x0, ttl 64, id 56178, offset 0, flags [DF], proto TCP (6), length 60)
    10.0.0.159.57564 > 10.196.139.1.8443: Flags [S], cksum 0xa092 (incorrect -> 0x353e), seq 3640499820, win 62727, options [mss 8961,sackOK,TS val 1392350153 ecr 0,nop,wscale 7], length 0
13:13:24.264234 IP (tos 0x0, ttl 64, id 56179, offset 0, flags [DF], proto TCP (6), length 60)
    10.0.0.159.57564 > 10.196.139.1.8443: Flags [S], cksum 0xa092 (incorrect -> 0x3136), seq 3640499820, win 62727, options [mss 8961,sackOK,TS val 1392351185 ecr 0,nop,wscale 7], length 0
13:13:26.284255 IP (tos 0x0, ttl 64, id 56180, offset 0, flags [DF], proto TCP (6), length 60)
    10.0.0.159.57564 > 10.196.139.1.8443: Flags [S], cksum 0xa092 (incorrect -> 0x2952), seq 3640499820, win 62727, options [mss 8961,sackOK,TS val 1392353205 ecr 0,nop,wscale 7], length 0
13:13:30.536236 IP (tos 0x0, ttl 64, id 56181, offset 0, flags [DF], proto TCP (6), length 60)
    10.0.0.159.57564 > 10.196.139.1.8443: Flags [S], cksum 0xa092 (incorrect -> 0x18b6), seq 3640499820, win 62727, options [mss 8961,sackOK,TS val 1392357457 ecr 0,nop,wscale 7], length 0
```

**Comment by tchwpkgorg** [comment]
Things like this work:
```
# lxc list work01:
```

Only lxc copy TO remote seems to be broken. Copying FROM remote works fine:
```
# lxc copy work01:work01-2020-01-23-13-39-22 here
Transferring instance: Unpack: 100% (92.73MB/s)
```

**Comment by tchwpkgorg** [comment]
lxd monitor from work01:

```
metadata:
  context:
    k: "0"
  level: dbug
  message: Found cert
timestamp: "2020-01-24T13:30:47.245266462Z"
type: logging


metadata:
  context:
    ip: 10.0.0.238:50150
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2020-01-24T13:30:47.245316207Z"
type: logging


metadata:
  context:
    k: "0"
  level: dbug
  message: Found cert
timestamp: "2020-01-24T13:30:47.246256996Z"
type: logging


metadata:
  context:
    ip: 10.0.0.238:50152
    method: GET
    url: /1.0/events
  level: dbug
  message: handling
timestamp: "2020-01-24T13:30:47.291017651Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'New event listener: 2ad949bc-c7b3-4207-b954-1c3ab3479bcb'
timestamp: "2020-01-24T13:30:47.291079775Z"
type: logging


metadata:
  context:
    k: "0"
  level: dbug
  message: Found cert
timestamp: "2020-01-24T13:30:47.290977035Z"
type: logging


metadata:
  context:
    k: "0"
  level: dbug
  message: Found cert
timestamp: "2020-01-24T13:30:47.327830591Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Responding to container create
timestamp: "2020-01-24T13:30:47.327897164Z"
type: logging


metadata:
  context:
    ip: 10.0.0.238:50154
    method: POST
    url: /1.0/containers
  level: dbug
  message: handling
timestamp: "2020-01-24T13:30:47.327876196Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: No valid storage pool in the container's local root disk device and profiles
    found
timestamp: "2020-01-24T13:30:47.331539092Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Database error: &errors.errorString{s:"sql: no rows in result set"}'
timestamp: "2020-01-24T13:30:47.331897193Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Database error: &errors.errorString{s:"sql: no rows in result set"}'
timestamp: "2020-01-24T13:30:47.33267709Z"
type: logging


metadata:
  context:
    ephemeral: "false"
    name: tomasztest
  level: info
  message: Creating container
timestamp: "2020-01-24T13:30:47.337653344Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/tomasztest
timestamp: "2020-01-24T13:30:47.354981411Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/tomasztest
timestamp: "2020-01-24T13:30:47.361619156Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/tomasztest
timestamp: "2020-01-24T13:30:47.368426574Z"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: Creating empty DIR storage volume for container "tomasztest" on storage
    pool "default"
timestamp: "2020-01-24T13:30:47.374280674Z"
type: logging


metadata:
  context:
    ephemeral: "false"
    name: tomasztest
  level: info
  message: Created container
timestamp: "2020-01-24T13:30:47.374217411Z"
type: logging


metadata:
  action: container-created
  source: /1.0/containers/tomasztest
timestamp: "2020-01-24T13:30:47.374260286Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/tomasztest
timestamp: "2020-01-24T13:30:47.381618275Z"
type: lifecycle


metadata:
  context:
    name: tomasztest
  level: warn
  message: Unable to update backup.yaml at this time
timestamp: "2020-01-24T13:30:47.38175332Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Created empty DIR storage volume for container "tomasztest" on storage
    pool "default"
timestamp: "2020-01-24T13:30:47.38166647Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'New task operation: 87d48fb7-0a40-4ae3-8266-fb995ae9e7ef'
timestamp: "2020-01-24T13:30:47.43753408Z"
type: logging


metadata:
  class: task
  created_at: "2020-01-24T13:30:47.434916231Z"
  description: Creating container
  err: ""
  id: 87d48fb7-0a40-4ae3-8266-fb995ae9e7ef
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/tomasztest
  status: Pending
  status_code: 105
  updated_at: "2020-01-24T13:30:47.434916231Z"
timestamp: "2020-01-24T13:30:47.437566877Z"
type: operation


metadata:
  context: {}
  level: dbug
  message: 'Started task operation: 87d48fb7-0a40-4ae3-8266-fb995ae9e7ef'
timestamp: "2020-01-24T13:30:47.437596672Z"
type: logging


metadata:
  class: task
  created_at: "2020-01-24T13:30:47.434916231Z"
  description: Creating container
  err: ""
  id: 87d48fb7-0a40-4ae3-8266-fb995ae9e7ef
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/tomasztest
  status: Running
  status_code: 103
  updated_at: "2020-01-24T13:30:47.434916231Z"
timestamp: "2020-01-24T13:30:47.437609372Z"
type: operation


metadata:
  context:
    ip: 10.0.0.238:50156
    method: GET
    url: /1.0/operations/87d48fb7-0a40-4ae3-8266-fb995ae9e7ef
  level: dbug
  message: handling
timestamp: "2020-01-24T13:30:47.47341273Z"
type: logging


metadata:
  context:
    k: "0"
  level: dbug
  message: Found cert
timestamp: "2020-01-24T13:30:47.473366535Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: sending write barrier
timestamp: "2020-01-24T13:30:47.591603345Z"
type: logging


metadata:
  context: {}
  level: eror
  message: 'Rsync receive failed: /var/lib/lxd/containers/tomasztest/: exit status
    22: '
timestamp: "2020-01-24T13:30:47.591696425Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Got message barrier, resetting stream
timestamp: "2020-01-24T13:30:47.592138977Z"
type: logging


metadata:
  context:
    err: exit status 22
  level: eror
  message: Error during migration sink
timestamp: "2020-01-24T13:30:47.592363803Z"
type: logging


metadata:
  context:
    created: 2020-01-24 13:30:47 +0000 UTC
    ephemeral: "false"
    name: tomasztest
    used: 1970-01-01 00:00:00 +0000 UTC
  level: info
  message: Deleting container
timestamp: "2020-01-24T13:30:47.592428117Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Deleting DIR storage volume for container "tomasztest" on storage pool
    "default"
timestamp: "2020-01-24T13:30:47.595626733Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Deleted DIR storage volume for container "tomasztest" on storage pool "default"
timestamp: "2020-01-24T13:30:47.59602207Z"
type: logging


metadata:
  action: container-deleted
  source: /1.0/containers/tomasztest
timestamp: "2020-01-24T13:30:47.760490057Z"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: 'Failure for task operation: 87d48fb7-0a40-4ae3-8266-fb995ae9e7ef: Error
    transferring container data: exit status 22'
timestamp: "2020-01-24T13:30:47.760535752Z"
type: logging


metadata:
  context:
    created: 2020-01-24 13:30:47 +0000 UTC
    ephemeral: "false"
    name: tomasztest
    used: 1970-01-01 00:00:00 +0000 UTC
  level: info
  message: Deleted container
timestamp: "2020-01-24T13:30:47.760438932Z"
type: logging


metadata:
  class: task
  created_at: "2020-01-24T13:30:47.434916231Z"
  description: Creating container
  err: 'Error transferring container data: exit status 22'
  id: 87d48fb7-0a40-4ae3-8266-fb995ae9e7ef
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/tomasztest
  status: Failure
  status_code: 400
  updated_at: "2020-01-24T13:30:47.434916231Z"
timestamp: "2020-01-24T13:30:47.760575067Z"
type: operation


metadata:
  context: {}
  level: dbug
  message: Responding to container create
timestamp: "2020-01-24T13:30:47.796708041Z"
type: logging


metadata:
  context:
    k: "0"
  level: dbug
  message: Found cert
timestamp: "2020-01-24T13:30:47.796646237Z"
type: logging


metadata:
  context:
    ip: 10.0.0.238:50158
    method: POST
    url: /1.0/containers
  level: dbug
  message: handling
timestamp: "2020-01-24T13:30:47.796691523Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: No valid storage pool in the container's local root disk device and profiles
    found
timestamp: "2020-01-24T13:30:47.799703548Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Database error: &errors.errorString{s:"sql: no rows in result set"}'
timestamp: "2020-01-24T13:30:47.8000565Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Database error: &errors.errorString{s:"sql: no rows in result set"}'
timestamp: "2020-01-24T13:30:47.80080354Z"
type: logging


metadata:
  context:
    ephemeral: "false"
    name: tomasztest
  level: info
  message: Creating container
timestamp: "2020-01-24T13:30:47.805384948Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/tomasztest
timestamp: "2020-01-24T13:30:47.821367618Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/tomasztest
timestamp: "2020-01-24T13:30:47.828023353Z"
type: lifecycle


metadata:
  action: container-updated
  source: /1.0/containers/tomasztest
timestamp: "2020-01-24T13:30:47.835344805Z"
type: lifecycle


metadata:
  context:
    ephemeral: "false"
    name: tomasztest
  level: info
  message: Created container
timestamp: "2020-01-24T13:30:47.841292365Z"
type: logging


metadata:
  action: container-created
  source: /1.0/containers/tomasztest
timestamp: "2020-01-24T13:30:47.84133471Z"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: Creating empty DIR storage volume for container "tomasztest" on storage
    pool "default"
timestamp: "2020-01-24T13:30:47.841376566Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Created empty DIR storage volume for container "tomasztest" on storage
    pool "default"
timestamp: "2020-01-24T13:30:47.849167717Z"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/tomasztest
timestamp: "2020-01-24T13:30:47.849119423Z"
type: lifecycle


metadata:
  context:
    name: tomasztest
  level: warn
  message: Unable to update backup.yaml at this time
timestamp: "2020-01-24T13:30:47.849398443Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'New task operation: 8627a7ba-7765-4259-9176-01e958c15172'
timestamp: "2020-01-24T13:30:47.90268778Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Started task operation: 8627a7ba-7765-4259-9176-01e958c15172'
timestamp: "2020-01-24T13:30:47.902753952Z"
type: logging


metadata:
  class: task
  created_at: "2020-01-24T13:30:47.900139064Z"
  description: Creating container
  err: ""
  id: 8627a7ba-7765-4259-9176-01e958c15172
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/tomasztest
  status: Running
  status_code: 103
  updated_at: "2020-01-24T13:30:47.900139064Z"
timestamp: "2020-01-24T13:30:47.902766872Z"
type: operation


metadata:
  class: task
  created_at: "2020-01-24T13:30:47.900139064Z"
  description: Creating container
  err: ""
  id: 8627a7ba-7765-4259-9176-01e958c15172
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/tomasztest
  status: Pending
  status_code: 105
  updated_at: "2020-01-24T13:30:47.900139064Z"
timestamp: "2020-01-24T13:30:47.902723746Z"
type: operation


metadata:
  context:
    k: "0"
  level: dbug
  message: Found cert
timestamp: "2020-01-24T13:30:47.938234496Z"
type: logging


metadata:
  context:
    ip: 10.0.0.238:50160
    method: GET
    url: /1.0/operations/8627a7ba-7765-4259-9176-01e958c15172
  level: dbug
  message: handling
timestamp: "2020-01-24T13:30:47.938287601Z"
type: logging


metadata:
  context:
    err: 'Unable to connect to: 10.196.139.1:8443'
  level: eror
  message: Error during migration sink
timestamp: "2020-01-24T13:30:57.903180132Z"
type: logging


metadata:
  context:
    created: 2020-01-24 13:30:47 +0000 UTC
    ephemeral: "false"
    name: tomasztest
    used: 1970-01-01 00:00:00 +0000 UTC
  level: info
  message: Deleting container
timestamp: "2020-01-24T13:30:57.903760149Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Deleting DIR storage volume for container "tomasztest" on storage pool
    "default"
timestamp: "2020-01-24T13:30:57.906804879Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: Deleted DIR storage volume for container "tomasztest" on storage pool "default"
timestamp: "2020-01-24T13:30:57.906963631Z"
type: logging


metadata:
  context:
    created: 2020-01-24 13:30:47 +0000 UTC
    ephemeral: "false"
    name: tomasztest
    used: 1970-01-01 00:00:00 +0000 UTC
  level: info
  message: Deleted container
timestamp: "2020-01-24T13:30:58.073137121Z"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Failure for task operation: 8627a7ba-7765-4259-9176-01e958c15172: Error
    transferring container data: Unable to connect to: 10.196.139.1:8443'
timestamp: "2020-01-24T13:30:58.073215042Z"
type: logging


metadata:
  action: container-deleted
  source: /1.0/containers/tomasztest
timestamp: "2020-01-24T13:30:58.073184575Z"
type: lifecycle


metadata:
  class: task
  created_at: "2020-01-24T13:30:47.900139064Z"
  description: Creating container
  err: 'Error transferring container data: Unable to connect to: 10.196.139.1:8443'
  id: 8627a7ba-7765-4259-9176-01e958c15172
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/tomasztest
  status: Failure
  status_code: 400
  updated_at: "2020-01-24T13:30:47.900139064Z"
timestamp: "2020-01-24T13:30:58.073264047Z"
type: operation

```
