### ISSUE TITLE
Failed to set cgroup cpuset.cpus

### ISSUE THREAD

**Issue by microcoder** [lxc/lxd#6885]
# Required information

 * Distribution: Manjaro Linux Stable
 * Distribution version: Latest stable updates
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.5.2-1-MANJARO
   * LXC version: 3.20
   * LXD version: 3.20
   * Storage backend in use: btrfs

# Issue description

After starting Container I get error message in log file and container is stopping:

```
t=2020-02-16T16:04:36+0300 lvl=info msg="Starting container" action=start created=2020-02-16T16:04:34+0300 ephemeral=false name=jupyter project=default stateful=false used=1970-01-01T03:00:00+0300
t=2020-02-16T16:04:51+0300 lvl=info msg="Started container" action=start created=2020-02-16T16:04:34+0300 ephemeral=false name=jupyter project=default stateful=false used=1970-01-01T03:00:00+0300
t=2020-02-16T16:05:06+0300 lvl=eror msg="balance: Unable to set cpuset" err="Failed to set cgroup cpuset.cpus=\"0,1,2,3,4,5,6,7\": setting cgroup item for the container failed" name=jupyter value=0,1,2,3,4,5,6,7
t=2020-02-16T16:05:07+0300 lvl=info msg="Container initiated stop" action=stop created=2020-02-16T16:04:34+0300 ephemeral=false name=jupyter project=default stateful=false used=2020-02-16T16:04:36+0300
```

# Steps to reproduce

 1. Create container
 2. Start container
 3. Watch log file

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [x] Container configuration (`lxc config show NAME --expanded`)
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 19.10 amd64 (release) (20200129)
  image.label: release
  image.os: ubuntu
  image.release: eoan
  image.serial: "20200129"
  image.type: squashfs
  image.version: "19.10"
  raw.idmap: |-
    uid 1000 1000
    gid 1000 1000
  volatile.base_image: 77866cd160e953f29064754b487e9a6a06e857d1a3882cc7996f6e5c659e3d37
  volatile.eth0.hwaddr: 00:16:3e:0e:f4:47
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":1001001,"Nsid":1001,"Maprange":999998999},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":false,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1001001,"Nsid":1001,"Maprange":999998999}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":1001001,"Nsid":1001,"Maprange":999998999},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":false,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1001001,"Nsid":1001,"Maprange":999998999}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":1001001,"Nsid":1001,"Maprange":999998999},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":false,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1001001,"Nsid":1001,"Maprange":999998999}]'
  volatile.last_state.power: STOPPED
devices:
  eth0:
    ipv4.address: 10.0.3.15
    nictype: bridged
    parent: lxdbr0
    type: nic
  hostfs:
    path: /mnt/hostfs
    source: /home/dv/projects/python/notebooks
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
