### ISSUE TITLE
Port forwarding 1935

### ISSUE THREAD

**Issue by ostap-mykhaylyak** [lxc/lxd#6928]
Hi,

port forwarding does not work properly for the RTMP protocol, while there is no problem over HTTP

```
# lxc version
Client version: 3.0.3
Server version: 3.0.3
# lxd version
3.0.3
```

```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20200218)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20200218"
  image.version: "18.04"
  volatile.base_image: 8c4e87e53c024e0449003350f0b0626b124b68060b73c0a7ad9547670e00d4b3
  volatile.eth0.hwaddr: 00:16:3e:5c:fd:46
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  myport1935:
    connect: tcp:127.0.0.1:1935
    listen: tcp:0.0.0.0:1935
    type: proxy
  myport8080:
    connect: tcp:127.0.0.1:8080
    listen: tcp:0.0.0.0:8080
    type: proxy
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

to make it work it was necessary to configure forward with iptables:

`iptables -t nat -A PREROUTING -p tcp -i ens160 --dport 1935 -j DNAT --to-destination 10.116.184.247:1935
`

```
root@nginx-rtmp:~# nginx -V
nginx version: nginx/1.17.8
built by gcc 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
built with OpenSSL 1.1.1  11 Sep 2018
TLS SNI support enabled
configure arguments: --with-http_ssl_module --add-module=../nginx-rtmp-module
```
