### ISSUE TITLE
Unable to set rootfs size with VMs and ZFS storage

### ISSUE THREAD

**Issue by leopaul36** [lxc/lxd#6956]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 19.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.0.0-38-generic
   * LXC version: 3.21
   * LXD version: 3.21
   * Storage backend in use: zfs

# Issue description

I am not able to set the rootfs size through the VM configuration. It works properly with regular containers.

# Steps to reproduce

 1. `lxc init images:ubuntu/bionic bionic --vm`
 2. `lxc config edit bionic`
 3. `lxc start bionic`
 4. `lxc exec bionic -- df -h /`
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       3.8G  704M  3.1G  19% /
```

# Information to attach

- Config:

```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Ubuntu bionic amd64 (20200227_07:42)
  image.os: Ubuntu
  image.release: bionic
  image.serial: "20200227_07:42"
  image.type: disk-kvm.img
  volatile.base_image: 645a9c9b131187498fadf3351910b23de548eee2bffabbfb09f2000038c39720
devices:
  root:
    path: /
    pool: system
    size: 15GB
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
- Profile:
```
lxc profile show default
config: {}
description: Default LXD profile
devices:
  root:
    path: /
    pool: system
    type: disk
used_by:
- /1.0/instances/bionic
```
- Storage:
```
config:
  source: syspool/lxd
  volatile.initial_source: syspool/lxd
  zfs.pool_name: syspool/lxd
description: ""
name: system
driver: zfs
used_by:
- /1.0/images/091b1efac72f71fb68d16856d176611c8f2db8cf766872d50c9add06fe0ecc17
- /1.0/images/4cd63d064053a9c638bdfc2f97a93b88757982138f229053ba3598b21972c612
- /1.0/images/645a9c9b131187498fadf3351910b23de548eee2bffabbfb09f2000038c39720
- /1.0/profiles/default
- /1.0/virtual-machines/bionic
status: Created
locations:
- none
```

Thank you for your help.
