### ISSUE TITLE
lxc copy re-enables btrfs quotas

### ISSUE THREAD

**Issue by tchwpkgorg** [lxc/lxd#7029]
btrfs quotas are buggy and should not be used where stability is important. They cause serious performance penalty with snapshots and affect the stability negatively. btrfs developers and community recommend to have it disabled, unless you know what you're doing.

LXD re-enables btrfs quotas if user previously disabled them. This can cause service downtime on busy servers with snapshots, lots of containers and lots of reads and writes.

To reproduce, we'll first verify that it's LXD doing this:

- make sure the quotas are disabled:

`btrfs quota disable /var/snap/lxd/common/lxd `

- verify it's really disabled - command exits with error:
```
# btrfs quota rescan /var/snap/lxd/common/lxd 
ERROR: quota rescan failed: Invalid argument
```

- snapshot the volume:
```
# btrfs subvolume snapshot testct1 testct1-clone
Create a snapshot of 'testct1' in './testct1-clone'
```

- now try quota rescan - it still fails, meaning, btrfs command does not re-enable the quotas by itself (expected):

```
# btrfs quota rescan /var/snap/lxd/common/lxd 
ERROR: quota rescan failed: Invalid argument
```

Now let's try "lxc copy":
```
# lxc copy testct1 testct1-enabled-quotas
```

- see if rescan works - it does (here complains that it's already running):
```
# btrfs quota rescan /var/snap/lxd/common/lxd 
ERROR: quota rescan failed: Operation now in progress
```

Please disable this behaviour and don't re-enable btrfs quotas if user disabled them. If user decided to disable the quotas, please respect the choice.

This caused stability issues on several of my servers and took me a while to find out why.

For the record, my current fix is the following cronjob - but I would appreciate if LXD was respecting user settings:

```
* * * * * root run-one btrfs quota disable /data/lxd
```

**Comment by tchwpkgorg** [comment]
BTW here is how it looks on my server when LXD decides to re-enable quotas and scan everything - pretty much anything touching btrfs filesystem can hang for hours in that state:

```
# ps auxf|grep " D "
root        605  4.0  0.0      0     0 ?        D    08:25   2:35  \_ [kworker/u257:3+]
root        606  3.0  0.0      0     0 ?        D    08:25   1:58  \_ [kworker/u257:4+]
root        778  0.0  0.0      0     0 ?        D    08:25   0:00  \_ [md0_raid1]
root       2342  1.3  0.0      0     0 ?        D    08:25   0:51  \_ [btrfs-transacti]
root       3999  0.0  0.0      0     0 ?        D    08:26   0:03  \_ [kworker/u260:4+]
root       4203  0.0  0.0      0     0 ?        D    08:26   0:03  \_ [kworker/u260:7+]
root       6883  0.4  0.0      0     0 ?        D    08:26   0:18  \_ [kworker/u256:7+]
root      17468  3.8  0.0      0     0 ?        D    08:26   2:26  \_ [kworker/u257:11]
root      17504  4.0  0.0      0     0 ?        D    08:26   2:36  \_ [kworker/u257:13]
root      28582  0.3  0.0      0     0 ?        D    08:28   0:13  \_ [kworker/u257:16]
root      29876  3.0  0.0      0     0 ?        D    08:28   1:50  \_ [kworker/u257:17]
root     115197  0.0  0.0      0     0 ?        D    08:38   0:01  \_ [kworker/u260:9+]
root      47184  0.0  0.0      0     0 ?        D    08:48   0:00  \_ [kworker/u259:5+]
root     126040  8.8  0.0      0     0 ?        D    09:17   1:04  \_ [kworker/u259:1+]
root     126298  0.0  0.0      0     0 ?        D    09:17   0:00  \_ [kworker/u258:2+]
root       2804  0.0  0.0      0     0 ?        D    09:25   0:00  \_ [kworker/u259:0+]
root       2806  0.0  0.0      0     0 ?        D    09:25   0:00  \_ [kworker/u258:4+]
root       2816  0.0  0.0      0     0 ?        D    09:25   0:00  \_ [kworker/u259:2+]
root       4006  0.4  0.0      0     0 ?        D    09:25   0:01  \_ [kworker/u257:9+]
root       4007  0.3  0.0      0     0 ?        D    09:25   0:00  \_ [kworker/u257:10]
root       4440  0.0  0.0      0     0 ?        D    09:25   0:00  \_ [kworker/u260:3+]
root       7500  0.1  0.0      0     0 ?        D    09:26   0:00  \_ [kworker/u259:3+]
root       8774  0.1  0.0      0     0 ?        D    09:27   0:00  \_ [kworker/u259:6+]
root       8775  0.1  0.0      0     0 ?        D    09:27   0:00  \_ [kworker/u259:7+]
root       9042  0.1  0.0      0     0 ?        D    09:27   0:00  \_ [kworker/u259:9+]
root       9043  0.0  0.0      0     0 ?        D    09:27   0:00  \_ [kworker/u259:10]
root       9895  0.0  0.0      0     0 ?        D    09:27   0:00  \_ [kworker/u260:5+]
root      10057  0.0  0.0      0     0 ?        D    09:27   0:00  \_ [kworker/u260:6+]
1000000   20612  0.0  0.0  34444   276 ?        D    09:30   0:00      |   \_ /usr/sbin/CRON -f
1000106    7618  0.5  0.0  63940 18360 ?        D    08:26   0:19          \_ nginx: worker process
1000000   20511  0.0  0.0  29012   276 ?        D    09:30   0:00      |   \_ /usr/sbin/CRON -f
root      20510  0.0  0.0  31324   284 ?        D    09:30   0:00      |   \_ /usr/sbin/CRON -f
1000999   10460  0.0  0.0  65480 26840 ?        D    09:28   0:00      |   |       \_ redis-server
1000000   20578  0.0  0.0   7268   228 ?        D    09:30   0:00      |   |       \_ CRON -f -l -L 15
1000106   12073  0.6  0.0  40488  9280 ?        D    08:26   0:23      |   \_ nginx: worker process
1000106   12074  2.0  0.0  42176 11056 ?        D    08:26   1:16      |   \_ nginx: worker process
1000106   12075  0.5  0.0  39012  7656 ?        D    08:26   0:20      |   \_ nginx: worker process
1000106   12077  0.2  0.0  39128  7700 ?        D    08:26   0:09      |   \_ nginx: worker process
1000106   12078  0.5  0.0  38848  7336 ?        D    08:26   0:20      |   \_ nginx: worker process
1000106   12079  0.5  0.0  38932  7524 ?        D    08:26   0:22      |   \_ nginx: worker process
1000106   12080  0.2  0.0  39056  7800 ?        D    08:26   0:09      |   \_ nginx: worker process
1000106   12081  0.6  0.0  38796  7272 ?        D    08:26   0:23      |   \_ nginx: worker process
```

A cron with "run-one btrfs quota disable /data/lxd" executed every minute also doesn't help much - because the command can run 10, 20, 30, 40... or more minutes to exit once everything hangs.

**Comment by tchwpkgorg** [comment]
One more:

```
# uptime
 09:32:48 up  1:07,  4 users,  load average: 167.47, 366.23, 545.04
```

**Comment by tchwpkgorg** [comment]
I think not only lxc copy enables it - but this gets enabled periodically.

Is this something that was added in LXD 3.22? Because over the past few days, several of my LXD servers started to show serious stability issues (IO basically blocked).

**Comment by stgraber** [comment]
Hmm, we shouldn't mess with quotas unless we're dealing with a volume that has a `size` limit applied to it.

Can you show `lxc config show --expanded testct1` to confirm there's nothing in there which would have us try to apply quotas?

**Comment by tchwpkgorg** [comment]
This isn't just lxc copy which re-enables the quotas. I've disabled them on several servers earlier today, and they were again enabled. I don't do lxc copy on these servers as they only have "static" containers. Interestingly, some servers did not re-enable the quotas.

Here is the requested info (name is different, also triggers re-enabling on btrfs quotas):

```
# lxc config show --expanded shard01c
architecture: x86_64
config:
  boot.autostart: "true"
  security.protection.delete: "true"
  volatile.base_image: 43a27fbda6f60753bf69437cddbfa1fee24e8294adcedf18fc49cbd7c8c65440
  volatile.eth0.host_name: vethe7c45862
  volatile.eth0.hwaddr: 00:16:3e:07:f5:c9
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: bridged
    parent: br-prod
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

Also:

```
# lxc storage list
+---------+-------------+--------+-----------+---------+
|  NAME   | DESCRIPTION | DRIVER |  SOURCE   | USED BY |
+---------+-------------+--------+-----------+---------+
| default |             | btrfs  | /data/lxd | 40      |
+---------+-------------+--------+-----------+---------+

# lxc storage show default
config:
  source: /data/lxd
  volatile.initial_source: /data/lxd
description: ""
name: default
driver: btrfs
used_by:
- /1.0/containers/TDv2-283c5947d3-2020-03-16-10-18-24
- /1.0/containers/TDv2-283c5947d3-2020-03-16-10-18-36
- /1.0/containers/TDv2-bbccf5b091-2020-03-16-10-15-50
(...)
status: Created
locations:
- none
```
