### ISSUE TITLE
Cannot start a container with "Function not implemented - Failed to send signal through pidfd" error

### ISSUE THREAD

**Issue by SleeplessSloth** [lxc/lxd#7048]
# Required information

 * Distribution: Arch Linux ARM
 * The output of "lxc info" or if that fails:
```
> lxc info --show-log pihole
Name: pihole
Location: none
Remote: unix://
Architecture: armv7l
Created: 2020/03/06 22:28 UTC
Status: Stopped
Type: container
Profiles: default

Log:

lxc pihole 20200317173257.508 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/unified//lxc.payload/pihole"
lxc pihole 20200317173257.509 ERROR    cgfsng - cgroups/cgfsng.c:container_create_path_for_hierarchy:1319 - Failed to create cgroup "/sys/fs/cgroup/unified//lxc.payload/pihole"
lxc pihole 20200317173257.509 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_payload_create:1456 - Failed to create cgroup "/sys/fs/cgroup/unified//lxc.payload/pihole"
lxc pihole 20200317173257.509 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/unified//lxc.payload/pihole-1"
lxc pihole 20200317173257.509 ERROR    cgfsng - cgroups/cgfsng.c:container_create_path_for_hierarchy:1319 - Failed to create cgroup "/sys/fs/cgroup/unified//lxc.payload/pihole-1"
lxc pihole 20200317173257.509 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_payload_create:1456 - Failed to create cgroup "/sys/fs/cgroup/unified//lxc.payload/pihole-1"
lxc pihole 20200317173257.509 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/unified//lxc.payload/pihole-2"
lxc pihole 20200317173257.509 ERROR    cgfsng - cgroups/cgfsng.c:container_create_path_for_hierarchy:1319 - Failed to create cgroup "/sys/fs/cgroup/unified//lxc.payload/pihole-2"
lxc pihole 20200317173257.509 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_payload_create:1456 - Failed to create cgroup "/sys/fs/cgroup/unified//lxc.payload/pihole-2"
lxc pihole 20200317173257.509 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/unified//lxc.payload/pihole-3"
lxc pihole 20200317173257.509 ERROR    cgfsng - cgroups/cgfsng.c:container_create_path_for_hierarchy:1319 - Failed to create cgroup "/sys/fs/cgroup/unified//lxc.payload/pihole-3"
lxc pihole 20200317173257.509 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_payload_create:1456 - Failed to create cgroup "/sys/fs/cgroup/unified//lxc.payload/pihole-3"
lxc pihole 20200317173257.509 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/unified//lxc.payload/pihole-4"
lxc pihole 20200317173257.509 ERROR    cgfsng - cgroups/cgfsng.c:container_create_path_for_hierarchy:1319 - Failed to create cgroup "/sys/fs/cgroup/unified//lxc.payload/pihole-4"
lxc pihole 20200317173257.509 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_payload_create:1456 - Failed to create cgroup "/sys/fs/cgroup/unified//lxc.payload/pihole-4"
lxc pihole 20200317173257.514 ERROR    start - start.c:proc_pidfd_open:1644 - Function not implemented - Failed to send signal through pidfd
lxc pihole 20200317173257.535 ERROR    conf - conf.c:lxc_map_ids:3009 - newuidmap failed to write mapping "": newuidmap 21442 0 1000000 1000000000
lxc pihole 20200317173257.535 ERROR    start - start.c:lxc_spawn:1798 - Failed to set up id mapping.
lxc pihole 20200317173257.535 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:873 - Received container state "ABORTING" instead of "RUNNING"
lxc pihole 20200317173257.538 ERROR    start - start.c:__lxc_start:2036 - Failed to spawn container "pihole"
lxc pihole 20200317173257.971 ERROR    conf - conf.c:lxc_map_ids:3009 - newuidmap failed to write mapping "": newuidmap 21456 0 1000000 1000000000 1000000000 0 1
lxc pihole 20200317173257.971 ERROR    conf - conf.c:userns_exec_1:4410 - Error setting up {g,u}id mappings for child process "21456"
lxc pihole 20200317173257.973 WARN     cgfsng - cgroups/cgfsng.c:cgfsng_payload_destroy:1112 - Failed to destroy cgroups
lxc 20200317173257.979 WARN     commands - commands.c:lxc_cmd_rsp_recv:135 - Connection reset by peer - Failed to receive response for command "get_state"
```
   * Kernel version: `4.19.106-1-ARCH #1 SMP PREEMPT Tue Mar 3 01:58:36 UTC 2020 armv7l GNU/Linux`
   * LXC version: `3.2.1-2`
   * LXD version: `3.21-2`
   * Storage backend in use: `dir`

# Issue description

Can't start a container. Fails with "Function not implemented - Failed to send signal through pidfd" error.
I've tried different images/distros but to no avail

# Steps to reproduce

 1. Create a container
 2. Start a container

# Information to attach
 - Container configuration (`lxc config show NAME --expanded`)
```
architecture: armv7l
config:
  image.architecture: armhf
  image.description: Debian buster armhf (20200306_05:50)
  image.os: Debian
  image.release: buster
  image.serial: "20200306_05:50"
  image.type: squashfs
  volatile.base_image: 74890e70e1b2f163cda786296ecc20a4dde710935bf3fbfaddbfb33321bc5693
  volatile.eth0.hwaddr: 00:16:3e:c4:c6:8d
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: STOPPED
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 - [Output of the client with --debug](https://pastebin.com/5euu8u4u)
 - [Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)](https://pastebin.com/Vdsg8vFQ)

I have posted this issue to [the lxc bug tracker](https://github.com/lxc/lxc/issues/3276) since I assumed that was a back-end bug but they've asked me to post here instead
