### ISSUE TITLE
Unable to delete a VM because the filesystem is still in use [LVM storage backend]

### ISSUE THREAD

**Issue by falstaff1288** [lxc/lxd#7135]
# Required information

 * Distribution: ArchLinux
 * Distribution version: latest (as of Apr 04 2020)
 * The output of "lxc info" or if that fails:
```
config: {}
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 4.0.0
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.30-1-lts
  lxc_features:
    cgroup2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    seccomp_notify: "true"
  project: default
  server: lxd
  server_clustered: false
  server_pid: 1436
  server_version: 4.0.0
  storage: btrfs | lvm
  storage_version: 5.4.1 | 2.02.187(2) (2020-03-24) / 1.02.170 (2020-03-24) / 4.41.0

```

# Issue description
Getting the following error when trying to delete a VM:

```
$ lxc delete demo
Error: Error deleting storage volume: Error removing LVM logical volume: Failed to run: lvremove -f /dev/lvmbased/containers_demo: Logical volume lvmbased/containers_demo contains a filesystem in use.
```
More info about the storage
```
$ lxc storage list
+----------+-------------+--------+--------------------------------+---------+
|   NAME   | DESCRIPTION | DRIVER |             SOURCE             | USED BY |
+----------+-------------+--------+--------------------------------+---------+
| default  |             | btrfs  | /var/lib/lxd/disks/default.img | 0       |
+----------+-------------+--------+--------------------------------+---------+
| lvmbased |             | lvm    | lvmbased                       | 9       |
+----------+-------------+--------+--------------------------------+---------+
[denis@T450s prometheus-demo-site]$ lxc storage show lvmbased
config:
  lvm.thinpool_name: LXDThinPool
  lvm.vg_name: lvmbased
  source: lvmbased
  volatile.initial_source: /dev/sda4
description: ""
name: lvmbased
driver: lvm
used_by:
- /1.0/containers/demo
- /1.0/containers/gitlab
- /1.0/images/29227944dc01396694237f08541d3135cab6b87a0b862ea0f2006c666d2c1ada
- /1.0/images/6ba50a93e883cf5ae71a4a727f55886c9857c4d74c8736104905e2513ae5cd2e
- /1.0/images/76f574054abcdec9c3a4f2c3177c370a3c5906217fe1648bde326b9937b8553b
- /1.0/images/7f47520c4613e56199c79ac660fc30c9a83352f8b78c465e57461356610991c0
- /1.0/images/9b3a342b12a16deabfce2e0444a0ac4c2245b108743345f3c3eed632c4f0e907
- /1.0/images/b2eb08cbfada3ea1301a9ee973fba91aef8a588fee56fb70d084b6306cb741a0
- /1.0/profiles/default
status: Created
locations:
- none
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [X] Container log
```
$ lxc info demo
Name: demo
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/04/04 04:39 UTC
Status: Stopped
Type: container
Profiles: default
[denis@T450s prometheus-demo-site]$ lxc info demo --show-log
Name: demo
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/04/04 04:39 UTC
Status: Stopped
Type: container
Profiles: default

Log:

lxc demo 20200404155958.296 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1136 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.demo"
lxc demo 20200404155958.297 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1136 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.demo"
lxc demo 20200404155958.328 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1445 - No such file or directory - Failed to fchownat(17, memory.oom.group, 65536, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )
```
 - [X] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
```
location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
    user: ""
  level: dbug
  message: Handling
timestamp: "2020-04-04T19:28:11.143201432-04:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/instances/demo
    user: ""
  level: dbug
  message: Handling
timestamp: "2020-04-04T19:28:11.145460945-04:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/events
    user: ""
  level: dbug
  message: Handling
timestamp: "2020-04-04T19:28:11.148272399-04:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'New event listener: 402a06f9-0a9e-43c5-a5e0-decc5378a4d5'
timestamp: "2020-04-04T19:28:11.148679906-04:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: DELETE
    url: /1.0/instances/demo
    user: ""
  level: dbug
  message: Handling
timestamp: "2020-04-04T19:28:11.149008623-04:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'New task Operation: 9f78f717-8634-4925-86b1-a5d8bb8e33f2'
timestamp: "2020-04-04T19:28:11.154907889-04:00"
type: logging


location: none
metadata:
  context:
    created: 2020-04-04 00:39:22.503089804 -0400 EDT
    ephemeral: "false"
    name: demo
    project: default
    used: 2020-04-04 11:59:58.233418938 -0400 EDT
  level: info
  message: Deleting container
timestamp: "2020-04-04T19:28:11.155774677-04:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'Started task operation: 9f78f717-8634-4925-86b1-a5d8bb8e33f2'
timestamp: "2020-04-04T19:28:11.155518629-04:00"
type: logging


location: none
metadata:
  class: task
  created_at: "2020-04-04T19:28:11.150715772-04:00"
  description: Deleting container
  err: ""
  id: 9f78f717-8634-4925-86b1-a5d8bb8e33f2
  location: none
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/demo
  status: Running
  status_code: 103
  updated_at: "2020-04-04T19:28:11.150715772-04:00"
timestamp: "2020-04-04T19:28:11.156414577-04:00"
type: operation


location: none
metadata:
  class: task
  created_at: "2020-04-04T19:28:11.150715772-04:00"
  description: Deleting container
  err: ""
  id: 9f78f717-8634-4925-86b1-a5d8bb8e33f2
  location: none
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/demo
  status: Pending
  status_code: 105
  updated_at: "2020-04-04T19:28:11.150715772-04:00"
timestamp: "2020-04-04T19:28:11.155478925-04:00"
type: operation


location: none
metadata:
  context:
    driver: lvm
    instance: demo
    pool: lvmbased
    project: default
  level: dbug
  message: DeleteInstance started
timestamp: "2020-04-04T19:28:11.158999489-04:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/operations/9f78f717-8634-4925-86b1-a5d8bb8e33f2
    user: ""
  level: dbug
  message: Handling
timestamp: "2020-04-04T19:28:11.158722241-04:00"
type: logging


location: none
metadata:
  context:
    driver: lvm
    instance: demo
    pool: lvmbased
    project: default
    volName: demo
  level: dbug
  message: Deleting instance volume
timestamp: "2020-04-04T19:28:11.159679969-04:00"
type: logging


location: none
metadata:
  context:
    driver: lvm
    instance: demo
    pool: lvmbased
    project: default
  level: dbug
  message: DeleteInstance finished
timestamp: "2020-04-04T19:28:23.777966276-04:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'Failure for task operation: 9f78f717-8634-4925-86b1-a5d8bb8e33f2: Error
    deleting storage volume: Error removing LVM logical volume: Failed to run: lvremove
    -f /dev/lvmbased/containers_demo: Logical volume lvmbased/containers_demo contains
    a filesystem in use.'
timestamp: "2020-04-04T19:28:23.778064057-04:00"
type: logging


location: none
metadata:
  class: task
  created_at: "2020-04-04T19:28:11.150715772-04:00"
  description: Deleting container
  err: 'Error deleting storage volume: Error removing LVM logical volume: Failed to
    run: lvremove -f /dev/lvmbased/containers_demo: Logical volume lvmbased/containers_demo
    contains a filesystem in use.'
  id: 9f78f717-8634-4925-86b1-a5d8bb8e33f2
  location: none
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/demo
  status: Failure
  status_code: 400
  updated_at: "2020-04-04T19:28:11.150715772-04:00"
timestamp: "2020-04-04T19:28:23.779760138-04:00"
type: operation


location: none
metadata:
  context: {}
  level: dbug
  message: 'Event listener finished: 402a06f9-0a9e-43c5-a5e0-decc5378a4d5'
timestamp: "2020-04-04T19:28:23.783860261-04:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'Disconnected event listener: 402a06f9-0a9e-43c5-a5e0-decc5378a4d5'
timestamp: "2020-04-04T19:28:23.784314786-04:00"
type: logging
```
