### ISSUE TITLE
LXD VM: Multiple PCIe slots per PCIe Device Types

### ISSUE THREAD

**Issue by rafaeldtinoco** [lxc/lxd#7175]
# Required information

 * Distribution: Ubuntu 19.10

```
  driver: lxc
  driver_version: 4.0.1
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.3.0-46-generic
  lxc_features:
    cgroup2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    seccomp_notify: "true"
  os_name: Ubuntu
  os_version: "19.10"
  project: default
  server: lxd
  server_clustered: false
  server_name: workstation
  server_pid: 1680296
  server_version: 4.0.0
  storage: dir
  storage_version: "1"
```

# Issue description

Having up to 4 network interfaces in a profile used by a virtual machine:

```
05:00.0 Ethernet controller: Red Hat, Inc. Virtio network device (rev 01)
06:00.0 Ethernet controller: Red Hat, Inc. Virtio network device (rev 01)
07:00.0 Ethernet controller: Red Hat, Inc. Virtio network device (rev 01)
08:00.0 Ethernet controller: Red Hat, Inc. Virtio network device (rev 01)
```

If I declare more network interfaces in the same profile:

```
Error: Failed to run: /snap/lxd/current/bin/lxd forklimits limit=memlock:unlimited:unlimited fd=3 fd=4 fd=5 fd=6 fd=7 fd=8 -- /snap/lxd/14503/bin/qemu-system-x86_64 -S -name cluster01 -uuid cd065583-67c4-44b3-a712-53d5682665df -daemonize -cpu host -nographic -serial chardev:console -nodefaults -no-reboot -no-user-config -sandbox on,obsolete=deny,elevateprivileges=allow,spawn=deny,resourcecontrol=deny -readconfig /var/snap/lxd/common/lxd/logs/cluster01/qemu.conf -pidfile /var/snap/lxd/common/lxd/logs/cluster01/qemu.pid -D /var/snap/lxd/common/lxd/logs/cluster01/qemu.log -chroot /var/snap/lxd/common/lxd/virtual-machines/cluster01 -runas lxd: : exit status 1
Try `lxc info --show-log cluster01` for more info

qemu-system-x86_64:/var/snap/lxd/common/lxd/logs/cluster01/qemu.conf:349: Property 'pcie-root-port.addr' doesn't take value '0x2.0x8'
```

# Steps to reproduce

```
in a profile.yaml file:

  devices:
    lxdbr0:
      nictype: bridged
      parent: lxdbr0
      type: nic
+   lxdint01:
+     nictype: bridged
+     parent: lxdint01
+     type: nic
+   lxdint02:
+     nictype: bridged
+     parent: lxdint02
+     type: nic
+   lxdiscsi01:
+     nictype: bridged
+     parent: lxdiscsi01
+     type: nic
+   lxdiscsi02:
+     nictype: bridged
+     parent: lxdiscsi02
+     type: nic
+   # lxdpub01:
+   #  nictype: bridged
+   #  parent: lxdpub01
+   #  type: nic
+   # lxdpub02:
+   #   nictype: bridged
+   #   parent: lxdpub02
+   #   type: nic
```

lxc profile edit <profile> < profile.yaml

# Information to attach

ERROR: Property 'pcie-root-port.addr' doesn't take value '0x2.0x8'

This is the nic (from qemu.conf file) that does not work:

```
...

[device "qemu_pcie1"]
driver = "pcie-root-port"
port = "0x10"
chassis = "1"
bus = "pcie.0"
multifunction = "on"
addr = "0x2"

...

# Network card ("lxdiscsi02" device)
[netdev "lxd_lxdiscsi02"]
type = "tap"
vhost = "on"
ifname = "tap4f8597cc"
script = "no"
downscript = "no"

[device "qemu_pcie9"]
driver = "pcie-root-port"
port = "0x18"
chassis = "9"
bus = "pcie.0"
addr = "0x2.0x8" <- 

[device "dev-lxd_lxdiscsi02"]
driver = "virtio-net-pci"
netdev = "lxd_lxdiscsi02"
mac = "00:16:3e:b3:cc:50"
bus = "qemu_pcie9"
addr = "0x0"
bootindex = "7"
```

It looks that this happens because addNetDevConfig() - driver_qemu.go - uses nicIndex from generateQemuConfigFile() and it does not take in consideration PCIe emulation limits from the q35 chipset.

From the VM:

```
00:02.0 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.1 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.2 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.3 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.4 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.5 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.6 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:02.7 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
```

looks like a 9th virtual function for the 02 slot is out of question here.

Adding all virtual PCI devices as functions for the same PCIe slot (00:02) seems fragile, no ? nicIndex++ (generateQemuConfigFile()) and hardcoded pcieAddr "4 + nicIndex" in addNetDevConfig() (because of balloon, rndgen, vsock) allows up to 4 extra PCI devices, only, attached to the VM, correct ?

From q35 specs:

https://github.com/qemu/qemu/blob/master/docs/pcie.txt

If my interpretation is right, then, not to put too much burden in the VM feature development:

- Shouldn't qemu driver use, for now, use 1 PCIe Root Port (ioh3420) *per device type* ? It would allow up to 8 functions for *that device type* and wouldn't change the logic too much.

- It seems that not adding switches to this logic would improve scalability because no PCI slots would be consumed (as q35 PCIe emulation supports only one PCI domain).
