### ISSUE TITLE
LXD VM: cloud images for VIRTUAL MACHINES should use ClientIdentifier=mac

### ISSUE THREAD

**Issue by rafaeldtinoco** [lxc/lxd#7180]
# Required information

Ubuntu Eoan

```
  driver: lxc
  driver_version: 4.0.1
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.3.0-46-generic
  lxc_features:
    cgroup2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    seccomp_notify: "true"
  os_name: Ubuntu
  os_version: "19.10"
  project: default
  server: lxd
  server_clustered: false
  server_name: workstation
  server_pid: 2717202
  server_version: 4.0.0
  storage: dir
  storage_version: "1"
```

# Issue description

After cloning a VM I ended up having the same IP address for the cloned VM:

```
rafaeldtinoco@workstation:~$ lxc list -c ns4t cluster01
+-----------+---------+-------------------------+-----------------+
|   NAME    |  STATE  |          IPV4           |      TYPE       |
+-----------+---------+-------------------------+-----------------+
| cluster01 | RUNNING | 10.250.97.142 (enp5s0)  | VIRTUAL-MACHINE |
|           |         | 10.250.94.166 (iscsi01) |                 |
|           |         | 10.250.93.100 (iscsi02) |                 |
+-----------+---------+-------------------------+-----------------+
rafaeldtinoco@workstation:~$ lxc list -c ns4t storage
+---------+---------+------------------------+-----------------+
|  NAME   |  STATE  |          IPV4          |      TYPE       |
+---------+---------+------------------------+-----------------+
| storage | RUNNING | 10.250.97.142 (enp5s0) | VIRTUAL-MACHINE |
|         |         | 10.250.94.99 (iscsi01) |                 |
|         |         | 10.250.93.99 (iscsi02) |                 |
+---------+---------+------------------------+-----------------+
```

# Steps to reproduce

Clone a VM and make sure netplan io is configured with DHCP4 for a single interface, for example.

first machine

```
$ cat /etc/netplan/50-cloud-init.yaml
network:
    ethernets:
        enp5s0:
            dhcp4: true
            match:
                macaddress: 00:16:3e:af:c4:d6
            set-name: enp5s0
    version: 2
    renderer: networkd
```

```
(k)root@cluster01:.../systemd/netif/leases$ cat 2
# This is private data. Do not parse.
ADDRESS=10.250.97.142
NETMASK=255.255.255.0
ROUTER=10.250.97.1
SERVER_ADDRESS=10.250.97.1
NEXT_SERVER=10.250.97.1
BROADCAST=10.250.97.255
T1=1800
T2=3150
LIFETIME=3600
DNS=10.250.97.1
DOMAINNAME=lxd
HOSTNAME=cluster01
CLIENTID=ff49721f4700020000ab11df4ace466968c6ba
```

second machine

```
$ cat /etc/netplan/50-cloud-init.yaml
network:
    ethernets:
        enp5s0:
            dhcp4: true
            match:
                macaddress: 00:16:3e:82:48:57
            set-name: enp5s0
    version: 2
    renderer: networkd
```

```
(k)root@storage:.../systemd/netif/leases$ cat 2
# This is private data. Do not parse.
ADDRESS=10.250.97.142
NETMASK=255.255.255.0
ROUTER=10.250.97.1
SERVER_ADDRESS=10.250.97.1
NEXT_SERVER=10.250.97.1
BROADCAST=10.250.97.255
T1=1800
T2=3150
LIFETIME=3600
DNS=10.250.97.1
DOMAINNAME=lxd
HOSTNAME=storage
CLIENTID=ff49721f4700020000ab11df4ace466968c6ba
```

# Information to attach

I believe that both machines ended up with the same CLIENTID because the systemd-networkd default is duid and not "mac". When I changed netplan.io to have:

`dhcp-identifier: mac`

Both got different IPs:

```
rafaeldtinoco@workstation:~$ lxc list -c ns4t cluster01
+-----------+---------+-------------------------+-----------------+
|   NAME    |  STATE  |          IPV4           |      TYPE       |
+-----------+---------+-------------------------+-----------------+
| cluster01 | RUNNING | 10.250.97.123 (enp5s0)  | VIRTUAL-MACHINE |
|           |         | 10.250.94.166 (iscsi01) |                 |
|           |         | 10.250.93.100 (iscsi02) |                 |
+-----------+---------+-------------------------+-----------------+
rafaeldtinoco@workstation:~$ lxc list -c ns4t storage
+---------+---------+------------------------+-----------------+
|  NAME   |  STATE  |          IPV4          |      TYPE       |
+---------+---------+------------------------+-----------------+
| storage | RUNNING | 10.250.97.143 (enp5s0) | VIRTUAL-MACHINE |
|         |         | 10.250.94.99 (iscsi01) |                 |
|         |         | 10.250.93.99 (iscsi02) |                 |
+---------+---------+------------------------+-----------------+
```

Perhaps dnsmasq in LXD should ignore clientids ? Or there should be a way to *enforce* netplan to always use mac for clientid ? Or something like it.
