### ISSUE TITLE
LXD VM: arm64 virtual machine stuck in UEFI

### ISSUE THREAD

**Issue by rafaeldtinoco** [lxc/lxd#7191]
# Required information

Ubuntu Eoan

```
  driver: lxc
  driver_version: 4.0.1
  firewall: xtables
  kernel: Linux
  kernel_architecture: aarch64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.0.0-30-generic
  lxc_features:
    cgroup2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    seccomp_notify: "true"
  os_name: Ubuntu
  os_version: "19.10"
  project: default
  server: lxd
  server_clustered: false
  server_name: firewall
  server_pid: 14966
  server_version: 4.0.0
  storage: zfs
  storage_version: 0.7.12-1ubuntu5
```

# Issue description

The just created VM won't pass UEFI menu.

# Steps to reproduce

$ lxc image ubuntu-daily:focal arm64 --vm

$ lxc console arm64

```
BdsDxe: loading Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Scsi(0x0,0x1)
BdsDxe: failed to load Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Scsi(0x0,0x1): Access Denied

>>Start PXE over IPv4.
  PXE-E16: No valid offer received.
BdsDxe: failed to load Boot0004 "UEFI PXEv4 (MAC:00163E333650)" from PciRoot(0x0)/Pci(0x2,0x4)/Pci(0x0,0x0)/MAC(00163E333650,0x1)/IPv4(0.0.0.0,0x0,DHCP,0.0.0.0,0.0.0.0,0.0.0.0): Not Found

>>Start HTTP Boot over IPv4.....
  Error: Could not retrieve NBP file size from HTTP server.

  Error: Server response timeout.
BdsDxe: failed to load Boot0005 "UEFI HTTPv4 (MAC:00163E333650)" from PciRoot(0x0)/Pci(0x2,0x4)/Pci(0x0,0x0)/MAC(00163E333650,0x1)/IPv4(0.0.0.0,0x0,DHCP,0.0.0.0,0.0.0.0,0.0.0.0)/Uri(): Not Found
BdsDxe: failed to load Boot0002 "UEFI Misc Device" from VenHw(93E34C7E-B50E-11DF-9223-2443DFD72085,00): Not Found
BdsDxe: loading Boot0003 "EFI Internal Shell" from Fv(64074AFE-340A-4BE6-94BA-91B5B4D0F71E)/FvFile(7C04A583-9E3E-4F1C-AD65-E05268D0B4D1)
BdsDxe: starting Boot0003 "EFI Internal Shell" from Fv(64074AFE-340A-4BE6-94BA-91B5B4D0F71E)/FvFile(7C04A583-9E3E-4F1C-AD65-E05268D0B4D1)

UEFI Interactive Shell v2.2

EDK II

UEFI v2.70 (EDK II, 0x00010000)

Mapping table

      FS0: Alias(s):HD0a1p:;BLK2:

          PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Scsi(0x0,0x1)/HD(15,GPT,20488E2B-AD48-468D-8C32-DFFD852592B5,0x800,0x31801)

     BLK3: Alias(s):

          VenHw(93E34C7E-B50E-11DF-9223-2443DFD72085,00)

     BLK0: Alias(s):

          PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Scsi(0x0,0x1)

     BLK1: Alias(s):

          PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Scsi(0x0,0x1)/HD(1,GPT,39B14FCF-294A-4F53-AF07-14DF4CECF791,0x32800,0x4337DF)





Press ESC in 1 seconds to skip startup.nsh or any other key to continue.

Shell>

```

$ lxc init images:ubuntu/focal arm64vm --vm 

$ lxc console arm64vm

```
BdsDxe: loading Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Scsi(0x0,0x1)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Scsi(0x0,0x1)


Synchronous Exception at 0x000000007841C4AC


Synchronous Exception at 0x000000007841C4AC
```

# Information to attach

Machine: SynQuacer E-series DeveloperBox
https://www.96boards.org/product/developerbox/
