### ISSUE TITLE
Proxy does not forward the traffic internally to the container

### ISSUE THREAD

**Issue by tchwpkgorg** [lxc/lxd#7205]
Suppose we have this network:

```
# lxc network show lxdbr0
config:
  ipv4.address: 10.188.132.1/24
  ipv4.nat: "true"
```

And container is using this config:

```
devices:
  eth0:
    ipv4.address: 10.188.132.56
    nictype: bridged
    parent: lxdbr0
    type: nic
  proxy-http:
    connect: tcp:10.188.132.56:80
    listen: tcp:PUBLIC-IP:80
    nat: "true"
    type: proxy
```

Let's say that PUBLIC-IP IP address is mapped to "example.com" in DNS.

When we enter the container and try to connect to "example.com" (to PUBLIC-IP), it times out:

```
# curl -v example.com
* Rebuilt URL to: PUBLIC-IP/
*   Trying PUBLIC-IP...
* TCP_NODELAY set
```

A workaround is to add "10.188.132.56 example.com" mapping in the hosts file in the container, but it would be great if iptables rules were passing such traffic transparently (also between the containers).
