### ISSUE TITLE
lxc cannot push file

### ISSUE THREAD

**Issue by microcoder** [lxc/lxd#7215]
# Required information

 * Distribution: MANJARO
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.6.3-2-MANJARO
   * LXC version: 4.0.0
   * LXD version: 4.0.0
   * Storage backend in use: btrfs

# Issue description

I run next command

```
lxc file push /mnt/work/backups/lxd/backup_lxd_04.04.2020_1344.tar.zst jupyter/home/jupyter
```

After copying the file complete I get the Error:

```
Pushing /mnt/work/backups/lxd/backup_lxd_04.04.2020_1344.tar.zst to jupyter/home/jupyter: 100% (1.91GB/s)
Error: Path already exists as a directory: File too large
```

`jupyter` it is identification of the container and container user which have dir `/home/jupyter`

File which I copy have size 441MB. The container use **root disk** which use pool **hddpool**:

```
lxc config show jupyter --expanded

...
devices:
  eth0:
    ipv4.address: 10.0.5.10
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  hostfs:
    path: /mnt/hostfs
    source: /home/dv/projects/python/notebooks
    type: disk
  root:
    path: /
    pool: hddpool
    type: disk
```

The storage pool have space:

```
xc storage info hddpool
info:
  description: ""
  driver: btrfs
  name: hddpool
  space used: 836.31MB
  total space: 10.00GB
used by:
  containers:
  - jupyter
  images:
  - ebd565585223487526ddb3607f5156e875c15a89e21b61ef004132196da6a0a3
  profiles:
  - hddroot
```

Why I cannot copy file to container when storage  pool have enough free space?

```
lxc info jupyter

Name: jupyter
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/04/17 09:08 UTC
Status: Running
Type: container
Profiles: default, hddroot
Pid: 212299
Ips:
  eth0: inet    10.0.5.10       veth7b6c89b7
  eth0: inet6   fe80::216:3eff:fe37:c357        veth7b6c89b7
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 5
  Disk usage:
    root: 801.28MB
  CPU usage:
    CPU usage (in seconds): 1325
  Memory usage:
    Memory (current): 90.60MB
  Network usage:
    eth0:
      Bytes received: 92.40MB
      Bytes sent: 1.87MB
      Packets received: 62433
      Packets sent: 26394
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
```
