### ISSUE TITLE
Make NAT proxy mode work with wildcards listen addresses

### ISSUE THREAD

**Issue by tchwpkgorg** [lxc/lxd#7221]
On a server/host with a static IP, I would use a mapping like follows for a proxy:

```
  eth0:
    ipv4.address: 10.194.74.149
    ipv6.address: fd42:775d:eec4:b58a:216:3eff:fe80:46d7
    nictype: bridged
    parent: lxdbr0
    type: nic
  proxy-http-ipv4:
    connect: tcp:10.194.74.149:80
    listen: tcp:192.168.1.14:80
    nat: "true"
    type: proxy
  proxy-http-ipv6:
    connect: tcp:[fd42:775d:eec4:b58a:216:3eff:fe80:46d7]:80
    listen: tcp:[2405:6580:3240:0:e054:650f:561a:8]:80
    nat: "true"
    type: proxy
```

With it, I can do these from external, and they will be passed to a container:

```
curl -v 192.168.1.14
curl -v [2405:6580:3240:0:e054:650f:561a:8]
```

However, what if host's external IP may change from time to time? How to specify a "catchall IP" (or, any IP on a given interface)?

I've tried using:

```
    listen: tcp:0.0.0.0:80

    listen: tcp:[::]:80
```

but then, these don't pass the traffic to the container. Using lxd 4.0.
