### ISSUE TITLE
LVM containers cannot be deleted if other container with same prefix exist

### ISSUE THREAD

**Issue by keestux** [lxc/lxd#7335]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
```
  driver: lxc
  driver_version: 4.0.2
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-29-generic
  lxc_features:
    cgroup2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    seccomp_notify: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: true
  server_name: ijssel
  server_pid: 1900
  server_version: 4.0.1
  storage: lvm
  storage_version: 2.02.176(2) (2017-11-03) / 1.02.145 (2017-11-03) / 4.41.0
```

# Issue description

A container using lvm storage cannot be deleted if there is another container has a name prefix that matches that name.

# Steps to reproduce

```
root@rapper:~# lxc init images:ubuntu/bionic/amd64 -p pool2 test04-second
Creating test04-second
root@rapper:~# lxc init images:ubuntu/bionic/amd64 -p pool2 test04
Creating test04
root@rapper:~# lxc delete test04
Error: Error deleting storage volume: Cannot remove a volume that has snapshots
```
