### ISSUE TITLE
sqlite3 makes lxd to segfault on s390x using latest lxd from repo

### ISSUE THREAD

**Issue by rafaeldtinoco** [lxc/lxd#7345]
#6532 Required information

 * Distribution: Focal
 * Distribution version: 20.04 

```
  driver: lxc
  driver_version: 4.0.2
  firewall: xtables
  kernel: Linux
  kernel_architecture: s390x
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "true"
    uevent_injection: "true"
    unpriv_fscaps: "false"
  kernel_version: 5.4.0-31-generic
  lxc_features:
    cgroup2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    seccomp_notify: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: mainframe
  server_pid: 164910
  server_version: "4.1"
  storage: dir | zfs
  storage_version: 1 | 0.8.3-1ubuntu12
```

# Issue description

Able to create the first container and upgrade it with cloud-init template. After the initial reboot I get a LXD segfault on s390x architecture:

```
rafaeldtinoco@mainframe:~$ sudo -E PATH=$PATH LD_LIBRARY_PATH=$LD_LIBRARY_PATH $GOPATH/bin/lxd --group sudo
WARN[05-10|19:54:12]  - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored 
WARN[05-10|19:54:12]  - Couldn't find the CGroup memory swap accounting, swap limits will be ignored 
Segmentation fault
```

# Steps to reproduce

To follow README.md on s390x architecture, install a container and try to restart it.

# Information to attach

GDB:

```
Thread 23 "lxd" received signal SIGSEGV, Segmentation fault.
0x000003fffdc1ecb4 in sqlite3VdbeRecordUnpack (pKeyInfo=0x3ff905a1930, nKey=0, pKey=0x5b00000000000001, p=p@entry=0x3ff907bb930) at /home/rafaeldtinoco/work/sources/upstream/lxd/deps/sqlite/src/vdbeaux.c:3964
3964	  idx = getVarint32(aKey, szHdr);

Thread 23 "lxd" received signal SIGSEGV, Segmentation fault.
runtime.raise () at /usr/lib/go-1.13/src/runtime/sys_linux_s390x.s:142
```

```
(gdb) bt -full
#0  runtime.raise () at /usr/lib/go-1.13/src/runtime/sys_linux_s390x.s:142
No locals.
#1  0x000000000105ef16 in runtime.raisebadsignal (sig=11, c=0x3fff8107190)
    at /usr/lib/go-1.13/src/runtime/signal_unix.go:492
        handler = 0
#2  0x000000000105f356 in runtime.badsignal (sig=11, c=0x3fff8107190)
    at /usr/lib/go-1.13/src/runtime/signal_unix.go:600
No locals.
#3  0x000000000105e864 in runtime.sigtrampgo (sig=<optimized out>, info=0x3fff81072c0, ctx=0x3fff8107340)
    at /usr/lib/go-1.13/src/runtime/signal_unix.go:300
        setStack = <optimized out>
        sp = <optimized out>
        gsignalStack = <optimized out>
        g = <optimized out>
#4  0x000000000107b7e2 in runtime.sigtramp () at /usr/lib/go-1.13/src/runtime/sys_linux_s390x.s:242
No locals.
#5  <signal handler called>
No symbol table info available.
#6  0x000003fffdc1ecb4 in sqlite3VdbeRecordUnpack (pKeyInfo=0x3ff905a1930, nKey=0, pKey=0x5b00000000000001, p=p@entry=0x3ff907bb930) at /home/rafaeldtinoco/work/sources/upstream/lxd/deps/sqlite/src/vdbeaux.c:3964
        aKey = 0x5b00000000000001 <error: Cannot access memory at address 0x5b00000000000001>
        d = <optimized out>
        idx = <optimized out>
        u = <optimized out>
        szHdr = 1023
        pMem = 0x3ff907bb948
#7  0x000003fffdc17108 in sqlite3VdbeExec (p=<optimized out>)
    at /home/rafaeldtinoco/work/sources/upstream/lxd/deps/sqlite/src/vdbe.c:4528
        ii = <optimized out>
        alreadyExists = <optimized out>
        takeJump = <optimized out>
        pC = <optimized out>
        res = 1023
        pFree = 0x3ff907bb930
        pIdxKey = 0x3ff907bb930
        r = {pKeyInfo = 0xffffffff00000026, aMem = 0x3ff9034d238, nField = 2, default_rc = 0 '\000', 
          errCode = 0 '\000', r1 = -1 '\377', r2 = 1 '\001', eqSeen = 1 '\001'}
        aOp = 0x3ff9082ab00
        pOp = 0x3ff9082ae48
        rc = <optimized out>
        db = <optimized out>
        resetSchemaOnFault = <optimized out>
        encoding = <optimized out>
        iCompare = <optimized out>
        nVmStep = 105
        nProgressLimit = 4294967295
        aMem = 0x3ff9034cfd0
        pIn1 = <optimized out>
        pIn2 = <optimized out>
        pIn3 = 0x3ff9034d238
        pOut = <optimized out>
#8  0x000003fffdc1a6c0 in sqlite3Step (p=0x3ff9059bc50)
    at /home/rafaeldtinoco/work/sources/upstream/lxd/deps/sqlite/src/vdbeapi.c:697
        db = 0x3ff901ab000
        rc = <optimized out>
        db = <optimized out>
        rc = <optimized out>
#9  sqlite3_step (pStmt=0x3ff9059bc50)
    at /home/rafaeldtinoco/work/sources/upstream/lxd/deps/sqlite/src/vdbeapi.c:762
        rc = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging-- 
        v = 0x3ff9059bc50
        cnt = <optimized out>
        db = <optimized out>
#10 0x000003fffda907f0 in loop ()
   from /home/rafaeldtinoco/work/sources/upstream/lxd/deps/dqlite/.libs/libdqlite.so.0
No symbol table info available.
#11 0x000003fffda9bece in springboard ()
   from /home/rafaeldtinoco/work/sources/upstream/lxd/deps/dqlite/.libs/libdqlite.so.0
No symbol table info available.
#12 <signal handler called>
No symbol table info available.
#13 raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {4398008901332, 4396494590288, 64424509440, 0, 0, 0, 4396169211904, 4396169211904, 
            4396173343824, 4398004867866, 4396494590360, 4398008892688, 4396494590376, 0, 0, 1}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
```
