### ISSUE TITLE
Add support to import SNAP image of type: os

### ISSUE THREAD

**Issue by ykoehler** [lxc/lxd#7464]
This is a request for LXD to support importing LXD images from the SNAP format.  It is my understanding that a SNAP of type: os is very similar to a rootfs compressed folder tarballs and also include the metadata information.

Ideally, support would look like:

```
lxd image import custom_image.snap
```

And the snapcraft.yaml for that  custom_imge.snap would be something like

```
name: custom_image
version: '1.0.0.0'
summary: Runtime environment for custom_image
description: |
  custom_image runtime environment
type: os

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  bootstrap:
    source: image
    plugin: dump
```

Where the image folder would then contain a valid rootfs file structure.
