### ISSUE TITLE
Arch lxc start failed

### ISSUE THREAD

**Issue by horseinthesky** [lxc/lxd#7469]
# Required information

 * Distribution: Arch/Majaro
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.6.14-arch1-1
   * LXC version: 4.0.2
   * LXD version: 4.1
   * Storage backend in use: dir

# Issue description
Arch fails to start the container
```
lxc launch ubuntu:20.04 c1
Creating c1
Starting c1                                 
Error: Failed to run: /usr/bin/lxd forkstart c1 /var/lib/lxd/containers /var/log/lxd/c1/lxc.conf: 
Try `lxc info --show-log local:c1` for more info
```

# Steps to reproduce

 1. I've manually created files
```
cat /etc/subuid
"root:1000000:65536"
```
and
```
cat /etc/subgid
"root:1000000:65536"
 2. But it still fails
```
lxc start c1                
Error: Failed to run: /usr/bin/lxd forkstart c1 /var/lib/lxd/containers /var/log/lxd/c1/lxc.conf: 
Try `lxc info --show-log c1` for more info
```

# Information to attach

```
and restarted lxd via `systemctl restart lxd`. Reboot also doesn't change anything.

```
lxc info --show-log local:c1
Name: c1
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/05/29 07:53 UTC
Status: Stopped
Type: container
Profiles: default

Log:

lxc c1 20200529075342.587 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_create:1157 - File exists - The /sys/fs/cgroup/cpuset//lxc.monitor.c1 cgroup already existed
lxc c1 20200529075342.588 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1264 - Failed to create cgroup "(null)"
lxc c1 20200529075342.588 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_create:1157 - File exists - The /sys/fs/cgroup/cpuset//lxc.monitor.c1-1 cgroup already existed
lxc c1 20200529075342.588 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1264 - Failed to create cgroup "(null)"
lxc c1 20200529075342.628 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1143 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.c1-2"
lxc c1 20200529075342.629 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_create:1157 - File exists - The /sys/fs/cgroup/unified//lxc.payload.c1 cgroup already existed
lxc c1 20200529075342.629 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_payload_create:1343 - Failed to create cgroup "(null)"
lxc c1 20200529075342.629 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_create:1157 - File exists - The /sys/fs/cgroup/unified//lxc.payload.c1-1 cgroup already existed
lxc c1 20200529075342.629 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_payload_create:1343 - Failed to create cgroup "(null)"
lxc c1 20200529075342.629 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1143 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.c1-2"
lxc c1 20200529075342.635 ERROR    conf - conf.c:lxc_map_ids:2779 - newuidmap failed to write mapping "newuidmap: uid range [0-1000000000) -> [1000000-1001000000) not allowed": newuidmap 2533 0 1000000 1000000000
lxc c1 20200529075342.635 ERROR    start - start.c:lxc_spawn:1690 - Failed to set up id mapping.
lxc c1 20200529075342.635 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:851 - Received container state "ABORTING" instead of "RUNNING"
lxc c1 20200529075342.636 ERROR    start - start.c:__lxc_start:1952 - Failed to spawn container "c1"
lxc c1 20200529075342.636 WARN     start - start.c:lxc_abort:1024 - No such process - Failed to send SIGKILL via pidfd 30 for process 2533
lxc c1 20200529075342.760 ERROR    conf - conf.c:lxc_map_ids:2779 - newuidmap failed to write mapping "newuidmap: uid range [0-1000000000) -> [1000000-1001000000) not allowed": newuidmap 2547 1000000000 0 1 0 1000000 1000000000
lxc c1 20200529075342.760 ERROR    conf - conf.c:userns_exec_1:4088 - Error setting up {g,u}id mappings for child process "2547"
lxc c1 20200529075342.761 WARN     cgfsng - cgroups/cgfsng.c:cgfsng_payload_destroy:1045 - Invalid argument - Failed to destroy cgroups
lxc c1 20200529075342.791 WARN     cgfsng - cgroups/cgfsng.c:cgfsng_monitor_destroy:1110 - No space left on device - Failed to move monitor 2522 to "/sys/fs/cgroup/cpuset//lxc.pivot"
lxc 20200529075342.792 WARN     commands - commands.c:lxc_cmd_rsp_recv:120 - Connection reset by peer - Failed to receive response for command "get_state"
```

Main log
```
t=2020-05-29T04:18:14+0300 lvl=info msg="Pruning expired instance backups" 
t=2020-05-29T04:18:14+0300 lvl=info msg="Done pruning expired instance backups" 
t=2020-05-29T05:18:14+0300 lvl=info msg="Pruning expired instance backups" 
t=2020-05-29T05:18:14+0300 lvl=info msg="Done pruning expired instance backups" 
t=2020-05-29T06:18:14+0300 lvl=info msg="Pruning expired instance backups" 
t=2020-05-29T06:18:14+0300 lvl=info msg="Done pruning expired instance backups" 
t=2020-05-29T07:18:14+0300 lvl=info msg="Pruning expired instance backups" 
t=2020-05-29T07:18:14+0300 lvl=info msg="Done pruning expired instance backups" 
t=2020-05-29T08:18:14+0300 lvl=info msg="Pruning expired instance backups" 
t=2020-05-29T08:18:14+0300 lvl=info msg="Done pruning expired instance backups" 
t=2020-05-29T09:18:14+0300 lvl=info msg="Pruning expired instance backups" 
t=2020-05-29T09:18:14+0300 lvl=info msg="Done pruning expired instance backups" 
t=2020-05-29T09:18:14+0300 lvl=info msg="Updating images" 
t=2020-05-29T09:18:14+0300 lvl=info msg="Done updating images" 
t=2020-05-29T10:18:14+0300 lvl=info msg="Pruning expired instance backups" 
t=2020-05-29T10:18:14+0300 lvl=info msg="Done pruning expired instance backups" 
t=2020-05-29T10:53:28+0300 lvl=info msg="Deleting container" created=2020-05-28T21:18:39+0300 ephemeral=false name=c2 project=default used=2020-05-28T21:18:47+0300
t=2020-05-29T10:53:29+0300 lvl=info msg="Deleted container" created=2020-05-28T21:18:39+0300 ephemeral=false name=c2 project=default used=2020-05-28T21:18:47+0300
t=2020-05-29T10:53:35+0300 lvl=info msg="Creating container" ephemeral=false name=c1 project=default
t=2020-05-29T10:53:35+0300 lvl=info msg="Created container" ephemeral=false name=c1 project=default
t=2020-05-29T10:53:42+0300 lvl=info msg="Starting container" action=start created=2020-05-29T10:53:35+0300 ephemeral=false name=c1 project=default stateful=false used=1970-01-01T03:00:00+0300
t=2020-05-29T10:53:42+0300 lvl=eror msg="Failed starting container" action=start created=2020-05-29T10:53:35+0300 ephemeral=false name=c1 project=default stateful=false used=1970-01-01T03:00:00+0300
t=2020-05-29T10:53:43+0300 lvl=info msg="Container initiated stop" action=stop created=2020-05-29T10:53:35+0300 ephemeral=false name=c1 project=default stateful=false used=2020-05-29T10:53:42+0300
t=2020-05-29T10:53:43+0300 lvl=info msg="Shut down container" action=stop created=2020-05-29T10:53:35+0300 ephemeral=false name=c1 project=default stateful=false used=2020-05-29T10:53:42+0300
t=2020-05-29T10:57:12+0300 lvl=info msg="Starting container" action=start created=2020-05-29T10:53:35+0300 ephemeral=false name=c1 project=default stateful=false used=2020-05-29T10:53:42+0300
t=2020-05-29T10:57:12+0300 lvl=eror msg="Failed starting container" action=start created=2020-05-29T10:53:35+0300 ephemeral=false name=c1 project=default stateful=false used=2020-05-29T10:53:42+0300
t=2020-05-29T10:57:13+0300 lvl=info msg="Container initiated stop" action=stop created=2020-05-29T10:53:35+0300 ephemeral=false name=c1 project=default stateful=false used=2020-05-29T10:57:12+0300
t=2020-05-29T10:57:13+0300 lvl=info msg="Shut down container" action=stop created=2020-05-29T10:53:35+0300 ephemeral=false name=c1 project=default stateful=false used=2020-05-29T10:57:12+0300
```

Conftainer config
```
lxc config show c1 --expanded  
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20200522)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20200522"
  image.type: squashfs
  image.version: "20.04"
  volatile.base_image: 40775fd923e2a77f56ce3c028ce22ad43b9254bb12766b12eeeefb32a3a145da
  volatile.eth0.hwaddr: 00:16:3e:a3:d3:17
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: STOPPED
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
