### ISSUE TITLE
"System doesn't support syscall interception" while it should

### ISSUE THREAD

**Issue by pshirshov** [lxc/lxd#7543]
I'm trying to run an lxd container with the following definition:

```yaml
config:
  environment.LANG: en_US.UTF-8
  environment.LANGUAGE: en_US:en
  environment.LC_ALL: en_US.UTF-8
  linux.kernel_modules: ip_tables,overlay
  security.nesting: "true"
  security.privileged: "false"
  security.syscalls.intercept.mknod: "true"
  security.syscalls.intercept.setxattr: "true"
  raw.lxc: lxc.apparmor.profile=unconfined
  user.user-data: |
    #cloud-config
    output:
      all: '| tee -a /var/log/cloud-init-output.log'
    package_update: true
    package_upgrade: true
    runcmd:
      - set -xe
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - apt-get install -y apt-transport-https curl
      - add-apt-repository
        "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - apt-get update
      - apt-get install -y
        docker-ce
        docker-compose
        vim
        git
        squashfuse
      - systemctl start docker
      - docker image pull hello-world
      - docker run hello-world
    write_files:
      - path: /etc/rsylog.conf
        content: |
          module(load="imuxsock")
          *.* @log.virtdmz
        owner: root:root
        permissions: '0644'
      - path: /etc/docker/daemon.json
        content: |
          {
            "hosts": [
                "fd://",
                "tcp://0.0.0.0:2345"
            ],
            "storage-driver": "overlay"
          }
        permissions: '0644'
        owner: root:root
      - path: /etc/systemd/system/docker.service.d/override.conf
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd
        permissions: '0644'
        owner: root:root
    users:
      - name: rferguson
        groups:
          - adm
          - sudo
        lock_passwd: true
        shell: /bin/bash
        ssh-authorized-keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPS4YhP...
        sudo:
          - ALL=(ALL) NOPASSWD:ALL
description: Docker instance config.
devices: {}
name: docker
used_by: []
```

Though it fails to start:

```
# lxc launch ubuntu:18.04 docker0 < lxdtest.yaml
Creating docker0
Starting docker0
Error: Common start logic: System doesn't support syscall interception
```

There is a little information available regarding this problem, and seems like everything is fine with my system - I have seccomp and all the relevant lines of `lxc info` show what they should:

```
- seccomp_notify
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    seccomp_notify: "true"
```

I'm using LXD 4.0.1 with lxc 4.0.2-r2 and kernel 5.7.1. The kernel config is attached.

[config.gz](https://github.com/lxc/lxd/files/4793426/config.gz)
[lxc-info.txt](https://github.com/lxc/lxd/files/4793427/lxc-info.txt)
