### ISSUE TITLE
Error: Failed to create storage pool ‘default’: Failed to run: ceph –name client.admin –cluster ceph osd pool create lxd 32: 2020-06-27 15:56:51.067330 7f2d25023700 -1 Errors while parsing config file!

### ISSUE THREAD

**Issue by cemzafer** [lxc/lxd#7592]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-37
   * LXC version: 4.2
   * LXD version: 4.2
   * Storage backend in use: ceph version 15.2.1 (9fd2f65f91d9246fae2c841a6222d34d121680ee) octopus (stable)

# Issue description

I executed ‘sudo lxd init’ command on the ceph monitor host, but I get the following error. 
```
Would you like to use LXD clustering? (yes/no) [default=no]: 
Do you want to configure a new storage pool? (yes/no) [default=yes]: 
Name of the new storage pool [default=default]: 
Name of the storage backend to use (btrfs, dir, lvm, zfs, ceph) [default=zfs]: ceph
Create a new CEPH pool? (yes/no) [default=yes]: 
Name of the existing CEPH cluster [default=ceph]: 
Name of the OSD storage pool [default=lxd]: 
Number of placement groups [default=32]: 
Would you like to connect to a MAAS server? (yes/no) [default=no]: 
Would you like to create a new local network bridge? (yes/no) [default=yes]: 
What should the new bridge be called? [default=lxdbr0]: 
What IPv4 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 
What IPv6 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 
Would you like LXD to be available over the network? (yes/no) [default=no]: 
Would you like stale cached images to be updated automatically? (yes/no) [default=yes] 
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: yes
config: {}
networks:
- config:
    ipv4.address: auto
    ipv6.address: auto
  description: ""
  name: lxdbr0
  type: ""
storage_pools:
- config:
    ceph.cluster_name: ceph
    ceph.osd.pg_num: "32"
    ceph.osd.pool_name: lxd
  description: ""
  name: default
  driver: ceph
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      network: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
cluster: null

Error: Failed to create storage pool 'default': Failed to run: ceph --name client.admin --cluster ceph osd pool create lxd 32: 2020-06-27 15:56:51.067330 7f2d25023700 -1 Errors while parsing config file!
2020-06-27 15:56:51.067344 7f2d25023700 -1 parse_file: cannot open /etc/ceph/ceph.conf: (2) No such file or directory
2020-06-27 15:56:51.067345 7f2d25023700 -1 parse_file: cannot open ~/.ceph/ceph.conf: (2) No such file or directory
2020-06-27 15:56:51.067345 7f2d25023700 -1 parse_file: cannot open ceph.conf: (2) No such file or directory
Error initializing cluster client: ObjectNotFound('error calling conf_read_file',)

indiana@ceph100:~$ ls -al /etc/ceph/
total 28
drwxr-xr-x  2 root root   95 Jun 27 15:51 .
drwxr-xr-x 99 root root 8192 Jun 27 15:30 ..
-rw-------  1 root root   63 Jun 22 07:03 ceph.client.admin.keyring
-rw-r--r--  1 root root  272 Jun 27 15:51 ceph.conf
-rw-r--r--  1 root root  595 Jun 22 07:04 ceph.pub
-rw-r--r--  1 root root   61 Jun 26 00:27 lxdpool.keyring
```

# Steps to reproduce

 1. sudo lxd init

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
```
=2020-06-27T22:46:52+0300 lvl=info msg="LXD 4.2 is starting in normal mode" path=/var/snap/lxd/common/lxd
t=2020-06-27T22:46:52+0300 lvl=info msg="Kernel uid/gid map:" 
t=2020-06-27T22:46:52+0300 lvl=info msg=" - u 0 0 4294967295" 
t=2020-06-27T22:46:52+0300 lvl=info msg=" - g 0 0 4294967295" 
t=2020-06-27T22:46:52+0300 lvl=info msg="Configured LXD uid/gid map:" 
t=2020-06-27T22:46:52+0300 lvl=info msg=" - u 0 1000000 1000000000" 
t=2020-06-27T22:46:52+0300 lvl=info msg=" - g 0 1000000 1000000000" 
t=2020-06-27T22:46:52+0300 lvl=info msg="Kernel features:" 
t=2020-06-27T22:46:52+0300 lvl=info msg=" - netnsid-based network retrieval: yes" 
t=2020-06-27T22:46:52+0300 lvl=info msg=" - pidfds: no" 
t=2020-06-27T22:46:52+0300 lvl=info msg=" - uevent injection: yes" 
t=2020-06-27T22:46:52+0300 lvl=info msg=" - seccomp listener: yes" 
t=2020-06-27T22:46:52+0300 lvl=info msg=" - seccomp listener continue syscalls: yes" 
t=2020-06-27T22:46:52+0300 lvl=info msg=" - unprivileged file capabilities: yes" 
t=2020-06-27T22:46:52+0300 lvl=info msg=" - cgroup layout: hybrid" 
t=2020-06-27T22:46:52+0300 lvl=warn msg=" - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored" 
t=2020-06-27T22:46:52+0300 lvl=warn msg=" - Couldn't find the CGroup memory swap accounting, swap limits will be ignored" 
t=2020-06-27T22:46:52+0300 lvl=info msg=" - shiftfs support: disabled" 
t=2020-06-27T22:46:52+0300 lvl=info msg="Initializing local database" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Starting /dev/lxd handler:" 
t=2020-06-27T22:46:53+0300 lvl=info msg=" - binding devlxd socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
t=2020-06-27T22:46:53+0300 lvl=info msg="REST API daemon:" 
t=2020-06-27T22:46:53+0300 lvl=info msg=" - binding Unix socket" inherited=true socket=/var/snap/lxd/common/lxd/unix.socket
t=2020-06-27T22:46:53+0300 lvl=info msg="Initializing global database" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Firewall loaded driver \"xtables\"" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Initializing storage pools" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Initializing daemon storage mounts" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Initializing networks" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Pruning leftover image files" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Done pruning leftover image files" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Loading daemon configuration" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Started seccomp handler" path=/var/snap/lxd/common/lxd/seccomp.socket
t=2020-06-27T22:46:53+0300 lvl=info msg="Pruning expired images" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Done pruning expired images" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Pruning expired instance backups" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Done pruning expired instance backups" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Updating instance types" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Done updating instance types" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Updating images" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Expiring log files" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Done updating images" 
t=2020-06-27T22:46:53+0300 lvl=info msg="Done expiring log files" 
t=2020-06-27T22:47:53+0300 lvl=warn msg="Failed getting list of tables from \"/proc/self/net/ip6_tables_names\", assuming all requested tables exist" 
```
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
```
root@ceph100:~# lxc monitor
If this is your first time running LXD on this machine, you should also run: lxd init
To start your first instance, try: lxc launch ubuntu:18.04

location: none
metadata:
  context: {}
  level: dbug
  message: 'New event listener: 7ee7c10a-7ba2-4e1d-9a1a-46fe0b38109e'
timestamp: "2020-06-27T22:49:33.08550701+03:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
    user: ""
  level: dbug
  message: Handling
timestamp: "2020-06-27T22:49:54.318247161+03:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/storage-pools/default
    user: ""
  level: dbug
  message: Handling
timestamp: "2020-06-27T22:50:00.617830321+03:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/networks/lxdbr0
    user: ""
  level: dbug
  message: Handling
timestamp: "2020-06-27T22:50:15.113174049+03:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/networks
    user: ""
  level: dbug
  message: Handling
timestamp: "2020-06-27T22:50:22.745528869+03:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: POST
    url: /1.0/networks
    user: ""
  level: dbug
  message: Handling
timestamp: "2020-06-27T22:50:22.74863624+03:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: lxdbr0 has been added: updating network priorities'
timestamp: "2020-06-27T22:50:23.801822927+03:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/storage-pools
    user: ""
  level: dbug
  message: Handling
timestamp: "2020-06-27T22:50:23.943085115+03:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: POST
    url: /1.0/storage-pools
    user: ""
  level: dbug
  message: Handling
timestamp: "2020-06-27T22:50:23.945581842+03:00"
type: logging


location: none
metadata:
  context:
    config: map[ceph.cluster_name:ceph ceph.osd.pg_num:32 ceph.osd.pool_name:lxd]
    description: ""
    driver: ceph
    localOnly: "false"
    pool: default
  level: dbug
  message: create started
timestamp: "2020-06-27T22:50:23.97396344+03:00"
type: logging


location: none
metadata:
  context:
    config: map[ceph.cluster_name:ceph ceph.osd.pg_num:32 ceph.osd.pool_name:lxd ceph.user.name:admin volatile.initial_source:]
    description: ""
    driver: ceph
    localOnly: "false"
    pool: default
  level: dbug
  message: create finished
timestamp: "2020-06-27T22:50:40.697018619+03:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: DELETE
    url: /1.0/networks/lxdbr0
    user: ""
  level: dbug
  message: Handling
timestamp: "2020-06-27T22:50:40.735209744+03:00"
type: logging
```
