### ISSUE TITLE
moving virtual-machine between cluster nodes gives: Error: Migration operation failure: Failed to get instance info: not found

### ISSUE THREAD

**Issue by vvolas** [lxc/lxd#7701]
```
 * Distribution: Ubuntu18 
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.3.0-59-generic
  driver: lxc
  driver_version: 4.0.3
  project: default
  server: lxd
  server_clustered: true
  server_version: 4.0.2
  storage: ceph | btrfs
```


I dont know how relevant it is but, I created windows10 vm on non-server machine from this guide https://discuss.linuxcontainers.org/t/running-virtual-machines-with-lxd-4-0/7519, then copied it to cluster, it copied to wrong node so I tried to move it and it gives error.

OK tried creating new containers with 
```
lxc launch ubuntu buntu -p default_hdd
lxc launch ubuntu buntu -p default_hdd --vm
```

 with  buntu on container type move works, but on virtual-machine it gives same error.

**when instead "lxc move" i tried "lxc copy" it worked fine.**

# Steps to reproduce

```
root@cluster-linux:~# lxc move windows10 --target paralel-linux
Error: Migration operation failure: Failed to get instance info: not found
root@cluster-linux:~# lxc info windows10
Name: windows10
Location: cluster-linux
Remote: unix://
Architecture: x86_64
Created: 2020/07/28 09:01 UTC
Status: Stopped
Type: virtual-machine
Profiles: default_hdd
root@cluster-linux:~# lxc info windows10 --show-log
Name: windows10
Location: cluster-linux
Remote: unix://
Architecture: x86_64
Created: 2020/07/28 09:01 UTC
Status: Stopped
Type: virtual-machine
Profiles: default_hdd

Log:

ioctl(KVM_CREATE_VM) failed: 16 Device or resource busy
qemu-system-x86_64: failed to initialize kvm: Device or resource busy

this is because there is virtualbox currently running on this machine, thats why i m moving it.
```
# Information to attach

 - [ ] Any relevant kernel output (`dmesg`) nothing
 - [ ] Container configuration (`lxc config show NAME --expanded`)
```
andriusjurkus@cluster-linux:~$ lxc config show windows10 --expanded
architecture: x86_64
config:
  limits.cpu: "4"
  limits.memory: 4GB
  security.secureboot: "false"
  volatile.eth0.hwaddr: 00:16:3e:9a:f0:4f
  volatile.vm.uuid: cde653ca-6749-439e-8b50-11121fff08f7
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: hdd
    size: 20GB
    type: disk
ephemeral: false
profiles:
- default_hdd
stateful: false
description: ""
```
```
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log) nothing on both ends
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  context: {}                                                                                                                                                                                                                                
  level: dbug                                                                                                                                                                                                                                
  message: 'New event listener: 2d639020-ee0a-466f-9930-1709bfd07c0e'                                                                                                                                                                        
timestamp: "2020-07-28T14:46:48.035186816+03:00"                                                                                                                                                                                             
type: logging                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  context:                                                                                                                                                                                                                                   
    ip: '@'                                                                                                                                                                                                                                  
    method: GET                                                                                                                                                                                                                              
    url: /1.0                                                                                                                                                                                                                                
    user: ""                                                                                                                                                                                                                                 
  level: dbug                                                                                                                                                                                                                                
  message: Handling                                                                                                                                                                                                                          
timestamp: "2020-07-28T14:46:49.342413239+03:00"                                                                                                                                                                                             
type: logging                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  context:                                                                                                                                                                                                                                   
    ip: '@'                                                                                                                                                                                                                                  
    method: GET                                                                                                                                                                                                                              
    url: /1.0/events?target=paralel-linux                                                                                                                                                                                                    
    user: ""                                                                                                                                                                                                                                 
  level: dbug                                                                                                                                                                                                                                
  message: Handling                                                                                                                                                                                                                          
timestamp: "2020-07-28T14:46:49.349805227+03:00"                                                                                                                                                                                             
type: logging                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  context: {}                  
  level: dbug                                                                                                                                                                                                                                
  message: 'New event listener: 7705857b-893f-4dfa-826d-0aa8373f0bb3'                                                                                                                                                                        
timestamp: "2020-07-28T14:46:49.350729726+03:00"                                                                                                                                                                                             
type: logging                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  context:                                                                                                                                                                                                                                   
    ip: '@'                                                                                                                                                                                                                                  
    method: POST                                                                                                                                                                                                                             
    url: /1.0/instances/windows10?target=paralel-linux                                                                                                                                                                                       
    user: ""                                                                                                                                                                                                                                 
  level: dbug                                                                                                                                                                                                                                
  message: Handling                                                                                                                                                                                                                          
timestamp: "2020-07-28T14:46:49.35173781+03:00"                                                                                                                                                                                              
type: logging                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  context: {}                                                                                                                                                                                                                                
  level: dbug                                                                                                                                                                                                                                
  message: 'New task Operation: 5927c55d-bba9-458a-a7f0-33343605e653'                                                                                                                                                                        
timestamp: "2020-07-28T14:46:49.594140781+03:00"                                                                                                                                                                                             
type: logging                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  class: task                                                                                                                                                                                                                                
  created_at: "2020-07-28T14:46:49.367679466+03:00"                                                                                                                                                                                          
  description: Migrating container                                                                                                                                                                                                           
  err: ""                                                                                                                                                                                                                                    
  id: 5927c55d-bba9-458a-a7f0-33343605e653                                                                                                                                                                                                   
  location: cluster-linux                                                                                                                                                                                                                    
  may_cancel: false                                                                                                                                                                                                                          
  metadata: null                                                                                                                                                                                                                             
  resources:                                                                                                                                                                                                                                 
    containers:                                                                                                                                                                                                                              
    - /1.0/containers/windows10                                                                                                                                                                                                              
  status: Pending                                                                                                                                                                                                                            
  status_code: 105                                                                                                                                                                                                                           
  updated_at: "2020-07-28T14:46:49.367679466+03:00"                                                                                                                                                                                          
timestamp: "2020-07-28T14:46:49.595106367+03:00"                                                                                                                                                                                             
type: operation                                                                                                                                                                                                                              
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  context: {}                                                                                                                                                                                                                                
  level: dbug                                                                                                                                                                                                                                
  message: 'Started task operation: 5927c55d-bba9-458a-a7f0-33343605e653'                                                                                                                                                                    
timestamp: "2020-07-28T14:46:49.595145931+03:00"                                                                                                                                                                                             
type: logging                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  context: {}                                                                                                                                                                                                                                
  level: dbug                                                                                                                                                                                                                                
  message: Connecting to a remote LXD over HTTPs                                                                                                                                                                                             
timestamp: "2020-07-28T14:46:49.595414664+03:00"                                                                                                                                                                                             
type: logging                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux            
metadata:                                                                                                                                                                                                                                    
  class: task                                                                                                                                                                                                                                
  created_at: "2020-07-28T14:46:49.367679466+03:00"                                                                                                                                                                                          
  description: Migrating container                                                                                                                                                                                                           
  err: ""                                                                                                                                                                                                                                    
  id: 5927c55d-bba9-458a-a7f0-33343605e653                                                                                                                                                                                                   
  location: cluster-linux                                                                                                                                                                                                                    
  may_cancel: false                                                                                                                                                                                                                          
  metadata: null                                                                                                                                                                                                                             
  resources:                                                                                                                                                                                                                                 
    containers:                                                                                                                                                                                                                              
    - /1.0/containers/windows10                                                                                                                                                                                                              
  status: Running                                                                                                                                                                                                                            
  status_code: 103                                                                                                                                                                                                                           
  updated_at: "2020-07-28T14:46:49.367679466+03:00"                                                                                                                                                                                          
timestamp: "2020-07-28T14:46:49.596470648+03:00"                                                                                                                                                                                             
type: operation                                                                                                                                                                                                                              
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  context:                                                                                                                                                                                                                                   
    ip: '@'                                                                                                                                                                                                                                  
    method: GET                                                                                                                                                                                                                              
    url: /1.0/operations/5927c55d-bba9-458a-a7f0-33343605e653?target=paralel-linux                                                                                                                                                           
    user: ""                                                                                                                                                                                                                                 
  level: dbug                                                                                                                                                                                                                                
  message: Handling                                                                                                                                                                                                                          
timestamp: "2020-07-28T14:46:49.599565113+03:00"                                                                                                                                                                                             
type: logging                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  context: {}                                                                                                                                                                                                                                
  level: dbug                                                                                                                                                                                                                                
  message: Connecting to a remote LXD over HTTPs                                                                                                                                                                                             
timestamp: "2020-07-28T14:46:49.618624215+03:00"                                                                                                                                                                                             
type: logging                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  context:                                                                                                                                                                                                                                   
    etag: ""                                                                                                                                                                                                                                 
    method: GET                                                                                                                                                                                                                              
    url: https://10.0.199.230:8443/1.0/containers/windows10                                                                                                                                                                                  
  level: dbug                                                                                                                                                                                                                                
  message: Sending request to LXD                                                                                                                                                                                                            
timestamp: "2020-07-28T14:46:49.636400872+03:00"                                                                                                                                                                                             
type: logging                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  context:                                                                                                                                                                                                                                   
    ip: 10.0.199.230:52694                                                                                                                                                                                                                   
    method: GET                                                                                                                                                                                                                              
    url: /1.0/containers/windows10                                                                                                                                                                                                           
    user: ""                                                                                                                                                                                                                                 
  level: dbug                                                                                                                                                                                                                                
  message: Handling                                                                                                                                                                                                                          
timestamp: "2020-07-28T14:46:49.740388779+03:00"                                                                                                                                                                                             
type: logging                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                    
metadata:                                                                                                                                                                                                                                    
  context:                                                                                                                                                                                                                                   
    name: "0"                                                                                                                                                                                                                                
  level: dbug                                                                                                                                                                                                                                
  message: Found cert                                                                                                                                                                                                                        
timestamp: "2020-07-28T14:46:49.740323422+03:00"                                                                                                                                                                                             
type: logging                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  context: {}                                                                                                                                                                                                                                
  level: dbug                                                                                                                                                                                                                                
  message: 'Database error: &errors.errorString{s:"No such object"}'                                                                                                                                                                         
timestamp: "2020-07-28T14:46:49.741518256+03:00"                                                                                                                                                                                             
type: logging                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  context: {}                                                                                                                                                                                                                                
  level: dbug                                                                                                                                                                                                                                
  message: 'Failure for task operation: 5927c55d-bba9-458a-a7f0-33343605e653: Failed to get instance info: not found'                                                                                                                        
timestamp: "2020-07-28T14:46:49.741896245+03:00"                                                                                                                                                                                             
type: logging                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  class: task                                                                                                                                                                                                                                
  created_at: "2020-07-28T14:46:49.367679466+03:00"                                                                                                                                                                                          
  description: Migrating container                                                                                                                                                                                                           
  err: 'Failed to get instance info: not found'                                                                                                                                                                                              
  id: 5927c55d-bba9-458a-a7f0-33343605e653                                                                                                                                                                                                   
  location: cluster-linux                                                                                                                                                                                                                    
  may_cancel: false                                                                                                                                                                                                                          
  metadata: null                                                                                                                                                                                                                             
  resources:                                                                                                                                                                                                                                 
    containers:                                                                                                                                                                                                                              
    - /1.0/containers/windows10                                                                                                                                                                                                              
  status: Failure                                                                                                                                                                                                                            
  status_code: 400                                                                                                                                                                                                                           
  updated_at: "2020-07-28T14:46:49.367679466+03:00"                                                                                                                                                                                          
timestamp: "2020-07-28T14:46:49.742922506+03:00"                                                                                                                                                                                             
type: operation                                                                                                                                                                                                                              
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  context: {}                                                                                                                                                                                                                                
  level: dbug                                                                                                                                                                                                                                
  message: 'Event listener finished: 7705857b-893f-4dfa-826d-0aa8373f0bb3'                                                                                                                                                                   
timestamp: "2020-07-28T14:46:49.745271726+03:00"                                                                                                                                                                                             
type: logging                                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
location: cluster-linux                                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                                                    
  context: {}                                                                                                                                                                                                                                
  level: dbug                                                                                                                                                                                                                                
  message: 'Disconnected event listener: 7705857b-893f-4dfa-826d-0aa8373f0bb3'                                                                                                                                                               
timestamp: "2020-07-28T14:46:49.745706551+03:00"                                                                                                                                                                                             
type: logging        
```
