### ISSUE TITLE
Can't delete networks without running detach-profile first

### ISSUE THREAD

**Issue by paride** [lxc/lxd#7804]
When configured to setup a LXD bridge cloud-init does the following:
1. `lxd init --auto`
2. deletes the automatically created `lxdbr0` bridge (https://github.com/canonical/cloud-init/blob/master/cloudinit/config/cc_lxd.py#L271)
3. creates a new bridge as specified.

Bridge deletion is done by running `lxd network delete <bridgename>`, however as https://github.com/lxc/lxd/commit/baaa81c71be93cf2e2059327008d358e322024e3 landed in the stable channels this stopped working, requiring an extra step: `lxd detach-profile <bridge> <profile>`.

I understand this is the new expected behavior, however: was it intentional have the change land in the non-*latest* stable channels? Will you make the older syntax valid again, or will the client broken by the change need to adapt to the new LXD behavior?

(I'm aware of `lxd --preseed`, however cloud-init needs to support Xenial (= lxd .deb 2.0.0-0ubuntu4), so that's not an option for the moment.)

Thanks!

**Comment by stgraber** [comment]
Hmm, in your profile, is it using `nictype=bridged + parent=lxdbr0` or `network=lxdbr0`?

If using `network=lxdbr0`, then this is similar to `pool=name` for `disk` devices and should definitely prevent the deletion of the network or you'd have a DB reference to something which does not exist.

Now this behavior should NOT happen if you use `nictype=bridged + parent=lxdbr0` as that would be equivalent to the bind-mount syntax in a `disk` device and not a reference to a in-DB network. If this is preventing deletion of a network, that's a bug which we would go and fix.

**Comment by paride** [comment]
The profile has `network: lxdbr0`:


```
root@paride-f:~# lxc profile show default
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by: []
```

```
root@paride-f:~# lxc network show lxdbr0
config:
  ipv4.address: 10.127.154.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:44e:244a:82f5::1/64
  ipv6.nat: "true"
description: ""
name: lxdbr0
type: bridge
used_by:
- /1.0/profiles/default
managed: true
status: Created
locations:
- none
```

```
root@paride-f:~# lxc network delete lxdbr0
Error: The network is currently in use
```

so I think the behavior is the expected one.
