### ISSUE TITLE
Error when starting proxy device: bind: address already in use

### ISSUE THREAD

**Issue by NicolasGoeddel** [lxc/lxd#7891]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.5 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-112-generic
   * LXC version: 4.5
   * LXD version: 4.5
   * Storage backend in use: zfs

# Issue description

We restart some of our containers over night for backup purposes. Some of them did not start again because of this error:
```
root@server:~# lxc start test
Error: Error occurred when starting proxy device: Error: Failed to listen on 0.0.0.0:2227: listen tcp 0.0.0.0:2227: bind: address already in use
Try `lxc info --show-log test` for more info
```
`lxc info --show-log test` shows this:
```
lxc test 20200918083103.967 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1152 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.test"
lxc test 20200918083103.967 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1152 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.test"
lxc test 20200918083103.968 ERROR    utils - utils.c:lxc_can_use_pidfd:1834 - Kernel does not support pidfds
lxc test 20200918083110.396 WARN     network - network.c:lxc_delete_network_priv:3185 - Failed to rename interface with index 2 from "eth0" to its initial name "veth602b439a"
```
And indeed the port is already in use:
```
root@server:~# netstat -tlnp | grep 2227
tcp6       0      0 :::2227                 :::*                    LISTEN      5451/lxd
```
Beforehand I created a proxy:
```
root@server:~# lxc config device show test
SSH:
  connect: tcp:10.100.20.127:22
  listen: tcp:0.0.0.0:2227
  type: proxy
eth0:
  ipv4.address: 10.100.20.127
  name: eth0
  nictype: bridged
  parent: lxdbr0
  type: nic
```
Now the proxy seems to be stuck. How can I stop it? And how can I avoid this issue in the future?

**Comment by NicolasGoeddel** [comment]
Okay, I figured out how to make it work again.
I found some `forkproxy` processes which I was able to kill. After that the containers started again.
In #7751 I saw the assumption for too less free space available on the device for PID files. I can not confirm that on my side. My ZFS pool has 2,21 TB free space available. And only some loop devices are 100% in use, but that should be normal.
```
root@server:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             32G     0   32G   0% /dev
tmpfs           6,3G   20M  6,3G   1% /run
/dev/md1         20G   16G  2,7G  86% /
tmpfs            32G     0   32G   0% /dev/shm
tmpfs           5,0M     0  5,0M   0% /run/lock
tmpfs            32G     0   32G   0% /sys/fs/cgroup
/dev/loop1       55M   55M     0 100% /snap/core18/1880
/dev/md0        969M  144M  759M  16% /boot
lxd/home        2,4T  179G  2,3T   8% /home
tmpfs           1,0M     0  1,0M   0% /var/snap/lxd/common/ns
tmpfs           6,3G     0  6,3G   0% /run/user/0
/dev/loop4       56M   56M     0 100% /snap/core18/1885
/dev/loop2       97M   97M     0 100% /snap/core/9804
/dev/loop9       24M   24M     0 100% /snap/bashtop/128
/dev/loop10      98M   98M     0 100% /snap/core/9993
/dev/loop11      24M   24M     0 100% /snap/bashtop/134
/dev/loop12      73M   73M     0 100% /snap/lxd/17147
/dev/loop7       69M   69M     0 100% /snap/lxd/17280
```

**Comment by NicolasGoeddel** [comment]
I will wait and check if the same thing happens tonight. If it does not happen again, we can close this issue I guess.

**Comment by stgraber** [comment]
@NicolasGoeddel  did this show up again?

**Comment by NicolasGoeddel** [comment]
No.

**Comment by larsemil** [comment]
I got the exact same problem today. Manually killing forkproxy got me starting the machines again.

**Comment by dontlaugh** [comment]
This happened to me as well. Killing the single forkproxy process associated with the device configuration attached to my instance allowed me to re-bind with the same device config.

This was the device I was trying to re-add

```
lxc config device add nearhan nearhanssh0 proxy listen=tcp:0.0.0.0:42022 connect=tcp:0.0.0.0:22 bind=host
```
This was originally a part of the container config, but a restart of the container failed with

```
lxc start nearhan
Error: Error occurred when starting proxy device: Error: Failed to listen on 0.0.0.0:42022: listen tcp 0.0.0.0:42022: bind: address already in use
```
The original configuration
```yaml
#lxc config device show nearhan            
nearhanssh0:   # had to remove this, kill forkproxy, and add it back
  bind: host
  connect: tcp:0.0.0.0:22
  listen: tcp:0.0.0.0:42022
  type: proxy
proxy0:
  connect: tcp:0.0.0.0:7420
  listen: tcp:0.0.0.0:7420
  type: proxy
```
