### ISSUE TITLE
It seems, that "limits.memory.swap = false" doesn't work.

### ISSUE THREAD

**Issue by kautMaks** [lxc/lxd#7916]
**Required information**

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-48-generic
   * LXC version: 4.5
   * LXD version: 4.5
   * Storage backend in use: dir

**Issue description**
It seems, that "limits.memory.swap = false" doesn't work.
I set limits.memory.swap = false and limits.memory.enforce = hard.
If swapaccount=1 doesn't set, I see total swap 0 inside CT, but when all ram inside CT is used, it takes swap from node.
Tested by command:
    `echo {1..1000000000}`
If swapaccount=1 set by adding "cgroup_enable=memory swapaccount=1" in GRUB_CMDLINE_LINUX, I see all swap from node, despite limits.memory.swap = false.
And similary, swap from node begins to be used, when memory limit reached inside CT.

**Steps to reproduce**
On the node:
```
lxc launch ubuntu:20.04 swaptest
lxc config set swaptest limits.memory 4GiB
lxc config set swaptest limits.memory.swap false
lxc config set swaptest limits.memory.enforce hard
```
Inside CT:
`echo {1..1000000000}`
And watch swap using on the node.

**Information to attach**
lxc config show --expanded swaptest
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20200921.1)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20200921.1"
  image.type: squashfs
  image.version: "20.04"
  limits.memory: 4GiB
  limits.memory.enforce: hard
  limits.memory.swap: "false"
  volatile.base_image: 4746a4889a31e449e6c5e2764eb733a60e85131be3165c91d5f5a8346f0ba43c
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":755360,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":755360,"Nsid":0,"Maprange":65536}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":755360,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":755360,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":755360,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":755360,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  root:
    path: /
    pool: default
    size: 1EiB
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
