### ISSUE TITLE
LXD another network interface has no internet access

### ISSUE THREAD

**Issue by LukasHanusek** [lxc/lxd#8050]
Host distro: Debian Buster
Container's distro: Debian Buster

lxc info:
```
config: {}
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 4.0.4
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 4.19.0-10-amd64
  lxc_features:
    cgroup2: "true"
    devpts_fd: "false"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "false"
  os_name: Debian GNU/Linux
  os_version: "10"
  project: default
  server: lxd
  server_clustered: false
  server_name: Debian-83-jessie-64-minimal
  server_pid: 1699
  server_version: "4.6"
  storage: dir
  storage_version: "1"
```

I have 2 static IPv4 addresses on my machine, I want to create another lxc network interface for the secondary IP so that I can have a container with that static IP so all udp/tcp ports are forwarded to that container so I can host services like apache and sql db inside that container under the secondary IP. However once I assign the second network to the container, the container loses internet access completely. The command "ping google.com" inside the container returns DNS resolution error, so it is completely cut off. I am not a network expert so I might be missing something here but since the default bridge "lxdbr0" and "publicip" have exactly the same output of "lxc network show" I cannot figure out why lxdbr0 is working and the second one is not.

Steps to reproduce:
```
lxc network create publicip #new network
lxc network add publicip ipv4.address 10.3.3.3/30 #local ip
lxc network add publicip ipv4.routes 138.*.16.151/32 #public ip route
lxc network attach publicip c1 eth0 #attach network to the container
lxc config device set c1 eth0 ipv4.address 10.3.3.2 #assign local IP from the publicip device range
```

route -n output:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         138.*.16.129  0.0.0.0         UG    0      0        0 eth0
10.3.3.0        0.0.0.0         255.255.255.252 U     0      0        0 publicip
10.10.0.0       0.0.0.0         255.255.0.0     U     0      0        0 lxdbr0
138.*.16.128  138.*.16.129  255.255.255.192 UG    0      0        0 eth0
138.*.16.128  0.0.0.0         255.255.255.192 U     0      0        0 eth0
138.*.16.132  0.0.0.0         255.255.255.255 UH    0      0        0 lxdbr0
138.*.16.151  0.0.0.0         255.255.255.255 UH    0      0        0 publicip
```

lxc list output:
```
+------+---------+-----------------+-----------------------------------------------+-----------+-----------+
| NAME |  STATE  |      IPV4       |                     IPV6                      |   TYPE    | SNAPSHOTS |
+------+---------+-----------------+-----------------------------------------------+-----------+-----------+
| c1   | RUNNING | 10.3.3.2 (eth0) | fd42:485a:4adb:7f3c:216:3eff:febd:6b85 (eth0) | CONTAINER | 0         |
+------+---------+-----------------+-----------------------------------------------+-----------+-----------+

```
host's /etc/network/interfaces file:
```
auto lo
iface lo inet loopback
auto  eth0
iface eth0 inet static
  address   138.*.16.132
  netmask   255.255.255.192
  gateway   138.*.16.129
  up route add -net 138.*.16.128 netmask 255.255.255.192 gw 138.*.16.129 eth0
auto eth0:0
iface   eth0:0 inet static
        address 138.*.16.151
        netmask 255.255.255.192
        up route add -net 138.*.16.151 netmask 255.255.255.192 eth0:0
```

container's /etc/network/interfaces file:
```
auto lo
iface lo inet loopback
auto eth0
iface   eth0 inet dhcp
```
