### ISSUE TITLE
lxd cluster, copying windows vm from ceph to local btrfs gives Error: You cannot shrink block volumes: Cannot be shrunk.

### ISSUE THREAD

**Issue by vvolas** [lxc/lxd#8112]
LXD 4.0.3 ubuntu18

I even tried to increase vm size by 5GB before copying in w10-dev-terminal but it failed again. 
devices:
  root:
    path: /
    pool: ceph-lxd
    size: 65GB
    type: disk

lxc copy --debug w10-dev-terminal w10-dev-terminal-ssd --instance-only --target paralel-linux -p default -s ssd

lxc monitor output
```
location: paralel-linux
metadata:
  class: task
  created_at: "2020-11-03T10:51:10.6111635+02:00"
  description: Creating container
  err: ""
  id: 707b2d66-368d-47ce-821b-3c7b207d955a
  location: paralel-linux
  may_cancel: false
  metadata:
    block_progress: 'w10-dev-terminal: 60.69GB (133.77MB/s)'
  resources:
    containers:
    - /1.0/containers/w10-dev-terminal-ssd
    - /1.0/containers/w10-dev-terminal
    instances:
    - /1.0/instances/w10-dev-terminal-ssd
    - /1.0/instances/w10-dev-terminal
  status: Running
  status_code: 103
  updated_at: "2020-11-03T10:58:45.989594018+02:00"
timestamp: "2020-11-03T10:58:45.991062097+02:00"
type: operation


location: paralel-linux
metadata:
  context:
    args: '&{w10-dev-terminal [] {BLOCK_AND_RSYNC []} true false false <nil>}'
    driver: ceph
    instance: w10-dev-terminal
    pool: ceph-lxd
    project: default
  level: dbug
  message: MigrateInstance finished
timestamp: "2020-11-03T10:58:48.784730189+02:00"
type: logging


location: paralel-linux
metadata:
  context:
    args: '{w10-dev-terminal-ssd  map[] [] {BLOCK_AND_RSYNC []} false false false 61000000000}'
    driver: btrfs
    instance: w10-dev-terminal-ssd
    pool: ssd
    project: default
  level: dbug
  message: CreateInstanceFromMigration finished
timestamp: "2020-11-03T10:58:48.875007779+02:00"
type: logging


location: paralel-linux
metadata:
  context:
    driver: btrfs
    instance: w10-dev-terminal-ssd
    pool: ssd
    project: default
    snapshots: "false"
    src: w10-dev-terminal
  level: dbug
  message: CreateInstanceFromCopy finished
timestamp: "2020-11-03T10:58:48.90767327+02:00"
type: logging


location: paralel-linux
metadata:
  context:
    driver: btrfs
    instance: w10-dev-terminal-ssd
    pool: ssd
    project: default
  level: dbug
  message: SetInstanceQuota started
timestamp: "2020-11-03T10:58:48.911858611+02:00"
type: logging

location: paralel-linux
metadata:
  context:
    driver: btrfs
    instance: w10-dev-terminal-ssd
    pool: ssd
    project: default
  level: dbug
  message: SetInstanceQuota finished
timestamp: "2020-11-03T10:58:48.912041362+02:00"
type: logging


location: paralel-linux
metadata:
  context:
    driver: btrfs
    instance: w10-dev-terminal-ssd
    pool: ssd
    project: default
  level: dbug
  message: DeleteInstance started
timestamp: "2020-11-03T10:58:48.917538443+02:00"
type: logging


location: paralel-linux
metadata:
  context:
    driver: btrfs
    instance: w10-dev-terminal-ssd
    pool: ssd
    project: default
    volName: w10-dev-terminal-ssd
  level: dbug
  message: Deleting instance volume
timestamp: "2020-11-03T10:58:48.918655099+02:00"
type: logging


location: paralel-linux
metadata:
  context:
    created: 2020-11-03 10:51:10.668748296 +0200 EET
    ephemeral: "false"
    name: w10-dev-terminal-ssd
    project: default
    used: 1970-01-01 03:00:00 +0300 MSK
  level: info
  message: Deleting instance
timestamp: "2020-11-03T10:58:48.91224108+02:00"
type: logging


location: paralel-linux
metadata:
  context:
    driver: btrfs
    instance: w10-dev-terminal-ssd
    pool: ssd
    project: default
  level: dbug
  message: DeleteInstance finished
timestamp: "2020-11-03T10:58:48.984272277+02:00"
type: logging


location: paralel-linux
metadata:
  context:
    created: 2020-11-03 10:51:10.668748296 +0200 EET
    ephemeral: "false"
    name: w10-dev-terminal-ssd
    project: default
    used: 1970-01-01 03:00:00 +0300 MSK
  level: info
  message: Deleted instance
timestamp: "2020-11-03T10:58:49.024170171+02:00"
type: logging

location: paralel-linux
metadata:
  action: virtual-machine-deleted
  source: /1.0/virtual-machines/w10-dev-terminal-ssd
timestamp: "2020-11-03T10:58:49.024289724+02:00"
type: lifecycle


location: paralel-linux
metadata:
  context: {}
  level: dbug
  message: 'Failure for task operation: 707b2d66-368d-47ce-821b-3c7b207d955a: You cannot shrink block volumes: Cannot be shrunk'
timestamp: "2020-11-03T10:58:49.024402834+02:00"
type: logging


location: paralel-linux
metadata:
  class: task
  created_at: "2020-11-03T10:51:10.6111635+02:00"
  description: Creating container
  err: 'You cannot shrink block volumes: Cannot be shrunk'
  id: 707b2d66-368d-47ce-821b-3c7b207d955a
  location: paralel-linux
  may_cancel: false
  metadata:
    block_progress: 'w10-dev-terminal: 60.69GB (133.77MB/s)'
  resources:
    containers:
    - /1.0/containers/w10-dev-terminal-ssd
    - /1.0/containers/w10-dev-terminal
    instances:
    - /1.0/instances/w10-dev-terminal-ssd
    - /1.0/instances/w10-dev-terminal
  status: Failure
  status_code: 400
  updated_at: "2020-11-03T10:58:45.989594018+02:00"
timestamp: "2020-11-03T10:58:49.028480608+02:00"
type: operation



```
