### ISSUE TITLE
`lxc delete instance --force` ramps up memory usage and freezes system momentarily

### ISSUE THREAD

**Issue by ye-yng** [lxc/lxd#8253]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-58-generic
   * LXC version: 4.9
   * LXD version: 4.9
   * Storage backend in use: ZFS

# Issue description

After upgrading to snap channel `4.9/candidate`, I noticed that when I try to `--force` delete a VM instance, LXD starts to ramp up memory (16GB) usage until the PC becomes unresponsive.

# Steps to reproduce

Create an LXD VM instance:
```
$ lxc launch ubuntu:20.04 vm-test --vm
```
Wait until the IPv4 address shows up:
```
$ lxc list
+--------------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+
|     NAME     |  STATE  |         IPV4          |                      IPV6                       |      TYPE       | SNAPSHOTS |
+--------------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+
| vm-test      | RUNNING | 10.14.76.223 (enp5s0) | fd42:5d8b:fede:b425:216:3eff:fe3c:73e2 (enp5s0) | VIRTUAL-MACHINE | 0         |
+--------------+---------+-----------------------+-------------------------------------------------+-----------------+-----------+

```

And finally force delete the instance:
```
$ lxc delete vm-test --force
```

At this point memory usage will slowly ramp up until it is at 100% capacity, leaving the system unresponsive until the following error is thrown:

```
Error: Stopping the instance failed: websocket: close 1006 (abnormal closure): unexpected EOF
```
# Information to attach

 - [x] Container log (`lxc info NAME --show-log`)
```
Name: vm-test
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/12/15 11:37 UTC
Status: Stopped
Type: virtual-machine
Profiles: default

Log:

qemu-system-x86_64: warning: 9p: degraded performance: a reasonable high msize should be chosen on client/guest side (chosen msize is <= 8192). See https://wiki.qemu.org/Documentation/9psetup#msize for details.
qemu-system-x86_64: ../util/async.c:343: aio_ctx_finalize: Assertion `flags & BH_DELETED' failed.
```
 - [x] Container configuration (`lxc config show NAME --expanded`)
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20201210)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20201210"
  image.type: disk-kvm.img
  image.version: "20.04"
  volatile.base_image: 5f7cb0463720be7bf5c81018f5a1cbeace78e1c38bb2e8fb9a6a545aadc43fe3
  volatile.eth0.hwaddr: 00:16:3e:3c:73:e2
  volatile.last_state.power: STOPPED
  volatile.uuid: 90fced9c-d77a-4e98-93c7-5bc2e4c43a5d
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: lxd-pool
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
