### ISSUE TITLE
lxd import breaks container's quota and disk usage

### ISSUE THREAD

**Issue by kautMaks** [lxc/lxd#8280]
* Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-58-generic
   * LXC version: 4.0.5
   * LXD version: 4.9
   * Storage backend in use: dir

# Issue description
lxd import breaks container's quota and disk usage

# Steps to reproduce
1. `lxc launch ubuntu:18.04 test`

Output of `repquota -avugPs`:
```
                        Space limits                File limits
Project         used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
#10097    --    751M      0K 1048576T          36034     0     0 
```

Output of `lxc info test | grep -A1 'Disk usage'`:
```
  Disk usage:
    root: 786.60MB
```
2. `lxc config device add test root disk pool=default path=/ size=8GiB`
Output of `repquota -avugPs`:
```
                        Space limits                File limits
Project         used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
#10097    --    751M      0K   8192M          36034     0     0
```

3. `lxc stop test`
4. `cp -r /var/lib/lxd/storage-pools/default/containers/test /root/`
5. `lxc delete test`
6. `lxc init --empty test`
7. `cp -r /root/test /var/lib/lxd/storage-pools/default/containers/`
8. `lxd import test --force`
9. `lxc start test`
Now, there is no disk usage section in `lxc info test`.
And no limit for root disk device, dispite that `size: 8GiB` presents in config.

Output of `lxc config show test`:
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20201211.1)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20201211.1"
  image.type: squashfs
  image.version: "18.04"
  volatile.base_image: 95c0e536d361eb5ac953ad343e0342c2f615e4aea714ca8a64126a228b809cae
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 7c124836-a129-490b-85ac-96307e48c833
devices:
  root:
    path: /
    pool: default
    size: 8GiB
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

Output of `lxc info test`:
```
Name: test
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/12/23 21:35 UTC
Status: Running
Type: container
Profiles: default
Pid: 685048
Ips:
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 31
  CPU usage:
    CPU usage (in seconds): 4
  Memory usage:
    Memory (current): 59.24MB
    Memory (peak): 85.91MB
  Network usage:
    lo:
      Bytes received: 512B
      Bytes sent: 512B
      Packets received: 8
      Packets sent: 8
```

Output of `repquota -avugPs`:
```
                        Space limits                File limits
Project         used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
#10098    --    757M      0K 1048576T          36036     0     0
```

10.` lxc config device set test root size 16GiB`

Output of `repquota -avugPs`:
```
                        Space limits                File limits
Project         used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
#10098    --    757M      0K 1048576T          36036     0     0       
#10099    --      0K         0K  16384M                 0        0     0  
```
Output of `lxc exec test -- df -h | grep -w '/'`:
```
/dev/md1        684G  333G  317G  52% /
```

Disk usage not shows in `lxc info test`

11. `lxc copy test test2`
lxc copy fix all problems in copy CT

Output of `repquota -avugPs`:
```
                        Space limits                File limits
Project         used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
#10098    --    757M      0K 1048576T          36036     0     0       
#10099    --      0K      0K  16384M              0     0     0       
#10100    --    747M      0K  16384M          36036     0     0 
```

Output of `lxc info test2 | grep -A1 'Disk usage'`:
```
  Disk usage:
    root: 782.48MB
```

Output of `lxc exec test2 -- df -h | grep -w '/'`:
```
/dev/md1         16G  747M   16G   5% /
```

# Information to attach
FS - ext4 with prjquota enabled
```
# tune2fs -l /dev/md2 | grep features
Filesystem features:      has_journal ext_attr resize_inode dir_index filetype needs_recovery extent 64bit flex_bg sparse_super large_file huge_file dir_nlink extra_isize quota metadata_csum project
```
```
# mount | grep /dev/md1
/dev/md1 on /var/lib/lxd type ext4 (rw,relatime,lazytime,prjquota)
```
