### ISSUE TITLE
Missing CPU name and vendor values when curl unix.socket

### ISSUE THREAD

**Issue by tai271828** [lxc/lxd#8339]
# Required information

 * Distribution: Ubuntu Server
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:

```
  kernel: Linux
  kernel_architecture: aarch64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "false"
    unpriv_fscaps: "true"
  kernel_version: 4.15.0-130-generic
```
The system installed the lxd snap (with core18)

```
lxd     4.10        18886  latest/stable  canonical✓  -
```

# Issue description

Failed to fetch cpu name and vendor name.

Please note `lxd.log` was collected on an TaiShan 2280 V2 ARM server (lab codename: kreiken), and this could
 be reproduced on many different arm servers.

The whole context comes from [this launchpad bug report LP:#1897946](https://bugs.launchpad.net/maas/+bug/1897946) and we were redirected to here according to the comment#3 of this LP issue.

# Steps to reproduce

To show the expected cpu name:
```
curl -G --unix-socket "/var/snap/lxd/common/lxd/unix.socket" "lxd/1.0/resources" 2>/dev/null  | jq .metadata.cpu.sockets[0].name
```

To show the expected vendor name:
```
curl -G --unix-socket "/var/snap/lxd/common/lxd/unix.socket" "lxd/1.0/resources" 2>/dev/null  | jq .metadata.cpu.sockets[0].vendor
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

[lxd.log](https://github.com/lxc/lxd/files/5821833/lxd.log)
