### ISSUE TITLE
Unable to start VM after reboot, "User 'lxd' does not exist" error (but it does exist on the host)

### ISSUE THREAD

**Issue by cmars** [lxc/lxd#8407]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info":
```
  driver: lxc
  driver_version: 4.0.6
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "false"
    unpriv_fscaps: "true"
  kernel_version: 4.15.0-135-generic
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "18.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: opcube
  server_pid: 2372
  server_version: 4.0.4
  storage: zfs
  storage_version: 0.7.5-1ubuntu16.10
```

# Issue description

Unable to start VM after reboot. Recently upgraded nvidia dkms drivers, but not sure if that's related.

$ lxc start wgdev
Error: Failed to run: forklimits limit=memlock:unlimited:unlimited -- /snap/lxd/19032/bin/qemu-system-x86_64 -S -name wgdev -uuid 528c2bf8-9eff-4024-85a4-bcc5b041834e -daemonize -cpu host -nographic -serial chardev:console -nodefaults -no-reboot -no-user-config -sandbox on,obsolete=deny,elevateprivileges=allow,spawn=deny,resourcecontrol=deny -readconfig /var/snap/lxd/common/lxd/logs/wgdev/qemu.conf -pidfile /var/snap/lxd/common/lxd/logs/wgdev/qemu.pid -D /var/snap/lxd/common/lxd/logs/wgdev/qemu.log -chroot /var/snap/lxd/common/lxd/virtual-machines/wgdev -smbios type=2,manufacturer=Canonical Ltd.,product=LXD -runas lxd: qemu-system-x86_64: -runas lxd: User "lxd" doesn't exist (and is not <uid>:<gid>)
: Process exited with a non-zero value
Try `lxc info --show-log wgdev` for more info

Despite the error message, there is a lxd user and group.

```
/etc/passwd:lxd:x:105:65534::/var/lib/lxd/:/bin/false
/etc/group:lxd:x:108:op
```

# Information to attach

 - [X] Any relevant kernel output (`dmesg`)

Problem with apparmor?

[  430.940055] audit: type=1400 audit(1612036089.523:103): apparmor="DENIED" operation="open" profile="lxd-wgdev_</var/snap/lxd/common/lxd>" name="/var/lib/snapd/hostfs/etc/passwd" pid=5903 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

 - [X] Container log (`lxc info NAME --show-log`)

```
$ lxc info wgdev --show-log
Name: wgdev
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/09/22 21:49 UTC
Status: Stopped
Type: virtual-machine
Profiles: default
Error: open /var/snap/lxd/common/lxd/logs/wgdev/qemu.log: no such file or directory
```

 - [X] Container configuration (`lxc config show NAME --expanded`)
```
$ lxc config show wgdev --expanded
architecture: x86_64
config:
  boot.autostart: "true"
  image.architecture: amd64
  image.description: Ubuntu bionic amd64 (20200922_07:42)
  image.os: Ubuntu
  image.release: bionic
  image.serial: "20200922_07:42"
  image.type: disk-kvm.img
  limits.cpu: "12"
  limits.memory: 20GiB
  volatile.base_image: 51f2de40ed9c48808327b57daf51354fbfc172114feb4814c71d52f2d5fd1449
  volatile.eth0.hwaddr: 00:16:3e:3f:de:6a
  volatile.last_state.power: STOPPED
  volatile.vm.uuid: 528c2bf8-9eff-4024-85a4-bcc5b041834e
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    size: 32GB
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

 - [X] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
Same error as when trying to start the VM. Not sure what the unsafe cache I/O error is.

t=2021-01-30T19:43:52+0000 lvl=warn msg="Using unsafe cache I/O with /dev/zd0" 
t=2021-01-30T19:43:53+0000 lvl=eror msg="Failed to start instance 'wgdev': Failed to run: forklimits limit=memlock:unlimited:unlimited -- /snap/lxd/19032/bin/qemu-system-x86_64 -S -name wgdev -uuid 528c2bf8-9eff-4024-85a4-bcc5b041834e -daemonize -cpu host -nographic -serial chardev:console -nodefaults -no-reboot -no-user-config -sandbox on,obsolete=deny,elevateprivileges=allow,spawn=deny,resourcecontrol=deny -readconfig /var/snap/lxd/common/lxd/logs/wgdev/qemu.conf -pidfile /var/snap/lxd/common/lxd/logs/wgdev/qemu.pid -D /var/snap/lxd/common/lxd/logs/wgdev/qemu.log -chroot /var/snap/lxd/common/lxd/virtual-machines/wgdev -smbios type=2,manufacturer=Canonical Ltd.,product=LXD -runas lxd: qemu-system-x86_64: -runas lxd: User \"lxd\" doesn't exist (and is not <uid>:<gid>)\n: Process exited with a non-zero value" 
t=2021-01-30T19:44:04+0000 lvl=warn msg="Using unsafe cache I/O with /dev/zd0" 
t=2021-01-30T19:45:12+0000 lvl=warn msg="Using unsafe cache I/O with /dev/zd0" 
t=2021-01-30T19:48:09+0000 lvl=warn msg="Using unsafe cache I/O with /dev/zd0" 

 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
