### ISSUE TITLE
Restarting LXC CT fails sometimes with network errors

### ISSUE THREAD

**Issue by kautMaks** [lxc/lxd#8427]
* Distribution: Ubuntu
 * Distribution version: 20.04
 * Kernel version: 5.4.0-42-generic
 * LXC version: 4.0.6
 * LXD version: 4.10
 * Storage backend in use: dir

# Issue description
I am using LXD with ~500 LXC CTs on one node. Network on CTs configured as ipvlan.
Sometimes, `lxc restart {someCT}` fails with such errors in log:
```
lxc testct 20210204161716.279 ERROR    network - network.c:setup_ipv4_addr:3383 - Address already in use - Failed to setup ipv4 address for network device with ifindex 838
lxc testct 20210204161716.279 ERROR    network - network.c:lxc_network_setup_in_child_namespaces_common:3425 - Address already in use - Failed to setup ip addresses for network device "eth0"
lxc testct 20210204161716.279 ERROR    network - network.c:lxc_setup_network_in_child_namespaces:3535 - Address already in use - Failed to setup netdev
lxc testct 20210204161716.279 ERROR    conf - conf.c:lxc_setup:3296 - Failed to setup network
lxc testct 20210204161716.279 ERROR    start - start.c:do_start:1218 - Failed to setup container "testct"
lxc testct 20210204161716.279 ERROR    sync - sync.c:__sync_wait:36 - An error occurred in another process (expected sequence number 5)
lxc testct 20210204161716.289 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:859 - Received container state "ABORTING" instead of "RUNNING"
lxc testct 20210204161716.289 ERROR    start - start.c:__lxc_start:1999 - Failed to spawn container "testct"
lxc testct 20210204161716.289 WARN     start - start.c:lxc_abort:1012 - No such process - Failed to send SIGKILL via pidfd 30 for process 4024181

```
After that, `lxc start testct` also fails with such errors.
After about a minute of waiting, CT starting normally and everything works.

It's really hard to reproduce in "test conditions", but in often appears randomly on different CTs.

**Comment by brauner** [comment]
@tomponline, @stgraber, this feels like an issue of not setting `SO_REUSEADDR`?

**Comment by tomponline** [comment]
Please show output of 'lxc config show <instance> --expanded' for one of the problem containers to show your device config.

**Comment by tomponline** [comment]
> @tomponline, @stgraber, this feels like an issue of not setting `SO_REUSEADDR`?

I thought that was to do with listening on an IP rather than adding an address?

**Comment by tomponline** [comment]
Also lxd doesn't normally set an address in liblxc as it uses dhcp except for things like routed nic and ipvlan so will confirm its one of those first.

**Comment by kautMaks** [comment]
> Please show output of 'lxc config show --expanded' for one of the problem containers to show your device config.
Here is the output:
```
architecture: x86_64
config:
  boot.autostart: "false"
  limits.cpu: "4"
  limits.hugepages.1GB: 4GiB
  limits.hugepages.2MB: 100MiB
  limits.kernel.nproc: 65000:65000
  limits.memory: 8GiB
  limits.memory.enforce: hard
  limits.memory.swap: "false"
  limits.processes: "500"
  raw.lxc: lxc.cgroup.memory.oom_control=1
  volatile.eth0.last_state.created: "false"
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1279648,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1279648,"Nsid":0,"Maprange":65536}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1279648,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1279648,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1279648,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1279648,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 332aedd6-8558-4913-a120-05d0240094bf
devices:
  eth0:
    ipv4.address: IP
    ipv4.host_table: "42"
    mtu: "1500"
    name: eth0
    nictype: ipvlan
    parent: vlan2
    type: nic
  resolvconf:
    path: /etc/resolv.conf
    readonly: "true"
    source: /etc/resolv.conf
    type: disk
  root:
    path: /
    pool: default
    size: 300GiB
    type: disk
  shared:
    path: /shared
    readonly: "true"
    source: /shared
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
