### ISSUE TITLE
Can't `lxc file push` files from home directory 

### ISSUE THREAD

**Issue by cmars** [lxc/lxd#8451]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
```
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
...
  architectures:
  - x86_64
  - i686
  certificate: |
...
  driver: lxc | qemu
  driver_version: 4.0.6 | 5.2.0
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-65-generic
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: slate
  server_pid: 215974
  server_version: "4.11"
  storage: dir | zfs | btrfs
  storage_version: 1 | 0.8.3-1ubuntu12.5 | 4.15.1
```
   * Storage backend in use: dir

# Issue description

I used to be able to push files from my home directory into containers. This no longer seems to work, now I get an error:

```
$ lxc file push /home/c/.ssh/id_rsa.pub some-container/home/ubuntu/.ssh/authorized_keys
Error: open /var/lib/snapd/hostfs/home/c/.ssh/id_rsa.pub: no such file or directory
```

Looks like the path I passed to lxc got mapped to something snapd-related.

I can workaround this particular use case with `ssh-import-id` (was file-pushing the SSH public key out of convenience) but this seems like a regression.
