### ISSUE TITLE
Post snap refresh, service is stopped, socket is owned by root:root

### ISSUE THREAD

**Issue by julian-klode** [lxc/lxd#8549]
<!--
Github issues are used for bug reports. For support questions, please use [our forum](https://discuss.linuxcontainers.org).

Please fill the template below as it will greatly help us track down your issue and reproduce it on our side.  
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.
-->

# Required information

 * Distribution: Ubuntu
 * Distribution version: hirsute
 * The output of "lxc info" or if that fails: (truncated)
```
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc | qemu
  driver_version: 4.0.6 | 5.2.0
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.10.0-14-generic
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "21.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: jak-t480s
  server_pid: 551526
  server_version: "4.12"
  storage: btrfs
  storage_version: 4.15.1
```

# Issue description

lxd socket always ends up being with wrong group if service is stopped, and then lxc obviously does not work unless I run it as root and that triggers socket activation which starts the service which then changes ownership.

```
jak@jak-t480s:~/Projects/Debian/apt:1.6.y$ lxc list                                                                                                                                                                                                                                
Error: Get "http://unix.socket/1.0": dial unix /var/snap/lxd/common/lxd/unix.socket: connect: permission denied                                                                                                                                                                             
jak@jak-t480s:~/Projects/Debian/apt:1.6.y$ uptime                                                                                                                                                                                                                                           
 10:42:16 up 5 days, 18:15, 64 users,  load average: 1,14, 1,66, 1,53                                                                                                                                                                                                                       
jak@jak-t480s:~/Projects/Debian/apt:1.6.y$ ls -lh /var/snap/lxd/common/lxd/unix.socket                                                                                                                                                                                                      
srw-rw---- 1 root root 0 Mär 10 21:39 /var/snap/lxd/common/lxd/unix.socket                                                                                                                                                                                                                                                                                                                                                                                                                                       
jak@jak-t480s:~/Projects/Debian/apt:1.6.y$ systemctl status snap.lxd.daemon.service                                                                                                                                                                                                         
● snap.lxd.daemon.service - Service for snap application lxd.daemon
     Loaded: loaded (/etc/systemd/system/snap.lxd.daemon.service; static)
     Active: inactive (dead)
TriggeredBy: ● snap.lxd.daemon.unix.socket

Mär 10 20:11:56 jak-t480s lxd.daemon[216674]: t=2021-03-10T20:11:56+0100 lvl=warn msg="Detected poll(POLLNVAL) event."
Mär 10 20:19:39 jak-t480s lxd.daemon[216674]: t=2021-03-10T20:19:39+0100 lvl=warn msg="Detected poll(POLLNVAL) event."
Mär 10 21:34:47 jak-t480s systemd[1]: Stopping Service for snap application lxd.daemon...
Mär 10 21:34:47 jak-t480s lxd.daemon[3991529]: => Stop reason is: snap refresh
Mär 10 21:34:47 jak-t480s lxd.daemon[3991529]: => Stopping LXD
Mär 10 21:38:05 jak-t480s lxd.daemon[216674]: t=2021-03-10T21:38:05+0100 lvl=eror msg="Failed to start expired instance backups operation" err="LXD is shutting down"
Mär 10 21:39:48 jak-t480s lxd.daemon[216531]: => LXD exited cleanly
Mär 10 21:39:49 jak-t480s lxd.daemon[3991529]: ==> Stopped LXD
Mär 10 21:39:49 jak-t480s systemd[1]: snap.lxd.daemon.service: Succeeded.
Mär 10 21:39:49 jak-t480s systemd[1]: Stopped Service for snap application lxd.daemon.
jak@jak-t480s:~/Projects/Debian/apt:1.6.y$ systemctl status snap.lxd.daemon.unix.socket 
● snap.lxd.daemon.unix.socket - Socket unix for snap application lxd.daemon
     Loaded: loaded (/etc/systemd/system/snap.lxd.daemon.unix.socket; enabled; vendor preset: enabled)
     Active: active (listening) since Wed 2021-03-10 21:39:55 CET; 13h ago
   Triggers: ● snap.lxd.daemon.service
     Listen: /var/snap/lxd/common/lxd/unix.socket (Stream)
      Tasks: 0 (limit: 28605)
     Memory: 0B
     CGroup: /system.slice/snap.lxd.daemon.unix.socket

Mär 10 21:39:55 jak-t480s systemd[1]: Listening on Socket unix for snap application lxd.daemon.
jak@jak-t480s:~/Projects/Debian/apt:1.6.y$ systemctl start snap.lxd.daemon.service                                                             
jak@jak-t480s:~/Projects/Debian/apt:1.6.y$ lxc list                                                                                            
+------------------------+---------+----------------------+-----------------------------------------------+-----------------------+-----------+
[... works ...]
jak@jak-t480s:~/Projects/Debian/apt:1.6.y$ ls -lh /var/snap/lxd/common/lxd/unix.socket
srw-rw---- 1 root lxd 0 Mär 10 21:39 /var/snap/lxd/common/lxd/unix.socket
```

# Steps to reproduce

I don't know, get a snap refresh?

# Information to attach

I don't think any of them are relevant here

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
