### ISSUE TITLE
BTRFS with LVM storage error when launch container

### ISSUE THREAD

**Issue by mosquito** [lxc/lxd#8564]
# Required information

 * Distribution: ubuntu
 * Distribution version: 20.04 (latest upgraded)
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-67-generic
   * LXC version: 4.12
   * LXD version: 4.12
   * Storage backend in use: lvm

# Issue description

```
# lxc launch ubuntu:20.04 test -p network -p nano.docker
Creating test
Starting test
Error: Failed to query btrfs filesystem information for "/dev/mapper/ssd-containers_test": Failed to run: btrfs filesystem show /dev/mapper/ssd-containers_test: ERROR: not a valid btrfs filesystem: /var/snap/lxd/common/lxd/storage-pools/ssd.btrfs/containers/test
Try `lxc info --show-log local:test` for more info
```

After starting container I have got an error `Error: Failed to query btrfs filesystem information for "/dev/mapper/ssd-containers_test": Failed to run: btrfs filesystem show /dev/mapper/ssd-containers_test: ERROR: not a valid btrfs filesystem: /var/snap/lxd/common/lxd/storage-pools/ssd.btrfs/containers/test`

It's failed [here](https://github.com/lxc/lxd/tree/6125eca0fc3dc24da20575338f4d416aa55ce2ef/lxd/device/disk.go#L1737) because the condition didn't contain LVM checks, or check making before filesystem mounted.

Used profiles:

```yaml
# lxc profile show network
config:
  boot.autostart: "true"
description: Network profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
name: network
used_by:
- /1.0/instances/template
- /1.0/instances/test
```

```yaml
# lxc profile show nano.docker
config:
  boot.autostart.priority: "0"
  limits.cpu: "1"
  limits.cpu.allowance: 25ms/50ms
  limits.cpu.priority: "1"
  limits.memory: 512MB
  limits.memory.swap: "false"
  limits.network.priority: "0"
  limits.processes: "1000"
  raw.lxc: |
    lxc.cgroup.blkio.bfq.weight = 50
  security.nesting: "true"
description: Nano docker instance limits profile
devices:
  root:
    limits.read: 6MB
    limits.write: 6MB
    path: /
    pool: ssd.btrfs
    size: 8GB
    type: disk
name: nano.docker
used_by:
- /1.0/instances/test
```

Storage pool configuration

```yaml
# lxc storage show ssd.btrfs
config:
  lvm.use_thinpool: "false"
  lvm.vg.force_reuse: "true"
  lvm.vg_name: ssd
  source: ssd
  volatile.initial_source: ssd
  volume.block.filesystem: btrfs
  volume.block.mount_options: compress=zstd,discard,autodefrag,commit=60,datacow,datasum,flushoncommit,inode_cache,ssd,thread_pool=4,user_subvol_rm_allowed
  volume.size: 8GB
description: SSD backed storage pool with BtrFS filesystem
name: ssd.btrfs
driver: lvm
used_by:
- /1.0/instances/template
- /1.0/instances/test
- /1.0/profiles/huge.docker
- /1.0/profiles/large.docker
- /1.0/profiles/medium.docker
- /1.0/profiles/micro.docker
- /1.0/profiles/nano.docker
status: Created
locations:
- none
```

Expected behaviour:

```
# lxc launch ubuntu:20.04 test -p network -p nano.docker
Creating test
Starting test
```

# Steps to reproduce

 1. Create similar storage as described
 2. Create similar profiles as described
 3. Try to create container `lxc launch ubuntu:20.04 test -p network -p nano.docker`

# Information to attach

```
# btrfs filesystem show /var/snap/lxd/common/lxd/storage-pools/ssd.btrfs/containers/test
ERROR: not a valid btrfs filesystem: /var/snap/lxd/common/lxd/storage-pools/ssd.btrfs/containers/test
# btrfs filesystem show /
Label: none  uuid: 54ade60b-c777-42f2-b214-9fd3661d9f03
	Total devices 1 FS bytes used 4.38GiB
	devid    1 size 16.00GiB used 5.52GiB path /dev/mapper/ssd-root
```

Container doesn't restart but after retry start command write the error and boot normally

```
# lxc restart test
Error: Failed to query btrfs filesystem information for "/dev/mapper/ssd-containers_test": Failed to run: btrfs filesystem show /dev/mapper/ssd-containers_test: ERROR: not a valid btrfs filesystem: /var/snap/lxd/common/lxd/storage-pools/ssd.btrfs/containers/test
Try `lxc info --show-log test` for more info

# lxc ls
+----------+---------+------+------+-----------+-----------+
|   NAME   |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |
+----------+---------+------+------+-----------+-----------+
| test     | STOPPED |      |      | CONTAINER | 0         |
+----------+---------+------+------+-----------+-----------+

# lxc start test
Error: Failed to query btrfs filesystem information for "/dev/mapper/ssd-containers_test": Failed to run: btrfs filesystem show /dev/mapper/ssd-containers_test: ERROR: not a valid btrfs filesystem: /var/snap/lxd/common/lxd/storage-pools/ssd.btrfs/containers/test
Try `lxc info --show-log test` for more info

# lxc ls
+----------+---------+------+------+-----------+-----------+
|   NAME   |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |
+----------+---------+------+------+-----------+-----------+
| test     | RUNNING |      |      | CONTAINER | 0         |
+----------+---------+------+------+-----------+-----------+

# sleep 10
# lxc ls
+----------+---------+------------------------+------------------------------------------+-----------+-----------+
|   NAME   |  STATE  |          IPV4          |                   IPV6                   |   TYPE    | SNAPSHOTS |
+----------+---------+------------------------+------------------------------------------+-----------+-----------+
| test     | RUNNING | 192.168.128.113 (eth0) | 2a01:5a9:4af:61a9:f:338:d935:9a5a (eth0) | CONTAINER | 0         |
+----------+---------+------------------------+------------------------------------------+-----------+-----------+
```

**Comment by mosquito** [comment]
@tomponline could you please pay attention here?

**Comment by tomponline** [comment]
@mosquito your pool config seems to be mixing config keys from LVM and BTRFS pool, a scenario that is invalid and unsupported.

Here's an example of using an existing (empty) LVM volume as the backing store for a BTRFS pool:

```
pvcreate /dev/sdb
vgcreate vg0 /dev/sdb
lvcreate -n btrfspool -L 8G vg0
lxc storage create btrfs btrfs source=/dev/vg0/btrfspool
```

**Comment by tomponline** [comment]
Apparently we do support btrfs on lvm as a filesystem option, so will relook at this. My thinking was that when using BTRFS one should use a BTRFS storage pool directly.

**Comment by tomponline** [comment]
@mosquito please can you show the commands you used to create the pool so I can reproduce?

**Comment by stgraber** [comment]
This looks like a valid setup to me, the btrfs volume would only be mounted if the instance is running and you won't be able to see the mountpoint from outside the snap.

In such a setup, the only btrfs interaction that LXD should be having with it is handling filesystem resizes.

**Comment by stgraber** [comment]
@tomponline there's an entire storage pool config above. I suspect that starting from a clean VG and then creating a storage pool matching the one dumped above should do the trick.

**Comment by tomponline** [comment]
@stgraber So should we not support `limits.read` and `limits.write` in those scenarios?

**Comment by stgraber** [comment]
Ah, that explains why we're running that btrfs command.

We definitely need to have the instance volume be mounted by the time we process those kind of limits, otherwise the device that will be used for the cgroup limits will be completely wrong. This would lead to the wrong behavior not just on btrfs but for anything on lvm or ceph.

**Comment by tomponline** [comment]
I've tried reproducing this issue to no avail:

```
lxc storage create lvm lvm \
    lvm.use_thinpool=false \
    volume.block.filesystem=btrfs \
    volume.size=3GB \
    volume.block.mount_options=compress=zstd,discard,autodefrag,commit=60,datacow,datasum,flushoncommit,inode_cache,ssd,thread_pool=4,user_subvol_rm_allowed 

lxc init images:ubuntu/focal c1 -s lvm

lxc config set c1 \
    limits.cpu=1 \
    limits.cpu.allowance=25ms/50ms \
    limits.cpu.priority=1 \
    limits.memory=512MB \
    limits.memory.swap=false \
    limits.network.priority=0 \
    limits.processes=1000 \
    security.nesting=true

lxc config device set c1 root \
    limits.read=6MB \
    limits.write=6MB

lxc start c1
lxc exec c1 -- mount | grep btrfs
/dev/dm-0 on / type btrfs (rw,relatime,thread_pool=4,compress=zstd:3,ssd,flushoncommit,discard,space_cache,user_subvol_rm_allowed,autodefrag,inode_cache,commit=60,subvolid=5,subvol=/)
```

The only config item I couldn't recreate was `raw.lxc: |
    lxc.cgroup.blkio.bfq.weight = 50` as that produce a lower level liblxc start up error. But I suspect this isn't relevant to the issue, as the error should have occurred before liblxc was used.

**Comment by tomponline** [comment]
@mosquito does that set of commands above work for you?

**Comment by tomponline** [comment]
@stgraber would you expect this command to find the btrfs tool inside the snap?

```
nsenter --mount=/run/snapd/ns/lxd.mnt -- btrfs filesystem show /var/snap/lxd/common/lxd/storage-pools/lvm/containers/c1
nsenter: failed to execute btrfs: No such file or directory
```

**Comment by stgraber** [comment]
@tomponline no, you need `/snap/lxd/current/bin/btrfs` instead of `btrfs`.

**Comment by tomponline** [comment]
Ah OK so this works OK:

```
nsenter --mount=/run/snapd/ns/lxd.mnt -- /snap/lxd/current/bin/btrfs filesystem show /var/snap/lxd/common/lxd/storage-pools/lvm/containers/c1
Label: none  uuid: 7ec439cc-5b2b-4077-8c21-b26ca398cb5c
	Total devices 1 FS bytes used 186.96MiB
	devid    1 size 2.80GiB used 598.38MiB path /dev/mapper/lvm-containers_c1
```

**Comment by mosquito** [comment]
Guys, this is the only 100% working configuration method that allows you to run docker inside an unprivileged container. At the same time, right now, despite the startup error, the running container works fine, docker starts up and runs nested containers.

Why would I need to run docker inside a container? To separate and limit the consumed resources like CPU, Disk I/O, and it works right now despite the error.

I will answer the accumulated questions:
* `raw.lxc: | lxc.cgroup.blkio.bfq.weight = 50` - this is a separate problem, on kernel 5.x.x it does not start with the usual `limits.disk.priority` option, I have not studied why this is so, but it seems that the matter is in BFQ scheduler, so I got around this problem, but if you remove it, then nothing changes, the described error at startup remains.
* I have been trying for several days to find a solution to this problem, and no matter what options I try, it does not work. And the problem is in the processing logic, in the condition that I described above.

So, what I have now:
* Limitations read and write limits work correctly
* The containers are started, but the restart command stops the container, and does not start it again by dropping with an error from topic.
* Automation (ansible) smoothed this issue out a bit, but had to ignore all errors.

@tomponline I think @stgraber is right and that lvm hosted partitions should be handled the same way as if they were xfs or ext4 partitions.

**Comment by tomponline** [comment]
@mosquito yes they are handle the same now, that was my misunderstanding.

So are you saying that the container does start ok without error and its only erroring on restart. I'm a bit confused as to the exact reproducer steps at this point.

Do you get the error with my reproducer steps I posted earlier?

**Comment by mosquito** [comment]
@tomponline 

```
# lxc storage create lvm lvm \
    lvm.use_thinpool=false \
    volume.block.filesystem=btrfs \
    volume.size=3GB \
    volume.block.mount_options=compress=zstd,discard,autodefrag,commit=60,datacow,datasum,flushoncommit,inode_cache,ssd,thread_pool=4,user_subvol_rm_allowed
Storage pool lvm created

# vgs
  VG  #PV #LV #SN Attr   VSize   VFree
  hdd   1   7   0 wz--n-  <1,82t <466,36g
  lvm   1   0   0 wz--n-   4,65g    4,65g
  ssd   1  19   0 wz--n- 464,63g <227,54g

# lxc init images:ubuntu/focal c1 -s lvm
Creating c1

# lxc config set c1 \
    limits.cpu=1 \
    limits.cpu.allowance=25ms/50ms \
    limits.cpu.priority=1 \
    limits.memory=512MB \
    limits.memory.swap=false \
    limits.network.priority=0 \
    limits.processes=1000 \
    security.nesting=true

# lxc config device set c1 root \
    limits.read=6MB \
    limits.write=6MB

# lxc start c1
Error: Failed to query btrfs filesystem information for "/dev/mapper/lvm-containers_c1": Failed to run: btrfs filesystem show /dev/mapper/lvm-containers_c1: ERROR: not a valid btrfs filesystem: /var/snap/lxd/common/lxd/storage-pools/lvm/containers/c1
Try `lxc info --show-log c1` for more info
```

**Comment by mosquito** [comment]
```
# lxc info --show-log c1
Name: c1
Location: none
Remote: unix://
Architecture: x86_64
Created: 2021/03/15 17:22 UTC
Status: Running
Type: container
Profiles: default
Pid: 514897
Ips:
  eth0:	inet	192.168.128.189	veth0fa9bd07
  eth0:	inet6	2a01:4f8:160:92e1:1:d260:6f29:8cf7	veth0fa9bd07
  eth0:	inet6	fe80::216:3eff:fe8e:f5d1	veth0fa9bd07
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 13
  Disk usage:
    root: 199.15MB
  CPU usage:
    CPU usage (in seconds): 1
  Memory usage:
    Memory (current): 98.27MB
    Memory (peak): 103.05MB
  Network usage:
    eth0:
      Bytes received: 1.24kB
      Bytes sent: 1.98kB
      Packets received: 7
      Packets sent: 17
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0

Log:

lxc c1 20210315172324.131 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1129 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.c1"
lxc c1 20210315172324.133 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1129 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.c1"
lxc c1 20210315172324.139 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1550 - No such file or directory - Failed to fchownat(17, memory.oom.group, 1000000000, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )
lxc c1 20210315172324.215 ERROR    utils - utils.c:__safe_mount_beneath_at:1106 - Function not implemented - Failed to open 30(dev)
lxc c1 20210315172324.317 ERROR    utils - utils.c:__safe_mount_beneath_at:1106 - Function not implemented - Failed to open 33(full)
lxc c1 20210315172324.317 ERROR    utils - utils.c:__safe_mount_beneath_at:1106 - Function not implemented - Failed to open 33(null)
lxc c1 20210315172324.317 ERROR    utils - utils.c:__safe_mount_beneath_at:1106 - Function not implemented - Failed to open 33(random)
lxc c1 20210315172324.317 ERROR    utils - utils.c:__safe_mount_beneath_at:1106 - Function not implemented - Failed to open 33(tty)
lxc c1 20210315172324.318 ERROR    utils - utils.c:__safe_mount_beneath_at:1106 - Function not implemented - Failed to open 33(urandom)
lxc c1 20210315172324.318 ERROR    utils - utils.c:__safe_mount_beneath_at:1106 - Function not implemented - Failed to open 33(zero)
```

**Comment by mosquito** [comment]
@tomponline for similar pool with xfs filesystem it works well, but not btrfs.

```
# lxc storage show ssd.xfs
config:
  lvm.use_thinpool: "false"
  lvm.vg.force_reuse: "true"
  lvm.vg_name: ssd
  source: ssd
  volatile.initial_source: ssd
  volume.block.filesystem: xfs
  volume.block.mount_options: discard,noquota,noatime,nodiratime
  volume.size: 8GB
description: SSD backed storage pool with XFS filesystem
name: ssd.xfs
driver: lvm
used_by:
- /1.0/profiles/huge.simple
- /1.0/profiles/large.simple
- /1.0/profiles/medium.simple
- /1.0/profiles/micro.simple
- /1.0/profiles/nano.simple
status: Created
locations:
- none
```

**Comment by tomponline** [comment]
OK so now we know there is something different about your setup than mine as those steps worked fine for me inside a fresh LXD ubuntu focal VM.

**Comment by tomponline** [comment]
Is it possible to reboot the host to ensure the mounts inside the snap are clean (snap can sometimes get the mounts confused).

**Comment by mosquito** [comment]
@tomponline the lxd was configured from preseed yaml file like this:

`lxd init --preseed /var/snap/lxd/common/preseed.yaml`

<details>
  <summary>preseed.yaml</summary>
```
# cat /var/snap/lxd/common/preseed.yaml
#
# Ansible managed
#

cluster: null
config: {}
networks:
-   config:
        ipv4.address: 192.168.128.1/24
        ipv4.nat: 'true'
        ipv6.address: 2a01:4f8:160:92e1:1::1/112
        ipv6.nat: 'false'
    description: default network
    name: lxdbr0
    type: bridge
profiles:
-   config:
        boot.autostart: 'true'
    description: Network profile
    devices:
        eth0:
            name: eth0
            nictype: bridged
            parent: lxdbr0
            type: nic
    name: network
-   config:
        boot.autostart.priority: '0'
        limits.cpu: '1'
        limits.cpu.allowance: 25ms/50ms
        limits.cpu.priority: '1'
        limits.memory: 512MB
        limits.memory.swap: 'false'
        limits.network.priority: '0'
        limits.processes: '1000'
        raw.lxc: 'lxc.cgroup.blkio.bfq.weight = 50

            '
        security.nesting: 'true'
    description: Nano docker instance limits profile
    devices:
        root:
            limits.read: 6MB
            limits.write: 6MB
            path: /
            pool: ssd.btrfs
            size: 8GB
            type: disk
    name: nano.docker
-   config:
        boot.autostart.priority: '10'
        limits.cpu: '2'
        limits.cpu.allowance: 25ms/50ms
        limits.cpu.priority: '2'
        limits.memory: 512MB
        limits.memory.swap: 'false'
        limits.network.priority: '1'
        limits.processes: '2000'
        raw.lxc: 'lxc.cgroup.blkio.bfq.weight = 100

            '
        security.nesting: 'true'
    description: Micro docker instance limits profile
    devices:
        root:
            limits.read: 10MB
            limits.write: 10MB
            path: /
            pool: ssd.btrfs
            size: 12GB
            type: disk
    name: micro.docker
-   config:
        boot.autostart.priority: '0'
        limits.cpu: '2'
        limits.cpu.allowance: 50ms/50ms
        limits.cpu.priority: '3'
        limits.memory: 1GB
        limits.memory.swap: 'true'
        limits.network.priority: '2'
        limits.processes: '3000'
        raw.lxc: 'lxc.cgroup.blkio.bfq.weight = 150

            '
        security.nesting: 'true'
    description: Medium docker instance limits profile
    devices:
        root:
            limits.read: 20MB
            limits.write: 20MB
            path: /
            pool: ssd.btrfs
            size: 16GB
            type: disk
    name: medium.docker
-   config:
        boot.autostart.priority: '0'
        limits.cpu: '4'
        limits.cpu.allowance: 35ms/50ms
        limits.cpu.priority: '4'
        limits.memory: 2GB
        limits.memory.swap: 'true'
        limits.network.priority: '3'
        limits.processes: '5000'
        raw.lxc: 'lxc.cgroup.blkio.bfq.weight = 200

            '
        security.nesting: 'true'
    description: Large docker instance limits profile
    devices:
        root:
            limits.read: 30MB
            limits.write: 30MB
            path: /
            pool: ssd.btrfs
            size: 32GB
            type: disk
    name: large.docker
-   config:
        boot.autostart.priority: '0'
        limits.cpu: '4'
        limits.cpu.allowance: 50ms/50ms
        limits.cpu.priority: '5'
        limits.memory: 4GB
        limits.memory.swap: 'true'
        limits.network.priority: '5'
        limits.processes: '10000'
        raw.lxc: 'lxc.cgroup.blkio.bfq.weight = 250

            '
        security.nesting: 'true'
    description: Huge docker instance limits profile
    devices:
        root:
            limits.read: 40MB
            limits.write: 40MB
            path: /
            pool: ssd.btrfs
            size: 50GB
            type: disk
    name: huge.docker
-   config:
        boot.autostart.priority: '0'
        limits.cpu: '1'
        limits.cpu.allowance: 25ms/50ms
        limits.cpu.priority: '1'
        limits.memory: 512MB
        limits.memory.swap: 'false'
        limits.network.priority: '0'
        limits.processes: '1000'
        raw.lxc: 'lxc.cgroup.blkio.bfq.weight = 50

            '
        security.nesting: 'true'
    description: Nano docker instance limits profile
    devices:
        root:
            limits.read: 6MB
            limits.write: 6MB
            path: /
            pool: ssd.xfs
            size: 8GB
            type: disk
    name: nano.simple
-   config:
        boot.autostart.priority: '10'
        limits.cpu: '2'
        limits.cpu.allowance: 25ms/50ms
        limits.cpu.priority: '2'
        limits.memory: 512MB
        limits.memory.swap: 'false'
        limits.network.priority: '1'
        limits.processes: '2000'
        raw.lxc: 'lxc.cgroup.blkio.bfq.weight = 100

            '
        security.nesting: 'true'
    description: Micro docker instance limits profile
    devices:
        root:
            limits.read: 10MB
            limits.write: 10MB
            path: /
            pool: ssd.xfs
            size: 12GB
            type: disk
    name: micro.simple
-   config:
        boot.autostart.priority: '0'
        limits.cpu: '2'
        limits.cpu.allowance: 50ms/50ms
        limits.cpu.priority: '3'
        limits.memory: 1GB
        limits.memory.swap: 'true'
        limits.network.priority: '2'
        limits.processes: '3000'
        raw.lxc: 'lxc.cgroup.blkio.bfq.weight = 150

            '
        security.nesting: 'true'
    description: Medium docker instance limits profile
    devices:
        root:
            limits.read: 20MB
            limits.write: 20MB
            path: /
            pool: ssd.xfs
            size: 16GB
            type: disk
    name: medium.simple
-   config:
        boot.autostart.priority: '0'
        limits.cpu: '4'
        limits.cpu.allowance: 35ms/50ms
        limits.cpu.priority: '4'
        limits.memory: 2GB
        limits.memory.swap: 'true'
        limits.network.priority: '3'
        limits.processes: '5000'
        raw.lxc: 'lxc.cgroup.blkio.bfq.weight = 200

            '
        security.nesting: 'true'
    description: Large docker instance limits profile
    devices:
        root:
            limits.read: 30MB
            limits.write: 30MB
            path: /
            pool: ssd.xfs
            size: 32GB
            type: disk
    name: large.simple
-   config:
        boot.autostart.priority: '0'
        limits.cpu: '4'
        limits.cpu.allowance: 50ms/50ms
        limits.cpu.priority: '5'
        limits.memory: 4GB
        limits.memory.swap: 'true'
        limits.network.priority: '5'
        limits.processes: '10000'
        raw.lxc: 'lxc.cgroup.blkio.bfq.weight = 250

            '
        security.nesting: 'true'
    description: Huge docker instance limits profile
    devices:
        root:
            limits.read: 40MB
            limits.write: 40MB
            path: /
            pool: ssd.xfs
            size: 50GB
            type: disk
    name: huge.simple
storage_pools:
-   config:
        lvm.use_thinpool: 'false'
        lvm.vg.force_reuse: 'true'
        lvm.vg_name: ssd
        source: ssd
        volume.block.filesystem: xfs
        volume.block.mount_options: discard,noquota,noatime,nodiratime
        volume.size: 8GB
    description: SSD backed storage pool with XFS filesystem
    driver: lvm
    name: ssd.xfs
-   config:
        lvm.use_thinpool: 'false'
        lvm.vg.force_reuse: 'true'
        lvm.vg_name: ssd
        source: ssd
        volume.block.filesystem: btrfs
        volume.block.mount_options: compress=zstd,discard,autodefrag,commit=60,datacow,datasum,flushoncommit,inode_cache,ssd,thread_pool=4,user_subvol_rm_allowed
        volume.size: 8GB
    description: SSD backed storage pool with BtrFS filesystem
    driver: lvm
    name: ssd.btrfs
-   config:
        lvm.use_thinpool: 'false'
        lvm.vg.force_reuse: 'true'
        lvm.vg_name: hdd
        source: hdd
        volume.block.filesystem: btrfs
        volume.block.mount_options: compress=zstd,discard,autodefrag,commit=60,datacow,datasum,flushoncommit,inode_cache,ssd,thread_pool=4,user_subvol_rm_allowed
        volume.size: 50GB
    description: HDD backed storage pool with BtrFS filesystem
    driver: lvm
    name: hdd.btrfs
-   config:
        lvm.use_thinpool: 'false'
        lvm.vg.force_reuse: 'true'
        lvm.vg_name: hdd
        source: hdd
        volume.block.filesystem: xfs
        volume.block.mount_options: discard,noquota,noatime,nodiratime
        volume.size: 50GB
    description: HDD backed storage pool with XFS filesystem
    driver: lvm
    name: hdd.xfs
```
</details>
