### ISSUE TITLE
lxd import overrides container's disk device

### ISSUE THREAD

**Issue by kautMaks** [lxc/lxd#8619]
* Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-70-generic
   * LXC version: 4.0.6
   * LXD version: 4.12
   * Storage backend in use: dir

# Issue description

lxd import overrides container's disk device.
I set root disk device in profile:
```
lxc profile show default
devices:
  root:
    path: /
    pool: default
    size: 256GiB
    type: disk
```

When I run `lxd import {ct}`, similar device (but without "size" field) appears in container's config.
```
devices:
  root:
    path: /
    pool: default
    type: disk
```
And it leads to unlimited disk inside ct (limited only with physical size of disk on node).

# Steps to reproduce

 1. `lxc launch ubuntu:20.04 test`
 2. Output of `lxc config show test`:
 ```
 architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20210325)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20210325"
  image.type: squashfs
  image.version: "20.04"
  volatile.base_image: 46701fa2d99c72583f858c50a25f9f965f06a266b997be7a57a8e66c72b5175b
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1279648,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1279648,"Nsid":0,"Maprange":65536}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1279648,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1279648,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1279648,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1279648,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: b41a9101-2bde-40c5-b2be-c8bf051b0a08
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""
 ```
 3.. `lxd import test --force`
 4. Output of `lxc config show test`:
 ```
 architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20210325)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20210325"
  image.type: squashfs
  image.version: "20.04"
  volatile.base_image: 46701fa2d99c72583f858c50a25f9f965f06a266b997be7a57a8e66c72b5175b
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1279648,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1279648,"Nsid":0,"Maprange":65536}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1279648,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1279648,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1279648,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1279648,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: STOPPED
  volatile.uuid: b41a9101-2bde-40c5-b2be-c8bf051b0a08
devices:
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
 ```

It appears only after upgrading to LXD 4.12.
