### ISSUE TITLE
Disabled ipv6 makes lxd fail to start lxdbr0

### ISSUE THREAD

**Issue by mDfRg** [lxc/lxd#8705]
# Required information

 * Distribution: Ubuntu 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-72-generic
   * LXD version: 4.13 (snap)
   * Storage backend in use: zfs

# Issue description

I have disabled ipv6 at work due to having network issues otherwise. After update to 4.13 lxdbr0 doesn’t work (and thus lxd in general). When I start fresh (snap remove -> install again) and run lxd init after answering initial questions (even with ipv6 CIDR set to none <- ```What IPv6 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: none```)
I get the error:

```
Error: Failed to create network "lxdbr0" in project "default": Failed to setup firewall: Failed to run: ip6tables -w -t filter -I FORWARD -i lxdbr0 -j REJECT -m comment --comment generated for LXD network lxdbr0: ip6tables v1.6.1: can't initialize ip6tables table `filter': Address family not supported by protocol
Perhaps ip6tables or your kernel needs to be upgraded.
```

I have ipv6 disabled via entry in /etc/default/grub:

```
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash ipv6.disable=1"
GRUB_CMDLINE_LINUX="ipv6.disable=1"
```

Till version 4.12 my setup had been working.

**Comment by tomponline** [comment]
Can you show output of `lxc network show lxdbr0` please

**Comment by tomponline** [comment]
@mDfRg if you can set `lxc network set lxdbr0 ipv6.firewall=false` this should fix it in the short term.

**Comment by mDfRg** [comment]
```
$ lxc network show lxdbr0                                                                                          
Error: not found
```

This is after I nuked my config (that worked with previous versions). I initially thought the error was on my side so I tried to reinstall by this steps:
0. lxc export <mycontainer> mycontainer.tar.gz
1. sudo snap remove lxd
2. zfs destroy mypool/lxd
3. zpool export mypool 
4. rm /home/lxd/mypool.img (path to file where imagefile was stored)
5. reboot

Then I proceed to install everything again:
1. sudo snap install lxd
2. lxd init (my user is in lxd group)
3. output:

```
Would you like to use LXD clustering? (yes/no) [default=no]: 
Do you want to configure a new storage pool? (yes/no) [default=yes]: 
Name of the new storage pool [default=default]: 
Name of the storage backend to use (btrfs, dir, lvm, zfs, ceph) [default=zfs]: 
Create a new ZFS pool? (yes/no) [default=yes]: 
Would you like to use an existing empty block device (e.g. a disk or partition)? (yes/no) [default=no]: 
Size in GB of the new loop device (1GB minimum) [default=5GB]: 20
Would you like to connect to a MAAS server? (yes/no) [default=no]: 
Would you like to create a new local network bridge? (yes/no) [default=yes]: 
What should the new bridge be called? [default=lxdbr0]: 
What IPv4 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 
What IPv6 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: none
Would you like the LXD server to be available over the network? (yes/no) [default=no]: 
Would you like stale cached images to be updated automatically? (yes/no) [default=yes] 
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: 
Error: Failed to create network "lxdbr0" in project "default": Failed to setup firewall: Failed to run: ip6tables -w -t filter -I FORWARD -i lxdbr0 -j REJECT -m comment --comment generated for LXD network lxdbr0: ip6tables v1.6.1: can't initialize ip6tables table `filter': Address family not supported by protocol
Perhaps ip6tables or your kernel needs to be upgraded.
```

**Comment by tomponline** [comment]
@mDfRg I have a fix for this, but if you can init without a bridge and add it later then setting `ipv6.firewall=false` will fix your current version.

**Comment by mDfRg** [comment]
Great! BTW here is a probably related bug:  #2842

**Comment by mDfRg** [comment]
> @mDfRg I have a fix for this, but if you can init without a bridge and add it later then setting `ipv6.firewall=false` will fix your current version.

Emm.. Can you help me with this? How can I set this setting when I cannot set lxdbr0? I can run ```lxd init --preseed < lxd_preseed.yml ``` and not specify eth0 device at all, but how to do it beforehand? Can I set a YAML setting in preseed file? Here is my setup:

**lxd_preseed.yml**

```
config: {}
networks: []
storage_pools:
- config:
    source: lxdpool
    volatile.initial_source: lxdpool
    zfs.pool_name: lxdpool
  description: ""
  name: lxdpool
  driver: zfs
profiles:
- name: default
  description: Default LXD profile
  config: 
    boot.autostart: "false"
    boot.autostart.delay: 5
  devices:
    eth0:
      name: eth0
      network: lxdbr0
      type: nic
    root:
      path: /
      pool: lxdpool
      type: disk
```

**lxdbr0.yml**

```
config:
  ipv4.address: 10.1.100.1/24
  ipv4.nat: "true"
  ipv6.address: none
description: ""
name: lxdbr0
type: bridge
used_by: []
managed: true
status: Created
locations:
- none
```
