### ISSUE TITLE
Allow passing a path to a cert on disk when joining a cluster

### ISSUE THREAD

**Issue by dontlaugh** [lxc/lxd#8708]
This is not a bug, it's a feature request.

The cluster bootstrap docs here show how to join a cluster.https://lxd.readthedocs.io/en/latest/clustering/

But it seems that embedding a pem-encoded cert inside yaml is our only option.

Templating yaml with large strings (like certificates) is error prone. It would be friendlier to automation if a filepath could be specified instead. This would avoid the need to run `sed` to post-process the cluster cert, and embed it in yaml.

Perhaps something like "cluster_certificate_path"

```yaml
cluster:
  enabled: true
  server_name: <%= $server_name %>
  server_address: <%= $server_addr %>
  cluster_address: <%= $cluster_addr %>
  cluster_certificate_path: "<%= $certificate_path %>"
  cluster_password: <%= $trust_password %>
```
