### ISSUE TITLE
/proc/sys/fs/binfmt_misc/register: Permission denied (causing network issue)

### ISSUE THREAD

**Issue by mariarti** [lxc/lxd#8844]
# Required information

 * Distribution: ubuntu 20.04
 * Distribution version: Linux version 5.8.0-53-generic (same on 5.4.0-72-generic)
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.8.0-53
   * LXC version: 4.0.6
   * LXD version: 4.0/stable: 4.0.6
   * Storage backend in use: dir

# Issue description
Failed to bring up network up.
`[FAILED] Failed to start LSB: Supports the direct execution of binary formats..`
`See 'systemctl status jexec.service' for details.`

in `systemctl status jexec`
error
```
jexec[46]: Starting jexec servicesgrep: /proc/sys/fs/binfmt_misc/*: No such file or directory
jexec[46]: /etc/rc.d/init.d/jexec: line 173: /proc/sys/fs/binfmt_misc/register: Permission denied
systemd[1]: jexec.service: Control process exited, code=exited status=4
systemd[1]: jexec.service: Failed with result 'exit-code'.
systemd[1]: Failed to start LSB: Supports the direct execution of binary formats..
```
Weird thing, that 10 absolutely same previously created containers are working fine now, and only 2 (test1&test2) failed with networking.
BTW: container test2 works ~20 minutes fine, untill network becomes down.

Expected to see nic up and go.

# Steps to reproduce

 1. Step one
`lxc launch images:oracle/8/amd64 test1`
 2. Step two
 `# lxc exec test1 bash`
 3. Step three
`systemctl status jexec`

# Information to attach
```
+-------+--------------+--------+---------------------------------+--------------+-----------+---------+-----------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |           DESCRIPTION           | ARCHITECTURE |   TYPE    |  SIZE   |         UPLOAD DATE         |
+-------+--------------+--------+---------------------------------+--------------+-----------+---------+-----------------------------+
|       | 330250d3c989 | no     | Oracle 8 amd64 (20210602_07:55) | x86_64       | CONTAINER | 93.79MB | Jun 2, 2021 at 9:07am (UTC) |
+-------+--------------+--------+---------------------------------+--------------+-----------+---------+-----------------------------+
```
 - [x] Any relevant kernel output (`dmesg`)
 ```
[113192.789449] physjZVVN6: renamed from eth0
[113192.836703] veth9a3fb372: renamed from physjZVVN6
[113192.905606] device veth2ff1ab93 left promiscuous mode
[113192.905632] lxdbr0: port 5(veth2ff1ab93) entered disabled state
[113193.693083] kauditd_printk_skb: 20 callbacks suppressed
[113193.693084] audit: type=1400 audit(1622565235.301:88): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="lxd-test2_</var/snap/lxd/common/lxd>" pid=13284 comm="apparmor_parser"
[113216.407357] lxdbr0: port 5(veth487269cd) entered blocking state
[113216.407358] lxdbr0: port 5(veth487269cd) entered disabled state
[113216.407419] device veth487269cd entered promiscuous mode
[113216.454390] audit: type=1400 audit(1622565258.064:89): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-test1_</var/snap/lxd/common/lxd>" pid=13350 comm="apparmor_parser"
[113216.542771] physkQiIum: renamed from vethc8ff36a9
[113216.562972] eth0: renamed from physkQiIum
[113216.588251] lxdbr0: port 5(veth487269cd) entered blocking state
[113216.588253] lxdbr0: port 5(veth487269cd) entered forwarding state
[113216.817379] lxdbr0: port 5(veth487269cd) entered disabled state
[113216.840697] audit: type=1400 audit(1622565258.448:90): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxd-test1_</var/snap/lxd/common/lxd>" name="/run/systemd/unit-root/dev/" pid=13422 comm="(ostnamed)" flags="ro, nosuid, noexec, remount, strictatime"
[113261.129019] physkQiIum: renamed from eth0
[113261.186057] vethc8ff36a9: renamed from physkQiIum
[113261.285929] device veth487269cd left promiscuous mode
[113261.285948] lxdbr0: port 5(veth487269cd) entered disabled state
[113262.075957] audit: type=1400 audit(1622565303.681:91): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="lxd-test1_</var/snap/lxd/common/lxd>" pid=13601 comm="apparmor_parser"
[114443.639484] lxdbr0: port 5(veth469c6a33) entered blocking state
[114443.639485] lxdbr0: port 5(veth469c6a33) entered disabled state
[114443.639527] device veth469c6a33 entered promiscuous mode
[114443.686337] audit: type=1400 audit(1622566485.227:92): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-test1_</var/snap/lxd/common/lxd>" pid=14074 comm="apparmor_parser"
```
 - [x] Container log (`lxc info NAME --show-log`)
 ```
# lxc info test1 --show-log
Name: test1
Location: none
Remote: unix://
Architecture: x86_64
Created: 2021/05/28 14:24 UTC
Status: Running
Type: container
Profiles: default
Pid: 14075
Ips:
  lo:	inet	127.0.0.1
Resources:
  Processes: 21
  CPU usage:
    CPU usage (in seconds): 2
  Memory usage:
    Memory (current): 382.19MB
    Memory (peak): 383.74MB
  Network usage:
    eth0:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0

Log:

lxc test1 20210601165445.292 WARN     conf - conf.c:lxc_map_ids:3007 - newuidmap binary is missing
lxc test1 20210601165445.292 WARN     conf - conf.c:lxc_map_ids:3013 - newgidmap binary is missing
lxc test1 20210601165445.294 WARN     conf - conf.c:lxc_map_ids:3007 - newuidmap binary is missing
lxc test1 20210601165445.294 WARN     conf - conf.c:lxc_map_ids:3013 - newgidmap binary is missing
lxc test1 20210601165445.294 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1296 - No such file or directory - Failed to fchownat(43, memory.oom.group, 1000000000, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )
lxc test1 20210601165459.750 WARN     conf - conf.c:lxc_map_ids:3007 - newuidmap binary is missing
lxc test1 20210601165459.750 WARN     conf - conf.c:lxc_map_ids:3013 - newgidmap binary is missing
```
 - [x] Container configuration (`lxc config show NAME --expanded`)
 ```
# lxc config show test1 --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Oracle 8 amd64 (20210502_07:46)
  image.os: Oracle
  image.release: "8"
  image.serial: "20210502_07:46"
  image.type: squashfs
  image.variant: default
  volatile.base_image: 576411ebfcaf420ab198128ec38cb88067e5fc4a71c26ada136e2a6c6576588f
  volatile.eth0.host_name: veth469c6a33
  volatile.eth0.hwaddr: 00:16:3e:68:9a:f2
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 7dd2822a-78e7-4b13-a341-7a3535135d61
devices:
  eth0:
    ipv4.address: 10.10.0.15
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: storagepool1
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
 ```
 location: none
metadata:
  context:
    ip: '@'
    method: GET
    protocol: unix
    url: /1.0
    username: root
  level: dbug
  message: Handling
timestamp: "2021-06-02T16:22:50.2712233+02:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    protocol: unix
    url: /1.0/instances/test1
    username: root
  level: dbug
  message: Handling
timestamp: "2021-06-02T16:22:50.272736063+02:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    protocol: unix
    url: /1.0/events
    username: root
  level: dbug
  message: Handling
timestamp: "2021-06-02T16:22:50.274201879+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'New event listener: d8797b0f-b317-4cb0-b4b0-7ca5af467e77'
timestamp: "2021-06-02T16:22:50.274295408+02:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: PUT
    protocol: unix
    url: /1.0/instances/test1/state
    username: root
  level: dbug
  message: Handling
timestamp: "2021-06-02T16:22:50.27453269+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'New task Operation: f6b4e2b6-2b35-4f3e-8401-6d7e9c530test18'
timestamp: "2021-06-02T16:22:50.279260927+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'Started task operation: f6b4e2b6-2b35-4f3e-8401-6d7e9c530test18'
timestamp: "2021-06-02T16:22:50.279534877+02:00"
type: logging


location: none
metadata:
  class: task
  created_at: "2021-06-02T16:22:50.275253367+02:00"
  description: Starting instance
  err: ""
  id: f6b4e2b6-2b35-4f3e-8401-6d7e9c530test18
  location: none
  may_cancel: false
  metadata: null
  resources:
    instances:
    - /1.0/instances/test1
  status: Pending
  status_code: 105
  updated_at: "2021-06-02T16:22:50.275253367+02:00"
timestamp: "2021-06-02T16:22:50.279526551+02:00"
type: operation


location: none
metadata:
  class: task
  created_at: "2021-06-02T16:22:50.275253367+02:00"
  description: Starting instance
  err: ""
  id: f6b4e2b6-2b35-4f3e-8401-6d7e9c530test18
  location: none
  may_cancel: false
  metadata: null
  resources:
    instances:
    - /1.0/instances/test1
  status: Running
  status_code: 103
  updated_at: "2021-06-02T16:22:50.275253367+02:00"
timestamp: "2021-06-02T16:22:50.279697785+02:00"
type: operation


location: none
metadata:
  context:
    ip: '@'
    method: GET
    protocol: unix
    url: /1.0/operations/f6b4e2b6-2b35-4f3e-8401-6d7e9c530test18
    username: root
  level: dbug
  message: Handling
timestamp: "2021-06-02T16:22:50.280365825+02:00"
type: logging


location: none
metadata:
  context:
    driver: dir
    instance: test1
    pool: storagepool1
    project: default
  level: dbug
  message: MountInstance started
timestamp: "2021-06-02T16:22:50.280804281+02:00"
type: logging


location: none
metadata:
  context:
    driver: dir
    instance: test1
    pool: storagepool1
    project: default
  level: dbug
  message: MountInstance finished
timestamp: "2021-06-02T16:22:50.281307418+02:00"
type: logging


location: none
metadata:
  context:
    device: eth0
    instance: test1
    instanceType: container
    project: default
    type: nic
  level: dbug
  message: Starting device
timestamp: "2021-06-02T16:22:50.282138576+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: veth0b4910b3 has been added: updating network priorities'
timestamp: "2021-06-02T16:22:50.285529196+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'Scheduler: network: vethc4d2da4a has been added: updating network priorities'
timestamp: "2021-06-02T16:22:50.288551671+02:00"
type: logging


location: none
metadata:
  context:
    device: root
    instance: test1
    instanceType: container
    project: default
    type: disk
  level: dbug
  message: Starting device
timestamp: "2021-06-02T16:22:50.293008814+02:00"
type: logging


location: none
metadata:
  context:
    driver: dir
    instance: test1
    pool: storagepool1
    project: default
  level: dbug
  message: UpdateInstanceBackupFile started
timestamp: "2021-06-02T16:22:50.293554487+02:00"
type: logging


location: none
metadata:
  context:
    driver: dir
    instance: test1
    pool: storagepool1
    project: default
  level: dbug
  message: UpdateInstanceBackupFile finished
timestamp: "2021-06-02T16:22:50.294647812+02:00"
type: logging


location: none
metadata:
  context:
    action: start
    created: 2021-05-28 16:24:46.566602541 +0200 CEST
    ephemeral: "false"
    instance: test1
    instanceType: container
    project: default
    stateful: "false"
    used: 2021-06-01 18:54:45.234426291 +0200 CEST
  level: info
  message: Starting container
timestamp: "2021-06-02T16:22:50.294700414+02:00"
type: logging


location: none
metadata:
  context:
    ip: '@'
    method: GET
    protocol: unix
    url: /internal/containers/test1/onstart?project=default
    username: root
  level: dbug
  message: Handling
timestamp: "2021-06-02T16:22:50.329754434+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'Scheduler: container test1 started: re-balancing'
timestamp: "2021-06-02T16:22:50.335179395+02:00"
type: logging


location: none
metadata:
  action: instance-started
  source: /1.0/instances/test1
timestamp: "2021-06-02T16:22:50.574167846+02:00"
type: lifecycle


location: none
metadata:
  context:
    action: start
    created: 2021-05-28 16:24:46.566602541 +0200 CEST
    ephemeral: "false"
    instance: test1
    instanceType: container
    project: default
    stateful: "false"
    used: 2021-06-01 18:54:45.234426291 +0200 CEST
  level: info
  message: Started container
timestamp: "2021-06-02T16:22:50.574159309+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'Success for task operation: f6b4e2b6-2b35-4f3e-8401-6d7e9c530test18'
timestamp: "2021-06-02T16:22:50.574178357+02:00"
type: logging


location: none
metadata:
  class: task
  created_at: "2021-06-02T16:22:50.275253367+02:00"
  description: Starting instance
  err: ""
  id: f6b4e2b6-2b35-4f3e-8401-6d7e9c530test18
  location: none
  may_cancel: false
  metadata: null
  resources:
    instances:
    - /1.0/instances/test1
  status: Success
  status_code: 200
  updated_at: "2021-06-02T16:22:50.275253367+02:00"
timestamp: "2021-06-02T16:22:50.574455132+02:00"
type: operation


location: none
metadata:
  context: {}
  level: dbug
  message: 'Event listener finished: d8797b0f-b317-4cb0-b4b0-7ca5af467e77'
timestamp: "2021-06-02T16:22:50.575344135+02:00"
type: logging


location: none
metadata:
  context: {}
  level: dbug
  message: 'Disconnected event listener: d8797b0f-b317-4cb0-b4b0-7ca5af467e77'
timestamp: "2021-06-02T16:22:50.575451637+02:00"
type: logging
```

**Comment by stgraber** [comment]
binfmt_misc isn't namespaced so the permission error is expected. This could then in turn block some stuff from starting up maybe causing your other symptoms.

Do you get the same network issue with a container which doesn't use that particular piece of software?

**Comment by mariarti** [comment]
Thanks for the clarification
I was most likely misled by the first part of the title (Indeed, the network disappeared during the installation of the JDK11 ).
I created a new container test3 with oraсle 8, assigned network, but networking still does not work. (at the meantime 10 other containers based on linux oracle 8 work fine )

So, logs from test3:
```
# lxc config show test3 --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Oracle 8 amd64 (20210602_07:55)
  image.os: Oracle
  image.release: "8"
  image.serial: "20210602_07:55"
  image.type: squashfs
  image.variant: default
  volatile.base_image: 330250d3c9891ffbed26a5b2b61459d8b491c35257712b837ef8bab9a7f49d9e
  volatile.eth0.host_name: vethd72140bb
  volatile.eth0.hwaddr: 00:16:3e:f7:90:a8
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: da63091a-ab6c-4671-95b4-afd888d87fe3
devices:
  eth0:
    ipv4.address: 10.10.0.16
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: storagepool1
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
```
# lxc info test3 --show-log
Name: test3
Location: none
Remote: unix://
Architecture: x86_64
Created: 2021/06/02 16:21 UTC
Status: Running
Type: container
Profiles: default
Pid: 23646
Ips:
  lo:	inet	127.0.0.1
Resources:
  Processes: 8
  CPU usage:
    CPU usage (in seconds): 0
  Memory usage:
    Memory (current): 29.60MB
    Memory (peak): 34.25MB
  Network usage:
    eth0:
      Bytes received: 1.92kB
      Bytes sent: 0B
      Packets received: 26
      Packets sent: 0
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0

Log:

lxc test3 20210602162311.847 WARN     conf - conf.c:lxc_map_ids:3007 - newuidmap binary is missing
lxc test3 20210602162311.847 WARN     conf - conf.c:lxc_map_ids:3013 - newgidmap binary is missing
lxc test3 20210602162311.848 WARN     conf - conf.c:lxc_map_ids:3007 - newuidmap binary is missing
lxc test3 20210602162311.848 WARN     conf - conf.c:lxc_map_ids:3013 - newgidmap binary is missing
lxc test3 20210602162311.848 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1296 - No such file or directory - Failed to fchownat(43, memory.oom.group, 1000000000, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )
lxc test3 20210602163324.210 WARN     conf - conf.c:lxc_map_ids:3007 - newuidmap binary is missing
lxc test3 20210602163324.210 WARN     conf - conf.c:lxc_map_ids:3013 - newgidmap binary is missing
```
`dmesg` from host
```
[198826.139618] audit: type=1400 audit(1622650863.270:107): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-test3_</var/snap/lxd/common/lxd>" pid=23148 comm="apparmor_parser"
[198826.217535] physROZEBs: renamed from veth2609a7b8
[198826.247293] eth0: renamed from physROZEBs
[198826.277592] lxdbr0: port 5(vethc9db2686) entered blocking state
[198826.277597] lxdbr0: port 5(vethc9db2686) entered forwarding state
[198826.566092] audit: type=1400 audit(1622650863.698:108): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxd-test3_</var/snap/lxd/common/lxd>" name="/run/systemd/unit-root/dev/" pid=23356 comm="(ostnamed)" flags="ro, nosuid, noexec, remount, strictatime"
[198851.583094] physROZEBs: renamed from eth0
[198851.607083] lxdbr0: port 5(vethc9db2686) entered disabled state
[198851.615088] veth2609a7b8: renamed from physROZEBs
[198851.705919] device vethc9db2686 left promiscuous mode
[198851.705940] lxdbr0: port 5(vethc9db2686) entered disabled state
[198852.493551] audit: type=1400 audit(1622650889.624:109): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="lxd-test3_</var/snap/lxd/common/lxd>" pid=23503 comm="apparmor_parser"
[198954.634243] lxdbr0: port 5(vethd72140bb) entered blocking state
[198954.634244] lxdbr0: port 5(vethd72140bb) entered disabled state
[198954.634298] device vethd72140bb entered promiscuous mode
[198954.681846] audit: type=1400 audit(1622650991.807:110): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-test3_</var/snap/lxd/common/lxd>" pid=23645 comm="apparmor_parser"
[198954.760495] physeAKxfP: renamed from veth3848b589
[198954.790057] eth0: renamed from physeAKxfP
[198954.832411] lxdbr0: port 5(vethd72140bb) entered blocking state
[198954.832415] lxdbr0: port 5(vethd72140bb) entered forwarding state
[198955.116962] audit: type=1400 audit(1622650992.243:111): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxd-test3_</var/snap/lxd/common/lxd>" name="/run/systemd/unit-root/dev/" pid=23849 comm="(ostnamed)" flags="ro, nosuid, noexec, remount, strictatime"
```
