### ISSUE TITLE
LVM storage problem - all container  stopped

### ISSUE THREAD

**Issue by esosan** [lxc/lxd#8904]
# Required information

 * Distribution: ubuntu
 * Distribution version: 18.04.4
 * The output of "lxc info" or if that fails:
   * Kernel version:4.15.0-144-generic
   * LXC version: 4.15
   * LXD version: 4.15
   * Storage backend in use: LVM (xfs/no thinpool)

# Issue description

All Containers doesn't start anymore. Seems to be a LVM problem. But all PVS and VGS are present

```
Error: Failed preparing container for start: Failed to activate LVM logical volume "/dev/pool_0/containers_iceCast": Failed to run: lvchange --activate y --ignoreactivationskip /dev/pool_0/containers_iceCast: Volume group "pool_0" not found
  Cannot process volume group pool_0
```

**Comment by tomponline** [comment]
Closing in place of https://discuss.linuxcontainers.org/t/lvm-storage-problem-all-container-stopped-and-doesnt-start-anymore/11358, support issues are better handled on the forum. Thanks.

**Comment by tomponline** [comment]
Reopening as after discussion on https://discuss.linuxcontainers.org/t/lvm-storage-problem-all-container-stopped-and-doesnt-start-anymore/11358 it seems that enabling:

```
sudo snap set lxd lvm.external=true
sudo systemctl reload snap.lxd.daemon
``` 

Fixes the LVM issue, but it should not be required. Suggesting a core20 snap issue. 

Also related to https://github.com/lxc/lxd/issues/8905

**Comment by tomponline** [comment]
@esosan please can you switch back to the snap's LVM tools using:

```


sudo snap set lxd lvm.external=false
sudo systemctl reload snap.lxd.daemon
```

And then check your back in a situation where the containers dont start with the error "Cannot process volume group pool_0"

Then can you run:

```
sudo nsenter --mount=/run/snapd/ns/lxd.mnt -- bash
LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/ /snap/lxd/current/bin/lvs
```

**Comment by esosan** [comment]
`LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/ /snap/lxd/current/bin/lvs
  LV             VG Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  home           vg -wi-ao---- <19.53g                                                    
  lxc_pool00     vg -wi-ao----  60.00g                                                    
  lxc_pool01     vg -wi-ao----  20.00g                                                    
  lxc_poolOC00   vg -wi-ao---- 220.00g                                                    
  lxc_pooldata00 vg -wi-ao----  50.00g                                                    
  lxc_pooldata01 vg -wi-a-----  50.00g     `

**Comment by tomponline** [comment]
Interesting, can you do the same but run `vgs` instead.

**Comment by esosan** [comment]
bash: vgs: command not found

(when I return to lvm.external=false the containers continue to be RUNNING.)

**Comment by tomponline** [comment]
I meant like this:

```
LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/ sudo --preserve-env=LD_LIBRARY_PATH nsenter --mount=/run/snapd/ns/lxd.mnt -- /snap/lxd/current/bin/vgs
```

**Comment by esosan** [comment]
```
sudo nsenter --mount=/run/snapd/ns/lxd.mnt -- bash
root@olivia3:/# LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/ sudo --preserve-env=LD_LIBRARY_PATH nsenter --mount=/run/snapd/ns/lxd.mnt -- /snap/lxd/current/bin/vgs
sudo: unable to stat /etc/sudoers: No such file or directory
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
```

**Comment by tomponline** [comment]
OK looks your sudo isnt happy.

Try this:

```
sudo nsenter --mount=/run/snapd/ns/lxd.mnt -- bash
LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/ /snap/lxd/current/bin/vgs
```

**Comment by esosan** [comment]
```
LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/ /snap/lxd/current/bin/vgs
  VG #PV #LV #SN Attr   VSize  VFree 
  vg   1   6   0 wz--n- <1.80t <1.39t
```

**Comment by tomponline** [comment]
OK so there's the problem then, inside the snap, your pool_0 pool volume group isn't being detected.

I suspect this is due to a change in the lvm tooling in the core20 base snap that is for some reason not doing a scan of available pools when we run the lvs or vgs commands. We may need to look at modifying the command we run or use a custom config file inside the snap. For now using the external fix I suggested earlier will ensure LXD uses your host's tooling.

**Comment by esosan** [comment]
ok, great. If you need further testing, I am of course available!

**Comment by stgraber** [comment]
@esosan can you show the `lxc storage show NAME` output for your pool?

**Comment by tomponline** [comment]
@stgraber its in the forum post:

```
lxc storage show pool0

config:
  lvm.use_thinpool: "false"
  lvm.vg_name: pool_0
  source: pool_0
  volatile.initial_source: pool_0
  volume.block.filesystem: xfs
  volume.size: "3221225472"
description: ""
name: pool0
driver: lvm
used_by:
- /1.0/instances/gdg
- /1.0/instances/git
- /1.0/instances/iceCast
- /1.0/instances/m-clamav
- /1.0/instances/m-clamavOLD
- /1.0/instances/m-dcc
- /1.0/instances/m-dcot
- /1.0/instances/m-pfix
- /1.0/instances/m-spam18
- /1.0/instances/mysql
- /1.0/instances/named
- /1.0/instances/owncloud
- /1.0/instances/rCube
- /1.0/instances/rCube14
- /1.0/instances/redis
- /1.0/instances/solr
- /1.0/instances/www-ext
- /1.0/instances/www-std
- /1.0/instances/wwwHurdega
- /1.0/profiles/default
- /1.0/storage-pools/pool0/volumes/custom/git_data
status: Created
locations:
- none
-
```
