### ISSUE TITLE
CephFS disk device does not work with modern(?) ceph.conf

### ISSUE THREAD

**Issue by mmeier86** [lxc/lxd#9042]
<!--
Github issues are used for bug reports. For support questions, please use [our forum](https://discuss.linuxcontainers.org).

Please fill the template below as it will greatly help us track down your issue and reproduce it on our side.  
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.
-->

# Required information

 * Distribution: Arch Linux
 * Distribution version: N/A
 * The output of "lxc info":
```
  driver: lxc | qemu                                                                                                                                                                                                                          
  driver_version: 4.0.9 | 5.2.0                                                                                                                                                                                                               
  firewall: xtables                                                                                                                                                                                                                           
  kernel: Linux                                                                                                                                                                                                                               
  kernel_architecture: x86_64                                                                                                                                                                                                                 
  kernel_features:                                                                                                                                                                                                                            
    netnsid_getifaddrs: "true"                                                                                                                                                                                                                
    seccomp_listener: "true"                                                                                           
    seccomp_listener_continue: "true"                                                                                                                                                                                                         
    shiftfs: "false"                                                                                                                                                                                                                          
    uevent_injection: "true"                                                                                                                                                                                                                  
    unpriv_fscaps: "true"                                                                                                                                                                                                                     
  kernel_version: 5.12.12-arch1-1                                                                                                                                                                                                             
  lxc_features:                                            
    cgroup2: "true"                                                                                                                                                                                                                           
    devpts_fd: "true"                                                                                                                                                                                                                         
    mount_injection_file: "true"                                                                                                                                                                                                              
    network_gateway_device_route: "true"                                                                                                                                                                                                      
    network_ipvlan: "true"                                                                                                                                                                                                                    
    network_l2proxy: "true"                                                                                            
    network_phys_macvlan_mtu: "true"                                                                                                                                                                                                          
    network_veth_router: "true"                                                                                        
    pidfd: "true"                                                                                                                                                                                                                             
    seccomp_allow_deny_syntax: "true"                                                                                                                                                                                                         
    seccomp_notify: "true"                                                                                                                                                                                                                    
    seccomp_proxy_send_notify_fd: "true"                                                                               
  os_name: Arch Linux                                                                                                  
  os_version: ""                                                                                                       
  project: default                                         
  server: lxd                                                                                                                                                                                                                                 
  server_clustered: false                                                                                              
  server_name: osiris                                      
  server_pid: 1142                                                                                                     
  server_version: "4.15"                                                                                               
  storage: lvm | ceph                                                                                                  
  storage_version: 2.03.12(2) (2021-05-07) / 1.02.177 (2021-05-07) / 4.44.0 | ceph                                                                                                                                                            
    version 15.2.12 (ce065eabfa5ce81323b009786bdf5bb03127cbe1) octopus (stable)          

```

My Ceph cluster is running version 15.2.12.

# Issue description

I'm trying to mount a `CephFS` disk device into a LXC VM. This fails.

The error message looks like this:

`Error: Failed to start device "warehouse": Unable to mount [v2:10.86.5.102:3300/0:6789,v1:10.86.5.102:6789/0]:/volumes/_nogroup/warehouse/6e79ee7c-2b90-4d49-97ce-b9e9bf69e3b6 at /var/lib/lxd/devices/playground/disk.warehouse.mnt-warehouse: invalid argument`

NOTE: I'm trying to mount what I think is called a `custom volume`(?), so I created the volume in Ceph manually, it is not coming from a LXC managed CephFS storage pool.

The relevant part of the VM's `lxc config show` output looks like this:

```
devices:
  warehouse:
    ceph.cluster_name: ceph
    ceph.user_name: osiris-mounts
    path: /mnt/warehouse
    source: cephfs:homenet-fs/volumes/_nogroup/warehouse/6e79ee7c-2b90-4d49-97ce-b9e9bf69e3b6
    type: disk
```

The following error message appears in the kernel logs:
`ceph: No path or : separator in source`

My `ceph.conf` file looks like this: 
```
[global]
        fsid = a84c7196-7ebf-11eb-b290-18c04d00217f
        mon_host = [v2:10.86.5.102:3300/0,v1:10.86.5.102:6789/0]
```

I believe the problem is simply in the way that lxc parses the `ceph.conf` file in the following code:

https://github.com/lxc/lxd/blob/4e1b322e1987092537a101d43dc4fec815ef9bc0/lxd/device/device_utils_disk.go#L199-L292

Here, the `mon_host`s are parsed, but it looks like the code doesn't handle having v1 and v2 mon specs in the same config file?

The following command works to mount that directory on the same machine manually:
`mount -t ceph "10.86.5.102:3300,10.86.5.102:6789:/volumes/_nogroup/warehouse/6e79ee7c-2b90-4d49-97ce-b9e9bf69e3b6" /mnt/warehouse -o name=my-keyring`

In comparison, I had to do the following changes to the `mon_host` value from the `ceph.conf` file:

- Remove the `[]` brackets around the IPs
- Remove the `v1:/v2:` in front of the IPs
- Remove the `/0` from the end of the IPs

I can see two possibilities to fix this:

1. Adapt the `ceph.conf` parsing code
2. Just don't set the mon hosts at all, using the shortened `:/path/to/cephfs` to get the ceph mount helper to read the `ceph.conf` file. I'm not sure how well that would work, from what I see in the code you're using a golang function, not directly called mount, and I have no idea whether that would use the mount helper?

One thing to note: I'm also using Ceph RBD volumes, also as "custom volumes" mounted into some VMs with `disk` devices and not controlled by LXC storage pools, and those work flawlessly with the `ceph.conf` above. From what I see the difference might be that for those, you don't try to parse `ceph.conf`?

# Steps to reproduce

 1. Set up a Ceph cluster (I'm using Ceph v15.2.12)
 2. Create a Ceph FS in that cluster
 3. Run `ceph config generate-minimal-conf` to get a ceph.conf file
 4. Try to add the Ceph FS as a disk device to a VM with `lxc config device add`
 5. Observe that it doesn't work

**EDIT** Noted that I use version 15.2.12 in my cluster.
