### ISSUE TITLE
nested focal containers - snapd broken

### ISSUE THREAD

**Issue by wallyworld** [lxc/lxd#9099]
Not sure if this should be filed here or against snapd. This showed up because we use a focal or bionic LXD container to host nested LXD containers and in those nested containers snap install things. For nested bionic containers, everything works. But nested focal containers have started to have an issue with completing the snapd seeding.

# Issue description

It seems recently something broke with nested focal containers and snapd seeding. This happens on LXD 4.16 and 4.17. There is a manual step required to unblock things. On a bionic or focal host:
```
lxc launch ubuntu:focal
lxc config set <container> security.nesting true
lxc exec <container> -- bash
lxd init
lxc launch ubuntu:focal
lxc exec <container-nested> -- bash
snap install <somesnap>
error: system does not fully support snapd: apparmor detected but insufficient permissions to use it

systemctl list-jobs
JOB UNIT                                 TYPE  STATE  
96  snapd.autoimport.service             start waiting
112 snapd.seeded.service                 start running
2   multi-user.target                    start waiting
1   graphical.target                     start waiting
126 cloud-config.service                 start waiting
109 systemd-update-utmp-runlevel.service start waiting
122 cloud-init.target                    start waiting
125 cloud-final.service                  start waiting
100 unattended-upgrades.service          start waiting
```

But you can fix it by doing this in the nested focal container

```
apt install squashfuse fuse
mount -t tmpfs tmpfs /sys/kernel/security/
service restart snapd
```

I guess we can manually install those packages but seems unfortunate that has become a requirement? Any idea why the tmpfs step has become necessary?

# Information to attach

Here the config of the top container:
```
lxc config show more-man --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20210720)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20210720"
  image.type: squashfs
  image.version: "20.04"
  security.nesting: "true"
  volatile.base_image: cea91a28441af36f088f3ae8b637499061518ea2d83c7560a2f7f33d74298968
  volatile.eth0.host_name: veth2766d9f0
  volatile.eth0.hwaddr: 00:16:3e:b8:48:04
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: eb912be2-0ca1-4e20-95ee-37644a84e4b1
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

Inside the top container, here's the config of the nested container:
```
lxc config show stable-condor --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20210720)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20210720"
  image.type: squashfs
  image.version: "20.04"
  volatile.base_image: cea91a28441af36f088f3ae8b637499061518ea2d83c7560a2f7f33d74298968
  volatile.eth0.host_name: veth539a8c0a
  volatile.eth0.hwaddr: 00:16:3e:6b:0e:eb
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":999900000},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":999900000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":999900000},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":999900000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":999900000},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":999900000}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 32a9557b-ebd0-4c3c-9163-cc9e15768927
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
Log of the nested container:
```
lxc info stable-condor --show-log
Name: stable-condor
Location: none
Remote: unix://
Architecture: x86_64
Created: 2021/08/09 05:07 UTC
Status: Running
Type: container
Profiles: default
Pid: 1234
Ips:
  eth0: inet    10.4.81.41      veth539a8c0a
  eth0: inet6   fd42:30f6:2a3f:27eb:216:3eff:fe6b:eeb   veth539a8c0a
  eth0: inet6   fe80::216:3eff:fe6b:eeb veth539a8c0a
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 75
  CPU usage:
    CPU usage (in seconds): 69
  Memory usage:
    Memory (current): 321.81MB
    Memory (peak): 348.27MB
  Network usage:
    eth0:
      Bytes received: 67.33MB
      Bytes sent: 1.21MB
      Packets received: 23156
      Packets sent: 16554
    lo:
      Bytes received: 8.43kB
      Bytes sent: 8.43kB
      Packets received: 84
      Packets sent: 84

Log:

lxc stable-condor 20210809050741.728 WARN     conf - conf.c:lxc_map_ids:3389 - newuidmap binary is missing
lxc stable-condor 20210809050741.733 WARN     conf - conf.c:lxc_map_ids:3395 - newgidmap binary is missing
lxc stable-condor 20210809050741.739 WARN     conf - conf.c:lxc_map_ids:3389 - newuidmap binary is missing
lxc stable-condor 20210809050741.744 WARN     conf - conf.c:lxc_map_ids:3395 - newgidmap binary is missing
lxc stable-condor 20210809050741.744 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1296 - No such file or directory - Failed to fchownat(43, memory.oom.group, 999900000, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )
lxc stable-condor 20210809050826.481 WARN     conf - conf.c:lxc_map_ids:3389 - newuidmap binary is missing
lxc stable-condor 20210809050826.485 WARN     conf - conf.c:lxc_map_ids:3395 - newgidmap binary is missing
lxc stable-condor 20210809052606.721 WARN     conf - conf.c:lxc_map_ids:3389 - newuidmap binary is missing
lxc stable-condor 20210809052606.798 WARN     conf - conf.c:lxc_map_ids:3395 - newgidmap binary is missing
```
