### ISSUE TITLE
USB device attach events are missing for a specific device

### ISSUE THREAD

**Issue by gbiggs** [lxc/lxd#9136]
# Required information

 * Distribution: ArchLinux
 * Distribution version: latest
 * [The output of "lxc info"](https://gist.github.com/gbiggs/1827d23d3addc4a100712e0dab0aa68b)

# Issue description

USB device attach events are missing for a specific device.

I have a USB camera that has two modes. In the first (startup) mode, bootloader mode, it is a USB2 device. To use the camera the camera's API loads a firmware into it while it is in the bootloader mode, then the camera restarts. After restarting the camera becomes either a USB2 device or a USB3 device (depending on a switch; the default is USB3) with the same vendor ID but a different product ID. When shut down, the camera reboots back into the USB2 bootloader mode.

Running the device's software in my host PC works as expected. Running the same software inside my LXD container fails to find the running-mode device. Debugging using `libusb` has shown that the specific event indicating the new device has been attached to the USB bus is not received by the application, even though all other device attach/remove events are.

I have added a device to my container that covers both modes by specifying only the vendor ID:

```
$ lxc config device add my_container oakd usb vendorid=03e7
```

The device shows up correctly inside the container using this device. Both the bootloader mode device and the running-mode device appear correctly in `/dev/bus/usb`, and with the correct permissions thanks to a udev rule, `SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"`. Here's a sample showing the running-mode device inside the container:

```
/dev/bus/usb:
total 0
drwxr-xr-x 2 root root 40 Aug 13 07:02 001
drwxr-xr-x 2 root root 40 Aug 20 09:24 003
drwxr-xr-x 2 root root 60 Aug 20 09:24 004

/dev/bus/usb/001:
total 0

/dev/bus/usb/003:
total 0

/dev/bus/usb/004:
total 0
crw-rw-rw- 1 root root 189, 431 Aug 20 09:24 048
```

When the device's software is [run inside the container](https://github.com/luxonis/depthai/issues/450#issuecomment-902562530), it correctly initialises the device from bootloader mode to running-mode, but then cannot find the device as it does not receive the notification about the running-mode device attaching to the USB bus.

Here's what it looks like in `dmesg` when the software runs:

```
[3233363.346779] usb 3-2.3: USB disconnect, device number 88
[3233363.641018] usb 4-2.3: new SuperSpeed Gen 1 USB device number 48 using xhci_hcd
[3233363.665603] usb 4-2.3: New USB device found, idVendor=03e7, idProduct=f63b, bcdDevice= 1.00
[3233363.665606] usb 4-2.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[3233363.665608] usb 4-2.3: Product: Luxonis Device
[3233363.665609] usb 4-2.3: Manufacturer: Intel Corporation
[3233363.665610] usb 4-2.3: SerialNumber: 14442C1061F95ED700
[3233371.460568] usb 4-2.3: USB disconnect, device number 48
[3233371.717366] usb 3-2.3: new high-speed USB device number 89 using xhci_hcd
[3233371.834706] usb 3-2.3: New USB device found, idVendor=03e7, idProduct=2485, bcdDevice= 0.01
[3233371.834710] usb 3-2.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[3233371.834712] usb 3-2.3: Product: Movidius MyriadX
[3233371.834713] usb 3-2.3: Manufacturer: Movidius Ltd.
[3233371.834713] usb 3-2.3: SerialNumber: 03e72485
```

Device 88 on the USB2 bus is the bootloader mode device, which disconnects and is replaced by the running-mode device number 48 on the USB3 bus. When the software fails to respond to the camera, after a timeout it reboots back into bootloader mode, giving device 89 on the USB2 bus.

Running the application with `LIBUSB_DEBUG=4` is what told us that the attachment notification event is not received by the application. The following events are received by the application.

The removal of the bootloader-mode device when it reboots:
```
[ 1.445999] [0000164e] libusb: debug [linux_netlink_read_message] netlink hotplug found device busnum: 3, devaddr: 30, sys_name: 3-2, removed: yes
```

The appearance of the bootloader-mode device _after_ the running-mode device gives up and reboots:
```
[10.156069] [0000164e] libusb: debug [linux_netlink_read_message] netlink hotplug found device busnum: 3, devaddr: 31, sys_name: 3-2, removed: no
```

The removal of the running-mode device when it gives up and reboots (note that this happens _after_ the above line):
```
[10.467585] [0000164e] libusb: debug [linux_netlink_read_message] netlink hotplug found device busnum: 4, devaddr: 19, sys_name: 4-2, removed: yes
```

Notably absent from the debug output in the container is the event for the running-mode device appearing, even though the device node in `/dev/bus/usb` is created properly, has the correct permissions, etc., and even though it gets an event for the device's removal from the USB bus. This pattern appears to be also visible in the `/var/log/lxd/lxd.log` file.

Running on the host, the debug output _does_ contain an event for the running-mode device appearance. It is only within the LXD container that this event is missing.

Running the software with the device using USB2 in its running mode correctly shows a USB2 device in `/dev/bus/usb` but the attach event still does not appear in the application.

I have tried [adding a cgroup LXC rule directly](https://github.com/luxonis/depthai/issues/450#issuecomment-903360236):

```
$ lxc config set oakd_test raw.lxc="lxc.cgroup.devices.allow = c 189:* rwm"
```

But this made no difference to the behaviour, and I'm guessing that it's added already anyway by the LXD device config.

See [this issue on the DepthAI repository](https://github.com/luxonis/depthai/issues/450) for where this bug was discovered and our debugging process to date.

# Steps to reproduce

You will need an OAK-D camera, or possibly some similar device that reboots into a separate mode to be used, to reproduce this issue.

1. Create an LXD container with Ubuntu 20.04
   ```
   lxc launch ubuntu:20.04 my_container
   ```
2. Enter the container
   ```
   lxc exec my_container --user 1000 --group 1000 -- bash --login
   ```
3. In the container, set up the udev rule for DepthAI
   ```
   echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"' | sudo tee /etc/udev/rules.d/80-movidius.rules
   sudo udevadm control --reload-rules && sudo udevadm trigger
   ```
4. On the host, add the USB device to the container:
   ```
   lxc config device add my_container oakd usb vendorid=03e7
   ```
5. Plug in the OAK-D
6. In the container, execute the `depthai_demo.py` demonstration application
7. Observe that the application finds the OAK-D in its bootloader mode, but fails to find the device after it reboots.

# Information to attach

Container log:

```
Name: oakd_test
Status: RUNNING
Type: container
Architecture: x86_64
PID: 81818
Created: 2021/08/11 02:11 UTC
Last Used: 2021/08/23 00:28 UTC

Resources:
  Processes: 69
  CPU usage:
    CPU usage (in seconds): 0
  Memory usage:
    Memory (current): 1.23GiB
    Swap (current): 7.22MiB
  Network usage:
    eth0:
      Type: broadcast
      State: UP
      Host interface: vethba8797e8
      MAC address: 00:16:3e:08:35:1d
      MTU: 1500
      Bytes received: 18.58MB
      Bytes sent: 430.56kB
      Packets received: 15239
      Packets sent: 5711
      IP addresses:
        inet:  10.22.236.157/24 (global)
        inet6: fd42:9332:3fae:d828:216:3eff:fe08:351d/64 (global)
        inet6: fe80::216:3eff:fe08:351d/64 (link)
    lo:
      Type: loopback
      State: UP
      MTU: 65536
      Bytes received: 12.21kB
      Bytes sent: 12.21kB
      Packets received: 140
      Packets sent: 140
      IP addresses:
        inet:  127.0.0.1/8 (local)
        inet6: ::1/128 (local)

Log:

lxc oakd_test 20210823002857.935 WARN     cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2746 - Invalid argument - Ignoring legacy cgroup limits on pure cgroup2 system
lxc oakd_test 20210823002858.197 WARN     cgfsng - cgroups/cgfsng.c:cgfsng_setup_limits_legacy:2746 - Invalid argument - Ignoring legacy cgroup limits on pure cgroup2 system
lxc oakd_test 20210823002903.185 WARN     attach - attach.c:get_attach_context:463 - No security context received
lxc oakd_test 20210823002919.314 WARN     attach - attach.c:get_attach_context:463 - No security context received
lxc oakd_test 20210823063527.894 WARN     attach - attach.c:get_attach_context:463 - No security context received
lxc oakd_test 20210823074533.491 WARN     attach - attach.c:get_attach_context:463 - No security context received
lxc oakd_test 20210823142521.798 WARN     attach - attach.c:get_attach_context:463 - No security context received

```

Container configuration:

```
architecture: x86_64
config:
  environment.DISPLAY: :0
  environment.IS_CONTAINER: "1"
  environment.IS_LXD_CONTAINER: "1"
  environment.PULSE_SERVER: unix:/home/pulse-native
  environment.SSH_AUTH_SOCK: /tmp/ssh
  image.architecture: amd64
  image.description: |
    Ubuntu focal
  image.name: ubuntu-x86_64
  image.os: ubuntu
  image.release: focal
  image.serial: "20210601_0155"
  image.variant: default
  nvidia.driver.capabilities: all
  nvidia.runtime: "true"
  raw.idmap: |-
    uid 1000 1000
    gid 1000 1000
  raw.lxc: lxc.cgroup.devices.allow = c 189:* rwm
  user.user-data: |
    #cloud-config
    merge_how:
     - name: list
       settings: [append]
     - name: dict
       settings: [no_replace, recurse_list]

    packages:
      - x11-apps
  volatile.base_image: 4b5ebb97d70ed3d121ae8cd1c8137f8b68db5980e14f5015223168a90b90a5a8
  volatile.eth0.host_name: vethba8797e8
  volatile.eth0.hwaddr: 00:16:3e:08:35:1d
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":101001,"Nsid":1001,"Maprange":64535},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":1000},{"Isuid":false,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":101001,"Nsid":1001,"Maprange":64535}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":101001,"Nsid":1001,"Maprange":64535},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":1000},{"Isuid":false,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":101001,"Nsid":1001,"Maprange":64535}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":101001,"Nsid":1001,"Maprange":64535},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":1000},{"Isuid":false,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":101001,"Nsid":1001,"Maprange":64535}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 7073e7ef-3c8c-4561-8020-8e8327257ee2
devices:
  HomeDirectory:
    path: /home/geoff
    required: "true"
    source: /home/geoff
    type: disk
  PASocket:
    bind: container
    connect: unix:/run/user/1000/pulse/native
    gid: "1000"
    listen: unix:/home/pulse-native
    mode: "0777"
    security.gid: "1000"
    security.uid: "1000"
    type: proxy
    uid: "1000"
  SSHAgentSocket:
    bind: container
    connect: unix:/run/user/1000/keyring/ssh
    listen: unix:/tmp/ssh
    mode: "0777"
    security.gid: "1000"
    security.uid: "1000"
    type: proxy
  SystemGPU:
    type: gpu
  Xsocket:
    bind: container
    connect: unix:@/tmp/.X11-unix/X0
    listen: unix:@/tmp/.X11-unix/X0
    security.gid: "1000"
    security.uid: "1000"
    type: proxy
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  oakd:
    type: usb
    vendorid: "03e7"
  realsense:
    type: usb
    vendorid: "8086"
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
- container_marker
- gpu
- home_directory
- pulseaudio
- sshagent
- x11
stateful: false
description: ""
```

Main daemon log:

```
t=2021-08-24T00:07:19+0900 lvl=eror msg="USB event instance handler failed" device=oakd err="Failed to run: /usr/bin/lxd forkuevent -- inject 81818 3 268 unbind@/devices/pci0000:00/0000:00:1c.0/0000:03:00.0/usb3/3-2 ACTION=unbind DEVPATH=/devices/pci0000:00/0000:00:1c.0/0000:03:00.0/usb3/3-2 SUBSYSTEM=usb MAJOR=189 MINOR=314 DEVNAME=bus/usb/003/059 DEVTYPE=usb_device PRODUCT=3e7/2485/1 TYPE=0/0/0 BUSNUM=003 DEVNUM=059: Error: unknown command \"inject\" for \"lxd forkuevent\"" instance=oakd_test project=default
t=2021-08-24T00:07:19+0900 lvl=eror msg="USB event instance handler failed" device=oakd err="Failed to run: /usr/bin/lxd forkuevent -- inject 81818 3 268 remove@/devices/pci0000:00/0000:00:1c.0/0000:03:00.0/usb3/3-2 ACTION=remove DEVPATH=/devices/pci0000:00/0000:00:1c.0/0000:03:00.0/usb3/3-2 SUBSYSTEM=usb MAJOR=189 MINOR=314 DEVNAME=bus/usb/003/059 DEVTYPE=usb_device PRODUCT=3e7/2485/1 TYPE=0/0/0 BUSNUM=003 DEVNUM=059: Error: unknown command \"inject\" for \"lxd forkuevent\"" instance=oakd_test project=default
t=2021-08-24T00:07:27+0900 lvl=eror msg="USB event instance handler failed" device=oakd err="Failed to run: /usr/bin/lxd forkuevent -- inject 81818 3 262 add@/devices/pci0000:00/0000:00:1c.0/0000:03:00.0/usb3/3-2 ACTION=add DEVPATH=/devices/pci0000:00/0000:00:1c.0/0000:03:00.0/usb3/3-2 SUBSYSTEM=usb MAJOR=189 MINOR=315 DEVNAME=bus/usb/003/060 DEVTYPE=usb_device PRODUCT=3e7/2485/1 TYPE=0/0/0 BUSNUM=003 DEVNUM=060: Error: unknown command \"inject\" for \"lxd forkuevent\"" instance=oakd_test project=default
t=2021-08-24T00:07:28+0900 lvl=eror msg="USB event instance handler failed" device=oakd err="Failed to run: /usr/bin/lxd forkuevent -- inject 81818 3 275 bind@/devices/pci0000:00/0000:00:1c.0/0000:03:00.0/usb3/3-2 ACTION=bind DEVPATH=/devices/pci0000:00/0000:00:1c.0/0000:03:00.0/usb3/3-2 SUBSYSTEM=usb MAJOR=189 MINOR=315 DEVNAME=bus/usb/003/060 DEVTYPE=usb_device DRIVER=usb PRODUCT=3e7/2485/1 TYPE=0/0/0 BUSNUM=003 DEVNUM=060: Error: unknown command \"inject\" for \"lxd forkuevent\"" instance=oakd_test project=default
t=2021-08-24T00:07:28+0900 lvl=eror msg="USB event instance handler failed" device=oakd err="Failed to run: /usr/bin/lxd forkuevent -- inject 81818 3 270 unbind@/devices/pci0000:00/0000:00:1c.0/0000:03:00.0/usb4/4-2 ACTION=unbind DEVPATH=/devices/pci0000:00/0000:00:1c.0/0000:03:00.0/usb4/4-2 SUBSYSTEM=usb MAJOR=189 MINOR=410 DEVNAME=bus/usb/004/027 DEVTYPE=usb_device PRODUCT=3e7/f63b/100 TYPE=0/0/0 BUSNUM=004 DEVNUM=027: Error: unknown command \"inject\" for \"lxd forkuevent\"" instance=oakd_test project=default
t=2021-08-24T00:07:28+0900 lvl=eror msg="USB event instance handler failed" device=oakd err="Failed to run: /usr/bin/lxd forkuevent -- inject 81818 3 270 remove@/devices/pci0000:00/0000:00:1c.0/0000:03:00.0/usb4/4-2 ACTION=remove DEVPATH=/devices/pci0000:00/0000:00:1c.0/0000:03:00.0/usb4/4-2 SUBSYSTEM=usb MAJOR=189 MINOR=410 DEVNAME=bus/usb/004/027 DEVTYPE=usb_device PRODUCT=3e7/f63b/100 TYPE=0/0/0 BUSNUM=004 DEVNUM=027: Error: unknown command \"inject\" for \"lxd forkuevent\"" instance=oakd_test project=default
```

[Output of `lxc monitor` command while reproducing the issue](https://gist.github.com/gbiggs/0279b4265eefed6bc62b93ec1fe24147).

 - [X] Any relevant kernel output (`dmesg`)
 - [X] Container log (`lxc info NAME --show-log`)
 - [X] Container configuration (`lxc config show NAME --expanded`)
 - [X] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [X] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
