### ISSUE TITLE
IPv6 addresses ending with ":" confuse LXD into thinking the port is missing

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#9186]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04.3
```
# snap list lxd
Name  Version      Rev    Tracking     Publisher   Notes
lxd   git-2dea139  21455  latest/edge  canonical✓  -
```
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:

# Issue description

On a system with an IPv6 address ending with ":" if the `cluster.https_address` is configured without the square brackets/port, LXD complains about a missing port.

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Setup a cluster
 2. Configure `cluster.https_address` without port and using an IPv6 ending with ":"
```
lxc config set cluster.https_address 2602:fc62:b:1018:0:1::
```
 3. Join the cluster using a preseed.yaml including a token:
```
# cat /tmp/tmp39umhd5p 
config: {}
networks: []
storage_pools: []
profiles: []
projects: []
cluster:
  enabled: true
  member_config:
  - {entity: storage-pool, name: local, key: source, value: ''}
  server_address: '2602:fc62:b:1018:0:1::'
  cluster_token: "eyJzZXJ2ZXJfbmFtZSI6ImNsb3VkLXZtMDMiLCJmaW5nZXJwcmludCI6IjgzYzA3NmViMGVhOTJiMDFiNzIyYjgzNGE3NzQyM2ZkNzA4ODliMzEzODY4ZDFmMzc1NWRkYzc0Y2JhYWQ4MjQiLCJhZGRyZXNzZXMiOlsiWzI2MDI6ZmM2MjpiOjEwMTg6MDoxOjA6ZF06ODQ0MyJdLCJzZWNyZXQiOiI2MzllNTQyYWRlZjg2MDNiNDNlMjEyNDcxMjcwMDA3NTc2NmNkZGQ2ZGNiY2NiNDBmN2Q3ZDc0MDg0ZTFmZTZkIn0="

# lxd init --preseed < /tmp/tmp39umhd5p
```

The above command will hang and the following will be logged:

```
root@cloud-vm03:~# journalctl -n2 -o cat -u snap.lxd.daemon
=> LXD is ready
t=2021-09-02T19:05:31+0000 lvl=warn msg="Dqlite: attempt 1: server 2602:fc62:b:1018:0:1::: dial: Failed to connect to HTTP endpoint: dial tcp: address 2602:fc62:b:1018:0:1::: too many colons in address"
```

Additional information on the machine:

```
root@cloud-vm03:~# ip -6 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp5s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 2602:fc62:b:1018:1::9264/128 scope global dynamic noprefixroute 
       valid_lft 1738sec preferred_lft 826sec
    inet6 2602:fc62:b:1018:0:1::/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fed6:4c8a/64 scope link 
       valid_lft forever preferred_lft forever

root@cloud-vm03:~# ss -nltp | grep lxd
LISTEN  0       4096       [2602:fc62:b:1018:0:1::]:8443             [::]:*      users:(("lxd",pid=19493,fd=22))
```
