### ISSUE TITLE
4.0 requires `server_name` for token-based cluster joins

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#9187]
# Required information

```
root@cloud-vm01:~# snap list lxd
Name  Version      Rev    Tracking  Publisher   Notes
lxd   git-1e32d45  21373  4.0/edge  canonical✓  -
```

# Issue description

In 4.0, in order to do a token-based cluster join, one has to add the `server_name` field to the preseed. `latest/edge` doesn't require that field suggesting a problem with the feature backport.

# Steps to reproduce

 1. Setup a cluster with 4.0/edge
 2. Try joining a node with the following preseed:
```
cat << EOF | lxd init --preseed
config: {}
networks: []
storage_pools: []
profiles: []
projects: []
cluster:
  enabled: true
  member_config:
  - {entity: storage-pool, name: local, key: source, value: ''}
  server_address: '[2602:fc62:b:1018:0:1:0:3]:8443'
  cluster_token: eyJzZXJ2ZXJfbmFtZSI6ImNsb3VkLXZtMDEiLCJmaW5nZXJwcmludCI6IjM5OGVmMWY3ZmFkODI5NTUwMDJjNTZkYWM4ZDQxNmY2YzcyMTUwZjZhNzE1YTNkNzJiZDkxOWY3NTYzMTM5NTYiLCJhZGRyZXNzZXMiOlsiWzI2MDI6ZmM2MjpiOjEwMTg6MDoxOjA6MTRdOjg0NDMiXSwic2VjcmV0IjoiZGJkZjRlZDZmNWU3MWUxZmEyZjgwYmFmYThkMWE3NmVkYTA1MzAxOGMwZjgzMWU0NzQzODkyODExYjE3NjczNSJ9
EOF
```

The above will fail with:

```
Error: Failed to configure cluster: ServerName is required when enabling clustering
```

Adding `server_name: cloud-vm01` to the preseed make it work.
