### ISSUE TITLE
Failed start container vm

### ISSUE THREAD

**Issue by ne-vlezay80** [lxc/lxd#9200]
# Required information

 * Distribution: Archlinux
 * Distribution version: current
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.13.13-arch1-1
   * LXC version: 4.17
   * LXD version: 4.17
   * Storage backend in use: lvm

# Issue description

Problem start container with vm mode.

# Steps to reproduce

 1. `lxc init images:debian/current docker --vm`
 2. lxc start docker
# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`)
 - [x] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

```
[root@router ne-vlezay80]# lxc info --show-log docker
Name: docker
Status: STOPPED
Type: virtual-machine
Architecture: x86_64
Created: 2021/09/04 02:40 UTC

qemu-system-x86_64:/var/log/lxd/docker/qemu.conf:43: memdev=mem0 is ambiguous
```

**Comment by ne-vlezay80** [comment]
```
[root@router ne-vlezay80]# lxc config show docker --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Debian bullseye amd64 (20210903_05:24)
  image.os: Debian
  image.release: bullseye
  image.serial: "20210903_05:24"
  image.type: disk-kvm.img
  image.variant: default
  limits.memory: 512MB
  security.secureboot: "false"
  volatile.base_image: f754983f53f771357b07d9c5621ec87080cf745a09d583202070aaf401910283
  volatile.eth0.hwaddr: 00:16:3e:5d:f6:f9
  volatile.uuid: 638c1ccf-c152-443d-8969-56c3dda1ef15
  volatile.vsock_id: "16"
devices:
  eth0:
    host_name: lxd-docker.0
    mtu: "16384"
    nictype: p2p
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
