### ISSUE TITLE
Allow ipv4_filtering even when no ip is set

### ISSUE THREAD

**Issue by Freeaqingme** [lxc/lxd#9215]
Suppose you have a bridge that has both IPv4 and IPv6 connectivity. A VM is created and an IPv6 address is assigned. That VM is only allowed to communicate over that single IPv6 address. 

Ideally, one would be able to configure:
```
devices:
  network:
    ipv6.address: 2001:db8:85a3:8d3:1319:8a2e:370:7348
    name: eth0
    nictype: bridged
    parent: brVM
    security.ipv4_filtering: "true"
    security.ipv6_filtering: "true"
    security.mac_filtering: "true"
    type: nic
```

This is not possible however, because you can only enable ipv4_filtering if an ipv4 address is set. Currently, you either need to add a 'fake' (e.g. ipv4 link-local) address to enable filtering, or disable the ipv4_filtering. The latter would allow the user to add an ipv4 address manually inside the VM and use it unauthorized.

Ideally, it would be possible to configure 'security.ipv4_filtering' to 'true' even if no ipv4 address was configured. Instead of a rule like this one:
```
		iifname "tap4326a2ff" ip saddr != 169.254.1.1 drop
```
a rule like this could be added:
```
		iifname "tap4326a2ff" ip saddr  = 0.0.0.0/0 drop
or:
		iifname "tap4326a2ff" ip version 4 drop
```

Alternatively, all IPv4 rules could be left out, and the ehter type rule could be changed:
```
	iifname "tap4326a2ff" ether type != { ip, arp, ip6 } drop
into:
	iifname "tap4326a2ff" ether type != { arp, ip6 } drop
```	

On IRC, tomp proposed to use 'ipv4_filtering=all' instead of '=true'. Personally I'd prefer to keep it at '=true' for simplicity.

I would say this issue is a minor improvement of low priority. A viable work-around is to use the aforementioned link-local ipv4 addresses.

The current error one gets when trying to configure it as proposed is:
> Failed instance creation: Failed creating instance record: Invalid devices: Device validation failed for "network": IPv4 filtering requires a manually specified ipv4.address when using an unmanaged parent bridge
