### ISSUE TITLE
4.0.7: lxc list timeout/error with stopped container

### ISSUE THREAD

**Issue by janmuennich** [lxc/lxd#9250]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-84-generic #94-Ubuntu SMP
   * LXD version: 4.0.7
   * Storage backend in use: Ceph

# Issue description

I noticed today that `lxc list` takes a very long time in a cluster and the reported state of all containers on only one host is `ERROR`. This apparently happens when one container is `STOPPED` and also only when the `lxc list` includes `4` or `6` to list the instance ip addresses. All other listing options work fast and normal and the container state is reported correctly then. After starting the stopped container, default listing works fine again too.

**Comment by stgraber** [comment]
What's `lxc cluster list` showing you?
And then can you go on the system where you're getting the ERRORed containers and run `lxc list` from there to make sure you get the same output and if you do, then get us the `dmesg` output too for that system?

**Comment by janmuennich** [comment]
> What's `lxc cluster list` showing you?

Works fine without any delay.

> And then can you go on the system where you're getting the ERRORed containers and run `lxc list` from there to make sure you get the same output

This also takes a long time but displays all instances correctly, including the local ones that are displayed as ERROR when running `lxc list` from another cluster member.

> and if you do, then get us the `dmesg` output too for that system?

`dmesg` does not show anything in relation to the issue or while running `lxc list`. I already checked the LXD logs on the host and nothing happens there either.

Some more information:
This doesn't seem to have anything to do with the specific cluster member. When I move the stopped container to another host, the same problem continues on the other host. I think it somehow takes a long time for LXD to gather the network information for the stopped container. The container that brought up the issue initially has Docker installed and therefore a few additional interfaces. When I stop a different container with one single interface, `lxc list` also takes quite long but finishes within ca. 10 seconds correctly. The ERROR seems to me that the request takes too long before `lxc list` times out.

**Comment by stgraber** [comment]
Hmm, this is still a bit odd, unless the system is extremely overloaded by that container or the container is itself blocked on slow I/O, retrieving network info is quit fast even with lots of interfaces and addresses.

For a non-profit I run, we commonly have containers with over 300 interfaces and around 3 addresses on each of those.

**Comment by janmuennich** [comment]
Let me know if there is anything more I can do to debug this!

**Comment by stgraber** [comment]
Would be good to get the `uptime` output on the system as well as checking how long a `lxc info` takes for that container.

`lxc info --show-log NAME` could also be useful

**Comment by janmuennich** [comment]
The host is not overloaded. `lxc info` actually takes very long as well when the container is stopped. I thought I tried that before but probably missed it.

```
root@host:~# time lxc info container
Name: container
Location: host
Remote: unix://
Architecture: x86_64
Created: 2021/05/17 16:09 UTC
Status: Running
Type: container
Profiles: default
Pid: 1503635
Ips:
  eth0:	inet	ipv4	vethee849d20
  eth0:	inet6	ipv6	vethee849d20
  eth0:	inet6	fe80::216:3eff:fe36:b224	vethee849d20
  lo:	inet	127.0.0.1
  lo:	inet6	::1
  veth4f706a0:	inet6	fe80::385c:10ff:fe19:3dfd	ens5f0
  veth651dd8b:	inet6	fe80::fc64:a7ff:fe52:2344	bond1
  br-4ab53b4d8f7e:	inet	172.19.0.1
  br-4ab53b4d8f7e:	inet6	fe80::42:5eff:feae:eb7
  docker0:	inet	172.17.0.1
Resources:
  Processes: 699
  Disk usage:
    root: 9.63GB
  CPU usage:
    CPU usage (in seconds): 199
  Memory usage:
    Memory (current): 3.80GB
    Memory (peak): 3.91GB
  Network usage:
    eth0:
      Bytes received: 2.74MB
      Bytes sent: 28.48kB
      Packets received: 12429
      Packets sent: 229
    lo:
      Bytes received: 8.82MB
      Bytes sent: 8.82MB
      Packets received: 63976
      Packets sent: 63976
    veth4f706a0:
      Bytes received: 43.00kB
      Bytes sent: 16.85kB
      Packets received: 110
      Packets sent: 124
    veth651dd8b:
      Bytes received: 15.70kB
      Bytes sent: 44.52kB
      Packets received: 110
      Packets sent: 128
    br-4ab53b4d8f7e:
      Bytes received: 56B
      Bytes sent: 800B
      Packets received: 2
      Packets sent: 8
    docker0:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0

real	0m0.204s
user	0m0.076s
sys	0m0.110s
root@host:~# lxc stop container
root@host:~# time lxc info container
Name: container
Location: host
Remote: unix://
Architecture: x86_64
Created: 2021/05/17 16:09 UTC
Status: Stopped
Type: container
Profiles: default

real	1m18.390s
user	0m0.055s
sys	0m0.133s
root@host:~# lxc info --show-log container
Name: container
Location: host
Remote: unix://
Architecture: x86_64
Created: 2021/05/17 16:09 UTC
Status: Stopped
Type: container
Profiles: default

Log:

lxc container 20210920084142.927 WARN     conf - conf.c:lxc_map_ids:3389 - newuidmap binary is missing
lxc container 20210920084142.927 WARN     conf - conf.c:lxc_map_ids:3395 - newgidmap binary is missing
lxc container 20210920084142.928 WARN     conf - conf.c:lxc_map_ids:3389 - newuidmap binary is missing
lxc container 20210920084142.928 WARN     conf - conf.c:lxc_map_ids:3395 - newgidmap binary is missing
lxc container 20210920084142.929 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1296 - No such file or directory - Failed to fchownat(43, memory.oom.group, 65536, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )
lxc container 20210920090326.200 WARN     conf - conf.c:lxc_map_ids:3389 - newuidmap binary is missing
lxc container 20210920090326.200 WARN     conf - conf.c:lxc_map_ids:3395 - newgidmap binary is missing

**Comment by stgraber** [comment]
Hmm, that is quite odd. Can you show `lxc config show --expanded NAME` for that container?
Also just to confirm, that container has no snapshot?

Can you also tell us what storage backend is in use by that container?

**Comment by janmuennich** [comment]
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Ubuntu bionic amd64 (20210517_07:42)
  image.os: Ubuntu
  image.release: bionic
  image.serial: "20210517_07:42"
  image.type: squashfs
  image.variant: default
  limits.cpu.allowance: 16%
  limits.memory: 16GiB
  limits.memory.swap: "false"
  security.idmap.isolated: "true"
  security.nesting: "true"
  volatile.base_image: 53740356f6a3c8262f06f8a2f6b41da8bfb6e6da738783d7ce5afae5a64c12a0
  volatile.eth0.host_name: vethbde7b23d
  volatile.eth0.hwaddr: 00:16:3e:36:b2:24
  volatile.idmap.base: "1065536"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1065536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1065536,"Nsid":0,"Maprange":65536}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1065536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1065536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1065536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1065536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: f3d543e8-64d9-415a-a36b-f56f2ce944dc
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: pool
    size: 100GiB
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

When the container is stopped, the line `volatile.eth0.host_name: vethbde7b23d` is missing, which is probably correct.

Storage backend is Ceph. There are no snapshots.
