### ISSUE TITLE
Don't leave gaps in VM disk scsi-id that is derived from bootindex

### ISSUE THREAD

**Issue by tomponline** [lxc/lxd#9268]
See https://discuss.linuxcontainers.org/t/wrong-boot-order-for-maas-generated-lxd-config/12117/6?u=tomp for more info.

Currently scsi-id is generated from the disk's boot index.
However if there is a network boot device too, then the scsi-ids generated can have gaps in the sequence.

This doesn't cause a problem. But would be nice to not have that, so we could generate the scsi-id based on the boot order of the just the disk devices (based on the boot index).

**Comment by kaustubnvd** [comment]
Hello, @Gautham-Raju and I are students from UT Austin taking a Virtualization class, and we would love to take a look at this issue as part of our final project to contribute to an open source repo.

**Comment by stgraber** [comment]
Done!

**Comment by stgraber** [comment]
@kaustubnvd @Gautham-Raju hello, just wanted to check if you still intend to work on this or if we should unassign it so someone else can take a crack at it?

**Comment by kaustubnvd** [comment]
@stgraber Apologies for the delayed response, we no longer intend to work on this issue, so you can unassign us from it.

**Comment by stgraber** [comment]
Going to take care of this one.

**Comment by stgraber** [comment]
I think we can close this one. With the switch to QMP, those entries don't exist in the config anymore at all.
And from the guest's point of view, I'm not seeing any issue with the ordering.

Here is a worst case scenario:
```
root@distrobuilder-45b8829d-6846-4f7c-b119-60e2b426831d:~# lsscsi
[0:0:0:1]    disk    QEMU     QEMU HARDDISK    2.5+  /dev/sda 
[0:0:1:1]    disk    QEMU     QEMU HARDDISK    2.5+  /dev/sdb 
[0:0:2:1]    disk    QEMU     QEMU HARDDISK    2.5+  /dev/sdc 
root@distrobuilder-45b8829d-6846-4f7c-b119-60e2b426831d:~# ls -lh /dev/disk/by-id/
total 0
lrwxrwxrwx 1 root root  9 Apr  8 19:35 scsi-0QEMU_QEMU_HARDDISK_lxd_root -> ../../sda
lrwxrwxrwx 1 root root 10 Apr  8 19:35 scsi-0QEMU_QEMU_HARDDISK_lxd_root-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Apr  8 19:35 scsi-0QEMU_QEMU_HARDDISK_lxd_root-part2 -> ../../sda2
lrwxrwxrwx 1 root root  9 Apr  8 19:35 scsi-0QEMU_QEMU_HARDDISK_lxd_test -> ../../sdb
lrwxrwxrwx 1 root root  9 Apr  8 19:35 scsi-0QEMU_QEMU_HARDDISK_lxd_test1 -> ../../sdc
root@distrobuilder-45b8829d-6846-4f7c-b119-60e2b426831d:~# stgraber@dakara:~$ lxc config show v1
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Ubuntu focal amd64 (20220408_08:30)
  image.os: Ubuntu
  image.release: focal
  image.serial: "20220408_08:30"
  image.type: disk-kvm.img
  image.variant: cloud
  volatile.base_image: 710ba4ca2b3cf7a9dfae2ded3c3c100180aefbcdd6d5a8019cf2d686c742ffbd
  volatile.cloud-init.instance-id: de150753-c19c-430b-a7a1-9d4bd0d326ab
  volatile.eth0.host_name: tapc98c99a7
  volatile.eth0.hwaddr: 00:16:3e:b1:d8:e8
  volatile.eth1.host_name: tap448f558b
  volatile.eth1.hwaddr: 00:16:3e:6f:77:3a
  volatile.last_state.power: RUNNING
  volatile.uuid: 5a166baf-6547-4efa-8672-8ec75f0c9a31
  volatile.vsock_id: "421"
devices:
  eth0:
    boot.priority: "6"
    name: eth0
    network: lxdbr0
    type: nic
  eth1:
    boot.priority: "7"
    name: eth1
    network: lxdbr0
    type: nic
  root:
    boot.priority: "10"
    path: /
    pool: default
    type: disk
  test:
    boot.priority: "1"
    pool: default
    source: test
    type: disk
  test1:
    boot.priority: "8"
    pool: default
    source: test1
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

As you can see, I have a mix of disks and NICs, yet the SCSI bus ordering is a simple bus ID per drive with the drivers being place in alphabetical order as listed in the config (root always goes first, then everything after that in alphabetical order).
