### ISSUE TITLE
Introduce cluster role for OVN gateways

### ISSUE THREAD

**Issue by skob** [lxc/lxd#9347]
# Required information

 * Distribution: ubuntu
 * Distribution version: focal
 * The output of "lxc info" or if that fails: <too many info for my request>
   * Kernel version: 5.4.0-84-generic
   * LXC version: 4.19
   * LXD version: 4.19
   * Storage backend in use: zfs

# Issue description

In my setup, I have cluster with 8 servers with OVN networks.
I want to receive public traffic only on two nodes — `dmznode-01` and `dmznode-02`. I think it's possible, because after manipulations with priorities via `ovn-nbctl ha-chassis-group-add-chassis` I can get result. But:
1. it's not best path to make some additional operations
2. it's can be not persistent change

it will be great to have ability to select nodes for binding ovn logical routers or to set priority manually.

# Information to attach

issue created after https://discuss.linuxcontainers.org/t/lxd-cluster-ovn-and-static-ha-chassis-group-priority/12297/9

**Comment by stgraber** [comment]
So if we always expect an environment where some cluster members can act as OVN gateways and some others can't, then we could introduce a cluster member role and if set on one or more servers, restrict the server selection for OVN to those.

Now this may not be flexible enough if you're dealing with multiple uplink networks with each only being available on some (different) servers, but I suspect that would get into an environment we'd rather not support (expectation in general is that all clustered servers have similar storage and network config).

The idea of introducing a cluster member role would also allow controlling the CPU overhead of running the OVN gateway, so even in normal clusters where all servers have equal storage and network access, it would allow putting the OVN ingress/egress away from the machines handling cluster events or cluster DB traffic.

@tomponline thoughts?

**Comment by tomponline** [comment]
> So if we always expect an environment where some cluster members can act as OVN gateways and some others can't, then we could introduce a cluster member role and if set on one or more servers, restrict the server selection for OVN to those.
> 
> Now this may not be flexible enough if you're dealing with multiple uplink networks with each only being available on some (different) servers, but I suspect that would get into an environment we'd rather not support (expectation in general is that all clustered servers have similar storage and network config).
> 
> The idea of introducing a cluster member role would also allow controlling the CPU overhead of running the OVN gateway, so even in normal clusters where all servers have equal storage and network access, it would allow putting the OVN ingress/egress away from the machines handling cluster events or cluster DB traffic.
> 
> @tomponline thoughts?

Yes that makes sense, admittedly I am not familiar yet with the cluster roles concept, but the way you're describing it, it would allow an OVN network to detect on startup whether it should add itself to the chassis group.

I don't think that would get the manual prioritisation control that @skob was asking for though (as the chassis would still be added with a stable random priority) so failover order couldn't be controlled.

**Comment by skob** [comment]
my relevant setup is:

```
lxc network list
+----------+----------+---------+-----------------+------+-------------+---------+---------+
|   NAME   |   TYPE   | MANAGED |      IPV4       | IPV6 | DESCRIPTION | USED BY |  STATE  |
+----------+----------+---------+-----------------+------+-------------+---------+---------+
| External | bridge   | NO      |                 |      |             | 0       |         |
+----------+----------+---------+-----------------+------+-------------+---------+---------+
| Internal | bridge   | NO      |                 |      |             | 0       |         |
+----------+----------+---------+-----------------+------+-------------+---------+---------+
| app      | ovn      | YES     | 10.232.176.1/24 | none |             | 12      | CREATED |
+----------+----------+---------+-----------------+------+-------------+---------+---------+
| br-int   | bridge   | NO      |                 |      |             | 0       |         |
+----------+----------+---------+-----------------+------+-------------+---------+---------+
| database | ovn      | YES     | 10.105.155.1/24 | none |             | 4       | CREATED |
+----------+----------+---------+-----------------+------+-------------+---------+---------+
| dmz      | ovn      | YES     | 10.12.218.1/24  | none |             | 6       | CREATED |
+----------+----------+---------+-----------------+------+-------------+---------+---------+
| dmz-02   | ovn      | YES     | 10.115.93.1/24  | none |             | 6       | CREATED |
+----------+----------+---------+-----------------+------+-------------+---------+---------+
| eno1     | physical | NO      |                 |      |             | 0       |         |
+----------+----------+---------+-----------------+------+-------------+---------+---------+
| eno2     | physical | NO      |                 |      |             | 0       |         |
+----------+----------+---------+-----------------+------+-------------+---------+---------+
| infra    | ovn      | YES     | 10.23.171.1/24  | none |             | 10      | CREATED |
+----------+----------+---------+-----------------+------+-------------+---------+---------+
| lxdbr0   | bridge   | YES     | 10.179.176.1/24 | none |             | 5       | CREATED |
+----------+----------+---------+-----------------+------+-------------+---------+---------+
| lxdovn3  | bridge   | NO      |                 |      |             | 0       |         |
+----------+----------+---------+-----------------+------+-------------+---------+------—-+
```
```
lxc network show  lxdbr0
config:
  ipv4.address: 10.179.176.1/24
  ipv4.dhcp.ranges: 10.179.176.5-10.179.176.90
  ipv4.nat: "true"
  ipv4.ovn.ranges: 10.179.176.91-10.179.176.120
  ipv4.routes: 10.179.176.93/32,10.179.176.91/32
  ipv6.address: none
  ipv6.nat: "false"
description: ""
name: lxdbr0
type: bridge
used_by:
- /1.0/networks/app
- /1.0/networks/database
- /1.0/networks/dmz
- /1.0/networks/dmz-02
- /1.0/networks/infra
managed: true
status: Created
locations:
- redis-01
- app-01
- app-02
- nginx-01
- nginx-02
- infra-01
- db-01
- db-02
```
```
lxc network show dmz
config:
  bridge.mtu: "1442"
  ipv4.address: 10.12.218.1/24
  ipv4.nat: "true"
  ipv6.address: none
  network: lxdbr0
  volatile.network.ipv4.address: 10.179.176.93
description: ""
name: dmz
type: ovn
used_by:
- /1.0/instances/lb-01
- /1.0/instances/lb-02
- /1.0/instances/nginx-01
- /1.0/instances/nginx-02
- /1.0/instances/openvpn-01
- /1.0/profiles/dmz
managed: true
status: Created
locations:
- app-01
- app-02
- nginx-01
- nginx-02
- infra-01
- db-01
- db-02
- redis-01
```
```
ip a sh dev lxdbr0
94: lxdbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:33:69:76 brd ff:ff:ff:ff:ff:ff
    inet 10.179.176.1/24 scope global lxdbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:fe33:6976/64 scope link
       valid_lft forever preferred_lft forever
```
```
ping 10.179.176.93
PING 10.179.176.93 (10.179.176.93) 56(84) bytes of data.
From 10.179.176.1 icmp_seq=1 Destination Host Unreachable
From 10.179.176.1 icmp_seq=2 Destination Host Unreachable
From 10.179.176.1 icmp_seq=3 Destination Host Unreachable
```
