### ISSUE TITLE
Vlan ranges in vlan.tagged

### ISSUE THREAD

**Issue by xaverruss** [lxc/lxd#9560]
Hi, I hope I am at the right place here.
I`d like to propose a convenience feature.

I am currently looking into VLAN support in bridges and found that lxd supports this since a while with

```
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
    vlan: "5"
    vlan.tagged: "4,6,7,8,9,10"
```
While a comma separated list works just fine, it would be nicer and more convenient to be able to specify a range here.

```
vlan.tagged: "4,6-10"
```
I am aware that there are not many containers/vms that would take benefit from this feature,
but for something like a virtual firewall, eg pfsense opensense, this would be great, 
as someone who might use such a setup could simply do:
```
vlan: "none"
vlan.tagged: "1-4096"
```
and configure all the VLANs  inside the virtual router.
