### ISSUE TITLE
Cannot override a single device config key

### ISSUE THREAD

**Issue by Kramerican** [lxc/lxd#9728]
LXD v4.2
Host: Ubuntu Focal
Container: Ubuntu Focal

Applying a new network limit to a container by editing the profile has zero effect. Restarting the container with lxc stop/start/restart does not apply the new ingress/egress limit.

Reapplying the profile does not work either.

Changing to an entirely different profile does nothing also.

Creating a new container with the profile applies the new network limit.

It is as if the network ingress/egress limits get "locked in" when the container is created. We are naming the network interface with volatile.eth0.host_name - could that be responsible?

I seem to remember seeing this working without a problem in earlier versions of LXD. Has something changed here?

Lots more details can be provided upon request, I'll leave this issue barebones for now in case this is by design or I am missing something obivious here.

**Comment by stgraber** [comment]
What does the 'lxc config show --expanded' for the instance look like?

**Comment by Kramerican** [comment]
I can mention that I see this on v4.19 and 4.2 which is what we have in production here. I see the same behavior across many hosts.

```
architecture: x86_64
config:
  boot.autostart: "false"
  image.description: Ubuntu Focal LEMP PHP 8.0
  limits.cpu: "10"
  limits.cpu.allowance: 10%
  limits.kernel.memlock: "67108864"
  limits.memory: 5GB
  limits.memory.enforce: hard
  linux.kernel_modules: ip_tables,ip6_tables
  security.nesting: "true"
  volatile.base_image: 4c4e30cd2126fe01cbc63e2438fd28710f93262d7671a5f19968458b12a2f56c
  volatile.eth0.host_name: veXcheckmila
  volatile.eth0.hwaddr: 00:16:3e:89:7d:65
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    host_name: veXcheckmila
    limits.egress: 800Mbit
    limits.ingress: 800Mbit
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    limits.read: 4000iops
    limits.write: 1000iops
    path: /
    pool: lxd
    size: 50GB
    type: disk
  tun:
    path: /dev/net/tun
    type: unix-char
ephemeral: false
profiles:
- largeprofile
stateful: false
description: ""
```

**Comment by tomponline** [comment]
Can you show the same command without '--expanded' flag?

**Comment by tomponline** [comment]
You should not modify 'volatile.eth0.host_name' instead set 'hostname' on the device config.

**Comment by Kramerican** [comment]
@tomponline the way this is set is with:

`lxc config device set containername eth0 host_name=somename`

So, we are not setting that key explicitly and are indeed just setting hostname on the device.

without --expanded:

```
architecture: x86_64
config:
  image.description: Ubuntu Focal LEMP PHP 8.0
  security.nesting: "true"
  volatile.base_image: 4c4e30cd2126fe01cbc63e2438fd28710f93262d7671a5f19968458b12a2f56c
  volatile.eth0.host_name: veXcheckmila
  volatile.eth0.hwaddr: 00:16:3e:89:7d:65
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    host_name: veXcheckmila
    limits.egress: 800Mbit
    limits.ingress: 800Mbit
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
ephemeral: false
profiles:
- largeprofile
stateful: false
description: ""
```

**Comment by stgraber** [comment]
What does `tc qdisc show` look like?

**Comment by tomponline** [comment]
This shoes the limit is applied in the instance config, and not from the profile, so it will override any profile config.


To my knowledge you cannot partially override a devices config, its all or nothing.

**Comment by webdock-io** [comment]
@tomponline OK so what you are saying that because we set the host name individually on a container, that "locks in" the eth0 config and makes it so that profiles cannot change the limits? This should make things clearer. This is LXD v4.21:

```
# created a brand new profile and set some stuff
# lxc profile show testbandwidth
config:
  boot.autostart: "false"
  limits.cpu: "4"
  limits.cpu.allowance: 5%
  limits.kernel.memlock: "67108864"
  limits.memory: 2GB
  limits.memory.enforce: hard
  linux.kernel_modules: ip_tables,ip6_tables
description: ""
devices:
  eth0:
    limits.egress: 50Mbit
    limits.ingress: 50Mbit
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    limits.read: 4000iops
    limits.write: 1000iops
    path: /
    pool: lxd
    size: 25GB
    type: disk
name: testbandwidth
used_by: []

# Create a new container, set the veth hostname
lxc launch ubuntu:focal testcontainer --profile testbandwidth
lxc config device override testcontainer eth0 host_name=myvethname

# config show - note how the ingress and egress is listed here as well which is what I believe you are talking about in your reply
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20211129)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20211129"
  image.type: squashfs
  image.version: "20.04"
  volatile.apply_template: create
  volatile.base_image: a8402324842148ccfcbacbc69bf251baa9703916593089f0609e8d45e3185bff
  volatile.eth0.hwaddr: 00:16:3e:c9:96:63
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
devices:
  eth0:
    host_name: myvethname
    limits.egress: 50Mbit
    limits.ingress: 50Mbit
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
ephemeral: false
profiles:
- testbandwidth
stateful: false
description: ""

```

And indeed, after setting a new profile, the config shows the same - which makes sense, sort of - except I'd really just expect the override to just set the host_name and not all the other eth0 settings:

```
...
devices:
  eth0:
    host_name: myvethname
    limits.egress: 50Mbit
    limits.ingress: 50Mbit
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
ephemeral: false
profiles:
- largeprofile
...

```
But, this is a bit of a catch-22 for me. We need to set the hostname on a container by container basis, and by touching that we "lock in" any other settings for eth0 making it impossible for a profile change to change anything already set. Hmm...

What would be a better way of doing this, if any, if I want to be able to just change profiles for a container? Would I need to unset the eth0 config and then apply the profile, or something?

I guess this is not a bug after all as there is some underlying reason why overriding a single key makes it so that all other interface settings are transferred from the profile to the instance config?
