### ISSUE TITLE
Very unreliable `lxc exec` since 4.21

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#9734]
Ever since I switched to LXD 4.21, doing a large number of exec sessions, especially targeting at VMs has been quite unreliable.

I'll open more issues as I go through them, but for now, the most annoying one is a case where the exec session will just get stuck indefinitely. In this case, it's running something like:
```
lxc --project lxc exec mtl-cluster:buildd16 -- /bin/sh -c /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
```

As it's run with stdin/stdout/stderr with pipes or sockets, this will be operating in non-interactive mode.

This is run against a cluster which then forwards to the correct target. Nothing is running in the VM itself, likely the command having completed. Instead things are stuck like so:

```
goroutine 12196245 [chan send, 13 minutes]:
github.com/lxc/lxd/lxd/instance/drivers.(*qemuCmd).Signal(0x4000eb6040, 0x9)
        /build/lxd/parts/lxd/src/lxd/instance/drivers/driver_qemu_cmd.go:35 +0x54
main.(*execWs).Do.func3()
        /build/lxd/parts/lxd/src/lxd/instance_exec.go:272 +0x48
sync.(*Once).doSlow(0x4000d24040, 0x4000b72450)
        /snap/go/8843/src/sync/once.go:68 +0x108
sync.(*Once).Do(...)
        /snap/go/8843/src/sync/once.go:59
main.(*execWs).Do.func4(0x4001326450, 0x40011a4480, {0xffff6c73f658, 0x400205f5c0}, 0x4000d24040, 0x4000b72450, {0x1b64b58, 0x4000eb6040}, {0x4000da07c8, 0x3, ...})
        /build/lxd/parts/lxd/src/lxd/instance_exec.go:316 +0xdfc
created by main.(*execWs).Do
        /build/lxd/parts/lxd/src/lxd/instance_exec.go:282 +0xa98

goroutine 12194269 [semacquire, 13 minutes]:
sync.runtime_Semacquire(0x4001326458)
        /snap/go/8843/src/runtime/sema.go:56 +0x38
sync.(*WaitGroup).Wait(0x4001326450)
        /snap/go/8843/src/sync/waitgroup.go:130 +0xa4
main.(*execWs).Do.func2(0x0, {0x0, 0x0})
        /build/lxd/parts/lxd/src/lxd/instance_exec.go:247 +0x1fc
main.(*execWs).Do(0x40011a4480, 0x40002c90e0)
        /build/lxd/parts/lxd/src/lxd/instance_exec.go:442 +0xce0
github.com/lxc/lxd/lxd/operations.(*Operation).Run.func1(0x40002c90e0, 0x400077ac00)
        /build/lxd/parts/lxd/src/lxd/operations/operations.go:270 +0x38
created by github.com/lxc/lxd/lxd/operations.(*Operation).Run
        /build/lxd/parts/lxd/src/lxd/operations/operations.go:269 +0x10c
```

Tracking down the line numbers, we're stuck on:

```
// Signal sends a signal to the command.
func (c *qemuCmd) Signal(sig unix.Signal) error {
    command := api.InstanceExecControl{
        Command: "signal",
        Signal:  int(sig),
    }

    c.controlSendCh <- command
    err := <-c.controlResCh
    if err != nil {
        return err
    }

    logger.Debugf(`Forwarded signal "%d" to lxd-agent`, sig)
    return nil
}
```

Specifically, we're stuck on the `c.controlSendCh <- command`.
It's looking like the handler which is supposed to process those messages just isn't running or isn't picking up anything.

This then causes the `Signal()` call to get stuck indefinitely, holding the entire exec session.

**Comment by stgraber** [comment]
@tomponline I read through a bunch of the code but haven't dived quite deep enough to understand all of the handler stuff in there :)

**Comment by tomponline** [comment]
OK will take a look perhaps the process has ended before the signal is sent.

**Comment by tomponline** [comment]
Do you see any warning level messages like "Unexpected read on stdout websocket, killing command" in the logs?

**Comment by tomponline** [comment]
Actually looks like an issue handling abnormal closure of the websocket connections.

**Comment by stgraber** [comment]
I'm logging at INFO level on this machine and I'm not seeing anything relevant in the log.
Also not seeing any error on the agent side, just the command it was sent.

**Comment by stgraber** [comment]
Tiny bit of extra captured details:
```
root@delmak:~# lxc operation show --project lxc b5f2c6be-ac5f-4f4c-95ca-fef86f409fa1
id: b5f2c6be-ac5f-4f4c-95ca-fef86f409fa1
class: websocket
description: Executing command
created_at: 2022-01-01T19:06:10.336974595Z
updated_at: 2022-01-01T19:06:10.336974595Z
status: Running
status_code: 103
resources:
  instances:
  - /1.0/instances/buildd16
metadata:
  command:
  - /bin/sh
  - -c
  - /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"';
    command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"';
    command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"';
    command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND
    && sleep 0'
  environment:
    HOME: /root
    LANG: C.UTF-8
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    TERM: screen
    USER: root
  fds:
    "0": adad8cd1dc7de69cdf5c758bef9ac174219d3589535690b3540b616f230b37b7
    "1": ad05d78bc53bffc59a269f09220f7d6acd4709a530090f6320d7537763c96d09
    "2": 522cd2b6e5bf08adf55aa7b281ef9b6e708f8356f53c96b205b3391edd8de8ba
    control: 88c6af146d92e1a4ceee620f1fbef4eec8958b9c1274a484112ea24d7afe1bf9
  interactive: false
may_cancel: false
err: ""
location: delmak
```
