### ISSUE TITLE
Broken TCP egress when same address is used for network NAT and forward (OVN)

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#9765]
Given the following network:
```
stgraber@dakara:~$ lxc network show default
config:
  bridge.mtu: "1500"
  ipv4.address: 10.66.241.1/24
  ipv4.nat: "true"
  ipv4.nat.address: 45.45.148.225
  ipv6.address: 2602:fc62:ee:8100::1/64
  ipv6.nat: "false"
  network: UPLINK
  volatile.network.ipv4.address: 172.16.1.1
  volatile.network.ipv6.address: 2602:fc62:ee:201:1::2
```

Along with a forward on the same address:
```
stgraber@dakara:~$ lxc network forward show default 45.45.148.225
description: Main IPv4 address
config:
  target_address: 10.66.241.4
ports:
- description: ""
  protocol: tcp
  listen_port: "10143"
  target_port: "22"
  target_address: 10.66.241.6
```

Traffic coming out of the instances gets the correct egress address through NAT but traffic coming back in seems to bypass the stateful NAT table and only hit the OVN load-balancer which then rejects the traffic with ICMP time exceeded.

Example:
```
16:01:12.265624 IP 45.45.148.225.53534 > 162.159.137.232.80: Flags [S], seq 3448107389, win 64240, options [mss 1460,sackOK,TS val 1111806197 ecr 0,nop,wscale 7], length 0
16:01:12.283019 IP 162.159.137.232.80 > 45.45.148.225.53534: Flags [S.], seq 830830838, ack 3448107390, win 65535, options [mss 1400,nop,nop,sackOK,nop,wscale 10], length 0
16:01:12.297670 IP 172.16.1.1 > 162.159.137.232: ICMP time exceeded in-transit, length 60
16:01:13.269738 IP 45.45.148.225.53534 > 162.159.137.232.80: Flags [S], seq 3448107389, win 64240, options [mss 1460,sackOK,TS val 1111807202 ecr 0,nop,wscale 7], length 0
16:01:13.287219 IP 162.159.137.232.80 > 45.45.148.225.53534: Flags [S.], seq 830830838, ack 3448107390, win 65535, options [mss 1400,nop,nop,sackOK,nop,wscale 10], length 0
16:01:14.332662 IP 162.159.137.232.80 > 45.45.148.225.53534: Flags [S.], seq 830830838, ack 3448107390, win 65535, options [mss 1400,nop,nop,sackOK,nop,wscale 10], length 0
```

**Comment by tomponline** [comment]
Reproduced this locally with Focal OVN packages:

Uplink network (connecting to lxdbr0):
```
lxc network show uplink
config:
  ipv4.gateway: 10.250.73.1/24
  ipv4.ovn.ranges: 10.250.73.20-10.250.73.29
  ipv4.routes: 10.0.0.0/24
  ipv6.gateway: fd42:bbc6:269a:23f5::1/64
  ovn.ingress_mode: routed
  parent: lxdbr0
  volatile.last_state.created: "false"
description: ""
name: uplink
type: physical
used_by:
- /1.0/networks/ovn1
```

OVN network connected to uplink network:
```
lxc network show ovn1
config:
  bridge.mtu: "1500"
  ipv4.address: 10.119.126.1/24
  ipv4.nat: "true"
  ipv4.nat.address: 10.0.0.1
  ipv6.address: fd42:3bdd:ca94:3c86::1/64
  ipv6.nat: "true"
  network: uplink
  volatile.network.ipv4.address: 10.250.73.20
  volatile.network.ipv6.address: fd42:bbc6:269a:23f5:216:3eff:fe78:a78d
description: ""
name: ovn1
type: ovn
```

Add manual static route for 10.0.0.0/24 towards OVN virtual router's IP on uplink network:

```
sudo ip r add 10.0.0.0/24 via 10.250.73.20 dev lxdbr0
```

Launch container connected to OVN network:
```
lxc launch images:ubuntu/focal c1 -n ovn1
lxc ls
+------+---------+---------------------+-----------------------------------------------+-----------+-----------+
| NAME |  STATE  |        IPV4         |                     IPV6                      |   TYPE    | SNAPSHOTS |
+------+---------+---------------------+-----------------------------------------------+-----------+-----------+
| c1   | RUNNING | 10.119.126.2 (eth0) | fd42:3bdd:ca94:3c86:216:3eff:fe65:61e8 (eth0) | CONTAINER | 0         |
+------+---------+---------------------+-----------------------------------------------+-----------+-----------+
```

Check egress TCP traffic works OK without forwarder:

```
lxc exec c1 -- apt install curl nginx -y
lxc exec c1 -- curl -I https://www.linuxcontainers.org -4 -m 5
HTTP/1.1 301 Moved Permanently
server: nginx/1.18.0 (Ubuntu)
date: Wed, 02 Mar 2022 12:50:05 GMT
content-type: text/html
content-length: 178
location: https://linuxcontainers.org/
```

Now add a network forward listening on same IP as the `ipv4.nat.address` of the OVN network, with a default target (it can be to any IP in the OVN network), in this case I am forwarding all traffic to the container we created earlier.

```
lxc network forward create ovn1 10.0.0.1 target_address=10.119.126.2
```

Now test that egress TCP is broken:

```
lxc exec c1 -- curl -I https://www.linuxcontainers.org -4 -m 5
curl: (28) Connection timed out after 5001 milliseconds
```

Check ingress forward is working towards nginx on c1:

```
curl -I http://10.0.0.1 -m 5
HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Wed, 02 Mar 2022 12:54:30 GMT
Content-Type: text/html
Content-Length: 612
Last-Modified: Wed, 02 Mar 2022 12:39:43 GMT
Connection: keep-alive
ETag: "621f658f-264"
Accept-Ranges: bytes
```

Disable forwarder and check egress works again:

```
lxc network forward unset ovn1 10.0.0.1 target_address
lxc exec c1 -- curl -I https://www.linuxcontainers.org -4 -m 5
HTTP/1.1 301 Moved Permanently
server: nginx/1.18.0 (Ubuntu)
date: Wed, 02 Mar 2022 12:55:05 GMT
content-type: text/html
content-length: 178
location: https://linuxcontainers.org/
```

Re-enable forward and gather OVN setup:

```
lxc network forward set ovn1 10.0.0.1 target_address=10.119.126.2
```

SNAT entry:
```
sudo ovn-nbctl list nat
_uuid               : 2a773658-3f15-4ef3-9c6c-d2654e0edd62
external_ids        : {}
external_ip         : "10.0.0.1"
external_mac        : []
logical_ip          : "10.119.126.0/24"
logical_port        : []
options             : {stateless="false"}
type                : snat
```

Forwarded (load balancer) entry:

```
sudo ovn-nbctl list load_balancer
_uuid               : 0fe0d8da-407c-4aca-b4f3-d54b7a895ca4
external_ids        : {}
health_check        : []
ip_port_mappings    : {}
name                : lxd-net39-lb-10.0.0.1-tcp
protocol            : tcp
vips                : {"10.0.0.1"="10.119.126.2"}
```
