### ISSUE TITLE
lxc restart deletes any DROP ebtables rules for named interface

### ISSUE THREAD

**Issue by webdock-io** [lxc/lxd#9923]
This is seen on LXD v4.22

As we've kept working on our anti-spoof measures following our discussion in https://github.com/lxc/lxd/issues/9728 an interesting issue has shown up. Issuing an lxc restart of a container where networking **is not** being managed by LXD causes LXD to delete any ebtables rules with the "DROP" directive in the ebtables forward chain.

I am guessing this is some cleanup code related to where LXD is managing bridges, or something like that.

In any case, it's easy to reproduce. Name the container interface (host_name) on a bridge which is not managed by LXD. Add some ebtables rules, for example our updated anti-spoof rules:

```
/usr/sbin/ebtables -A FORWARD -p ARP -i ".$ctif." --arp-ip-src ".$ipv4." -j ACCEPT
/usr/sbin/ebtables -A FORWARD -p ARP -i ".$ctif." --arp-ip-dst ".$ipv4." -j ACCEPT
/usr/sbin/ebtables -A FORWARD -p ARP -i ".$ctif." -j DROP
```

List the rules with `ebtables -L` and they will all be present and correct - issue `lxc restart` and you will notice the last DROP rule has now been deleted, defeating the purpose of the rules.

This really feels like a bug as LXD shouldn't be messing with ebtables at all in this case.

**Comment by tomponline** [comment]
Please show `lxc config show <instance> --expanded` for the affected instance.

**Comment by webdock-io** [comment]
Sure

```
architecture: x86_64
config:
  boot.autostart: "false"
  image.description: Webdock Ubuntu Focal LEMP PHP 8.0
  limits.cpu: "20"
  limits.cpu.allowance: 25%
  limits.kernel.memlock: "67108864"
  limits.memory: 10GB
  limits.memory.enforce: hard
  linux.kernel_modules: ip_tables,ip6_tables
  security.nesting: "true"
  volatile.base_image: 20800999bec103d03d78bc31e6d7b0d116890b20403a0a9d099d13be6cf1f6a7
  volatile.eth0.host_name: veXstagingtest
  volatile.eth0.hwaddr: 00:16:3e:c5:9b:21
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 07a9e2eb-222b-4e0b-962a-6eea55545993
devices:
  eth0:
    host_name: veXstagingtest
    limits.egress: 800Mbit
    limits.ingress: 800Mbit
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    limits.read: 4000iops
    limits.write: 1000iops
    path: /
    pool: lxd
    size: 100GB
    type: disk
  tun:
    path: /dev/net/tun
    type: unix-char
ephemeral: false
profiles:
- webdockpro
stateful: false
description: ""
```
