### ISSUE TITLE
cannot start guest Error: Failed to start device "eth0": ipv4.address "x.x.x.x" is already in use

### ISSUE THREAD

**Issue by aqueos** [lxc/lxd#9940]
# Required information

 * Distribution: Ubuntu 20.04.3 LTS
 * Distribution version: 20.04.3 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.11.0
   * LXC version: lxd snap 4.22
   * LXD version:lxd     4.22      22358  4.22/stable    canonical✓  -
   * Storage backend in use: btrfs

was working fine, there have been upgrade to 4.23 and nothing worked, we switch back to 4.22 but this is still not working. ip are routed mode

```
devices:
  eth0:
    host_name: test02
    ipv4.address: 156.12.65.181
    limits.max: 100Mibit
    name: eth0
    nictype: routed
    parent: eth1
    type: nic

```
```
LXDHOST:root@lxdserver01:[~]: lxc stop test02
LXDHOST:root@lxdserver01:[~]: lxc start test02
Error: Failed to start device "eth0": ipv4.address "156.12.65.181" is already in use
Try `lxc info --show-log test02` for more info
```

# Issue description

starting a new guest or restarting an old one fails with ip allready used

```
LXDHOST:root@lxdserver01:[~]: ifconfig |grep ubun
LXDHOST:root@lxdserver01:[~]: ip addr ls|grep 156.12.65.184
LXDHOST:root@lxdserver01:[~]: lxc start ubuntuguest 
Error: Failed to start device "eth0": ipv4.address "156.12.65.184" is already in use
Try `lxc info --show-log ubuntuguest` for more info
LXDHOST:root@lxdserver01:[~]: lxc info --show-log ubuntuguest
Name: ubuntuguest
Status: STOPPED
Type: container
Architecture: x86_64
Created: 2022/02/18 08:29 CET

Log:


LXDHOST:root@lxdserver01:[~]: uname -a
Linux lxdserver01.myserver.net 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

# Steps to reproduce
create a guest, try to start it. or take an existing guest an try to stop start it.

# Information to attach

nothing in the logs

```
LXDHOST:root@lxdserver01:[~]: lxc config show --expanded ubuntuguest
architecture: x86_64
config:
  boot.autostart: "true"
  image.architecture: amd64
  image.description: Ubuntu bionic amd64 (20220217_07:43)
  image.os: Ubuntu
  image.release: bionic
  image.serial: "20220217_07:43"
  image.type: squashfs
  image.variant: default
  limits.cpu: "4"
  limits.memory: 12GiB
  limits.processes: "10000"
  security.devlxd: "false"
  security.idmap.isolated: "true"
  security.nesting: "true"
  security.protection.delete: "true"
  volatile.apply_template: create
  volatile.base_image: 4f120b3e98591f7549cf88f0dd5792c33511c000cdf24ed2d13f0fcf052ec4b6
  volatile.eth0.hwaddr: 00:16:3e:34:1c:97
  volatile.idmap.base: "1589824"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1589824,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1589824,"Nsid":0,"Maprange":65536}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1589824,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1589824,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1589824,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1589824,"Nsid":0,"Maprange":65536}]'
  volatile.uuid: 52807a2e-0db2-4945-820c-193f78b946b7
devices:
  eth0:
    host_name: serveur
    ipv4.address: 156.12.65.184
    limits.max: 100Mibit
    name: eth0
    nictype: routed
    parent: eth1
    type: nic
  root:
    path: /
    pool: GUEST
    size: 240GiB
    type: disk
ephemeral: false
profiles:
stateful: false
description: ""
```

 for now we cannot find any reason to it so we post it has a bug here. Prior to that all worked fine. I dont know if this was the upgrade in 4.23 that caused the issue.

  reverting to 4.22 did not change anything, guest cannot be restarted or created :(

regards,
Ghislain.
