### ISSUE TITLE
Failed to start container and failed to remove device

### ISSUE THREAD

**Issue by jemail99** [lxc/lxd#9965]
# Required information

 * Distribution: Armbian Focal Linux 5.10.81-meson64 21.08.6 SMP PREEMPT aarch64 aarch64 aarch64 GNU/Linux
 * Distribution version:
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: Client version: 4.23 Server version: 4.23
   * LXD version: 4.23
   * Storage backend in use: btrfs

# Issue description

Container failed to start today with:
```lxc start alpine-calendar-server
Error: Failed to start device "alpine-calendar-share-ssl-acme.sh": Name can only contain alphanumeric and hyphen characters
Try `lxc info --show-log alpine-calendar-server` for more info
```
```
lxc info --show-log alpine-calendar-server
Name: alpine-calendar-server
Status: STOPPED
Type: container
Architecture: aarch64
Created: 2021/11/21 15:25 CET
Last Used: 2022/02/23 02:01 CET

Snapshots:
+--------------------------------------------+----------------------+------------+----------+
|                    NAME                    |       TAKEN AT       | EXPIRES AT | STATEFUL |
+--------------------------------------------+----------------------+------------+----------+
| alpine-calendar-server-2021-11-21_15.25.44 | 2021/11/21 15:26 CET |            | NO       |
+--------------------------------------------+----------------------+------------+----------+
| alpine-calendar-server-2021-11-25_23.21.49 | 2021/11/25 23:21 CET |            | NO       |
+--------------------------------------------+----------------------+------------+----------+
| lxd-snapper-20211202-143126                | 2021/12/02 15:31 CET |            | NO       |
+--------------------------------------------+----------------------+------------+----------+
| lxd-snapper-20211222-183245                | 2021/12/22 19:32 CET |            | NO       |
+--------------------------------------------+----------------------+------------+----------+

Log:

```
Attempt to remove the device (share) results in:
```
lxc config device remove alpine-calendar-server alpine-calendar-share-ssl-acme.sh
Error: Failed to remove device "alpine-calendar-share-ssl-acme.sh": Device remove validation failed for "alpine-calendar-share-ssl-acme.sh": Name can only contain alphanumeric and hyphen characters
```
```
lxc config show alpine-calendar-server --expanded
architecture: aarch64
config:
  boot.autostart: "true"
  image.architecture: arm64
  image.description: Alpine 3.14 arm64 (20211120_13:00)
  image.os: Alpine
  image.release: "3.14"
  image.serial: "20211120_13:00"
  image.type: squashfs
  image.variant: default
  raw.idmap: |-
    uid 1000-1002 1000-1002
    gid 1005 1005
  volatile.base_image: 351b6564e8c5e892c979e118c760477518d8e8f554bd36b51e3817675ad21f63
  volatile.eth0.hwaddr: 00:16:3e:7f:54:21
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":3},{"Isuid":true,"Isgid":false,"Hostid":1001003,"Nsid":1003,"Maprange":999998997},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1005},{"Isuid":false,"Isgid":true,"Hostid":1005,"Nsid":1005,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1001006,"Nsid":1006,"Maprange":999998994}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":3},{"Isuid":true,"Isgid":false,"Hostid":1001003,"Nsid":1003,"Maprange":999998997},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1005},{"Isuid":false,"Isgid":true,"Hostid":1005,"Nsid":1005,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1001006,"Nsid":1006,"Maprange":999998994}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000},{"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":3},{"Isuid":true,"Isgid":false,"Hostid":1001003,"Nsid":1003,"Maprange":999998997},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1005},{"Isuid":false,"Isgid":true,"Hostid":1005,"Nsid":1005,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1001006,"Nsid":1006,"Maprange":999998994}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 07c492e3-f43c-4d6b-b6f1-5d8a6719cae6
devices:
  alpine-calendar-share-ssl-acme.sh:
    path: /etc/ssl/acme.sh/
    source: /etc/ssl/acme.sh/
    type: disk
  eth0:
    name: eth0
    nictype: macvlan
    parent: eth0
    type: nic
  root:
    path: /
    pool: titanium-btrfs
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
# Steps to reproduce
Attempt to start container produces result described above

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`) see above
 - [x] Container configuration (`lxc config show NAME --expanded`) see above
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
[lxc-info.txt](https://github.com/lxc/lxd/files/8130222/lxc-info.txt)
