### ISSUE TITLE
Random MAC address after a reboot in the container

### ISSUE THREAD

**Issue by domosekai** [lxc/lxd#9980]
# Required information

 * Distribution: Debian
 * Distribution version: 11.2
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.10.0-11-amd64
   * LXC version: 4.0.12
   * LXD version: 4.23 22525 (snap)
   * Storage backend in use: btrfs

# Issue description

I am using a Ubuntu 21.10 container on a Debian 11 host. The NIC type is macvlan and there is a fixed MAC address set by `volatile.eth0.hwaddr`. Usually it works fine but sometimes after a reboot within the container (by `reboot`) results in a different and random MAC address getting assigned.
The weird thing is that it does not happen every time (about 20% chance). Any idea what might be going wrong or how I can dig further?

# Steps to reproduce

 1. Connect to the container via SSH
 2. Execute `reboot`

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [X] Container log (`lxc info NAME --show-log`)
**Note the wrong MAC address `12:90:31:f3:66:3d` instead of `00:16:3e` as in the config.**
```
Name: name
Status: RUNNING
Type: container
Architecture: x86_64
PID: 1025096
Created: 2020/07/31 01:37 CST
Last Used: 2022/03/01 17:19 CST

Resources:
  Processes: 53
  CPU usage:
    CPU usage (in seconds): 14
  Memory usage:
    Memory (current): 98.27MiB
  Network usage:
    eth0:
      Type: broadcast
      State: UP
      Host interface: enp1s0
      MAC address: 12:90:31:f3:66:3d
      MTU: 1500
      Bytes received: 20.43kB
      Bytes sent: 13.64kB
      Packets received: 86
      Packets sent: 112
      IP addresses:
        inet:  192.168.118.86/24 (global)
        inet6: 2408:xx:xx:xx:1090:31ff:fef3:663d/64 (global)
        inet6: fe80::1090:31ff:fef3:663d/64 (link)
    lo:
      Type: loopback
      State: UP
      MTU: 65536
      Bytes received: 1.66kB
      Bytes sent: 1.66kB
      Packets received: 18
      Packets sent: 18
      IP addresses:
        inet:  127.0.0.1/8 (local)
        inet6: ::1/128 (local)

Log:

lxc name 20220301091922.231 WARN     conf - conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc name 20220301091922.232 WARN     conf - conf.c:lxc_map_ids:3598 - newgidmap binary is missing
lxc name 20220301091922.233 WARN     conf - conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc name 20220301091922.234 WARN     conf - conf.c:lxc_map_ids:3598 - newgidmap binary is missing
```
 - [X] Container configuration (`lxc config show NAME --expanded`)
 ```
architecture: x86_64
config:
  boot.autostart: "true"
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20200720)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20200720"
  image.type: squashfs
  image.version: "20.04"
  limits.cpu: "2"
  limits.memory: 3GiB
  volatile.base_image: 0a4f3d88ed1c0e0d34c0f1e9be71b5dd73dc3de81a1e139b0ecd4e0faa958a30
  volatile.eth0.host_name: macbdxxxxxx
  volatile.eth0.hwaddr: 00:16:3e:xx:xx:xx
  volatile.eth0.last_state.created: "false"
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 33c9xxxx
devices:
  eth0:
    nictype: macvlan
    parent: enp1s0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
   No relevant log before and after the reboot.
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment]
@tomponline may have some idea.

My initial guess would be that the kernel didn't fully delete the previous device and as it enforces that no duplicate address may exist on the parent device, you're getting a random address from the kernel instead.

**Comment by tomponline** [comment]
So if you try and create a new macvlan interface and then set its MAC address to a MAC address already used by an existing macvlan device on the parent interface it will fail with `RTNETLINK answers: Address already in use` which would prevent the instance from starting here: https://github.com/lxc/lxd/blob/master/lxd/device/nic_macvlan.go#L189

However there is nothing stopping the network configuration system running inside the instance from setting a different MAC address after LXD has started it. So I wonder if something inside the instance that is changing the MAC.

What is the MAC your seeing inside the instance?

**Comment by domosekai** [comment]
Thanks for your replies.
So what you are saying is that since the container got started, there should not have been a duplicate address error. 
FYI, the MAC inside the instance is the same as shown in `lxc info NAME --show-log`. That is, the random one, `12:90:31:f3:66:3d`.
I say it's random because I've seen totally different addresses from time to time.
```
~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
15: eth0@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 12:90:31:f3:66:3d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.118.86/24 brd 192.168.118.255 scope global dynamic eth0
       valid_lft 3902sec preferred_lft 3902sec
    inet6 2408:xx:xx:xx:1090:31ff:fef3:663d/64 scope global dynamic mngtmpaddr noprefixroute
       valid_lft 172775sec preferred_lft 172775sec
    inet6 fe80::1090:31ff:fef3:663d/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by domosekai** [comment]
Could it be the case that if a duplicate MAC address is set, the system assigns a random one instead of returning an error?

**Comment by tomponline** [comment]
> Could it be the case that if a duplicate MAC address is set, the system assigns a random one instead of returning an error?

From my experiments (please can you try them also) if you set a macvlan's MAC address to a MAC address already used by an existing macvlan device on the parent interface it will fail with RTNETLINK answers: Address already in use.

e.g. inside the container run `ip link set eth0 address <duplicate mac address>`

**Comment by tomponline** [comment]
> I tried in the container and yes, an address-in-use error is throwed.

OK so if LXD had tried to do the same it would have prevented the instance from starting.

**Comment by tomponline** [comment]
`lxc config device set name eth0 hwaddr=00:16:3e:7a:5a:e0`

**Comment by domosekai** [comment]
Wow. Setting MAC address directly on the device seems the right fix. I did 15 reboots and the address has stayed the same.

**Comment by domosekai** [comment]
The current configuration:
```
~# lxc config show name
architecture: x86_64
config:
  boot.autostart: "true"
  image.architecture: amd64
  image.description: ubuntu 20.04 LTS amd64 (release) (20200720)
  image.label: release
  image.os: ubuntu
  image.release: focal
  image.serial: "20200720"
  image.type: squashfs
  image.version: "20.04"
  limits.cpu: "2"
  limits.memory: 3GiB
  volatile.base_image: 0a4f3d88ed1c0e0d34c0f1e9be71b5dd73dc3de81a1e139b0ecd4e0faa958a30
  volatile.eth0.host_name: mac4982f7d3
  volatile.eth0.last_state.created: "false"
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 33c9b14d-
devices:
  eth0:
    hwaddr: 00:16:3e:7a:5a:e0
    nictype: macvlan
    parent: enp1s0
    type: nic
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
